Repository matrixorigin/matrixone, pull requests merged in 2021-12, with the labels that each got.

#1255 [AOE] Change LogIndex structure for storing raft term
  pkg/vm/driver/aoe/storage.go
  pkg/vm/engine/aoe/storage/aoedb/v1/ctx.go
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
  pkg/vm/engine/aoe/storage/wal/shard/index.go
Labels: component/aoe, priority/high, kind/refactor, reviewed

#1263 Update readme
  README.md
Labels: kind/documentation

#1273 fix snapshot data rebuild bug
  pkg/vm/engine/aoe/storage/metadata/v1/block.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1272 [AOE] Optimization for building zone map on PK & small code refactor
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
  pkg/vm/engine/aoe/storage/layout/index/segzonemap.go
Labels: kind/enhancement, component/aoe, kind/refactor, reviewed

#1274 [AOE] Fix potential inconsistency in indices operations
  pkg/vm/engine/aoe/storage/aoedb/v1/db.go
Labels: kind/bug, component/aoe, reviewed

#1287 [AOE] Process one column at a time in segment writer & enable zone map by default
  pkg/vm/engine/aoe/mergesort/float32s/func.go
  pkg/vm/engine/aoe/mergesort/float64s/func.go
  pkg/vm/engine/aoe/mergesort/int16s/func.go
  pkg/vm/engine/aoe/mergesort/int32s/func.go
  pkg/vm/engine/aoe/mergesort/int64s/func.go
  pkg/vm/engine/aoe/mergesort/int8s/func.go
  pkg/vm/engine/aoe/mergesort/mergesort.go
  pkg/vm/engine/aoe/mergesort/uint16s/func.go
  pkg/vm/engine/aoe/mergesort/uint32s/func.go
  pkg/vm/engine/aoe/mergesort/uint64s/func.go
  pkg/vm/engine/aoe/mergesort/uint8s/func.go
  pkg/vm/engine/aoe/mergesort/varchar/func.go
  pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
  pkg/vm/engine/aoe/storage/db/sched/flushseg.go
  pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
  pkg/vm/engine/aoe/storage/layout/iterator/iface/types.go
  pkg/vm/engine/aoe/storage/layout/table/v1/blkiter.go
Labels: kind/enhancement, component/aoe, kind/refactor

#1290 Integrate CUBE new API: support snapshot
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/aoe/storage_test.go
  pkg/vm/driver/aoe_shard_aware.go
  pkg/vm/driver/cube_driver.go
Labels: reviewed

#1292 add event listener
  pkg/vm/engine/aoe/storage/db/sched/scheduler.go
  pkg/vm/engine/aoe/storage/db/split.go
  pkg/vm/engine/aoe/storage/event/listeners.go
  pkg/vm/engine/aoe/storage/event/logging.go
  pkg/vm/engine/aoe/storage/event/types.go
  pkg/vm/engine/aoe/storage/options.go
Labels: kind/enhancement, component/aoe, priority/critical, severity/critical

#1300 [AOE] Support filters upon unclosed segment - phase 1
  pkg/vm/engine/aoe/storage/aoedb/v1/db.go
  pkg/vm/engine/aoe/storage/common/file.go
  pkg/vm/engine/aoe/storage/db/seg_test.go
  pkg/vm/engine/aoe/storage/layout/dataio/colpart.go
  pkg/vm/engine/aoe/storage/layout/dataio/index.go
  pkg/vm/engine/aoe/storage/layout/index/blk.go
  pkg/vm/engine/aoe/storage/layout/index/index_test.go
  pkg/vm/engine/aoe/storage/layout/index/seg.go
  pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/index/tbl.go
  pkg/vm/engine/aoe/storage/layout/index/types.go
  pkg/vm/engine/aoe/storage/layout/index/unsortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/table/v1/baseblk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/blk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/col/stdblk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
  pkg/vm/engine/aoe/storage/layout/table/v1/seg.go
Labels: component/aoe, priority/critical, severity/major, kind/refactor

#1304 update event listener and related dependency
  pkg/vm/engine/aoe/storage/aoedb/v1/shard_test.go
  pkg/vm/engine/aoe/storage/db/split.go
  pkg/vm/engine/aoe/storage/event/listeners.go
  pkg/vm/engine/aoe/storage/event/logging.go
  pkg/vm/engine/aoe/storage/event/types.go
  pkg/vm/engine/aoe/storage/metadata/v1/database.go
Labels: component/aoe, priority/critical, kind/feature, severity/critical

#1312 Reading data fails in a multi environment
  cmd/db-server/main.go
Labels: reviewed

#1319 [AOE] Support filters upon unclosed segment - phase 2
  pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
  pkg/vm/engine/aoe/storage/db/segment_filter.go
  pkg/vm/engine/aoe/storage/db/segment_sparse_filter.go
  pkg/vm/engine/aoe/storage/layout/base/file.go
  pkg/vm/engine/aoe/storage/layout/dataio/blk.go
  pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
  pkg/vm/engine/aoe/storage/layout/dataio/blkwriter.go
  pkg/vm/engine/aoe/storage/layout/dataio/mockseg.go
  pkg/vm/engine/aoe/storage/layout/dataio/sortedseg.go
  pkg/vm/engine/aoe/storage/layout/dataio/unsortedseg.go
  pkg/vm/engine/aoe/storage/layout/index/blk.go
  pkg/vm/engine/aoe/storage/layout/index/blk_holder.go
  pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go
  pkg/vm/engine/aoe/storage/layout/index/helper.go
  pkg/vm/engine/aoe/storage/layout/index/index_test.go
  pkg/vm/engine/aoe/storage/layout/index/seg.go
  pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/index/tbl.go
  pkg/vm/engine/aoe/storage/layout/index/types.go
  pkg/vm/engine/aoe/storage/layout/index/unsortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/index/zonemap.go
  pkg/vm/engine/aoe/storage/layout/iterator/iface/types.go
  pkg/vm/engine/aoe/storage/layout/table/v1/baseblk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/blkiter.go
  pkg/vm/engine/aoe/storage/layout/table/v1/col/blk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
  pkg/vm/engine/aoe/storage/layout/table/v1/seg.go
Labels: component/aoe, priority/critical, kind/feature, severity/major, kind/refactor, reviewed

#1333 Add the RFC template
  docs/rfcs/00000000-template.md
  docs/rfcs/README.md
Labels: kind/documentation

#1335 add aoe overall design rfc
  docs/rfcs/20211210_aoe_overall_design.md
Labels: kind/documentation, priority/high, severity/major

#1321 define and implement whole split process: add catalog listener
  cmd/db-server/main.go
  pkg/catalog/catalog.go
  pkg/catalog/errors.go
  pkg/catalog/helper.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/helper.go
  pkg/vm/driver/kv/executor.go
Labels: reviewed

#1355 wait checkpointed in flush database
  pkg/vm/engine/aoe/storage/aoedb/v1/db.go
  pkg/vm/engine/aoe/storage/aoedb/v1/replay_test.go
  pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
  pkg/vm/engine/aoe/storage/db/impl.go
  pkg/vm/engine/aoe/storage/wal/shard/manager.go
  pkg/vm/engine/aoe/storage/wal/shard/proxy.go
Labels: kind/enhancement, component/aoe, priority/high, severity/major

#1358 snapshot enhancement
  pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
  pkg/vm/engine/aoe/storage/db/db.go
  pkg/vm/engine/aoe/storage/db/snapshot.go
  pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
  pkg/vm/engine/aoe/storage/metadata/v1/ctx.go
  pkg/vm/engine/aoe/storage/metadata/v1/entry.go
  pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
  pkg/vm/engine/aoe/storage/metadata/v1/snapshot.go
Labels: kind/enhancement, component/aoe, priority/critical, severity/critical

#1353 update SaveShardMetadata
  pkg/vm/driver/aoe/storage.go
Labels: reviewed

#1360 fix aoe&frontend ut and some build errors
  pkg/frontend/epochgc_test.go
  pkg/sort/asc/varchar/sort_test.go
  pkg/sort/desc/varchar/sort_test.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/test/storage_test.go
  pkg/vm/engine/aoe/cmd/demo/main.go
  pkg/vm/engine/aoe/cmd/read/main.go
  pkg/vm/engine/aoe/local/database.go
  pkg/vm/engine/aoe/local/engine.go
  pkg/vm/engine/aoe/local/relation.go
  pkg/vm/engine/pb/db.go
  pkg/vm/engine/pb/types.go
  pkg/vm/engine/spillEngine/block/block.go
  pkg/vm/engine/spillEngine/block/types.go
  pkg/vm/engine/spillEngine/engine.go
  pkg/vm/engine/spillEngine/kv/kv.go
  pkg/vm/engine/spillEngine/kv/types.go
  pkg/vm/engine/spillEngine/meta/meta.go
  pkg/vm/engine/spillEngine/meta/types.go
  pkg/vm/engine/spillEngine/relation.go
  pkg/vm/engine/spillEngine/segment/segment.go
  pkg/vm/engine/spillEngine/segment/types.go
  pkg/vm/engine/spillEngine/types.go
  pkg/vm/engine/tpEngine/block.go
  pkg/vm/engine/tpEngine/codec.go
  pkg/vm/engine/tpEngine/database.go
  pkg/vm/engine/tpEngine/engine.go
  pkg/vm/engine/tpEngine/key.go
  pkg/vm/engine/tpEngine/relation.go
  pkg/vm/engine/tpEngine/schema.go
  pkg/vm/engine/tpEngine/segment.go
  pkg/vm/engine/tpEngine/types.go
  pkg/vm/engine/tpEngine/util.go
Labels: component/aoe

#1389 fix bug for concurrent flush tblk
  pkg/vm/engine/aoe/storage/db/impl.go
  pkg/vm/engine/aoe/storage/mutation/blk.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1421 Bumped MatrixCube version
  go.mod
  go.sum
Labels: kind/bug, priority/high, size/s, severity/major

#1423 fix wrong index used for split
  pkg/vm/engine/aoe/storage/db/split.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1426 support split on incremental database after split check
  pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
  pkg/vm/engine/aoe/storage/db/split.go
  pkg/vm/engine/aoe/storage/metadata/v1/database.go
  pkg/vm/engine/aoe/storage/metadata/v1/split.go
Labels: kind/enhancement, component/aoe, priority/critical, severity/critical

#1451 provide AOE interface for create/drop index
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/local/relation.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/types.go
Labels: reviewed

#1458 [CONFIG] Support advertise rpc addresses parameters for pd
  cmd/generate-config/system_vars_def.toml
  go.mod
  go.sum
Labels: kind/documentation, kind/support

#1496 To build docker image
  optools/image_builder/Dockerfile
  optools/image_builder/entrypoint.sh
Labels: devops

#1513 Fix the bug that GetInitialStates gets expired metadata
  pkg/vm/driver/aoe/storage.go
Labels: reviewed

#1519 Add UT for split and snapshot
  go.mod
  go.sum
  optools/run_ut.sh
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/errors.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/aoe/storage_test.go
  pkg/vm/driver/cube_driver.go
  pkg/vm/driver/test/storage_test.go
  pkg/vm/driver/testutil/testutil.go
  pkg/vm/engine/aoe/engine/database.go
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/relation.go
Labels: reviewed

#1516 Config file verbose update(added some comments and deleted some internal and redundant parameters)
  cmd/generate-config/config_template.go
  cmd/generate-config/system_vars_def.toml
  docs/en/MatrixOne/Get-Started/set-up-matrixone.md
Labels: reviewed

#1541 disable v0.1.0 workflow scheduler
  .github/workflows/build_matrixone_0.1.0.yml
Labels: devops

#1534 refine interface split
  pkg/catalog/catalog.go
  pkg/vm/driver/aoe/helper.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/test/storage_test.go
Labels: reviewed

#1543 disable v0.1.0 workflow scheduler (#1541)
  .github/workflows/build_matrixone_0.1.0.yml
  optools/run_bvt.sh
Labels: devops

#1523 add function writeBatchToStorage threadNum log
  cmd/generate-config/system_vars_def.toml
  pkg/frontend/load.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
Labels: reviewed

#1552 fix interface RemoveShard
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/test/storage_test.go
Labels: reviewed

#1561 [AOE]Fix the bug that logstore hole entery is not handled when mo-server i…
  pkg/vm/engine/aoe/storage/db/replay_test.go
  pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1562 Bumped MatrixCube version
  go.mod
  go.sum
  pkg/frontend/test/types_mock.go
Labels: reviewed

#1546 Year function implementation with lookup tables
  pkg/container/types/date.go
Labels: reviewed

#1401 [AOE] Support filters upon unclosed segment - end
  pkg/vm/engine/aoe/storage/aoedb/v1/db.go
  pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
  pkg/vm/engine/aoe/storage/common/compare.go
  pkg/vm/engine/aoe/storage/common/filenames.go
  pkg/vm/engine/aoe/storage/db/replay.go
  pkg/vm/engine/aoe/storage/db/sched/flushblkidx.go
  pkg/vm/engine/aoe/storage/db/sched/flushseg.go
  pkg/vm/engine/aoe/storage/db/sched/flushsegidx.go
  pkg/vm/engine/aoe/storage/db/sched/scheduler.go
  pkg/vm/engine/aoe/storage/db/segment_filter.go
  pkg/vm/engine/aoe/storage/db/segment_sparse_filter.go
  pkg/vm/engine/aoe/storage/db/segment_summarizer.go
  pkg/vm/engine/aoe/storage/layout/dataio/blk.go
  pkg/vm/engine/aoe/storage/layout/dataio/blkwriter.go
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
  pkg/vm/engine/aoe/storage/layout/dataio/unsortedseg.go
  pkg/vm/engine/aoe/storage/layout/index/blk_holder.go
  pkg/vm/engine/aoe/storage/layout/index/numbsi.go
  pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/index/types.go
  pkg/vm/engine/aoe/storage/layout/index/unsortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/table/v1/blk.go
  pkg/vm/engine/aoe/storage/layout/table/v1/data.go
  pkg/vm/engine/aoe/storage/layout/table/v1/iface/types.go
  pkg/vm/engine/aoe/storage/layout/table/v1/tblk.go
Labels: kind/enhancement, component/aoe, priority/critical, kind/feature, kind/refactor, reviewed
