Repository matrixorigin/matrixone, pull requests merged in 2022-06, with the labels that each got.

#2741 Fix the bug that the file info expires when replay
  pkg/vm/engine/tae/dataio/segmentio/segment.go
Labels: reviewed, component/tae

#2704 fix unfold star bug and rewrite count(*) to starcount(col)
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_function.go
  pkg/sql/plan2/build_subquery.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/build_util.go
Labels: reviewed

#2750 fix bug 2739
  pkg/sql/plan2/build_util.go
Labels: reviewed

#2753 Fix cast function bug
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build_function.go
  proto/plan.proto
Labels: reviewed

#2752 support timestamp in tae stdVector
  pkg/vm/engine/tae/container/vector/stdvec.go
  pkg/vm/engine/tae/logstore/store/vfile.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: reviewed

#2740 add fileservice package
  go.mod
  go.sum
  pkg/fileservice/errors.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/init_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/io_entry_test.go
  pkg/fileservice/io_vector.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: reviewed

#2762 Adjust interface of engine for delete
  pkg/frontend/test/engine_mock.go
  pkg/sql/colexec2/deletion/deletion.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/local/relation.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tpe/engine/relation.go
  pkg/vm/engine/types.go
Labels: reviewed

#2754 Trigo functions migration
  pkg/sql/plan2/function/builtin/unary/sinh.go
  pkg/sql/plan2/function/builtin/unary/tan.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/plan2/function/function_id.go
Labels: reviewed

#2776 fix ut TestAddrVersion
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
Labels: reviewed

#2773 Update tae layout log's pagesize=512
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: reviewed, component/tae

#2779 Implement delete
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
Labels: reviewed, component/tae

#2788 Add read latency
  pkg/vm/engine/tae/moengine/reader.go
  pkg/vm/engine/tae/moengine/types.go
Labels: reviewed, component/tae

#2763 change args in case function
  pkg/sql/plan2/build_expr.go
Labels: reviewed

#2781 Catch all panics in mysql_cmd_executor
  pkg/frontend/mysql_cmd_executor.go
Labels: reviewed

#2793 implement GC logic for drop table and database
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/compound_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/helper.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scanner.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/mock.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/bug, kind/enhancement, kind/refactor, component/tae

#2804 Update ci.yml
  .github/workflows/ci.yml
Labels: reviewed

#2798 Deep copy expr
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_util.go
Labels: reviewed

#2802 (tae/hot fix): support decimal
  pkg/vm/engine/tae/common/compare.go
  pkg/vm/engine/tae/container/compute/utils.go
Labels: component/tae

#2801 Add tae layout's replay ut
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/layout/segment/segment.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: component/tae

#2805 Support delete
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec2/deletion/deletion.go
  pkg/sql/colexec2/deletion/types.go
  pkg/sql/compile2/compile.go
  pkg/sql/compile2/operator.go
  pkg/sql/compile2/types.go
  pkg/sql/plan2/build_delete.go
  proto/plan.proto
Labels: reviewed

#2809 (tae): fix checkpoint bug
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/scanner.go
Labels: kind/bug, component/tae

#2728 support date_add date_sub timestamp_add bulitin function
  log
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  pkg/container/types/datetime_test.go
  pkg/container/types/interval.go
  pkg/container/types/interval_test.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/function/builtin/unary/date_add.go
  pkg/sql/plan2/function/builtin/unary/date_sub.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/unittest/datatype_test.go
  pkg/vectorize/date_add/date_add.go
  pkg/vectorize/date_add/date_add_test.go
  pkg/vectorize/date_sub/date_sub.go
  pkg/vectorize/date_sub/date_sub_test.go
Labels: reviewed

#2810 Fix wal truncate
  pkg/vm/engine/tae/common/intervals.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/store/checker.go
  pkg/vm/engine/tae/logstore/store/file.go
  pkg/vm/engine/tae/logstore/store/file_test.go
  pkg/vm/engine/tae/logstore/store/history.go
  pkg/vm/engine/tae/logstore/store/replayer.go
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
  pkg/vm/engine/tae/logstore/store/types.go
  pkg/vm/engine/tae/logstore/store/vfile.go
  pkg/vm/engine/tae/logstore/store/vgroup.go
  pkg/vm/engine/tae/logstore/store/vinfo.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: reviewed

#2814 rewrite [in expr] to [or expr], [not in expr] to [and expr]
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_test.go
Labels: reviewed

#2794 Solve the cast function bug and unit test in plan2
  pkg/sql/plan2/function/operator/cast.go
  pkg/sql/plan2/function/operator/cast_test.go
  pkg/sql/plan2/function/operators.go
Labels: reviewed

#2820 (tae): support timestamp (part 1)
  pkg/vm/engine/tae/common/compare.go
  pkg/vm/engine/tae/container/compute/compute.go
  pkg/vm/engine/tae/container/compute/utils.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
Labels: kind/enhancement, component/tae

#2825 Add rows for WriteIBatch
  pkg/vm/engine/tae/dataio/segmentio/block.go
Labels: reviewed, component/tae

#2828 update ut and code refactor
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/dataio/mockio/segment_test.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block_test.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/file/segment.go
  pkg/vm/engine/tae/iface/file/types.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tables/table.go
  pkg/vm/engine/tae/tables/tables.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, kind/refactor, component/tae

#2837 Fix the bug of offset
  pkg/sql/colexec2/mergegroup/group.go
  pkg/sql/compile2/compile.go
  pkg/sql/plan2/function/aggregate.go
Labels: reviewed

#2840 Slove unaryMinus bug
  pkg/sql/plan2/function/operator/unaryops.go
  pkg/sql/plan2/function/operators.go
Labels: reviewed

#2833 fix issue#2795
  pkg/sql/plan2/function/builtin/unary/space.go
  pkg/sql/plan2/function/builtin/unary/space_test.go
  pkg/vectorize/space/space.go
Labels: reviewed

#2841 Segmentio code refactor
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/allocator.go
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
  pkg/vm/engine/tae/dataio/segmentio/extent.go
  pkg/vm/engine/tae/dataio/segmentio/file.go
  pkg/vm/engine/tae/dataio/segmentio/inode.go
  pkg/vm/engine/tae/dataio/segmentio/log.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/open.go
Labels: kind/refactor, reviewed, component/tae

#2845 add bool for tae mergesort
  pkg/vm/engine/tae/mergesort/bools/func.go
  pkg/vm/engine/tae/mergesort/bools/heap.go
  pkg/vm/engine/tae/mergesort/bools/sort.go
  pkg/vm/engine/tae/mergesort/bools/types.go
  pkg/vm/engine/tae/mergesort/mergesort.go
Labels: reviewed

#2847 fix timestamp|bool|decimal related type support in TAE and more ut and code refactor
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/generator.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/compute/hack.go
  pkg/vm/engine/tae/compute/hack_test.go
  pkg/vm/engine/tae/compute/mock.go
  pkg/vm/engine/tae/compute/utils.go
  pkg/vm/engine/tae/container/vector/stdvec.go
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/mtree.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/index/zonemap_test.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/memo.md
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mock/coldefs.go
  pkg/vm/engine/tae/model/blkview.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/bug, kind/enhancement, kind/refactor, component/tae

#2832 Fix incorrect behavior for handling write relation errors
  pkg/frontend/insert.go
Labels: reviewed

#2866 fix load and replay in logstore
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
  pkg/vm/engine/tae/logstore/store/types.go
  pkg/vm/engine/tae/logstore/store/vfile.go
  pkg/vm/engine/tae/logstore/store/vinfo.go
Labels: reviewed

#2874 fix bugs and update ut
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/common/id.go
  pkg/vm/engine/tae/common/id_test.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/container/vector/stdvec_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: kind/bug, component/tae

#2875 add statement latency panel to grafana dashboard
  pkg/util/metric/dashboard/grafana8.4_mo_overview.json
Labels: reviewed

#2876 add support to run show databases/tables/columns
  pkg/sql/compile2/compile.go
Labels: reviewed

#2869 Add missing error of const run
  pkg/vm/pipeline2/pipeline.go
Labels: reviewed

#2877 Refactoring pb generation tool
  Makefile
  pkg/pb/plan/plan.pb.go
  proto/Makefile
  proto/gen.sh
  proto/plan.proto
Labels: reviewed

#2878 (tae): update ut for sleep time
  pkg/vm/engine/aoe/storage/db/db.go
  pkg/vm/engine/tae/db/scheduler_test.go
Labels: component/tae

#2883 Use gogoproto
  pkg/pb/plan/plan.pb.go
  proto/gen.sh
  proto/plan.proto
Labels: reviewed

#2884 add resolveVariable
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/sql/plan2/mock.go
  pkg/sql/plan2/types.go
Labels: reviewed

#2830 merge columns without sort
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/mergesort/bools/func.go
  pkg/vm/engine/tae/mergesort/dates/func.go
  pkg/vm/engine/tae/mergesort/datetimes/func.go
  pkg/vm/engine/tae/mergesort/decimal128s/func.go
  pkg/vm/engine/tae/mergesort/decimal64s/func.go
  pkg/vm/engine/tae/mergesort/float32s/func.go
  pkg/vm/engine/tae/mergesort/float64s/func.go
  pkg/vm/engine/tae/mergesort/int16s/func.go
  pkg/vm/engine/tae/mergesort/int32s/func.go
  pkg/vm/engine/tae/mergesort/int64s/func.go
  pkg/vm/engine/tae/mergesort/int8s/func.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/timestamps/func.go
  pkg/vm/engine/tae/mergesort/uint16s/func.go
  pkg/vm/engine/tae/mergesort/uint32s/func.go
  pkg/vm/engine/tae/mergesort/uint64s/func.go
  pkg/vm/engine/tae/mergesort/uint8s/func.go
  pkg/vm/engine/tae/mergesort/varchar/func.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/wal/wal_test.go
Labels: reviewed

#2885 (tae): update Rows for system virtual table
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: component/tae

#2892 (tae): fix bug for load block
  pkg/vm/engine/tae/dataio/segmentio/block.go
Labels: kind/bug, reviewed, component/tae

#2893 (tae): fix some replay bugs
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/bug, reviewed, component/tae

#2897 fix many replay related bugs
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/logstore/store/replayer.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
  pkg/vm/engine/tae/wal/driver.go
Labels: kind/bug, component/tae

#2898 Add explain for case when expression
  pkg/sql/plan2/explain/explain_expr.go
  pkg/sql/plan2/explain/explain_test.go
Labels: reviewed

#2901 support more types for case-when operator
  pkg/sql/plan2/function/function.go
  pkg/sql/plan2/function/function_id.go
  pkg/sql/plan2/function/operator/case_when.go
  pkg/sql/plan2/function/operator/case_when_test.go
  pkg/sql/plan2/function/operator/if.go
  pkg/sql/plan2/function/operators.go
Labels: reviewed

#2910 fix issue#2906, plus result is wrong
  pkg/sql/plan2/function/operator/plus.go
Labels: reviewed

#2912 update for replay
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  pkg/vm/engine/tae/wal/driver.go
Labels: kind/bug, kind/enhancement, component/tae

#2916 fix testutil function bugs
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/testutil/testutil.go
Labels: reviewed

#2919 fix replay related bugs
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/dataio/segmentio/log.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/logstore/store/replayer.go
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/logstore/store/vfile.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
Labels: kind/bug, reviewed, component/tae

#2908 support date_add/sub("2010-01-01", interval 1 day)
  pkg/container/types/bytes.go
  pkg/container/types/interval.go
  pkg/sql/plan2/build_function.go
  pkg/sql/plan2/function/builtin/multi/date_add.go
  pkg/sql/plan2/function/builtin/multi/date_add_test.go
  pkg/sql/plan2/function/builtin/multi/date_sub.go
  pkg/sql/plan2/function/builtin/multi/date_sub_test.go
  pkg/sql/plan2/function/builtin/unary/month.go
  pkg/sql/plan2/function/builtin/unary/year.go
  pkg/sql/plan2/function/buitins.go
  pkg/vectorize/date_add/date_add.go
  pkg/vectorize/date_add/date_add_test.go
  pkg/vectorize/date_sub/date_sub.go
  pkg/vectorize/date_sub/date_sub_test.go
  pkg/vectorize/month/month.go
  pkg/vectorize/year/year.go
Labels: reviewed

#2917 add cast function unit test
  pkg/sql/plan2/function/operator/cast.go
  pkg/sql/plan2/function/operator/cast_test.go
  pkg/sql/plan2/function/operator/minus_test.go
Labels: reviewed

#2922 fix rtrim
  go.mod
  pkg/sql/plan2/function/builtin/unary/rtrim.go
  pkg/sql/plan2/function/builtin/unary/rtrim_test.go
  pkg/sql/testutil/testutil.go
  pkg/vectorize/rtrim/rtrim.go
  pkg/vectorize/rtrim/rtrim_test.go
Labels: reviewed

#2928 fix replay delete bugs
  pkg/vm/engine/tae/catalog/idalloc.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/stats.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: kind/bug, component/tae

#2934 Fix update file replay bug
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
Labels: component/tae

#2935 feature: add function concat_ws
  pkg/common/moerr/error.go
  pkg/sql/plan2/function/builtin/multi/concat_ws.go
  pkg/sql/plan2/function/builtin/multi/concat_ws_test.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/plan2/function/function.go
  pkg/sql/plan2/function/function_id.go
Labels: reviewed

#2891 Support default value for tae
  pkg/frontend/insert.go
  pkg/sql/compile2/scope.go
  pkg/sql/plan2/build_util.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
Labels: reviewed, component/tae

#2943 fix replay update related bugs and add more test cases
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
Labels: kind/bug, kind/enhancement, component/tae

#2947 (tae): fix replay catalog related bug
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/db/replay.go
Labels: kind/bug, component/tae

#2949 add log/ln/power/sin ut
  pkg/sql/plan2/function/builtin/binary/power_test.go
  pkg/sql/plan2/function/builtin/unary/ln_test.go
  pkg/sql/plan2/function/builtin/unary/log_test.go
  pkg/sql/plan2/function/builtin/unary/sin_test.go
Labels: reviewed

#2929 add decimal timestap into load
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/test/loadfile5
Labels: reviewed

#2950 fix the way to deal with NULL for acos
  pkg/sql/plan2/function/builtin/unary/acos.go
Labels: reviewed

#2939 Fix -0 problem in the float type(#2510)
  pkg/frontend/insert.go
Labels: reviewed

#2952 Add engine's interface of update for tae
  pkg/frontend/test/engine_mock.go
  pkg/sql/compile2/scope.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/local/relation.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
Labels: reviewed

#2959 fix MergeCheckpointInfo
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
Labels: reviewed

#2960 Fix default value serialization bug
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/replay_test.go
Labels: reviewed, component/tae

#2962 ingore colname check in some cases
  .github/workflows/ci.yml
Labels: reviewed

#2961 Support aggregate function any_value()
  pkg/container/ring/anyvalue/anyvalue.go
  pkg/container/ring/anyvalue/anyvalue_test.go
  pkg/sql/colexec2/aggregate/aggregate.go
  pkg/sql/colexec2/aggregate/types.go
  pkg/sql/plan2/function/aggregate.go
  pkg/sql/plan2/function/function.go
  pkg/sql/plan2/function/function_id.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/types.go
Labels: reviewed

#2976 fix bug 2969(return column name is wrong)
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/query_builder.go
Labels: reviewed

#2983 fix replay bugs and some code refactor
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/common/fields.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tasks/base.go
  pkg/vm/engine/tae/tasks/types.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnbase/fields.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/bug, kind/refactor, reviewed, component/tae

#2970 Initial commit of LogService and HAKeeper
  go.mod
  go.sum
  pkg/common/moerr/error.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/hakeeper/state.go
  pkg/hakeeper/state_test.go
  pkg/logservice/README.md
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/errors.go
  pkg/logservice/errors_test.go
  pkg/logservice/rsm.go
  pkg/logservice/rsm_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/shardinfo.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/logservice/transport.go
  pkg/logservice/transport_test.go
  pkg/logservice/utils.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/plan/plan.pb.go
  proto/logservice.proto
Labels: priority/high, kind/feature

#2987 Support update for tae moengine
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
Labels: kind/feature, component/tae

#2996 cleanup stale files after replay
  pkg/vm/engine/tae/db/replay.go
Labels: kind/enhancement, component/tae

#2981 add function for casting ts as varchar
  pkg/sql/plan2/function/operator/cast.go
  pkg/sql/plan2/function/operator/cast_test.go
  pkg/sql/plan2/function/operators.go
  pkg/vectorize/typecast/typecast.go
Labels: do-not-merge/wip

#2999 logservice: added IsTempError()
  go.mod
  go.sum
  pkg/logservice/client.go
  pkg/logservice/errors.go
  pkg/logservice/errors_test.go
  pkg/logservice/service.go
  pkg/logservice/store.go
  pkg/logservice/transport.go
  pkg/logservice/transport_test.go
Labels: priority/high, kind/api-change

#3012 support decimal aggregation in plan2
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec2/aggregate/aggregate.go
Labels: do-not-merge/wip

#3013 Remove tae reader preallocated memory
  pkg/vm/engine/tae/moengine/reader.go
Labels: component/tae

#3016 update for replay
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/replay.go
Labels: kind/bug, kind/enhancement, component/tae

#3035 hakeeper: added the Checker interface
  pkg/hakeeper/checker.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/state.go
Labels: kind/enhancement, priority/high

#3050 Add data value in tae AppendValue interface
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/moengine/reader.go
  pkg/vm/engine/tae/moengine/types.go
Labels: component/tae

#3053 add hakeeper.proto
  pkg/pb/hakeeper/hakeeper.pb.go
  proto/hakeeper.proto
Labels: priority/high, kind/feature

#3056 modify hakeeper.proto
  pkg/pb/hakeeper/hakeeper.pb.go
  proto/hakeeper.proto
Labels: priority/high, kind/feature

#3054 Move operator out of rsm
  go.mod
  go.sum
  pkg/hakeeper/checker.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/hakeeper/state.go
  pkg/logservice/hachecker.go
  pkg/logservice/hachecker_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: kind/enhancement, priority/high

#3067 Save schedule command
  pkg/hakeeper/checker.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hachecker.go
  pkg/logservice/hachecker_test.go
  pkg/logservice/store.go
  pkg/pb/hakeeper/hakeeper.pb.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/metric/metric.pb.go
  pkg/pb/timestamp/timestamp.pb.go
  pkg/pb/txn/txn.pb.go
  proto/hakeeper.proto
  proto/logservice.proto
Labels: priority/high, kind/feature

#3077 quick solution for tae allocator to crash
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
Labels: component/tae

#3061 add operators & log service check in hakeeper
  pkg/hakeeper/checkers/logservice/checker.go
  pkg/hakeeper/checkers/logservice/checker_test.go
  pkg/hakeeper/operator/builder.go
  pkg/hakeeper/operator/builder_test.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/operator.go
  pkg/hakeeper/operator/operator_test.go
  pkg/hakeeper/operator/status.go
  pkg/hakeeper/operator/status_test.go
  pkg/hakeeper/operator/status_tracker.go
  pkg/hakeeper/operator/status_tracker_test.go
  pkg/hakeeper/operator/steps.go
  pkg/hakeeper/utils/utils.go
  pkg/pb/hakeeper/hakeeper.pb.go
  proto/hakeeper.proto
Labels: priority/high, kind/feature, do-not-merge/wip

#3059 Schedule logic for DN shard;
  pkg/hakeeper/checkers/dnservice/README.md
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/errors.go
  pkg/hakeeper/checkers/dnservice/filter.go
  pkg/hakeeper/checkers/dnservice/filter_test.go
  pkg/hakeeper/checkers/dnservice/operator.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/dnservice/step.go
  pkg/hakeeper/utility.go
Labels: priority/high, kind/feature, do-not-merge/wip

#3094 implement update null
  pkg/vm/engine/tae/common/bitmap.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/container/vector/stdvec.go
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/mockio/block_test.go
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/dataio/mockio/segment_test.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/mergesort/varchar/func.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/types/types.go
Labels: kind/bug, kind/enhancement, component/tae

#3102 Driver refactor
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block_test.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
  pkg/vm/engine/tae/dataio/segmentio/file.go
  pkg/vm/engine/tae/dataio/segmentio/inode.go
  pkg/vm/engine/tae/dataio/segmentio/log.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/iface/file/segment.go
Labels: kind/refactor, component/tae

#3103 logservice: minor refactoring
  pkg/hakeeper/rsm.go
  pkg/logservice/rsm.go
  pkg/logservice/rsm_test.go
  pkg/logservice/service.go
  pkg/logservice/store.go
Labels: priority/high, kind/refactor

#3106 Use pb for hakeeper RSM state
  pkg/hakeeper/checker.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/checker.go
  pkg/hakeeper/checkers/logservice/checker_test.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/operator.go
  pkg/hakeeper/operator/operator_test.go
  pkg/hakeeper/operator/steps.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hachecker.go
  pkg/logservice/rsm.go
  pkg/logservice/rsm_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/hakeeper/hakeeper.go
  pkg/pb/hakeeper/hakeeper.pb.go
  pkg/pb/hakeeper/hakeeper_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/hakeeper.proto
  proto/logservice.proto
Labels: priority/high, kind/refactor

#3112 Get rid of verbose hakeeper utilities;
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/checker.go
  pkg/hakeeper/utility.go
  pkg/hakeeper/utils/utils.go
Labels: kind/refactor

#3125 Get rid of verbose hakeeper utilities
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/checker.go
  pkg/hakeeper/utility.go
  pkg/hakeeper/utils/utils.go
Labels: kind/refactor

#3126 (tae): implement new container ready for replacing the current
  pkg/vm/engine/tae/adaptor/batch.go
  pkg/vm/engine/tae/adaptor/factory.go
  pkg/vm/engine/tae/adaptor/types.go
  pkg/vm/engine/tae/adaptor/vecbase.go
  pkg/vm/engine/tae/adaptor/vecimpl.go
  pkg/vm/engine/tae/adaptor/vector.go
  pkg/vm/engine/tae/adaptor/vector_test.go
  pkg/vm/engine/tae/adaptor/vecwindow.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/mempool.go
  pkg/vm/engine/tae/common/mempool_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/stl/allocator.go
  pkg/vm/engine/tae/stl/bytes.go
  pkg/vm/engine/tae/stl/container/stdvec.go
  pkg/vm/engine/tae/stl/container/strvec.go
  pkg/vm/engine/tae/stl/container/types.go
  pkg/vm/engine/tae/stl/container/vector.go
  pkg/vm/engine/tae/stl/container/vector_test.go
  pkg/vm/engine/tae/stl/errors.go
  pkg/vm/engine/tae/stl/stl_test.go
  pkg/vm/engine/tae/stl/types.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: kind/enhancement, component/tae

#3136 Integrate dn checker into related logic
  pkg/hakeeper/checkers/dnservice/README.md
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/operator.go
  pkg/hakeeper/checkers/dnservice/step.go
  pkg/hakeeper/operator/operator.go
  pkg/hakeeper/operator/steps.go
Labels: priority/medium, kind/refactor

#3150 Fix bitmap bug
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, component/tae

#3153 (tae): implement a simple table truncate solution
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/handle/database.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/sysdb.go
Labels: kind/feature, component/tae

#3173 Fix the bug of segmentio loadupdates
  pkg/vm/engine/tae/dataio/segmentio/block.go
Labels: component/tae

#3204 (tae): update containers and adaptors
  pkg/vm/engine/tae/adaptor/batch.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/batch_test.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vecbase.go
  pkg/vm/engine/tae/containers/vecimpl.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/containers/vecwindow.go
  pkg/vm/engine/tae/stl/adaptors/buffer.go
  pkg/vm/engine/tae/stl/adaptors/types.go
  pkg/vm/engine/tae/stl/containers/stdvec.go
  pkg/vm/engine/tae/stl/containers/strvec.go
  pkg/vm/engine/tae/stl/containers/types.go
  pkg/vm/engine/tae/stl/containers/vector.go
  pkg/vm/engine/tae/stl/containers/vector_test.go
Labels: kind/enhancement, component/tae

#3322 Fix the bug that segmentio memory pre-allocation causes oom
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
Labels: kind/bug, component/tae

#3321 logservice: added ScheduleCommand handler
  pkg/logservice/client_test.go
  pkg/logservice/commands.go
  pkg/logservice/commands_test.go
  pkg/logservice/hachecker.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/shardinfo.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: kind/feature

#3358 logservice: added the ability to add replica
  pkg/logservice/commands.go
  pkg/logservice/commands_test.go
Labels: kind/feature

#3420 logservice: added type field to LogRecord, return all entries
  pkg/logservice/client.go
  pkg/logservice/errors.go
  pkg/logservice/errors_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/logservice/transport_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/enhancement

#3476 fix the result for issue#3302
  test/cases/expression/cte.sql
  test/result/expression/cte.result
Labels: bvt

#3482 Fix util MOToVectorTmp
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/utils.go
Labels: component/tae

#3504 (tae): improve replay related implementation code
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/compound_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/model/blkview.go
  pkg/vm/engine/tae/model/blkview_test.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/model/helper.go
  pkg/vm/engine/tae/moengine/block.go
  pkg/vm/engine/tae/moengine/reader.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/factory.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tasks/ops/gc/types.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, kind/enhancement, component/tae

#3460 logservice: minor fix for a test
  pkg/logservice/service_test.go
Labels: kind/enhancement

#3490 [Plan2] Make DISTINCT work as expected
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/distinct_binder.go
  pkg/sql/plan2/explain/explain_expr.go
  pkg/sql/plan2/explain/explain_node.go
  pkg/sql/plan2/group_binder.go
  pkg/sql/plan2/order_binder.go
  pkg/sql/plan2/query_builder.go
  pkg/sql/plan2/types.go
  proto/plan.proto
  test/result/function/func_anyvalue.result
  test/result/function/func_math_abs.result
  test/result/subquery/subquery-with-exists.result
Labels: do-not-merge/wip

#3469 fileservice: use default aws config loading method
  go.mod
  go.sum
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: size/m

#3520 Fix the bug of tae driver allocator
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
Labels: kind/bug, component/tae

#3480 Health check for `hakeeper`
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/dnservice/README.md
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/syshealth/check.go
  pkg/hakeeper/checkers/syshealth/check_test.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/operator.go
  pkg/hakeeper/operator/steps.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/commands.go
  pkg/logservice/commands_test.go
  pkg/pb/hakeeper/hakeeper.pb.go
  proto/gen.sh
  proto/hakeeper.proto
Labels: priority/medium, kind/feature

#3558 Add system relation in moengine
  pkg/vm/engine/tae/moengine/database.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/sys_relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/moengine/types.go
Labels: kind/bug, component/tae

#3571 logservice: use sync.Pool to avoid morpc allocations
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/service.go
Labels: kind/enhancement
