Repository matrixorigin/matrixone, pull requests merged in 2022-02, with the labels that each got.

#1661 Engine supports zonemap index
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/reader.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/engine/sparse_filter.go
  pkg/vm/engine/aoe/engine/store.go
  pkg/vm/engine/aoe/engine/types.go
Labels: component/aoe, reviewed

#1707 Add to judge whether the segment exists in GetInitialStates
  pkg/vm/driver/aoe/storage.go
Labels: component/aoe, reviewed

#1733 Update count.md
  docs/en/MatrixOne/Reference/SQL-Reference/Aggregate-Functions/count.md
Labels: documentation/grammar error

#1734 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/documentation

#1720 Fix Metadata compaction
  pkg/vm/engine/aoe/storage/metadata/v1/block.go
  pkg/vm/engine/aoe/storage/metadata/v1/database.go
  pkg/vm/engine/aoe/storage/metadata/v1/segment.go
  pkg/vm/engine/aoe/storage/metadata/v1/table.go
Labels: reviewed

#1749 Add docs about round() function
  docs/en/MatrixOne/Reference/Customer-Functions/floor.md
  docs/en/MatrixOne/Reference/Customer-Functions/length.md
  docs/en/MatrixOne/Reference/Customer-Functions/round.md
Labels: reviewed

#1748 Add issue templates files
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general_question.yml
  .github/ISSUE_TEMPLATE/performance_question.yml
  .github/ISSUE_TEMPLATE/refactoring_request.yml
Labels: reviewed

#1765 fix [Bug]:buffer busy #1624
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
Labels: reviewed

#1764 fix a projecion bug, and a version display bug
  cmd/db-server/main.go
  pkg/frontend/mysql_protocol.go
  pkg/sql/colexec/projection/projection.go
Labels: reviewed
