Repository matrixorigin/matrixone, pull requests merged in 2022-05, with the labels that each got.

#2340 (aoe): small fix for zonemap unmarshal
  pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go
Labels: reviewed

#2345 fix issue#2335
  pkg/builtin/unary/month.go
  pkg/builtin/unary/weekday.go
Labels: reviewed

#2346 fix issue#2300
  pkg/sql/plan/expr.go
  pkg/sql/unittest/dml_test.go
Labels: reviewed

#2361 (tae/doc): add tae design rfc
  docs/rfcs/20220503_tae_design.md
Labels: kind/documentation, component/tae

#2383 imporve the export speed
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/tree/update.go
Labels: reviewed

#2371 fix issue#2297
  pkg/container/types/decimal.go
Labels: reviewed

#2409 Enable molint as a part of SCA
  Makefile
Labels: reviewed

#2428 Added go-licenses check to the static-check target
  Makefile
Labels: reviewed

#2365 Add timestamp data type
  pkg/container/types/decimal.go
  pkg/container/types/temestamp_test.go
  pkg/container/types/timestamp.go
  pkg/container/types/types.go
  pkg/container/vector/vector.go
  pkg/encoding/encoding.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/sql/colexec/extend/overload/cast.template
  pkg/sql/colexec/extend/overload/eq.template
  pkg/sql/colexec/extend/overload/ge.template
  pkg/sql/colexec/extend/overload/gt.template
  pkg/sql/colexec/extend/overload/init.go
  pkg/sql/colexec/extend/overload/le.template
  pkg/sql/colexec/extend/overload/lt.template
  pkg/sql/colexec/extend/overload/ne.template
  pkg/sql/colexec/extend/overload/overloadGenerate.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/constant.go
  pkg/sql/plan/create_table.go
  pkg/sql/plan/expr.go
  pkg/sql/plan/insert.go
  pkg/sql/protocol/protocol.go
  pkg/sql/unittest/dml_test.go
  pkg/sql/unittest/operator_test.go
  pkg/vectorize/shuffle/shuffle.go
  pkg/vectorize/typecast/typecast.go
  pkg/vm/engine/aoe/protocol/protocol.go
  pkg/vm/engine/aoe/storage/container/vector/stdvec.go
Labels: reviewed

#2455 Fix the race of MergeRun and mmu
  pkg/sql/compile/scope.go
  pkg/vm/mmu/guest/mmu.go
Labels: reviewed

#2460 add nightly code analysis notify
  .github/workflows/build_matrixone.yml
  .github/workflows/robot.yml
  optools/run_ut.sh
Labels: do-not-merge/wip

#2451 Add limit and offset operator
  pkg/sql/colexec2/limit/limit.go
  pkg/sql/colexec2/limit/limit_test.go
  pkg/sql/colexec2/limit/types.go
  pkg/sql/colexec2/mergelimit/limit.go
  pkg/sql/colexec2/mergelimit/limit_test.go
  pkg/sql/colexec2/mergelimit/types.go
  pkg/sql/colexec2/mergeoffset/offset.go
  pkg/sql/colexec2/mergeoffset/offset_test.go
  pkg/sql/colexec2/mergeoffset/types.go
  pkg/sql/colexec2/offset/offset.go
  pkg/sql/colexec2/offset/offset_test.go
  pkg/sql/colexec2/offset/types.go
Labels: reviewed

#2478 temp turn off gc check for tae ut
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/tasks/worker/worker.go
Labels: priority/high, severity/major, component/tae

#2483 fix gc bug and add more debug info
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/common/id.go
  pkg/vm/engine/tae/db/checkpoint/units.go
  pkg/vm/engine/tae/db/dispatcher.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/bug, component/tae

#2485 Static check: commonly misspelled English words;
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/tree/precedence.go
  pkg/sql/protocol/protocol.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/common/interval.go
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/mockio/colblk.go
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/txn/txnbase/errors.go
  pkg/vm/engine/tpe/orderedcodec/types.go
  pkg/vm/engine/tpe/tuplecodec/cubekv.go
  pkg/vm/engine/tpe/tuplecodec/serialize.go
Labels: reviewed

#2402 Add built-in function oct (#2115)
  pkg/builtin/types.go
  pkg/builtin/unary/oct.go
  pkg/vectorize/oct/oct.go
  pkg/vectorize/oct/oct_test.go
Labels: reviewed

#2496 update for TAE catalog replay - phase 1
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/checkpoint.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/dataio/mockio/block.go
  pkg/vm/engine/tae/dataio/mockio/block_test.go
  pkg/vm/engine/tae/dataio/mockio/fs.go
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/data/segment.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/iface/file/segment.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/feature, reviewed, component/tae

#2489 Add group operator
  pkg/container/batch2/batch.go
  pkg/container/batch2/types.go
  pkg/container/types/types.go
  pkg/sql/colexec2/aggregate/aggregate.go
  pkg/sql/colexec2/aggregate/types.go
  pkg/sql/colexec2/group/group.go
  pkg/sql/colexec2/group/group_test.go
  pkg/sql/colexec2/group/types.go
Labels: reviewed

#2429 add function register for compute layer refactor
  pkg/sql/plan2/function/aggregate.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/plan2/function/function.go
  pkg/sql/plan2/function/function_id.go
  pkg/sql/plan2/function/function_kind.go
  pkg/sql/plan2/function/function_test.go
  pkg/sql/plan2/function/init.go
  pkg/sql/plan2/function/operators.go
Labels: reviewed

#2506 Add mergegroup operator
  pkg/sql/colexec2/mergegroup/group.go
  pkg/sql/colexec2/mergegroup/group_test.go
  pkg/sql/colexec2/mergegroup/types.go
Labels: reviewed

#2518 Adding transaction snapshot to the engine interface
  pkg/vm/engine2/engine.go
  pkg/vm/engine2/types.go
Labels: reviewed

#2527 Static check: fix cases for `errcheck`;
  cmd/db-server/main.go
  pkg/container/batch/batch.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/rpcserver/codec.go
  pkg/rpcserver/server.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec2/order/order.go
Labels: reviewed

#2516 Parse 'create view' (#2456)
  pkg/sql/parsers/dialect/mysql/explain_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/scanner/scanner.go
  pkg/sql/parsers/tree/view.go
  pkg/sql/plan2/build_from.go
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/mock.go
  pkg/sql/unittest/ddl_test.go
  pkg/sql/unittest/exec_operator_test.go
  pkg/vm/engine/memEngine/testEngine.go
Labels: reviewed

#2532 update for system DB - phase 1
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/checkpoint.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/errors.go
  pkg/vm/engine/tae/catalog/idalloc.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/types.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/dispatcher.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/scanner.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/feature, component/tae

#2535 fix some linter errcheck for tae
  pkg/vm/engine/aoe/storage/db/split.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logstore/sm/sm.go
  pkg/vm/engine/tae/model/blkview.go
  pkg/vm/engine/tae/model/blkview_test.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/insert.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/tables_test.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/txn/txnbase/helper.go
  pkg/vm/engine/tae/txn/txnbase/kv.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/wal/wal_test.go
Labels: kind/refactor, reviewed, component/tae

#2502 Build tcl plan
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/tree/txn.go
  pkg/sql/plan2/build.go
  pkg/sql/plan2/build_delete.go
  pkg/sql/plan2/build_insert.go
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/build_transation.go
  pkg/sql/plan2/build_update.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/explain/buildexplain_test.go
  pkg/sql/plan2/mock.go
  pkg/sql/plan2/types.go
  proto/plan.proto
Labels: reviewed

#2543 Fix bitmap allocator&Remove read cache
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
  pkg/vm/engine/tae/layout/segment/extent.go
  pkg/vm/engine/tae/layout/segment/file.go
  pkg/vm/engine/tae/layout/segment/segment.go
Labels: kind/bug, reviewed, component/tae

#2542 update engine interface
  cmd/db-server/main.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/util.go
  pkg/sql/colexec/deleteTag/deleteTag.go
  pkg/sql/colexec/updateTag/updateTag.go
  pkg/sql/compile/exec.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/create_index.go
  pkg/sql/plan/create_table.go
  pkg/sql/plan/drop_index.go
  pkg/sql/plan/from.go
  pkg/sql/plan/insert.go
  pkg/sql/plan/show_tables.go
  pkg/vm/engine/aoe/engine/database.go
  pkg/vm/engine/aoe/engine/engine.go
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/local/database.go
  pkg/vm/engine/aoe/local/engine.go
  pkg/vm/engine/aoe/local/relation.go
  pkg/vm/engine/memEngine/database.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/memEngine/testEngine.go
  pkg/vm/engine/tae/moengine/database.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tpe/engine/database.go
  pkg/vm/engine/tpe/engine/database_test.go
  pkg/vm/engine/tpe/engine/engine.go
  pkg/vm/engine/tpe/engine/engine_test.go
  pkg/vm/engine/tpe/engine/reader_test.go
  pkg/vm/engine/tpe/engine/relation.go
  pkg/vm/engine/tpe/engine/relation_test.go
  pkg/vm/engine/tpe/engine/toolKitHandler.go
  pkg/vm/engine/tpe/engine/toolKitHandler_test.go
  pkg/vm/engine/types.go
  pkg/vm/engine2/engine.go
  pkg/vm/engine2/types.go
Labels: reviewed

#2552 update for catalog checkpoint
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/checkpoint.go
  pkg/vm/engine/tae/container/types.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/wal/types.go
Labels: kind/enhancement, component/tae

#2551 Add compress
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/block_test.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/stat.go
  pkg/vm/engine/tae/layout/segment/extent.go
  pkg/vm/engine/tae/layout/segment/file.go
  pkg/vm/engine/tae/layout/segment/inode.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: component/tae

#2558 (tae): update for new engine api
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/samples/sample4/main.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/feature, component/tae

#2519 [MatrixCamp] Add add built-in string function find_in_set()
  pkg/builtin/binary/findinset.go
  pkg/builtin/types.go
  pkg/vectorize/findinset/findinset.go
  pkg/vectorize/findinset/findinset_test.go
Labels: reviewed

#2568 Fix the bug that the last pos is not updated and the offset is abnormal
  pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
Labels: reviewed, component/tae

#2567 (tae): update for system db -- phase 2
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/sysdb.go
Labels: kind/feature, reviewed, component/tae

#2570 string should not be covert to lower case when parse string
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/scanner/scanner.go
Labels: reviewed

#2572 add support for building show statement plan
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build.go
  pkg/sql/plan2/build_show.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/function.go
  pkg/sql/plan2/mock.go
  proto/plan.proto
Labels: reviewed

#2579 Fix drop table bug: lost db name
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build_ddl.go
  pkg/sql/plan2/build_test.go
  proto/plan.proto
Labels: reviewed

#2575 Add UT & Fix level0 offset
  pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: component/tae

#2573 Add projection operator and remove batch's attributes reorder
  pkg/container/batch2/batch.go
  pkg/container/batch2/batch_test.go
  pkg/sql/colexec2/mergeorder/order.go
  pkg/sql/colexec2/mergetop/top.go
  pkg/sql/colexec2/mergetop/types.go
  pkg/sql/colexec2/projection/projection.go
  pkg/sql/colexec2/projection/projection_test.go
  pkg/sql/colexec2/projection/types.go
  pkg/sql/colexec2/top/top.go
  pkg/sql/colexec2/top/types.go
Labels: reviewed

#2584 check column length match value length in insert statement
  pkg/sql/plan2/build_insert.go
  pkg/sql/plan2/build_test.go
Labels: reviewed

#2582 (tae): update for system db -- phase 3
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/feature, component/tae

#2588 Fix ddl bug
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build.go
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_subquery.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/build_util.go
  proto/plan.proto
Labels: reviewed

#2590 change CompilerContext interface
  pkg/sql/plan2/build_ddl.go
  pkg/sql/plan2/build_from.go
  pkg/sql/plan2/build_insert.go
  pkg/sql/plan2/build_show.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/mock.go
  pkg/sql/plan2/types.go
Labels: reviewed

#2592 fix scan txn uncommitted data and txnimpl refactor
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/container/vector/wrapper.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/iface/handle/segment.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/sysdb.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, kind/enhancement, kind/refactor, component/tae

#2593 (tae): fix system db bug
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, reviewed, component/tae

#2594 refactor compile2
  pkg/sql/colexec2/mergeorder/order.go
  pkg/sql/colexec2/mergeorder/order_test.go
  pkg/sql/colexec2/mergeorder/types.go
  pkg/sql/colexec2/mergetop/top.go
  pkg/sql/colexec2/mergetop/top_test.go
  pkg/sql/colexec2/mergetop/types.go
  pkg/sql/colexec2/order/order.go
  pkg/sql/colexec2/order/order_test.go
  pkg/sql/colexec2/order/types.go
  pkg/sql/colexec2/top/top.go
  pkg/sql/colexec2/top/top_test.go
  pkg/sql/colexec2/top/types.go
  pkg/sql/compile2/compile.go
  pkg/sql/compile2/exec.go
  pkg/sql/compile2/operator.go
  pkg/sql/compile2/types.go
  pkg/vm/overload/types.go
Labels: reviewed

#2597 (tae): fix pre commit dedup bug
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
Labels: kind/bug, reviewed, component/tae

#2598 update replay ut, fix bug
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/logstore/store/replayer.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/types.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: reviewed

#2601 use new function register method
  pkg/container/types/types.go
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_from.go
  pkg/sql/plan2/build_function.go
  pkg/sql/plan2/build_show.go
  pkg/sql/plan2/build_subquery.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/build_update.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/explain/explain_expr.go
  pkg/sql/plan2/explain/explain_test.go
  pkg/sql/plan2/explain/tpch_explain_test.go
  pkg/sql/plan2/function/aggregate.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/plan2/function/function.go
  pkg/sql/plan2/function/function_id.go
  pkg/sql/plan2/function/function_kind.go
  pkg/sql/plan2/function/operators.go
  pkg/sql/plan2/mock.go
Labels: reviewed

#2603 (tae): fix bugs and apply deletes for mo engine
  pkg/vm/engine/tae/container/compute/mock.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/moengine/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/bug, reviewed, component/tae

#2602 Refine tae layout&Add replay
  pkg/vm/engine/tae/layout/segment/file.go
  pkg/vm/engine/tae/layout/segment/inode.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: reviewed, component/tae

#2605 adapt frontend for tae/aoe/plan2/compile2
  cmd/generate-config/config_template.go
  cmd/generate-config/system_vars_def.toml
  pkg/frontend/init_db.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/test/iosession_mock.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
Labels: reviewed

#2606 api changes and implementation improvement
  pkg/vm/engine/tae/buffer/base/types.go
  pkg/vm/engine/tae/buffer/node.go
  pkg/vm/engine/tae/buffer/nodemgr.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/node.go
  pkg/vm/engine/tae/common/id.go
  pkg/vm/engine/tae/common/range.go
  pkg/vm/engine/tae/common/retry.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/errors.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
  pkg/vm/engine/tae/logstore/sm/queue.go
  pkg/vm/engine/tae/logstore/sm/safeq.go
  pkg/vm/engine/tae/logstore/sm/types.go
  pkg/vm/engine/tae/logstore/store/history.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/mock.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, kind/refactor, reviewed, component/tae

#2608 1. add staticcheck
  Makefile
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan2/build_ddl.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/function/aggregate.go
  pkg/sql/plan2/function/operators.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: reviewed

#2613 fix many bugs and enhance code robustness and testability
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/node.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/container/compute/compute.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/iterator.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/handle/segment.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, kind/enhancement, reviewed, component/tae

#2596 Support DDL's execution for TPCH
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile2/compile.go
  pkg/sql/compile2/scope.go
  pkg/sql/compile2/types.go
  pkg/sql/plan2/build_util.go
Labels: reviewed

#2600 feature: Decimal max min average functions
  pkg/container/ring/avg/decimal.go
  pkg/container/ring/avg/types.go
  pkg/container/ring/max/decimal128.go
  pkg/container/ring/max/decimal64.go
  pkg/container/ring/max/types.go
  pkg/container/ring/min/decimal128.go
  pkg/container/ring/min/decimal64.go
  pkg/container/ring/min/types.go
  pkg/container/types/decimal.go
  pkg/container/types/decimal_test.go
  pkg/sql/colexec2/aggregate/aggregate.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/types.go
  pkg/sql/unittest/dml_test.go
  pkg/sql/viewexec/transformer/transformer.go
Labels: reviewed

#2617 Add allocator Replay
  pkg/vm/engine/tae/layout/segment/allocator.go
  pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: component/tae

#2618 Add compile2's compile logic
  pkg/sql/compile2/compile.go
  pkg/sql/compile2/operator.go
  pkg/sql/compile2/scope.go
  pkg/sql/compile2/types.go
  pkg/vm/overload/overload.go
  pkg/vm/overload/run.go
  pkg/vm/pipeline2/pipeline.go
  pkg/vm/pipeline2/types.go
Labels: reviewed

#2624 fix delete related bugs and txn code improvement
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/data/errors.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, kind/enhancement, reviewed, component/tae

#2621 add ddl
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/txn_mock.go
  pkg/sql/compile2/compile.go
  pkg/sql/compile2/scope.go
  pkg/sql/plan2/build_ddl.go
Labels: reviewed

#2629 Unify aggregate functions in HAVING clause
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_from.go
  pkg/sql/plan2/build_function.go
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_show.go
  pkg/sql/plan2/build_subquery.go
  pkg/sql/plan2/build_update.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/explain/explain_node.go
Labels: reviewed

#2628 Change show rewrite
  pkg/sql/plan2/build_show.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/mock.go
Labels: reviewed

#2631 Fix default value for 'create table'
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile2/scope.go
  pkg/sql/plan2/build_util.go
  proto/plan.proto
Labels: reviewed

#2633 support bool operation in plan2
  pkg/container/types/bool.go
  pkg/container/vector/vector.go
  pkg/encoding/encoding.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/create_table.go
  pkg/sql/plan/expr.go
  pkg/sql/plan/insert.go
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_expr_test.go
  pkg/sql/plan2/build_function.go
  pkg/sql/plan2/function/operators.go
  pkg/vm/engine/aoe/protocol/protocol.go
  pkg/vm/engine/aoe/storage/container/vector/stdvec.go
  proto/plan.proto
Labels: reviewed

#2642 Remove replay ids
  pkg/vm/engine/tae/dataio/mockio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/dataio/segmentio/segment_test.go
  pkg/vm/engine/tae/iface/file/segment.go
Labels: reviewed, component/tae

#2658 Add aggregate functions in SELECT/ORDER BY clause into agg node
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_select.go
Labels: reviewed

#2657 Add base optimizer
  pkg/sql/plan2/optimize.go
  pkg/sql/plan2/rule/consant_fold.go
  pkg/sql/plan2/types.go
Labels: reviewed

#2655 Surpport insert values
  pkg/frontend/insert.go
  pkg/frontend/mysql_cmd_executor.go
Labels: reviewed

#2659 update appendable block index to support multi versions
  pkg/vm/engine/tae/container/compute/utils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/mtree.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/index/zonemap_test.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/deletes.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, kind/feature, component/tae

#2646 explain support txn CompileContext
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan2/explain/explain_expr.go
  pkg/sql/plan2/explain/explain_node.go
  pkg/sql/plan2/explain/explain_query.go
  pkg/sql/plan2/explain/explain_test.go
  pkg/sql/plan2/function/operators.go
Labels: reviewed

#2637 update tpch ddl sql
  pkg/sql/plan2/tpch/ddl.sql
Labels: reviewed

#2666 fix UpdateOffsets
  pkg/vm/engine/tae/container/compute/compute.go
  pkg/vm/engine/tae/db/db_test.go
Labels: reviewed

#2652 Ci/new tool
  .github/workflows/ci.yml
Labels: reviewed

#2672 (tae): fix wait committing txn state bug
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
Labels: kind/bug, priority/critical, reviewed, component/tae

#2677 update replay ut, fix bugs
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/store/syncbase.go
  pkg/vm/engine/tae/logstore/store/vgroup.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/wal/types.go
Labels: reviewed

#2682 drop database if exists test01; failed when using plan2 with aoe
  pkg/sql/compile2/scope.go
  pkg/sql/plan2/build_ddl.go
  pkg/sql/plan2/build_test.go
Labels: reviewed

#2685 Fix tae replay oom bug & layout replay check hole data
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment.go
Labels: kind/bug, priority/critical, severity/critical, component/tae

#2689 fix snapshot isolation violation
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/deletes.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, component/tae

#2690 fix logstore cache
  pkg/vm/engine/tae/logstore/store/vfile.go
Labels: reviewed

#2692 Fix bug in bitmap allocator for large numbers of files
  pkg/vm/engine/tae/layout/segment/bitmap_allocator.go
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: kind/bug, priority/critical, severity/critical, component/tae

#2694 implement Rows() for TAE underlying table
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/container/compute/compute.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/txnif/errors.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnbase/errors.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/feature, component/tae

#2698 Fix the bug that deleted files are still visible after replay
  pkg/vm/engine/tae/layout/segment/log.go
  pkg/vm/engine/tae/layout/segment/segment_test.go
Labels: kind/bug, component/tae

#2695 Function to plan2
  pkg/sql/plan2/explain/explain_test.go
  pkg/sql/plan2/function/builtin/binary/power.go
  pkg/sql/plan2/function/builtin/multi/floor.go
  pkg/sql/plan2/function/builtin/unary/abs.go
  pkg/sql/plan2/function/builtin/unary/acos.go
  pkg/sql/plan2/function/buitins.go
  pkg/sql/plan2/function/function_id.go
Labels: reviewed

#2711 Implement tae moengine Nodes
  pkg/frontend/insert.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/reader.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/types.go
Labels: component/tae

#2721 Add Zs in batch
  pkg/vm/engine/tae/moengine/reader.go
  pkg/vm/engine/tae/moengine/types.go
Labels: reviewed, component/tae

#2722 replay table rows
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: reviewed

#2714 add value-scan demo, fix an expression eval bug
  pkg/sql/colexec2/expr_eval.go
  pkg/sql/compile2/compile.go
Labels: reviewed

#2723 Fix insert bug (#2715)
  pkg/sql/compile2/scope.go
Labels: reviewed

#2726 add hidden column into tae
  pkg/frontend/init_db.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/errors.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/container/compute/compute.go
  pkg/vm/engine/tae/container/compute/mock.go
  pkg/vm/engine/tae/container/vector/stdvec.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/errors.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/model/helper.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/moengine/database.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/helper.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/feature, component/tae

#2730 Add predicate pushdown
  pkg/sql/plan2/rule/consant_fold.go
  pkg/sql/plan2/rule/predicate_pushdown.go
Labels: reviewed

#2734 (tae): check nil during destoring immutindex
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
Labels: kind/bug, component/tae
