Repository matrixorigin/matrixone, pull requests merged in 2022-01, with the labels that each got.

#1479 fix SafeIds Unmarshal
  pkg/vm/engine/aoe/storage/wal/shard/shard_test.go
  pkg/vm/engine/aoe/storage/wal/shard/types.go
Labels: reviewed

#1573 update comment for system vars
  cmd/generate-config/system_vars_def.toml
Labels: priority/high, size/s, severity/moderate

#1580 add package frontend testcase
  pkg/frontend/epochgc.go
  pkg/frontend/epochgc_test.go
  pkg/frontend/iopackage_test.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/protocol_test.go
  pkg/frontend/test/iopackage_mock.go
  pkg/frontend/util.go
Labels: reviewed

#1579 Support constrain of key in the sql layer (#1578)
  pkg/sql/compile/scope.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/scanner/tokens.go
  pkg/sql/parsers/scanner/tokens_mysql.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/create_table.go
  pkg/vm/engine/aoe/common/helper/helper.go
  pkg/vm/engine/format.go
  pkg/vm/engine/types.go
Labels: reviewed

#1569 delete a orphan parameter in quick start(shard-groups), fix a mistake in quick start
  cmd/generate-config/config_template.go
  docs/en/MatrixOne/Get-Started/set-up-matrixone.md
Labels: reviewed

#1582 feature: add round function
  pkg/builtin/multi/round.go
  pkg/builtin/multi/types.go
  pkg/sql/colexec/extend/overload/init.go
  pkg/vectorize/round/round.go
  pkg/vectorize/round/round_test.go
Labels: reviewed

#1599 [AOE] Fix unexpected reference of block index holder
  pkg/vm/engine/aoe/storage/layout/table/v1/baseblk.go
Labels: kind/bug, component/aoe, severity/critical, reviewed

#1591 Implement interface Rows() and Size(string)
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/relation.go
Labels: reviewed

#1607 [AOE] Integrate fixed string BSI & some bug fix
  pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
  pkg/vm/engine/aoe/storage/common/compare.go
  pkg/vm/engine/aoe/storage/db/replay.go
  pkg/vm/engine/aoe/storage/db/sched/flushblkidx.go
  pkg/vm/engine/aoe/storage/db/sched/flushsegidx.go
  pkg/vm/engine/aoe/storage/db/segment_sparse_filter.go
  pkg/vm/engine/aoe/storage/layout/index/blk_holder.go
  pkg/vm/engine/aoe/storage/layout/index/blkzonemap.go
  pkg/vm/engine/aoe/storage/layout/index/builder.go
  pkg/vm/engine/aoe/storage/layout/index/index_test.go
  pkg/vm/engine/aoe/storage/layout/index/numbsi.go
  pkg/vm/engine/aoe/storage/layout/index/segzonemap.go
  pkg/vm/engine/aoe/storage/layout/index/sortedseg_holder.go
  pkg/vm/engine/aoe/storage/layout/index/strbsi.go
Labels: component/aoe, priority/high, kind/feature, reviewed

#1608 Use storeId to determine whether to read data
  pkg/vm/engine/aoe/engine/database.go
Labels: component/aoe

#1609 Add read latency of the reader
  pkg/vm/engine/aoe/engine/reader.go
  pkg/vm/engine/aoe/engine/types.go
Labels: component/aoe

#1610 vectorized floor function_
  pkg/builtin/multi/floor.go
  pkg/builtin/types.go
  pkg/vectorize/floor/floor.go
  pkg/vectorize/floor/floor_amd64.go
  pkg/vectorize/floor/floor_avx2_amd64.s
  pkg/vectorize/floor/floor_test.go
Labels: reviewed

#1613 fix data race
  pkg/vm/engine/aoe/storage/aoedb/v1/shard_test.go
  pkg/vm/engine/aoe/storage/flusher/flusher.go
  pkg/vm/engine/aoe/storage/flusher/flusher_test.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1615 fix physical resources not released after drop op
  pkg/vm/engine/aoe/storage/db/sched/flushseg.go
  pkg/vm/engine/aoe/storage/db/sched/scheduler.go
  pkg/vm/engine/aoe/storage/layout/dataio/index.go
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
Labels: kind/bug, component/aoe, priority/critical, severity/critical

#1622 fix TestAOEEngine
  pkg/vm/engine/aoe/engine/engine_test.go
Labels: reviewed

#1480 improve wal/shard UT & comment
  docs/rfcs/20211210_aoe_layout.md
  docs/rfcs/20211210_aoe_overall_design.md
  pkg/vm/engine/aoe/storage/wal/entry.go
  pkg/vm/engine/aoe/storage/wal/shard/index.go
  pkg/vm/engine/aoe/storage/wal/shard/manager.go
  pkg/vm/engine/aoe/storage/wal/shard/proxy.go
  pkg/vm/engine/aoe/storage/wal/shard/shard_test.go
  pkg/vm/engine/aoe/storage/wal/shard/slice.go
Labels: reviewed

#1636 Support computing storage IO pipeline separation
  cmd/db-server/main.go
  pkg/vm/engine/aoe/engine/database.go
  pkg/vm/engine/aoe/engine/engine.go
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/reader.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/engine/sparse_filter.go
  pkg/vm/engine/aoe/engine/store.go
  pkg/vm/engine/aoe/engine/types.go
  pkg/vm/engine/aoe/engine/worker.go
  pkg/vm/engine/aoe/types.go
Labels: component/aoe, reviewed
