Repository matrixorigin/matrixone, pull requests merged in 2022-07, with the labels that each got.

#3604 fix compaction related bugs
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/dataio/segmentio/colblk.go
  pkg/vm/engine/tae/dataio/segmentio/data.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/checkpoint/driver.go
  pkg/vm/engine/tae/db/checkpoint/units.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tasks/base.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
Labels: kind/bug, priority/critical, component/tae

#3643 deps: bumped dragonboat version
  go.mod
  go.sum
Labels: kind/bug

#3652 logservice: fix TestHandleRemoveReplica
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: unit-test-failed

#3670 fix static code errors and optimize prints
  pkg/vm/engine/tae/buffer/nodemgr.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/mempool.go
  pkg/vm/engine/tae/dataio/segmentio/block.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/compound_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/types.go
Labels: kind/bug, kind/refactor, component/tae

#3445 fix timezone issue for unix ts and utc ts
  pkg/container/types/datetime.go
Labels: do-not-merge/wip

#3683 hakeeper,logservice: support heartbeats to be sent to hakeeper
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/commands_test.go
  pkg/logservice/hachecker.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/feature

#3691 logservice: use pkg/common/stopper
  pkg/logservice/store.go
Labels: kind/refactor

#3707 Fix the bug of tae driver allocator
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
Labels: kind/bug, component/tae

#3741 hakeeper: added the ability to set initial cluster info
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hachecker.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/metadata/metadata.pb.go
  proto/logservice.proto
  proto/metadata.proto
Labels: kind/feature

#3763 add cgo allocator for container
  pkg/vm/engine/tae/containers/alloc/alloc.go
  pkg/vm/engine/tae/containers/alloc/alloc_32bit.go
  pkg/vm/engine/tae/containers/alloc/alloc_64bit.go
  pkg/vm/engine/tae/containers/alloc/alloc_nocgo.go
  pkg/vm/engine/tae/containers/types.go
Labels: kind/feature, component/tae

#3767 fix vector expand bug during extend
  pkg/vm/engine/tae/stl/containers/stdvec.go
Labels: kind/bug, component/tae

#3762 Change the maximum number of inodes of the driver to 20480
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
  pkg/vm/engine/tae/dataio/segmentio/log.go
Labels: kind/bug, kind/enhancement, component/tae

#3782 Reallocate when ALL_UNIT_CLEAR occurs during bitmap getBitPos
  pkg/vm/engine/tae/dataio/segmentio/bitmap_allocator.go
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
Labels: kind/bug, component/standalone tae

#3788 hakeeper: refactor logservice check
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/bootstrap/bootstrap_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/check_test.go
  pkg/hakeeper/checkers/logservice/parse.go
  pkg/hakeeper/checkers/logservice/parse_test.go
  pkg/hakeeper/checkers/logservice/stats.go
  pkg/hakeeper/checkers/util/store.go
Labels: kind/refactor

#3825 fix issue #3814
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/bootstrap/bootstrap_test.go
Labels: kind/bug

#3834 logservice: added godoc comments for client
  pkg/logservice/client.go
  pkg/logservice/client_test.go
Labels: kind/documentation

#3835 logservice: added tso support
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/message.go
  pkg/logservice/rsm.go
  pkg/logservice/rsm_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/feature

#3906 Add objectio for distributed tae
  pkg/vm/engine/tae/dataio/objectio/allocator.go
  pkg/vm/engine/tae/dataio/objectio/block.go
  pkg/vm/engine/tae/dataio/objectio/block_test.go
  pkg/vm/engine/tae/dataio/objectio/colblk.go
  pkg/vm/engine/tae/dataio/objectio/dir.go
  pkg/vm/engine/tae/dataio/objectio/extent.go
  pkg/vm/engine/tae/dataio/objectio/file.go
  pkg/vm/engine/tae/dataio/objectio/fs.go
  pkg/vm/engine/tae/dataio/objectio/inode.go
  pkg/vm/engine/tae/dataio/objectio/object.go
  pkg/vm/engine/tae/dataio/objectio/reader.go
  pkg/vm/engine/tae/dataio/objectio/segment.go
  pkg/vm/engine/tae/dataio/objectio/segment_test.go
  pkg/vm/engine/tae/dataio/objectio/stat.go
  pkg/vm/engine/tae/dataio/objectio/types.go
  pkg/vm/engine/tae/dataio/objectio/vfs.go
  pkg/vm/engine/tae/dataio/objectio/writer.go
  pkg/vm/engine/tae/iface/tfs/types.go
Labels: component/distributed tae

#3985 mutable index atomic revert changes
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/index/mtree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/indexwrapper/deletes.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/index_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: priority/p0, component/distributed tae, kind/subtask

#3994 (tae): small code refactor and update ut
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/tables/block.go
Labels: component/standalone tae

#4008 logservice,hakeeper: fixed some staticheck reported errors
  pkg/hakeeper/rsm.go
  pkg/logservice/commands.go
  pkg/logservice/config.go
  pkg/logservice/service.go
  pkg/logservice/store.go
Labels: do-not-merge/wip

#4027 (tae): fix non-repeatable read for delete nodes
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/stl/containers/vector_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
Labels: kind/bug, priority/p0, component/standalone tae

#4049 update insert during transaction commit
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnimpl/appender.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
Labels: kind/bug, kind/enhancement, component/standalone tae, component/distributed tae

#4051 Fix the bug that replay dead loop when the log is not full
  pkg/vm/engine/tae/dataio/segmentio/driver_test.go
  pkg/vm/engine/tae/dataio/segmentio/log.go
Labels: component/standalone tae

#4052 Fix the bug that block&index file reference count is not released
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/jobs/helper.go
Labels: component/standalone tae

#4062 chore: add go mod cache to speed up CI
  .github/actions/setup_env/action.yaml
  .github/workflows/ci.yml
Labels: kind/undefined, size/s

#4060 hakeeper: add configurable timeout settings
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/bootstrap/bootstrap_test.go
  pkg/hakeeper/checker.go
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/check_test.go
  pkg/hakeeper/checkers/logservice/parse.go
  pkg/hakeeper/checkers/logservice/parse_test.go
  pkg/hakeeper/checkers/syshealth/check.go
  pkg/hakeeper/checkers/syshealth/check_test.go
  pkg/hakeeper/checkers/util/store.go
  pkg/hakeeper/config.go
  pkg/hakeeper/config_test.go
  pkg/logservice/store.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/txn/txn.pb.go
  proto/logservice.proto
Labels: kind/feature

#4079 update applying append node during commit
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, kind/refactor, component/standalone tae, component/distributed tae

#4105 (tae): fix mvcc bug
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
  pkg/vm/engine/tae/tables/updates/updateview.go
Labels: kind/bug, component/standalone tae

#4119 make clean cgo *.o, *.a files
  Makefile
Labels: kind/bug

#4129 Skip TestReplay7 ut
  pkg/vm/engine/tae/db/replay_test.go
Labels: unit-test-failed, size/XS

#4137 Add constraint for CTE, update sql faq
  docs/en/MatrixOne/FAQs/sql-faqs.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/with-cte.md
Labels: size/XS

#4140 Modify hashmap
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/common/hashmap/types.go
Labels: size/l

#4136 fileservice: call Sync in LocalFS.Mutate
  pkg/fileservice/local_fs.go
Labels: size/XS

#4141 fix data race in frontend module
  pkg/frontend/routine_manager.go
Labels: size/XS

#4138 [Plan] Support row constructor with subquery
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/query_builder.go
  proto/plan.proto
  test/cases/subquery/subquery-with-any.sql
  test/cases/subquery/subquery-with-in.sql
  test/result/subquery/subquery-with-any.result
  test/result/subquery/subquery-with-in.result
Labels: size/xxl

#4146 Add analyze info and memory limit for operator
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/merge/merge_test.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergelimit/types.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergeoffset/types.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/restrict/restrict.go
  pkg/sql/colexec2/limit/limit.go
  pkg/sql/colexec2/limit/limit_test.go
  pkg/sql/colexec2/limit/types.go
  pkg/sql/colexec2/merge/merge.go
  pkg/sql/colexec2/merge/merge_test.go
  pkg/sql/colexec2/merge/types.go
  pkg/sql/colexec2/mergelimit/limit.go
  pkg/sql/colexec2/mergelimit/limit_test.go
  pkg/sql/colexec2/mergelimit/types.go
  pkg/sql/colexec2/mergeoffset/offset.go
  pkg/sql/colexec2/mergeoffset/offset_test.go
  pkg/sql/colexec2/mergeoffset/types.go
  pkg/sql/colexec2/offset/offset.go
  pkg/sql/colexec2/offset/offset_test.go
  pkg/sql/colexec2/offset/types.go
  pkg/sql/colexec2/restrict/restrict.go
  pkg/sql/colexec2/restrict/types.go
  pkg/sql/compile/compile_test.go
  pkg/testutil/util_new.go
  pkg/vm/process/process.go
Labels: size/xxl

#4149 Retag some #3304 cases
  test/cases/expression/cte.sql
  test/cases/subquery/subquery-with-any.sql
  test/cases/subquery/subquery-with-exists.sql
  test/cases/subquery/subquery-with-in.sql
Labels: size/m

#4150 Fix agg and disagg string type init issue
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
Labels: size/s

#4156 txn: format txn log
  pkg/pb/metadata/metadata.go
  pkg/pb/timestamp/timestamp.go
  pkg/pb/txn/txn.go
  pkg/txn/client/operator.go
  pkg/txn/service/service.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_dn_handler.go
  pkg/txn/service/service_recovery.go
  pkg/txn/util/log.go
Labels: size/xl

#4154 fix install doc-descriptionversionbug and delete $ and update case...when doc
  docs/cn/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
  docs/cn/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
  docs/cn/MatrixOne/Get-Started/Tutorial/TPCH-test-with-matrixone.md
  docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/case.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/from-subquery.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-any-some.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
  docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions.md
  docs/en/MatrixOne/Contribution-Guide/Tutorial/develop_builtin_functions.md
  docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
  docs/en/MatrixOne/Get-Started/Tutorial/TPCH-test-with-matrixone.md
  docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/case.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-any-some.md
Labels: size/XS

#4159 remove cgo env vars from go file
  pkg/common/bitmap/cbitmap.go
Labels: size/XS

#4161 Modify the makefile to generate only one static library libmo
  Makefile
  cgo/.gitignore
  cgo/Makefile
  optools/run_ut.sh
  pkg/container/types/decimal.go
Labels: size/s, do-not-merge/wip

#4145 update MaxSizeRotateChecker
  pkg/vm/engine/tae/logstore/store/checker.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/wal/wal_test.go
Labels: size/m

#4155 Add Ut and fix intHashTable bugs
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/inthashmap_test.go
  pkg/common/hashmap/iterator.go
Labels: size/m

#4162 label size modify
  .github/workflows/labeler.yml
Labels: size/XS

#4164 Remove static check errors
  pkg/config/test/config_template.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
Labels: size/m

#4170 Modify the compile options in yum
  .github/workflows/robot.yml
  pkg/common/bitmap/cbitmap.go
Labels: size/XS

#4171 Add constraint for CTE, update sql faq and edit subquries docs
  docs/cn/MatrixOne/FAQs/sql-faqs.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/comparisons-using-subqueries.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/derived-tables.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/from-subquery.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-all.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subquery.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/with-cte.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/comparisons-using-subqueries.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/derived-tables.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/from-subquery.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-all.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subquery.md
Labels: size/XS

#4167 fileservice: add ETLFileService, LocalETLFS
  pkg/fileservice/etl_file_service.go
  pkg/fileservice/io.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_minio.go
Labels: size/l

#4181 remove usages of ioutil package
  cmd/generate-config/config_template.go
  pkg/config/test/config_template.go
  pkg/fileservice/memory_fs.go
  pkg/sql/parsers/goyacc/goyacc.go
  pkg/sql/plan/build_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/replay.go
Labels: size/s

#4182 Makefile: report all errors identified by static-check
  Makefile
  pkg/sql/plan/visit_query.go
  pkg/vm/engine/tae/logstore/store/file.go
Labels: size/s

#4188 ci: added dependency license check
  .licenserc.yml
  Makefile
  go.mod
  go.sum
Labels: size/s

#4195 Remove recover from stopper
  pkg/common/stopper/stopper.go
Labels: size/XS

#4166 change cast rule
  pkg/sql/plan/function/type_check.go
  test/result/expression/case_when.result
Labels: size/s

#4160 fix cast number to bool bug
  pkg/sql/plan/function/builtin/binary/typecast.go
  test/result/operator/operator.result
Labels: size/s

#4177 delete mo tech design
  docs/cn/MatrixOne/Contribution-Guide/Code-Style/code-comment-style.md
  docs/cn/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
  docs/cn/MatrixOne/Overview/matrixone-architecture.md
  docs/cn/MatrixOne/glossary.md
  docs/cn/README.md
  docs/en/MatrixOne/Contribution-Guide/Code-Style/code-comment-style.md
  docs/en/MatrixOne/Contribution-Guide/Code-Style/code-of-conduct.md
  docs/en/MatrixOne/Contribution-Guide/Code-Style/commit-pr-style.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-code.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/contribute-documentation.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/make-a-design.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/report-an-issue.md
  docs/en/MatrixOne/Contribution-Guide/How-to-Contribute/review-a-pull-request.md
  docs/en/MatrixOne/Contribution-Guide/make-your-first-contribution.md
  docs/en/MatrixOne/Develop/develop_python_application.md
  docs/en/MatrixOne/FAQs/deployment-faqs.md
  docs/en/MatrixOne/FAQs/product-faqs.md
  docs/en/MatrixOne/FAQs/sql-faqs.md
  docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Overview/matrixone-architecture.md
  docs/en/MatrixOne/Overview/matrixone-introduction.md
  docs/en/MatrixOne/Test/mo-tester.md
  docs/en/MatrixOne/glossary.md
Labels: size/XS

#4148 hakeeper: update cluster details query
  pkg/hakeeper/config.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/store.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/txn/txn.pb.go
  proto/logservice.proto
Labels: kind/feature, kind/subtask

#4199 fileservice: add IOEntry.Object, ToObject
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_minio.go
Labels: size/l

#4208 fix union operator bug and update some comments for hash map
  pkg/common/hashmap/types.go
  pkg/sql/colexec/union/union.go
  pkg/sql/colexec/union/union_test.go
Labels: size/m

#4203 hakeeper: fix resend start&stop command bug
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/check_test.go
  pkg/hakeeper/checkers/logservice/filter.go
  pkg/hakeeper/checkers/logservice/filter_test.go
  pkg/hakeeper/checkers/logservice/parse.go
  pkg/hakeeper/checkers/logservice/parse_test.go
  pkg/hakeeper/checkers/logservice/stats.go
  pkg/hakeeper/checkers/syshealth/check.go
  pkg/hakeeper/checkers/syshealth/check_test.go
  pkg/hakeeper/checkers/util/filter.go
  pkg/hakeeper/checkers/util/store.go
  pkg/hakeeper/operator/builder.go
  pkg/hakeeper/operator/builder_test.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/controller_test.go
  pkg/hakeeper/operator/create_operator.go
  pkg/hakeeper/operator/operator_test.go
  pkg/hakeeper/operator/steps.go
  pkg/hakeeper/operator/steps_test.go
Labels: kind/feature

#4174 reset default precision for datetime
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/builtin/multi/date_add.go
  pkg/sql/plan/function/builtin/multi/date_sub.go
  test/result/expression/temporal_interval.result
  test/result/function/func_datetime_date_add.result
Labels: size/m

#4214 optimize checkpoint in replay
  pkg/vm/engine/tae/logstore/store/replayer.go
Labels: size/XS

#4212 dnservice: update default service address
  pkg/dnservice/cfg.go
  pkg/dnservice/cfg_test.go
Labels: size/XS

#4220 config: add minmal dn test config
  cmd/mo-service/cfg.go
  cmd/mo-service/cfg_test.go
  etc/dn-minimal-test.toml
Labels: size/m

#4222 dnservice: fix config toml tag error
  pkg/dnservice/cfg.go
Labels: size/XS

#4221 logservice: added the ability to build log service
  Makefile
  cmd/mo-service/cfg.go
  cmd/mo-service/main.go
  pkg/logservice/commands.go
  pkg/logservice/commands_test.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/hakeeper_checker_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/logservice/testclient.go
Labels: size/l

#4224 logservice: fixed some issues that prevented logservice from starting
  .gitignore
  etc/log-minimal-test.toml
  go.mod
  go.sum
  pkg/logservice/commands.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/service.go
Labels: size/m

#4219 Added the ability for a hashmap to handle buckets, and then modified the union implementation to stream the output
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/inthashmap_test.go
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/common/hashmap/types.go
  pkg/container/hashtable/bucket.go
  pkg/sql/colexec/union/types.go
  pkg/sql/colexec/union/union.go
  pkg/sql/colexec/union/union_test.go
  pkg/testutil/util_new.go
Labels: size/xl

#4216 Support update for multiple-table
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
  test/cases/dml/update/update.test
  test/result/dml/update/update.result
Labels: size/xxl

#4233 Fix some bugs of delete
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_update.go
  proto/plan.proto
  test/cases/dml/delete/delete.test
  test/result/dml/delete/delete.result
Labels: size/l

#4232 fix querytype bug
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS

#4231 Use hashmap to refactor join and support analyze
  pkg/cnservice/server.go
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/types.go
  pkg/container/batch/batch.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/restrict/restrict.go
  pkg/sql/compile/operator.go
  pkg/vm/process/process.go
Labels: size/xl

#4235 txn: fix prepare conflict check
  pkg/txn/storage/mem/kv_txn_storage.go
  pkg/txn/storage/mem/kv_txn_storage_test.go
Labels: size/XS

#4236 logservice: allow cluster to be bootstrapped using toml config file
  cmd/mo-service/main.go
  etc/log-minimal-test.toml
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/hakeeper_checker.go
  pkg/logservice/hakeeper_checker_test.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/store.go
Labels: size/l

#4217 Rework arithmetic operators.
  cgo/decimal.c
  cgo/mo.h
  pkg/common/bitmap/bitmap.go
  pkg/container/nulls/nulls.go
  pkg/container/types/decimal.go
  pkg/sql/plan/function/operator/arith.go
  pkg/sql/plan/function/operator/plus.go
  pkg/sql/plan/function/operator/plus_test.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/add/add.go
  pkg/vectorize/add/add_test.go
  pkg/vectorize/add/dec.go
Labels: size/xxl

#4243 fileservice: add create fileservice from config
  pkg/fileservice/config.go
  pkg/fileservice/s3.go
Labels: size/m

#4246 fileservice: add VfsFS for testing uses
  pkg/fileservice/vfs_fs.go
  pkg/fileservice/vfs_fs_test.go
Labels: size/l

#4238 Makefile: specify what versions of SCA tools to use
  Makefile
Labels: size/XS

#4240 Fengttt 3458 add
  cgo/arith.c
  cgo/bitmap.h
  cgo/decimal.c
  cgo/mo.c
  cgo/mo.h
  cgo/test/.gitignore
  cgo/test/Makefile
  cgo/test/test_add.c
  pkg/vectorize/add/add.go
  pkg/vectorize/add/add_test.go
  pkg/vectorize/add/dec.go
Labels: size/xxl

#4248 sketch TAE storage
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/txn/storage/tae/storage.go
Labels: size/l

#4237 logservice: minor fix for TestHAKeeperCanBootstrapAndRepairShards
  pkg/logservice/hakeeper_checker_test.go
Labels: size/XS

#4249 fileservice: add new file service from config
  pkg/fileservice/config.go
  pkg/fileservice/s3.go
Labels: size/m

#4255 logservice: fixed dragonboat.ErrInvalidDeadline handling
  pkg/logservice/errors.go
  pkg/logservice/errors_test.go
Labels: size/s

#4252 logservice: fixed duplicated shard metadata record
  pkg/logservice/store_metadata.go
  pkg/logservice/store_metadata_test.go
Labels: size/s

#4261 update minimal dn config file
  cmd/mo-service/cfg_test.go
  etc/dn-minimal-test.toml
Labels: size/m

#4260 dnservice: remove datadir config
  pkg/dnservice/cfg.go
  pkg/dnservice/cfg_test.go
  pkg/dnservice/store_test.go
Labels: size/XS

#4253 fix errors
  cmd/generate-config/config_template.go
  cmd/generate-config/config_template_test.go
  cmd/generate-config/main.go
  cmd/generate-config/system_vars_def.toml
  cmd/generate-config/test/def1.toml
  cmd/generate-config/test/def2.toml
  cmd/generate-config/test/system_vars_def.toml
  cmd/generate-config/test/t1.toml
  cmd/generate-config/test/t2.toml
  go.mod
  pkg/config/configuration.go
  pkg/config/test/.gitignore
  pkg/config/test/config.toml
  pkg/config/test/config_template.go
  pkg/config/test/system_vars_config.toml
  pkg/config/test/varconfig.toml
  pkg/frontend/load.go
  pkg/frontend/load_test.go
Labels: size/xxl

#4262 hakeeper: remove schedule commands after heartbeat
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_checker_test.go
  pkg/logservice/service.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: size/l

#4264 logservice: added config files for 3 nodes log service
  etc/bootstrap-example/README.md
  etc/bootstrap-example/log-node-1.toml
  etc/bootstrap-example/log-node-2.toml
  etc/bootstrap-example/log-node-3.toml
  pkg/hakeeper/rsm.go
  pkg/logservice/service_bootstrap.go
Labels: size/l

#4270 Support intersect/except/minus in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/union.go
Labels: size/xxl

#4274 morpc: mark backend inactive if reconnect fail
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: size/m

#4276 morpc: skip inactive backends
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/client.go
  pkg/common/morpc/client_test.go
  pkg/common/morpc/server_test.go
  pkg/logservice/client.go
  pkg/txn/rpc/sender_test.go
Labels: size/l

#4244 Add #3738 bvt tag
  test/cases/function/func_string_lpad_rpad.test
Labels: size/XS

#4280 mo-service: remove uuid from cmd line
  cmd/mo-service/main.go
  etc/dn-minimal-s3-test.toml
  etc/dn-minimal-test.toml
Labels: size/s

#4168 support text type
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/container/types/bytes.go
  pkg/container/types/types.go
  pkg/container/vector/vector.go
  pkg/frontend/insert.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/pb/plan/plan.pb.go
  pkg/sort/sort.go
  pkg/sql/colexec/aggregate/aggregate.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/update.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/aggregate.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/operator/case_when.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operator/if.go
  pkg/sql/plan/function/operator/isnotnull_test.go
  pkg/sql/plan/function/operator/isnull_test.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/function/type_check.go
  pkg/testutil/types.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/moengine/utils.go
  pkg/vm/engine/tae/types/types.go
  proto/plan.proto
  test/cases/dtype/text.test
  test/result/dtype/text.result
Labels: size/xxl

#4275 add "\"" to string type data when export to file
  pkg/frontend/export.go
Labels: kind/bug, size/XS

#4282 fix cmd_field_list
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/types.go
Labels: kind/bug

#4234 Implements integration test framework for `dn` and `log` services;
  pkg/logservice/service_wrap.go
  pkg/tests/service/address.go
  pkg/tests/service/address_test.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/doc.go
  pkg/tests/service/errors.go
  pkg/tests/service/fileservice.go
  pkg/tests/service/fileservice_test.go
  pkg/tests/service/logservice.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
Labels: priority/p1, kind/feature

#4279 txnengine: gob register all TableDef types
  pkg/vm/engine/txn/operations.go
Labels: kind/bug, size/XS

#4284 logservice: minor tweaks on connection timeout
  pkg/logservice/client.go
  pkg/logservice/commands.go
Labels: kind/enhancement, size/s

#4286 add txnstorage package
  go.mod
  go.sum
  pkg/txn/storage/txn/alias.go
  pkg/txn/storage/txn/catalog.go
  pkg/txn/storage/txn/handler.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mem_handler_test.go
  pkg/txn/storage/txn/mvcc.go
  pkg/txn/storage/txn/mvcc_test.go
  pkg/txn/storage/txn/read.go
  pkg/txn/storage/txn/read_result.go
  pkg/txn/storage/txn/storage.go
  pkg/txn/storage/txn/storage_test.go
  pkg/txn/storage/txn/table.go
  pkg/txn/storage/txn/table_iter.go
  pkg/txn/storage/txn/table_test.go
  pkg/txn/storage/txn/transaction.go
  pkg/txn/storage/txn/types.go
  pkg/txn/storage/txn/write.go
  pkg/vm/engine/txn/operations.go
Labels: kind/enhancement, size/xxl

#4287 morpc: fix close data race
  pkg/common/morpc/server.go
Labels: kind/bug

#4288 morpc: upgrade goetty
  go.mod
  go.sum
Labels: kind/enhancement, size/XS

#4289 logservice: updated logservice configurations
  .gitignore
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  etc/bootstrap-example/log-node-1.toml
  etc/bootstrap-example/log-node-2.toml
  etc/bootstrap-example/log-node-3.toml
  etc/log-minimal-test.toml
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_commands.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_test.go
  pkg/logservice/testclient.go
  pkg/tests/service/logservice.go
Labels: kind/enhancement, size/l

#4285 Make `TestCluster` runnable and restructure implementation.
  pkg/tests/service/logservice.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
Labels: priority/p1, kind/feature, size/l

#4292 fix ineffictiveassign static check
  pkg/common/morpc/examples/message/message.go
Labels: kind/bug, size/XS

#4293 ci: enforce license compatibility check on all dependencies
  .licenserc.yml
  go.mod
  go.sum
Labels: size/s, kind/test-ci
