Repository matrixorigin/matrixone, pull requests merged in 2022-11, with the labels that each got.

#6117 hakeeper: support set moadmin from env
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
Labels: kind/feature, size/S

#6144 Update ci.yml
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#6140 We should not log errors
  pkg/frontend/session.go
Labels: kind/refactor, size/XS

#6134 add create sql for database
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, size/M

#6145 CI: extended mergify timeout and add base check
  .github/mergify.yml
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#6141 mpool fixes.
  pkg/common/mpool/mpool.go
  pkg/container/batch/batch.go
  pkg/vectorize/shuffle/shuffle.go
Labels: kind/bug, size/S

#6149 Modify mergify
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#6111 improve: reduce unnecessary cast
  pkg/container/types/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/init.go
  pkg/sql/plan/make.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/gob.go
  proto/plan.proto
Labels: kind/enhancement, size/L

#6147 Fix mpool shrink to 0.
  pkg/common/mpool/mpool.go
  pkg/container/types/encoding.go
  pkg/container/vector/vector.go
Labels: kind/bug, size/S

#6150 fix issue about limit/offset para is string
  pkg/sql/plan/limit_binder.go
Labels: kind/bug, size/S

#6062 Implement the built in function str_to_date
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  pkg/container/vector/vector.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/binary/date_format.go
  pkg/sql/plan/function/builtin/binary/generalTime.go
  pkg/sql/plan/function/builtin/binary/str_to_date.go
  pkg/sql/plan/function/builtin/binary/str_to_date_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/make.go
  test/cases/dml/update/update_multiple_table.sql
  test/cases/function/func_str_to_date.sql
  test/distributed/cases/dml/update/update_multiple_table.sql
  test/distributed/cases/function/func_str_to_date.sql
  test/distributed/result/dml/update/update_multiple_table.result
  test/distributed/result/function/func_str_to_date.result
  test/distributed/result/function/func_string_space.result
  test/result/dml/update/update_multiple_table.result
  test/result/function/func_str_to_date.result
  test/result/function/func_string_space.result
Labels: kind/bug, kind/feature, size/XXL

#6131 Optimize pipeline logic for limit and offset. Remove redundant bitmap code. Fix vector shrink bug.
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
  pkg/container/nulls/nulls.go
  pkg/container/vector/vector.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/types.go
Labels: kind/bug, kind/enhancement, size/M

#6161 Replace NiLei's repo with matrixorigin's.
  go.mod
  go.sum
Labels: size/S, kind/refactor

#6159 Corrections for debug pb
  pkg/pb/debug/debug.pb.go
  proto/debug.proto
Labels: kind/refactor, size/XS

#6137 logservice: support config gossip with 1 replica
  etc/launch-flush-tae-CN-tae-DN/cn.toml
  etc/launch-flush-tae-CN-tae-DN/dn.toml
  etc/launch-flush-tae-CN-tae-DN/log.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-logservice/log.toml
  go.mod
  go.sum
  pkg/logservice/config.go
  pkg/logservice/store.go
  pkg/tests/service/logservice.go
  pkg/tests/service/network_test.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
Labels: kind/enhancement, size/M

#6173 tests: disable multi dn tests
  pkg/tests/service/service_test.go
Labels: size/S, kind/test-ci

#6167 log stacktrace info while dragonboat/v4 log error
  pkg/logutil/adapt_cron.go
  pkg/logutil/dragonboat.go
  pkg/logutil/dragonboat_test.go
Labels: kind/enhancement, size/XS

#6155 Fix bugs #5930,#6102
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.test
  test/distributed/result/dml/show/show.result
Labels: kind/bug, size/S

#6174 feat: add make ci
  .dockerignore
  .gitignore
  Makefile
  go.mod
  optools/bvt_ut/Dockerfile
  optools/bvt_ut/entrypoint.sh
  optools/image_builder/Dockerfile
  optools/image_builder/entrypoint.sh
  optools/run_ut.sh
  optools/test/Dockerfile.bvt
  optools/test/Dockerfile.mo
  optools/test/config.toml
  optools/test/docker-compose.yaml
  optools/test/entrypoint.sh
Labels: size/L, kind/test-ci

#6181 upgrade goetty to fix panic
  go.mod
  go.sum
Labels: kind/bug, size/XS

#6177 add projects milestone
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#6194 git ignore tester-log.
  .gitignore
Labels: kind/test-ci

#6183 small code refactor
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/dbbase.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
Labels: size/M, kind/refactor

#6158 skip not found when collecting logtail
  pkg/vm/engine/tae/logtail/operator.go
Labels: size/S

#6186 log: add some close log
  pkg/cnservice/server.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/server_task.go
  pkg/logutil/action.go
  pkg/taskservice/task_service_holder.go
  pkg/tests/service/service.go
Labels: kind/enhancement, size/S

#6195 cnservice: fix deadlock in task executor
  pkg/cnservice/server_task.go
Labels: kind/bug, size/S

#6200 fix: docker build ignore bvt generate files
  .dockerignore
Labels: kind/enhancement, size/S

#6193 refactor mergeOrder operator
  pkg/container/nulls/nulls.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/compile/compile.go
Labels: kind/enhancement, size/S

#6192 support table subquery without alias
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/query_builder.go
  test/cases/subquery/from-subquery.sql
  test/distributed/cases/subquery/from-subquery.sql
  test/distributed/result/subquery/from-subquery.result
  test/result/subquery/from-subquery.result
Labels: size/XXL

#6164 fix create task table too often
  pkg/logservice/store_hakeeper_check_test.go
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/task_service_holder.go
Labels: kind/bug, size/S

#6202 fix mPool id error caused by remote-run's batch didn't allocated from mPool.
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/compile/cnserviceDriver.go
Labels: kind/bug, size/S

#6204 tests: fix cluster test
  pkg/cnservice/server.go
  pkg/logservice/service_wrap.go
  pkg/logutil/api.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/logservice.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
  pkg/tests/service/task_test.go
  pkg/tests/txn/sql_client.go
Labels: kind/bug, size/M, kind/test-ci

#6170 Fix bug unix timestamp
  pkg/container/types/timestamp.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/multi/unix_timestamp.go
  pkg/sql/plan/function/builtin/multi/unix_timestamp_test.go
  pkg/sql/plan/function/builtins.go
  pkg/vectorize/unixtimestamp/unixtimestamp.go
  pkg/vectorize/unixtimestamp/unixtimestamp_test.go
Labels: kind/bug, size/M

#5625 Fix tablefunction not support expr
  pkg/container/bytejson/bytejson.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/colexec/generate_series/generate_series.go
  pkg/sql/colexec/generate_series/generate_series_test.go
  pkg/sql/colexec/generate_series/types.go
  pkg/sql/colexec/unnest/types.go
  pkg/sql/colexec/unnest/unnest.go
  pkg/sql/colexec/unnest/unnest_test.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/cnserviceDriver_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/table_function.go
  pkg/sql/parsers/tree/unnest.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/builtin/binary/json_extract.go
  pkg/sql/plan/function/builtin/binary/json_extract_test.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/unnest.go
  pkg/sql/plan/utils.go
  pkg/vectorize/json_extract/json_extract.go
  pkg/vectorize/json_extract/json_extract_test.go
  proto/pipeline.proto
  proto/plan.proto
  test/cases/function/func_json_extract.test
  test/cases/function/table_func_generate_series.test
  test/cases/function/table_func_unnest.test
  test/distributed/cases/function/func_json_extract.test
  test/distributed/cases/function/table_func_generate_series.test
  test/distributed/cases/function/table_func_unnest.test
  test/distributed/result/function/func_json_extract.result
  test/distributed/result/function/table_func_generate_series.result
  test/distributed/result/function/table_func_unnest.result
  test/result/function/func_json_extract.result
  test/result/function/table_func_generate_series.result
  test/result/function/table_func_unnest.result
Labels: kind/bug, kind/feature, size/XXL

#6156 Fix 5895:system table "statement_info"，Query with UNION ALL，Return ERROR
  pkg/sql/plan/function/operator/case_when.go
  pkg/sql/plan/function/operator/coalesce.go
  pkg/sql/plan/function/operator/if.go
  pkg/sql/plan/function/operators.go
  test/cases/function/func_coalesce.test
  test/distributed/cases/function/func_coalesce.test
  test/distributed/result/ddl/json_type.result
  test/distributed/result/function/func_coalesce.result
  test/result/ddl/json_type.result
  test/result/function/func_coalesce.result
Labels: kind/bug, size/M

#6169 fix #5406 cast datetime type precision
  pkg/sql/plan/query_builder.go
  test/cases/dml/select/minus.result
  test/cases/dml/select/minus.sql
  test/distributed/cases/dml/select/minus.result
  test/distributed/cases/dml/select/minus.sql
Labels: kind/bug, size/M

#6205 refactor duplicate error in tae
  pkg/common/moerr/error.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/dbbase.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/load_data/import_data.result
  test/cases/load_data/load_data.result
  test/cases/table/truncate_table_2.result
  test/distributed/cases/auto_increment/auto_increment_columns.result
  test/distributed/cases/load_data/import_data.result
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/table/truncate_table_2.result
  test/distributed/cases/transaction/atomicity_1.result
  test/distributed/cases/transaction/isolation_2.result
  test/distributed/result/ddl/comprimary_key.result
  test/distributed/result/ddl/partition.result
  test/distributed/result/dml/insert/insert.result
  test/distributed/result/dml/update/update.result
  test/distributed/result/prepare/prepare_all.result
  test/distributed/result/transaction/autocommit_isolation.result
  test/distributed/result/transaction/isolation.result
  test/result/ddl/comprimary_key.result
  test/result/ddl/partition.result
  test/result/dml/insert/insert.result
  test/result/dml/update/update.result
  test/result/prepare/prepare_all.result
  test/result/transaction/autocommit_isolation.result
  test/result/transaction/isolation.result
Labels: kind/enhancement, size/M, kind/refactor

#6207 [Bug]: MO doesn't recognize localhost #6152
  pkg/config/configuration.go
  pkg/frontend/server.go
Labels: kind/bug, size/S

#6212 upgrade goetty to support listen multi address
  go.mod
  go.sum
Labels: kind/enhancement, size/XS

#6191 add load data docs and tutorial docs
  README.md
  README_CN.md
  docs/cn/MatrixOne/Develop/export-data/backup-restore-matrixone-with_modump.md
  docs/cn/MatrixOne/Develop/import-data/0.6-bulk-load/load-s3.md
  docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/cn/MatrixOne/Reference/Limitations/mo-partition-support.md
  docs/cn/MatrixOne/Tutorial/connect_mo_with_orm.md
  docs/cn/MatrixOne/Tutorial/springboot-mybatis-crud-demo.md
  docs/en/MatrixOne/Develop/0.6-read-data/subquery.md
  docs/en/MatrixOne/Develop/export-data/backup-restore-matrixone-with_modump.md
  docs/en/MatrixOne/Develop/import-data/0.6-bulk-load/load-jsonline.md
  docs/en/MatrixOne/Develop/import-data/0.6-bulk-load/load-s3.md
  docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/en/MatrixOne/Reference/Limitations/mo-partition-support.md
  docs/en/MatrixOne/Tutorial/connect_mo_with_orm.md
Labels: kind/documentation, size/XS

#6211 fix TestTaskSchedulerCanReallocateTask
  pkg/taskservice/mysql_task_storage.go
  pkg/tests/service/task_test.go
Labels: kind/bug, size/S, kind/test-ci

#6213 fileservice: add []byte param to IOEntry.ToObject
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: kind/enhancement, size/S

#6215 logger: fix log config not work in logservice
  cmd/mo-service/main.go
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  pkg/cnservice/server.go
  pkg/dnservice/store.go
  pkg/logservice/service.go
  pkg/logutil/internal.go
Labels: kind/bug, size/S

#6228 checkpoint supports table granularity operations
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/feature, size/M

#6220 Fix 131: rewrite EOF and OK packets
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  test/cases/prepare/prepare.test
  test/distributed/cases/prepare/prepare.test
  test/distributed/result/prepare/prepare.result
  test/result/prepare/prepare.result
Labels: kind/documentation, size/M

#6133 add Performance Tuning docs
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-aggregation.md
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-joins.md
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-overview.md
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-subqueries.md
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-views.md
  docs/cn/MatrixOne/0.6-Performance-Tuning/explain-walkthrough.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/cn/MatrixOne/Tutorial/TPCH-test-with-matrixone.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-aggregation.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-joins.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-overview.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-subqueries.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-views.md
  docs/en/MatrixOne/0.6-Performance-Tuning/explain-walkthrough.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Overview/matrixone-feature-list.md
  docs/en/MatrixOne/Tutorial/SSB-test-with-matrixone.md
  docs/en/MatrixOne/Tutorial/TPCH-test-with-matrixone.md
Labels: kind/documentation, size/XS

#6208 remove pem test file
  pkg/frontend/test/ca-key.pem
  pkg/frontend/test/ca.pem
  pkg/frontend/test/client-cert.pem
  pkg/frontend/test/client-cert2.pem
  pkg/frontend/test/client-key.pem
  pkg/frontend/test/client-key2.pem
  pkg/frontend/test/private_key.pem
  pkg/frontend/test/public_key.pem
  pkg/frontend/test/server-cert.pem
  pkg/frontend/test/server-cert2.pem
  pkg/frontend/test/server-key.pem
  pkg/frontend/test/server-key2.pem
  pkg/frontend/test/system_vars_config.toml
Labels: kind/enhancement, size/M

#6136 fix load batch size too big bug
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/insert/insert.go
  test/cases/load_data/import_data.result
  test/distributed/cases/load_data/import_data.result
Labels: kind/bug, size/M

#6216 Open blocklist
  .github/workflows/e2e.yml
  etc/launch-flush-tae-CN-tae-DN/cn.toml
  etc/launch-flush-tae-CN-tae-DN/dn.toml
  etc/launch-flush-tae-CN-tae-DN/launch.toml
  etc/launch-flush-tae-CN-tae-DN/log.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  go.sum
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
Labels: size/M

#6227 json unnest bvt cases
  test/cases/ddl/json_type.sql
  test/distributed/cases/ddl/json_type.sql
  test/distributed/result/ddl/json_type.result
  test/result/ddl/json_type.result
Labels: size/M

#6237 Skip dumping external table data
  cmd/mo-dump/main.go
Labels: kind/bug, size/S

#6235 [Bug]: text type cast bool type, Not up to expectations. #4636
  pkg/container/types/bool.go
  pkg/sql/plan/function/operator/cast.go
  test/cases/dtype/text_1.sql
  test/distributed/cases/dtype/text_1.sql
  test/distributed/result/dtype/text_1.result
  test/distributed/result/operator/is_not_operator.result
  test/result/dtype/text_1.result
  test/result/operator/is_not_operator.result
Labels: kind/bug, size/M

#6206 Commit the off-band transactions.
  pkg/sql/plan/function/builtin/ctl/cmd_flush.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#6224 [Bug]: the result is error that the temporal interval expression is w…
  test/cases/expression/temporal_interval.sql
  test/distributed/cases/expression/temporal_interval.sql
  test/distributed/result/expression/temporal_interval.result
  test/result/expression/temporal_interval.result
Labels: kind/bug, size/S

#6247 memorystorage: remove no longer needed frontend tests
  pkg/txn/storage/memorystorage/storage_txn_client_test.go
Labels: kind/enhancement, size/M

#6241 fix replay in cn-dn without flushing
  etc/launch-tae-CN-tae-DN/dn.toml
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/txnif/memo.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/types.go
Labels: kind/bug, size/S

#6148 [Bug]: system table, panic info occured #5892
  pkg/common/bitmap/bitmap.go
  pkg/container/nulls/nulls.go
  test/cases/ddl/comprimary_key.sql
  test/cases/table/system_table_cases.sql
  test/distributed/cases/ddl/comprimary_key.sql
  test/distributed/cases/table/system_table_cases.sql
  test/distributed/resources/external_table_file/rawlog_withnull.csv
  test/distributed/result/ddl/comprimary_key.result
  test/distributed/result/table/system_table_cases.result
  test/resources/external_table_file/rawlog_withnull.csv
  test/result/ddl/comprimary_key.result
  test/result/table/system_table_cases.result
Labels: kind/bug, size/XXL

#6250 Improve point read by pk
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/enhancement, size/M

#6244 txn: make txn message max size configurable
  pkg/dnservice/store.go
  pkg/txn/rpc/cfg.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/sender_test.go
  pkg/txn/rpc/server.go
  pkg/txn/rpc/server_test.go
  pkg/txn/rpc/types.go
Labels: kind/enhancement, size/M

#6231 fix #5285 decimal plus scale problem
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function.go
  test/cases/dtype/decimal.test
  test/distributed/cases/dtype/decimal.test
  test/distributed/result/dtype/decimal.result
  test/result/dtype/decimal.result
Labels: kind/bug, size/M

#6253 Add a loop for auto incr value.
  pkg/sql/colexec/auto_incr.go
Labels: kind/bug, size/S

#6255 rpc: modify deafult max message size to 100MB
  pkg/common/morpc/codec.go
  pkg/txn/rpc/cfg.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/server.go
Labels: kind/enhancement, size/S

#6257 dnservice: get main fs and temp fs and pass to TAE explicitly
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/server.go
  pkg/cnservice/server_metadata_test.go
  pkg/defines/const.go
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/dnservice/store.go
  pkg/dnservice/store_metadata_test.go
  pkg/dnservice/store_test.go
  pkg/logutil/adapt_s3.go
  pkg/objectio/fs.go
  pkg/objectio/writer_test.go
  pkg/tests/service/fileservice.go
  pkg/tests/service/service.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/dataio/blockio/writer.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/bug, size/M

#6262 fileservice: set a background context if passed argument is nil
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#6265 Sukki37 patch 10
  .github/workflows/e2e.yml
Labels: size/XS, kind/test-ci

#6229 Objectio added lz4 compression
  CODEOWNERS
  pkg/objectio/column.go
  pkg/objectio/index.go
  pkg/objectio/reader.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/dataio/blockio/read.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/tables/evictable/coldata.go
  pkg/vm/engine/tae/tables/evictable/deltadata.go
Labels: kind/feature, size/M

#6223 fix limit issue and show databases issue
  pkg/sql/plan/build_show.go
  pkg/sql/plan/limit_binder.go
  test/cases/accesscontrol/create_account.sql
  test/cases/accesscontrol/inner_object.sql
  test/distributed/cases/zz_accesscontrol/create_account.sql
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/bug, size/S

#6252 [Bug]: text type cast bool type, Not up to expectations. #4636
  pkg/container/types/bool.go
  pkg/sql/plan/function/operator/cast.go
  test/cases/dtype/text_1.sql
  test/cases/operator/is_not_operator.sql
  test/distributed/cases/dtype/text_1.sql
  test/distributed/cases/operator/is_not_operator.sql
  test/distributed/result/dtype/text_1.result
  test/distributed/result/operator/is_not_operator.result
  test/result/dtype/text_1.result
  test/result/operator/is_not_operator.result
Labels: kind/bug, size/M

#6239 Jdbc parse auto commit on
  pkg/frontend/variables.go
  test/cases/transaction/autocommit_1.sql
  test/distributed/result/database/system_variables.result
  test/result/database/system_variables.result
  test/result/transaction/autocommit_1.result
Labels: kind/bug, size/M

#6259 remove bvt tag
  test/cases/ddl/comprimary_key.sql
  test/cases/ddl/partition.sql
  test/cases/table/external_table.result
  test/cases/table/external_table.sql
  test/distributed/cases/ddl/comprimary_key.sql
  test/distributed/cases/ddl/partition.sql
  test/distributed/cases/table/external_table.result
  test/distributed/cases/table/external_table.sql
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_account.sql
  test/distributed/result/ddl/comprimary_key.result
  test/distributed/result/ddl/partition.result
  test/result/ddl/comprimary_key.result
  test/result/ddl/partition.result
Labels: size/M, kind/test-ci

#6285 Remove error use of context
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/engine/disttae/database.go
Labels: kind/bug, size/S

#6248 fileservice: fix initialization of dyanmic s3 fs
  pkg/fileservice/get.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/S

#6287 fix find pk value bug
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/XS

#6267 fix some bugs
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/dml.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
Labels: size/XXL

#6278 [Feature Request]: Problem with sqlalchemy #2174
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#6291 Fix #6275:batch insert stuck
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#6258 fix table join external table bug
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  proto/pipeline.proto
  test/cases/table/external_table.result
  test/cases/table/external_table.sql
  test/distributed/cases/table/external_table.result
  test/distributed/cases/table/external_table.sql
Labels: kind/bug, size/S

#6283 use process ctx insteal of context.TODO()
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: size/S

#6251 Fix bug: panic in needRead function
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopsemi/join_test.go
  pkg/sql/colexec/loopsingle/join_test.go
  pkg/sql/colexec/mark/join_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/make.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  test/distributed/cases/prepare/prepare_like.sql
Labels: kind/bug, size/S

#6274 Revert "[Bug]: the cast from datetime to timestamp doesn't handle out…
  pkg/sql/plan/function/builtin/multi/unix_timestamp_test.go
  pkg/vectorize/unixtimestamp/unixtimestamp.go
  test/distributed/result/function/func_datetime_unixtime.result
  test/result/function/func_datetime_unixtime.result
Labels: size/S, kind/test-ci

#6059 disttae: add transaction workspace and check primary key
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/index.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/transaction/atomicity_1.result
  test/distributed/cases/transaction/isolation_2.result
  test/distributed/result/transaction/autocommit_isolation.result
  test/distributed/result/transaction/isolation.result
Labels: kind/enhancement, size/M

#6230 fix bug
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_predefines.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  test/cases/database/system_variables.sql
  test/distributed/cases/database/system_variables.sql
  test/distributed/result/database/system_variables.result
  test/result/database/system_variables.result
Labels: size/XL

#6277 support load from s3
  pkg/fileservice/file_service_test.go
  pkg/fileservice/path.go
  pkg/fileservice/s3_fs_test.go
  pkg/sql/colexec/external/external.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_ddl.go
Labels: kind/bug, size/XXL

#6293 fix getpendding
  pkg/vm/engine/tae/logstore/store/walinfo.go
Labels: kind/bug, size/XS

#6279 add create show table composite primary key info
  pkg/sql/plan/build_show.go
  test/distributed/result/ddl/comprimary_key.result
  test/result/ddl/comprimary_key.result
Labels: size/S

#6201 Fix const time/datetime/timestamp/date bugs in eval_expr
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/build_expr_test.go
Labels: kind/bug, size/M

#6296 remove panic
  go.mod
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
Labels: size/S

#6292 Modify bvt result for #4510
  test/distributed/cases/prepare/prepare_all.sql
  test/distributed/result/prepare/prepare_all.result
Labels: size/S, kind/test-ci

#6289 [feat] logservice: make RPC message max size configurable
  pkg/cnservice/tae.go
  pkg/dnservice/factory.go
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/config.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/shardinfo.go
Labels: kind/feature, size/M

#6300 Fix timediff bug for #6197 #6199
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/binary/timediff.go
  pkg/sql/plan/function/builtin/binary/timediff_test.go
  pkg/sql/plan/function/builtins.go
  pkg/vectorize/timediff/timediff.go
  pkg/vectorize/timediff/timediff_test.go
  test/cases/function/func_datetime_timediff.test
  test/distributed/cases/function/func_datetime_timediff.test
  test/distributed/result/function/func_datetime_timediff.result
  test/result/function/func_datetime_timediff.result
Labels: kind/bug, size/M

#6290 use S3 as main fs in both CN and DN
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/server.go
  pkg/cnservice/server_metadata_test.go
  pkg/defines/const.go
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/dnservice/store.go
  pkg/dnservice/store_metadata_test.go
  pkg/dnservice/store_test.go
  pkg/logutil/adapt_s3.go
  pkg/objectio/fs.go
  pkg/objectio/writer_test.go
  pkg/tests/service/fileservice.go
  pkg/tests/service/service.go
  pkg/util/export/fs_writer.go
  pkg/util/export/fs_writer_test.go
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
Labels: kind/bug, size/M

#6303 Allow legal correlated columns in CTEs
  pkg/sql/plan/query_builder.go
  test/cases/expression/cte.sql
  test/distributed/cases/expression/cte.sql
  test/distributed/result/expression/cte.result
  test/result/expression/cte.result
Labels: kind/bug, size/S

#6307 Bugfix stmt status running and record missing txn_id
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/report_statement.go
Labels: kind/bug, size/S

#6264 Make dbeaver display mo columns meta
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/builtin/binary/show_visible_bin.go
  pkg/sql/plan/function/builtin/binary/show_visible_bin_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/util/sysview/sysview.go
  test/cases/database/system_table.sql
  test/cases/database/system_variables.sql
  test/cases/table/truncate_table_2.result
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/table/truncate_table_2.result
  test/distributed/result/database/system_table.result
  test/distributed/result/database/system_variables.result
  test/distributed/result/table/system_table_cases.result
  test/result/database/system_table.result
  test/result/database/system_variables.result
  test/result/table/system_table_cases.result
Labels: kind/bug, size/M

#6297 [Bug]: text cast as char(1), Not up to expectations. #4634
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/query_builder.go
  test/cases/dtype/text_1.sql
  test/cases/dtype/uuid_type_and_uuid_func.result
  test/cases/function/func_string_reverse.test
  test/cases/function/func_string_rtrim_ltrim.test
  test/distributed/cases/dtype/text_1.sql
  test/distributed/cases/dtype/uuid_type_and_uuid_func.result
  test/distributed/cases/function/func_string_reverse.test
  test/distributed/cases/function/func_string_rtrim_ltrim.test
  test/distributed/result/dml/insert/insert_with_function.result
  test/distributed/result/dtype/text_1.result
  test/distributed/result/function/func_string_reverse.result
  test/distributed/result/function/func_string_rtrim_ltrim.result
  test/result/dml/insert/insert_with_function.result
  test/result/dtype/char.result
  test/result/dtype/text_1.result
  test/result/function/func_string_reverse.result
  test/result/function/func_string_rtrim_ltrim.result
Labels: kind/bug, size/M

#6282 set load batch size
  pkg/cnservice/server.go
  pkg/common/morpc/codec.go
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/parsers/tree/update.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#6316 set load batch size
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
Labels: kind/bug, size/S

#6298 Bugfix: redurce memory use in merge task
  CODEOWNERS
  cmd/mo-service/main.go
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/export/example/main.go
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
  pkg/util/export/table.go
  pkg/util/export/table_test.go
Labels: kind/bug, size/L

#6308 Modify the memory usage rules of the mo hash map
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: size/M, kind/refactor

#6315 Fix primary index read bug. #6280.
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/dataio/blockio/read.go
Labels: kind/bug, size/S

#6273 add rpc-client tags & fix goroutine leaks in cn
  pkg/cnservice/cnclient/client.go
  pkg/cnservice/server.go
  pkg/cnservice/tae.go
  pkg/common/morpc/client.go
  pkg/common/stopper/stopper.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/logservice/client.go
  pkg/logservice/config.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/service.go
  pkg/logservice/shardinfo.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
  pkg/tests/service/task_test.go
  pkg/tests/txn/cluster.go
  pkg/tests/txn/cluster_basic_test.go
  pkg/tests/txn/sql_client.go
  pkg/txn/client/client.go
  pkg/txn/client/types.go
  pkg/txn/rpc/cfg.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/tae/moengine/txn_wrapper.go
  pkg/vm/engine/tae/tasks/poolhandler.go
Labels: kind/bug, size/M

#6322 CN-DN supports s3 checkpoint&replay
  etc/launch-tae-CN-tae-DN/dn.toml
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/feature, size/XL

#6337 add more a nil check to avoid panic when clean up the pipeline
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/semi/join.go
Labels: kind/bug, size/S

#6338 fix point read bug
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/XS

#6336 Unix timestamp
  pkg/container/types/timestamp.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/multi/unix_timestamp.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/make.go
  pkg/vectorize/unixtimestamp/unixtimestamp.go
Labels: kind/bug, size/M

#6332 [test]: add bvt case
  test/cases/dtype/text_1.sql
  test/cases/expression/set_variable.result
  test/cases/expression/set_variable.sql
  test/cases/load_data/load_data_set_null.result
  test/cases/load_data/load_data_set_null.sql
  test/cases/prepare/prepare_autoincrement.result
  test/cases/prepare/prepare_autoincrement.sql
  test/distributed/cases/dtype/text_1.sql
  test/distributed/cases/expression/set_variable.result
  test/distributed/cases/expression/set_variable.sql
  test/distributed/cases/load_data/load_data_set_null.result
  test/distributed/cases/load_data/load_data_set_null.sql
  test/distributed/cases/prepare/prepare_autoincrement.result
  test/distributed/cases/prepare/prepare_autoincrement.sql
  test/distributed/resources/load_data/set_null_1.csv
  test/distributed/resources/load_data/set_null_2.csv
  test/distributed/resources/load_data/set_null_3.csv
  test/distributed/result/dtype/text_1.result
  test/resources/load_data/set_null_1.csv
  test/resources/load_data/set_null_2.csv
  test/resources/load_data/set_null_3.csv
  test/result/dtype/text_1.result
Labels: size/L, kind/test-ci

#6340 fix goroutine leak in wal
  pkg/vm/engine/tae/wal/driver.go
Labels: kind/bug, size/XS

#6342 check whether hakeeperClient is nil
  pkg/logservice/hakeeper_client.go
Labels: kind/bug, size/XS

#6349 Fix log string
  pkg/pb/logservice/logservice.go
  pkg/tests/service/service_test.go
  pkg/tests/service/task_test.go
  pkg/tests/txn/cluster_basic_test.go
Labels: kind/bug, size/S, kind/test-ci

#6301 fix: docker launch way
  optools/images/Dockerfile
Labels: kind/bug, size/XS

#6343 [Bug]: MySQL Workbench database version error #5438
  pkg/frontend/mysql_protocol.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S

#6351 Pass the correct contextual information when running across nodes
  pkg/frontend/test/engine_mock.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/types.go
  proto/pipeline.proto
Labels: kind/bug, size/M

#6350 [bug] gossip seed num is not correct in cluster test.
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
Labels: kind/bug, size/S

#6355 Delete the bvt tag of issue#3677
  test/cases/dtype/double.test
  test/distributed/cases/dtype/double.test
  test/distributed/result/dtype/double.result
  test/result/dtype/double.result
Labels: kind/bug, size/L

#6326 text blob and time type bvt case
  test/cases/dtype/text_blob.result
  test/cases/dtype/text_blob.sql
  test/cases/dtype/time_1.result
  test/cases/dtype/time_1.sql
  test/distributed/cases/dtype/text_blob.result
  test/distributed/cases/dtype/text_blob.sql
  test/distributed/cases/dtype/time_1.result
  test/distributed/cases/dtype/time_1.sql
  test/distributed/resources/blob_file/blob1.csv
  test/distributed/resources/blob_file/blob2.mp3
  test/distributed/resources/blob_file/blob3.jpeg
  test/distributed/resources/blob_file/blob4.gif
  test/distributed/resources/blob_file/blob5.docx
  test/distributed/resources/blob_file/blob6.pptx
  test/distributed/resources/blob_file/blob7.pdf
  test/distributed/resources/blob_file/blob8.xlsx
  test/distributed/resources/blob_file/blob9.xml
  test/distributed/resources/external_table_file/time_ex_table.csv
  test/resources/blob_file/blob1.csv
  test/resources/blob_file/blob2.mp3
  test/resources/blob_file/blob3.jpeg
  test/resources/blob_file/blob4.gif
  test/resources/blob_file/blob5.docx
  test/resources/blob_file/blob6.pptx
  test/resources/blob_file/blob7.pdf
  test/resources/blob_file/blob8.xlsx
  test/resources/blob_file/blob9.xml
  test/resources/external_table_file/time_ex_table.csv
Labels: size/XL, kind/test-ci

#6344 fix bug: sometimes colRef.Name is empty
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#6353 create task tables if not exists
  pkg/taskservice/mysql_task_storage.go
Labels: kind/bug, size/S

#6356 remove tag which bug was fixed
  test/cases/dml/select/order_by_with_nulls.sql
  test/cases/function/func_bit.sql
  test/cases/operator/is_not_operator.sql
  test/distributed/cases/dml/select/order_by_with_nulls.sql
  test/distributed/cases/operator/is_not_operator.sql
  test/distributed/result/dml/select/order_by_with_nulls.result
  test/distributed/result/operator/is_not_operator.result
  test/result/dml/select/order_by_with_nulls.result
  test/result/function/func_bit.result
  test/result/operator/is_not_operator.result
Labels: kind/bug, size/S, kind/test-ci

#6354 alter external timestamp case and remove tag
  test/cases/table/external_table.result
  test/cases/table/external_table.sql
  test/distributed/cases/table/external_table.result
  test/distributed/cases/table/external_table.sql
  test/distributed/cases/zz_accesscontrol/grant_privs_role.sql
  test/distributed/resources/external_table_file/ex_table_3_2.csv
  test/distributed/resources/external_table_file/ex_table_3_3.csv
  test/distributed/resources/external_table_file/ex_table_3_4.csv
  test/distributed/resources/external_table_file/ex_table_bzip.bz2
  test/distributed/resources/external_table_file/ex_table_char.csv
  test/distributed/resources/external_table_file/ex_table_char.log
  test/distributed/resources/external_table_file/ex_table_char.text
  test/resources/external_table_file/ex_table_3_2.csv
  test/resources/external_table_file/ex_table_3_3.csv
  test/resources/external_table_file/ex_table_3_4.csv
  test/resources/external_table_file/ex_table_bzip.bz2
  test/resources/external_table_file/ex_table_char.csv
  test/resources/external_table_file/ex_table_char.log
  test/resources/external_table_file/ex_table_char.text
Labels: kind/feature, size/M

#6358 fix logservice bugs:
  pkg/logservice/store.go
  pkg/pb/logservice/logservice.go
Labels: kind/bug, size/S

#6359 check rpc not nil before closing it
  pkg/cnservice/server.go
Labels: kind/bug, size/S

#6319 modify read simdcsv flow
  go.mod
  go.sum
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/S

#6346 solve bvt tag
  pkg/sql/plan/build_util.go
  test/distributed/cases/transaction/autocommit_1.sql
  test/distributed/result/transaction/autocommit_1.result
Labels: kind/bug, size/XS

#6363 fix ut hang
  pkg/vm/engine/tae/tasks/poolhandler.go
Labels: kind/bug, size/XS, kind/test-ci

#6360 taskservice: add task mo_ctl command to enable or disable task framework.
  pkg/pb/ctl/ctl.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/function/builtin/ctl/cmd_task.go
  pkg/sql/plan/function/builtin/ctl/types.go
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/task_ctl.go
  pkg/taskservice/task_ctl_test.go
  pkg/taskservice/task_runner.go
  proto/ctl.proto
Labels: kind/enhancement, size/M

#6376 Rearrange inserted cells after extending hashtable
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: kind/bug, size/M

#6387 fix bug: can't get row_id's idx
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/S

#6386 cfg: add multi cn launch config
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/launch.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
Labels: kind/documentation, size/M

#6364 report execute failed when column not exists
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_load.go
  test/cases/dml/insert/insert_with_function.sql
  test/cases/load_data/load_data_set_null.result
  test/cases/load_data/load_data_set_null.sql
  test/cases/table/external_table.sql
  test/distributed/cases/dml/insert/insert_with_function.sql
  test/distributed/cases/load_data/load_data_set_null.result
  test/distributed/cases/load_data/load_data_set_null.sql
  test/distributed/cases/table/external_table.sql
Labels: kind/bug, size/M

#6392 fix a data race in logservice.
  pkg/logservice/store_metadata.go
  pkg/logservice/truncation.go
Labels: kind/bug, size/S

#6339 Fix 6321:timediff results error
  pkg/sql/plan/function/builtin/binary/timediff.go
  pkg/vectorize/timediff/timediff.go
  test/cases/function/func_datetime_timediff.test
  test/distributed/cases/function/func_datetime_timediff.test
  test/distributed/result/function/func_datetime_timediff.result
  test/result/function/func_datetime_timediff.result
Labels: kind/bug, size/M

#6399 Explain bug
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/explain/explain_test.go
Labels: kind/bug, size/S

#6396 modify log level in hakeeper
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/dnservice/parse.go
Labels: kind/enhancement, size/XS

#6407 add variable performance_schema to support mybatis
  pkg/frontend/variables.go
Labels: kind/bug, size/XS

#6394 add date type for variable
  pkg/frontend/util.go
  test/cases/set/set_operator.test
  test/distributed/cases/set/set_operator.test
  test/distributed/result/set/set_operator.result
  test/result/set/set_operator.result
Labels: size/S

#6408 Add the missing remote flg
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/S

#6418 fix checkpoint and replay bugs and add ut
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/filter.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/M

#6414 fix goroutine leak in tests
  pkg/taskservice/task_service_holder_test.go
  pkg/txn/rpc/sender_test.go
Labels: size/S, kind/test-ci

#6420 fix: make ci
  optools/bvt_ut/entrypoint.sh
Labels: kind/bug, size/S

#6430 alter json bvt cases
  test/cases/ddl/json_type.sql
  test/distributed/cases/ddl/json_type.sql
  test/distributed/resources/json/json_table_3.txt
  test/distributed/result/ddl/json_type.result
  test/resources/json/json_table_3.txt
  test/result/ddl/json_type.result
Labels: size/S

#6428 fix print debug logs in morpc
  pkg/cnservice/cnclient/client.go
  pkg/common/morpc/backend.go
  pkg/logservice/client.go
Labels: size/S

#6429 fix bug: colIdx is incorrect
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/S

#6432 fix format show variable like
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/show.go
Labels: size/XS

#6424 Remove some unnecessary slow bitmap ops
  pkg/common/bitmap/bitmap.go
  pkg/compare/strcompare.go
  pkg/container/nulls/nulls.go
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
Labels: kind/enhancement, size/M

#6431 remove bvt tags
  test/cases/dtype/time_1.sql
  test/distributed/cases/dtype/time_1.sql
Labels: kind/bug, size/S

#6425 [Bug]: query get empty results #6385
  pkg/sql/plan/build_test.go
  pkg/sql/plan/explain/column_prune_test.go
  pkg/sql/plan/explain/marshal_query_test.go
  pkg/sql/plan/flatten_subquery.go
  test/cases/dml/select/subquery.sql
  test/distributed/cases/dml/select/subquery.sql
  test/distributed/result/dml/select/subquery.result
  test/result/dml/select/subquery.result
Labels: kind/bug, size/M

#6440 [User Bug]: java.sql.SQLException: internal error: the system variable does not exist #230
  pkg/frontend/variables.go
  test/distributed/result/database/system_variables.result
  test/result/database/system_variables.result
Labels: kind/bug, size/S

#6444 fileservice: add symlink to dir test
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/S

#6446 Avoid local remote run
  pkg/cnservice/server.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
Labels: kind/enhancement, size/S

#6447 fileservice: deref symlink in LocalETLFS.List, LocalFS.List
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs.go
Labels: kind/enhancement, size/S
