Repository matrixorigin/matrixone, pull requests merged in 2022-12, with the labels that each got.

#7026 set var = default for 0.6 branch
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/variables.go
  pkg/sql/colexec/expr_eval.go
Labels: kind/bug

#7028 fix bug: Expr_T have no Typ
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/make.go
  test/cases/prepare/prepare.test
  test/distributed/cases/prepare/prepare.test
  test/distributed/result/prepare/prepare.result
  test/result/prepare/prepare.result
Labels: kind/bug, size/S

#6992 feature6649: support function subString_index()
  pkg/sql/plan/function/builtin/multi/substr_index.go
  pkg/sql/plan/function/builtin/multi/substr_index_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/subStrIndex/subStr_Index.go
  pkg/vectorize/subStrIndex/subStr_Index_test.go
  test/cases/function/func_string_substringindex.test
  test/distributed/cases/function/func_string_substringindex.test
  test/distributed/result/function/func_string_substringindex.result
  test/result/function/func_string_substringindex.result
Labels: kind/feature, size/XL

#6558 fix : correct error when load_file can't found #6313
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/dml.go
  pkg/sql/plan/build_insert.go
Labels: kind/bug, size/S

#7030 Fix error occurs in dumping null data
  cmd/mo-dump/main.go
Labels: kind/bug, size/XS

#7031 bugfix: shutdown trace meet error panic
  cmd/mo-service/main.go
  pkg/util/trace/trace.go
  pkg/util/trace/trace_test.go
Labels: kind/bug, size/S

#7001 memorytable: fix multi-table transaction rollback
  pkg/txn/storage/memorystorage/memorytable/transaction.go
  pkg/txn/storage/memorystorage/memorytable/transaction_test.go
Labels: kind/bug, size/S

#7035 memorytable: de-dup some common types and variables
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/memtable/atomic.go
  pkg/txn/storage/memorystorage/memtable/batch_utils.go
  pkg/txn/storage/memorystorage/memtable/diff_iter.go
  pkg/txn/storage/memorystorage/memtable/index_iter.go
  pkg/txn/storage/memorystorage/memtable/nullable.go
  pkg/txn/storage/memorystorage/memtable/ordered.go
  pkg/txn/storage/memorystorage/memtable/physical_row.go
  pkg/txn/storage/memorystorage/memtable/table.go
  pkg/txn/storage/memorystorage/memtable/table_iter.go
  pkg/txn/storage/memorystorage/memtable/transaction.go
  pkg/txn/storage/memorystorage/memtable/tuple.go
  pkg/txn/storage/memorystorage/memtable/tuple_test.go
  pkg/txn/storage/memorystorage/memtable/types.go
  pkg/txn/storage/memorystorage/memtable/vector.go
  pkg/txn/storage/memorystorage/memtable/vector_utils.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/enhancement, size/L

#7038 support last_insert_id func
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/plan/function/builtin/unary/infomation_function.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/auto_increment/auto_increment_columns.sql
  test/distributed/cases/auto_increment/auto_increment_columns.result
  test/distributed/cases/auto_increment/auto_increment_columns.sql
Labels: kind/enhancement, size/M

#7041 Make HAKeeper use MOLogger~
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/bootstrap/bootstrap_test.go
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/check_test.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/logservice/client.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
Labels: size/M, kind/refactor

#6945 change and optimize index struct
  pkg/catalog/types.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/index_util.go
  pkg/sql/util/index_util_test.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/vm/engine/gob.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/types.go
  proto/plan.proto
Labels: size/XL

#7043 do idempotence check in cn
  pkg/vm/engine/disttae/partition.go
Labels: kind/bug, size/S

#7036 revisit logtail manager implementation
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/util_test.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtail_test.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/operator.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/model/aot.go
Labels: size/L, kind/refactor

#7044 Return NULL when casting empty string to date/time types
  pkg/sql/plan/function/operator/cast.go
  test/cases/dtype/time_1.result
  test/distributed/cases/dtype/time_1.result
  test/distributed/result/dtype/time.result
  test/result/dtype/time.result
Labels: kind/bug, size/S

#7047 small code refactor
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vecbase.go
  pkg/vm/engine/tae/containers/vecimpl.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vecwindow.go
  pkg/vm/engine/tae/db/db_test.go
Labels: size/S, kind/refactor

#6997 Fix now/current_timestamp returns inconsistent value in one sql
  pkg/container/types/datetime.go
  pkg/container/types/timestamp.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/multi/current_timestamp.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/optimize.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/process/process.go
  test/cases/function/func_datetime_now.test
  test/distributed/cases/function/func_datetime_now.test
  test/distributed/result/function/func_datetime_now.result
  test/result/function/func_datetime_now.result
Labels: kind/bug, size/M

#7033 feature 6637: support format() function
  pkg/sql/plan/function/builtin/multi/format.go
  pkg/sql/plan/function/builtin/multi/format_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/format/format.go
  pkg/vectorize/format/format_test.go
  test/cases/function/func_string_format.test
  test/distributed/cases/function/func_string_format.test
  test/distributed/result/function/func_string_format.result
  test/result/function/func_string_format.result
Labels: kind/feature, size/XL

#7052 Update robot.yml
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#7054 Change rows per block and blocks per seg.
  pkg/vm/engine/tae/options/types.go
Labels: size/XS

#7027 [Feature Request]: Support a non-primary-key table with sorting key #6959
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/util/util.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/cases/table/create_table.test
  test/distributed/cases/table/create_table.test
  test/distributed/result/table/create_table.result
  test/result/table/create_table.result
Labels: kind/feature, size/XXL

#7055 fix bug: prepare with show stmt is incorrect
  pkg/frontend/mysql_cmd_executor.go
  test/cases/prepare/prepare.test
  test/distributed/cases/prepare/prepare.test
  test/distributed/result/prepare/prepare.result
  test/result/prepare/prepare.result
Labels: kind/bug, size/S

#7029 use bool not error for returning in some case
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/rule/predicate_pushdown.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/S

#7057 add tabledef of constraint
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
  pkg/vm/engine/types_test.go
Labels: size/M

#7069 Adjust startup config
  .github/workflows/robot.yml
  cmd/mo-service/main.go
Labels: kind/bug, size/XS, kind/test-ci

#7063 morpc: add compress support
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/compress.go
  pkg/common/morpc/compress_test.go
Labels: kind/feature, size/M

#6549 feat: image push to ecr
  .github/actions/ecr/action.yaml
  .github/workflows/docker_ci.yml
Labels: size/S, kind/test-ci

#7075 modify the password of the administrator of the account
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
  test/cases/tenant/alter_account.result
  test/cases/tenant/alter_account.sql
  test/distributed/cases/tenant/alter_account.result
  test/distributed/cases/tenant/alter_account.sql
Labels: kind/feature, size/XXL

#7078 logservice: make logservice rpc enable compress
  pkg/logservice/client.go
  pkg/logservice/config.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/shardinfo.go
Labels: kind/feature, size/S

#7086 refactor schema and sortkey
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/id.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/util_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, kind/enhancement, size/L

#7090 optimize logtail has catalog changes check
  pkg/vm/engine/tae/logtail/logtail_test.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/options/types.go
Labels: kind/enhancement, size/S

#7083 [Enhancement]: refactoring stats #7082
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/dml.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/sql/plan/unnest.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
  proto/plan.proto
Labels: kind/enhancement, size/L

#7089 add field constraint in tea
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/frontend/session.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/marshal.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: size/M

#7097 Update e2e_with_race.yml
  .github/workflows/e2e_with_race.yml
Labels: size/XS, kind/test-ci

#7098 use constraint instead of index in table def
  pkg/frontend/session.go
  pkg/sql/compile/ddl.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/vm/engine/gob.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/types.go
Labels: size/M

#7103 fix-284: time type read error
  pkg/frontend/mysql_protocol.go
Labels: kind/bug, size/S

#7100 [Enhancement]: refactoring stats #7082
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#7101 [Bug]: mo's scan with predicate is slower than clickhouse #6870
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#7114 support show function status in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
Labels: kind/feature, size/XXL

#7117 fix mnode unref
  pkg/vm/engine/tae/tables/base.go
Labels: kind/bug, size/XS

#7129 Update ci.yml to fix sca install linter fail
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#7049 Reconstruct cp key serialize
  pkg/container/types/tuple.go
  pkg/container/types/tuple_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/function/builtin/multi/serial.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/index_util.go
Labels: kind/feature, size/M

#7131 morpc: make the stream strictly in order
  go.mod
  go.sum
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
Labels: kind/enhancement, size/M

#7122 support show node list and show locks in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
Labels: kind/feature, size/XXL

#7037 Add sleep function
  pkg/sql/plan/function/builtin/unary/sleep.go
  pkg/sql/plan/function/builtin/unary/sleep_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  test/cases/function/func_sleep.test
  test/distributed/cases/function/func_sleep.test
  test/distributed/result/function/func_sleep.result
  test/result/function/func_sleep.result
Labels: kind/feature, size/M

#7137 fix create_sql too large in tabledef
  pkg/catalog/types.go
Labels: size/S

#7138 fix concurrent io
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/enhancement, size/S

#7118 fix log service driver read, retry when read large entry
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
Labels: kind/bug, size/XS

#7076 Add a hidden column to external table output
  pkg/catalog/types.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/M

#7148 Remove moerr.New*NoCtx in frontend
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/codec.go
  pkg/frontend/export.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/resultset.go
  pkg/frontend/resultset_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/trace/report_error.go
Labels: kind/feature, size/XL

#7155 [Bug]: mo's scan with predicate is slower than clickhouse #6870
  pkg/sql/plan/function/operator/compare.go
Labels: kind/enhancement, size/S

#7161 Remove lint-docs check in mergify
  .github/mergify.yml
Labels: size/XS, kind/test-ci

#7125 [Enhancement]: refactoring stats #7082
  pkg/sql/plan/join_order.go
Labels: kind/enhancement, size/S

#7128 add kill statement
  go.mod
  go.sum
  pkg/config/configuration.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/kill.go
Labels: kind/feature, size/XXL

#7152 fix time type mysql protocol issue
  pkg/defines/type.go
  pkg/frontend/mysql_protocol.go
Labels: kind/bug, size/S

#7162 morpc: fix data race
  go.mod
  go.sum
  pkg/common/morpc/backend.go
Labels: kind/bug, size/S

#7153 Distinguish internal SQL executed by non-users
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/util/trace/buffer_pipe_test.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/schema.go
  test/cases/sql_source_type/sql_source_type.result
  test/cases/sql_source_type/sql_source_type.sql
Labels: kind/feature, size/M

#7173 update log service driver config
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
Labels: kind/enhancement, size/XS

#7151 fix bug: error happen in prepare statement
  pkg/sql/plan/build_show.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S

#7176 [User Bug]: 跟ck的单机复杂查询性能相差从10倍-3000倍 #251
  pkg/vm/engine/disttae/hack.go
  pkg/vm/engine/disttae/tools.go
Labels: kind/enhancement, size/S

#7130 memoryengine: use new memorytable package
  pkg/cnservice/memory_engine.go
  pkg/dnservice/factory.go
  pkg/testutil/testengine/testengine.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/txn/storage/memorystorage/catalog_handler.go
  pkg/txn/storage/memorystorage/catalog_handler_test.go
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/log_tail_test.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/mem_handler_test.go
  pkg/txn/storage/memorystorage/mem_storage.go
  pkg/txn/storage/memorystorage/memorytable/history.go
  pkg/txn/storage/memorystorage/memorytable/table.go
  pkg/txn/storage/memorystorage/memorytable/table_state.go
  pkg/txn/storage/memorystorage/memorytable/table_test.go
  pkg/txn/storage/memorystorage/memorytable/transaction.go
  pkg/txn/storage/memorystorage/precommit.go
  pkg/txn/storage/memorystorage/read.go
  pkg/txn/storage/memorystorage/types.go
  pkg/txn/storage/memorystorage/write.go
  pkg/vm/engine/memoryengine/operation_handler.go
Labels: kind/enhancement, size/L

#7108 fix bug: return rows is incorrect in delete clause
  pkg/frontend/test/engine_mock.go
  pkg/sql/compile/dml.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M

#7119 CI: Update `ut_pr.yaml` to check the coverage of the file
  .github/workflows/e2e_with_race.yml
  .github/workflows/ut_pr.yml
Labels: size/S, kind/test-ci

#7135 Redesign TableDef and constraint definitions
  pkg/pb/plan/plan.pb.go
  proto/plan.proto
Labels: size/M, kind/refactor

#7188 Fix the bug that LoadCheckpointEntries hangs due to too many checkpoint
  pkg/vm/engine/tae/logtail/handle.go
Labels: kind/bug, size/XS

#7175 remove case dir
  test/cases/sql_source_type/sql_source_type.result
  test/cases/sql_source_type/sql_source_type.sql
Labels: size/S

#7195 add codeowner
  .github/workflows/robot.yml
  CODEOWNERS
Labels: size/XS, kind/test-ci

#7179 fix bug: table.proc is nil
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/XS

#7198 Optimize CI
  .github/workflows/ci.yml
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e.yml
  .github/workflows/ut_pr.yml
Labels: size/S, kind/test-ci

#7064 Delay applying constantFold on non-volatile fn.
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/function/builtin/multi/current_timestamp.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/optimize.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/visit_plan_rule.go
  test/distributed/cases/function/func_datetime_now.result
  test/distributed/cases/function/func_datetime_now.test
Labels: kind/bug, size/M

#7201 Dealing with side case in relation to text type.
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/operator/compare.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/utils.go
  test/distributed/cases/operator/like_operator.result
  test/distributed/cases/operator/like_operator.sql
Labels: kind/bug, size/S

#7207 [Enhancement]: optimize the filtering using zonemap #7206
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/enhancement, size/S

#7205 Add curdate function
  pkg/sql/plan/function/builtin/unary/current_date.go
  pkg/sql/plan/function/builtin/unary/current_date_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  test/distributed/cases/function/func_datetime_curdate.result
  test/distributed/cases/function/func_datetime_curdate.test
Labels: kind/feature, size/M

#7204 fix blob type error
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  test/distributed/cases/dtype/text_blob.result
Labels: kind/bug, size/S

#7219 filepath support character '@'
  pkg/fileservice/path.go
Labels: kind/bug, size/XS

#7212 support no report in moerr.New
  pkg/util/errutil/errors.go
  pkg/util/errutil/errors_test.go
  pkg/util/trace/example/main.go
Labels: kind/enhancement, size/S

#7120 Add median function
  pkg/sql/colexec/agg/aggUt/agg_testutil.go
  pkg/sql/colexec/agg/aggUt/median_test.go
  pkg/sql/colexec/agg/median.go
  pkg/sql/colexec/agg/new.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/function/aggregate.go
  pkg/sql/plan/function/function_id.go
  test/distributed/cases/function/func_aggr_median.result
  test/distributed/cases/function/func_aggr_median.test
  test/distributed/cases/function/func_aggr_sum.result
  test/distributed/cases/function/func_aggr_sum.test
Labels: kind/feature, size/XXL

#7227 fix #7200
  pkg/catalog/types.go
Labels: kind/bug, size/S

#7199 refactor viewDef
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/builtin/multi/split_part_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  proto/plan.proto
Labels: size/M, kind/refactor

#7245 update checkpoint runner
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/types.go
Labels: kind/api-change, size/M

#7217 support create/drop unique index
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/common/moerr/error.go
  pkg/pb/api/api.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/sys_relation.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  proto/api.proto
  proto/plan.proto
  test/distributed/cases/ddl/comprimary_key.result
  test/distributed/cases/ddl/comprimary_key.sql
  test/distributed/cases/table/truncate_table_2.sql
  test/distributed/cases/transaction/atomicity_1.result
  test/distributed/cases/transaction/atomicity_1.sql
  test/distributed/cases/transaction/autocommit_1.result
Labels: size/L

#7237 alter account cases
  test/distributed/cases/zz_accesscontrol/alter_account.result
  test/distributed/cases/zz_accesscontrol/alter_account.sql
Labels: size/M, kind/test-ci

#7251 support COM_STMT_RESET
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/reset.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/XXL

#7216 support show triggers stmt
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/feature, size/S

#7226 fix json_extract err
  pkg/sql/plan/function/builtin/binary/json_extract.go
  pkg/sql/plan/function/builtin/binary/json_extract_test.go
  pkg/sql/plan/function/builtins.go
  pkg/vectorize/json_extract/json_extract.go
  pkg/vectorize/json_extract/json_extract_test.go
  pkg/vectorize/split_part/split_part.go
  test/distributed/cases/function/func_json_extract.result
  test/distributed/cases/function/func_json_extract.test
Labels: kind/bug, size/L

#7189 Add instr function
  pkg/sql/plan/function/builtin/binary/instr.go
  pkg/sql/plan/function/builtin/binary/instr_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/instr/instr.go
  pkg/vectorize/instr/instr_test.go
  test/distributed/cases/function/func_string_instr.result
  test/distributed/cases/function/func_string_instr.test
Labels: kind/feature, size/M

#7255 fix missing errutil.NoReportFromContext in trace.ReportError
  pkg/util/trace/example/main.go
  pkg/util/trace/report_error.go
Labels: kind/bug, size/S

#7244 add syntax for the cluster table
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/insert.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/XXL

#7256 fix wrong rows in table status
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS

#7261 do not log error message when column was found in parent table
  pkg/sql/plan/base_binder.go
Labels: kind/enhancement, size/S

#7236 Fix bug: deep copy error
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/deepcopy.go
Labels: kind/bug, size/S

#7259 Remove some unused bvt case
  test/distributed/cases/dtype/timestamp.result
  test/distributed/cases/dtype/timestamp.test
  test/distributed/cases/function/func_aggr_avg.result
  test/distributed/cases/function/func_aggr_avg.test
Labels: size/S

#7257 tae small fix
  pkg/vm/engine/tae/common/refs.go
  pkg/vm/engine/tae/dataio/blockio/read.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
Labels: kind/bug, kind/enhancement, size/S

#6968 add parser support for udf
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/extension.go
  pkg/sql/parsers/tree/function.go
  test/distributed/cases/function/udf.result
  test/distributed/cases/function/udf.sql
Labels: kind/feature, size/XXL

#7271 #6671 add some database statistics in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
Labels: kind/feature, size/XXL

#7269 [User Bug]: MO点查慢，比mysql慢20倍，比mongo慢三个数量级 #257
  pkg/container/vector/tools.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#7266 contributors readme action update
  README.md
Labels: size/XS

#7270 Refactor: return table id & column id for TableDef
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/function/builtin/ctl/cmd_flush.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/database.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#7262 do not report err in evalFilterExpr
  pkg/container/vector/tools.go
  pkg/sql/colexec/expr_eval.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/M

#7277 [Bug]: BIGINT UNSIGNED type, insert can success, but select abnormal.…
  test/distributed/cases/prepare/prepare_all.sql
Labels: kind/bug, size/XS

#7228 Support init password with env var
  pkg/frontend/authenticate.go
Labels: kind/feature, size/S

#7272 Add alter view support in parser
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/view/view.result
  test/distributed/cases/view/view.test
Labels: kind/feature, size/XXL

#7287 [Bug]: mo's scan with predicate is slower than clickhouse #6870
  pkg/sql/plan/function/operator/compare.go
Labels: kind/enhancement, size/XS

#7279 #6671 support some show stmt for dev
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/feature, size/S

#7283 fix blocklist in cn
  pkg/vm/engine/disttae/partition.go
  test/distributed/cases/dml/update/flush.result
  test/distributed/cases/dml/update/flush.test
  test/distributed/cases/zz_accesscontrol/alter_account.result
  test/distributed/cases/zz_accesscontrol/alter_account.sql
Labels: kind/bug, size/S

#7298 fileservice: add IOVector.ExpireAt
  pkg/fileservice/file_service.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#7297 Fix vector method bug and Aggregate AVG bug.
  pkg/container/vector/vector.go
  pkg/sql/colexec/agg/avg.go
Labels: kind/bug, size/S

#7293 Fix mo-cloud #334
  pkg/common/hashmap/strhashmap.go
Labels: kind/bug, size/S

#7291 fix mo-cloud #328
  pkg/sql/colexec/agg/agg.go
Labels: kind/bug, size/S

#7309 [Bug]: optimze bitmap isEmpty #7307
  pkg/common/bitmap/bitmap.go
  pkg/common/bitmap/types.go
Labels: kind/bug, size/S

#7310 blockio supports generates zonemap for written data
  pkg/vm/engine/tae/dataio/blockio/writer.go
  pkg/vm/engine/tae/dataio/blockio/writer_test.go
Labels: kind/enhancement, size/M

#7314 remove flush.test bvt tag
  test/distributed/cases/dml/update/flush.test
Labels: size/XS, kind/test-ci

#7136 global ckp
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-logservice/cn.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  pkg/cnservice/tae.go
  pkg/cnservice/types.go
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/objectio/fs.go
  pkg/tests/service/dnservice.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/option.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/handle.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
Labels: kind/feature, size/XL

#7273 Add json_quote function
  pkg/sql/plan/function/builtin/unary/json_quote.go
  pkg/sql/plan/function/builtin/unary/json_quote_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/json_quote/json_quote.go
  pkg/vectorize/json_quote/json_quote_test.go
  test/distributed/cases/function/func_json_quote.result
  test/distributed/cases/function/func_json_quote.test
Labels: kind/feature, size/M

#7308 add more ut in plan
  pkg/sql/plan/build.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
Labels: size/M, kind/test-ci

#7317 Implement tae's GC
  pkg/objectio/fs.go
  pkg/vm/engine/tae/dataio/blockio/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc/delete.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/gc/dropdb.go
  pkg/vm/engine/tae/db/gc/droptable.go
  pkg/vm/engine/tae/db/gc/entry.go
  pkg/vm/engine/tae/db/gc/gc_test.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/db/gc/types.go
Labels: kind/feature, size/XL

#7316 [Enhancement]: support in operator #7190
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/compare.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/rule/constant_fold.go
  test/distributed/cases/dtype/bool.result
Labels: kind/enhancement, size/L

#7276 finish group_concat without order by
  pkg/common/hashmap/strhashmap.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/multi_col/group_concat/group_concat.go
  pkg/sql/colexec/multi_col/group_concat/group_concat_test.go
  pkg/sql/colexec/multi_col/group_concat/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/aggregate.go
  pkg/sql/plan/function/function_id.go
  test/distributed/cases/function/func_aggr_group_concat.result
  test/distributed/cases/function/func_aggr_group_concat.test
Labels: kind/feature, size/XXL

#7318 fix ut, fix forceGlobalCheckpoint
  pkg/vm/engine/tae/db/base_test.go
Labels: kind/bug, size/XS

#7289 basic support foreign key constraint in create table
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/types.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
Labels: kind/feature, size/M

#7320 support binary()
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/bug, size/XXL

#7321 Allow hostname changed in dragonboat.
  go.mod
  go.sum
Labels: kind/enhancement, size/XS

#7247 fix strHashMap bug
  pkg/common/hashmap/strhashmap.go
  test/distributed/cases/join/join.result
  test/distributed/cases/join/join.test
Labels: kind/bug, size/M

#7182 Refactor insert node
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/handle/segment.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/sys_relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/factory.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/mock.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/enhancement, kind/feature, size/XL, kind/refactor

#7323 function_left test cases
  test/distributed/cases/function/func_string_left.result
  test/distributed/cases/function/func_string_left.sql
Labels: size/M, kind/test-ci

#7329 [Enhancement]: optimize filter expr for zonemap #7328
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/enhancement, size/S

#7284 Support last/range in jsonpath
  pkg/container/bytejson/README.md
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/path_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  test/distributed/cases/function/func_json_extract.result
  test/distributed/cases/function/func_json_extract.test
Labels: kind/enhancement, size/L

#7280 use json as colType in unnest operator to reduce conversion
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/colexec/table_function/unnest.go
  pkg/sql/plan/unnest.go
  test/distributed/cases/ddl/json_type.sql
  test/distributed/cases/function/table_func_unnest.result
  test/distributed/cases/function/table_func_unnest.test
Labels: kind/enhancement, size/M

#7254 loading with jsonline format supports json type
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/types.go
  pkg/sql/colexec/external/external.go
  test/distributed/cases/load_data/load_data_jsonline.result
  test/distributed/cases/load_data/load_data_jsonline.test
  test/distributed/resources/load_data/jsonline_array.jl
  test/distributed/resources/load_data/jsonline_object.jl
Labels: kind/bug, size/M

#7335 fix collectCheckpointMetadata
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
Labels: kind/bug, size/S

#7242 improve log context
  pkg/common/log/example_log_test.go
  pkg/common/log/logger.go
  pkg/common/log/types.go
  pkg/logutil/fields.go
Labels: kind/enhancement, size/M

#7332 [Feature] support show table values stmt
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/feature, size/S

#7324 add cluster table
  pkg/catalog/types.go
  pkg/common/hashmap/strhashmap.go
  pkg/container/vector/vector.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/binding.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
  pkg/sql/util/util.go
  pkg/vm/engine/memoryengine/compiler_context.go
  proto/plan.proto
  test/distributed/cases/tenant/clustertable.result
  test/distributed/cases/tenant/clustertable.sql
Labels: kind/feature, size/XL

#7286 Unique index table dml
  pkg/catalog/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/function/builtin/multi/serial.go
  pkg/sql/plan/index_table_dml_test.go
  pkg/sql/plan/mock.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/index_util.go
  pkg/sql/util/index_util_test.go
  proto/plan.proto
  test/distributed/cases/dml/delete/delete_index.result
  test/distributed/cases/dml/delete/delete_index.test
  test/distributed/cases/dml/delete/delete_index_table.result
  test/distributed/cases/dml/delete/delete_index_table.sql
  test/distributed/cases/dml/update/update_index.result
  test/distributed/cases/dml/update/update_index.test
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/bug, kind/feature, size/XXL

#7340 [Enhancement]: optimize the filtering using zonemap #7206
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#7296 Add ascii function
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/unary/ascii.go
  pkg/sql/plan/function/builtin/unary/ascii_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/ascii/ascii.go
  pkg/vectorize/ascii/ascii_test.go
  test/distributed/cases/function/func_ascii.result
  test/distributed/cases/function/func_ascii.sql
Labels: kind/feature, size/L

#7348 fix update index table when updating origin table primary key
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_update.go
  test/distributed/cases/dml/update/update_index.result
  test/distributed/cases/dml/update/update_index.test
Labels: kind/bug, size/S

#7252 Cast constant int to column varchar first.
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/tools.go
  test/distributed/cases/dtype/varchar.result
  test/distributed/cases/dtype/varchar.test
  test/distributed/cases/function/func_aggr_count.result
  test/distributed/cases/operator/between_and_operator.result
Labels: kind/bug, size/S

#7325 support values clause/statement
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/resultset_stmt.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/parsers/tree/values.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/build_values.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/make.go
  pkg/sql/plan/query_builder.go
  proto/plan.proto
  test/distributed/cases/dml/select/values.result
  test/distributed/cases/dml/select/values.sql
  test/distributed/cases/table/values.result
  test/distributed/cases/table/values.test
Labels: kind/feature, size/XXL

#7306 Add json cast to string
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/types.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/unary/json_unquote.go
  pkg/sql/plan/function/builtin/unary/json_unquote_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/json_unquote/json_unquote.go
  pkg/vectorize/json_unquote/json_unquote_test.go
  test/distributed/cases/dtype/text_blob.result
  test/distributed/cases/function/func_json_unquote.result
  test/distributed/cases/function/func_json_unquote.sql
  test/distributed/cases/function/func_like.result
  test/distributed/cases/function/func_like.test
Labels: kind/feature, size/L

#7345 [Feature] support some show stmt
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/feature, size/XXL

#7352 [Enhancement]: optimize like function #7351
  pkg/vectorize/like/like.go
Labels: kind/enhancement, size/XS

#7312 Add alter view support.
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/query_builder.go
  proto/plan.proto
  test/distributed/cases/view/view.result
  test/distributed/cases/view/view.test
Labels: kind/feature, size/M

#7360 update the cluster table
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/tenant/clustertable2.sql
  test/distributed/resources/load_data/cluster_table1.csv
Labels: kind/feature, size/M

#7346 set parallel by cpu and cost blocks info
  pkg/sql/colexec/multi_col/group_concat/group_concat.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
Labels: kind/enhancement, size/S

#7368 memorytable: unify KV and Index to Tree
  pkg/txn/storage/memorystorage/memorytable/batch.go
  pkg/txn/storage/memorystorage/memorytable/bench_test.go
  pkg/txn/storage/memorystorage/memorytable/bounded_index_iter.go
  pkg/txn/storage/memorystorage/memorytable/btree.go
  pkg/txn/storage/memorystorage/memorytable/btree_index.go
  pkg/txn/storage/memorystorage/memorytable/btree_kv_test.go
  pkg/txn/storage/memorystorage/memorytable/btree_log_test.go
  pkg/txn/storage/memorystorage/memorytable/btree_test.go
  pkg/txn/storage/memorystorage/memorytable/index.go
  pkg/txn/storage/memorystorage/memorytable/kv_pair.go
  pkg/txn/storage/memorystorage/memorytable/log_entry.go
  pkg/txn/storage/memorystorage/memorytable/table.go
  pkg/txn/storage/memorystorage/memorytable/table_iter.go
  pkg/txn/storage/memorystorage/memorytable/table_iter_test.go
  pkg/txn/storage/memorystorage/memorytable/table_state.go
  pkg/txn/storage/memorystorage/memorytable/tree.go
  pkg/txn/storage/memorystorage/memorytable/tuple_test.go
Labels: kind/enhancement, size/L

#7371 fix force checkpoint
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/bug, size/S

#7071 Retag #4432 -> #4241
  test/distributed/cases/dtype/decimal.test
Labels: size/XS, kind/test-ci

#7059 Add date/datetime -> int type conversion rules
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  pkg/container/types/datetime_test.go
  pkg/container/types/time.go
  pkg/container/types/time_test.go
  pkg/container/types/timestamp.go
  pkg/container/types/tuple_test.go
  pkg/sql/plan/function/builtin/binary/str_to_date.go
  pkg/sql/plan/function/builtin/multi/serial_test.go
  pkg/sql/plan/function/builtin/unary/time_test.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/function/type_check.go
  pkg/sql/util/composite_primary_key_util_test.go
  pkg/vectorize/date/date_test.go
  pkg/vectorize/date_add/date_add_test.go
  pkg/vectorize/date_sub/date_sub_test.go
  pkg/vectorize/day/day_test.go
  pkg/vectorize/dayofyear/dayofyear_test.go
  pkg/vectorize/fromunixtime/from_unixtime.go
  pkg/vectorize/time/time_test.go
  pkg/vectorize/timediff/timediff.go
  pkg/vectorize/timestamp/timestamp_test.go
  pkg/vectorize/week/week_test.go
  pkg/vm/engine/tae/containers/mock.go
  test/distributed/cases/function/func_coalesce.result
  test/distributed/cases/function/func_datetime_date.result
  test/distributed/cases/function/func_datetime_date.test
Labels: kind/feature, size/L

#7359 show create table add unique key info
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: size/S

#7361 fix mysql system view
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_variables.result
Labels: kind/bug, size/S
