Repository matrixorigin/matrixone, pull requests merged in 2022-03, with the labels that each got.

#1787 fix a bug in overload/init.go
  pkg/sql/colexec/extend/overload/init.go
Labels: reviewed

#1771 Update relation when shard is unavailable
  go.mod
  go.sum
  optools/test/config.toml
  pkg/catalog/catalog_test.go
  pkg/frontend/epochgc_test.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/test/storage_test.go
  pkg/vm/driver/testutil/testutil.go
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/relation.go
Labels: do-not-merge/wip

#1796 Wangjian/encode
  pkg/vm/engine/tpe/orderedcodec/constants.go
  pkg/vm/engine/tpe/orderedcodec/decoder.go
  pkg/vm/engine/tpe/orderedcodec/decoder_test.go
  pkg/vm/engine/tpe/orderedcodec/encoder.go
  pkg/vm/engine/tpe/orderedcodec/encoder_test.go
  pkg/vm/engine/tpe/orderedcodec/types.go
  pkg/vm/engine/tpe/tuplecodec/decoder.go
  pkg/vm/engine/tpe/tuplecodec/encoder.go
  pkg/vm/engine/tpe/tuplecodec/encoder_test.go
  pkg/vm/engine/tpe/tuplecodec/types.go
Labels: reviewed

#1802 Fix restoreWal
  go.mod
  go.sum
  pkg/vm/driver/aoe/storage.go
  pkg/vm/engine/aoe/storage/aoedb/v1/snapshot_test.go
  pkg/vm/engine/aoe/storage/metadata/v1/replayer.go
  pkg/vm/engine/aoe/storage/wal/shard/manager.go
  pkg/vm/engine/aoe/storage/wal/types.go
Labels: reviewed

#1838 Feature abs
  pkg/builtin/types.go
  pkg/builtin/unary/abs.go
  pkg/vectorize/abs/abs.go
  pkg/vectorize/abs/abs_test.go
Labels: reviewed

#1833 fix tpe engine bvt bugs
  pkg/vm/engine/tpe/descriptor/types.go
  pkg/vm/engine/tpe/engine/database.go
  pkg/vm/engine/tpe/orderedcodec/decoder.go
  pkg/vm/engine/tpe/orderedcodec/decoder_test.go
  pkg/vm/engine/tpe/tuplecodec/computationhandler.go
  pkg/vm/engine/tpe/tuplecodec/decoder.go
  pkg/vm/engine/tpe/tuplecodec/descriptorhandler.go
Labels: do-not-merge/wip, reviewed

#1849 fix tpe engine epochGC bugs
  pkg/vm/engine/tpe/engine/engine.go
  pkg/vm/engine/tpe/tuplecodec/computationhandler.go
  pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
  pkg/vm/engine/tpe/tuplecodec/epoch.go
Labels: do-not-merge/wip, reviewed

#1851 fix illgeal where condition expression
  pkg/sql/rewrite/astrewrite.go
Labels: do-not-merge/wip, reviewed

#1855 delete non-numeric characters of the version number
  cmd/db-server/main.go
  pkg/frontend/mysql_protocol.go
Labels: reviewed

#1856 fix load stream space bugs
  pkg/frontend/load.go
Labels: reviewed

#1842 [RFC] implement ln builtin function
  pkg/builtin/types.go
  pkg/builtin/unary/ln.go
  pkg/vectorize/ln/ln.go
  pkg/vectorize/ln/ln_test.go
Labels: reviewed

#1892 Implement built-in function power.
  pkg/builtin/binary/power.go
  pkg/builtin/types.go
  pkg/sql/colexec/extend/overload/init.go
  pkg/vectorize/power/power.go
  pkg/vectorize/power/power_test.go
Labels: reviewed

#1891 implement exp builtin function (matrixorigin#1822)
  pkg/builtin/types.go
  pkg/builtin/unary/exp.go
  pkg/vectorize/exp/exp.go
  pkg/vectorize/exp/exp_test.go
Labels: reviewed

#1904 implement Ceil builtin function
  pkg/builtin/multi/ceil.go
  pkg/builtin/types.go
  pkg/vectorize/ceil/ceil.go
  pkg/vectorize/ceil/ceil_test.go
Labels: reviewed

#1949 fix static code analysis error in aoe
  pkg/vm/engine/aoe/common/helper/helper_test.go
  pkg/vm/engine/aoe/storage/layout/dataio/blk_test.go
  pkg/vm/engine/aoe/storage/logstore/entry.go
  pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
Labels: component/aoe, priority/high, size/m, severity/moderate

#1941 More understandable variable name in variance sample code
  pkg/container/ring/variance/variance.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/protocol_test.go
  pkg/sql/viewexec/transformer/transformer.go
Labels: reviewed

#1961 Fix the case that WaitExpect time is not enough
  pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
Labels: component/aoe, auto-test

#1962 Update the timeout value of WaitExpect to adapt to worse CI running platforms
  pkg/vm/engine/aoe/storage/testutils/helpers.go
Labels: component/aoe, auto-test

#1963 Fix RemoveShard
  pkg/vm/driver/aoe/storage.go
Labels: reviewed

#2014 Fix linter warning
  pkg/builtin/multi/ceil.go
  pkg/builtin/multi/floor.go
  pkg/builtin/multi/pi.go
  pkg/builtin/multi/round.go
  pkg/builtin/unary/ln.go
Labels: reviewed

#2057 Update the timeout value of WaitExpect
  pkg/vm/engine/aoe/storage/testutils/helpers.go
Labels: component/aoe, auto-test

#2027 [MatrixCamp] add function ltrim and rtrim
  pkg/builtin/types.go
  pkg/builtin/unary/ltrim.go
  pkg/builtin/unary/rtrim.go
  pkg/vectorize/ltrim/ltrim.go
  pkg/vectorize/ltrim/ltrim_test.go
  pkg/vectorize/rtrim/rtrim.go
  pkg/vectorize/rtrim/rtrim_test.go
Labels: good first issue, reviewed, MatrixCamp

#2072 Fix the bug of query data error due to split
  cmd/generate-config/system_vars_def.toml
  docs/cn/MatrixOne/Get-Started/install-distributed-matrixone.md
  docs/en/MatrixOne/Get-Started/install-distributed-matrixone.md
  pkg/vm/engine/aoe/engine/database.go
Labels: component/aoe, auto-test

#2053 [MatrixCamp] Add Built-in function atan
  pkg/builtin/types.go
  pkg/builtin/unary/atan.go
  pkg/vectorize/atan/atan.go
  pkg/vectorize/atan/atan_test.go
Labels: good first issue, reviewed, MatrixCamp

#2077 Fixed the bug that the buffer of Zs in the reader worker was reset
  pkg/vm/engine/aoe/engine/types.go
  pkg/vm/engine/aoe/engine/worker.go
Labels: component/aoe

#2083 Independent configuration of cube engine features
  cmd/db-server/main.go
  cmd/generate-config/system_vars_def.toml
  go.mod
  go.sum
  optools/test/config.toml
  pkg/catalog/catalog_test.go
  pkg/frontend/epochgc_test.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/config/config.go
  pkg/vm/driver/cube_driver.go
  pkg/vm/driver/test/storage_test.go
  pkg/vm/driver/testutil/testutil.go
  pkg/vm/engine/aoe/engine/engine_test.go
Labels: reviewed

#2074 [MatrixCamp] Add Built-in function MONTH
  pkg/builtin/types.go
  pkg/builtin/unary/month.go
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  pkg/vectorize/month/month.go
  pkg/vectorize/month/month_test.go
Labels: good first issue, MatrixCamp

#2087 chaostesting: update to newest cube
  pkg/chaostesting/9p_test.go
  pkg/chaostesting/fuse_test.go
  pkg/chaostesting/go.mod
  pkg/chaostesting/go.sum
  pkg/chaostesting/testcube/config_default.go
  pkg/chaostesting/testcube/config_randomize.go
  pkg/chaostesting/testcube/kv.go
  pkg/chaostesting/testcube/nodes.go
  pkg/chaostesting/testcube/shard_state_aware.go
  pkg/chaostesting/testcube/transport.go
  pkg/chaostesting/util_random.go
Labels: reviewed

#2022 [MatrixCamp] add function cos
  pkg/builtin/types.go
  pkg/builtin/unary/cos.go
  pkg/vectorize/cos/cos.go
  pkg/vectorize/cos/cos_test.go
Labels: good first issue, MatrixCamp
