Repository matrixorigin/matrixone, pull requests merged in 2022-09, with the labels that each got.

#4818 fileservice fixes
  pkg/fileservice/errors.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/get.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/path.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/M

#4776 add dbeaver connect to mo docs
  docs/cn/MatrixOne/Develop/connect-mo/client-connect-to-matrixone.md
  docs/en/MatrixOne/Develop/connect-mo/client-connect-to-matrixone.md
Labels: kind/documentation, size/XS

#4815 fix distinct test
  test/cases/distinct/distinct.sql
  test/result/distinct/distinct.result
Labels: size/S, kind/test-ci

#4785 Remove mutable buffer node in appendable block
  pkg/vm/engine/tae/dataio/segmentio/driver.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/checkpoint/policy.go
  pkg/vm/engine/tae/db/checkpoint/units.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/tables/handle.go
  pkg/vm/engine/tae/tables/jobs/compactablk.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
Labels: kind/feature, size/XL

#4814 txnstorage, dnservice: various changes
  pkg/dnservice/store_rpc_handler.go
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/log.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mvcc.go
  pkg/txn/storage/txn/mvcc_test.go
  pkg/txn/storage/txn/read.go
  pkg/txn/storage/txn/table_iter.go
  pkg/txn/storage/txn/write.go
  pkg/vm/engine/txn.go
  pkg/vm/engine/txn/hakeeper.go
Labels: kind/enhancement, size/M

#4821 fileservice: try loading s3 test config
  pkg/fileservice/errors.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/S

#4817 Adapter the dragonboat logger to MO Logger
  pkg/logservice/service.go
  pkg/logutil/api_test.go
  pkg/logutil/dragonboat.go
Labels: kind/enhancement, size/S

#4807 Support partition by
  pkg/frontend/session.go
  pkg/pb/plan/plan.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/types.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/txn/operations.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/cases/ddl/table_partition.test
  test/result/ddl/table_partition.result
Labels: kind/feature, size/M

#4829 logservice: fixed flaky tests
  pkg/logservice/service_test.go
Labels: size/S, kind/test-ci

#4831 {Opt] Fix bugs in scalar handling to enable constant fold
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/builtin/unary/math.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/result/explain/explain.result
Labels: kind/bug, kind/enhancement, size/M, kind/test-ci

#4830 Reduce unnecessary non-sequential memory copies
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
Labels: kind/enhancement, size/M

#4837 Ci/add s3 env
  .github/workflows/ci.yml
Labels: size/S, kind/test-ci

#4838 Update s3_fs_test.go
  pkg/fileservice/s3_fs_test.go
Labels: size/S, kind/refactor

#4819 fix bug: if one arg is null in operator function, then result will be null.
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_util.go
  test/cases/operator/math_operator.result
  test/cases/operator/math_operator.test
Labels: kind/bug, size/S

#4835 txnstorage: simplify CatalogHandler
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/catalog_handler_test.go
  pkg/txn/storage/txn/mem_handler.go
Labels: kind/enhancement, size/M

#4822 Add writes and fileMap for txn
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/M

#4848 protoc: add cn store metadata
  pkg/pb/metadata/metadata.pb.go
  proto/metadata.proto
Labels: kind/enhancement, size/S

#4857 Update ut_pr.yml
  .github/workflows/ut_pr.yml
Labels: size/S, kind/test-ci

#4854 txnstorage: various changes
  pkg/dnservice/factory.go
  pkg/txn/storage/txn/alias.go
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/catalog_handler_test.go
  pkg/txn/storage/txn/frontend_test.go
  pkg/txn/storage/txn/handler.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mem_handler_test.go
  pkg/txn/storage/txn/mem_storage.go
  pkg/txn/storage/txn/mvcc.go
  pkg/txn/storage/txn/mvcc_test.go
  pkg/txn/storage/txn/storage_txn_client.go
  pkg/txn/storage/txn/table_iter.go
  pkg/txn/storage/txn/table_test.go
  pkg/txn/storage/txn/time.go
  pkg/txn/storage/txn/transaction.go
Labels: kind/enhancement, size/M

#4849 dnservice: refactoring local metadata
  pkg/dnservice/store_metadata.go
  pkg/dnservice/store_metadata_test.go
  pkg/util/file/file.go
  pkg/util/file/file_test.go
Labels: size/M, kind/refactor

#4858 taskservice: init task service types
  pkg/pb/task/task.pb.go
  pkg/pb/txn/txn.pb.go
  pkg/taskservice/types.go
  proto/task.proto
Labels: kind/feature, size/M

#4855 logservice: allow unresolved host in config
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
Labels: kind/enhancement, size/S

#4859 fix bug: add bit operator: >>, <<, ~
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/op_bit.go
  pkg/sql/plan/function/operator/op_bit_test.go
  pkg/sql/plan/function/operator/unaryops.go
  pkg/sql/plan/function/operator/unaryops_test.go
  pkg/sql/plan/function/operators.go
  test/cases/operator/operator.test
  test/result/operator/operator.result
Labels: kind/bug, kind/feature, size/L

#4864 cnservice: add load and save CNStore metadata
  etc/cn-minimal-test.toml
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-mem-engine-test.toml
  etc/cn-standalone-test.toml
  pkg/cnservice/server.go
  pkg/cnservice/server_metadata.go
  pkg/cnservice/server_metadata_test.go
  pkg/cnservice/types.go
  pkg/pb/metadata/metadata.go
Labels: kind/feature, size/M

#4841 fix bug: operator function do not support args are bool and numeric
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/function/type_check.go
  test/cases/dtype/bool.test
  test/cases/function/func_cast.test
  test/result/function/func_coalesce.result
  test/result/subquery/subquery-with-in.result
Labels: kind/bug, size/M

#4868 [Enhancement]: gcc build mod only allowed in C99
  cgo/Makefile
Labels: kind/enhancement, size/XS

#4869 refactor func of variance and std for decimal
  pkg/sql/colexec/agg/stddevpop/stddevpop.go
  pkg/sql/colexec/agg/stddevpop/stddevpop_test.go
  pkg/sql/colexec/agg/stddevpop/types.go
  pkg/sql/colexec/agg/variance/types.go
  pkg/sql/colexec/agg/variance/variance.go
  pkg/sql/colexec/agg/variance/variance_test.go
  pkg/sql/colexec/aggregate/aggregate.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/aggregate.go
  test/cases/function/func_aggr_count.test
  test/cases/function/func_aggr_variance.test
  test/result/function/func_aggr_variance.result
Labels: size/M

#4645 Support json_extract function
  pkg/container/bytejson/README.md
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/path_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/container/types/json.go
  pkg/container/types/json_test.go
  pkg/errno/errcode.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/builtin/binary/json_extract.go
  pkg/sql/plan/function/builtin/binary/json_extract_test.go
  pkg/sql/plan/function/builtins.go
  pkg/vectorize/json_extract/json_extract.go
  pkg/vectorize/json_extract/json_extract_test.go
  test/cases/function/func_json_extract.test
  test/result/function/func_json_extract.result
Labels: kind/feature, size/XL

#4860 fileservice: add Mutator.Append
  pkg/fileservice/file_service.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mutable_file_service.go
  pkg/fileservice/mutable_file_service_test.go
Labels: kind/enhancement, size/S

#4873 txnstorage: various fixes
  pkg/txn/storage/txn/any.go
  pkg/txn/storage/txn/batch.go
  pkg/txn/storage/txn/frontend_test.go
  pkg/txn/storage/txn/mem_handler.go
Labels: kind/bug, size/S

#4742 Metric/Trace use FileService to write down CSV data.
  .gitignore
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  etc/cn-minimal-test.toml
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-mem-engine-test.toml
  etc/cn-standalone-test.toml
  etc/dn-minimal-s3-test.toml
  etc/dn-minimal-test.toml
  etc/log-minimal-test.toml
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/config/configuration.go
  pkg/dnservice/factory.go
  pkg/dnservice/store_test.go
  pkg/logutil/internal.go
  pkg/logutil/report.go
  pkg/pb/metric/metric.pb.go
  pkg/txn/storage/txn/frontend_test.go
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/export/fs_writer.go
  pkg/util/export/fs_writer_test.go
  pkg/util/export/type.go
  pkg/util/export/type_test.go
  pkg/util/metric/config.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_collector.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_exporter.go
  pkg/util/metric/metric_exporter_test.go
  pkg/util/metric/metric_test.go
  pkg/util/stack_test.go
  pkg/util/trace/.gitignore
  pkg/util/trace/batch_span_processor.go
  pkg/util/trace/batch_span_processor_test.go
  pkg/util/trace/buffer_pipe_sql.go
  pkg/util/trace/buffer_pipe_sql_test.go
  pkg/util/trace/config.go
  pkg/util/trace/context.go
  pkg/util/trace/example/main.go
  pkg/util/trace/mo_trace.go
  pkg/util/trace/mo_trace_test.go
  pkg/util/trace/noop_trace.go
  pkg/util/trace/noop_trace_test.go
  pkg/util/trace/ptrace.go
  pkg/util/trace/report_error.go
  pkg/util/trace/report_log.go
  pkg/util/trace/report_log_test.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/schema.go
  pkg/util/trace/schema_test.go
  pkg/util/trace/trace.go
  pkg/util/trace/trace_test.go
  pkg/util/trace/type.go
  pkg/util/uuidutil.go
  pkg/util/uuidutil_test.go
  proto/metric.proto
Labels: kind/feature, size/XL

#4856 add auto_increment columns test
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/auto_increment/auto_increment_columns.sql
  test/resources/auto_increment_columns/auto_increment_1.csv
  test/resources/auto_increment_columns/auto_increment_2.csv
  test/resources/auto_increment_columns/auto_increment_3.csv
Labels: size/XL, kind/test-ci

#4893 Add golang hash function implementation for older CPUS
  pkg/container/hashtable/bucket.go
  pkg/container/hashtable/hash.go
  pkg/container/hashtable/hash_amd64.go
  pkg/container/hashtable/hash_amd64.s
  pkg/container/hashtable/hash_arm64.go
  pkg/container/hashtable/hash_arm64.s
  pkg/container/hashtable/hash_fallback_dummy.go
  pkg/container/hashtable/hash_test.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: kind/bug, size/M

#4901 Implement a rowid type.
  pkg/compare/compare.go
  pkg/container/types/encoding_test.go
  pkg/container/types/txnts.go
  pkg/container/types/types.go
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/sort/sort.go
  pkg/sql/colexec/agg/count/count.go
  pkg/sql/colexec/aggregate/aggregate.go
  pkg/sql/colexec/update/update.go
  pkg/txn/storage/txn/types.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/hack.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vecwindow.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/rowid/func.go
  pkg/vm/engine/tae/mergesort/rowid/heap.go
  pkg/vm/engine/tae/mergesort/rowid/sort.go
  pkg/vm/engine/tae/mergesort/rowid/types.go
  pkg/vm/engine/tae/mergesort/txnts/func.go
  pkg/vm/engine/tae/mergesort/txnts/heap.go
  pkg/vm/engine/tae/mergesort/txnts/sort.go
  pkg/vm/engine/tae/mergesort/txnts/types.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/model/model_test.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/moengine/utils.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
Labels: size/XXL, kind/refactor

#4902 taskservice: modify the task-related abstract
  pkg/pb/task/task.pb.go
  pkg/taskservice/types.go
  proto/task.proto
Labels: kind/api-change, size/M

#4882 cnservice: add cn store heartbeat
  pkg/cnservice/server.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/types.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  proto/logservice.proto
Labels: kind/feature, size/M

#4884 process: add not nil fields to New params; use testutil.NewProc in tests
  pkg/compare/compare_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sort/sort_test.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/connector/connector_test.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/hashbuild/build_test.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/limit/limit_test.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopsemi/join_test.go
  pkg/sql/colexec/loopsingle/join_test.go
  pkg/sql/colexec/mark/join_test.go
  pkg/sql/colexec/merge/merge_test.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergeorder/order_test.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/offset/offset_test.go
  pkg/sql/colexec/order/order_test.go
  pkg/sql/colexec/output/output_test.go
  pkg/sql/colexec/product/product_test.go
  pkg/sql/colexec/projection/projection_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/plan/function/builtin/binary/date_format_test.go
  pkg/sql/plan/function/builtin/binary/endswith_test.go
  pkg/sql/plan/function/builtin/binary/power_test.go
  pkg/sql/plan/function/builtin/binary/startswith_test.go
  pkg/sql/plan/function/builtin/multi/ceil_test.go
  pkg/sql/plan/function/builtin/multi/date_add_test.go
  pkg/sql/plan/function/builtin/multi/date_sub_test.go
  pkg/sql/plan/function/builtin/multi/floor_test.go
  pkg/sql/plan/function/builtin/multi/round_test.go
  pkg/sql/plan/function/builtin/multi/rpad_test.go
  pkg/sql/plan/function/builtin/multi/substr_test.go
  pkg/sql/plan/function/builtin/multi/utctimestamp_test.go
  pkg/sql/plan/function/builtin/unary/abs_test.go
  pkg/sql/plan/function/builtin/unary/ltrim_test.go
  pkg/sql/plan/function/builtin/unary/space_test.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operator/like_test.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/vm/process/process.go
Labels: kind/enhancement, size/S

#4906 [Doc]:Subquery_all.md fix some error result
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-all.md
Labels: kind/documentation, size/XS

#4870 Remove dependency on StatSafeTS
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/checkpoint.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/dbbase.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/filter.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/mvccnode.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tasks/scheduler.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/feature, size/M, kind/refactor

#4892 [Doc]: update with-cte.md SQL format adjustment
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/with-cte.md
Labels: kind/documentation, size/XS

#4895 [Doc]: update interval.md fix some error result
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/interval.md
Labels: kind/documentation, size/XS

#4897 add note:installed config file difference between pre0.6 and 0.5
  README.md
  README_CN.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
Labels: kind/documentation, size/XS

#4908 replenish distinct test
  test/cases/distinct/distinct.sql
  test/result/distinct/distinct.result
Labels: size/S, kind/test-ci

#4910 Hide IsConst
  pkg/container/vector/vector.go
  pkg/sql/plan/function/builtin/binary/findinset_test.go
  pkg/sql/plan/function/builtin/binary/startswith.go
  pkg/sql/plan/function/builtin/unary/bit_length_test.go
  pkg/sql/plan/function/builtin/unary/day.go
  pkg/sql/plan/function/builtin/unary/day_test.go
  pkg/sql/plan/function/builtin/unary/empty_test.go
  pkg/sql/plan/function/builtin/unary/month.go
  pkg/sql/plan/function/builtin/unary/oct_test.go
  pkg/sql/plan/function/builtin/unary/reverse.go
  pkg/sql/plan/function/builtin/unary/week.go
  pkg/sql/plan/function/builtin/unary/week_test.go
  pkg/sql/plan/function/builtin/unary/year.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operator/is_test.go
Labels: size/M

#4898 add external scan for text data type
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
Labels: kind/bug, size/M

#4923 morpc: add disable auto cancel option
  pkg/common/morpc/server.go
Labels: kind/enhancement, size/S

#4912 fix bug: length of func substring result is not correct
  pkg/sql/plan/function/builtin/multi/substr.go
  test/cases/function/func_string_substring.test
  test/result/function/func_string_substring.result
Labels: kind/bug, size/M

#4915 Add cache interface for cn
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/S

#4883 Txn message
  pkg/pb/api/api.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/timestamp/timestamp.go
  proto/api.proto
Labels: kind/feature, size/M

#4913 fix unix_timestamp() and modify error msg
  pkg/sql/plan/function/builtin/multi/unix_timestamp.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function.go
  test/cases/function/func_datetime_unixtime.test
  test/result/expression/temporal_interval.result
  test/result/function/func_cast.result
  test/result/function/func_date_format_1.result
  test/result/function/func_datetime_extract.result
  test/result/function/func_datetime_unixtime.result
  test/result/function/func_string_uuid.result
Labels: size/S

#4933 fix: #3934 ln function return error
  pkg/vectorize/momath/math.go
  pkg/vectorize/momath/math_test.go
  test/result/function/func_math_ln.result
  test/result/function/func_math_log.result
Labels: kind/bug, size/M

#4930 add Process.TxnClient and use it in auto increment codes
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/testutil/util_new.go
  pkg/vectorize/momath/math_test.go
  pkg/vm/engine/tae/common/mempool_test.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/enhancement, size/S

#4941 taskservice: initial taskservice
  go.mod
  go.sum
  pkg/pb/task/task.go
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_test.go
  pkg/taskservice/task_storage_test.go
  pkg/taskservice/types.go
  proto/task.proto
Labels: kind/feature, size/XL

#4928 Hide Data from vector
  pkg/container/batch/batch.go
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/partition/partition_test.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/connector/connector_test.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/external/external.go
  pkg/sql/plan/function/builtin/binary/power.go
  pkg/sql/plan/function/builtin/multi/date_add.go
  pkg/sql/plan/function/builtin/multi/date_sub.go
  pkg/sql/plan/function/builtin/unary/abs.go
  pkg/sql/plan/function/builtin/unary/date.go
  pkg/sql/plan/function/builtin/unary/day.go
  pkg/sql/plan/function/builtin/unary/dayofyear.go
  pkg/sql/plan/function/builtin/unary/math.go
  pkg/sql/plan/function/builtin/unary/month.go
  pkg/sql/plan/function/builtin/unary/oct.go
  pkg/sql/plan/function/builtin/unary/timestamp.go
  pkg/sql/plan/function/builtin/unary/week.go
  pkg/sql/plan/function/builtin/unary/weekday.go
  pkg/sql/plan/function/builtin/unary/year.go
  pkg/sql/plan/function/operator/arith.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/compare.go
  pkg/sql/plan/function/operator/unaryops.go
  pkg/testutil/util_make.go
  pkg/vectorize/abs/abs.go
  pkg/vectorize/power/power.go
  pkg/vectorize/power/power_test.go
  pkg/vectorize/week/week.go
  pkg/vm/engine/memEngine/reader.go
  pkg/vm/engine/tae/moengine/utils.go
Labels: size/XL, kind/refactor

#4932 fix bug: count(*) without from clause is error
  pkg/sql/plan/base_binder.go
  test/cases/distinct/distinct.sql
  test/result/distinct/distinct.result
  test/result/function/func_aggr_avg.result
  test/result/function/func_aggr_count.result
Labels: kind/bug, size/S

#4953 mv tenant context keys to defines package
  pkg/defines/type.go
  pkg/frontend/authenticate.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/vm/engine/tae/moengine/helper.go
Labels: kind/enhancement, size/S

#4922 add mo_columns a composite pk
  pkg/txn/storage/txn/catalog_handler_test.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/enhancement, size/M, component/distributed tae

#4969 refactor txn visibility
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/dbbase.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/mvccnode.go
  pkg/vm/engine/tae/catalog/node.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/common/dlnode.go
  pkg/vm/engine/tae/iface/txnif/cmd.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: size/XXL, kind/refactor, component/distributed tae

#4909 fix bug: view cannot be involved in a join query
  pkg/sql/plan/query_builder.go
  test/cases/view/view.test
  test/result/view/view.result
Labels: kind/bug, size/M

#4872 Add HEX function
  pkg/sql/plan/function/builtin/unary/hex.go
  pkg/sql/plan/function/builtin/unary/hex_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  test/cases/function/func_hex.test
  test/result/function/func_hex.result
Labels: kind/feature, size/M

#4955 add err define of mysql to moerr
  cgo/mo_impl.h
  pkg/common/moerr/error.go
  pkg/common/moerr/error_test.go
  pkg/common/moerr/mysql_error_define.go
  pkg/container/types/decimal.go
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_predefines.go
  pkg/frontend/protocol.go
  pkg/frontend/session.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/partition.go
  pkg/vectorize/div/dec.go
  test/cases/auto_increment/auto_increment_columns.result
  test/result/dtype/text_1.result
  test/result/function/func_aggr_max.result
  test/result/function/func_string_rtrim_ltrim.result
  test/result/operator/is_operator.result
Labels: size/XXL

#4961 modify the describtion about image version
  README.md
  README_CN.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
Labels: kind/documentation, size/XS

#4890 [Doc]: Update select.md Adjusting Document Content
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/select.md
Labels: kind/documentation, size/XS

#4974 add elementary privilege check for statements
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/sql/parsers/tree/revoke.go
  test/cases/tenant/privilege/database.test
  test/result/tenant/privilege/database.result
Labels: size/XXL

#4877 [Documentation]: Optimizing document presentation
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Definition-Statements/primary-key.md
Labels: kind/documentation, size/XS

#4973 dn txn related code refactor
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/api-change, size/L, kind/refactor, component/distributed tae

#4959 vector: return nil in encodeColToByteSlice if vector.Col is nil
  pkg/container/vector/tools.go
Labels: kind/bug, size/XS

#4977 [Doc]: Fix some code error
  docs/cn/MatrixOne/Tutorial/develop-java-connect-mo.md
Labels: kind/documentation, size/XS

#4979 log statement status
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
Labels: kind/enhancement, size/S

#4960 fix bug:orderBy&limit clause lost in parenSelect clause
  pkg/sql/plan/query_builder.go
  test/cases/union/union.result
  test/cases/union/union.sql
Labels: kind/bug, size/M

#4983 Fix the oom bug of top
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/top/top.go
Labels: kind/bug, size/S

#4980 logservice: skip TestGossipInSimulatedCluster
  pkg/logservice/service_test.go
Labels: size/XS, kind/test-ci

#4995 taskservice: support re-allocate CN for task
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_test.go
Labels: kind/bug, size/S

#4993 misc: update code owner
  CODEOWNERS
Labels: kind/documentation, size/S

#4904 [Doc]: Adjusting document presentation
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/comparisons-using-subqueries.md
Labels: kind/documentation, size/XS

#4956 engine: add context and error to Rows and Size
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/txn/table.go
  pkg/vm/engine/types.go
Labels: kind/enhancement, size/M

#4985 remove tag 3419
  test/cases/expression/case_when.sql
  test/cases/expression/cte.sql
  test/cases/subquery/subquery-with-exists.sql
  test/cases/subquery/subquery-with-in.sql
  test/result/expression/case_when.result
  test/result/expression/cte.result
Labels: size/S, kind/test-ci

#4984 remove tag 4660
  test/cases/dtype/text_1.sql
  test/result/dtype/text_1.result
Labels: size/S, kind/test-ci

#4996 fix bug: output is incorrect in union clause
  pkg/sql/plan/function/type_check.go
  test/cases/union/union.result
  test/cases/union/union.sql
Labels: kind/bug, size/S

#4632 Add load_file function
  pkg/sql/plan/function/builtin/unary/load_file.go
  pkg/sql/plan/function/builtin/unary/load_file_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  test/cases/function/func_load_file.test
  test/resources/file_test/empty.txt
  test/resources/file_test/normal.txt
  test/result/function/func_load_file.result
Labels: kind/feature, kind/api-change, size/M

#4989 update metric
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/metric/batch_collector.go
  pkg/util/metric/m_hardware.go
  pkg/util/metric/m_process.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_sql.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/mtype_counter.go
Labels: kind/enhancement, size/M

#4843 handle data cast overflow
  cgo/decimal.c
  cgo/mo.h
  pkg/common/hashmap/strhashmap_test.go
  pkg/container/types/decimal.go
  pkg/container/types/decimal_test.go
  pkg/frontend/authenticate.go
  pkg/sql/colexec/agg/anyvalue/anyvalue_test.go
  pkg/sql/colexec/agg/avg/avg_test.go
  pkg/sql/colexec/agg/max/max_test.go
  pkg/sql/colexec/agg/min/min_test.go
  pkg/sql/colexec/agg/stddevpop/stddevpop.go
  pkg/sql/colexec/agg/stddevpop/stddevpop_test.go
  pkg/sql/colexec/agg/sum/sum_test.go
  pkg/sql/colexec/agg/variance/variance.go
  pkg/sql/colexec/agg/variance/variance_test.go
  pkg/sql/compile/dml.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/builtin/unary/oct_test.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/vectorize/add/add_test.go
  pkg/vectorize/div/div_test.go
  pkg/vectorize/mult/mult_test.go
  pkg/vectorize/neg/neg_test.go
  pkg/vectorize/oct/oct.go
  pkg/vectorize/sub/sub_test.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/moengine/utils.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/dtype/bigint.test
  test/cases/dtype/decimal.test
  test/cases/dtype/int.test
  test/cases/dtype/smallint.test
  test/cases/dtype/tinyint.test
  test/result/dtype/bigint.result
  test/result/dtype/decimal.result
  test/result/dtype/int.result
  test/result/dtype/smallint.result
  test/result/dtype/tinyint.result
Labels: kind/bug, size/L

#4998 testutil: add etl fs to NewFS
  pkg/testutil/util_new.go
Labels: kind/enhancement, size/XS

#4975 Add disttae's logic of engine interface and database interface
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/L

#4991 add check bvt issue ci
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#4927 Update docs/cn/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions.md
  docs/cn/MatrixOne/Contribution-Guide/Tutorial/develop_aggregate_functions.md
Labels: kind/documentation, size/XS

#5003 fix: skip specific metric check
  pkg/util/metric/metric_test.go
Labels: size/XS, kind/test-ci

#5005 add text date type export function
  pkg/frontend/export.go
Labels: kind/bug, size/XS

#5008 Modify the time unit of explain
  pkg/vm/process/analyze.go
Labels: kind/feature, size/XS

#5001 FmtCtx with quote string
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/tree/constant.go
  pkg/sql/parsers/tree/format.go
Labels: kind/feature, size/S

#5002 taskservice: implement the TaskRunner
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/task_runner_test.go
Labels: kind/feature, size/L

#5013 hakeeper: lower the log level for frequent output
  pkg/hakeeper/checkers/dnservice/parse.go
Labels: kind/enhancement, size/XS

#4972 Layout object
  pkg/objectio/block.go
  pkg/objectio/buffer.go
  pkg/objectio/column.go
  pkg/objectio/extent.go
  pkg/objectio/index.go
  pkg/objectio/meta.go
  pkg/objectio/object.go
  pkg/objectio/reader.go
  pkg/objectio/type.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
Labels: kind/feature, size/XL

#5006 Fix #4790
  pkg/container/vector/vector.go
Labels: kind/bug, size/XS

#5010 cnservice: add non-distributed memory CN engine type
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-mem-engine-test.toml
  etc/cn-standalone-non-dist-memory-test.toml
  pkg/cnservice/memory_engine.go
  pkg/cnservice/server.go
  pkg/cnservice/types.go
Labels: kind/enhancement, size/M

#5015 throw no database select error msg
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/XS

#5018 fix bug: limit is incorrect in plan for union clause
  pkg/sql/plan/query_builder.go
  test/cases/union/union.result
  test/cases/union/union.sql
Labels: kind/bug, size/S

#5025 txnstorage: various improvements
  pkg/txn/storage/txn/any.go
  pkg/txn/storage/txn/batch.go
  pkg/txn/storage/txn/catalog.go
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/nullable.go
  pkg/txn/storage/txn/table.go
  pkg/txn/storage/txn/types.go
Labels: kind/enhancement, size/L

#5016 moengine: implement wrappedTx.Snapshot; fix wrappedEngine.NewWithSnapshot
  pkg/vm/engine/tae/moengine/txn_wrapper.go
  pkg/vm/engine/tae/moengine/txn_wrapper_test.go
Labels: kind/bug, size/S

#5030 add union and union all test
  test/cases/dml/select/union_and_union_all.sql
  test/result/dml/select/union_and_union_all.result
Labels: size/XL, kind/test-ci

#5021 [Opt] Improve join order by considering primary keys
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/tpch/ddl.sql
  test/result/explain/explain.result
Labels: kind/enhancement, size/XL

#5031 txn: fix panic when sending txn response
  pkg/pb/txn/txn.go
  pkg/txn/service/service_cn_handler.go
Labels: kind/bug, size/XS

#4630 support serialization from multi column to single
  LICENSES/Foundationdb-license
  pkg/container/types/tuple.go
  pkg/container/types/tuple_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/function/builtin/multi/serial.go
  pkg/sql/plan/function/builtin/multi/serial_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/composite_primary_key_util_test.go
  proto/plan.proto
Labels: size/XXL

#5032 support Single quotation mark when load with file
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
Labels: kind/bug, size/S

#4999 fileservice: use int64 extensively
  pkg/dnservice/store_metadata_test.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/config.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/lru.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/buffer.go
  pkg/objectio/column.go
  pkg/objectio/reader.go
  pkg/sql/plan/function/builtin/unary/load_file_test.go
  pkg/util/export/fs_writer.go
  pkg/util/file/file.go
Labels: kind/enhancement, size/M

#5035 fix show create table with auto_incr col
  pkg/sql/plan/build_show.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/auto_increment/auto_increment_columns.sql
  test/result/ddl/table_partition.result
Labels: kind/bug, size/S

#5043 txnstorage: various changes
  pkg/txn/storage/txn/account.go
  pkg/txn/storage/txn/catalog.go
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/data.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/table.go
  pkg/txn/storage/txn/table_iter.go
  pkg/txn/storage/txn/table_test.go
  pkg/txn/storage/txn/tuple.go
Labels: kind/enhancement, size/L

#5044 Reduce unnecessary memory overhead
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/strhashmap.go
  pkg/container/vector/vector.go
Labels: kind/enhancement, size/S

#5047 Add func to convert vector to proto vector
  pkg/container/vector/tools.go
  pkg/pb/api/api.pb.go
  proto/api.proto
Labels: kind/enhancement, size/S

#5014 fix auto_incr col default value bug
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/auto_increment/auto_increment_columns.sql
Labels: kind/bug, size/S

#4978 Hakeeper: Add Task Scheduler
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/checker.go
  pkg/hakeeper/config.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/task/cn_ordered_map.go
  pkg/hakeeper/task/cn_ordered_map_test.go
  pkg/hakeeper/task/parse.go
  pkg/hakeeper/task/parse_test.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/logservice/config.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/pb/logservice/logservice.pb.go
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/task_runner_test.go
  pkg/taskservice/task_service_test.go
  pkg/taskservice/task_storage_test.go
  proto/logservice.proto
Labels: kind/feature, size/L

#5049 fix bug when load with bigint value
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/XS

#5033 INSERT value with function
  test/cases/dml/insert/insert_with_function.sql
  test/result/dml/insert/insert_with_function.result
Labels: size/M, kind/test-ci

#5023 fix bug: when some project is null, type cast is incorrect in union clause
  pkg/sql/plan/query_builder.go
  test/cases/union/union.result
  test/cases/union/union.sql
Labels: kind/bug, size/S

#5051 support on update in create table an update
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/operator/cast.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/cases/dml/update/update.test
  test/result/dml/update/update.result
Labels: size/XXL

#5012 rename pkg/util/errors -> pkg/util/errutil
  pkg/common/moerr/error.go
  pkg/util/errors/message.go
  pkg/util/errors/message_test.go
  pkg/util/errors/panic.go
  pkg/util/errors/panic_test.go
  pkg/util/errutil/context.go
  pkg/util/errutil/context_test.go
  pkg/util/errutil/errors.go
  pkg/util/errutil/errors_test.go
  pkg/util/errutil/stack.go
  pkg/util/errutil/stack_test.go
  pkg/util/export/batch_processor_test.go
  pkg/util/export/fs_writer.go
  pkg/util/stack.go
  pkg/util/trace/buffer_pipe_sql.go
  pkg/util/trace/buffer_pipe_sql_test.go
  pkg/util/trace/example/main.go
  pkg/util/trace/report_error.go
  pkg/util/trace/trace.go
Labels: size/L, kind/refactor

#5054 fix bug: COM_EXECUTE in MySQL protocol will response by binary row not text row
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
Labels: kind/bug, size/M

#5058 more info of sytax error when parse
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  test/cases/auto_increment/auto_increment_columns.result
  test/cases/operator/bag_operator.result
  test/result/dtype/text_1.result
  test/result/dtype/uuid.result
  test/result/expression/cte.result
  test/result/expression/temporal_interval.result
  test/result/function/func_datetime_extract.result
  test/result/operator/is_operator.result
  test/result/tenant/tenant.result
  test/result/transaction/autocommit_1.result
Labels: size/M

#5036 support more text and blob type
  pkg/sql/plan/build_util.go
  test/cases/dtype/text.test
  test/result/dtype/text.result
Labels: size/M

#5067 modify explain insert value panic error
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#5053 fix typos in pkg/tests/
  pkg/tests/service/fileservice.go
  pkg/tests/service/logservice.go
  pkg/tests/service/network.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/service/status.go
Labels: size/S, kind/refactor

#5011 txnengine, txnstorage: log tail
  pkg/txn/storage/txn/catalog_handler.go
  pkg/txn/storage/txn/handler.go
  pkg/txn/storage/txn/log_tail.go
  pkg/txn/storage/txn/log_tail_test.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/read.go
  pkg/txn/storage/txn/storage_test.go
  pkg/vm/engine/txn/log_tail.go
  pkg/vm/engine/txn/operations.go
Labels: kind/enhancement, size/M

#5064 add memengine ci job
  .github/workflows/ci.yml
Labels: size/S, do-not-merge/wip, kind/test-ci

#5071 fix the result of float/double with length&precision
  pkg/frontend/export.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build_util.go
  test/result/explain/explain.result
Labels: kind/bug, size/S

#5072 add elementary grant/revoke role, grant privilege
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/revoke.go
  test/cases/tenant/privilege/role.test
  test/result/tenant/privilege/role.result
  test/result/tenant/role.result
  test/result/tenant/user.result
Labels: kind/enhancement, kind/feature, size/XXL

#5037 Add prepare ts
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/checkpoint.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/dbbase.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/iface/txnif/cmd.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updateview.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  pkg/vm/engine/tae/wal/checkpoint.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
  pkg/vm/engine/tae/wal/wal_test.go
  pkg/vm/engine/tae/wal/walinfo.go
Labels: kind/feature, size/L, kind/refactor

#5073 Add logtail for disttae
  pkg/catalog/types.go
  pkg/cnservice/distributed_tae.go
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/txn/operations.go
  proto/api.proto
Labels: kind/feature, size/M

#5076 Tests: Add CN in tests
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/syshealth/check.go
  pkg/hakeeper/config.go
  pkg/hakeeper/rsm.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/network.go
  pkg/tests/service/network_test.go
  pkg/tests/service/options.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
  pkg/tests/service/utility.go
Labels: size/L, kind/test-ci

#5083 fix bug: Execute parameter parser incorrect
  pkg/frontend/mysql_protocol.go
Labels: kind/bug, size/XS

#5089 Modify the logic bug Issue#5062
  pkg/sql/plan/function/operator/logical.go
Labels: kind/bug, size/S

#5092 fix lastappendableblock
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/handle.go
Labels: kind/bug, size/S

#5022 feat(tae): add every column a zonemap
  pkg/container/types/encoding.go
  pkg/vm/engine/tae/db/compound_test.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/index_test.go
  pkg/vm/engine/tae/tables/indexwrapper/meta.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/helper.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
Labels: kind/feature, size/L, component/distributed tae

#5094 fix keyword 'password' conflict
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: size/XXL

#5075 fix bug: when union two same statement, rewrite rule is incorrect
  pkg/sql/plan/query_builder.go
  test/cases/dml/select/union_and_union_all.sql
  test/result/dml/select/union_and_union_all.result
Labels: size/S

#5093 feat(tae): Log tail phase 2
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/logtail.go
  pkg/vm/engine/tae/moengine/block.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/utils.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/feature, size/L, component/distributed tae

#5095 add view bvt test cases
  test/cases/view/view-from-subquery.result
  test/cases/view/view-from-subquery.sql
  test/cases/view/view-subquery-with-any.result
  test/cases/view/view-subquery-with-any.sql
  test/cases/view/view-subquery-with-exists.result
  test/cases/view/view-subquery-with-exists.sql
  test/cases/view/view-subquery-with-in.result
  test/cases/view/view-subquery-with-in.sql
  test/cases/view/view_all.result
  test/cases/view/view_all.sql
Labels: size/XXL, kind/test-ci

#5099 fix prepare for update bug
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/visit_plan.go
  test/cases/prepare/prepare.test
  test/cases/prepare/prepare_all.sql
  test/result/prepare/prepare.result
  test/result/prepare/prepare_all.result
Labels: kind/bug, size/M

#5077 taskservice: fix TestCompletedWithInvalidEpoch
  pkg/taskservice/task_service_test.go
Labels: kind/bug, size/XS

#5102 fix getappendableblk
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/handle.go
Labels: kind/bug, size/S

#5096 add isunkown/isnotunknown function
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/unknown.go
  pkg/sql/plan/function/operator/unknown_test.go
  pkg/sql/plan/function/operators.go
  pkg/testutil/util_compare.go
  test/cases/operator/is_operator.sql
  test/result/operator/is_operator.result
Labels: kind/bug, size/L

#5082 add taskservice argument when create logservice
  cmd/mo-service/main.go
  pkg/logservice/client_test.go
  pkg/logservice/config.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/service_wrap.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_metadata_test.go
  pkg/logservice/store_test.go
  pkg/logservice/testclient.go
  pkg/tests/service/logservice.go
  pkg/tests/service/service.go
  pkg/testutil/util_new.go
Labels: kind/enhancement, size/M

#5101 Test cases for comparison operator LIKE
  test/cases/operator/like_operator.sql
  test/result/operator/like_operator.result
Labels: size/L

#5109 fix double type parse bug
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/XS

#5120 txnengine: do retry in GetClusterDetailsFromHAKeeper
  pkg/vm/engine/txn/hakeeper.go
Labels: kind/bug, size/S

#5114 fix load oom bug
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: kind/bug, component/standalone tae, size/XS

#5111 Improve the logic of cn
  etc/cn-standalone-dist-tae.toml
  pkg/container/batch/batch.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/txn/engine.go
  pkg/vm/engine/types.go
Labels: kind/feature, size/XL

#4846 feat: add git describe --always option
  Makefile
Labels: kind/enhancement, size/XS

#5091 taskservice: add schedule cron tasks
  cmd/mo-service/main.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/logservice/client_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/testclient.go
  pkg/pb/task/task.go
  pkg/pb/task/task.pb.go
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/task_runner_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_cron_test.go
  pkg/taskservice/task_service_test.go
  pkg/taskservice/task_storage_test.go
  pkg/taskservice/types.go
  pkg/testutil/util_new.go
  proto/task.proto
Labels: kind/feature, size/L

#5103 hakeeper: add allocate unique ID
  pkg/logservice/config.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/service.go
  pkg/logservice/store.go
  pkg/pb/logservice/logservice.pb.go
  pkg/tests/service/service_test.go
  proto/logservice.proto
Labels: kind/feature, size/M

#5128 fix memory related bugs
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/stl/containers/stdvec.go
Labels: kind/bug, size/S, component/standalone tae
