Repository matrixorigin/matrixone, pull requests merged in 2022-04, with the labels that each got.

#2091 [MatrixCamp] Add built-in function weekday
  pkg/builtin/types.go
  pkg/builtin/unary/weekday.go
  pkg/vectorize/weekday/weekday.go
  pkg/vectorize/weekday/weekday_test.go
Labels: good first issue, reviewed, MatrixCamp

#2092 [MatrixCamp] Add Aggregate function bit_and
  go.sum
  pkg/container/ring/bitand/numeric.go
  pkg/container/ring/bitand/numeric_test.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/protocol_test.go
  pkg/sql/protocol/types.go
  pkg/sql/viewexec/transformer/transformer.go
  pkg/sql/viewexec/transformer/types.go
Labels: good first issue, reviewed, MatrixCamp

#2025 [MatrixCamp] add function cot
  pkg/builtin/types.go
  pkg/builtin/unary/cot.go
  pkg/vectorize/cot/cot.go
  pkg/vectorize/cot/cot_test.go
Labels: good first issue, reviewed, MatrixCamp

#2070 [MatrixCamp] Add Built-in function lpad
  .gitignore
  pkg/builtin/multi/lpad.go
  pkg/builtin/types.go
  pkg/vectorize/lpad/lpad.go
  pkg/vectorize/lpad/lpad_test.go
  pkg/vm/engine/aoe/common/codec/codec.go
Labels: good first issue, MatrixCamp

#2143 check whether a vector is constant in multiEval, unaryEval
  pkg/builtin/multi/ceil.go
  pkg/builtin/multi/floor.go
  pkg/builtin/multi/round.go
  pkg/sql/colexec/extend/overload/multi.go
  pkg/sql/colexec/extend/unary.go
Labels: reviewed

#2054 [MatrixCamp] Add Built-in function space
  pkg/builtin/types.go
  pkg/builtin/unary/space.go
  pkg/vectorize/space/space.go
  pkg/vectorize/space/space_test.go
Labels: good first issue, reviewed, MatrixCamp

#2055 [MatrixCamp] add function acos
  pkg/builtin/types.go
  pkg/builtin/unary/acos.go
  pkg/vectorize/acos/acos.go
  pkg/vectorize/acos/acos_test.go
Labels: good first issue, reviewed, MatrixCamp

#2152 [MatrixCamp] support bit_xor
  pkg/container/ring/bitxor/bit_xor.go
  pkg/container/ring/bitxor/bit_xor_test.go
  pkg/container/ring/bitxor/types.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/protocol_test.go
  pkg/sql/protocol/types.go
  pkg/sql/viewexec/transformer/transformer.go
  pkg/sql/viewexec/transformer/types.go
Labels: good first issue, reviewed, MatrixCamp

#2123 [MatrixCamp] Add Aggregate function bit_or
  pkg/container/ring/bitor/bitor.go
  pkg/container/ring/bitor/bitor_test.go
  pkg/sql/protocol/protocol.go
  pkg/sql/protocol/protocol_test.go
  pkg/sql/protocol/types.go
  pkg/sql/viewexec/transformer/transformer.go
  pkg/sql/viewexec/transformer/types.go
Labels: good first issue, reviewed, MatrixCamp

#2084 [MatrixCamp] Add built-in funcion date
  pkg/builtin/types.go
  pkg/builtin/unary/date.go
  pkg/vectorize/date/date.go
  pkg/vectorize/date/date_test.go
Labels: good first issue, MatrixCamp

#2124 [MatrixCamp] builtin function sinh
  pkg/builtin/types.go
  pkg/builtin/unary/sinh.go
  pkg/vectorize/sinh/sinh.go
  pkg/vectorize/sinh/sinh_test.go
Labels: good first issue, reviewed, MatrixCamp

#2169 [MatrixCamp] Add built-in function startswith
  pkg/builtin/binary/startsWith.go
  pkg/builtin/types.go
  pkg/vectorize/startsWith/startsWith.go
  pkg/vectorize/startsWith/startsWith_test.go
Labels: good first issue, reviewed, MatrixCamp

#2147 [MatrixCamp] Add built-in function rpad
  pkg/builtin/multi/rpad.go
  pkg/builtin/types.go
  pkg/vectorize/rpad/rpad.go
  pkg/vectorize/rpad/rpad_test.go
Labels: good first issue, reviewed, MatrixCamp

#2184 Fix the bug of times
  pkg/sql/viewexec/times/times.go
Labels: reviewed

#2178 [MatrixCamp] Add built-in function endswith
  pkg/builtin/binary/endswith.go
  pkg/builtin/types.go
  pkg/vectorize/endswith/endswith.go
  pkg/vectorize/endswith/endswith_test.go
Labels: good first issue, reviewed, MatrixCamp

#2217 Fix the bug of repeated data append after mo restart
  pkg/vm/engine/aoe/storage/db/replay.go
Labels: component/aoe, reviewed

#2245 Fix the bug of stuck
  go.mod
  go.sum
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
Labels: reviewed

#2250 Fix sca problems for aoe - phase 2
  pkg/vm/engine/aoe/common/helper/helper.go
  pkg/vm/engine/aoe/engine/database.go
  pkg/vm/engine/aoe/engine/engine_test.go
  pkg/vm/engine/aoe/engine/store.go
  pkg/vm/engine/aoe/engine/types.go
  pkg/vm/engine/aoe/protocol/protocol.go
  pkg/vm/engine/aoe/storage/aoedb/v1/db_test.go
  pkg/vm/engine/aoe/storage/aoedb/v1/split_test.go
  pkg/vm/engine/aoe/storage/common/iterator/types.go
  pkg/vm/engine/aoe/storage/container/vector/stdvec.go
  pkg/vm/engine/aoe/storage/container/vector/strvec.go
  pkg/vm/engine/aoe/storage/container/vector/wrapper.go
  pkg/vm/engine/aoe/storage/db/factories.go
  pkg/vm/engine/aoe/storage/db/replay.go
  pkg/vm/engine/aoe/storage/db/replay_test.go
  pkg/vm/engine/aoe/storage/db/snapshot.go
  pkg/vm/engine/aoe/storage/layout/dataio/index.go
  pkg/vm/engine/aoe/storage/layout/dataio/mockseg.go
  pkg/vm/engine/aoe/storage/layout/dataio/segwriter.go
  pkg/vm/engine/aoe/storage/layout/dataio/sortedseg.go
  pkg/vm/engine/aoe/storage/layout/dataio/tblk.go
  pkg/vm/engine/aoe/storage/logstore/rotational.go
  pkg/vm/engine/aoe/storage/metadata/v1/block.go
  pkg/vm/engine/aoe/storage/metadata/v1/catalog.go
  pkg/vm/engine/aoe/storage/metadata/v1/database.go
  pkg/vm/engine/aoe/storage/metadata/v1/database_test.go
  pkg/vm/engine/aoe/storage/metadata/v1/entry.go
  pkg/vm/engine/aoe/storage/metadata/v1/helper.go
  pkg/vm/engine/aoe/storage/metadata/v1/metadata_test.go
  pkg/vm/engine/aoe/storage/metadata/v1/split.go
  pkg/vm/engine/aoe/storage/ops/ops.go
  pkg/vm/engine/aoe/storage/wal/shard/proxy.go
  pkg/vm/engine/aoe/storage/wal/shard/shard_test.go
  pkg/vm/engine/aoe/storage/wal/shard/types.go
Labels: reviewed

#2252 add tpe engine test case code
  pkg/vm/engine/tpe/engine/engine_test.go
  pkg/vm/engine/tpe/engine/reader.go
  pkg/vm/engine/tpe/engine/reader_test.go
  pkg/vm/engine/tpe/tuplecodec/computationhandler_test.go
  pkg/vm/engine/tpe/tuplecodec/cubekv_test.go
  pkg/vm/engine/tpe/tuplecodec/decoder.go
  pkg/vm/engine/tpe/tuplecodec/decoder_test.go
Labels: reviewed

#2269 support the load stream with float value in NOT-FLOAT column
  pkg/frontend/load.go
Labels: reviewed

#2279 Fix sca problems for aoe - phase 5
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/helper.go
  pkg/vm/driver/aoe/helper.go
  pkg/vm/driver/aoe/storage.go
  pkg/vm/driver/cube_driver.go
  pkg/vm/driver/error/errors.go
  pkg/vm/driver/helper.go
  pkg/vm/driver/kv/executor.go
  pkg/vm/engine/aoe/cmd/read/main.go
  pkg/vm/engine/aoe/common/codec/codec.go
  pkg/vm/engine/aoe/common/helper/helper_test.go
  pkg/vm/engine/aoe/common/util/util.go
  pkg/vm/engine/aoe/engine/relation.go
  pkg/vm/engine/aoe/engine/types.go
  pkg/vm/engine/aoe/engine/worker.go
  pkg/vm/engine/aoe/local/database.go
  pkg/vm/engine/aoe/protocol/protocol.go
  pkg/vm/engine/aoe/protocol/types.go
  pkg/vm/engine/aoe/storage/buffer/manager/manager.go
  pkg/vm/engine/aoe/storage/common/mempool.go
  pkg/vm/engine/aoe/storage/metadata/v1/types.go
  pkg/vm/engine/aoe/storage/mutation/blk_test.go
  pkg/vm/engine/aoe/storage/mutation/buffer/base/types.go
  pkg/vm/engine/aoe/storage/mutation/buffer/limiter.go
  pkg/vm/engine/aoe/storage/sched/eventhandler.go
  pkg/vm/engine/aoe/storage/wal/shard/manager.go
Labels: reviewed

#2286 Fix the bug of zonemap
  pkg/sql/compile/scope.go
Labels: reviewed

#2288 refine_decimal_doc
  pkg/container/types/decimal.go
Labels: reviewed

#2292 more case support in plan2
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan2/build.go
  pkg/sql/plan2/build_expr.go
  pkg/sql/plan2/build_from.go
  pkg/sql/plan2/build_select.go
  pkg/sql/plan2/build_subquery.go
  pkg/sql/plan2/build_test.go
  pkg/sql/plan2/build_util.go
  pkg/sql/plan2/init.go
  pkg/sql/plan2/mock.go
  pkg/sql/plan2/types.go
  proto/plan.proto
Labels: reviewed

#2277 delete the recover function call
  go.mod
  go.sum
  pkg/frontend/load.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine_manager.go
Labels: reviewed

#2280 [MatrixCamp] Add built-in function lengthUTF8
  pkg/builtin/types.go
  pkg/builtin/unary/length_utf8.go
  pkg/vectorize/lengthutf8/length_utf8.go
  pkg/vectorize/lengthutf8/length_utf8_amd64.go
  pkg/vectorize/lengthutf8/length_utf8_avx2_amd.s
  pkg/vectorize/lengthutf8/length_utf8_test.go
Labels: good first issue, reviewed

#2332 Fix the bug of dealing with Null values in mergesort of varchar
  pkg/vm/engine/aoe/mergesort/varchar/func.go
Labels: reviewed
