Repository matrixorigin/matrixone, pull requests merged in 2022-08, with the labels that each got.

#4113 Support json type storage
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/container/types/json.go
  pkg/container/types/types.go
  pkg/container/vector/vector.go
  pkg/encoding/encoding.go
  pkg/errno/errcode.go
  pkg/frontend/insert.go
  pkg/frontend/insert_test.go
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/resultset.go
  pkg/frontend/util.go
  pkg/partition/partition.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/update.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/binary/json_extract.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/make.go
  pkg/testutil/util_compare.go
  pkg/vectorize/json_extract/json_extract.go
  pkg/vectorize/json_extract/json_extract_test.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  proto/plan.proto
  test/cases/dtype/json.test
  test/result/dtype/json.result
Labels: kind/feature

#4300 contributors readme action update
  README.md
Labels: size/l

#4298 Update Golangci-lint & `make pb`
  .golangci.yml
  Makefile
  proto/gen.sh
Labels: size/l, kind/test-ci

#4297 logservice: added some missing loggings
  pkg/logservice/service.go
  pkg/logservice/service_commands.go
  pkg/logservice/store.go
Labels: kind/refactor

#4304 Refactor operators
  pkg/container/batch/batch.go
  pkg/sql/colexec/complement/complement.go
  pkg/sql/colexec/complement/complement_test.go
  pkg/sql/colexec/complement/types.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/joincondition/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/loopcomplement/complement.go
  pkg/sql/colexec/loopcomplement/complement_test.go
  pkg/sql/colexec/loopcomplement/types.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/types.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopleft/types.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsemi/types.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/merge/types.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/types.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/product/types.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/restrict/restrict.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/semi/types.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/union/types.go
  pkg/sql/colexec/union/union.go
  pkg/sql/colexec/union/union_test.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/mheap/mheap.go
  pkg/vm/mheap/types.go
  pkg/vm/overload.go
  pkg/vm/types.go
Labels: kind/feature, size/xxl, kind/refactor

#4302 HAKeeper: Fix default time test error
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/logservice/check_test.go
  pkg/hakeeper/checkers/logservice/parse_test.go
Labels: kind/test-ci

#4307 bitmap: implement encoding.BinaryMarshaler/Unmarshaler for Bitmap
  pkg/common/bitmap/bitmap.go
Labels: kind/enhancement, size/s

#4310 add kill zombie schedule command
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/parse.go
  pkg/hakeeper/checkers/logservice/parse_test.go
  pkg/hakeeper/checkers/logservice/stats.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/create_operator.go
  pkg/hakeeper/operator/steps.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/feature

#4313 logservice: handle kill zombie command
  pkg/logservice/service_commands.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/store_metadata.go
  pkg/logservice/store_metadata_test.go
Labels: kind/feature

#4303 Fix decimal arithmatics that lost scale.
  pkg/sql/plan/function/operator/arith.go
Labels: kind/bug

#4315 dnservice: pass clock to taestorage.New
  pkg/dnservice/factory.go
  pkg/txn/storage/tae/storage.go
Labels: kind/enhancement, size/XS

#4317 cgo: fix Makefile to avoid recompilation in every build
  cgo/Makefile
Labels: kind/bug, size/XS

#4316 feat: add query to internalExecutor
  cmd/db-server/main.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/metric/metric_collector_test.go
Labels: kind/enhancement, kind/feature

#4320 Mergify: add mergify message for PR
  .github/mergify.yml
Labels: size/XS, kind/test-ci

#4319 chore: disable optimization and inlining when build debug binary
  Makefile
Labels: kind/enhancement, size/XS

#4318 logservice: always validate client config first
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
Labels: kind/enhancement

#4321 Hashmap support mmu
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/inthashmap_test.go
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/common/hashmap/types.go
  pkg/container/hashtable/bucket.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/complement/complement.go
  pkg/sql/colexec/complement/complement_test.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/colexec/union/union.go
  pkg/vm/mheap/mheap.go
  pkg/vm/mheap/types.go
Labels: kind/feature, size/xxl

#4324 fix bootstrap dn bug & commands' log output
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/bootstrap/bootstrap_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice_test.go
Labels: kind/bug, size/m

#4332 Mergify: mergify add PR number
  .github/mergify.yml
Labels: kind/test-ci

#4331 Add marshal of scope
  pkg/container/batch/batch.go
  pkg/container/batch/batch_test.go
  pkg/container/batch/types.go
  pkg/container/vector/vector.go
  pkg/pb/plan/plan.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/source.go
  pkg/sql/compile/types.go
  pkg/vm/process/process.go
  pkg/vm/vm.go
Labels: kind/feature, size/l

#4333 Mergify ignore darwin
  .github/mergify.yml
Labels: size/XS, kind/test-ci

#4327 logservice: stop hakeeper ticker on KillZombie command
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: kind/enhancement

#4337 updated CODEOWNERS
  CODEOWNERS
Labels: size/m, kind/test-ci

#4338 ci: updated CODEOWNERS
  CODEOWNERS
Labels: kind/test-ci

#4326 hakeeper: add replicaID field in KillZombie
  pkg/hakeeper/checkers/coordinator_test.go
  pkg/hakeeper/checkers/logservice/check.go
  pkg/hakeeper/checkers/logservice/parse.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/create_operator.go
Labels: kind/bug, size/s

#4344 fix usql
  pkg/frontend/variables.go
Labels: kind/bug, size/XS

#4341 chore: cgo debug build with -O0
  Makefile
  cgo/Makefile
  cgo/external/decNumber/Makefile
Labels: kind/enhancement, size/s

#4345 refactor(tae): rename hidden column to phyAddr
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/errors.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/model/model_test.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/refactor

#4353 Mergify: add more information for PR merge commit message
  .github/PULL_REQUEST_TEMPLATE.md
  .github/mergify.yml
Labels: kind/test-ci

#4355 Mergify: add check label do-not-merge/wip
  .github/mergify.yml
Labels: size/XS, kind/test-ci

#4350 add Minus operator and rename Anti operator
  pkg/sql/colexec/anti/anti.go
  pkg/sql/colexec/anti/anti_test.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/loopanti/loopanti.go
  pkg/sql/colexec/loopanti/loopanti_test.go
  pkg/sql/colexec/loopanti/types.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/minus/minus_test.go
  pkg/sql/colexec/minus/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/overload.go
  pkg/vm/types.go
Labels: kind/feature

#4352 txnstorage: various changes
  pkg/txn/storage/txn/any.go
  pkg/txn/storage/txn/batch.go
  pkg/txn/storage/txn/handler.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/storage.go
  pkg/txn/storage/txn/storage_test.go
  pkg/txn/storage/txn/types.go
  pkg/vm/engine/txn/operations.go
Labels: kind/enhancement, size/xl

#4358 logservice: minor tweak for TestHAKeeperCanBootstrapAndRepairShards
  pkg/logservice/service_commands_test.go
  pkg/logservice/store_hakeeper_check_test.go
Labels: size/m, kind/test-ci

#4366 fileservice: remove VfsFS
  go.mod
  pkg/fileservice/vfs_fs.go
  pkg/fileservice/vfs_fs_test.go
Labels: kind/enhancement, size/l

#4351 Add union/intersect/minus support in plan
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_query_rule.go
  proto/plan.proto
  test/cases/expression/case_when.sql
  test/cases/expression/cte.sql
  test/cases/subquery/subquery-with-any.sql
  test/cases/subquery/subquery-with-exists.sql
  test/cases/subquery/subquery-with-in.sql
Labels: kind/feature, size/xxl

#4365 fileservice: remove CacheFS; add memory cache to S3FS
  pkg/fileservice/cache_fs.go
  pkg/fileservice/cache_fs_test.go
  pkg/fileservice/config.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement

#4336 Update the server system settings
  docs/en/MatrixOne/Reference/System-Parameters/configuration-settings.md
Labels: kind/documentation, size/XS

#4375 rewrite explain/describe/desc table to show columns from table
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/object_name.go
Labels: kind/bug

#4373 Add bucket hashtable for group operator
  pkg/container/batch/batch.go
  pkg/container/batch/types.go
  pkg/container/hashtable/bucket.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/connector/connector_test.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/process/process.go
  test/cases/dtype/bool.test
  test/cases/function/func_substr.sql
  test/result/dtype/bool.result
  test/result/function/func_substr.result
Labels: kind/enhancement, size/xl

#4348 feat(tae): zonemap with fixed 64-byte serialized data
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/index/zonemap_test.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
Labels: kind/feature, size/l

#4385 remove insert issue tag and add some test cases=
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  test/cases/dml/insert/insert.test
  test/cases/dtype/bigint.test
  test/cases/dtype/decimal.test
  test/cases/dtype/double.test
  test/cases/dtype/float.test
  test/cases/dtype/int.test
  test/cases/dtype/smallint.test
  test/cases/dtype/tinyint.test
  test/cases/function/func_aggr_max.test
  test/cases/function/func_aggr_sum.test
  test/cases/function/func_if.test
  test/result/dml/insert/insert.result
  test/result/dtype/double.result
  test/result/dtype/tinyint.result
  test/result/function/func_aggr_sum.result
  test/result/function/func_if.result
Labels: size/l

#4384 Add fill anaylze information
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/process/analyze.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  pkg/vm/vm.go
Labels: kind/feature

#4376 Modify the method of package `hashmap` and related calls.
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/types.go
  pkg/sql/colexec/anti/anti.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/union/union.go
Labels: size/l, kind/refactor

#4367 logservice: switch to tan
  go.mod
  go.sum
  pkg/logservice/store.go
Labels: kind/feature, size/s

#4389 Update lz4 version
  pkg/compress/compress.go
  pkg/compress/compress_test.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/tae/dataio/segmentio/driver.go
Labels: kind/refactor, size/XS

#4369 fileservice: various changes
  pkg/fileservice/errors.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/l

#4378 add LogShard & DNShard minimal cluster configuration
  etc/bootstrap-example2/README.md
  etc/bootstrap-example2/dn-node-1.toml
  etc/bootstrap-example2/dn-node-2.toml
  etc/bootstrap-example2/log-node-1.toml
  etc/bootstrap-example2/log-node-2.toml
  etc/bootstrap-example2/log-node-3.toml
  etc/bootstrap-example2/log-node-4.toml
Labels: kind/enhancement

#4391 add an empty getExecTypeFromPlan for test
  pkg/sql/plan/build.go
  pkg/sql/plan/types.go
Labels: kind/feature, size/m

#4340 Implement interface `ClusterOperation` for test framework;
  pkg/tests/service/address.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/errors.go
  pkg/tests/service/logservice.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
Labels: priority/p1, kind/feature

#4394 Add tp and ap compile
  go.mod
  go.sum
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
Labels: kind/feature, kind/refactor

#4399 Support update column to default value
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_update.go
  proto/plan.proto
  test/cases/dml/update/update.test
  test/result/dml/update/update.result
Labels: size/l

#4397 add create/drop/alter account for the tenant
  cmd/generate-config/system_vars_def.toml
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/drop.go
Labels: kind/feature, size/xxl

#4392 txnstorage, txnengine: refinements
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/sql/compile/compile.go
  pkg/txn/storage/txn/atomic.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mvcc.go
  pkg/txn/storage/txn/mvcc_test.go
  pkg/txn/storage/txn/transaction.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/txn/database.go
  pkg/vm/engine/txn/engine.go
  pkg/vm/engine/txn/hakeeper.go
  pkg/vm/engine/txn/table.go
  pkg/vm/engine/txn/table_reader.go
  pkg/vm/engine/txn/test/engine_test.go
  pkg/vm/engine/txn/test/txn_sender.go
  pkg/vm/engine/txn/txn.go
  pkg/vm/engine/types.go
Labels: kind/enhancement, size/xl

#4401 fileservice: add value pinning in LRU
  pkg/fileservice/file_service.go
  pkg/fileservice/lru.go
  pkg/fileservice/pin.go
  pkg/fileservice/pin_test.go
Labels: kind/enhancement, size/l

#4359 ci: add workflow to build mo-service for each PR
  .github/workflows/ci.yml
Labels: kind/test-ci

#4405 update the grammar of the create/alter/drop user statement for the tenant
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
Labels: kind/feature, size/xxl

#4403 fileservice: cache refinements
  pkg/fileservice/caching_file_service.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/config.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/lru.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement

#4404 Support adding replica for initial dn shard;
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/errors.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/steps.go
Labels: kind/enhancement, priority/p1

#4387 Adding a fault injection tool.
  pkg/container/types/bytes.go
  pkg/sql/plan/function/builtin/multi/faultinj.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
  pkg/vm/process/process.go
  test/cases/util/fault.sql
  test/result/util/fault.result
Labels: kind/test-ci

#4408 add create/drop/grant/revoke role
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/grant.go
  pkg/sql/parsers/tree/revoke.go
  pkg/sql/parsers/tree/use.go
Labels: kind/enhancement, kind/feature, size/xxl

#4328 updateb docs:subqueries/update/delete/data_types/faq_theme/glossary/interval/install_standalone link/
  docs/cn/MatrixOne/FAQs/deployment-faqs.md
  docs/cn/MatrixOne/Get-Started/Playground.md
  docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/cn/MatrixOne/Overview/matrixone-introduction.md
  docs/cn/MatrixOne/Reference/Builtin-Functions/String/char-length.md
  docs/cn/MatrixOne/Reference/Data-Types/data-types.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/delete.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/case-when.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/show-tables.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/comparisons-using-subqueries.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/derived-tables.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-all.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-any-some.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-exists.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-in.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subquery.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/update.md
  docs/cn/MatrixOne/Test/mo-tester.md
  docs/cn/MatrixOne/glossary.md
  docs/en/MatrixOne/FAQs/deployment-faqs.md
  docs/en/MatrixOne/Get-Started/Playground.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Overview/matrixone-introduction.md
  docs/en/MatrixOne/Reference/Builtin-Functions/Datetime/to-date.md
  docs/en/MatrixOne/Reference/Builtin-Functions/String/char-length.md
  docs/en/MatrixOne/Reference/Data-Types/data-types.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/delete.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/case-when.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/show-tables.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/comparisons-using-subqueries.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/derived-tables.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-all.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-any-some.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-exists.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subqueries/subquery-with-in.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/subquery.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/update.md
  docs/en/MatrixOne/glossary.md
Labels: kind/documentation, size/XS

#4398 Minor changes. Use explicit uint64 in bitmap len.
  pkg/common/bitmap/bitmap.go
  pkg/common/bitmap/cbitmap.go
  pkg/common/bitmap/types.go
  pkg/container/types/decimal.go
  pkg/vectorize/add/dec.go
  pkg/vectorize/div/dec.go
  pkg/vectorize/mult/dec.go
  pkg/vectorize/sub/dec.go
Labels: kind/enhancement

#4410 fileservice: replace Pinned with RC
  pkg/fileservice/file_service.go
  pkg/fileservice/lru.go
  pkg/fileservice/rc.go
  pkg/fileservice/rc_test.go
Labels: kind/enhancement

#4417 Implement interface `ClusterState` for test framework;
  pkg/tests/service/dnservice.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
Labels: priority/p1, kind/feature, size/l

#4425 fix precedence of cast rule and modify some case
  pkg/sql/plan/function/type_check.go
  test/cases/function/func_cast.test
  test/cases/function/func_math_sinh.test
  test/cases/function/func_math_trig.test
  test/cases/function/func_string_oct.test
  test/cases/function/func_string_substring.test
  test/result/function/func_cast.result
  test/result/function/func_math_sinh.result
  test/result/function/func_math_trig.result
  test/result/function/func_string_oct.result
  test/result/function/func_string_substring.result
Labels: size/m

#4422 logservice: shuffle service address list before use
  cmd/mo-service/main.go
  pkg/logservice/client.go
  pkg/logservice/hakeeper_client.go
Labels: kind/bug

#4426 Add pipeline.proto
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/vm/types.go
  proto/pipeline.proto
Labels: kind/feature

#4421 cmd: resolve gossip seed addresses
  .gitignore
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
Labels: kind/feature, size/l

#4429 Fix the bug of ssb
  pkg/sql/colexec/mergeorder/order.go
Labels: kind/bug, size/XS

#4436 Fix issue #4430
  pkg/hakeeper/checkers/syshealth/check.go
  pkg/hakeeper/checkers/syshealth/check_test.go
Labels: kind/bug

#4431 fix onReplayAppendCmd
  pkg/vm/engine/tae/db/replay.go
Labels: kind/bug

#4435 logservice: fixed various HAKeeper client connectivity issues
  pkg/logservice/client.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_commands.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: kind/bug, size/s

#4371 CI: add PR UT coverage
  .github/workflows/ut_pr.yml
Labels: size/m, kind/test-ci

#4439 Update ut_pr.yml
  .github/workflows/ut_pr.yml
Labels: size/XS, kind/test-ci

#4438 Add union and minus
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/minus/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
Labels: kind/feature

#4420 Rework compare operator
  cgo/Makefile
  cgo/arith.c
  cgo/compare.c
  cgo/decimal.c
  cgo/mo.h
  cgo/mo_impl.h
  pkg/sql/plan/function/operator/compare.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/compare/compare.go
  pkg/vectorize/compare/equal_test.go
  pkg/vectorize/compare/greatEqual_test.go
  pkg/vectorize/compare/greatThan_test.go
  pkg/vectorize/compare/lessEqual_test.go
  pkg/vectorize/compare/lessThan_test.go
  pkg/vectorize/compare/notEqual_test.go
Labels: kind/enhancement, size/xxl

#4445 CI: add pull request additional unit test coverage
  .github/ut_pr.yml
Labels: kind/test-ci

#4447 Ut pr move
  .github/workflows/ut_pr.yml
Labels: size/XS, kind/test-ci

#4442 Update gen.sh
  proto/gen.sh
Labels: size/XS, kind/test-ci

#4440 prepare structures for the multi-tenant
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/export.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/pb/txn/txn.pb.go
  pkg/sql/parsers/tree/use.go
Labels: kind/enhancement, kind/feature

#4452 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, kind/test-ci

#4455 Upgrade goetty to support TLS
  go.mod
  go.sum
Labels: kind/feature, size/XS

#4449 logservice: use reverse proxy for service discovery
  pkg/common/moerr/error.go
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/shardinfo.go
  pkg/logservice/shardinfo_test.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/plan/plan.pb.go
  proto/logservice.proto
Labels: kind/feature, size/l

#4458 proto: fixed proto/gen.sh
  proto/gen.sh
Labels: kind/bug, size/XS

#4456 morpc: fix retry frequently
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: kind/bug, size/m

#4463 txn: make mem log lsn start with 1
  pkg/txn/service/service_testutil.go
  pkg/txn/storage/mem/kv_txn_storage.go
  pkg/txn/storage/mem/kv_txn_storage_test.go
  pkg/txn/storage/mem/log.go
  pkg/txn/storage/mem/log_test.go
Labels: kind/bug, size/m

#4454 Transaction timestamp2
  pkg/pb/txn/txn.pb.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/types/tsalloc.go
  pkg/vm/engine/tae/types/types.go
Labels: kind/feature

#4465 dnservice: fix start failed if any replica exists
  pkg/dnservice/store.go
  pkg/dnservice/store_metadata.go
  pkg/dnservice/store_test.go
Labels: kind/bug

#4460 logservice: reduced rpc marshal/unmarshal overheads
  pkg/logservice/client.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: size/m, kind/refactor

#4466 morpc: fix goroutine leak in test
  pkg/common/morpc/backend_test.go
Labels: kind/bug

#4457 Rework logical operation
  cgo/Makefile
  cgo/logic.c
  cgo/mo.c
  cgo/mo.h
  pkg/sql/plan/function/operator/logical.go
  pkg/sql/plan/function/operators.go
  pkg/testutil/util_make.go
  pkg/vectorize/logical/logical.go
  pkg/vectorize/logical/logical_test.go
  pkg/vectorize/sum/sum.go
Labels: kind/enhancement

#4470 fix mergeblocks
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/bug

#4467 Fix segmentio's log free bug
  pkg/vm/engine/tae/dataio/segmentio/log.go
Labels: kind/bug, size/XS

#4475 dnservice: close unstarted shard will be blocked
  pkg/dnservice/replica.go
  pkg/dnservice/replica_test.go
  pkg/dnservice/store.go
Labels: kind/bug, size/s

#4483 add cast decimal128 as int32 and fix func of floor
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/builtin/multi/floor.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/floor/floor.go
  test/cases/function/func_math_floor.test
Labels: size/L

#4461 Implement interface `ClusterWaitState` for test framework;
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/hakeeper/checkers/syshealth/check_test.go
  pkg/hakeeper/config.go
  pkg/hakeeper/config_test.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/tests/service/errors.go
  pkg/tests/service/logservice.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
  pkg/tests/service/utility.go
  pkg/tests/service/utility_test.go
Labels: priority/p1, kind/feature, size/XXL

#4481 Transaction timestamp2
  pkg/vm/engine/tae/dataio/segmentio/segment.go
  pkg/vm/engine/tae/txn/txnbase/fields.go
  pkg/vm/engine/tae/types/types.go
Labels: kind/bug, size/M

#4486 morpc: add checksum support
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
Labels: kind/feature, size/L

#4480 Labeler: Update labeler.yml to fix bug
  .github/workflows/labeler.yml
Labels: size/S, kind/test-ci

#4453 add testtxnengine package
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mvcc.go
  pkg/vm/engine/txn/database.go
  pkg/vm/engine/txn/engine.go
  pkg/vm/engine/txn/hack.go
  pkg/vm/engine/txn/operations_test.go
  pkg/vm/engine/txn/shard.go
  pkg/vm/engine/txn/table.go
  pkg/vm/engine/txn/table_reader.go
  pkg/vm/engine/txn/test/engine_test.go
  pkg/vm/engine/txn/test/env.go
  pkg/vm/engine/txn/test/execution.go
  pkg/vm/engine/txn/test/node.go
  pkg/vm/engine/txn/test/shard.go
  pkg/vm/engine/txn/test/tx.go
  pkg/vm/engine/txn/test/txn_sender.go
  pkg/vm/engine/txn/txn.go
Labels: kind/enhancement, size/XL

#4496 fileservice: add BlockMapper
  pkg/fileservice/block_mapper.go
  pkg/fileservice/block_mapper_test.go
  pkg/fileservice/utils.go
Labels: kind/enhancement, size/L

#4395 Delete TestIOSchedule1 case for ut
  pkg/vm/engine/tae/db/scheduler_test.go
Labels: size/M, kind/test-ci

#4478 Fix segmentio replay bug
  pkg/vm/engine/tae/dataio/segmentio/segment.go
Labels: kind/bug, size/S

#4498 txn: add context parameter to TxnStorage
  pkg/txn/service/service.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_cn_handler_test.go
  pkg/txn/service/service_dn_handler.go
  pkg/txn/service/service_recovery.go
  pkg/txn/storage/mem/kv_txn_storage.go
  pkg/txn/storage/mem/kv_txn_storage_test.go
  pkg/txn/storage/tae/storage.go
  pkg/txn/storage/txn/read.go
  pkg/txn/storage/txn/storage.go
  pkg/txn/storage/txn/storage_test.go
  pkg/txn/storage/txn/write.go
  pkg/txn/storage/types.go
Labels: kind/api-change, size/M

#4468 logservice: enabled TestGossipInSimulatedCluster
  go.mod
  go.sum
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
Labels: size/M, kind/test-ci

#4499 fileservice: use BlockMapper in LocalFS
  pkg/fileservice/block_mapper.go
  pkg/fileservice/block_mapper_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: kind/enhancement, size/L

#4501 Regenerate plan.pb
  pkg/container/types/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/anti/anti_test.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/loopanti/loopanti_test.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopsemi/join_test.go
  pkg/sql/colexec/loopsingle/join_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/limit_binder.go
  pkg/sql/plan/make.go
  pkg/sql/plan/make_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/txn/test/execution.go
  proto/plan.proto
Labels: kind/bug, size/XXL, kind/refactor

#4503 fileservice: add BlockMappable interafce
  pkg/fileservice/block_mapper.go
  pkg/fileservice/block_mapper_test.go
  pkg/fileservice/local_fs.go
Labels: kind/enhancement, size/M

#4497 upgrade goetty to v2 for mysql protocol
  go.mod
  go.sum
  pkg/frontend/codec.go
  pkg/frontend/iopackage_test.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/protocol_test.go
  pkg/frontend/routine_manager.go
  pkg/frontend/server.go
  pkg/frontend/session_test.go
  pkg/frontend/test/iosession_mock.go
Labels: kind/enhancement, size/L

#4459 Add view support
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/drop.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/txn/operations.go
  pkg/vm/engine/txn/test/execution.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/cases/view/view.test
  test/result/view/view.result
Labels: kind/feature, size/XXL

#4489 add doc about ssb-test on M1
  docs/cn/MatrixOne/FAQs/deployment-faqs.md
  docs/cn/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
  docs/en/MatrixOne/FAQs/deployment-faqs.md
  docs/en/MatrixOne/Get-Started/Tutorial/SSB-test-with-matrixone.md
Labels: kind/documentation, size/XXL

#4479 add mo-tester examples
  docs/cn/MatrixOne/Test/mo-tester.md
  docs/en/MatrixOne/Test/mo-tester.md
Labels: kind/documentation, size/M

#4476 fix catalog replay
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/db/replay_test.go
Labels: kind/bug, size/M

#4495 bugfix trace ut & data race
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/trace/ptrace.go
  pkg/util/trace/report_error.go
  pkg/util/trace/report_log.go
  pkg/util/trace/report_log_test.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/trace.go
  pkg/util/trace/trace_test.go
Labels: kind/bug, size/M

#4493 Agg sum with decimal
  cgo/decimal.c
  cgo/mo.h
  pkg/vectorize/sum/sum.go
Labels: kind/enhancement, size/M, do-not-merge/wip

#4515 modify error msg for func of agg
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/type_check.go
  test/cases/function/func_aggr_avg.test
  test/cases/function/func_aggr_sum.test
  test/result/function/func_aggr_avg.result
  test/result/function/func_aggr_sum.result
Labels: size/S

#4494 connect the context.Context in modules (frontend,metric and trace)
  cmd/db-server/main.go
  go.mod
  go.sum
  pkg/config/configuration.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/init_db.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/test/iosession_mock.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/util/batchpipe/batch_pipe.go
  pkg/util/batchpipe/batch_pipe_test.go
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_collector.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_exporter.go
  pkg/util/metric/metric_exporter_test.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/testutil_test.go
  pkg/util/trace/buffer_pipe_sql.go
  pkg/util/trace/buffer_pipe_sql_test.go
  pkg/util/trace/example/main.go
  pkg/util/trace/schema.go
  pkg/util/trace/schema_test.go
  pkg/util/trace/trace.go
  pkg/util/trace/trace_test.go
Labels: kind/enhancement, size/XL

#4511 fileservice: various changes
  pkg/fileservice/file_like.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/file_with_checksum_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/L

#4521 logservice: made tan's buffer size configurable
  go.mod
  go.sum
  pkg/logservice/config.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
Labels: size/S, kind/test-ci

#4485 implement intersect
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersect/intersect_test.go
  pkg/sql/colexec/intersect/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/overload.go
  pkg/vm/types.go
  test/cases/set/set_operator.test
  test/result/set/set_operator.result
Labels: kind/feature, size/L

#4507 small code refactor to local txn
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
Labels: size/M, kind/refactor, component/distributed tae

#4517 Fix prepare/execute stmt bug
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/deepcopy.go
  test/cases/prepare/prepare.test
  test/result/prepare/prepare.result
Labels: kind/bug, size/M

#4471 Add bit or/and/xor function
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/op_bit.go
  pkg/sql/plan/function/operator/op_bit_test.go
  pkg/sql/plan/function/operators.go
  test/cases/function/func_string_lpad_rpad.test
Labels: kind/feature, size/XL

#4531 morpc: fix unstable test
  pkg/common/morpc/backend_test.go
Labels: size/XS, kind/test-ci

#4525 fix char_length with param of varchar
  pkg/sql/plan/function/builtins.go
  test/cases/function/func_string_char_length.test
  test/cases/function/func_string_substring.test
Labels: size/S

#4490 improve moerr to support mo-error's unified format and reporting
  pkg/common/moerr/error.go
  pkg/common/moerr/error_test.go
  pkg/container/types/decimal.go
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/txn/client/operator.go
  pkg/util/errors/context.go
Labels: kind/feature, size/XL

#4534 fix some bugs
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/aggregate.go
  pkg/sql/plan/function/operator/cast.go
  test/cases/function/func_aggr_std.test
  test/cases/function/func_aggr_variance.test
  test/result/function/func_aggr_std.result
  test/result/function/func_aggr_variance.result
Labels: size/XXL

#4529 Agg sum with decimal
  cgo/decimal.c
  pkg/vectorize/sum/sum.go
Labels: kind/enhancement, size/S

#4524 CI: optimized unit test coverage and labeler
  .github/workflows/labeler.yml
  .github/workflows/ut_pr.yml
Labels: size/S, kind/test-ci

#4502 Add timezone support
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  pkg/container/types/datetime_test.go
  pkg/container/types/interval.go
  pkg/container/types/timestamp.go
  pkg/container/types/timestamp_test.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/builtin/multi/current_timestamp.go
  pkg/sql/plan/function/builtin/multi/current_timestamp_test.go
  pkg/sql/plan/function/builtin/multi/date_add.go
  pkg/sql/plan/function/builtin/multi/date_sub.go
  pkg/sql/plan/function/builtin/multi/from_unixtime.go
  pkg/sql/plan/function/builtin/multi/from_unixtime_test.go
  pkg/sql/plan/function/builtin/multi/rpad_test.go
  pkg/sql/plan/function/builtin/multi/unix_timestamp.go
  pkg/sql/plan/function/builtin/multi/unix_timestamp_test.go
  pkg/sql/plan/function/builtin/unary/timestamp.go
  pkg/sql/plan/function/builtin/unary/timestamp_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast_test.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/optimize.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_exporter.go
  pkg/util/metric/mtype_rawhist.go
  pkg/vectorize/date_add/date_add.go
  pkg/vectorize/date_add/date_add_test.go
  pkg/vectorize/date_sub/date_sub.go
  pkg/vectorize/date_sub/date_sub_test.go
  pkg/vectorize/fromunixtime/from_unixtime.go
  pkg/vectorize/fromunixtime/from_unixtime_test.go
  pkg/vectorize/get_timestamp/utc_timestamp.go
  pkg/vectorize/timestamp/timestamp.go
  pkg/vectorize/timestamp/timestamp_test.go
  pkg/vectorize/unixtimestamp/unixtimestamp.go
  pkg/vectorize/unixtimestamp/unixtimestamp_test.go
  pkg/vm/process/types.go
  test/cases/expression/temporal_interval.sql
  test/cases/function/func_datetime_unixtime.test
  test/cases/function/func_datetime_utc_timestamp.test
  test/result/expression/temporal_interval.result
  test/result/function/func_datetime_unixtime.result
  test/result/function/func_datetime_utc_timestamp.result
Labels: kind/bug, kind/feature, size/XL, kind/test-ci

#4450 fix minor unreachable code caused by t.Fatal
  pkg/vectorize/div/integer_div_test.go
Labels: size/XS, kind/test-ci

#4541 contributors readme action update
  README.md
Labels: size/XS

#4415 rewrite Load plan
  go.mod
  go.sum
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/query_builder.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/overload.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/types.go
  proto/plan.proto
Labels: kind/feature, size/XXL

#4547 support parameter expr in LIKE function
  pkg/sql/plan/base_binder.go
Labels: kind/bug, size/XS

#4549 vector: fix Vector.Read; batch: add EncodeBatch.Attrs
  pkg/container/batch/batch.go
  pkg/container/batch/types.go
  pkg/container/vector/vector.go
Labels: kind/bug, size/S

#4539 SpanContext add MarshalTo/Unmarshal support morpc (de)serialize
  pkg/util/trace/example/main.go
  pkg/util/trace/mo_trace.go
  pkg/util/trace/mo_trace_test.go
  pkg/util/trace/trace.go
Labels: size/M, kind/refactor

#4437 Add json type load&export
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/test/loadfile6
Labels: kind/feature, size/M

#4546 Agg sum with decimal
  cgo/mo.h
Labels: kind/enhancement, size/XS

#4544 fix intersect issue
  pkg/sql/colexec/intersect/intersect.go
Labels: kind/bug, size/M

#4543 support insert statement in prepare clause
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/visit_plan.go
  pkg/sql/plan/visit_plan_rule.go
  pkg/sql/plan/visit_query.go
  proto/plan.proto
  test/cases/prepare/prepare.test
  test/result/prepare/prepare.result
Labels: kind/feature, size/L

#4406 common: updated pkg/common/stopper to use MO's logutil
  go.mod
  go.sum
  pkg/common/stopper/stopper.go
  proto/gen.sh
Labels: size/M, kind/refactor

#4506 feat: update image go version to 1.19
  optools/images/Dockerfile
Labels: size/XS, kind/test-ci

#4552 [Plan] Deduplicate identical UNION parts
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  test/cases/subquery/subquery-with-any.sql
  test/cases/subquery/subquery-with-exists.sql
  test/cases/subquery/subquery-with-in.sql
  test/result/subquery/subquery-with-any.result
  test/result/subquery/subquery-with-exists.result
  test/result/subquery/subquery-with-in.result
Labels: kind/feature, size/S, kind/test-ci

#4551 fix replay logstore
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
Labels: kind/bug, size/M

#4555 Support noequi join condition in hash join
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/anyvalue/anyvalue_test.go
  pkg/sql/colexec/agg/approxcd/approxcd_test.go
  pkg/sql/colexec/agg/avg/avg.go
  pkg/sql/colexec/agg/avg/avg_test.go
  pkg/sql/colexec/agg/bit_and/bit_and_test.go
  pkg/sql/colexec/agg/bit_or/bit_or_test.go
  pkg/sql/colexec/agg/bit_xor/bit_xor_test.go
  pkg/sql/colexec/agg/count/count_test.go
  pkg/sql/colexec/agg/max/max_test.go
  pkg/sql/colexec/agg/min/min_test.go
  pkg/sql/colexec/agg/stddevpop/stddevpop_test.go
  pkg/sql/colexec/agg/sum/sum.go
  pkg/sql/colexec/agg/sum/sum_test.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/agg/variance/variance_test.go
  pkg/sql/colexec/aggregate/aggregate.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/semi/types.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/colexec/single/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vectorize/sum/sum.go
Labels: kind/enhancement, size/L

#4557 [Opt] Enable pushdown of non-equi SEMI/ANTI joins
  pkg/sql/plan/query_builder.go
Labels: kind/enhancement, size/S

#4535 Add the cn-service
  .gitignore
  Makefile
  cmd/db-server/main.go
  cmd/generate-config/config_template.go
  cmd/generate-config/config_template_test.go
  cmd/generate-config/main.go
  cmd/generate-config/system_vars_def.toml
  cmd/generate-config/test/def1.toml
  cmd/generate-config/test/def2.toml
  cmd/generate-config/test/system_vars_def.toml
  cmd/generate-config/test/t1.toml
  cmd/generate-config/test/t2.toml
  cmd/mo-service/config.go
  cmd/mo-service/main.go
  etc/cn-minimal-test.toml
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/config/configuration.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/system_vars_config.toml
  pkg/frontend/util.go
  pkg/util/export/batch_processor_test.go
  pkg/util/metric/config.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/trace/trace_test.go
  system_vars_config.toml
Labels: kind/enhancement, size/XXL

#4553 txnengine, txnstorage: various changes
  pkg/txn/storage/txn/batch.go
  pkg/txn/storage/txn/catalog.go
  pkg/txn/storage/txn/mem_handler.go
  pkg/txn/storage/txn/mem_handler_test.go
  pkg/txn/storage/txn/storage_test.go
  pkg/vm/engine/txn/database.go
  pkg/vm/engine/txn/engine.go
  pkg/vm/engine/txn/error.go
  pkg/vm/engine/txn/operations.go
  pkg/vm/engine/txn/test/bvt_test.go
  pkg/vm/engine/txn/test/engine_test.go
  pkg/vm/engine/txn/test/env.go
  pkg/vm/engine/txn/test/execution.go
  pkg/vm/engine/txn/test/node.go
  pkg/vm/engine/txn/test/tx.go
  pkg/vm/engine/txn/txn.go
Labels: kind/enhancement, size/L

#4556 fix: ut and metric collecttime
  pkg/util/batchpipe/batch_pipe_test.go
  pkg/util/metric/metric_collector.go
Labels: size/S, kind/test-ci

#4562 Fix the bug of union
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/avg/avg.go
  pkg/sql/colexec/group/group.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S
