Repository matrixorigin/matrixone, pull requests merged in 2022-10, with the labels that each got.

#5331 parsers: add syntax values statement
  pkg/frontend/authenticate.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/revoke.go
  pkg/sql/parsers/tree/values.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_values.go
  test/cases/table/values.test
  test/result/table/values.result
Labels: kind/feature, size/XXL

#5384 Txn pre commit write
  go.mod
  pkg/container/types/txnts.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/seqnum.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/stats.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/fields.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  pkg/vm/engine/tae/wal/wal_test.go
  pkg/vm/engine/tae/wal/walinfo.go
Labels: kind/feature, size/M

#5392 Code Refactoring
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/enhancement, size/M, kind/refactor

#5383 use mvcc node in mutindex
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/index/mtree.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/block_test.go
  pkg/vm/engine/tae/tables/indexwrapper/deletes.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/index_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  test/result/transaction/autocommit_isolation.result
  test/result/transaction/autocommit_isolation_1.result
  test/result/transaction/isolation.result
  test/result/transaction/isolation_1.result
Labels: kind/feature, size/XL

#5411 update multi account
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/revoke.go
  pkg/sql/parsers/tree/set.go
  test/cases/tenant/privilege/role2.sql
  test/cases/tenant/privilege/role3.sql
  test/cases/tenant/privilege/role4_special_roles.result
  test/cases/tenant/privilege/role4_special_roles.sql
  test/cases/tenant/privilege/role5_inherit.result
  test/cases/tenant/privilege/role5_inherit.sql
  test/cases/tenant/privilege/role6_createuser.result
  test/cases/tenant/privilege/role6_createuser.sql
  test/cases/tenant/role.test
  test/cases/tenant/tenant.test
  test/cases/tenant/user.test
  test/result/tenant/privilege/role.result
  test/result/tenant/privilege/role2.result
  test/result/tenant/privilege/role3.result
  test/result/tenant/role.result
  test/result/tenant/tenant.result
  test/result/tenant/user.result
Labels: kind/enhancement, kind/feature, size/XXL

#5409 logtailreader get all dirty blocks
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/operator.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/enhancement, size/S

#5416 fix `unnecessary type arguments infertype args` warning
  pkg/sql/plan/function/builtin/unary/time_of_day.go
Labels: size/S, kind/refactor

#5389 remvoe memEngine package
  CODEOWNERS
  pkg/testutil/testengine/testdata.go
  pkg/testutil/testengine/testengine.go
  pkg/vm/engine/memEngine/database.go
  pkg/vm/engine/memEngine/engine.go
  pkg/vm/engine/memEngine/kv/kv.go
  pkg/vm/engine/memEngine/kv/types.go
  pkg/vm/engine/memEngine/meta/meta.go
  pkg/vm/engine/memEngine/meta/types.go
  pkg/vm/engine/memEngine/reader.go
  pkg/vm/engine/memEngine/relation.go
  pkg/vm/engine/memEngine/types.go
Labels: kind/enhancement, size/L

#5423 Add free writer
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/tables/jobs/flushablk.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
Labels: kind/enhancement

#5424 memorystorage: use []byte to store string types
  pkg/txn/storage/memorystorage/account.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/txn/storage/memorystorage/catalog_handler.go
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/memtable/types.go
Labels: kind/bug, size/M

#5422 update GetColumnDataById
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/dataio/blockio/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/evictable/coldata.go
  pkg/vm/engine/tae/tables/evictable/deltadata.go
  pkg/vm/engine/tae/tables/evictable/deltameta.go
  pkg/vm/engine/tae/tables/evictable/utils.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
Labels: kind/feature, size/L

#5425 Txn pipeline
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/moengine/database.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/entry.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
Labels: kind/enhancement, size/L

#5431 Fix TestGCTable
  pkg/vm/engine/tae/db/gc_test.go
Labels: size/XS, kind/test-ci

#5427 memorystorage: add context param to handler methods
  pkg/txn/storage/memorystorage/catalog_handler.go
  pkg/txn/storage/memorystorage/catalog_handler_test.go
  pkg/txn/storage/memorystorage/handler.go
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/precommit.go
  pkg/txn/storage/memorystorage/read.go
  pkg/txn/storage/memorystorage/storage.go
  pkg/txn/storage/memorystorage/write.go
  pkg/vm/engine/memoryengine/operation_handler.go
  pkg/vm/engine/memoryengine/request.go
Labels: kind/enhancement, size/M

#5432 Add catalog owner
  CODEOWNERS
Labels: kind/enhancement, size/XS

#5420 use memory repeattly in load stream
  go.mod
  go.sum
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
Labels: kind/bug, size/S

#5436 morpc: fix codec panic
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
Labels: kind/bug, size/XS

#5317 add some util function for CN Workspace
  pkg/cnservice/distributed_tae.go
  pkg/container/vector/tools.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/builtin/multi/from_unixtime.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/make.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/engine_test.go
  pkg/vm/engine/disttae/meta.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  proto/plan.proto
Labels: kind/feature, size/XL

#5375 LogService: modify some log level from info to debug
  cmd/mo-service/main.go
  pkg/cnservice/server.go
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/logservice/client.go
  pkg/logservice/client_test.go
  pkg/logservice/errors.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/rsm.go
  pkg/logservice/service.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_commands.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/shardinfo.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_metadata.go
  pkg/logservice/store_metadata_test.go
  pkg/logservice/store_test.go
  pkg/logservice/utils.go
Labels: size/M, kind/refactor

#5437 endswith function scalar parameter result error
  pkg/sql/plan/function/builtin/binary/endswith.go
  pkg/sql/plan/function/builtin/binary/endswith_test.go
  test/cases/function/func_string_startsWith_endsWith.test
  test/result/function/func_string_startsWith_endsWith.result
Labels: kind/bug, size/S

#5373 fix final 0.5.1 docs
  README.md
  README_CN.md
  docs/cn/MatrixOne/Develop/connect-mo/client-connect-to-matrixone.md
  docs/cn/MatrixOne/Develop/connect-mo/java-connect-to-matrixone.md
  docs/cn/MatrixOne/Develop/connect-mo/python-connect-to-matrixone.md
  docs/cn/MatrixOne/Develop/export-data/0.6-general-method-export-data.md
  docs/cn/MatrixOne/Develop/export-data/0.6-use-docker-export-data.md
  docs/cn/MatrixOne/Develop/export-data/export-data.md
  docs/cn/MatrixOne/Develop/export-data/general-method-export-data.md
  docs/cn/MatrixOne/Develop/export-data/use-docker-export-data.md
  docs/cn/MatrixOne/Develop/import-data/import-data.md
  docs/cn/MatrixOne/Develop/import-data/use-docker-import-data.md
  docs/cn/MatrixOne/Develop/import-data/use-source-import-data.md
  docs/cn/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/cn/MatrixOne/Maintain/upgrade-standalone-matrixone.md
  docs/cn/MatrixOne/Migrate/migrate-from-mysql-to-matrixone.md
  docs/en/MatrixOne/Develop/export-data/0.6-general-method-export-data.md
  docs/en/MatrixOne/Develop/export-data/0.6-use-docker-export-data.md
  docs/en/MatrixOne/Develop/import-data/import-data.md
  docs/en/MatrixOne/Get-Started/connect-to-matrixone-server.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Maintain/upgrade-standalone-matrixone.md
  docs/en/MatrixOne/Migrate/migrate-from-mysql-to-matrixone.md
  docs/en/MatrixOne/Tutorial/TPCH-test-with-matrixone.md
  docs/en/MatrixOne/Tutorial/develop-java-crud-demo.md
Labels: kind/documentation, size/XS

#5412 add minus test
  test/cases/dml/select/minus.result
  test/cases/dml/select/minus.sql
Labels: size/L, kind/test-ci

#5380 Adjust the code to use mvcc data
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/cnservice/distributed_tae.go
  pkg/container/batch/batch.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/logservice/hakeeper_client.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/plan/function/builtin/multi/hash.go
  pkg/sql/plan/function/builtins.go
  pkg/txn/storage/memorystorage/batch.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/gob.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/pipeline/pipeline.go
Labels: kind/feature, size/L

#5443 fix prepare bug
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  test/cases/prepare/prepare.test
  test/result/prepare/prepare.result
Labels: kind/bug, size/S

#5452 txn: ignore txnclosed for rollback
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: kind/enhancement, size/S

#5365 Support keywords NULLS FIRST/LAST in ORDER BY clause
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/strcompare.go
  pkg/compare/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sort/sort.go
  pkg/sort/sort_test.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/order_test.go
  pkg/sql/colexec/mergeorder/types.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/order/order_test.go
  pkg/sql/colexec/order/types.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/top/types.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/select.go
  pkg/sql/plan/query_builder.go
  proto/plan.proto
Labels: kind/feature, size/XXL

#5445 fix logservicedriver
  pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
Labels: kind/bug, size/S

#5458 add compare to json type
  pkg/compare/compare.go
Labels: kind/bug, size/XS

#5433 Support left function
  pkg/sql/plan/function/builtin/binary/left.go
  pkg/sql/plan/function/builtin/binary/left_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/left/left.go
  pkg/vectorize/left/left_test.go
  test/cases/function/func_string_left.sql
  test/result/function/func_string_left.result
Labels: kind/feature, size/L

#5444 feature 4097 ：Support regular expressions funtion
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/multi/regular_instr.go
  pkg/sql/plan/function/builtin/multi/regular_like.go
  pkg/sql/plan/function/builtin/multi/regular_replace.go
  pkg/sql/plan/function/builtin/multi/regular_substr.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/reg_match.go
  pkg/sql/plan/function/operator/reg_match_test.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/regular/regular_instr.go
  pkg/vectorize/regular/regular_like.go
  pkg/vectorize/regular/regular_replace.go
  pkg/vectorize/regular/regular_substr.go
  pkg/vectorize/regular/regular_test.go
  test/cases/function/func_regular_instr.test
  test/cases/function/func_regular_like.test
  test/cases/function/func_regular_replace.test
  test/cases/function/func_regular_substr.test
  test/cases/operator/not_regexp_operator.test
  test/cases/operator/regexp_operator.test
  test/cases/operator/rlike_operator.test
  test/result/function/func_regular_instr.result
  test/result/function/func_regular_like.result
  test/result/function/func_regular_replace.result
  test/result/function/func_regular_substr.result
  test/result/operator/not_regexp_operator.result
  test/result/operator/regexp_operator.result
  test/result/operator/rlike_operator.result
Labels: kind/feature, size/XXL

#5454 Update fixed-point-types.md
  docs/cn/MatrixOne/Reference/Data-Types/fixed-point-types.md
Labels: kind/documentation, size/XS

#5446 Fix NullMask out of bounds bug
  pkg/vm/engine/tae/containers/vecimpl.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
Labels: kind/bug, size/XS

#5447 add a more message type check at remote run
  pkg/cnservice/server_heartbeat.go
  pkg/sql/compile/cnserviceDriver.go
Labels: kind/bug, size/S

#5463 let cmd field list returns empty
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/enhancement, size/M

#5461 fix the broken links by mkdocs serve
  docs/cn/MatrixOne/Contribution-Guide/How-to-Contribute/preparation.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/case.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators.md
  docs/cn/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/flow-control-functions-overview.md
  docs/cn/MatrixOne/Release-Notes/v0.5.1.md
  docs/cn/MatrixOne/Tutorial/TPCH-test-with-matrixone.md
  docs/cn/MatrixOne/Tutorial/develop-java-crud-demo.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/case.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/load-data.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators.md
  docs/en/MatrixOne/Reference/SQL-Reference/Data-Manipulation-Statements/operators/flow-control-functions/flow-control-functions-overview.md
  docs/en/MatrixOne/Release-Notes/v0.5.1.md
Labels: kind/documentation, size/XS

#5465 remove dummy code
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/handle.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/colupdate.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/updatechain.go
Labels: size/M, kind/refactor, component/standalone tae

#5440 fix bug: pushdown filter is incorrect in UNION/MINUS/INTERSECT node
  pkg/sql/plan/optimize.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  test/cases/union/union.result
  test/cases/union/union.sql
Labels: kind/bug, size/S

#5471 small code refactor
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
Labels: size/S, kind/refactor, component/standalone tae

#5478 Add delete logic
  pkg/catalog/types.go
  pkg/container/batch/batch.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/M

#5349 parser: support insert on duplicate key update
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/insert.go
  pkg/sql/plan/build_insert.go
  test/cases/dml/insert/insert.test
  test/result/dml/insert/insert.result
Labels: kind/feature, size/XXL, MatrixCamp

#5483 add prepare/execute log
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS

#5473 Txn pipeline
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/fields.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, kind/enhancement, size/L

#5488 cleanup xxx mpool
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/entry_test.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/stl/containers/stdvec.go
  pkg/vm/engine/tae/stl/containers/strvec.go
  pkg/vm/engine/tae/stl/containers/vector_test.go
  pkg/vm/engine/tae/tables/evictable/coldata.go
  pkg/vm/engine/tae/tables/evictable/utils.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/helper.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/testutils/helpers.go
Labels: size/M, kind/refactor, component/standalone tae

#5462 add dirty blocks observer and flush visitor
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/dirtywatcher.go
  pkg/vm/engine/tae/db/stats.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/tables/blocktasks.go
  pkg/vm/engine/tae/testutils/helpers.go
Labels: kind/enhancement, size/M

#5455 Refactor unnest to general table function
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/unnest/types.go
  pkg/sql/colexec/unnest/unnest.go
  pkg/sql/colexec/unnest/unnest_test.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/expr.go
  pkg/sql/parsers/tree/table_function.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/predicate_pushdown.go
  pkg/sql/plan/unnest.go
  pkg/sql/plan/utils.go
  proto/plan.proto
Labels: kind/feature, size/XL, kind/refactor

#5490 morpc: fix send payload missed setting timeout
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: kind/bug, size/S

#5426 Support system table of mysql
  pkg/cnservice/server.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/sysview/sysview.go
  test/cases/database/system_table.sql
  test/result/database/create_database.result
  test/result/database/drop_database.result
  test/result/database/new_database.result
  test/result/database/system_table.result
Labels: kind/feature, size/L

#5496 fix dedup
  pkg/vm/engine/tae/tables/block.go
Labels: kind/bug, size/XS

#5198 Loading data enhancement. jsonline
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/function/builtin/multi/external.go
  pkg/sql/plan/function/builtin/multi/external_test.go
  pkg/vectorize/external/external.go
  pkg/vectorize/external/external_test.go
  pkg/vectorize/external/types.go
  test/cases/load_data/load_data_jsonline.result
  test/cases/load_data/load_data_jsonline.test
  test/resources/load_data/jsonline_array.jl
  test/resources/load_data/jsonline_object.jl
Labels: kind/feature, size/XXL

#5498 Test for ORDER BY AND NULLS LAST/FIRST
  test/cases/dml/select/order_by_with_nulls.sql
  test/result/dml/select/order_by_with_nulls.result
Labels: size/L, kind/test-ci

#5497 Refactoring delete's partitioning strategy
  pkg/container/batch/batch.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/M

#5333 parsers: add do and declare statement
  pkg/frontend/authenticate.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/declare.go
  pkg/sql/parsers/tree/do.go
  pkg/sql/plan/build.go
  test/cases/util/declare.result
  test/cases/util/declare.sql
  test/cases/util/do.result
  test/cases/util/do.sql
Labels: kind/feature, size/XXL, MatrixCamp

#5509 add delete view
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: kind/enhancement, size/S

#5504 improve tls support
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine_manager.go
  pkg/frontend/test/client-cert2.pem
  pkg/frontend/test/client-key2.pem
  pkg/frontend/test/server-cert2.pem
  pkg/frontend/test/server-key2.pem
  pkg/frontend/test/system_vars_config.toml
Labels: size/M

#5485 export Metric data in one csv file each cycle
  cmd/mo-service/main.go
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/batchpipe/batch_pipe.go
  pkg/util/metric/m_sql.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_collector.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_test.go
  pkg/util/trace/buffer_pipe.go
  pkg/util/trace/mo_trace.go
  pkg/util/trace/report_error.go
  pkg/util/trace/report_log.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/schema.go
  pkg/util/trace/schema_test.go
  pkg/util/trace/table.go
  pkg/util/trace/table_test.go
  pkg/util/trace/trace.go
Labels: kind/enhancement, size/L

#5517 set prepare to CanBeExecutedInUncommittedTransaction
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#5493 Adding mo_memory_usage function.
  pkg/cnservice/distributed_tae.go
  pkg/common/mpool/mpool.go
  pkg/common/mpool/mpool_test.go
  pkg/dnservice/factory.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/plan/function/builtin/unary/momem.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vm/engine/tae/common/mpool.go
Labels: kind/enhancement, kind/feature, size/L

#5515 add some system variable and enable where
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/variables.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/default_binder.go
  pkg/sql/plan/types.go
  test/cases/dml/show/show.test
  test/result/dml/show/show.result
Labels: size/M

#5518 update get value
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/updates/delchain.go
Labels: kind/enhancement, size/S

#5506 Feature 3753：support datediff and timestampdiff function
  pkg/container/types/datetime.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/function/builtin/binary/datediff.go
  pkg/sql/plan/function/builtin/binary/datediff_test.go
  pkg/sql/plan/function/builtin/multi/timestampdiff.go
  pkg/sql/plan/function/builtin/multi/timestampdiff_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vectorize/datediff/datediff.go
  test/cases/function/func_datetime_datediff.test
  test/cases/function/func_datetime_timestampdiff.test
  test/result/function/func_datetime_datediff.result
  test/result/function/func_datetime_timestampdiff.result
Labels: kind/feature, size/XXL

#5514 Copy go slice's memory growth strategy to mpool
  pkg/common/mpool/mpool.go
  pkg/common/mpool/sizeclasses.go
Labels: kind/enhancement, size/M

#5522 Add default rowid
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/txn.go
Labels: size/XS

#5521 Add mpool dispose.
  pkg/container/vector/vector.go
  pkg/frontend/internal_executor.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
Labels: kind/bug, size/S

#5520 report err when primary key contain no exist col
  pkg/sql/plan/build_ddl.go
  test/cases/dml/insert/insert.test
  test/result/dml/insert/insert.result
Labels: size/S

#5479 Change delete plan
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/auto_incr_test.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/deepcopy.go
  pkg/txn/storage/memorystorage/frontend_test.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/tae/moengine/sys_relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/types.go
  proto/plan.proto
Labels: kind/feature, size/M

#5527 Implementing Truncate
  pkg/vm/engine/disttae/table.go
Labels: kind/feature, size/S

#5528 improve query log format, log in oneline
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
  pkg/logutil/api.go
  pkg/logutil/fields.go
  pkg/logutil/report.go
Labels: kind/enhancement, size/S

#5469 rollback compact if there're deletes
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/dataio/blockio/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/flushablk.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
Labels: kind/feature, size/M

#5531 Manage hashtable's memory with mpool
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: size/S, kind/refactor

#5535 Adding the processing of block list of table
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/M

#5502 record ExecPlan total RowsRead, BytesScan
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/util/trace/buffer_pipe_test.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/report_statement_test.go
  pkg/util/trace/schema.go
Labels: kind/enhancement, size/M

#5533 memoryengine bug fixes
  pkg/cnservice/memory_engine.go
  pkg/testutil/testengine/testengine.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/txn/storage/memorystorage/storage_txn_client_test.go
  pkg/vm/engine/memoryengine/database.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/memoryengine/id.go
  pkg/vm/engine/memoryengine/operation_handler.go
  pkg/vm/engine/memoryengine/request.go
  pkg/vm/engine/memoryengine/table_reader.go
Labels: kind/bug, size/M

#5529 fix a small bug
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/node.go
Labels: kind/bug, size/S, component/standalone tae

#5545 [#4694]Txn 2 pc mvcc
  pkg/txn/storage/tae/read.go
  pkg/txn/storage/tae/storage.go
  pkg/txn/storage/tae/write.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
Labels: kind/bug, kind/feature, size/XL

#5470 fix description bug about ssb-test and installation
  docs/cn/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/cn/MatrixOne/Tutorial/SSB-test-with-matrixone.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Tutorial/SSB-test-with-matrixone.md
Labels: kind/documentation, size/XS

#5541 Fix #3291 #3589: support minus (-) operator for DATE/DATETIME type
  pkg/container/types/datetime.go
  pkg/sql/plan/function/operator/arith.go
  pkg/sql/plan/function/operators.go
  pkg/vectorize/sub/dec.go
  pkg/vectorize/sub/sub_test.go
  test/cases/dtype/date.test
  test/cases/function/func_cast.test
  test/cases/function/func_datetime_date_add.test
  test/cases/function/func_datetime_utc_timestamp.test
  test/result/function/func_cast.result
Labels: kind/bug, size/M

#5546 Fix the bug of memorystorage(return the true defaultexpr)
  pkg/catalog/types.go
  pkg/container/batch/batch.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
Labels: kind/bug, size/S

#5567 fix memory leak and refactor some code
  pkg/vm/engine/tae/buffer/limiter.go
  pkg/vm/engine/tae/buffer/node.go
  pkg/vm/engine/tae/buffer/nodemgr.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/close.go
  pkg/vm/engine/tae/common/idalloc.go
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/engine/tae/common/refs.go
  pkg/vm/engine/tae/common/refs_test.go
  pkg/vm/engine/tae/common/seqnum.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/syncbase.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/sm/safeq.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tasks/worker/worker.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/bug, size/M, kind/refactor

#5540 FileService suppot delete multi paths
  pkg/fileservice/file_service.go
  pkg/fileservice/file_services.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/M

#5553 remove parse error
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/file.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
Labels: kind/bug, size/S

#5568 Fix the bug of insert/delete/update
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/update.go
  pkg/vm/engine/disttae/table.go
Labels: kind/bug, size/S

#5566 fix content format bug
  README.md
  docs/cn/MatrixOne/FAQs/deployment-faqs.md
  docs/en/MatrixOne/FAQs/deployment-faqs.md
  docs/en/MatrixOne/Get-Started/install-standalone-matrixone.md
  docs/en/MatrixOne/Tutorial/develop-java-crud-demo.md
Labels: kind/documentation, size/XS

#5574 refactor mergeblocks
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
Labels: size/S, kind/refactor

#5569 add util function for CN Workspace
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/feature, size/M

#5572 fix logservicedriver replay
  pkg/vm/engine/tae/logstore/driver/entry/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
Labels: kind/bug, kind/feature, size/M

#5576 Fix prepare bug
  pkg/frontend/mysql_protocol.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  test/cases/prepare/prepare.test
  test/result/prepare/prepare.result
Labels: kind/bug, size/M

#5555 fix # 5547 ：fix code for invalid regexp pattern
  pkg/vectorize/regular/regular_instr.go
  pkg/vectorize/regular/regular_replace.go
  pkg/vectorize/regular/regular_substr.go
  test/cases/function/func_regular_instr.test
  test/cases/function/func_regular_like.test
  test/cases/function/func_regular_replace.test
  test/cases/function/func_regular_substr.test
  test/result/function/func_regular_instr.result
  test/result/function/func_regular_like.result
  test/result/function/func_regular_replace.result
  test/result/function/func_regular_substr.result
Labels: kind/bug, size/M

#5586 test for left function
  test/cases/function/left_function.sql
  test/result/function/left_function.result
Labels: size/M

#5584 add uuid type and uuid func
  test/cases/dtype/uuid_type_and_uuid_func.result
  test/cases/dtype/uuid_type_and_uuid_func.sql
Labels: size/M, kind/test-ci

#5589 memtable: use separate b-trees for rows, indexes, writes
  pkg/txn/storage/memorystorage/memtable/physical_iter.go
  pkg/txn/storage/memorystorage/memtable/table.go
  pkg/txn/storage/memorystorage/memtable/table_iter.go
Labels: kind/enhancement, size/M

#5536 fix #5397：index out of range [0] with length 0 during bin()
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function.go
  test/cases/function/func_args_length.text
  test/result/function/func_args_length.result
Labels: kind/bug, size/M

#5573 modify Makefile with GOLDFALGS params to show version info
  Makefile
Labels: kind/enhancement, size/XS

#5593 refactor dirty block collector
  pkg/vm/engine/tae/common/tree.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/forest.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/tasks/worker/heartbeater.go
Labels: size/M, kind/refactor

#5587 update multi account
  .gitignore
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/util/sysview/sysview.go
  test/cases/tenant/privilege/create_account_case_insensitive.result
  test/cases/tenant/privilege/create_account_case_insensitive.sql
  test/cases/tenant/privilege/create_account_case_sensitive.result
  test/cases/tenant/privilege/create_account_case_sensitive.sql
  test/cases/tenant/privilege/create_account_wrong_account_name.result
  test/cases/tenant/privilege/create_account_wrong_account_name.sql
  test/cases/tenant/privilege/create_role_case_insensitive.result
  test/cases/tenant/privilege/create_role_case_insensitive.sql
  test/cases/tenant/privilege/create_role_case_sensitive.result
  test/cases/tenant/privilege/create_role_case_sensitive.sql
  test/cases/tenant/privilege/create_user_case_insensitive.result
  test/cases/tenant/privilege/create_user_case_insensitive.sql
  test/cases/tenant/privilege/create_user_case_sensitive.result
  test/cases/tenant/privilege/create_user_case_sensitive.sql
  test/cases/tenant/privilege/create_user_default_role.result
  test/cases/tenant/privilege/create_user_default_role.sql
  test/cases/tenant/privilege/operate_catalog.result
  test/cases/tenant/privilege/operate_catalog.sql
  test/cases/tenant/privilege/role4_special_roles.sql
  test/cases/tenant/privilege/role5_inherit.result
  test/cases/tenant/privilege/role5_inherit.sql
  test/cases/tenant/privilege/role7_special_roles_accountadmin.result
  test/cases/tenant/privilege/role7_special_roles_accountadmin.sql
Labels: kind/enhancement, kind/feature, size/XXL

#5477 support unique index
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/builtin/multi/serial.go
  pkg/sql/plan/types.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/index_util.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/cases/dml/delete/delete.test
  test/cases/dml/insert/insert.test
  test/cases/dml/update/update.test
  test/cases/table/drop_table.test
  test/result/dml/delete/delete.result
  test/result/dml/insert/insert.result
  test/result/dml/update/update.result
  test/result/table/drop_table.result
Labels: size/XL

#5595 add prepare transaction test
  test/cases/prepare/prepare_transaction.result
  test/cases/prepare/prepare_transaction.sql
Labels: size/M, kind/test-ci

#5594 add blockread to apply deletes
  pkg/vm/engine/tae/dataio/blockio/read.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/model/preparer.go
Labels: kind/feature, size/M

#5592 memtable: replace physical iter with diff iter
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/memtable/diff_iter.go
  pkg/txn/storage/memorystorage/memtable/physical_iter.go
  pkg/txn/storage/memorystorage/memtable/table.go
Labels: kind/enhancement, size/M

#5449 add prefix to hide column avoiding conflict
  pkg/catalog/types.go
  pkg/common/moerr/error.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/util/composite_primary_key_util.go
  pkg/sql/util/index_util.go
  pkg/txn/storage/memorystorage/mem_handler.go
  test/cases/view/view-subquery-with-in.result
  test/result/dml/insert/insert.result
  test/result/dml/update/update.result
  test/result/function/func_datetime_dayofyear.result
  test/result/function/func_datetime_month.result
  test/result/function/func_datetime_weekday.result
  test/result/function/func_datetime_year.result
  test/result/function/func_math_floor.result
  test/result/function/func_math_pi.result
Labels: kind/bug, size/S

#5603 replace lni/dragonboat with matrixorigin/dragonboat.
  go.mod
  go.sum
Labels: kind/refactor, size/XS

#5605 contributors readme action update
  README.md
Labels: size/XS

#5585 Modify cn and memorystorge to be compatible with tae's behavior
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/plan/build_show.go
  pkg/txn/storage/memorystorage/catalog.go
  pkg/txn/storage/memorystorage/precommit.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: size/L, kind/refactor

#5570 fix some json bugs
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/path_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/container/types/json_test.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/operators.go
  test/cases/dtype/json.test
  test/cases/function/func_json_extract.test
  test/result/dtype/json.result
  test/result/function/func_json_extract.result
Labels: kind/bug, size/M

#5606 fix memtable check type bug
  pkg/txn/storage/memorystorage/memtable/types.go
Labels: kind/bug, size/XS

#5591 check if prepare stmt can run in uncommit txn
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/pb/plan/plan.pb.go
  proto/plan.proto
  test/cases/prepare/prepare.test
  test/cases/prepare/prepare_transaction.result
  test/result/prepare/prepare.result
Labels: kind/bug, size/M

#5609 memorystorage: refactor to make disttae not depend on memorystorage
  pkg/txn/storage/memorystorage/catalog_handler.go
  pkg/txn/storage/memorystorage/data.go
  pkg/txn/storage/memorystorage/log_tail.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/memtable/batch_utils.go
  pkg/txn/storage/memorystorage/memtable/vector.go
  pkg/txn/storage/memorystorage/memtable/vector_utils.go
  pkg/vm/engine/disttae/partition.go
Labels: kind/enhancement, size/M

#5599 refactor metric data store path as {account}/log/yyyy/mm/dd/metric/*.csv
  pkg/config/configuration.go
  pkg/util/export/fs_writer.go
  pkg/util/export/fs_writer_test.go
  pkg/util/export/type.go
  pkg/util/export/type_test.go
  pkg/util/metric/config.go
  pkg/util/metric/m_process.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_collector.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_test.go
  pkg/util/trace/buffer_pipe.go
  pkg/util/trace/buffer_pipe_test.go
  pkg/util/trace/example/main.go
  pkg/util/trace/schema.go
  pkg/util/trace/table.go
  pkg/util/trace/table_test.go
Labels: kind/feature, size/M

#5607 fix mce race
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#5602 always use row id to delete row
  pkg/sql/colexec/update/update.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_update.go
Labels: kind/feature, size/M

#5613 fix some tests
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, size/S

#5610 etc: unify naming convention of launch profiles
  etc/launch-dist-tae/launch.toml
  etc/launch-mem-CN-mem-DN/cn.toml
  etc/launch-mem-CN-mem-DN/cn2.toml
  etc/launch-mem-CN-mem-DN/dn.toml
  etc/launch-mem-CN-mem-DN/launch.toml
  etc/launch-mem-CN-mem-DN/log.toml
  etc/launch-mem-engine/launch.toml
  etc/launch-tae-CN-mem-DN/cn.toml
  etc/launch-tae-CN-mem-DN/dn.toml
  etc/launch-tae-CN-mem-DN/launch.toml
  etc/launch-tae-CN-mem-DN/log.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/launch.toml
  etc/launch-tae-CN-tae-DN/log.toml
Labels: kind/enhancement, size/M

#5601 use logservice in bvt
  .github/workflows/ci.yml
  etc/launch-tae-logservice/cn1.toml
  etc/launch-tae-logservice/dn1.toml
  etc/launch-tae-logservice/launch.toml
  etc/launch-tae-logservice/log1.toml
  etc/launch-tae-logservice/log2.toml
  etc/launch-tae-logservice/log3.toml
  pkg/cnservice/server.go
  pkg/cnservice/tae.go
  pkg/cnservice/types.go
  pkg/config/configuration.go
  pkg/dnservice/factory.go
  pkg/logservice/client.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/wal_test.go
Labels: size/M, kind/test-ci

#5614 fix drop table with auto_incr col bug with unique key in table
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/XS

#5615 Skip empty batch
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/tools.go
Labels: kind/enhancement, size/S

#5628 Reopen the UT for 2PC ,since PR [#5586] closed it .
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: kind/bug, kind/feature, size/M

#5624 add blk meta schema
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/types.go
Labels: kind/feature, size/M

#5611 add cluster info logs
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/logservice/check.go
Labels: kind/feature, size/S

#5579 support some feature
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  test/cases/dml/update/update.test
  test/cases/prepare/prepare_transaction.result
  test/cases/set/set_operator.test
  test/cases/transaction/autocommit_1.sql
  test/result/dml/update/update.result
  test/result/prepare/prepare.result
  test/result/prepare/prepare_all.result
  test/result/set/set_operator.result
  test/result/transaction/autocommit.result
  test/result/transaction/autocommit_1.result
  test/result/transaction/autocommit_atomicity.result
  test/result/transaction/isolation.result
  test/result/transaction/isolation_1.result
Labels: size/M

#5643 fix race
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/util.go
Labels: kind/bug, kind/enhancement, size/XL

#5641 updates for gc | transaction | compaction
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/tree.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/checkpointop.go
  pkg/vm/engine/tae/db/gc_test.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/iface/handle/database.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/enhancement, size/XL, kind/refactor, component/standalone tae, kind/test-ci

#5644 Update ci.yml
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#5645 Ci upgrade
  .github/mergify.yml
  .github/workflows/ci.yml
Labels: size/S, kind/test-ci

#5647 txn: fix unstable txn test
  pkg/txn/service/service.go
Labels: size/XS, kind/test-ci

#5617 CN starts after HAKeeper is running
  cmd/mo-service/launch.go
  cmd/mo-service/main.go
  pkg/frontend/routine_manager.go
  pkg/hakeeper/rsm.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/service.go
  pkg/pb/logservice/logservice.pb.go
  pkg/tests/service/service.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  proto/logservice.proto
Labels: kind/bug, size/M

#5648 1. remove unnecessary upload data
  .github/mergify.yml
  .github/workflows/ci.yml
Labels: size/S, kind/test-ci

#5649 Change panic to error log in truncation worker.
  pkg/logservice/store.go
Labels: kind/bug, size/XS

#5652 set locale before bvt start in bvt-linux-x86
  .github/workflows/ci.yml
Labels: size/XS, kind/test-ci

#5650 add special user for cluster initialization
  pkg/frontend/authenticate.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
Labels: kind/enhancement, size/S

#5489 add every insert batch commit in load stream
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/vm/process/types.go
  proto/plan.proto
Labels: kind/bug, size/M

#5635 Meta loc add object size
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/dataio/blockio/info.go
  pkg/vm/engine/tae/dataio/blockio/read.go
  pkg/vm/engine/tae/dataio/blockio/types.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/tables/evictable/deltameta.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/enhancement, kind/feature, size/M

#5597 Objectio supports mpool
  pkg/objectio/column.go
  pkg/objectio/reader.go
  pkg/objectio/type.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/dataio/blockio/block_test.go
  pkg/vm/engine/tae/dataio/blockio/colblk.go
  pkg/vm/engine/tae/dataio/blockio/read.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/tables/evictable/bf.go
  pkg/vm/engine/tae/tables/evictable/coldata.go
  pkg/vm/engine/tae/tables/evictable/colmeta.go
  pkg/vm/engine/tae/tables/evictable/deltadata.go
Labels: kind/enhancement, kind/feature, size/M

#5627 disttae: fix process init
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/tae.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#5657 BVT uses single logservice to reduce test time.
  etc/launch-tae-logservice/cn1.toml
  etc/launch-tae-logservice/dn1.toml
  etc/launch-tae-logservice/log1.toml
  etc/launch-tae-logservice/log2.toml
  etc/launch-tae-logservice/log3.toml
Labels: size/S, bvt, kind/test-ci

#5588 tests: Add txn test framework
  CODEOWNERS
  pkg/dnservice/factory.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/txn/cluster.go
  pkg/tests/txn/cluster_basic_test.go
  pkg/tests/txn/doc.go
  pkg/tests/txn/kv_client.go
  pkg/tests/txn/sql_client.go
  pkg/tests/txn/types.go
  pkg/txn/storage/mem/kv_txn_storage.go
Labels: size/L, kind/test-ci

#5655 add replay txn, use txn in replay
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/common/tree.go
  pkg/vm/engine/tae/common/tree_test.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/iface/txnif/cmd.go
  pkg/vm/engine/tae/iface/txnif/memo.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/tables/txnentries/compactblkcmd.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/replaytxn.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: size/XL, kind/refactor

#5324 Add steps for go configuretion of document
  docs/cn/MatrixOne/parser_camp_event.md
Labels: size/XS

#5525 fix bug:count on json cols and modify errmsg on json insert
  pkg/frontend/load.go
  pkg/sql/colexec/agg/new.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_util.go
  test/cases/dtype/json.test
  test/result/dtype/json.result
Labels: kind/bug, size/S

#5620 Rollback load to no vectorization
  pkg/sql/colexec/external/external.go
  pkg/sql/plan/function/builtin/multi/external.go
  pkg/sql/plan/function/builtin/multi/external_test.go
  pkg/vectorize/external/external.go
  pkg/vectorize/external/external_test.go
  pkg/vectorize/external/types.go
Labels: size/XL

#5621 fix fail to create index table
  pkg/sql/compile/ddl.go
Labels: size/S

#5575 Fix 5286：fix date_sub when date out of range
  pkg/container/types/datetime.go
  test/cases/function/func_datetime_date_add.test
  test/result/function/func_datetime_date_add.result
Labels: kind/bug, size/XS

#5526 improve deletion and update end status
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/update/update.go
Labels: kind/enhancement, size/S

#5495 Add generate_series table function.
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/generate_series/generate_series.go
  pkg/sql/colexec/generate_series/generate_series_test.go
  pkg/sql/colexec/generate_series/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/query_builder.go
  pkg/vm/overload.go
  pkg/vm/types.go
  proto/pipeline.proto
  test/cases/function/table_func_generate_series.test
  test/result/function/table_func_generate_series.result
Labels: kind/feature, size/XXL

#5659 add metric sql_transaction_errors, sql_transaction_total
  etc/launch-tae-logservice/cn1.toml
  etc/launch-tae-logservice/dn1.toml
  etc/launch-tae-logservice/log1.toml
  etc/launch-tae-logservice/log2.toml
  etc/launch-tae-logservice/log3.toml
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_sql.go
Labels: kind/enhancement, size/M

#5664 fix: sync block meta list
  pkg/catalog/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/M

#5665 data block struct code refactor
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/containers/batch_test.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/dataio/blockio/block.go
  pkg/vm/engine/tae/dataio/blockio/block_test.go
  pkg/vm/engine/tae/dataio/blockio/colblk.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/dataio/blockio/segment.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/data/segment.go
  pkg/vm/engine/tae/iface/file/block.go
  pkg/vm/engine/tae/iface/file/segment.go
  pkg/vm/engine/tae/iface/file/types.go
  pkg/vm/engine/tae/iface/tfs/types.go
  pkg/vm/engine/tae/tables/block.go
  pkg/vm/engine/tae/tables/evictable/bf.go
  pkg/vm/engine/tae/tables/evictable/coldata.go
  pkg/vm/engine/tae/tables/evictable/colmeta.go
  pkg/vm/engine/tae/tables/evictable/deltadata.go
  pkg/vm/engine/tae/tables/evictable/deltameta.go
  pkg/vm/engine/tae/tables/factory.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/flushablk.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tables/table.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, size/XL

#5639 use new s3 block reader&new block info struct
  pkg/vm/engine/disttae/meta.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/feature, size/M

#5632 Fix the bug of using wrong txn operator
  pkg/sql/compile/compile.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#5685 Reorder schema with column number
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/XS

#5693 implement String for batch
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vecbase.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vecview.go
  pkg/vm/engine/tae/containers/vecwindow.go
Labels: kind/enhancement, size/S

#5666 replay code refactor to process log entry as a normal transaction
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/replay.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/db/gcop.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/db/stats.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/store/partialckp.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/node.go
  pkg/vm/engine/tae/tables/replay.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/fields.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/replaytxn.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: kind/bug, kind/enhancement, size/XL, kind/refactor
