Repository matrixorigin/matrixone, pull requests merged in 2023-01, with the labels that each got.

#7336 lockservice: add lockservice api
  CODEOWNERS
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/lockservice/options.go
  pkg/lockservice/types.go
Labels: kind/feature, size/M

#7395 refactor merge policy
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/enhancement, size/M, kind/refactor

#7412 Add marker to make logtail sync only once
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/S

#7390 function_format cases
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: size/M

#7405 function_sleep cases
  test/distributed/cases/function/function_sleep.result
  test/distributed/cases/function/function_sleep.sql
Labels: size/M

#7400 fix bit aggregation function bug
  pkg/sql/colexec/agg/bit_and.go
  pkg/sql/colexec/agg/bit_or.go
  pkg/sql/colexec/agg/bit_xor.go
  test/distributed/cases/function/func_aggr_bitwise.result
  test/distributed/cases/function/func_aggr_bitwise.test
Labels: kind/bug, size/S

#7414 Fix GC UT restart case
  pkg/vm/engine/tae/db/base_test.go
Labels: kind/bug, size/XS, kind/test-ci

#7409 [BUG] Fix mo_catalog created time error
  pkg/container/types/date.go
  pkg/vm/engine/disttae/tools.go
Labels: kind/bug, size/XS

#7421 query explain add golbal stats
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
Labels: kind/feature, size/M

#7416 etc: add cache configs
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
Labels: kind/enhancement, size/S

#7422 fileservice: refactor S3 GetForETL
  pkg/fileservice/get.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/M

#7406 lockservice: add btree based lock store
  pkg/lockservice/btree_storage.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/types.go
Labels: kind/feature, size/M

#7428 Sync logtail updates from relation to ranges function (dn will push l…
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/refactor

#7424 support access observability data collecting from outside.
  go.mod
  go.sum
  pkg/util/export/batch_processor_test.go
  pkg/util/export/observability/logs/log.go
  pkg/util/export/observability/metrics/metric.go
  pkg/util/export/observability/schema.go
  pkg/util/export/observability/trace/span.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/export/table/type.go
  pkg/util/trace/buffer_pipe.go
Labels: kind/feature, size/L

#7403 Add merge GC metadata
  pkg/vm/engine/tae/dataio/blockio/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/gc/table.go
Labels: kind/enhancement, kind/feature, size/M

#7339 refactor the function evaluate framework.
  pkg/container/types/time.go
  pkg/container/types/time_test.go
  pkg/container/vector/functionTools.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/builtin/binary/typecast.go
  pkg/sql/plan/function/castBackup
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/operator/cast.go
  pkg/sql/plan/function/operator/cast2.go
  pkg/sql/plan/function/operator/cast2_test.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/utils.go
  pkg/testutil/util_function.go
  pkg/vectorize/time/time.go
  test/distributed/cases/dtype/text_1.result
  test/distributed/cases/dtype/text_blob.result
  test/distributed/cases/function/func_cast.result
Labels: kind/feature, size/XXL

#7417 Fix columns resp after updating constraints
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/tablebase.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#7427 Supplement bit aggregate function feature
  pkg/sql/colexec/agg/bit_and.go
  pkg/sql/colexec/agg/bit_or.go
  pkg/sql/colexec/agg/bit_xor.go
Labels: kind/bug, size/S

#7430 Update GC config
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
Labels: kind/enhancement, size/XS

#7426 fix show tables bug
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/S

#7425 Add some interface for tableDef refactor
  pkg/frontend/session.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/types.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/catalog_test.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#7437 fix uts
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/bug, size/XS

#7439 removed a duplicate function structure
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/function/function.go
Labels: size/XS

#7441 Ignore errors when prefetching metadata
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/S

#7446 lockservice: add deadlock detector
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
Labels: kind/feature, size/M

#7438 all: rename S3 file service to Shared
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  etc/bootstrap-example2/dn-node-1.toml
  etc/bootstrap-example2/dn-node-2.toml
  etc/cn-non-dist-memory.toml
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-dist-tae.toml
  etc/cn-standalone-test.toml
  etc/dn-minimal-s3-test.toml
  etc/dn-minimal-test.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-logservice/cn.toml
  etc/launch-tae-logservice/dn.toml
  etc/launch-tae-logservice/log.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
  etc/launch/cn1.toml
  etc/launch/dn1.toml
  etc/launch/log1.toml
  etc/launch/log2.toml
  etc/launch/log3.toml
  etc/log-minimal-test.toml
  pkg/cnservice/distributed_tae.go
  pkg/defines/const.go
  pkg/dnservice/factory.go
  pkg/dnservice/store_test.go
  pkg/logutil/adapt_s3.go
  pkg/tests/service/fileservice.go
  pkg/testutil/util_new.go
Labels: kind/enhancement, size/S

#7418 add force checkpoint
  pkg/pb/ctl/ctl.pb.go
  pkg/sql/plan/function/builtin/ctl/cmd_checkpoint.go
  pkg/sql/plan/function/builtin/ctl/types.go
  pkg/txn/storage/tae/read.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/tae/common/retry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  proto/ctl.proto
  test/distributed/cases/dml/update/checkpoint.result
  test/distributed/cases/dml/update/checkpoint.test
Labels: size/M

#7327 create/drop function logic
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/function.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/function/udf.result
  test/distributed/cases/function/udf.sql
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/XXL

#7444 function_replace cases
  test/distributed/cases/function/func_string_replace.result
  test/distributed/cases/function/func_string_replace.test
Labels: size/L

#7452 Fix warnings.
  pkg/sql/plan/function/operator/cast2.go
Labels: size/M

#7435 Dispatch cross cn
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
  proto/pipeline.proto
Labels: kind/feature, size/M

#7398 Make some changes in format function.
  pkg/vectorize/format/format.go
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: kind/bug, size/S

#7450 fix README page 404 link
  README.md
  README_CN.md
Labels: kind/documentation, size/XS

#7456 fileservice: fix ReaderForWrite
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/M

#7463 improve the GetValue performance of FunctionParameterWrapper
  pkg/container/vector/functionTools.go
  pkg/sql/plan/function/operator/cast2.go
Labels: kind/enhancement, size/XL

#7469 bugfix: panic issue if simdcsv.Read return nil buffer and err is nil
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
  pkg/util/export/table/table.go
Labels: kind/bug, size/M

#7459 function_format cases
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: size/M

#7467 [Feature] Support show function status stmt
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
Labels: kind/feature, size/S

#7415 support to save query result
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/common/moerr/error.go
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/output/types.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/function/builtin/unary/infomation_function.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/result_scan.go
  pkg/sql/plan/types.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/process/types.go
  proto/plan.proto
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: size/L

#7399 fix create unique index panic
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/util/index_util.go
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
Labels: kind/bug, size/M

#7483 bugfix: ut discover bug while failed to open file.
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
Labels: kind/bug, size/M

#7484 statemetn_info record stats json
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/util/export/table/table.go
  pkg/util/trace/buffer_pipe_test.go
  pkg/util/trace/report_statement.go
  pkg/util/trace/report_statement_test.go
  pkg/util/trace/schema.go
Labels: kind/feature, size/M

#7480 fix IOSession.Ref in frontend
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
Labels: kind/bug, size/S

#7485 support load from s3 with role_arn and external_id
  pkg/fileservice/get.go
  pkg/sql/colexec/external/external.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/S

#7496 fileservice: do not check IOEntry.Size when reading to the end of file in LocalFS/LocalETLFS.Read
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/S

#7445 lockservice: add waiter implementation
  pkg/lockservice/wait_test.go
  pkg/lockservice/waiter.go
  pkg/util/ring/ring.go
  pkg/util/ring/ring_test.go
Labels: kind/feature, size/L

#7451 auto format with autocorrect --fix
  README_CN.md
  docs/rfcs/20220503_tae_design.md
  pkg/sql/colexec/table_function/README.md
  pkg/util/export/merge.go
  pkg/util/metric/dashboard/grafana8.4_mo_overview.json
Labels: kind/documentation, size/S

#7494 Bugfix trace cause mo tpcc hang
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/export/merge_test.go
  pkg/util/metric/metric_collector.go
  pkg/util/trace/buffer_pipe.go
  pkg/util/trace/buffer_pipe_test.go
Labels: kind/bug, size/M

#7497 add modump for the query result
  go.mod
  pkg/config/configuration.go
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/mo_dump.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/XXL

#7472 fileservice: check context done in methods
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/io_entry_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/mutable_file_service_test.go
  pkg/fileservice/replaceable_file_service_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/frontend/query_result_test.go
  pkg/sql/colexec/external/external_test.go
  pkg/util/export/merge_test.go
Labels: kind/enhancement, size/M

#7447 Integrate `logtail push model` into DN service;
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  pkg/dnservice/cfg.go
  pkg/dnservice/cfg_test.go
  pkg/dnservice/factory.go
  pkg/dnservice/store_test.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/network.go
  pkg/tests/service/network_test.go
  pkg/tests/service/options.go
  pkg/txn/service/service.go
  pkg/txn/storage/mem/kv_txn_storage.go
  pkg/txn/storage/memorystorage/dynamic_storage.go
  pkg/txn/storage/memorystorage/storage.go
  pkg/txn/storage/tae/storage.go
  pkg/txn/storage/types.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/service/logtail.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/stacker.go
  pkg/vm/engine/tae/logtail/service/stacker_test.go
  pkg/vm/engine/tae/logtail/service/waterline.go
  pkg/vm/engine/tae/logtail/service/waterline_test.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/cfg_test.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/feature, size/XL, dn

#7506 disable query result when no config
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/sql/compile/compile.go
  pkg/vm/process/types.go
Labels: size/S

#7510 Take global logger as the default logger for logtail server
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
Labels: kind/enhancement, size/XS, dn

#7495 fix user account can show all the databases
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/query_builder.go
  pkg/sql/util/util.go
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_account.sql
Labels: kind/bug, size/M

#7512 complete func of last_query_id and init var by config
  pkg/frontend/authenticate_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/load.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine_manager.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/function/builtin/unary/infomation_function.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vm/process/types.go
Labels: size/M

#7514 Revert "fix user account can show all the databases (#7495)"
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/query_builder.go
  pkg/sql/util/util.go
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_account.sql
Labels: kind/bug, size/M

#7474 [Feature Request]: Support a non-primary-key table with sorting key #6959
  pkg/catalog/types.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/types.go
  pkg/sql/util/composite_clusterby_util.go
  pkg/sql/util/util.go
  proto/plan.proto
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/feature, size/M

#7513 Include `logtail server address` in DN heartbeat
  pkg/dnservice/store_heartbeat.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  proto/logservice.proto
Labels: kind/enhancement, size/S

#7519 add prepare update statement
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S

#7503 [Feature] support configuration table
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/M

#7440 add gc checkpoint
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/testutils/config/options.go
Labels: kind/api-change, size/M

#7524 Take dnservice's logger for tae engine's logtail server
  pkg/dnservice/factory.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/bug, size/M

#7518 Modify code owners.
  CODEOWNERS
Labels: size/S

#7491 more support for foreign key in DDL statement
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  proto/plan.proto
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
Labels: kind/feature, size/M

#7294 Plan cache
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/plan_cache.go
  pkg/frontend/plan_cache_test.go
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/dml.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan_rule.go
  pkg/vm/engine/disttae/database.go
  proto/plan.proto
  test/distributed/cases/plan_cache/plan_cache.result
  test/distributed/cases/plan_cache/plan_cache.test
Labels: kind/feature, size/L

#7538 fix table function expr deep-copy err
  pkg/sql/plan/deepcopy.go
Labels: kind/bug, size/XS

#7526 Avoid using hard coded network port within UT;
  pkg/tests/network.go
  pkg/tests/network_test.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/network.go
  pkg/tests/service/network_test.go
  pkg/vm/engine/tae/logtail/service/service_test.go
Labels: kind/enhancement, size/M

#7535 fix log print
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/common/retry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/enhancement, size/S

#7545 Objectio add write options
  pkg/objectio/buffer.go
  pkg/objectio/type.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
Labels: kind/feature, size/S

#7548 Set affected rows for create/drop database
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#7552 Fix the merge bug of dist agg
  pkg/sql/colexec/agg/distagg.go
Labels: kind/bug, size/XS

#7528 [Bug] skip get value when the column type is json using show table_values stmt
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/bug, size/S

#7542 Add information function for current account
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/table_function/current_account.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/plan/current_account.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/account_info_func.result
  test/distributed/cases/function/account_info_func.sql
Labels: kind/feature, size/M

#7544 add field of tables in meta scan and support size limit
  pkg/catalog/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/sql/plan/meta_scan.go
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: size/M

#7522 moctl: add use spec timestamp as txn snapshot ts
  pkg/common/runtime/types.go
  pkg/frontend/session.go
  pkg/pb/ctl/ctl.pb.go
  pkg/pb/timestamp/timestamp.go
  pkg/pb/timestamp/timestamp_test.go
  pkg/sql/plan/function/builtin/ctl/cmd_snapshot.go
  pkg/sql/plan/function/builtin/ctl/cmd_snapshot_test.go
  pkg/sql/plan/function/builtin/ctl/types.go
  pkg/tests/txn/cluster_mo_ctl_test.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/util/json/json.go
  pkg/vm/engine/tae/logtail/service/server.go
  proto/ctl.proto
Labels: kind/feature, size/M

#7487 Precommit write s3 delete
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/metabase.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  proto/api.proto
Labels: kind/bug, size/L, kind/test-ci

#7551 Fix some incorrect memory usage
  pkg/sql/colexec/auto_incr.go
  pkg/sql/plan/function/operator/like.go
  pkg/txn/storage/memorystorage/memorytable/nullable.go
  pkg/vm/engine/disttae/partition_reader.go
Labels: kind/bug, size/S

#7566 add a bvt issue tag
  test/distributed/cases/table/create_table.test
Labels: kind/bug, size/XS

#7558 Fix #7397
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/function/func_hex.result
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/bug, size/S

#7541 Fix values bug
  pkg/sql/compile/compile.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/distributed/cases/dml/select/values.result
  test/distributed/cases/dml/select/values.sql
Labels: kind/bug, size/M

#7572 fileservice: disable caches in S3 tests
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/S

#7567 Account bug
  pkg/catalog/types.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/query_builder.go
  pkg/sql/util/util.go
  test/distributed/cases/zz_accesscontrol/inner_object.result
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/bug, size/M

#7149 Support use system-init to search system initialization related logs
  cmd/mo-service/main.go
  pkg/cnservice/server_task.go
  pkg/common/log/example_log_test.go
  pkg/common/log/filter.go
  pkg/common/log/logger.go
  pkg/common/log/types.go
  pkg/common/runtime/runtime.go
  pkg/common/runtime/types.go
  pkg/dnservice/store.go
  pkg/hakeeper/bootstrap/bootstrap.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/logservice/option.go
  pkg/logservice/service.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_commands.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_task.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_metadata.go
  pkg/logservice/store_metadata_test.go
  pkg/logservice/store_test.go
  pkg/logservice/truncation.go
  pkg/pb/task/task.go
  pkg/pb/task/task.pb.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/types.go
  pkg/tests/service/service.go
  pkg/tests/service/task_test.go
  pkg/util/export/merge.go
  proto/task.proto
  test/distributed/cases/log/system_init_log.result
  test/distributed/cases/log/system_init_log.sql
Labels: kind/enhancement, size/M

#7576 fix explain analyze bug
  pkg/sql/plan/build.go
Labels: kind/bug, size/XS

#7556 put table type in information_schema.tables
  pkg/util/sysview/sysview.go
Labels: kind/bug, size/XS

#7532 fix some bugs about auto_col
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/update/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: kind/enhancement, size/M

#7575 Logtail mem truncate
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/logtail/table_test.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/model/aot.go
Labels: kind/feature, size/S

#7547 fix analyzeinfo issue
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/types.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/top/top.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/vm/process/analyze.go
  pkg/vm/process/types.go
  proto/plan.proto
Labels: kind/bug, size/M

#7521 Add lock single row
  pkg/lockservice/lockTable.go
  pkg/lockservice/lockTable_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
Labels: kind/feature, size/M

#7579 Precommit write s3 delete
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/handle/segment.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
Labels: kind/bug, size/S, kind/test-ci

#7582 add show accounts
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/show_account_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/show.go
Labels: kind/feature, size/XXL

#7517 fix #7367
  pkg/sql/plan/function/builtin/unary/sleep.go
  pkg/sql/plan/function/builtin/unary/sleep_test.go
  test/distributed/cases/function/func_sleep.result
  test/distributed/cases/function/func_sleep.sql
  test/distributed/cases/function/func_sleep.test
  test/distributed/cases/function/function_sleep.sql
Labels: kind/bug, size/M

#7515 unique secondary index cases
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/ddl/unique_secondary_index.sql
  test/distributed/cases/dml/show/show.test
  test/distributed/cases/dtype/text_blob.sql
  test/distributed/cases/function/account_info_func.result
  test/distributed/cases/function/account_info_func.sql
  test/distributed/resources/load_data/unique_index_duplicate.csv
  test/distributed/resources/load_data/unique_index_file.csv
Labels: size/XL

#7591 fix analyze s3io issue
  pkg/vm/pipeline/pipeline.go
  pkg/vm/process/analyze.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#7584 Truncate cstr
  pkg/sql/compile/ddl.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
Labels: kind/bug, size/S

#7560 [Feature] support mo_table_col max() and min()
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
  test/distributed/cases/function/builtin.result
  test/distributed/cases/function/builtin.sql
Labels: kind/feature, size/M

#7139 fix system variables transaction_isolation
  pkg/frontend/variables.go
  test/distributed/cases/database/system_variables.result
Labels: kind/bug, size/S

#7583 Implement segmentation for `logtail response`
  pkg/pb/logtail/logtail.pb.go
  pkg/vm/engine/tae/logtail/service/chunk.go
  pkg/vm/engine/tae/logtail/service/chunk_test.go
  pkg/vm/engine/tae/logtail/service/client.go
  pkg/vm/engine/tae/logtail/service/request.go
  pkg/vm/engine/tae/logtail/service/response.go
  pkg/vm/engine/tae/logtail/service/response_test.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
  proto/logtail.proto
Labels: kind/enhancement, size/L, dn

#7563 add database statistics bvt test
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/resources/external_table_file/external_table.csv
Labels: size/L, kind/test-ci

#7536 [Bug] remove redundant show stmt code
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
Labels: kind/bug, size/XXL

#7592 GetConstantValue support all const values
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan_rule.go
Labels: kind/bug, size/S

#7602 update show accounts
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_manager.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/enhancement, kind/feature, size/XS

#7580 [Feature] support alter mo_mysql_compatbility_mode
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/feature, size/XXL

#7577 moctl: fix txn leak in engine
  pkg/sql/plan/function/builtin/ctl/cmd_flush.go
  pkg/sql/plan/function/builtin/ctl/ctl.go
Labels: size/S

#7606 lockservice: support skip completed waiter
  pkg/lockservice/lockTable.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_test.go
Labels: kind/enhancement, size/M

#7593 ObjectIO read metadata improvement
  pkg/objectio/block.go
  pkg/objectio/extent.go
  pkg/objectio/meta.go
  pkg/objectio/reader.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/dataio/blockio/info.go
  pkg/vm/engine/tae/dataio/blockio/types.go
Labels: kind/enhancement, kind/feature, size/M

#7603 add query result timeout and check privilege
  pkg/catalog/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/result_scan.go
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: size/XXL

#7525 support secondary key in the ddl
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/util/index_util.go
  pkg/sql/util/index_util_test.go
  proto/plan.proto
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/table/create_table.result
  test/distributed/cases/transaction/autocommit_1.result
  test/distributed/cases/transaction/autocommit_1.sql
  test/distributed/cases/transaction/isolation_2.result
  test/distributed/cases/transaction/isolation_2.sql
Labels: size/L

#7610 correct QueryType as doc declear
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/tree/analyze.go
  pkg/sql/parsers/tree/deallocate.go
  pkg/sql/parsers/tree/declare.go
  pkg/sql/parsers/tree/do.go
  pkg/sql/parsers/tree/execute.go
  pkg/sql/parsers/tree/explain.go
  pkg/sql/parsers/tree/kill.go
  pkg/sql/parsers/tree/mo_dump.go
  pkg/sql/parsers/tree/prepare.go
  pkg/sql/parsers/tree/select.go
  pkg/sql/parsers/tree/set.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/sql/parsers/tree/table_function.go
  pkg/sql/parsers/tree/truncate.go
  pkg/sql/parsers/tree/use.go
  pkg/sql/parsers/tree/values.go
  pkg/sql/parsers/tree/with.go
Labels: kind/enhancement, size/M

#7493 support load local
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/protocol.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_load.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  test/distributed/cases/dtype/json.result
  test/distributed/cases/dtype/json.test
Labels: kind/feature, size/M

#7622 add exclusive range lock
  pkg/lockservice/lock.go
  pkg/lockservice/lockTable.go
  pkg/lockservice/lockTable_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_test.go
Labels: kind/feature, size/M

#7623 [Bug] Fix mo_table_col_max and mo_table_col_min
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  pkg/vm/engine/disttae/table.go
Labels: kind/bug, size/S

#7640 fix cluster table privilege
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate2.go
  pkg/frontend/authenticate2_test.go
  test/distributed/cases/tenant/clustertable4.result
  test/distributed/cases/tenant/clustertable4.sql
Labels: kind/bug, size/M

#7645 Fix bug of output operator and remote run
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/aggUt/agg_testutil.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/multi_col/group_concat/group_concat.go
  pkg/sql/colexec/output/output.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/engine.go
  proto/pipeline.proto
Labels: kind/bug, size/M

#7627 remove bvt tag
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/ddl/unique_secondary_index.sql
Labels: size/S

#7618 add limit 1 in bvt test case
  test/distributed/cases/log/system_init_log.result
  test/distributed/cases/log/system_init_log.sql
Labels: kind/bug, size/XS

#7639 [Bug] Fix all null in show table_values stmt
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
Labels: kind/bug, size/S

#7653 bugfix: data trace on bufferHolder.buffer
  pkg/util/export/batch_processor.go
Labels: kind/bug, size/XS

#7657 fix for context being canceled
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#7448 fix load bug
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/deepcopy.go
  pkg/vm/process/analyze.go
  pkg/vm/process/types.go
  proto/plan.proto
Labels: kind/bug, size/XXL

#7660 improve: reduce unnecessary cast
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/XS

#7661 Fix the memory leak of joinmap
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/types.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_bench_test.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
Labels: kind/bug, size/M

#7654 fix create index blob/json/text not reported error
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/comprimary_key.result
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/ddl/unique_secondary_index.sql
  test/distributed/cases/dtype/text.result
  test/distributed/cases/dtype/text_blob.result
Labels: size/S

#7651 etc: add file service disk cache path config
  etc/dn-minimal-s3-test.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
  pkg/fileservice/local_fs_test.go
Labels: kind/enhancement, size/S

#7662 Skip table that doesn't have incremental logtail
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/enhancement, size/XS

#7664 [Bug] format function not support time types
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function.go
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: kind/bug, size/M

#7669 Fix some memory leak of cn
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#7666 Fix uniquekey bug
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: kind/bug, size/M

#7671 fix error info
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  test/distributed/cases/transaction/ww_conflict.result
  test/distributed/cases/transaction/ww_conflict.sql
Labels: kind/bug, size/S

#7677 FIX: make logtail collection and publishement serialized in `logtail push model`
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/bug, size/S

#7667 lockservice: integrated deadlock detector
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lockTable.go
  pkg/lockservice/lockTable_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
Labels: size/M

#7616 fix load compress
  pkg/sql/colexec/external/external.go
  pkg/sql/parsers/tree/update.go
  test/distributed/cases/load_data/load_data_jsonline.result
  test/distributed/cases/load_data/load_data_jsonline.test
  test/distributed/resources/load_data/jsonline_array.jl.bz2
  test/distributed/resources/load_data/jsonline_array.jl.gz
Labels: kind/bug, kind/enhancement, size/S

#7668 fix connection counter
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/bug, size/M

#7680 [Bug]: like op got false result, if target string has ( #7656
  pkg/vectorize/like/like.go
  test/distributed/cases/function/func_like.result
  test/distributed/cases/function/func_like.test
Labels: kind/bug, size/S

#7681 morpc: reset last received seqence in stream
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: kind/bug, size/XS

#7648 [Feature] support order by for group_concat in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/feature, size/XXL

#7647 [Docs]: Update root readme to correct frontend server start comments
  README.md
  README_CN.md
Labels: size/XS

#7540 Minor, fix a warning.
  pkg/sql/colexec/agg/median.go
Labels: size/XS

#7658 [Bug] Fix format func when the format string is null
  pkg/vectorize/format/format.go
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: kind/bug, size/M

#7694 remove bvt tag
  test/distributed/cases/ddl/json_type.result
  test/distributed/cases/ddl/json_type.sql
  test/distributed/cases/function/table_func_unnest.result
  test/distributed/cases/function/table_func_unnest.test
Labels: size/S, kind/test-ci

#7696 Ensure that a transaction opens a table only once
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/S

#7689 fix timestamp report error bug
  pkg/vm/engine/tae/common/print.go
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/dtype/time_1.result
Labels: size/S

#7698 support fk in delete statement
  pkg/container/vector/vector.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/column_prune_test.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/explain/marshal_query_test.go
  pkg/sql/plan/explain/tpch_explain_test.go
  pkg/sql/plan/index_table_dml_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/tpch_test.go
  pkg/sql/util/index_util.go
  pkg/vm/engine/disttae/tools.go
  proto/plan.proto
  test/distributed/cases/database/system_table.result
  test/distributed/cases/dml/delete/delete_multiple_table.result
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
  test/distributed/cases/table/external_table.result
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/tenant/privilege/operate_catalog.result
  test/distributed/cases/transaction/autocommit_1.result
  test/distributed/cases/transaction/autocommit_isolation.result
  test/distributed/cases/transaction/isolation.result
  test/distributed/cases/view/view_all.result
Labels: kind/feature, size/XXL

#7705 fix show create table bugs about float&double type
  pkg/sql/plan/build_show.go
Labels: kind/bug, size/XS

#7630 add segment flag to merge
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/enhancement, size/M

#7700 morpc: support ping
  pkg/cnservice/cnclient/client.go
  pkg/cnservice/server.go
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/client.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/internal.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/logservice/service.go
  pkg/txn/rpc/server.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/bug, size/M

#7710 "Add new func for floor ceil"
  pkg/sql/plan/function/builtin/multi/ceil.go
  pkg/sql/plan/function/builtin/multi/floor.go
  pkg/sql/plan/function/builtins.go
Labels: kind/bug, size/S

#7693 Collect metric storage usage
  cmd/mo-service/main.go
  pkg/cnservice/server_task.go
  pkg/config/configuration.go
  pkg/frontend/internal_executor.go
  pkg/pb/task/task.pb.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/metric/cron_task.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_server.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/test/cron_task_test.go
  proto/task.proto
Labels: kind/feature, size/M

#7719 fix show tables with quote
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/S

#7655 udf execution
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/types.go
  pkg/vm/engine/memoryengine/compiler_context.go
  test/distributed/cases/function/udf.result
  test/distributed/cases/function/udf.sql
Labels: kind/feature, size/M
