Repository matrixorigin/matrixone, pull requests merged in 2023-04, with the labels that each got.

#8766 Alter index visible
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
Labels: kind/feature, size/XXL

#8820 lockop: get min and max value in lock op
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
Labels: kind/feature, size/M

#8821 remove some dependencies on start TS
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/node.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/model/blkview.go
  pkg/vm/engine/tae/model/blkview_test.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/block_test.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/L

#8812 disttae: fix partitions fetching in updateMeta
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/XS

#8727 Update docu_check.yaml
  .github/workflows/docu_check.yaml
Labels: size/XS, kind/test-ci

#8787 modify err msg in local-infile err
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/enhancement, size/XS

#8796 Fix #8791
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: kind/bug, size/M

#8809 remove issue tag
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: size/XS, kind/test-ci

#8828 fileservice: disk cache evict fixes
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/perfcounter/counter_set.go
  pkg/tests/service/fileservice.go
  pkg/util/export/etl/csv_test.go
Labels: kind/bug, size/M

#8833 fix mo_columns filter
  pkg/sql/util/util.go
Labels: kind/bug, size/XS

#8835 Fix information schema bug
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
Labels: kind/bug, size/XS

#8840 better vector foreach impl and benchmarks
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/containers/vecwindow.go
  pkg/vm/engine/tae/dataio/blockio/write_index.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/functions_test.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: size/XL, kind/performance, dn

#8824 lockservice: add more log for panic
  pkg/lockservice/waiter.go
Labels: kind/bug, size/XS

#8143 plsql grammar
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/tree/branch.go
  pkg/sql/parsers/tree/compound.go
  pkg/sql/parsers/tree/iteration.go
  test/distributed/cases/procedure/procedure.result
  test/distributed/cases/procedure/procedure.sql
Labels: kind/feature, size/XXL

#8837 remove proc
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/enhancement, size/S

#8838 fix some function for cluster table
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/tenant/clustertable2.sql
Labels: kind/bug, size/M

#8839 add pk column for delete unique table
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/plan/build_constraint_util.go
Labels: size/S, kind/refactor

#8846 fileservice: disk cache fixes
  etc/dn-minimal-s3-test.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
  pkg/cnservice/server_metadata_test.go
  pkg/dnservice/store_metadata_test.go
  pkg/dnservice/store_test.go
  pkg/fileservice/cache.go
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path_test.go
  pkg/logservice/testclient.go
  pkg/perfcounter/counter_set.go
  pkg/tests/service/fileservice.go
  pkg/testutil/util_new.go
  pkg/util/export/etl/csv_test.go
  pkg/util/file/file_test.go
Labels: kind/bug, size/M

#8854 [Opt] Remove unnecessary PROJECT nodes from plan
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/L

#8849 remove unused field
  pkg/frontend/compiler_context.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/query_builder.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/S, kind/refactor

#8851 Improve prefetch interface
  pkg/vm/engine/tae/dataio/blockio/prefetch.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/enhancement, size/M

#8862 using insertion sort to replace quick sort to sort log tail received in cn.
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailPushModel_test.go
Labels: kind/bug, size/S

#8860 add internal table type in infromation_schema
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
Labels: kind/bug, size/XS

#8852 split join onlist
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/utils.go
Labels: size/S

#8858 fix lllegal use of transactions in ddl
  pkg/sql/colexec/index_metadata.go
  pkg/sql/colexec/index_metadata_test.go
Labels: kind/bug, size/M

#8864 small code refactor
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/dataio/blockio/write_index.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
Labels: size/M, kind/refactor

#8861 [Opt] Strip unnecessary subqueries which have no FROM clause
  pkg/sql/plan/flatten_subquery.go
  test/distributed/cases/subquery/subquery-with-in.sql
  test/distributed/cases/view/view-subquery-with-in.result
  test/distributed/cases/view/view-subquery-with-in.sql
Labels: kind/feature, size/M

#8521 update go.mod
  go.mod
  go.sum
Labels: kind/enhancement, size/XS

#8845 Remove seq init of bgsession
  pkg/frontend/session.go
Labels: size/S

#8874 adjust stats to get a better join order.
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/XS

#8880 use prepare in task update
  pkg/taskservice/mysql_task_storage.go
Labels: kind/refactor, size/XS

#8878 implement vector.Window
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
Labels: kind/feature, size/S, kind/refactor

#8885 fix marsh schema, persist partioned in log
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/bug, size/S

#8894 fileservice: use one file per IOEntry in disk cache
  pkg/fileservice/cache.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
Labels: kind/bug, size/M

#8897 fix force checkpoint timeout, unref ablk when applycommit/rollback
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, size/S

#8876 support compile multi step
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
Labels: kind/feature, size/M

#8843 minor refactor:change field name of Node
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: kind/refactor, size/XS

#8898 adjust join reordering algorithm in getJoinGraph
  pkg/sql/plan/join_order.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/S

#8823 Fix binary bug
  pkg/sql/plan/function/builtin/multi/concat.go
  pkg/sql/plan/function/builtin/multi/lpad.go
  pkg/sql/plan/function/builtin/multi/rpad.go
  pkg/sql/plan/function/builtins.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/dtype/binary.test
  test/distributed/cases/dtype/text_blob.result
  test/distributed/cases/function/func_string_lpad_rpad.result
  test/distributed/cases/function/func_string_lpad_rpad.test
Labels: kind/bug, size/S

#8899 update waterline before handle txn
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: size/S

#8873 improve export performance
  pkg/frontend/export.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
Labels: kind/enhancement, size/M

#8882 Refactor: add all Cols to TableDef.Cols
  pkg/frontend/compiler_context.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/binding.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/make.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: size/M, kind/refactor

#8902 lockservice: rpc blocked by remote lock
  pkg/common/morpc/cfg.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/lockservice/waiter.go
Labels: kind/bug, size/S

#8905 use stats to judge if pushdownSemiAntiJoins should be done
  pkg/sql/plan/join_order.go
Labels: kind/enhancement, size/XS

#8909 remove dn vecwindow
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vecwindow.go
  pkg/vm/engine/tae/db/db_test.go
Labels: size/M, kind/refactor, dn

#8900 [Opt] Reduce PROJECT nodes whose outputs are referenced only once
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: kind/enhancement, size/S

#8868 update marshal unmarshal, remove binary
  pkg/container/types/rowid.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/common/common_test.go
  pkg/vm/engine/tae/common/idalloc.go
  pkg/vm/engine/tae/common/interval.go
  pkg/vm/engine/tae/common/intervals.go
  pkg/vm/engine/tae/common/marshal.go
  pkg/vm/engine/tae/common/tree.go
  pkg/vm/engine/tae/iface/txnif/memo.go
  pkg/vm/engine/tae/logstore/driver/entry/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/desc.go
  pkg/vm/engine/tae/logstore/store/checkpointinfo.go
  pkg/vm/engine/tae/logstore/store/partialckp.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/tables/txnentries/command_test.go
  pkg/vm/engine/tae/tables/txnentries/compactblkcmd.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/helper.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
Labels: kind/enhancement, size/L

#8906 support show roles stmt in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/show.go
Labels: kind/bug, size/XXL

#8910 update bvt
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: size/S, kind/test-ci

#8901 removed insertion sort of push model; fix a bad code cause isSameCn lost efficacy
  pkg/sql/compile/compile.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailPushModel_test.go
Labels: kind/enhancement, size/S

#8914 change the zm impl
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/dataio/blockio/index.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/dataio/blockio/write_index.go
  pkg/vm/engine/tae/dataio/blockio/writer.go
  pkg/vm/engine/tae/dataio/blockio/writer_test.go
  pkg/vm/engine/tae/dataio/types.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  pkg/vm/engine/tae/index/zonemap.go
  pkg/vm/engine/tae/index/zonemap_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/zmnode_test.go
Labels: size/XL

#8743 clean up Makefile
  Makefile
Labels: size/S, kind/refactor

#8460 contributors readme action update
  README.md
Labels: size/XS

#8892 fix table function crash
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/function/table_func_unnest.result
  test/distributed/cases/function/table_func_unnest.test
Labels: kind/bug, size/M

#8768 Use WithRegion to do both golang trace and bpftrace
  pkg/common/moprobe/probe.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: size/S

#8884 Format sql in dat_cretatesql
  pkg/sql/compile/ddl.go
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/bug, size/S

#8903 Modify error code for invalid timezone value
  pkg/common/moerr/error.go
  pkg/frontend/variables.go
  test/distributed/cases/dtype/datetime.result
Labels: kind/feature, size/S

#8869 refuse converting string to decimal without type
  pkg/sql/plan/function/type_check.go
  test/distributed/cases/dtype/date.result
  test/distributed/cases/dtype/varchar.result
  test/distributed/cases/dtype/varchar.test
Labels: kind/bug, size/M

#8915 fix issue 8741 that connector operator early free the vector before dup and cause crash finally
  pkg/container/batch/batch.go
  pkg/container/batch/batch_test.go
  pkg/frontend/export.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/testutil/util_debug.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/moengine/reader.go
Labels: kind/bug, size/M

#8922 Add command-line option "--heap-profile"
  cmd/mo-service/debug.go
  cmd/mo-service/main.go
Labels: kind/feature, size/S

#8912 remove unused logic
  pkg/frontend/cmd_executor.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/resultset_stmt.go
  pkg/frontend/session.go
  pkg/frontend/status_stmt.go
Labels: size/S, kind/refactor

#8908 lockservice: fix data race
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/txn.go
Labels: kind/bug, size/XS

#8921 ConstFold for unary operator and limit/offset validation in QueryBuilder
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#8923 support agg pullup
  pkg/sql/plan/agg_pushdown_pullup.go
  pkg/sql/plan/query_builder.go
Labels: kind/feature, size/M

#8919 fix full segment
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/handle.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
Labels: kind/bug, size/M

#8887 Add `PROPERTIES` to non_reserved_keyword
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
Labels: kind/bug, size/XXL

#8926 code refactor
  pkg/container/types/encoding.go
  pkg/container/types/txnts.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compare_test.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/dataio/blockio/write_index.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/functions_test.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: kind/enhancement, size/L, kind/refactor

#8924 optimize deleteBatch
  pkg/container/types/rowid.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/S

#8934 improve dedup in dn
  pkg/vm/engine/tae/common/seqnum.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
Labels: kind/enhancement, size/S, kind/performance

#8935 lockservice: fix dead lock between acquireLock and getLock
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/txn.go
Labels: kind/bug, size/S

#8927 get pk column for lock before delete
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: size/S, kind/refactor

#8917 support show roles stmt
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
Labels: kind/feature, size/S

#8929 remove unused interface
  pkg/frontend/compiler_context.go
  pkg/frontend/session_test.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/make.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: size/M, kind/refactor

#8813 bugfix: txn context loss trace context info
  pkg/frontend/txn.go
Labels: kind/bug, size/XS

#8907 clean up some code in compile
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
Labels: size/M, kind/refactor

#8941 fix float&double precision
  pkg/defines/type.go
Labels: kind/bug, size/XS

#8920 fix grafana connect error
  pkg/frontend/authenticate.go
Labels: kind/bug, size/XS

#8928 Fix #8886
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/sql/colexec/table_function/meta_scan.go
Labels: kind/bug, size/S

#8943 [Feature Request]: support agg pushdown and pullup
  pkg/sql/plan/agg_pushdown_pullup.go
Labels: kind/feature, size/M

#8952 fix a new sender error will not return.
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/XS

#8950 fix null zm
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
Labels: kind/bug, size/S

#8939 Extend alter table add constraint
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
  test/distributed/cases/table/create_table.result
Labels: kind/bug, size/XL

#8961 fix some rpc client logger not set
  pkg/cnservice/cnclient/client.go
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/bug, size/S

#8855 Show accounts save result
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/show_account_test.go
Labels: kind/bug, size/L

#8956 [Refactor] Remove types.Null | Update()
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/moengine/engine_test.go
Labels: size/M, kind/refactor

#8962 disttae: init txnTable partitions once
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/dml/update/flush.result
  test/distributed/cases/dml/update/flush.test
Labels: kind/bug, size/S

#8965 morpc: fix dead lock after close server session
  pkg/common/morpc/server.go
  pkg/lockservice/log.go
Labels: kind/bug, size/S

#8969 fix merge deletes
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/writer_test.go
  test/distributed/cases/dml/update/flush.result
  test/distributed/cases/dml/update/flush.test
Labels: kind/bug, size/S

#8955 update deduplication
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
Labels: kind/enhancement, size/M

#8968 Optimize ObjectName.String() interface
  pkg/objectio/location.go
  pkg/objectio/location_test.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
Labels: kind/enhancement, size/S

#8819 txn: support use latest pushed ts as snapshot ts
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e_with_push_model.yml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch/cn1.toml
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/preinsert/preinsert_test.go
  pkg/sql/compile/compile_test.go
  pkg/sql/plan/function/builtin/ctl/cmd_flush.go
  pkg/sql/plan/function/builtin/ctl/ctl.go
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/function/builtin/inside/internal_auto_increment.go
  pkg/sql/plan/function/builtin/inside/internal_auto_increment_test.go
  pkg/sql/plan/function/builtin/inside/util.go
  pkg/sql/plan/function/builtin/seq/currval_test.go
  pkg/sql/plan/function/builtin/seq/seq_util.go
  pkg/sql/plan/function/builtin/seq/setval_test.go
  pkg/testutil/testengine/testengine.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/client/timestamp_waiter.go
  pkg/txn/client/timestamp_waiter_test.go
  pkg/txn/client/types.go
  pkg/txn/service/service.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_dn_handler.go
  pkg/txn/service/service_testutil.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/txn/util/log.go
  pkg/util/metric/test/cron_task_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailPushModel_test.go
  pkg/vm/engine/tae/moengine/txn_wrapper.go
  pkg/vm/engine/tae/moengine/txn_wrapper_test.go
Labels: kind/feature, size/M

#8963 [Refactor] Remove types.Null | types.IsNull() + Append
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/batch_test.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/block_test.go
  pkg/vm/engine/tae/tables/functions_test.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: size/L, kind/refactor

#8970 Resolve bugs about alter table index
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
Labels: kind/bug, size/XXL

#8975 lockup: add lock support partition
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/types.go
Labels: kind/feature, size/L

#8971 Format sql for create table stmt
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
  test/distributed/cases/view/view.result
Labels: kind/bug, size/S

#8978 [bug] proxy: Add some condition for proxy service startup when use -cfg.
  cmd/mo-service/config.go
  cmd/mo-service/main.go
Labels: kind/bug, size/XS

#8974 fix issue #8959 and analyze info issue
  pkg/sql/compile/compile.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/S

#8976 [Refactor] Remove types.Null | common.TypeStringValue + Get
  pkg/container/types/txnts.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: size/M, kind/refactor

#8983 fix compaction
  pkg/objectio/meta.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/bug, size/S

#8932 refactor S3Writer
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/enhancement, size/M

#8990 Add BlockPrefetch interface to support cn Prefetch
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/api-change, size/S

#8992 [Exec] Fix null value handling for hash join operators
  pkg/container/vector/vector.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/join_test.go
  pkg/sql/colexec/right/types.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/join_test.go
  pkg/sql/colexec/rightanti/types.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/join_test.go
  pkg/sql/colexec/rightsemi/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: kind/bug, size/M

#8988 fix compatibility misspelling
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  pkg/sql/util/util.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/sql_inject/sql_inject.result
  test/distributed/cases/sql_inject/sql_inject.test
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/bug, size/M

#8844 pb/txn: give more info in panic
  pkg/pb/txn/txn.go
Labels: kind/enhancement, size/XS

#8987 add one column for mo_account to check connect version
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  test/distributed/cases/tenant/alter_account.result
  test/distributed/cases/tenant/alter_account.sql
Labels: kind/feature, size/S

#8997 [Refactor] : Minor refactoring in container/types.go
  pkg/container/types/types.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/s3util.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/function/builtin/inside/mo_internal.go
  pkg/sql/plan/function/builtin/unary/infomation_function.go
  pkg/sql/plan/function/builtin/unary/json_unquote.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/type_check.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_util.go
  pkg/testutil/util_new.go
Labels: size/M, kind/refactor

#8967 support alter user password
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/tenant/privilege/role6_createuser.result
  test/distributed/cases/tenant/privilege/role6_createuser.sql
Labels: kind/feature, size/M

#9003 [Exec] Avoid sending empty batches during right SEMI/ANTI join probe
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
Labels: kind/enhancement, size/S

#8938 [bug] kill query failed in multi cn env.
  pkg/cnservice/server.go
  pkg/config/configuration.go
  pkg/frontend/routine_manager.go
  pkg/frontend/server.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/conn_manager.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/handshake.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/mysql_conn_buf_test.go
  pkg/proxy/ppv2.go
  pkg/proxy/ppv2_test.go
  pkg/proxy/router.go
  pkg/proxy/router_test.go
  pkg/proxy/server.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/server_test.go
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
  pkg/proxy/whitelist.go
  pkg/proxy/whitelist_test.go
Labels: kind/bug, size/XXL

#9002 Improve nulls handling
  pkg/container/batch/batch.go
  pkg/container/nulls/nulls.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/update/update.go
Labels: kind/enhancement, size/M

#8801 support parallel load for multi-CN
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/vm/process/process.go
  proto/pipeline.proto
Labels: kind/enhancement, size/M

#9009 fix issue #8165
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
Labels: kind/bug, size/XS

#9007 Add missing deserialization of right SEMI/ANTI join
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#9006 Improve plan cache
  pkg/frontend/plan_cache.go
  pkg/frontend/plan_cache_test.go
Labels: kind/enhancement, size/S

#9005 release resources
  pkg/frontend/authenticate2_test.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/show_account_test.go
  pkg/frontend/show_publications_test.go
  pkg/frontend/show_subscriptions_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/enhancement, size/M

#9012 refactor some read and write related code
  pkg/objectio/block.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/meta.go
  pkg/objectio/reader.go
  pkg/objectio/types.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/prefetch.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
Labels: priority/p1, size/XL, kind/refactor

#9019 Change col data layout
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
Labels: kind/enhancement, size/S

#8891 transaction ddl cases
  test/distributed/cases/sequence/create_sequence.result
  test/distributed/cases/sequence/create_sequence.sql
  test/distributed/cases/transaction/atomicity.result
  test/distributed/cases/transaction/atomicity.sql
Labels: size/M, kind/test-ci

#8998 add alter user test case
  test/distributed/cases/tenant/privilege/alter_user_password.result
  test/distributed/cases/tenant/privilege/alter_user_password.sql
Labels: kind/feature, size/S

#9025 improve dedup perf
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/model/index.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/factory.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/segment.go
  pkg/vm/engine/tae/tables/table.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, size/M, kind/refactor, dn

#9028 fix reader
  pkg/objectio/reader.go
Labels: kind/bug, size/XS

#9023 bugfix: etl collect buffer cnt default: no limit
  pkg/config/configuration.go
  pkg/util/export/batch_processor.go
Labels: kind/bug, size/S

#9036 fix time convert bug
  pkg/sql/plan/function/operator/cast2.go
Labels: size/S

#9015 perf(ci): optimize docker compose
  etc/launch-tae-compose/compose.yaml
Labels: size/S, kind/test-ci

#9040 Preallocate result vector for CAST expression
  pkg/container/vector/functionTools.go
Labels: kind/enhancement, size/XS

#9038 force right join to execute on single cn
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#9035 Cn liveness check
  pkg/cnservice/cnclient/client.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#9048 calc stats for values scan node
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#9053 [Opt] Transform count distinct into 2 agg nodes
  pkg/frontend/util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/distinct_agg.go
  pkg/sql/plan/having_binder.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/visit_plan.go
Labels: kind/enhancement, kind/feature, size/M

#9055 fix a pipeline free bug may cause hung if next pipeline closed early
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/merge/types.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/types.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/types.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/types.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/types.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/types.go
  pkg/vm/pipeline/types.go
Labels: kind/bug, size/M

#9058 add codecs for objectio
  pkg/objectio/codecs.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/meta.go
  pkg/objectio/reader.go
  pkg/objectio/versions.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
Labels: kind/enhancement, size/M, kind/refactor

#9059 fix unnest bug in rawlog table
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/colexec/table_function/unnest.go
Labels: kind/bug, size/XS

#9021 Record original sql in statement_info
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/parsers/sqlparse_test.go
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
  test/distributed/cases/log/query_version.result
  test/distributed/cases/log/query_version.sql
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: kind/enhancement, size/L

#9067 Reduce memory generation cost of WriteBlock
  pkg/container/vector/vector.go
  pkg/objectio/writer.go
Labels: kind/enhancement, size/S

#9063 floor/ceil(decimal,digit) return error when digit is too large
  pkg/sql/plan/function/builtin/multi/ceil.go
  pkg/sql/plan/function/builtin/multi/floor.go
  test/distributed/cases/function/func_math_ceil.result
  test/distributed/cases/function/func_math_floor.result
Labels: size/S

#9064 Fix 553, 7813
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: kind/bug, size/S

#9061 Change scale when cast time to decimal
  pkg/sql/plan/function/operator/cast2.go
Labels: kind/bug, size/XS

#9052 [#8993]Fix 8993
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/s3util.go
Labels: kind/bug, size/S

#9050 [feat] proxy: add counter set and show cmd for proxy.
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/stmt_kind.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/conn_manager_test.go
  pkg/proxy/counter_set.go
  pkg/proxy/counter_set_test.go
  pkg/proxy/error.go
  pkg/proxy/error_test.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/rebalancer_test.go
  pkg/proxy/router_test.go
  pkg/proxy/server.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/util/metric/stats/registry.go
Labels: kind/feature, size/XXL

#9071 refactor compare function
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: size/S, kind/refactor

#9054 hide password using SHA1(SHA1(password))
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  test/distributed/cases/tenant/user.result
  test/distributed/cases/zz_accesscontrol/alter_account.result
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_user.result
  test/distributed/cases/zz_accesscontrol/drop_user.result
  test/distributed/cases/zz_accesscontrol/grant_privs_role.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/enhancement, size/M

#9072 remove unused code
  pkg/vm/engine/tae/buffer/base/types.go
  pkg/vm/engine/tae/buffer/buffer_test.go
  pkg/vm/engine/tae/buffer/evict.go
  pkg/vm/engine/tae/buffer/limiter.go
  pkg/vm/engine/tae/buffer/node.go
  pkg/vm/engine/tae/buffer/nodemgr.go
  pkg/vm/engine/tae/common/compress.go
  pkg/vm/engine/tae/common/consts.go
  pkg/vm/engine/tae/common/file.go
  pkg/vm/engine/tae/common/file_test.go
  pkg/vm/engine/tae/common/generator.go
  pkg/vm/engine/tae/common/hack.go
  pkg/vm/engine/tae/common/hack_test.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/tables/indexwrapper/meta.go
  pkg/vm/engine/tae/txn/txnbase/node.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: size/XL, kind/refactor

#9077 code cleanup
  pkg/objectio/utils.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/common/marshal.go
  pkg/vm/engine/tae/common/retry.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/moengine/block.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/samples/sample3/main.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/mock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/M, kind/refactor

#9078 Support layout adaptation version control
  pkg/objectio/codecs.go
  pkg/objectio/column.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/meta.go
  pkg/objectio/reader.go
  pkg/objectio/utils.go
  pkg/objectio/versions.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: kind/enhancement, kind/feature, size/M

#9074 TimeToIntAndDecimal
  test/distributed/cases/dtype/TimeToInt.result
  test/distributed/cases/dtype/TimeToInt.sql
Labels: size/L

#9084 update objectio
  pkg/objectio/codecs.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/objectio/utils.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
Labels: size/M, kind/refactor

#9089 improve objectio's writer memory usage
  pkg/objectio/writer.go
Labels: kind/enhancement, size/S

#9056 Fix truncate
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_delete.go
  pkg/vm/engine/disttae/txn_database.go
  test/distributed/cases/auto_increment/auto_increment_columns.result
  test/distributed/cases/load_data/load_data_set_null.result
Labels: kind/bug, size/S

#9042 modify decimal result for some cases
  test/distributed/cases/dtype/date.result
  test/distributed/cases/function/func_math_floor.test
  test/distributed/cases/operator/operator.result
Labels: size/S, kind/test-ci

#9101 fix udf exec bug on constant fold
  pkg/sql/plan/base_binder.go
Labels: kind/bug, size/S
