Repository matrixorigin/matrixone, pull requests merged in 2023-03, with the labels that each got.

#8065 disttae: new partition cache implementation. phase 1
  pkg/container/types/rowid.go
  pkg/vm/engine/disttae/bench_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/M

#8187 fix bvt test
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
Labels: kind/bug, size/S

#8191 fix 8186
  pkg/container/vector/vector.go
  pkg/sql/colexec/s3util.go
Labels: kind/bug, size/XS

#8184 Fix alter config error and add account privilege check
  pkg/frontend/authenticate.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#8195 lockservice: fix TestKeepaliveBind failed
  pkg/lockservice/lock_table_allocator_test.go
Labels: kind/bug, size/XS

#8189 add ut for cn logtail push model
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailPushModel_test.go
Labels: size/M

#8198 fix bvt test error
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
Labels: kind/bug, size/S

#8201 disttae: code clean-ups
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/M

#8209 logservice: fix bug #8154, logservice not working if failover happens.
  pkg/logservice/shardinfo.go
Labels: kind/bug, size/XS

#8203 Update logtail server buffer size for responses to be sent
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/enhancement, size/S

#8193 fix stats and join order in join vertex
  pkg/sql/compile/compile.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/M

#8211 morpc: add message cache
  pkg/common/morpc/cache.go
  pkg/common/morpc/cache_test.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/feature, size/M

#8213 disttae: various refactors
  pkg/container/types/rowid.go
  pkg/txn/storage/memorystorage/memtable/index_iter.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_meta.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/XL

#8221 Add GetUnionOneFunction for better copying of vector's data
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
Labels: kind/feature, size/M

#8226 logservice: update dragonboat version.
  go.mod
  go.sum
Labels: kind/enhancement, size/XS

#8140 tae sort refactor
  .licenserc.yml
  pkg/vm/engine/tae/mergesort/bools/func.go
  pkg/vm/engine/tae/mergesort/bools/heap.go
  pkg/vm/engine/tae/mergesort/bools/sort.go
  pkg/vm/engine/tae/mergesort/bools/types.go
  pkg/vm/engine/tae/mergesort/decimal128s/func.go
  pkg/vm/engine/tae/mergesort/decimal128s/heap.go
  pkg/vm/engine/tae/mergesort/decimal128s/sort.go
  pkg/vm/engine/tae/mergesort/decimal128s/types.go
  pkg/vm/engine/tae/mergesort/decimal64s/func.go
  pkg/vm/engine/tae/mergesort/decimal64s/sort.go
  pkg/vm/engine/tae/mergesort/decimal64s/types.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/heap.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/mergesort/numerics/func.go
  pkg/vm/engine/tae/mergesort/numerics/heap.go
  pkg/vm/engine/tae/mergesort/numerics/sort.go
  pkg/vm/engine/tae/mergesort/numerics/types.go
  pkg/vm/engine/tae/mergesort/rowid/func.go
  pkg/vm/engine/tae/mergesort/rowid/heap.go
  pkg/vm/engine/tae/mergesort/rowid/sort.go
  pkg/vm/engine/tae/mergesort/rowid/types.go
  pkg/vm/engine/tae/mergesort/sort.go
  pkg/vm/engine/tae/mergesort/txnts/func.go
  pkg/vm/engine/tae/mergesort/txnts/heap.go
  pkg/vm/engine/tae/mergesort/txnts/sort.go
  pkg/vm/engine/tae/mergesort/txnts/types.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/mergesort/uuids/func.go
  pkg/vm/engine/tae/mergesort/uuids/heap.go
  pkg/vm/engine/tae/mergesort/uuids/types.go
  pkg/vm/engine/tae/mergesort/varchar/func.go
  pkg/vm/engine/tae/mergesort/varchar/heap.go
  pkg/vm/engine/tae/mergesort/varchar/sort.go
  pkg/vm/engine/tae/mergesort/varchar/types.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/stl/containers/stdvec.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/bug, size/XXL, kind/refactor

#8219 change the time record unit to nanosecond
  pkg/sql/plan/explain/explain_query.go
Labels: kind/bug, size/XS

#8230 try to cast values to decimal64 if possible
  pkg/sql/plan/make.go
  test/distributed/cases/dml/select/union_and_union_all.result
  test/distributed/cases/dtype/date.result
  test/distributed/cases/function/func_datetime_date.result
  test/distributed/cases/function/func_datetime_dayofyear.result
  test/distributed/cases/function/func_datetime_weekday.result
  test/distributed/cases/subquery/subquery-with-exists.result
  test/distributed/cases/view/view-subquery-with-exists.result
Labels: kind/enhancement, size/S

#8222 sort filters by stats
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  test/distributed/cases/operator/is_not_operator.result
Labels: kind/enhancement, size/S

#8190 show_case
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/S

#8171 Support data information schema view
  pkg/sql/plan/function/builtin/inside/internal_auto_increment.go
  pkg/sql/plan/function/builtin/inside/internal_auto_increment_test.go
  pkg/sql/plan/function/builtin/inside/mo_internal.go
  pkg/sql/plan/function/builtin/inside/mo_internal_test.go
  pkg/sql/plan/function/builtin/inside/util.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/feature, size/XL

#8237 fix bug: SQL injection
  pkg/frontend/session.go
  test/distributed/cases/sql_inject/sql_inject.result
  test/distributed/cases/sql_inject/sql_inject.test
Labels: kind/bug, size/S

#8236 disttae: various refactors
  pkg/container/vector/vector.go
  pkg/vm/engine/disttae/bench_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/M

#8233 fix show columns order
  pkg/sql/plan/build_show.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
Labels: kind/bug, size/S

#8220 add a filter to change version
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#8229 CI: fix coverage is zero error
  .github/workflows/coverage_pr.yml
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#8245 disttae: various refactors
  pkg/vm/engine/disttae/bench_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_meta.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/L

#8250 Revert "disttae: various refactors (#8245)"
  pkg/vm/engine/disttae/bench_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_meta.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/L

#8175 basic support for 'on duplicate key xxxx' clause
  pkg/container/vector/vector.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/builtin/unary/values.go
  pkg/sql/plan/function/builtin/unary/values_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/sql/plan/update_binder.go
  pkg/sql/plan/utils.go
  pkg/vm/overload.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/dml/insert/insert.result
  test/distributed/cases/dml/insert/on_duplicate_key.result
  test/distributed/cases/dml/insert/on_duplicate_key.sql
Labels: kind/feature, size/XL

#8238 adjust stats and join order
  pkg/sql/plan/join_order.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/S

#8249 support more than one stmt sourceType
  pkg/frontend/cmd_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
Labels: kind/bug, size/S

#8170 optimize insert s3
  pkg/sql/colexec/merge_util.go
Labels: kind/enhancement, size/M

#8254 rename e2e(race) job name
  .github/workflows/e2e_with_race.yml
Labels: size/XS, kind/test-ci

#8205 support lock tables stmt in plan
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/lock.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: kind/feature, size/M

#8251 disttae: various refactors
  go.mod
  go.sum
  pkg/container/types/tuple.go
  pkg/fileservice/memory_fs.go
  pkg/txn/storage/memorystorage/memorytable/btree.go
  pkg/txn/storage/memorystorage/memorytable/btree_log.go
  pkg/txn/storage/memorystorage/memtable/bench_test.go
  pkg/txn/storage/memorystorage/memtable/diff_iter.go
  pkg/txn/storage/memorystorage/memtable/index_iter.go
  pkg/txn/storage/memorystorage/memtable/physical_row.go
  pkg/txn/storage/memorystorage/memtable/physical_row_test.go
  pkg/txn/storage/memorystorage/memtable/table.go
  pkg/txn/storage/memorystorage/memtable/table_iter.go
  pkg/txn/storage/memorystorage/memtable/table_test.go
  pkg/txn/storage/memorystorage/memtable/time.go
  pkg/txn/storage/memorystorage/memtable/transaction.go
  pkg/txn/storage/memorystorage/memtable/types.go
  pkg/vm/engine/disttae/bench_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/encode.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/index.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/partition_state_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_meta.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/XXL

#8265 fix stats and join order, add exprNDV
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/S

#8261 support unlock tables stmt in plan
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/lock.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: kind/feature, size/S

#8273 fix pipeline hung bug
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#8272 CI: Coverage html upload
  .github/workflows/coverage_pr.yml
Labels: size/S, kind/test-ci

#8260 Improve publishment performance and stability
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/enhancement, size/S

#8267 Fix testEngine causing ut to fail
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M

#8280 disttae: also delete primary key index entry when deleting row entry
  pkg/vm/engine/disttae/partition_state.go
Labels: kind/enhancement, size/S

#8283 Replace the original partition with a snapshot
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/function/func_aggr_avg.test
  test/distributed/cases/function/func_aggr_count.test
Labels: kind/bug, kind/enhancement, size/S

#8258 Insert s3 optimize
  pkg/container/batch/batch.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/transaction/conflict_transation.result
Labels: kind/enhancement, size/M

#8282 fix some error result
  test/distributed/cases/function/func_aggr_bitwise.result
  test/distributed/cases/function/func_coalesce_1.result
  test/distributed/cases/function/func_string_bin.result
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/table/external_table.result
Labels: size/S, kind/test-ci

#8132 update the version number and backend launch command
  README.md
  README_CN.md
Labels: kind/documentation, size/XS

#8285 [Bug]: Decimal64 can't use IN or NOT IN, while Decimal128 can
  pkg/sql/plan/base_binder.go
Labels: kind/bug, size/S

#8289 fix reminder backoff ut failure
  pkg/util/batchpipe/batch_pipe_test.go
Labels: size/XS

#8296 Fix sql injection
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/session.go
  test/distributed/cases/sql_inject/sql_inject.result
  test/distributed/cases/sql_inject/sql_inject.test
Labels: kind/bug, size/L

#8293 fix error in coverage_pr
  .github/workflows/coverage_pr.yml
Labels: size/XS, kind/test-ci

#8299 check if no need to cast double column when compared to int constant
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#8174 Fix bug: 7278
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/make.go
  pkg/sql/plan/visit_plan.go
  pkg/sql/plan/visit_plan_rule.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/M

#8292 Remove cluster table in insertion
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/deepcopy.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/table/cluster_table/cluster_table.sql
  test/distributed/cases/tenant/clustertable.result
  test/distributed/cases/tenant/clustertable.sql
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/tenant/clustertable2.sql
  test/distributed/cases/tenant/clustertable3.result
  test/distributed/cases/tenant/clustertable3.sql
  test/distributed/resources/load_data/cluster_table.csv
  test/distributed/resources/load_data/cluster_table1.csv
Labels: size/M, kind/refactor

#8302 adjust stats for ssb and tpch benchmark
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/S

#8301 Test engine
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: kind/bug, size/XS

#8317 Add ci for push
  .github/workflows/e2e-compose.yml
  etc/launch-test-push-model/cn.toml
  etc/launch-test-push-model/dn.toml
  etc/launch-test-push-model/launch.toml
  etc/launch-test-push-model/log.toml
Labels: size/M, kind/test-ci

#8316 revert transfer little batch
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/transaction/conflict_transation.result
Labels: kind/bug, size/M

#8313 disttae: add packer pool
  pkg/container/types/tuple.go
  pkg/container/types/tuple_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/pool.go
  pkg/fileservice/pool_test.go
  pkg/fileservice/profile.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/encode.go
  pkg/vm/engine/disttae/encode_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/partition_state_iterators_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/M

#8264 lower case table names
  pkg/config/configuration.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/show_account_test.go
  pkg/frontend/status_stmt.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/postgresql/postgresql_sql.go
  pkg/sql/parsers/dialect/postgresql/postgresql_sql.y
  pkg/sql/parsers/example/eg_mysql.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/parsers/sqlparse_test.go
  pkg/sql/parsers/tree/cstr.go
  pkg/sql/parsers/tree/cstr_test.go
  pkg/sql/parsers/tree/use.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/explain/column_prune_test.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/explain/marshal_query_test.go
  pkg/sql/plan/explain/tpch_explain_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/tpch_test.go
  test/distributed/cases/database/new_database.result
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/tenant/privilege/create_account_case_sensitive.result
  test/distributed/cases/tenant/privilege/create_role_case_sensitive.result
  test/distributed/cases/tenant/privilege/create_user_case_sensitive.result
Labels: size/L

#8330 revert cast integer constant to double column
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/XS

#8308 fix bvt case sql_source_type - make it stable
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
Labels: size/S, kind/test-ci

#8333 change time-spent statics unit to ns
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
Labels: kind/bug, size/XS

#8324 seperate big pipelinemsg into chunks
  pkg/cnservice/cnclient/client.go
  pkg/cnservice/server.go
  pkg/pb/pipeline/pipeline.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, kind/enhancement, size/M

#8334 clean up insertion code
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/insert/insert.go
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
Labels: size/S, kind/refactor

#8339 fix some bugs
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
Labels: size/XXL

#8340 improve error output
  pkg/common/moerr/error.go
  pkg/sql/plan/build_constraint_util.go
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/function_split_part.result
  test/distributed/cases/function/function_substring_index.result
  test/distributed/cases/view/view-subquery-with-in.result
Labels: kind/enhancement, size/S, kind/refactor

#8341 add status code for some stmts
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
Labels: kind/bug, size/S

#8349 Dn dosen't check pk duplication against txn's workspace
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/moengine/sys_relation.go
  pkg/vm/engine/tae/moengine/txn_relation.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/ddl/unique_secondary_index.sql
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/cases/transaction/conflict_transation.result
  test/distributed/cases/transaction/conflict_transation.sql
Labels: kind/bug, size/L

#8350 disttae: fix checkpoint replay in push mode
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/dml/update/checkpoint.result
  test/distributed/cases/dml/update/checkpoint.test
Labels: kind/bug, size/M

#8357 for tpch q13, do not use right outer join. will fix it in the future
  pkg/sql/plan/join_order.go
Labels: kind/bug, size/S

#8276 more support in on duplicate key clause
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/deepcopy.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/dml/insert/on_duplicate_key.result
  test/distributed/cases/dml/insert/on_duplicate_key.sql
Labels: kind/feature, size/M

#8361 fileservice: add Counter, WithCounter
  pkg/fileservice/counter.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/S

#8360 improve load compatibility
  pkg/defines/type.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/resultset.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_load.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
Labels: kind/bug, size/M

#8370 No longer lazy load 3 tables on mo_catalog. Fix push model init and reconnect bug.
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table_meta.go
Labels: kind/bug, size/M

#8369 [Refactor] Decouple Cache Replacement Strategy from MemCache.
  pkg/fileservice/example_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memcachepolicy/clockpolicy/clock.go
  pkg/fileservice/memcachepolicy/lrupolicy/lru.go
  pkg/fileservice/memcachepolicy/lrupolicy/lru_test.go
  pkg/fileservice/memcachepolicy/rc_value.go
  pkg/fileservice/memcachepolicy/releasable_value.go
  pkg/fileservice/memcachepolicy/types.go
  pkg/fileservice/releasable_test.go
  pkg/fileservice/s3_fs.go
Labels: size/M, kind/refactor

#8377 fix issue 8291
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/bug, size/XS

#8378 fix prepare and txn mgr
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/waterline.go
  pkg/vm/engine/tae/logtail/service/waterline_test.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/logtail/table_test.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/bug, size/S

#8365 fix q13 crash issue
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#8387 Update cn's morpc configuration
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
Labels: kind/enhancement, size/S

#8366 remove accounts syntax in insert & load
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/api-change, size/XXL

#8389 Revert "for tpch q13, do not use right outer join. will fix it in the…
  pkg/sql/plan/join_order.go
Labels: kind/bug, size/S

#8358 support pubAndSub in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/drop.go
  pkg/sql/parsers/tree/show.go
Labels: kind/feature, size/XXL

#8395 Tolerate cases setting bitmap for index larger than vector length
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/containers/utils.go
Labels: kind/bug, size/S

#8397 morpc: return error if write failed in server
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
Labels: kind/bug, size/XS

#8400 morpc: fix panic
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
Labels: kind/bug, size/S

#8399 Don't panic on empty vector read from dn
  pkg/container/vector/tools.go
Labels: kind/bug, size/S

#8401 morpc: fix TestServerTimeoutCacheWillRemoved
  pkg/common/morpc/server_test.go
Labels: kind/bug, size/XS

#8406 add some comments
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/operator.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/enhancement, size/M

#8403 mo-service: setup global counter and HTTP page
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/debug.go
  cmd/mo-service/launch.go
  cmd/mo-service/main.go
  pkg/cnservice/distributed_tae.go
  pkg/perfcounter/counter.go
  pkg/perfcounter/http.go
  pkg/perfcounter/http_test.go
  pkg/vm/engine/disttae/partition_state.go
Labels: kind/enhancement, size/M

#8385 Support alter foreign key in plan
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/types.go
  proto/plan.proto
Labels: kind/feature, size/M

#8372 reorder insert instructions
  pkg/sql/colexec/constraint_util.go
  pkg/sql/compile/compile.go
Labels: size/S, kind/refactor

#8417 txn: intergration lockservice
  pkg/frontend/test/txn_mock.go
  pkg/pb/txn/txn.pb.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/tae/moengine/txn_wrapper.go
  proto/txn.proto
Labels: kind/feature, size/M

#8411 Rename WriteS3Container to S3Writer
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/sql/colexec/server.go
  pkg/sql/compile/operator.go
Labels: size/L, kind/refactor

#8424 lockservice: fix ut
  pkg/common/morpc/server_test.go
  pkg/lockservice/lock_table_allocator_test.go
Labels: kind/bug, size/S

#8429 modify err msg for query result
  pkg/common/moerr/error.go
  pkg/frontend/query_result.go
  pkg/frontend/session.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/table_function/meta_scan.go
Labels: size/S

#8343 fix showCreateTable comment
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/dml/show/show.result
Labels: kind/bug, size/S

#8407 fix show create system view
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/bug, size/S

#8435 Fix planner logic of non-equi join conditions
  pkg/sql/plan/join_order.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#8434 Fix 8423
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#8433 txn: dn service integration lock service
  pkg/dnservice/cfg.go
  pkg/dnservice/store.go
  pkg/dnservice/store_heartbeat.go
  pkg/lockservice/lock_table_allocator.go
  pkg/txn/service/service.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_cn_handler_test.go
  pkg/txn/service/service_testutil.go
Labels: kind/feature, size/M

#8410 Count the number of rows of returned execution results
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/schema.go
Labels: kind/feature, size/S

#8437 morpc: fix data race
  pkg/common/morpc/backend.go
Labels: kind/bug, size/XS

#8409 Add s3 count
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/types.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/vm/process/analyze.go
  pkg/vm/process/types.go
  proto/plan.proto
Labels: kind/feature, size/M

#8441 lockservice: fix TestCheckTimeoutServiceTask
  pkg/lockservice/lock_table_allocator_test.go
Labels: size/S, kind/test-ci

#8443 fix wrong role
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/bug, size/S

#8419 Writer add log info&warn
  pkg/objectio/writer.go
  pkg/vm/engine/tae/dataio/blockio/reader.go
  pkg/vm/engine/tae/dataio/blockio/writer.go
Labels: kind/bug, size/S

#8413 CI: fix the html generate error
  .github/workflows/coverage_pr.yml
  .github/workflows/e2e-compose.yml
Labels: size/XS, kind/test-ci

#8447 lockservice: return locktable bind if lock added
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
Labels: kind/feature, size/S

#8452 morpc: fix missing notify in handle stopWriteC
  pkg/common/morpc/backend.go
Labels: kind/bug, size/XS

#8425 perfcounter: optimizations
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/debug.go
  cmd/mo-service/launch.go
  cmd/mo-service/main.go
  pkg/cnservice/distributed_tae.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/perfcounter/context.go
  pkg/perfcounter/counter_set.go
  pkg/perfcounter/http.go
  pkg/perfcounter/http_test.go
  pkg/perfcounter/update.go
  pkg/perfcounter/update_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/partition_state.go
  pkg/vm/pipeline/pipeline.go
Labels: kind/enhancement, size/M

#8446 cnservice: intergration lockservice
  pkg/cnservice/server.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/types.go
  pkg/common/runtime/types.go
  pkg/lockservice/cfg.go
  pkg/lockservice/cfg_test.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
Labels: kind/feature, size/S

#8404 fix show create cluster table
  pkg/sql/plan/build_show.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/tenant/clustertable4.result
  test/distributed/cases/tenant/clustertable4.sql
Labels: kind/bug, size/S

#8346 Modify the absolute link of doc url
  README.md
  README_CN.md
Labels: kind/documentation, size/XS

#8448 scan log tail only when there are subscriptions
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: kind/enhancement, size/S

#8418 remove unused code
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/mo_dump.go
Labels: size/XXL, kind/refactor

#8453 Removing unnecessary error messages to ensure that real errors are th…
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergetop/top.go
Labels: kind/bug, size/S

#8458 Hide access key for sql record
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/S

#8466 close morpc stream when post-cleaning logtail service session
  pkg/vm/engine/tae/logtail/service/session.go
Labels: kind/bug, size/S

#8455 fix UT TestReplay2 TestGCCatalog3
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/replay_test.go
Labels: kind/bug, size/XS

#8474 lockservice: add lock with batch rows or ranges support
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/log.go
  pkg/lockservice/service_test.go
  pkg/lockservice/waiter.go
Labels: kind/feature, size/M

#8444 Support alter table add/drop foreign key
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
Labels: kind/feature, size/M

#8475 Fix context timeout for s3 load
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/M

#8442 fix show columns for cluster table
  pkg/sql/util/util.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/tenant/clustertable2.sql
Labels: kind/bug, size/S

#8476 fileservice: add SubPath
  pkg/fileservice/config.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/path.go
  pkg/fileservice/path_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path.go
  pkg/fileservice/sub_path_test.go
Labels: kind/enhancement, size/M

#8485 fix some time-related fragile ut
  pkg/util/batchpipe/batch_pipe_test.go
Labels: size/M

#8490 SortKey may not be the primary key.
  pkg/vm/engine/tae/tables/jobs/flushblk.go
Labels: kind/bug, size/XS

#8491 fix foreach
  pkg/vm/engine/tae/containers/vecimpl.go
  pkg/vm/engine/tae/containers/vector_test.go
Labels: kind/bug, size/S

#8464 lockservice: fix multi cn panic
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
Labels: kind/bug, size/XS

#8472 fix buffer
  pkg/sql/colexec/s3util.go
Labels: kind/bug, size/S

#8482 util/export: remove refers to defines.ETLFileServiceName
  cmd/mo-service/main.go
  pkg/cnservice/server.go
  pkg/cnservice/server_task.go
  pkg/cnservice/types.go
  pkg/util/export/etl/csv.go
  pkg/util/export/etl/csv_test.go
  pkg/util/export/etl/tae.go
  pkg/util/export/etl/tae_test.go
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
Labels: kind/enhancement, size/M

#8500 fileservice: use ListObjects instead of ListObjectsV2 in s3
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/S

#8431 [Feature] DevStats Periodic Log Writer
  cmd/mo-service/config.go
  pkg/perfcounter/counter_logexporter.go
  pkg/perfcounter/counter_set.go
  pkg/perfcounter/http.go
  pkg/util/metric/config.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/mometric/metric_test.go
  pkg/util/metric/mometric/stats_log_writer.go
  pkg/util/metric/mometric/stats_log_writer_test.go
  pkg/util/metric/stats/counter.go
  pkg/util/metric/stats/counter_test.go
  pkg/util/metric/stats/doc.go
  pkg/util/metric/stats/registry.go
  pkg/util/metric/stats/registry_test.go
  pkg/util/metric/stats/types.go
Labels: kind/feature, size/L

#8492 fix cn runs completed tasks when it restarts
  pkg/taskservice/task_runner.go
Labels: kind/bug, size/XS

#8503 Fix dump query_result panic
  pkg/frontend/query_result.go
Labels: kind/bug, size/XS

#8505 Allow constant case-when expressions to be folded
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/rule/constant_fold.go
  test/distributed/cases/expression/case_when.result
  test/distributed/cases/expression/case_when.sql
Labels: kind/bug, size/S

#8487 lockservice: fix data race
  pkg/common/morpc/server.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
  pkg/pb/lock/lock.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: kind/bug, size/L

#8451 refine dispatch operator
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/operator.go
Labels: kind/bug, kind/enhancement, size/M

#8511 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, kind/test-ci

#8512 Cache support IOVector.NoCache
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/mem_cache.go
Labels: kind/feature, size/S

#8506 remove unused bytes.Buffer
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/moengine/block.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/M, kind/refactor, dn

#8514 set ETL Merge task run one task at a time
  pkg/util/export/merge.go
Labels: kind/enhancement, size/XS

#8489 fix decimal bug
  pkg/container/types/decimal.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function.go
Labels: kind/bug, size/S

#8509 Fixed a bug that cn node incorrectly release the dn memory
  pkg/container/vector/vector.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/order/order.go
Labels: kind/bug, size/S

#8519 fix locktable stmt
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
Labels: kind/enhancement, size/S

#8504 fileservice: naming fixes
  pkg/fileservice/cache.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memcachepolicy/clockpolicy/clock.go
  pkg/fileservice/objcache/clockobjcache/clock.go
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/fileservice/objcache/lruobjcache/lru_test.go
  pkg/fileservice/objcache/rc_value.go
  pkg/fileservice/objcache/releasable_value.go
Labels: kind/enhancement, size/M

#8520 add txnctx
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate2.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/output.go
  pkg/frontend/profiler.go
  pkg/frontend/protocol.go
  pkg/frontend/protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/enhancement, size/XXL

#8257 add dollar quote string
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: kind/enhancement, size/S

#8398 refactoring stats
  pkg/frontend/compiler_context.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/function/builtin/inside/internal_auto_increment_test.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/sql/plan/utils.go
  pkg/util/metric/test/cron_task_test.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
Labels: kind/enhancement, size/L

#8528 fix [#8499]
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/XS

#8518 lockservice: add timestamp for lock operation
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_test.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: kind/feature, size/L
