Repository matrixorigin/matrixone, pull requests merged in 2023-05, with the labels that each got.

#9218 support init subscription database
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/variables.go
  test/distributed/cases/tenant/init_pub.result
  test/distributed/cases/tenant/init_pub.sql
Labels: kind/feature, size/S

#9219 fix publishing system db bug
  pkg/frontend/authenticate.go
Labels: kind/bug, size/S

#9229 update zm to support some op and add related ut
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
Labels: size/L

#9225 Add comparison between two decimals with scales
  pkg/container/types/decimal.go
Labels: size/S

#9247 Add object meta cache
  cmd/mo-service/config.go
  cmd/mo-service/main.go
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  pkg/objectio/cache.go
  pkg/objectio/reader.go
  pkg/objectio/types.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, kind/feature, size/M

#9234 Add comparison between two tuples
  pkg/sql/plan/base_binder.go
Labels: kind/feature, size/M

#9233 fix subscription view error
  pkg/sql/plan/build_show.go
  test/distributed/cases/tenant/pub_sub.result
Labels: kind/bug, size/S

#9243 fileservice: fix DiskCache.Update
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/perfcounter/counter_set.go
Labels: kind/bug, size/S

#9239 fix publishing other tenant's database error
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  test/distributed/cases/tenant/init_pub.result
  test/distributed/cases/tenant/init_pub.sql
Labels: kind/bug, size/S

#9253 [disttae]: remove some useless and time-consuming code
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, kind/performance, size/XS, perf-tp

#9254 Add Location for Object's ColumnMeta
  pkg/objectio/writer.go
  pkg/vm/engine/tae/blockio/writer_test.go
Labels: kind/enhancement, size/S

#9263 [Enhancement]: refactoring stats
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/M

#9258 [disttae]: remove some time-consuming operations in Ranges
  pkg/vm/engine/disttae/hack.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/M, kind/performance, perf-tp

#9261 add scale in zonemap
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
Labels: size/M

#9264 Change the structure of BloomFilter in memory cache to []byte
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/objectio/versions.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
Labels: kind/enhancement, size/S

#9269 Fix CN delete s3 bug
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#9232 Reduce some info log to debug.
  pkg/frontend/cmd_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/types.go
  pkg/taskservice/task_runner.go
  pkg/util/batchpipe/batch_pipe.go
  pkg/util/export/batch_processor_test.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/interval.go
  pkg/vm/engine/tae/common/intervals.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/gc/manager.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/file.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/tables/functions.go
Labels: size/M, kind/refactor

#9227 fix subscribe non_existent tenant error
  pkg/frontend/authenticate.go
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/tenant/pub_sub.sql
Labels: kind/bug, size/S

#9228 fix subscribe itself error
  pkg/frontend/authenticate.go
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/tenant/pub_sub.sql
Labels: kind/bug, size/S

#9213 disttae: separate logtail replay codes to logtailreplay package
  CODEOWNERS
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/encode.go
  pkg/vm/engine/disttae/logtailreplay/encode_test.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_iterators.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_iterators_test.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/logtailreplay/utils.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/M

#9271 fix appendIds
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS

#9267 [Enhancement]: refactoring stats
  pkg/sql/plan/join_order.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/S

#9256 fix bug: use viewDef as varchar not blob
  pkg/catalog/types.go
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/bug, size/XS

#9266 allow converting string to json and json to string
  pkg/sql/plan/function/type_check.go
  test/distributed/cases/ddl/json_type.result
Labels: kind/bug, size/XS

#9279 IndexCahce caches the BloomFilter of the entire object
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
Labels: kind/enhancement, size/S

#9281 [refactor] hakeeper: Change the behavior of updating cn label.
  pkg/clusterservice/cluster.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  proto/logservice.proto
Labels: size/S, kind/refactor

#9286 [Performance]: Predicate transitivity and join order [step 1]
  pkg/sql/plan/agg_pushdown_pullup.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/M

#9291 Reduce heap allocation in vector.ToConst
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/projection/projection.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/enhancement, size/M

#9280 morpc: support close conn in stream
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/examples/stream/main.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/txn/rpc/sender.go
  pkg/vm/engine/tae/logtail/service/client.go
Labels: kind/feature, size/M

#9257 [Refactor] : Replacing FS IOEntry `Object` with `ByteSlice` for Zero-Copy
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/objcache/clockobjcache/clock.go
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/fileservice/objcache/lruobjcache/lru_test.go
  pkg/fileservice/objcache/rc_value.go
  pkg/fileservice/objcache/releasable_value.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/model/index.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
Labels: kind/enhancement, kind/api-change, size/L

#9224 change txn behavior
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/plan/function/builtin/ctl/cmd_flush.go
  pkg/sql/plan/function/builtin/ctl/ctl.go
  pkg/sql/plan/function/builtin/ctl/table_stat.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/function/builtin/seq/currval.go
  pkg/sql/plan/function/builtin/seq/currval_test.go
  pkg/sql/plan/function/builtin/seq/nextval.go
  pkg/sql/plan/function/builtin/seq/seq_util.go
  pkg/sql/plan/function/builtin/seq/setval.go
  pkg/sql/plan/function/builtin/seq/setval_test.go
  pkg/sql/plan/set_binder.go
  pkg/sql/plan/types.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/catalog_test.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare_transaction.result
  test/distributed/cases/sequence/create_sequence.sql
  test/distributed/cases/sequence/sequence.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/table/drop_table2.result
  test/distributed/cases/table/drop_table2.sql
  test/distributed/cases/table/truncate_table_3.result
  test/distributed/cases/table/truncate_table_3.sql
  test/distributed/cases/table/truncate_table_4.result
  test/distributed/cases/table/truncate_table_4.sql
  test/distributed/cases/transaction/atomicity_1.result
  test/distributed/cases/transaction/autocommit.result
  test/distributed/cases/transaction/autocommit_1.result
  test/distributed/cases/transaction/autocommit_1.sql
  test/distributed/cases/transaction/autocommit_atomicity.result
  test/distributed/cases/transaction/autocommit_isolation.result
  test/distributed/cases/transaction/autocommit_isolation_1.result
  test/distributed/cases/transaction/drop_table_truncate.result
  test/distributed/cases/transaction/drop_table_truncate.sql
  test/distributed/cases/transaction/isolation.result
  test/distributed/cases/transaction/isolation_1.result
Labels: kind/enhancement, size/XL

#9295 use prefetch for insert request when handle pre commit write
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/S

#9300 [bug] proxy: allow sys tenant login when there are no empty-label cn …
  pkg/proxy/label_info.go
  pkg/proxy/label_info_test.go
  pkg/proxy/router.go
  pkg/proxy/router_test.go
Labels: kind/bug, size/S

#9294 Remove the overhead of permission validation and remove some unnecess…
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/zz_accesscontrol/create_role.result
Labels: kind/enhancement, size/M

#9297 fix bvt: scan limited-content to verify sql query.
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
Labels: kind/bug, size/XS

#9303 add one column to mo_stored_procedure
  pkg/frontend/authenticate.go
Labels: kind/bug, size/XS

#9242 fix col default error display
  pkg/sql/plan/build_util.go
  test/distributed/cases/function/func_datetime_dayofyear.result
  test/distributed/cases/function/func_datetime_month.result
  test/distributed/cases/function/func_datetime_weekday.result
  test/distributed/cases/function/func_datetime_year.result
  test/distributed/cases/function/func_math_floor.result
  test/distributed/cases/function/func_math_pi.result
Labels: kind/bug, size/S

#9298 some code update to disttae
  pkg/catalog/types.go
  pkg/objectio/id.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/L

#9290 pipeline hung issue
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, kind/enhancement, size/M

#9284 fileservice: fix TestDiskCacheWriteAgain
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
Labels: kind/bug, size/S

#9092 add bvt case
  test/distributed/cases/publication_subscription/publish_subscribe.result
  test/distributed/cases/publication_subscription/publish_subscribe.sql
Labels: size/XL, kind/test-ci

#9202 fileservice: add FileServiceCounterSet.Memory.Available
  pkg/fileservice/cache.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/objcache/clockobjcache/clock.go
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/perfcounter/counter_set.go
  pkg/util/metric/stats/counter.go
  pkg/vm/engine/tae/model/index.go
Labels: kind/enhancement, size/S

#9306 fix colexec operator bug will cause memory leak
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergedelete/mergedelete.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/restrict/restrict.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/update/update.go
Labels: kind/bug, size/S

#9305 Remove bvt tag 7772
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/XS

#9315 morpc: fix ping not work
  pkg/common/morpc/server.go
Labels: kind/bug, size/S

#9317 fileservice: implement retryableReader
  pkg/fileservice/retryable_reader.go
  pkg/fileservice/retryable_reader_test.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/M

#9308 optimize eval filter expr by zonemap
  pkg/objectio/meta.go
  pkg/objectio/types.go
  pkg/sql/colexec/expr_eval.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
Labels: kind/enhancement, size/L, kind/performance, perf-tp

#9319 Unset Block's Col Ndv
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
Labels: kind/bug, kind/enhancement, size/XS

#9322 add json not_equal
  pkg/sql/plan/function/operators.go
Labels: kind/bug, size/XS

#9311 [Performance]: Predicate transitivity and join order [step 2]
  pkg/sql/plan/join_order.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/M

#8543 support parallel load with compressed file
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/plan/build_load.go
  pkg/testutil/testengine/testdata.go
  pkg/testutil/testengine/testengine.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/parallel.txt.gz
Labels: kind/enhancement, size/L

#9313 skip check json when valid
  pkg/util/export/etl/tae.go
Labels: kind/bug, size/S

#9320 optimize DoPrecommitDedupByPK
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M

#9324 fix zm reading in calc stats
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#9318 fix stats for dynamic parameter
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S

#9327 improve load performance
  pkg/sql/colexec/external/external.go
Labels: size/XS

#9307 dump batch
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#9097 show procedure, creater field and type typo.
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result.go
  pkg/frontend/stmt_kind.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
Labels: kind/bug, size/XXL

#9312 Rename upload artifact file
  .github/workflows/coverage_pr.yml
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e.yml
  .github/workflows/e2e_with_proxy.yml
  .github/workflows/e2e_with_push_model.yml
  .github/workflows/e2e_with_race.yml
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#9329 fix stats selectivity
  pkg/sql/plan/stats.go
Labels: kind/bug, size/XS

#9328 nocopy nulls.
  pkg/common/bitmap/bitmap.go
  pkg/container/nulls/nulls.go
  pkg/container/vector/vector.go
Labels: size/S

#9334 cnclient: fix data race
  pkg/cnservice/cnclient/client.go
Labels: kind/bug, size/S

#9337 logtailreplay: add PartitionState.BlockVisible
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/M

#9342 optimize filter execution
  pkg/sql/colexec/restrict/restrict.go
Labels: kind/enhancement, size/S

#9346 add bvt case
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
Labels: size/M, kind/test-ci

#9345 Don't allow a quantified subquery's left operand to be a subquery
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/utils.go
  test/distributed/cases/subquery/subquery-with-in.result
Labels: kind/bug, size/S

#9351 Fix tiny bug for insert op
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/M

#9349 add ownership privilege to role
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/privilege/create_user_default_role.sql
  test/distributed/cases/tenant/privilege/owner.result
  test/distributed/cases/tenant/privilege/owner.sql
  test/distributed/cases/zz_accesscontrol/create_role.result
  test/distributed/cases/zz_accesscontrol/use_role.result
Labels: kind/feature, size/M

#9357 fileservice: let caller of Pool.Get allocates
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/pool.go
  pkg/fileservice/pool_test.go
  pkg/fileservice/profile.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/S

#9341 reduce mem alloc while do etl write
  pkg/config/configuration.go
  pkg/util/export/batch_processor.go
  pkg/util/export/etl/csv.go
  pkg/util/export/etl/tae.go
  pkg/util/export/etl/tae_test.go
  pkg/util/export/merge_test.go
  pkg/util/export/observability/logs/log.go
  pkg/util/export/observability/metrics/metric.go
  pkg/util/export/observability/schema.go
  pkg/util/export/observability/trace/span.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/export/table/type.go
  pkg/util/export/writer_factory.go
  pkg/util/metric/mometric/metric_collector.go
  pkg/util/metric/mometric/metric_collector_test.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/report_error.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/schema.go
  pkg/util/trace/trace.go
Labels: kind/bug, size/XL

#9352 Add Reader pool
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/prefetch.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: kind/api-change, size/S

#9365 prepare seg deletion event
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/utils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/enhancement, size/M

#9371 change timeout
  pkg/cnservice/types.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/taskservice/task_runner.go
Labels: kind/enhancement, size/XS

#9372 Refactor insert for prepare statement
  go.mod
  go.sum
  pkg/frontend/computation_wrapper.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/visit_plan_rule.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/bug, size/L

#9373 add system variables net_buffer_length
  pkg/frontend/variables.go
Labels: kind/bug, size/XS

#9375 [Enhancement]: Hashbuild operator benefit from NOT NULL restriction
  pkg/container/types/types.go
  pkg/container/types/types_test.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/compile/compile.go
Labels: kind/enhancement, size/S

#9367 refactoring stats
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/M

#9370 fix visit table, visit db
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#9358 modify cnList with multi-CN
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#9359 fix zonemap seqnum
  pkg/objectio/block.go
  pkg/objectio/funcs.go
  pkg/objectio/meta.go
  pkg/objectio/types.go
  pkg/objectio/writer_test.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/types.go
  pkg/vm/engine/tae/blockio/writer_test.go
Labels: kind/bug, kind/enhancement, size/M

#9384 Add `RemoteAddress` for `morpc.ClientSession` in order to identify morpc stream client
  pkg/common/morpc/server.go
  pkg/common/morpc/types.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/enhancement, size/S

#9383 optimize sysbench insert performance
  pkg/catalog/catalog.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/encode.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/bug, kind/enhancement, size/S, kind/performance, perf-tp

#9387 add seg del in ckp
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/enhancement, size/M

#9390 Resize multi-block hash table in place
  pkg/common/hashmap/iterator.go
  pkg/container/hashtable/bucket.go
  pkg/container/hashtable/hash.go
  pkg/container/hashtable/hash_amd64.go
  pkg/container/hashtable/hash_amd64.s
  pkg/container/hashtable/hash_arm64.go
  pkg/container/hashtable/hash_arm64.s
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: kind/enhancement, size/M

#9391 fix multi-thread sequence bug
  pkg/sql/plan/function/builtin/seq/nextval.go
Labels: kind/bug, size/XS

#9289 row constructor
  test/distributed/cases/operator/row_constructor.result
  test/distributed/cases/operator/row_constructor.sql
Labels: size/L

#9389 support grant lower rank privilege when has all or ownership priv
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  test/distributed/cases/tenant/privilege/owner.result
  test/distributed/cases/tenant/privilege/owner.sql
  test/distributed/cases/tenant/privilege/role5_inherit.result
  test/distributed/cases/zz_accesscontrol/grant_privs_role.result
  test/distributed/cases/zz_accesscontrol/revoke_privs_role.result
Labels: kind/feature, size/M

#9331 finish pipeline for inner&right join if hashmap is empty to improve performance
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/semi/join.go
Labels: kind/enhancement, size/S

#9301 [feat] determine the range of CNs for pipeline.
  pkg/frontend/computation_wrapper.go
  pkg/frontend/session.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/types.go
Labels: kind/feature, size/M

#9382 change error code of resultscan
  pkg/frontend/compiler_context.go
  pkg/frontend/query_result.go
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: kind/bug, size/S

#9401 Add blockio.LoadColumns without NewObjectReader
  pkg/objectio/funcs.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/enhancement, size/M

#9386 add log for init ts
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/waterline.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/XS

#9396 fix kill in single cn
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_test.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/M

#9402 only support provider = 'minio'
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#9404 Remove MO unnecessary NewObjetcReader
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/S

#9392 mo_log_date
  test/distributed/cases/function/mo_log_date.result
  test/distributed/cases/function/mo_log_date.sql
Labels: size/L

#9362 feat: introduce external plugin support in proxy
  .gitignore
  pkg/pb/plan/plan.pb.go
  pkg/pb/plugin/plugin.go
  pkg/pb/plugin/plugin.pb.go
  pkg/pb/plugin/plugin_test.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/config.go
  pkg/proxy/config_test.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handshake.go
  pkg/proxy/label_info.go
  pkg/proxy/plugin.go
  pkg/proxy/plugin_test.go
  pkg/proxy/rebalancer_test.go
  pkg/proxy/router.go
  pkg/proxy/router_test.go
  pkg/proxy/server.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/tunnel_test.go
  proto/plugin.proto
Labels: kind/feature, size/L

#9414 some code update to dn vector
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/functions_test.go
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: size/L, kind/refactor

#9412 fix publication bvt test error
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/tenant/pub_sub.sql
Labels: kind/bug, size/XS

#9407 Serialize plan to json alloc much
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/explain/init.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/explain/marshal_query_test.go
  pkg/sql/plan/explain/types.go
Labels: kind/bug, kind/enhancement, size/L

#9417 filter out empty batch in ckp
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/enhancement, size/S

#9420 add error msg, remove panic msg
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/XS

#9421 correct docker image default startup args
  optools/images/Dockerfile
Labels: kind/bug, size/XS

#9422 reduce creating small objects
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/segment.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M, perf-tp

#9416 remove cloud-nonuser tag
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/parsers/sqlparse_test.go
  test/distributed/cases/log/query_version.result
  test/distributed/cases/log/query_version.sql
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: kind/bug, size/L

#9418 optimize replay
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/wal/checkpoint.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
  pkg/vm/engine/tae/wal/wal_test.go
  pkg/vm/engine/tae/wal/walinfo.go
Labels: kind/enhancement, size/M

#9423 LoadColumns need to use metacache
  pkg/vm/engine/tae/blockio/funcs.go
Labels: kind/enhancement, size/XS

#9430 Fix dn panic
  pkg/pb/txn/txn.go
Labels: kind/bug, size/S

#9403 support dropdatabase and droptable for object owner
  pkg/frontend/authenticate.go
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/privilege/owner1.result
  test/distributed/cases/tenant/privilege/owner1.sql
  test/distributed/cases/zz_accesscontrol/revoke_privs_role.result
Labels: kind/feature, size/M

#9408 alter table name
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/node.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  proto/api.proto
Labels: kind/feature, size/L

#9431 optimize replay
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/file.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/type.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go
  pkg/vm/engine/tae/logstore/driver/entry/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/load.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: size/M

#9432 Add object's bloom filter
  pkg/objectio/constructors.go
  pkg/objectio/meta.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
Labels: kind/feature, size/M

#9338 [feat]: kill connected session if account suspended or dropped.
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/conn_manager.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/plugin_test.go
  pkg/proxy/router.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/tunnel.go
  pkg/proxy/util.go
  test/distributed/cases/dml/insert/insert.result
  test/distributed/cases/dml/insert/insert.test
Labels: kind/feature, size/XL

#9437 optimize DoPrecommitDedupByPK
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/S

#9440 optimize dn dedup
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M, kind/performance, perf-tp

#9413 Rewrite pool, to be a little bit simpler.
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/pool.go
  pkg/fileservice/pool_test.go
  pkg/fileservice/profile.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/M, kind/refactor

#9354 Change nulls and bitmap ptr to struct.
  pkg/common/bitmap/bitmap.go
  pkg/common/bitmap/bitmap_test.go
  pkg/common/bitmap/types.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/container/nulls/nulls.go
  pkg/container/nulls/nulls_test.go
  pkg/container/types/decimal_test.go
  pkg/container/vector/functionTools.go
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/order/order.go
  pkg/sql/plan/function/builtin/binary/endswith_test.go
  pkg/sql/plan/function/builtin/binary/startswith_test.go
  pkg/sql/plan/function/builtin/multi/ceil_test.go
  pkg/sql/plan/function/builtin/multi/field.go
  pkg/sql/plan/function/builtin/multi/floor_test.go
  pkg/sql/plan/function/builtin/multi/from_unixtime_test.go
  pkg/sql/plan/function/builtin/multi/pi_test.go
  pkg/sql/plan/function/builtin/multi/round_test.go
  pkg/sql/plan/function/builtin/unary/abs_test.go
  pkg/sql/plan/function/builtin/unary/ltrim_test.go
  pkg/sql/plan/function/operator/case_when.go
  pkg/sql/plan/function/operator/coalesce.go
  pkg/testutil/util_function.go
  pkg/testutil/util_new.go
  pkg/vectorize/logical/logical_test.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector.go
  test/distributed/cases/function/function_mid.result
  test/distributed/cases/function/function_substring_index.result
Labels: kind/enhancement, size/XL

#9438 fix logtail hung in close stream
  pkg/vm/engine/tae/logtail/service/client.go
Labels: kind/bug, size/XS

#9444 fix the output of explain
  pkg/sql/plan/explain/explain_expr.go
Labels: kind/bug, size/XS

#9441 Avoid redundant allocations when filtering zonemaps
  pkg/container/vector/vector.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  proto/plan.proto
Labels: kind/enhancement, size/M

#9000 [Enhancement]: optimize bucket group for tpch q18
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/M

#9451 Set Primary Key Ndv
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
Labels: kind/bug, size/S

#9435 Solve external table file path error
  pkg/sql/compile/debugTools.go
  pkg/sql/plan/external.go
Labels: kind/bug, size/S

#9449 add pk in logtail delete
  pkg/sql/plan/build_ddl.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/feature, size/M

#9448 [bug] proxy: support the Ctrl+C operation to kill query.
  pkg/frontend/routine_manager.go
  pkg/frontend/server.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/conn_manager.go
  pkg/proxy/handler.go
  pkg/proxy/label_info_test.go
  pkg/proxy/router.go
  pkg/proxy/server_conn_test.go
Labels: kind/bug, size/M

#9446 fix mo_dump bug
  cmd/mo-dump/main.go
Labels: kind/bug, size/S

#9462 remove one dependency of blockInfos
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/refactor

#9460 refactoring stats
  pkg/frontend/compiler_context.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/external.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/function/builtin/inside/internal_auto_increment_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/sql/plan/utils.go
  pkg/util/metric/test/cron_task_test.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#9468 optimize dn dedup
  pkg/objectio/meta.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/indexwrapper/bfnode.go
  pkg/vm/engine/tae/tables/indexwrapper/immutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/indexwrapper/types.go
  pkg/vm/engine/tae/tables/indexwrapper/zonemapnode.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M, dn, perf-tp

#9480 Use Int64HashMap in group operator as much as possible
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/compile/compile.go
Labels: kind/enhancement, size/M

#9477 refactoring stats
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/M

#9471 Update go.mod
  go.mod
  go.sum
  pkg/logutil/api.go
  pkg/sql/colexec/external/external.go
Labels: size/L

#9489 Update api design in order to reduce unnecessary heap allocation;
  pkg/container/types/rowid.go
  pkg/container/types/rowid_test.go
  pkg/objectio/id_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/model/codec.go
Labels: kind/enhancement, size/M

#9503 [refactor] proxy: change the action of drop account.
  pkg/proxy/client_conn.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/ppv2.go
  pkg/proxy/ppv2_test.go
  pkg/proxy/server.go
  pkg/proxy/tunnel.go
Labels: size/M, kind/refactor

#9488 fix dup tables in truncating table
  pkg/vm/engine/disttae/cache/catalog.go
Labels: size/S

#9457 [bug] logserivce: too many truncation logs.
  pkg/logservice/store.go
  pkg/logservice/truncation.go
Labels: kind/bug, size/S

#9490 fix truncate error msg
  pkg/vm/engine/tae/txn/txnimpl/database.go
Labels: kind/bug, size/XS

#9508 fix a bug that shuffle group output wrong results on multi cn occasionally
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: kind/bug, size/M

#9475 disttae: ensure Unlock will be called when panic
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/M

#9497 Enable to filter zonemaps by IN predicates
  pkg/frontend/test/engine_mock.go
  pkg/sql/colexec/expr_eval.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/function/operators.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/types.go
Labels: kind/feature, size/M

#9433 fix bvt case remove mo-tester exec mo_ctl records
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/S

#9445 txn: fix determine txn snapshot ts
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
Labels: kind/bug, size/XS

#9500 refactoring stats
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/S

#9029 sp_exec impl
  pkg/defines/type.go
  pkg/frontend/authenticate.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/plsql_interpreter.go
  pkg/sql/parsers/tree/branch.go
  pkg/sql/parsers/tree/compound.go
  pkg/sql/parsers/tree/procedure.go
  pkg/sql/plan/base_binder.go
  test/distributed/cases/procedure/procedure.result
  test/distributed/cases/procedure/procedure.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: kind/feature, size/XL

#9496 remove unnecessary non pk indexes
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M, perf-tp

#9518 morpc: add lock for stream send
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/server_test.go
Labels: kind/bug, size/S

#9482 optimize replay
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/file.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/type.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/vfile.go
  pkg/vm/engine/tae/logstore/driver/entry/entry.go
  pkg/vm/engine/tae/logstore/driver/entry/mock.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/load.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: size/L

#9361 Merge two steps into one when change the format of json
  pkg/container/bytejson/bytejson.go
  pkg/util/export/etl/tae.go
Labels: kind/bug, size/S

#9522 using Rowid.Decode to replace old duplicate implementation
  pkg/objectio/utils.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/model/codec.go
  pkg/vm/engine/tae/model/preparer.go
  pkg/vm/engine/tae/model/transfer_test.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/M

#9469 txn: adjust concurrency model
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-with-proxy/cn1.toml
  etc/launch-with-proxy/cn2.toml
  pkg/cnservice/server.go
  pkg/common/morpc/cfg.go
  pkg/common/morpc/codec_header.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/examples/pingpong/main.go
  pkg/common/morpc/examples/stream/main.go
  pkg/common/morpc/handler.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/dnservice/cfg.go
  pkg/dnservice/store.go
  pkg/lockservice/rpc.go
  pkg/logservice/service.go
  pkg/proxy/plugin_test.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/sender_test.go
  pkg/txn/rpc/server.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/enhancement, size/M
