Repository matrixorigin/matrixone, pull requests merged in 2023-12, with the labels that each got.

#13134 fix commit an active transaction when drop database
  pkg/frontend/authenticate.go
  pkg/frontend/stmt_kind.go
Labels: kind/bug, size/S

#13138 [enhancement] txnClient: it waits until txn client is in normal state.
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
Labels: kind/bug, size/M, kind/enhancement

#13153 CI: add always() to collect trace in ssb/tpch
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13019 [enhancement] status: add lock status and dump status info to s3.
  pkg/cnservice/server.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/util/address/address.go
  pkg/util/profile/profile.go
  pkg/util/status/lock.go
  pkg/util/status/server.go
  pkg/util/status/status.go
  pkg/util/status/txn_client.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
Labels: size/M, kind/enhancement

#13144 make lock op can deal with const null
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/bug, size/S

#13158 CI: remove unuse yaml and add annotation for mergerun mo
  optools/mo_checkin_regression/mo_checkin_regression.yaml
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci

#13157 [BugFix]: Deep Copy missing parts + Panic suppression + Adding a debug log.
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/deepcopy.go
Labels: size/S

#13140 delete bvt test case issue tag
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
Labels: kind/bug, size/XS

#13165 make lock op can deal with const null (#13143)
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/bug, size/S

#13166 some pipeline cannot execute remotely
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/types.go
Labels: kind/bug, size/S

#13162 donot check pk dup in some case
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS

#13161 CI: sync ci to 1.1-dev
  .github/mergify.yml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  optools/mo_checkin_regression/mo_checkin_regression.yaml
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci

#13105 [enhancement] proxy: add metrics and dashboard.
  pkg/proxy/client_conn.go
  pkg/proxy/handler.go
  pkg/proxy/plugin.go
  pkg/proxy/rebalancer.go
  pkg/proxy/router.go
  pkg/proxy/scaling.go
  pkg/proxy/tunnel.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/proxy.go
Labels: size/M, kind/enhancement

#13168 remove unreachable code
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/types.go
Labels: size/M, kind/refactor

#13174 adding ranges selectivity metrics
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/feature, size/M

#13129 Add method version check in lock rpc and txn rpc
  pkg/cacheservice/cache_service_test.go
  pkg/cacheservice/client/cache_client.go
  pkg/cnservice/server.go
  pkg/common/runtime/runtime.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service_remote.go
  pkg/logservice/service.go
  pkg/pb/cache/cache.go
  pkg/pb/query/query.go
  pkg/queryservice/query_service.go
  pkg/queryservice/query_service_test.go
  pkg/sql/plan/function/ctl/cmd_rpc_version_test.go
  pkg/tnservice/store.go
  pkg/txn/rpc/server.go
  pkg/txn/rpc/server_test.go
Labels: kind/feature, size/M

#13117 Fix mo stream bugs
  pkg/frontend/connector.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/explain/explain_node.go
  pkg/stream/adapter/kafka/adapter.go
  pkg/stream/adapter/kafka/adapter_test.go
  pkg/stream/connector/connector.go
  pkg/stream/connector/converter.go
  pkg/stream/connector/options.go
  pkg/stream/connector/options_test.go
Labels: kind/bug, size/L

#13139 cherry-pick PR 13101 to 1.1-dev: [BugFix]:`Precision` issue for Cosine Similarity+ `Except` for VECTOR…
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/list_operator.go
  pkg/vectorize/moarray/external.go
  pkg/vectorize/moarray/external_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/M

#13137 Fix 12617
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/plan/build_load.go
Labels: kind/bug, size/S

#13184 [cherry-pick] some pipeline cannot execute remotely (#13166)
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/types.go
Labels: kind/bug, size/S

#13169 don't check pk dup in some case (#13162)
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS

#13062 [Performance]: tune ap cache policy
  pkg/objectio/funcs.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/read.go
Labels: size/S, kind/enhancement

#13209 add max retry times for allocate increment value
  pkg/incrservice/column_cache.go
Labels: kind/bug, size/S

#13136 collect block deletes by primary key
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/M

#13223 [cherry-pick] #13222 fix a remote run bug; removed unused codes.
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#13228 fix race in ut
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
Labels: kind/bug, size/XS

#13218 fix wrong sysblock
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: size/S

#13231 Add more metric for build plan
  pkg/frontend/compiler_context.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/plan/stats.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#13222 fix a remote run bug will suppress the error message
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#13237 fix agg function panic
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#13202 CI: add timeout for create tenant
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13227 add max retry times for allocator increment value to 1.0
  pkg/incrservice/column_cache.go
Labels: kind/bug, size/S

#13249 fileservice: add ObjectStorageArguments.CertFiles
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-compose/config/tn.toml
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
Labels: size/M

#13225 fix can't get cluster table in mo dev
  pkg/frontend/authenticate.go
  pkg/frontend/variables.go
  pkg/sql/plan/function/func_mo.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/table/cluster_table/cluster_table.sql
Labels: kind/bug, size/S

#13226 add max retry times for allocator increment value to 1.1
  pkg/incrservice/column_cache.go
Labels: kind/bug, size/S

#13191 add a session variable to control txn log
  pkg/frontend/session_test.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/variables.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
  test/distributed/cases/database/system_variables.result
Labels: kind/feature, size/M

#13244 [enhancement] system: support resource in cgroup v2.
  go.mod
  go.sum
  pkg/common/system/system.go
  pkg/sql/plan/function/func_unary.go
Labels: size/M, kind/enhancement

#13241 Remove object's bloom filter
  pkg/vm/engine/tae/blockio/writer.go
Labels: size/S, kind/enhancement

#13253 slow down prefetch speed for 1.0-dev
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/XS

#13242 remove unused code
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/dbutils/throttle.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: size/M, kind/refactor

#13261 CI: Sync ci 1.0 dev
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13262 CI: Sync ci to 1.1 dev
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13255 add local and k8s metrics dashboard create test
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
Labels: size/M

#13243 Optimize reader for tp scenario 2
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement

#13233 Optimize reader for tp scenario 1
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement

#13263 determine degree of parallelism for scan in runtime
  pkg/sql/compile/scope.go
Labels: size/S, kind/enhancement

#13265 [cherry-pick] pr #13295 Fix the the bug of concurrently reading channel
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/mock_morpc/Makefile
  pkg/common/morpc/mock_morpc/types_mock.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: size/XL

#13266 [cherry-pick] pr #13295 Fix the the bug of concurrently reading channel
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/mock_morpc/Makefile
  pkg/common/morpc/mock_morpc/types_mock.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/bug, size/XL

#13267 upgrade upgrader
  pkg/cnservice/upgrader/upgrade_sql.go
  pkg/cnservice/upgrader/upgrader.go
Labels: size/S, kind/enhancement

#13240 fix bug: add more title/label for BuildJsonPlan
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
Labels: kind/bug, size/M

#13269 Add more metric for debug #13045
  pkg/sql/compile/compile.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_replace.go
  pkg/sql/plan/build_update.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/engine.go
Labels: kind/bug, size/S

#13230 make shared table segregation by tenant in lock to 1.1
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_forward_test.go
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter_events.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/txn/client/operator_test.go
  pkg/txn/service/service_cn_handler_test.go
Labels: kind/bug, size/M

#13264 [enhancement] system: support resource in cgroup v2.
  go.mod
  go.sum
  pkg/common/system/system.go
  pkg/sql/plan/function/func_unary.go
Labels: kind/bug, size/M, kind/enhancement

#13280 Revert "fix a remote run bug will suppress the error message"
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: size/S

#13106 [enhancement] proxy: add metrics and dashboard.
  pkg/proxy/client_conn.go
  pkg/proxy/handler.go
  pkg/proxy/plugin.go
  pkg/proxy/rebalancer.go
  pkg/proxy/router.go
  pkg/proxy/scaling.go
  pkg/proxy/tunnel.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/proxy.go
Labels: size/M, kind/enhancement

#13290 [cherry-pick] #13289 fix a remote run bug. fix bugs about clean methods of operators.
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/intersect/types.go
  pkg/sql/colexec/mergeorder/types.go
  pkg/sql/colexec/mergerecursive/types.go
  pkg/sql/colexec/minus/types.go
  pkg/sql/colexec/partition/types.go
  pkg/sql/colexec/shuffle/types.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/M

#13321 Revert "Fix the the bug of concurrently reading channel (#13259)"
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/mock_morpc/Makefile
  pkg/common/morpc/mock_morpc/types_mock.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/bug, size/XL

#13320 Revert "Fix the the bug of concurrently reading channel (#13259)"
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/mock_morpc/Makefile
  pkg/common/morpc/mock_morpc/types_mock.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/common/morpc/types.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/txn/rpc/server_test.go
  pkg/vm/engine/tae/logtail/service/session_test.go
Labels: kind/bug, size/XL

#13248 add leak metrics to 1.0
  pkg/cnservice/server.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: kind/bug, size/XS

#13308 Fix stopped checkpoint 1.0
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: size/S

#13312 cherry pick the db conn pool fix to 1.0
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/merge.go
Labels: kind/bug, size/S

#13309 sync 1.0 collect block deletes by primary key (#13136)
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/M

#13319 sync to 1.0: fix internal show accounts result empty
  pkg/frontend/show_account.go
Labels: kind/bug, size/XS

#13324 fileservice: pick changes to 1.0
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs.go
Labels: size/M, kind/enhancement

#13332 Revert "sync 1.0 collect block deletes by primary key (#13136) (#13309)"
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#13339 Fix the the bug of concurrently reading channel
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
Labels: kind/bug, size/XS

#13340 Fix the the bug of concurrently reading channel
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
Labels: kind/bug, size/XS

#13343 Resolve the issue of inconsistent create account results-1.0-dev
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/L

#13346 fix lock service concurrent creating lock table to 1.0
  pkg/lockservice/service.go
Labels: kind/bug, size/S

#13347 fix lock service concurrent creating lock table to 1.1
  pkg/lockservice/service.go
Labels: kind/bug, size/S

#13188 pick: fix DATA RACE
  pkg/util/errutil/context.go
  pkg/util/trace/config.go
Labels: kind/bug, size/S

#13247 add leak metrics to 1.1
  pkg/cnservice/server.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: kind/bug, size/XS

#13256 fix can't get cluster table in mo dev (1.1-dev)
  pkg/frontend/authenticate.go
  pkg/frontend/variables.go
  pkg/sql/plan/function/func_mo.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/table/cluster_table/cluster_table.sql
Labels: kind/bug, size/S

#13275 removed unused codes. fix a bug about remote run.
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scopeRemoteRunTypes_test.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/M, kind/refactor

#13283 [BugFix]: Lock original table during create index.
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#13246 add leak metrics
  pkg/cnservice/server.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: size/XS, kind/enhancement

#13206 make shared table segregation by tenant in lock
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_forward_test.go
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter_events.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/txn/client/operator_test.go
  pkg/txn/service/service_cn_handler_test.go
Labels: kind/bug, size/M

#13120 [perf] improve delete from table without where & limit
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_dml_util.go
  proto/plan.proto
Labels: size/S, kind/enhancement

#13349 Add debug log of bmsql_district
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/S, kind/enhancement

#13277 [cherry-pick] #13275 removed unused codes. fix a bug about remote run.
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scopeRemoteRunTypes_test.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/M, kind/refactor

#13284 adding the hidden col size when do `mo_table_size`
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/function/builtin.result
  test/distributed/cases/mo_cloud/mo_cloud.result
Labels: kind/bug, size/S

#13278 pick: revert MOCollector default worker num
  pkg/config/configuration.go
Labels: kind/bug, size/XS

#13300 fix bug: throw incorrect err type
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#13281 fix bug: add more title/label for BuildJsonPlan (#13240)
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
Labels: kind/bug, size/M

#13276 revert MOCollector default worker num
  pkg/config/configuration.go
Labels: kind/bug, size/XS

#13239 fileservice: add ObjectStorageArguments.CertFiles
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-compose/config/tn.toml
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/config.go
  pkg/fileservice/config_test.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
Labels: size/M, kind/enhancement

#13304 BI Tool Special Dialect Equivalent Rewriting
  pkg/frontend/dialect_compatibility_util.go
  pkg/frontend/dialect_compatibility_util_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_upper_lower.result
  test/distributed/cases/function/func_upper_lower.sql
Labels: kind/bug, size/M

#13314 [bug] proxy: unify connection ID between proxy and cn.
  pkg/frontend/mysql_protocol.go
  pkg/pb/proxy/proxy.go
  pkg/proxy/router.go
Labels: kind/bug, size/S

#13285 sync to 1.1: adding the hidden col size when do mo_table_size
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/function/builtin.result
  test/distributed/cases/mo_cloud/mo_cloud.result
Labels: kind/bug, size/S

#13315 [bug] processlist: handle the inconsistent result when cn scaling.
  pkg/sql/colexec/table_function/processlist.go
Labels: kind/bug, size/S

#13316 [bug] processlist: handle the inconsistent result when cn scaling.
  pkg/sql/colexec/table_function/processlist.go
Labels: kind/bug, size/S

#13296 [cherry-pick-1.1-dev] incorrect isNull semantics after join (#12849)
  pkg/cnservice/upgrader/new_add_table.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/view/view.result
  test/distributed/cases/view/view.test
Labels: kind/bug, size/S

#12619 Use cloned statementinfo instmtinfo aggregator and add logs for tracking the incorrect statementinfo
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#13297 [cherry-pick-1.1-dev] convert the constant string of length 0 from varchar to char (…
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/make.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/function/func_aggr_median.result
Labels: kind/bug, size/S

#13341 Update checkpoint replay read duration
  pkg/vm/engine/tae/db/checkpoint/replay.go
Labels: size/XS, kind/enhancement

#13301 fileservice: fix newS3FileService, newMinioFileService
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/config.go
  pkg/fileservice/config_test.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
Labels: size/M

#13306 Fix stopped checkpoint 1.1
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
Labels: kind/bug, size/S

#13334 clone zonemap to avoid reference the whole object metadata
  pkg/vm/engine/tae/catalog/segment.go
Labels: kind/bug, size/XS

#13310 fix data type conversion in kafka adapter
  pkg/stream/adapter/kafka/adapter.go
  pkg/stream/adapter/kafka/adapter_test.go
Labels: kind/bug, size/L

#13351 cherry-pick PR 13283 to 1.1-dev: Lock original table during create index
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#13345 fix lock service concurrent creating lock table
  pkg/lockservice/service.go
Labels: kind/bug, size/S

#13313 Pick db conn pool fix to 1.1
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/merge.go
Labels: kind/bug, size/S

#13355 add more detail to get variable error log
  pkg/frontend/variables.go
Labels: size/S, kind/enhancement

#13354 cherry pick “determine degree of parallelism for scan in runtime” to 1.1-dev
  pkg/sql/compile/scope.go
Labels: size/S, kind/enhancement

#13353 fix Incorrect use of proc.ctx in the builtin func
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S

#13357 Fix the the bug of concurrently reading channel
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
Labels: size/XS

#13187 refactor-pipeline-stats
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/top/top.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/process/analyze.go
  pkg/vm/process/types.go
  pkg/vm/types.go
Labels: size/S, kind/enhancement

#13360 change fileservice.policy from dynamic parameter to static parameter
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S, kind/refactor

#13366 Add more metric for debug #13045
  pkg/fileservice/s3_fs.go
  pkg/util/metric/v2/fileservice.go
Labels: kind/bug, size/S

#13348 fix drop dynamic table and create dynamic table without db name
  pkg/frontend/connector.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/task.go
  pkg/sql/plan/build_constraint_util.go
  pkg/stream/adapter/kafka/adapter.go
  pkg/stream/connector/connector.go
  pkg/taskservice/mysql_task_storage.go
Labels: kind/bug, size/S

#13358 clone zonemap to avoid reference the whole object metadata (#13334) to 1.0-dev
  pkg/vm/engine/tae/catalog/segment.go
Labels: kind/bug, size/XS

#13367 Add debug log of bmsql_district (#13349)
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/S, kind/test-ci

#13359 clone zonemap to avoid reference the whole object metadata (#13334) to 1.1-dev
  pkg/vm/engine/tae/catalog/segment.go
Labels: kind/bug, size/XS

#13361 fix stage check role (1.0-dev)
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
Labels: kind/bug, size/M

#13292 Implementing a more efficient lru(sharding)
  go.mod
  go.sum
  pkg/fileservice/lrucache/internal/hashmap/hashmap.go
  pkg/fileservice/lrucache/internal/hashmap/hashmap_test.go
  pkg/fileservice/lrucache/internal/hashmap/types.go
  pkg/fileservice/lrucache/list.go
  pkg/fileservice/lrucache/list_test.go
  pkg/fileservice/lrucache/lru.go
  pkg/fileservice/lrucache/lru_test.go
  pkg/fileservice/lrucache/pool.go
  pkg/fileservice/lrucache/shard.go
  pkg/fileservice/lrucache/types.go
  pkg/fileservice/mem_cache_test.go
Labels: size/L, kind/enhancement

#13362 add more detail to get variable error log (#1.0-dev)
  pkg/frontend/variables.go
Labels: size/S, kind/enhancement

#13365 fix Incorrect use of proc.ctx in the builtin func (#13353)
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S

#13318 fix bug: can not retry for execute statement
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/utils.go
  test/distributed/cases/pessimistic_transaction/prepare.result
  test/distributed/cases/pessimistic_transaction/prepare.sql
Labels: kind/bug, size/M

#13364 fix Incorrect use of proc.ctx in the builtin func (#13353)
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S

#13383 update mo_sessions view (#1.0-dev)
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/feature, size/S

#13350 fix bug: throw incorrect err type (#13300)
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#13271 Resolve the issue of inconsistent create account results
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/L

#13388 fileservice: pick changes
  pkg/fileservice/config_test.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/s3_fs.go
Labels: size/S, kind/enhancement

#13387 Resolve the issue of inconsistent create account results (#13271)
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/L

#13393 add orphans txn log
  pkg/lockservice/service_remote.go
Labels: kind/bug, size/XS

#13363 add more detail to get variable error log (#1.1-dev)
  pkg/frontend/variables.go
Labels: size/S, kind/enhancement

#13398 fix create dynamic table with if not exist
  pkg/frontend/connector.go
Labels: kind/bug, size/XS

#13391 do not write memcache for normal scan
  pkg/vm/engine/disttae/reader.go
Labels: size/XS, kind/enhancement

#13400 cn-service use the global log level
  pkg/cnservice/server.go
Labels: kind/bug, size/XS

#13394 add orphans txn log to 1.0
  pkg/lockservice/service_remote.go
Labels: kind/bug, size/XS

#13401 [cherry-pick] #13400 cn-service use the global log level
  pkg/cnservice/server.go
Labels: kind/bug, size/XS

#13406 Reduce io cost of load
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/operator.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: kind/bug, size/S

#13404 Cherry pick stmt report racing fix
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#13403 [opt] apply indices for IN filters
  pkg/frontend/util_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/table_function/generate_series_test.go
  pkg/sql/colexec/table_function/unnest.go
  pkg/sql/colexec/table_function/unnest_test.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/udf.go
  pkg/sql/plan/make.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/partition_prune.go
  pkg/sql/plan/partition_util.go
  pkg/sql/plan/projection_binder.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/rule/predicate_pushdown.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan_rule.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/feature, size/XL

#13402 [cherry-pick] #13400 cn-service use the global log level
  pkg/cnservice/server.go
Labels: kind/bug, size/XS

#13411 Revert "Reduce io cost of load"
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/operator.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: size/S

#13407 remove success field from ExplainData
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#13307 collect block deletes by primary key (#13136)
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/M

#13380 add goroutine debug tool
  .gitignore
  Makefile
  cmd/mo-debug/goroutine.go
  cmd/mo-debug/main.go
  cmd/mo-service/config.go
  cmd/mo-service/main.go
  pkg/util/debug/goroutine/analyze.go
  pkg/util/debug/goroutine/analyze_test.go
  pkg/util/debug/goroutine/leak.go
  pkg/util/debug/goroutine/log.go
  pkg/util/debug/goroutine/parser.go
  pkg/util/debug/goroutine/parser_test.go
  pkg/util/debug/goroutine/types.go
Labels: size/L, kind/enhancement

#13378 [bug] proxy: fix mysql protocal parsing issue.
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/bug, size/M

#13392 [bug] UT: fix data race
  pkg/taskservice/mem_task_storage.go
Labels: kind/bug, size/XS

#13395 add orphans txn log to 1.1
  pkg/lockservice/service_remote.go
Labels: kind/bug, size/XS

#13405 1.1 cherry pick stmt racing fix
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#13381 fix bug: can not retry for execute statement (#13318)
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/utils.go
  test/distributed/cases/pessimistic_transaction/prepare.result
  test/distributed/cases/pessimistic_transaction/prepare.sql
Labels: kind/bug, size/M

#13418 fix bvt bug: check rule is incorrect
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
Labels: kind/bug, size/XS

#13425 update dashboard for metric
  pkg/sql/colexec/insert/insert.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
Labels: kind/bug, size/S

#13412 add prepare sql for execute statement
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/plsql_interpreter.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/status_stmt.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: size/M, kind/enhancement

#13419 remove success field from ExplainData (#13407)
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#13427 remove success field from ExplainData (#13407)
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#12792 [Feature]: Vector Index | Phase 3
  pkg/catalog/secondary_index_utils.go
  pkg/catalog/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer_bench_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/initializer.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/initializer_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/types.go
  pkg/sql/plan/function/functionAgg/cluster_centers.go
  pkg/sql/plan/index_algo_params.go
  pkg/util/executor/types.go
  proto/plan.proto
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
  test/distributed/cases/ddl/secondary_index_create.result
  test/distributed/cases/ddl/secondary_index_create.sql
  test/distributed/cases/sample/sample_func.result
  test/distributed/cases/sample/sample_func.sql
Labels: kind/feature, size/XXL, area/ai
