Repository matrixorigin/matrixone, pull requests merged in 2023-06, with the labels that each got.

#9777 remove independent txn in sequence's function
  pkg/frontend/authenticate_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/txn.go
  pkg/frontend/util_test.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/function/seqfunc.go
Labels: kind/enhancement, size/M

#9784 Add logic for pipeline to retry in rc mode
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
Labels: kind/feature, size/S

#9781 improve range shuffle
  pkg/sql/colexec/join/join.go
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/S

#9788 Clean up the effect of failed statement on retry
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#9792 Improve performance with ETL trace-on by reusing objects and reducing memory usage
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/logutil/api.go
  pkg/logutil/internal.go
  pkg/logutil/report.go
  pkg/util/export/etl/csv.go
  pkg/util/trace/impl/motrace/report_error.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/enhancement, size/M

#9795 txn.WrapError handles all types of errors
  pkg/pb/txn/txn.go
Labels: kind/bug, size/XS

#9776 Add support for disabling spans and ignoring error log stacktraces.
  cmd/mo-service/config.go
  cmd/mo-service/main.go
  pkg/common/log/logger.go
  pkg/config/configuration.go
  pkg/logutil/api.go
  pkg/logutil/dragonboat.go
  pkg/logutil/internal.go
  pkg/logutil/internal_test.go
  pkg/util/export/batch_processor.go
  pkg/util/export/table/type.go
  pkg/util/export/writer_factory.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/syncer.go
  pkg/util/trace/impl/motrace/trace.go
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
Labels: kind/enhancement, size/M

#9801 fix retry conflict txn in rc mode
  pkg/sql/compile/compile.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#9796 improve auto-increment in load scene
  pkg/incrservice/cfg.go
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
  pkg/incrservice/store_mem.go
Labels: kind/enhancement, size/S

#9800 Fix performance regression of RIGHT join
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/M

#9803 fix incrservice panic
  CODEOWNERS
  pkg/incrservice/column_cache.go
Labels: kind/bug, size/XS

#9802 disable cn based consistency as default
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch/cn1.toml
  optools/mo_checkin_regression/mo_checkin_regression.yaml
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_test.go
  pkg/cnservice/server.go
  pkg/txn/client/client.go
Labels: kind/enhancement, size/S

#9804 fix bvt case: correct query result
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
Labels: kind/bug, size/XS

#9806 Refactor FilterRowIdForDel&AntiShrink
  pkg/container/batch/batch.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/M, kind/refactor

#9807 fix hung when close session and write concurrently
  pkg/common/morpc/server.go
Labels: kind/bug, size/S

#9808 update for binary search of pk vector
  pkg/container/types/types.go
  pkg/container/vector/tools.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/M, kind/refactor

#9812 Fix the bug of double free detection in mpool
  pkg/common/mpool/mpool.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#9814 fix 702
  pkg/vm/engine/tae/logtail/mgr.go
Labels: kind/bug, size/XS

#9810 Improve data reading performance of partition table
  pkg/frontend/compiler_context.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/partition_hash.go
  pkg/sql/plan/partition_key.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/partition_range.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
  test/distributed/cases/ddl/partition3.sql
  test/distributed/cases/ddl/partition4.sql
  test/distributed/cases/ddl/table_partition.test
  test/distributed/cases/transaction/atomicity_1.sql
  test/distributed/cases/zz_accesscontrol/grant_privs_role.sql
Labels: kind/enhancement, size/M

#9818 change timeout check code position of push model, add more logs in log tail client.
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/tae/logtail/service/client.go
  pkg/vm/engine/tae/logtail/service/server_test.go
Labels: kind/bug, size/S

#9820 using delete mask in block read
  pkg/common/bitmap/bitmap.go
  pkg/container/nulls/nulls.go
  pkg/container/nulls/nulls_test.go
  pkg/vm/engine/tae/blockio/read.go
Labels: size/M, kind/refactor

#9805 make plan tree more simple in some case
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/M

#9828 add more log for bootstrap
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_test.go
  pkg/bootstrap/log.go
  pkg/cnservice/server.go
Labels: kind/enhancement, size/S

#9829 change block read to support filter and optimize sysbench point select
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/enhancement, size/M, kind/refactor

#9831 (disttae): some code change to blockMergeReader for deletes
  pkg/vm/engine/disttae/reader.go
Labels: kind/enhancement, size/S, kind/refactor

#9837 improve sysbench delete and update performance
  pkg/objectio/utils.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/types.pb.go
  pkg/vm/engine/disttae/types.proto
  pkg/vm/engine/disttae/types_test.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/enhancement, size/L, kind/refactor

#9843 improve tpcc performance a lot by supporting composite primary key filter
  pkg/container/nulls/nulls.go
  pkg/container/vector/utils.go
  pkg/container/vector/utils_test.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/enhancement, size/XL

#9846 Fix the bug of front-end error of deleting mpool in advance and add some check
  pkg/common/mpool/mpool.go
  pkg/frontend/session.go
Labels: kind/bug, size/S

#9849 [Bug]: q21 of tpch_100g report 'internal error: send notify msg to dispatch operator timeout' on eks with 2*cn
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/XS

#9836 fileservice: add aliyun credential provider for s3 fs
  go.mod
  go.sum
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#9845 Add ping timeout
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/future.go
  pkg/common/morpc/future_test.go
  pkg/common/morpc/server.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/M

#9850 Fix the bug of wrong judgment condition of workspace write s3
  pkg/vm/engine/disttae/txn.go
Labels: size/XS

#9832 improve mem reused
  pkg/container/types/types.go
  pkg/container/vector/vector.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/visit_plan.go
Labels: kind/enhancement, size/M

#9844 logtailreplay: add exact, prefix, min-max primary key iter
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/S

#9857 Revert "Add ping timeout (#9845)"
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/future.go
  pkg/common/morpc/future_test.go
  pkg/common/morpc/server.go
  pkg/sql/compile/compile.go
Labels: size/M

#9824 fix issue open bvt test case
  test/distributed/cases/ddl/alter_table.sql
Labels: size/XS, kind/test-ci

#9858 improve tpcc performance by prefix scan
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/S

#9791 fix select global system variable
  pkg/frontend/authenticate.go
  pkg/frontend/compiler_context.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/variables.go
Labels: kind/bug, size/M

#9866 [bug] dn: split commands in case it is too large for RPC message.
  pkg/dnservice/factory.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/bug, size/M

#9691 optimize build response
  pkg/txn/storage/tae/read.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/service/event.go
  pkg/vm/engine/tae/logtail/service/event_test.go
  pkg/vm/engine/tae/logtail/service/response.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/server_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: kind/enhancement, size/L

#9876 Add ping timeout
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/future.go
  pkg/common/morpc/future_test.go
  pkg/common/morpc/server.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/M

#9880 fix checkpoint check
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/reader.go
Labels: kind/bug, size/S

#9881 partition table support `mo_table_size`,`mo_table_rows`
  pkg/sql/plan/function/func_mo.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
Labels: kind/feature, size/M

#9873 Fix dn crash
  pkg/vm/engine/tae/logtail/service/response.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: kind/bug, size/S

#9887 fix r-w conflict
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/XS

#9869 support partition table lock operator
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_dml_util.go
  proto/plan.proto
Labels: kind/feature, size/S

#9893 fix tpch plan
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/XS

#9894 fileservice: add credentials provider for Tencent Cloud
  go.mod
  go.sum
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/enhancement, size/S

#9799 fix the sendLast which might cause hung
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#9888 improve batch update zonemap by vector
  pkg/container/vector/utils.go
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/indexwrapper/immutindex.go
  pkg/vm/engine/tae/index/indexwrapper/mutindex.go
  pkg/vm/engine/tae/index/tree.go
  pkg/vm/engine/tae/index/tree_test.go
  pkg/vm/engine/tae/index/types.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/block_test.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/L, kind/refactor

#9906 fix a log tail client bug may cause response lost
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/bug, size/M

#9907 fix queryID null bug without trace
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
Labels: kind/bug, size/S

#9908 improve shuffle performance
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/M

#9912 Enable runtime filters for more cases
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
  pkg/vm/engine/disttae/txn_table.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/enhancement, kind/feature, size/M

#9905 show statements related to partition table
  pkg/frontend/show_account.go
  pkg/sql/plan/build_show.go
Labels: kind/feature, size/XS

#9903 Add restart test job in CI
  .github/workflows/e2e_launch.yml
  .github/workflows/e2e_upgrade.yml
  .github/workflows/e2e_with_proxy.yml
  pkg/bootstrap/bootstrap.go
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
  test/distributed/cases/query_result/query_result.sql
Labels: size/M, kind/test-ci

#9890 change mo_checkin_regression.yaml tp loglevel to info
  optools/mo_checkin_regression/mo_checkin_regression.yaml
Labels: size/XS, kind/test-ci, logging-regression

#9877 txn: fix txn rollback multi-times
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: kind/bug, size/S

#9915 fix boostreap step 2 failed
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-with-proxy/cn2.toml
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_test.go
Labels: kind/bug, size/S

#9904 [BugFix]: StatsLogger Data Race
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/mometric/stats_log_writer_test.go
  pkg/util/metric/stats/registry.go
  pkg/util/metric/stats/registry_test.go
Labels: kind/bug, size/S

#9913 Fix stmt stats as null and note sqlWrite meet commit timeout.
  pkg/util/export/etl/db/db_holder.go
  pkg/util/trace/impl/motrace/schema.go
Labels: kind/bug, kind/enhancement, size/S

#9918 fix cn ping panic
  pkg/common/morpc/client.go
  pkg/common/morpc/server_test.go
Labels: kind/bug, size/S

#9826 txn: adjusting transaction wait-related logic
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/enhancement, size/S

#9911 Fix the bug of workspace write s3 condition
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S

#9461 transaction cases
  test/distributed/cases/tenant/privilege/alter_user_password.result
  test/distributed/cases/tenant/privilege/alter_user_password.sql
  test/distributed/cases/transaction/transaction_enhance.result
  test/distributed/cases/transaction/transaction_enhance.sql
Labels: size/L, kind/test-ci

#9921 Disable runtime filter on multi CN
  pkg/sql/compile/compile.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/M

#9928 fileservice: more logging for retry
  pkg/fileservice/retry.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#9920 Fix data race panic 1
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#9933 lockservice: fix lock range merge bugs
  pkg/lockservice/btree_storage.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/log.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
Labels: kind/bug, size/M

#9916 change set_var and fix bugs
  pkg/config/configuration.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/compiler_context.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/output.go
  pkg/frontend/query_result.go
  pkg/frontend/routine_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/status_stmt.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/result_scan.go
  pkg/sql/plan/set_binder.go
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/sequence/create_sequence.result
  test/distributed/cases/sequence/create_sequence.sql
  test/distributed/cases/sequence/seq_func2.result
  test/distributed/cases/sequence/seq_func2.sql
  test/distributed/cases/sequence/sequence.sql
Labels: kind/bug, kind/enhancement, size/XL

#9937 [bug] CI: fix e2e upgrade CI, add more checks and retry.
  .github/workflows/e2e_upgrade.yml
Labels: kind/bug, size/S

#9938 optimize delete, optimize prepare range delete
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: kind/enhancement, size/S

#9931 add foreign key info in desc
  pkg/sql/plan/build_show.go
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: kind/bug, size/S

#9898 let the dispatch return normally when the receiver's context done
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#9946 Fix data inconsistency bug
  pkg/container/vector/vector.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#9746 don't skip when error happened in agg
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
Labels: kind/bug, size/M

#9923 Fix test dedup snapshot3
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/M

#9947 reduce the occurrence of panic
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#9875 fix and refine metadata scan
  pkg/catalog/types.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/metadata_scan.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: kind/bug, kind/enhancement, size/L

#9940 Improve partition table dml operation
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/deepcopy.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/enhancement, size/M

#9953 fix check applied logtail if re-connect
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/bug, size/XS

#9944 fix auto incrservice null handle logic
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
Labels: kind/bug, size/S

#9926 Fix out of range error for set set type var
  pkg/frontend/variables.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#9943 fix a merge-order bug will cause duplicate result
  pkg/sql/colexec/mergeorder/order.go
Labels: kind/bug, size/S

#9775 fix #8599: move task schedule to a separate goroutine
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_test.go
Labels: kind/bug, size/M

#9961 fix shuffle in window func
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/window/window.go
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/S

#9968 fix killqueue bug
  pkg/frontend/routine_manager.go
Labels: kind/bug, size/XS

#9969 print the number of WAL entries when replay
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: size/S

#9798 CI: not store log in s3 and upload to summary
  .github/workflows/mo_checkin_regression.yaml
Labels: size/S, kind/test-ci

#9972 make incrservice using external txn in all ops
  pkg/incrservice/allocator.go
  pkg/incrservice/allocator_test.go
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
  pkg/incrservice/service.go
  pkg/incrservice/service_test.go
  pkg/incrservice/store_mem.go
  pkg/incrservice/store_sql.go
  pkg/incrservice/table_cache.go
  pkg/incrservice/types.go
  pkg/sql/colexec/preinsert/preinsert.go
Labels: kind/bug, size/M, kind/refactor

#9973 Revert "fix #8599: move task schedule to a separate goroutine"
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_test.go
Labels: size/M

#9975 Fix the bug in HandleCommit where error does not release txn's context
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#9976 let the lock op of the same txn serially
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter_events.go
Labels: kind/bug, size/M

#9977 fix bvt w-w conflict
  pkg/incrservice/service.go
  pkg/incrservice/service_test.go
  pkg/incrservice/store_mem.go
  pkg/incrservice/store_sql.go
  pkg/incrservice/types.go
  pkg/sql/compile/sql_executor.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
Labels: kind/bug, size/M

#9979 txn: need wait if have not received notification
  pkg/txn/client/timestamp_waiter.go
Labels: kind/bug, size/XS

#9980 CI: modify the sequence of process
  .github/workflows/mo_checkin_regression.yaml
Labels: size/S, kind/test-ci

#9981 CI: Pauses performance comparison error log output
  .github/workflows/mo_checkin_regression.yaml
Labels: size/S, kind/test-ci

#9917 [improvement] proxy: add bootstrap logic and some logs.
  pkg/proxy/bootstrap.go
  pkg/proxy/bootstrap_test.go
  pkg/proxy/counter_set.go
  pkg/proxy/error.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/label_info_test.go
  pkg/proxy/server.go
  pkg/proxy/tunnel.go
Labels: kind/enhancement, size/M

#9864 support select for update in plan
  pkg/sql/plan/build_test.go
  pkg/sql/plan/flatten_subquery.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/types.go
Labels: kind/feature, size/M

#9987 fileservice: do not cache 3rd-party credential providers
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#9936 add cn primary key check config
  pkg/cnservice/types.go
  pkg/sql/plan/build_dml_util.go
Labels: kind/feature, size/L

#9970 print hakeeper state when bootstrap
  pkg/hakeeper/rsm.go
  pkg/logservice/store_hakeeper_check.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/enhancement, size/XS

#9991 add method to print stats to help debug some problem
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#9990 logutil: add Slow
  pkg/logutil/slow.go
  pkg/logutil/slow_test.go
Labels: kind/enhancement, size/S

#9989 fileservice: disable 3rd-party s3 credentials
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/bug, size/S

#9994 remove redundant join condition
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: kind/enhancement, size/S

#9995 fileservice: fix s3 retryer
  pkg/fileservice/retry.go
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/S

#9999 [bug] fix bug that connectAttrs map is nil.
  pkg/frontend/mysql_protocol.go
Labels: kind/bug, size/XS

#10001 fix notify applied logtail block
  pkg/txn/client/timestamp_waiter.go
Labels: kind/bug, size/S

#10010 fix stats for left join and right join
  pkg/sql/colexec/right/join.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/S

#10013 fix data race
  pkg/incrservice/service.go
Labels: kind/bug, size/XS

#10000 proxy: improve performance of isStmt functions
  pkg/proxy/util.go
Labels: kind/enhancement, size/S, kind/refactor

#10014 Enable runtime filter on composite primary key
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/feature, size/M

#10008 Optimize delete
  pkg/container/nulls/nulls.go
  pkg/vm/engine/tae/common/bitmap.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/compute/compute_test.go
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/indexwrapper/immutindex.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/model/blkview.go
  pkg/vm/engine/tae/model/blkview_test.go
  pkg/vm/engine/tae/model/colview.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
Labels: size/L

#9993 support order by decimal and fix some bugs
  pkg/partition/partition.go
  pkg/sql/colexec/window/window.go
  pkg/sql/plan/projection_binder.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/L

#10011 fix logtail related bugs
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/client/testutil.go
  pkg/txn/client/timestamp_waiter.go
  pkg/txn/client/timestamp_waiter_test.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/bug, size/M

#10006 [bug] txn: drop table reported error ExpectedEOB.
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/ddl.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M

#10021 fix a push bug may set client ready when log tail time is still 0
  pkg/vm/engine/disttae/logtailPushModel.go
Labels: kind/bug, size/XS

#10018 CI: add bvt test in mo-checkin-regression
  .github/workflows/mo_checkin_regression.yaml
  optools/mo_checkin_regression/mo_checkin_regression.yaml
Labels: size/M, kind/test-ci

#10023 improve join order
  pkg/sql/plan/join_order.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
Labels: kind/enhancement, size/S

#10027 Use runtime filter to handle primary key constraint
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/feature, size/M

#10022 fix a bug for right join which may cause wrong result
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
Labels: kind/bug, size/XS

#10020 fix select for update getPrimary key out of index
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/XS

#10026 fix data race in lock service
  pkg/lockservice/rpc.go
Labels: kind/bug, size/XS

#10030 reduce some memory allocations
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
Labels: size/M

#10033 Revert "remove some stale logic and update some default configuration…
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: kind/bug, size/S

#9941 Add ctx in DN txn and tables
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/block.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/jobs/compactblk.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/basenode.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/node.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/enhancement, size/XL

#10028 record Span with long time threshold and context deadline condition.
  pkg/config/configuration.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/schema.go
  pkg/util/trace/noop_trace.go
  pkg/util/trace/noop_trace_test.go
  pkg/util/trace/trace.go
  pkg/util/trace/type.go
Labels: kind/enhancement, size/M

#10029 optimize some function and remove unused code.
  pkg/sql/plan/function/baseTemplate.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/func_builtin_regexp.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/list_builtIn.go
Labels: size/L, kind/refactor

#10037 fileservice: remove context.TODO
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/objectio/fs.go
  pkg/objectio/writer_test.go
  pkg/tests/service/fileservice.go
  pkg/tests/service/fileservice_test.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
  pkg/tests/service/task_test.go
  pkg/tests/txn/cluster.go
  pkg/tests/txn/cluster_basic_test.go
  pkg/tests/txn/cluster_mo_ctl_test.go
  pkg/txn/storage/tae/storage.go
  pkg/util/export/etl/csv_test.go
  pkg/util/metric/test/cron_task_test.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/catalog_test.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/hidden_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/db/scheduler_test.go
  pkg/vm/engine/tae/db/tables_test.go
  pkg/vm/engine/tae/db/txn_test.go
  pkg/vm/engine/tae/index/indexwrapper/bfnode_test.go
  pkg/vm/engine/tae/index/indexwrapper/zmnode_test.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/samples/sample1/main.go
  pkg/vm/engine/tae/samples/sample2/main.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/enhancement, size/L

#10040 optimize r-w transfer
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/enhancement, size/M

#10019 fix partition lock problem
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/plan/build_dml_util.go
Labels: kind/feature, size/M

#10012 change decimal encoding in tuple
  pkg/container/types/tuple.go
  pkg/container/types/tuple_test.go
Labels: kind/bug, size/M

#10042 fix select sql_mode order
  pkg/frontend/variables.go
Labels: kind/bug, size/XS

#10039 remove some useless code in join order
  pkg/sql/plan/join_order.go
Labels: kind/enhancement, size/S

#10048 refactor block related code
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/block_test.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
Labels: size/L, kind/refactor

#10032 Revert "logutil: add Slow (#9990)"
  pkg/logutil/slow.go
  pkg/logutil/slow_test.go
Labels: size/S, kind/refactor

#10051 release append nodes and refactor related code
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/L, kind/refactor

#10056 minor refactor of stats
  pkg/sql/plan/agg_pushdown_pullup.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/S

#10058 fix lock start greater than end panic
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
Labels: kind/bug, size/S

#10044 remove bvt tag
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#10066 check ctx timeout in async goroutine
  pkg/incrservice/allocator.go
Labels: kind/bug, size/M

#10057 Clean rpc handle txn cache for invlid
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_test.go
Labels: kind/bug, size/S

#10070 fileservice: retry on dns lookup error
  pkg/fileservice/error.go
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/S

#10065 csv writer reuse buffer while do ETL
  pkg/util/export/etl/csv.go
  pkg/util/export/etl/db/db_holder.go
Labels: kind/enhancement, size/S

#10062 Fix keyparititon bug
  pkg/sql/plan/partition_key.go
  pkg/sql/plan/partition_key_test.go
Labels: kind/bug, size/M

#10079 Revert "check ctx timeout in async goroutine"
  pkg/incrservice/allocator.go
Labels: size/M

#10072 fix memory leak of function and expression framework
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_test.go
Labels: kind/bug, size/M

#10073 release delete nodes when compact
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: kind/enhancement, size/M

#10083 Revert "release delete nodes when compact (#10073)"
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/ablk.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: size/M
