Repository matrixorigin/matrixone, pull requests merged in 2023-10, with the labels that each got.

#11969 fix collect deletes
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#11980 fix cannot allocate new cache
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
Labels: kind/bug, size/S

#11968 fix heartbeat context deadline not set
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/message.go
Labels: kind/bug, size/S

#11984 make retry reset conn with temp net error
  pkg/common/morpc/backend.go
  pkg/logservice/hakeeper_client_test.go
Labels: kind/bug, size/S

#11965 fix some lockservice panic
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_forward.go
  pkg/lockservice/service_forward_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/txn.go
Labels: kind/bug, size/S

#11979 fix txn deadlock in IterTxns
  pkg/txn/client/client.go
Labels: kind/bug, size/S

#11869 fix : do not let other errors override the retry error
  pkg/sql/compile/compile.go
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
  test/distributed/cases/pessimistic_transaction/ww_conflict.result
  test/distributed/cases/pessimistic_transaction/ww_conflict.sql
Labels: kind/bug, size/S

#11987 pipeline return error if ctx is done
  pkg/vm/pipeline/pipeline.go
Labels: kind/bug, size/XS

#11986 Fix incorrect locking logic for inserting tables without primary keys
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#11955 add variables view
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/authenticate.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/S

#11961 Type check failure.
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/S

#11993 [feature] proxy: add heartbeat to hakeeper to support upload configs.
  pkg/hakeeper/checkers/coordinator.go
  pkg/hakeeper/checkers/proxy/check.go
  pkg/hakeeper/checkers/proxy/check_test.go
  pkg/hakeeper/config.go
  pkg/hakeeper/operator/controller.go
  pkg/hakeeper/operator/controller_test.go
  pkg/hakeeper/operator/create_operator.go
  pkg/hakeeper/operator/operator.go
  pkg/hakeeper/operator/operator_test.go
  pkg/hakeeper/operator/steps.go
  pkg/hakeeper/operator/steps_test.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  pkg/proxy/bootstrap.go
  pkg/proxy/config.go
  pkg/proxy/handler.go
  pkg/proxy/heartbeat.go
  pkg/proxy/label_info_test.go
  pkg/proxy/server.go
  pkg/proxy/server_test.go
  pkg/sql/colexec/table_function/system_view.go
  proto/logservice.proto
Labels: kind/feature, size/L

#11996 cherrypick 3df1bae
  pkg/vm/engine/disttae/util.go
Labels: size/S

#11932 fix trace context
  pkg/fileservice/local_fs.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/cmd_tracespan_test.go
  pkg/tnservice/store_rpc_handler.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_bench_test.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/trace.go
  pkg/vm/process/types.go
  test/distributed/cases/table/system_table_cases.sql
Labels: kind/bug, kind/enhancement, size/L

#11989 Fix partition bug
  pkg/common/moerr/error.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_hash.go
  pkg/sql/plan/partition_key_test.go
  pkg/sql/plan/partition_list_test.go
  pkg/sql/plan/partition_util.go
Labels: kind/feature, size/M

#11997 add some debug log
  pkg/cnservice/server.go
  pkg/common/morpc/backend.go
  pkg/incrservice/store_sql.go
Labels: kind/bug, size/S

#11982 refresh cluster cache if found cache is stale
  pkg/clusterservice/cluster.go
  pkg/clusterservice/cluster_test.go
  pkg/clusterservice/types.go
  pkg/common/morpc/client.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/label_info_test.go
  pkg/proxy/rebalancer_test.go
  pkg/proxy/router_test.go
  pkg/proxy/scaling_test.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/bug, size/M

#12005 Add some logs for locating table build failures
  pkg/sql/compile/ddl.go
  pkg/sql/compile/log.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/M

#12000 add log
  pkg/frontend/txn.go
  pkg/frontend/util.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/util/log.go
Labels: size/S, kind/test-ci

#11988 fix global checkpoint
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#11790 use in-memory pk when collect delete batch
  pkg/objectio/CHANGELOG.md
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: kind/enhancement, size/M

#12009 fix data race in tableEntry.GetCreateTS()
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: kind/bug, size/S

#11959 Speed Up Count/Min/Max
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/any_value.go
  pkg/sql/plan/function/functionAgg/approx_count.go
  pkg/sql/plan/function/functionAgg/avg.go
  pkg/sql/plan/function/functionAgg/bit_and.go
  pkg/sql/plan/function/functionAgg/bit_or.go
  pkg/sql/plan/function/functionAgg/bit_xor.go
  pkg/sql/plan/function/functionAgg/count.go
  pkg/sql/plan/function/functionAgg/dense_rank.go
  pkg/sql/plan/function/functionAgg/group_concat.go
  pkg/sql/plan/function/functionAgg/max.go
  pkg/sql/plan/function/functionAgg/median.go
  pkg/sql/plan/function/functionAgg/min.go
  pkg/sql/plan/function/functionAgg/rank.go
  pkg/sql/plan/function/functionAgg/row_number.go
  pkg/sql/plan/function/functionAgg/stddev_pop.go
  pkg/sql/plan/function/functionAgg/sum.go
  pkg/sql/plan/function/functionAgg/var_pop.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/func_aggr_count.result
  test/distributed/cases/function/func_aggr_count.test
  test/distributed/cases/function/func_aggr_max.result
  test/distributed/cases/function/func_aggr_max.test
  test/distributed/cases/function/func_aggr_min.result
  test/distributed/cases/function/func_aggr_min.test
Labels: size/L

#12014 fix global checkpoint
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#12010 do not check insert pk dup in some case
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, kind/enhancement, size/M

#12008 fix data race
  pkg/frontend/routine_manager.go
Labels: kind/bug, size/XS

#12011 fix DATA RACE between setting stmt.SessionID and getting stmt.SessionID
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/session.go
  pkg/frontend/util.go
Labels: kind/bug, size/S

#11992 fix data race
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#12016 update log
  pkg/frontend/txn.go
Labels: size/XS

#11756 add wait committed log applied in incrservice
  pkg/incrservice/store_sql.go
Labels: kind/bug, size/XS

#12019 fix the sort key missing in tables having cluster by clause
  pkg/vm/engine/tae/catalog/schema.go
Labels: kind/bug, size/XS

#11690 set sum in zonemap when flush to disk
  pkg/container/types/types.go
  pkg/container/vector/utils.go
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: kind/feature, size/M

#12029 Update enhancement.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: kind/documentation, size/S

#12030 Make sure no one use ses.tStmt after EndStatement
  pkg/frontend/util.go
Labels: kind/bug, size/XS

#12025 fix checkpoint meta
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/test/catalog_test.go
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/M

#12032 CI: Add issue template check
  .github/ISSUE_TEMPLATE/schema.json
  .github/workflows/ci.yml
Labels: size/XL, kind/test-ci

#12018 Add local chaos tester
  cmd/mo-service/config.go
  cmd/mo-service/dynamic.go
  etc/launch-dynamic-cn/launch.toml
  pkg/common/chaos/README.md
  pkg/common/chaos/chaos.go
  pkg/common/chaos/restart.go
  pkg/common/chaos/types.go
Labels: size/M, kind/test-ci

#12038 add debug log
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/test-ci

#12012 upgrade for mo_stages
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
Labels: kind/tech-request, size/S, kind/enhancement

#11861 [bug] incre: bootstrap fails as the wrong incre service instance.
  pkg/cnservice/server.go
  pkg/defines/type.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/txn.go
  pkg/incrservice/service.go
  pkg/incrservice/service_test.go
  pkg/incrservice/types.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/plan/function/auto_increase.go
  pkg/testutil/util_new.go
  pkg/vm/process/process.go
Labels: kind/bug, size/S

#11946 load object metadata to estimate memory size
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/tech-request, size/S, kind/enhancement

#12044 Remove unnecessary warning logs
  pkg/objectio/writer.go
Labels: size/XS, kind/enhancement

#12048 [bug] fix nil pointer bug
  pkg/frontend/authenticate.go
Labels: kind/bug, size/XS

#12046 [bug] fix data race
  pkg/taskservice/daemon_task.go
  pkg/taskservice/task_runner.go
Labels: kind/bug, size/S

#11995 add txn views
  pkg/cnservice/server_query.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_test.go
  pkg/frontend/authenticate.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/query/query.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/colexec/table_function/system_view.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/system_view.go
  pkg/util/export/table/table.go
  proto/query.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/L

#12028 fix txn leak in cloud env
  pkg/cnservice/server.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service.go
  pkg/lockservice/service_forward.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/types.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/client.go
Labels: kind/bug, size/M

#12050 fix a bug will lost context deadline exceeded error
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
Labels: kind/bug, size/M

#12057 [bug] fix nil pointer bug
  pkg/frontend/authenticate.go
  pkg/sql/colexec/table_function/processlist.go
Labels: kind/bug, size/XS

#12053 Add some logs to locate why a table was not created.
  pkg/txn/client/operator.go
  pkg/txn/util/log.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S

#12066 remove #10701 bvt tag
  test/distributed/cases/pessimistic_transaction/isolation_1.sql
Labels: size/XS

#12056 optimize deadlock check
  pkg/lockservice/cfg.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
Labels: size/M, kind/enhancement

#12037 fileservice: add oidc_role_arn credential to AliyunSDK
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/object_storage_arguments.go
Labels: size/S, kind/enhancement

#12034 Compatibility test failed
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_test.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/common/moerr/error.go
  pkg/util/export/table/table.go
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
Labels: kind/bug, size/L

#12072 Revert "optimize deadlock check (#12056)"
  pkg/lockservice/cfg.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
Labels: kind/bug, size/M

#11971 A sequence of minor rewrite to clean up executeStmt
  pkg/frontend/mysql_cmd_executor.go
Labels: size/M, kind/refactor

#12076 fix count(const) from table
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#12077 optimize deadlock check
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
Labels: size/M, kind/enhancement

#12069 change config frontend::lengthOfQueryPrinted default as 1KiB
  pkg/config/configuration.go
Labels: size/XS, kind/enhancement

#12090 fix waiter data race
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
Labels: kind/bug, size/M

#12085 fix disttae mpool and internal executor mpool leak.
  pkg/backup/tae.go
  pkg/cnservice/distributed_tae.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/function/func_builtin.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/bug, size/M

#12092 add debug log
  pkg/vm/engine/tae/logtail/handle.go
Labels: size/S

#12087 Cherry pick upgrate
  go.mod
  pkg/cnservice/upgrader/newAddTable.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_test.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/common/moerr/error.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/sysview/sysview.go
  pkg/util/trace/impl/motrace/schema.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/log/query_sql_statement_hotspot.result
  test/distributed/cases/log/query_sql_statement_hotspot.sql
Labels: kind/bug, size/L

#12097 Port #11971 from main: A sequence of minor rewrite to executeStmt.
  pkg/frontend/mysql_cmd_executor.go
Labels: size/M, kind/refactor

#12101 perfcounter: add Named
  cmd/mo-service/config.go
  cmd/mo-service/debug.go
  pkg/perfcounter/named.go
Labels: size/S, kind/enhancement

#12094 try fix TestMOSpan_doProfile in low cpu dev
  pkg/util/trace/impl/motrace/mo_trace_test.go
Labels: kind/bug, size/S

#12068 merge refactor phase 1
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/feature, size/XL

#12098 fix bug:unhandled exception in some case in stats function
  pkg/frontend/compiler_context.go
Labels: kind/bug, size/XS

#12089 add unique index for mo_account table
  pkg/frontend/authenticate.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
Labels: kind/bug, size/S

#12103 add many metrics
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/lockservice/service.go
  pkg/sql/compile/compile.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/server.go
  pkg/txn/service/service_cn_handler.go
  pkg/util/metric/v2/fs_metric_counter.go
  pkg/util/metric/v2/fs_metric_gauge.go
  pkg/util/metric/v2/fs_metric_histogram.go
  pkg/util/metric/v2/logtail_metric_gauge.go
  pkg/util/metric/v2/logtail_metric_histogram.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/sql_metric_histogram.go
  pkg/util/metric/v2/txn_metric_counter.go
  pkg/util/metric/v2/txn_metric_gauge.go
  pkg/util/metric/v2/txn_metric_histogram.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
Labels: size/L, kind/enhancement

#12104 add log
  pkg/cnservice/server.go
  pkg/txn/client/client.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/leak_checker_test.go
  pkg/txn/client/operator.go
Labels: size/S, kind/test-ci

#12110 remove unnecessary panic check
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: size/XS, kind/enhancement

#12061 remove rawitem from the clusterby
  pkg/util/trace/impl/motrace/schema.go
Labels: kind/bug, size/XS, kind/enhancement

#12095 Limit the size of a single checkpoint file
  pkg/objectio/metav2.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/db/checkpoint/option.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/cfg.go
Labels: kind/bug, size/M, kind/enhancement

#12102 fix alter sequence
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/sequence/alter_sequence.result
  test/distributed/cases/sequence/alter_sequence_1.result
  test/distributed/cases/sequence/alter_sequence_1.sql
Labels: kind/bug, size/M

#12124 Limit the size of a single checkpoint file (#12095)
  pkg/objectio/metav2.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/db/checkpoint/option.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/cfg.go
Labels: kind/bug, size/M, kind/enhancement

#12122 Implementing batch chunking for ondup's operators
  pkg/common/mpool/mpool.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
Labels: kind/bug, size/S

#12127 Implementing batch chunking for ondup's operators
  pkg/common/mpool/mpool.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
Labels: kind/bug, size/S

#12131 Improve parse date cast
  pkg/container/types/date.go
  pkg/container/types/date_test.go
Labels: size/M, kind/enhancement

#12112 feat: add log2 function to SQL
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/func_builtin_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/momath/math.go
  test/distributed/cases/function/func_math_log2.result
  test/distributed/cases/function/func_math_log2.test
Labels: kind/feature, size/M

#12134 Add timeout for pipeline stream
  pkg/cnservice/cnclient/client.go
Labels: size/XS, kind/enhancement

#12071 optimize hash join on primary key
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mark/types.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/types.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/types.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/single/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/opt_misc.go
  proto/pipeline.proto
  test/distributed/cases/join/join.result
  test/distributed/cases/join/join.test
Labels: size/L

#12136 Add timeout for pipeline stream
  pkg/cnservice/cnclient/client.go
Labels: size/XS, kind/enhancement

#12114 feat: add lg function to SQL
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/func_builtin_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/momath/math.go
  test/distributed/cases/function/func_math_lg.result
  test/distributed/cases/function/func_math_lg.test
Labels: kind/feature, size/M

#12117 fix datarace for txn.meta.snapshotts
  pkg/frontend/test/txn_mock.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/bug, size/M

#12109 CI: Add tke mergerun
  .github/workflows/merge-trigger-tke.yaml
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: size/L, kind/test-ci

#12135 fix a mpool leak of reader; remove some hack code.
  pkg/common/mpool/mpool.go
  pkg/frontend/computation_wrapper.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/process/process.go
Labels: kind/bug, size/S

#12140 CI: Add trigger condition for tke
  .github/workflows/merge-trigger-tke.yaml
Labels: size/XS, kind/test-ci

#12144 Add missing recover
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#12145 Add missing recover
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#12146 feat: support mo-dump -no-data flag
  cmd/mo-dump/main.go
  cmd/mo-dump/types.go
Labels: kind/feature, size/S

#12141 support load from stage in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/XXL

#12151 [bug] logservice: add timeout for RPC read.
  cmd/mo-service/launch.go
  pkg/logservice/client.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/shardinfo.go
Labels: kind/bug, size/S

#12153 add error log in task allocation
  pkg/hakeeper/task/task_scheduler.go
Labels: size/XS, kind/enhancement

#12154 fileservice: refactor read/write bytes counting
  pkg/fileservice/file_service.go
  pkg/fileservice/io.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/M

#12165 CI: debug tke mergerun action
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#12172 Fix CN prefetch checkpoint
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#12152 Add log to locate why table was not created
  pkg/sql/compile/ddl.go
  pkg/txn/util/log.go
  pkg/vm/engine/disttae/txn_database.go
Labels: kind/bug, size/S

#12162 Handle alter table index issue
  pkg/sql/compile/alter.go
  pkg/sql/plan/build_alter_table.go
Labels: kind/bug, size/S

#12178 fix a remote run bug will cause memory leak.
  pkg/sql/colexec/server.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/S

#12181 fix lockservice panic with try hold on empty lock
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
Labels: kind/bug, size/M

#12115 Use load in mo logger
  pkg/sql/compile/compile.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/etl/sql_test.go
Labels: kind/bug, size/M, kind/enhancement

#12185 Prune the log of debug for 11917
  .github/workflows/e2e-compose.yml
  pkg/sql/compile/ddl.go
  pkg/vm/engine/disttae/txn_database.go
Labels: size/S, kind/enhancement

#12180 fix: show create table is abnormal after add constraint primary key
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
Labels: kind/bug, size/XS

#12156 fix alter sequence
  pkg/sql/compile/ddl.go
  test/distributed/cases/sequence/alter_sequence.result
  test/distributed/cases/sequence/alter_sequence_1.result
  test/distributed/cases/sequence/alter_sequence_1.sql
  test/distributed/cases/sequence/create_sequence.result
Labels: kind/bug, size/S

#12192 Prune the log of debug for 11917
  pkg/sql/compile/ddl.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/S, kind/enhancement

#12191 Prune log for tae's rpc handle
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/XS, kind/enhancement

#12157 fix stage comment
  pkg/frontend/authenticate.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  test/distributed/cases/stage/stage.result
  test/distributed/cases/stage/stage.sql
Labels: kind/bug, size/XXL

#12199 improve the preformace of log for debug
  pkg/vm/engine/disttae/txn_database.go
Labels: size/XS, kind/enhancement

#12205 Revert "fix alter sequence"
  pkg/sql/compile/ddl.go
  test/distributed/cases/sequence/alter_sequence.result
  test/distributed/cases/sequence/alter_sequence_1.result
  test/distributed/cases/sequence/alter_sequence_1.sql
  test/distributed/cases/sequence/create_sequence.result
Labels: size/S

#12200 fix create stage with comment
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  test/distributed/cases/stage/stage.result
Labels: kind/bug, size/XS

#12207 add csv field delimiter
  cmd/mo-dump/main.go
  cmd/mo-dump/main_test.go
  cmd/mo-dump/types.go
Labels: kind/bug, size/M, attention/doc-influence

#12213 Remove log for debug 11917
  pkg/vm/engine/disttae/txn_database.go
Labels: size/S, kind/enhancement

#12208 add some log
  pkg/hakeeper/task/task_scheduler.go
  pkg/taskservice/task_runner.go
Labels: size/XS

#12217 [bug] logtail: CN panic due to wait latest commit ts failed
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/bug, size/M

#12188 add unique index for mo_account table (#12089)
  pkg/frontend/authenticate.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
Labels: size/S

#12227 remove some unnecessary logs
  pkg/frontend/txn.go
  pkg/frontend/util.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/util/log.go
Labels: size/S

#12108 merge more blocks
  pkg/sql/plan/function/ctl/cmd_inspectdn.go
  pkg/sql/plan/function/ctl/ctl.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: size/XL, kind/enhancement

#12228 feat: add CN heartbeat metric
  pkg/cnservice/server_heartbeat.go
  pkg/util/metric/v2/hakeeper_metric.go
  pkg/util/metric/v2/metrics.go
Labels: size/S, kind/enhancement

#12233 cherry-pick: feat: add CN heartbeat metric
  pkg/cnservice/server_heartbeat.go
  pkg/util/metric/v2/hakeeper_metric.go
  pkg/util/metric/v2/metrics.go
Labels: size/S, kind/enhancement

#12237 add metric for heartbeat process
  pkg/logservice/service.go
  pkg/logservice/service_commands.go
  pkg/tnservice/store_heartbeat.go
  pkg/util/metric/v2/hakeeper_metric.go
  pkg/util/metric/v2/metrics.go
Labels: size/S, kind/enhancement

#12247 fix stopped checkpoint 1.0
  pkg/vm/engine/tae/db/checkpoint/runner.go
Labels: size/S

#12246 fix slice out of bound 1.0
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/S

#12242 cn upgrade once
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/types.go
Labels: kind/bug, size/S

#12244 fix slice out of range when considering available mem
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/index/zm.go
Labels: kind/bug, size/S

#12230 trace controller for tn
  pkg/cnservice/server_query.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/query/query.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/cmd_tracespan_test.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_bench_test.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/vm/engine/tae/common/context_records.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  proto/query.proto
Labels: size/M

#12189 removeTag11406
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.sql
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/alter_table_rename_column.sql
  test/distributed/cases/dml/show/show.test
  test/distributed/cases/dtype/enum.sql
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
Labels: size/M

#12265 fix txn need retry in rc mode
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  proto/api.proto
Labels: kind/bug, size/M

#12276 cherry pick add more metrics to 1.0 dev
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/service.go
  pkg/lockservice/types.go
  pkg/sql/compile/compile.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/server.go
  pkg/txn/service/service_cn_handler.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/fs_metric.go
  pkg/util/metric/v2/fs_metric_counter.go
  pkg/util/metric/v2/fs_metric_gauge.go
  pkg/util/metric/v2/fs_metric_histogram.go
  pkg/util/metric/v2/grafana_dashboard.go
  pkg/util/metric/v2/logtail.go
  pkg/util/metric/v2/logtail_metric_gauge.go
  pkg/util/metric/v2/logtail_metric_histogram.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/sql_metric_histogram.go
  pkg/util/metric/v2/txn.go
  pkg/util/metric/v2/txn_metric_counter.go
  pkg/util/metric/v2/txn_metric_gauge.go
  pkg/util/metric/v2/txn_metric_histogram.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: size/XXL, kind/enhancement

#12218 The default checkpoint size is changed from 1G to 512M
  pkg/vm/engine/tae/logtail/utils.go
Labels: size/XS, kind/enhancement

#12222 fix username problem of modump on mocloud
  CODEOWNERS
  cmd/mo-dump/main.go
Labels: kind/bug, size/S

#12277 Remove unused debug log
  pkg/sql/compile/ddl.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
Labels: size/S, kind/enhancement

#12270 cherry pick #12265
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  proto/api.proto
Labels: kind/bug, size/M

#12254 [Improvement]: Support Dictionary Order Comparison Operator for Vector
  pkg/vectorize/moarray/array.go
  pkg/vectorize/moarray/array_test.go
Labels: size/S, kind/enhancement

#12266 add more metrics
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/service.go
  pkg/lockservice/types.go
  pkg/sql/compile/compile.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/server.go
  pkg/txn/service/service_cn_handler.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/fs_metric.go
  pkg/util/metric/v2/fs_metric_counter.go
  pkg/util/metric/v2/fs_metric_gauge.go
  pkg/util/metric/v2/fs_metric_histogram.go
  pkg/util/metric/v2/grafana_dashboard.go
  pkg/util/metric/v2/logtail.go
  pkg/util/metric/v2/logtail_metric_gauge.go
  pkg/util/metric/v2/logtail_metric_histogram.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/sql_metric_histogram.go
  pkg/util/metric/v2/txn.go
  pkg/util/metric/v2/txn_metric_counter.go
  pkg/util/metric/v2/txn_metric_gauge.go
  pkg/util/metric/v2/txn_metric_histogram.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: size/XXL, kind/enhancement

#12284 fix panic and missing info when calling mo-ctl 1.0
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: kind/bug, size/M, kind/enhancement

#12286 Cover log discardable
  pkg/util/export/batch_processor.go
Labels: kind/bug, size/S

#12252 fix errors info on missing database
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/object_name.go
  pkg/sql/parsers/tree/show.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/utils.go
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/lowercase.result
  test/distributed/cases/ddl/lowercase.test
  test/distributed/cases/dml/show/show4.result
  test/distributed/cases/dml/show/show4.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/optimistic/atomicity.result
  test/distributed/cases/optimistic/isolation_2.result
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/isolation_2.result
Labels: kind/bug, size/XXL

#12278 fix TryDeleteByDeltaloc
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/M

#12163 add cache view
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/launch.go
  cmd/mo-service/main.go
  pkg/clusterservice/cluster.go
  pkg/cnservice/server_query.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/hakeeper/rsm.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/metadata/metadata.pb.go
  pkg/pb/query/query.pb.go
  pkg/perfcounter/named.go
  pkg/queryservice/handler.go
  pkg/queryservice/query_service_test.go
  pkg/sql/colexec/table_function/system_view.go
  pkg/sql/colexec/table_function/system_view_test.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/system_view.go
  pkg/tnservice/cfg.go
  pkg/tnservice/service_ports.go
  pkg/tnservice/store.go
  pkg/tnservice/store_heartbeat.go
  pkg/vm/engine/disttae/util.go
  proto/logservice.proto
  proto/metadata.proto
  proto/query.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/XL, attention/doc-influence

#12272 New shuffle algorithm
  pkg/sql/plan/shuffle_algo.go
  pkg/sql/plan/shuffle_test.go
Labels: size/M

#12289 Cover log discardable, pick from #12286
  pkg/util/export/batch_processor.go
Labels: kind/bug, size/S

#12198 fileservice: write to disk cache in S3FS.Write and Read
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/file_cache.go
  pkg/fileservice/s3_fs.go
  pkg/perfcounter/counter_set.go
Labels: size/M, kind/enhancement

#12243 fileservice: fix oidc credentials
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M

#12138 chore: rename lg function to log10
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/func_builtin_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/momath/math.go
  test/distributed/cases/function/func_math_lg.result
  test/distributed/cases/function/func_math_log10.result
  test/distributed/cases/function/func_math_log10.test
Labels: kind/feature, size/M

#12280 fix panic and missing info when calling mo-ctl
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: kind/bug, size/M, kind/enhancement

#12253 [Feature]: CSV Export support for Vector Type
  cmd/mo-dump/main.go
  cmd/mo-dump/main_test.go
  pkg/container/types/types.go
  pkg/frontend/export.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/tae/common/print.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/load_data/load_data_array.result
  test/distributed/cases/load_data/load_data_array.sql
  test/distributed/resources/load_data/array_out.csv
Labels: kind/feature, size/S

#12241 cn upgrade once
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/types.go
Labels: kind/bug, size/S

#12281 generate_series with only one parameter
  pkg/sql/colexec/table_function/generate_series.go
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
Labels: size/S

#12306 addTag12305
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql
Labels: size/XS

#12287 fix stripping comment
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/dialect/mysql/scanner_test.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/parsers/sqlparse_test.go
Labels: kind/bug, size/M
