Repository matrixorigin/matrixone, pull requests merged in 2023-02, with the labels that each got.

#7766 [Plan] Fix a bug in filter push-down involving MARK join
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S

#7776 fix a pipeline cleanup bug may cause hung
  pkg/common/bitmap/bitmap.go
  pkg/vm/pipeline/types.go
Labels: kind/bug, size/S

#7702 moctl: add force GC command
  pkg/pb/ctl/ctl.pb.go
  pkg/sql/plan/function/builtin/ctl/cmd_gc.go
  pkg/sql/plan/function/builtin/ctl/types.go
  proto/ctl.proto
Labels: kind/feature, size/S

#7594 gc catalog
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
Labels: kind/feature, size/M

#7781 fix ckp ut
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/bug, size/S

#7774 function_instr cases
  test/distributed/cases/function/function_instr.result
  test/distributed/cases/function/function_instr.sql
Labels: size/L

#7756 function_mid cases
  test/distributed/cases/function/function_mid.result
  test/distributed/cases/function/function_mid.sql
Labels: size/M

#7782 fix #7779
  pkg/sql/plan/build_delete.go
Labels: kind/bug, size/XS

#7780 Change bvt for auto_incr cache.
  pkg/frontend/types.go
  test/distributed/cases/transaction/isolation_2.result
  test/distributed/cases/transaction/isolation_2.sql
Labels: kind/bug, size/M

#7784 get metadata if needed before calc stats
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/M

#7604 trace/log data logs tae (mo native format) file
  cmd/mo-service/main.go
  pkg/config/configuration.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/util/export/etl/csv.go
  pkg/util/export/etl/csv_test.go
  pkg/util/export/etl/tae.go
  pkg/util/export/etl/tae_test.go
  pkg/util/export/example/main.go
  pkg/util/export/fs_writer.go
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
  pkg/util/export/observability/logs/log.go
  pkg/util/export/observability/metrics/metric.go
  pkg/util/export/observability/schema.go
  pkg/util/export/observability/trace/span.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/export/table/type.go
  pkg/util/export/table/type_test.go
  pkg/util/export/type.go
  pkg/util/export/writer/tae_test.go
  pkg/util/export/writer_factory.go
  pkg/util/metric/cron_task.go
  pkg/util/metric/m_server_test.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_collector.go
  pkg/util/metric/metric_collector_test.go
  pkg/util/metric/metric_test.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/example/main.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/ptrace.go
  pkg/util/trace/impl/motrace/report_error.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/schema.go
  pkg/util/trace/impl/motrace/schema_test.go
  pkg/util/trace/impl/motrace/trace.go
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
  test/distributed/cases/table/mix_csv_tae.result
  test/distributed/cases/table/mix_csv_tae.sql
  test/distributed/cases/zz_accesscontrol/alter_account.result
  test/distributed/cases/zz_accesscontrol/alter_account.sql
  test/distributed/resources/external_table_file/mix/csv/1672722966_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL.csv
  test/distributed/resources/external_table_file/mix/csv/1672722981_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL.csv
  test/distributed/resources/external_table_file/mix/tae/1673512274_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_612930000.tae
  test/distributed/resources/external_table_file/mix/tae/1673512289_7c4dccb4-4d3c-41f8-b482-5251dc7a41bf_ALL_612978000.tae
Labels: kind/bug, kind/feature, size/XXL

#7790 [Test]: add bvt case
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
  test/distributed/resources/load_data/test.csv
Labels: size/L, kind/test-ci

#7759 lockservice: opt memory allocation and concurrency model
  go.mod
  go.sum
  pkg/lockservice/btree_storage.go
  pkg/lockservice/lockTable.go
  pkg/lockservice/lock_table.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/lockservice/slice.go
  pkg/lockservice/slice_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
Labels: kind/enhancement, size/XL

#7703 update error message, update force flush duration
  pkg/sql/plan/function/builtin/ctl/cmd_checkpoint.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/replay_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/moengine/engine.go
  pkg/vm/engine/tae/moengine/types.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#7786 add shuffle for join
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/merge/types.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  proto/pipeline.proto
Labels: kind/enhancement, size/L

#7787 load jsonline cases
  test/distributed/cases/function/func_aggr_avg.test
  test/distributed/cases/function/func_aggr_count.test
  test/distributed/cases/load_data/load_data_jsonline.result
  test/distributed/cases/load_data/load_data_jsonline.test
  test/distributed/resources/load_data/char_varchar_1.jl
  test/distributed/resources/load_data/char_varchar_1_array.json
  test/distributed/resources/load_data/char_varchar_1_array.json.gz
  test/distributed/resources/load_data/float_1.json
  test/distributed/resources/load_data/float_1.json.lz4
  test/distributed/resources/load_data/float_1_array.jl
  test/distributed/resources/load_data/integer_numbers_1.jl
  test/distributed/resources/load_data/integer_numbers_1.jl.bz2
  test/distributed/resources/load_data/integer_numbers_1_array.jl
  test/distributed/resources/load_data/time_date_1.jl
  test/distributed/resources/load_data/time_date_1_array.jl
Labels: size/M

#7597 [Bug] Fix show stmt with account_id condition
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/bug, size/M

#7500 contributors readme action update
  README.md
Labels: size/XS

#7807 Improve lock service performance
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock_table.go
  pkg/lockservice/service_test.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_test.go
Labels: kind/enhancement, size/M

#7805 fix show in begin ... commit
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: kind/bug, size/M

#7800 function_split_part cases
  test/distributed/cases/function/function_split_part.result
  test/distributed/cases/function/function_split_part.sql
Labels: size/L

#7822 disable gc catalog
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
Labels: size/S

#7812 fix ctrl+c mo not shutdown with tasks running in stopper
  cmd/mo-service/main.go
  pkg/frontend/internal_executor.go
  pkg/util/export/example/main.go
  pkg/util/metric/cron_task.go
  pkg/util/metric/metric.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/example/main.go
  pkg/util/trace/impl/motrace/trace.go
Labels: kind/bug, size/S

#7788 Para load
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/result_scan.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
Labels: kind/bug, kind/feature, size/XXL

#7809 function_group_concat cases
  test/distributed/cases/function/function_group_concat.result
  test/distributed/cases/function/function_group_concat.sql
Labels: size/L

#7824 delete stale segments
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/tables/jobs/helper.go
Labels: kind/bug, size/S

#7819 Fix issue 7770
  pkg/vm/engine/tae/txn/txnimpl/index.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/S

#7825 Change stored alter view sql for show create view
  pkg/sql/plan/build_ddl.go
Labels: kind/bug, size/S

#7801 support sort cluster by keys
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/util/composite_clusterby_util.go
  test/distributed/cases/dml/insert/insert.result
  test/distributed/cases/dml/insert/insert.test
  test/distributed/resources/load_data/integer.csv
  test/distributed/resources/load_data/integer2.csv
Labels: kind/bug, size/M

#7833 [Bug]: create temporary table cluster by reported panic error
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/bug, size/XS

#7816 adjust query type and quote create param fields
  pkg/sql/parsers/tree/format.go
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/sql/parsers/tree/update.go
  test/distributed/cases/statement_query_type/statement_query_type.result
Labels: kind/enhancement, size/M

#7830 fix memory leak in plan cache
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/plan_cache.go
  pkg/frontend/session.go
Labels: size/S

#7799 Change in auto_incr
  pkg/sql/colexec/auto_incr.go
  test/distributed/cases/function/account_info_func.result
  test/distributed/cases/function/account_info_func.sql
Labels: size/S

#7826 refactoring stats api and make stats more accurate when clusterby column
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/utils.go
  pkg/sql/util/composite_clusterby_util.go
  pkg/util/metric/test/cron_task_test.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
Labels: kind/bug, kind/enhancement, size/M

#7714 Fengttt probe
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
  pkg/common/moprobe/probe.go
  pkg/vm/engine/disttae/partition.go
Labels: size/S, kind/test-ci

#7837 Cluster by and conflict transaction cases
  test/distributed/cases/transaction/conflict_transation.result
  test/distributed/cases/transaction/conflict_transation.sql
  test/distributed/resources/load_data/ct_file.csv
  test/distributed/resources/load_data/sort_key_1.csv
Labels: size/M

#7838 add temp err msg
  pkg/vm/engine/tae/moengine/txn_relation.go
Labels: kind/enhancement, size/XS

#7791 Primary key transfer
  pkg/frontend/session.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/auto_incr_test.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/update/update.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/dml.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/types.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/storage_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/format.go
  pkg/vm/engine/gob.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/moengine/database.go
  pkg/vm/engine/tae/moengine/helper.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/distributed/cases/ddl/primary_key_transfer.result
  test/distributed/cases/ddl/primary_key_transfer.sql
Labels: kind/feature, size/L

#7843 [Test]: add save query result test
  test/distributed/cases/benchmark/tpch/03_QUERIES/test_tpch_query_cache.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/test_tpch_query_cache.sql
  test/distributed/cases/save_query_result/save_query_result.result
  test/distributed/cases/save_query_result/save_query_result.sql
  test/distributed/resources/load_data/test_1.csv
Labels: size/XXL, kind/test-ci

#7821 [Bug] Fix show columns order
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dtype/uuid_type_and_uuid_func.result
  test/distributed/cases/table/create_table.result
  test/distributed/cases/table/create_table.test
Labels: kind/bug, size/M

#7851 adjust stats
  pkg/sql/plan/utils.go
  pkg/sql/util/composite_clusterby_util.go
Labels: kind/enhancement, size/S

#7708 Add trim function
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/builtin/multi/trim.go
  pkg/sql/plan/function/builtin/multi/trim_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  test/distributed/cases/function/builtin.result
  test/distributed/cases/function/builtin.sql
Labels: kind/feature, size/L

#7856 Output precision and scale for Decimal in explain to help debugging
  pkg/sql/plan/explain/explain_expr.go
Labels: kind/enhancement, size/XS

#7840 fix view recursive reference
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/view.go
  pkg/sql/plan/Makefile
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/vm/engine/memoryengine/compiler_context.go
  test/distributed/cases/view/alterview.result
  test/distributed/cases/view/alterview.sql
Labels: kind/bug, size/XXL

#7855 fix load from s3 bugs
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: kind/bug, size/S

#7859 fix the issue 7853
  pkg/sql/compile/cnserviceDriver.go
Labels: kind/bug, size/S

#7857 fileservice: role arn fixes
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/S

#7842 Partition semantic check
  pkg/frontend/session.go
  pkg/pb/plan/plan.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_util.go
  pkg/sql/plan/types.go
  proto/plan.proto
  test/distributed/cases/ddl/partition.result
  test/distributed/cases/ddl/table_partition.result
  test/distributed/cases/ddl/table_partition.test
Labels: kind/bug, size/XL

#7852 show_cases
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/M

#7868 fix panic during the table joins itself
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/dml/select/select_issue7858.result
  test/distributed/cases/dml/select/select_issue7858.sql
Labels: kind/bug, size/S

#7874 [Bug]: The value of Stats Field contains NaN，which cause background s…
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#7866 Add getTableMeta err messages
  pkg/objectio/block.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/XS

#7849 [Fix] CnVector Window() Nsp StartOffset
  pkg/container/nulls/nulls.go
  pkg/container/nulls/nulls_test.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
Labels: kind/bug, size/S

#7865 fix same col name in save query result
  pkg/catalog/types.go
  pkg/frontend/query_result.go
  pkg/sql/plan/meta_scan.go
  test/distributed/cases/save_query_result/save_query_result.result
  test/distributed/cases/save_query_result/save_query_result.sql
Labels: size/L

#7803 fix some bugs about sql_type
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/types.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/utils.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/L

#7839 fix 7709
  pkg/frontend/session.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/query_builder.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/table/mix_csv_tae.sql
Labels: kind/bug, size/S

#7861 [Enhancement]: Transitivity of equalities
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
Labels: kind/enhancement, size/M

#7878 fix primary key show bug in the show columns
  pkg/sql/plan/build_show.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
  test/distributed/cases/dtype/uuid_type_and_uuid_func.result
Labels: kind/bug, size/M

#7860 function mo_log_date
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/plan/function/builtin/ctl/mo_log_date.go
  pkg/sql/plan/function/builtin/ctl/mo_log_date_test.go
  pkg/sql/plan/function/builtins.go
  pkg/sql/plan/function/function_id.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  test/distributed/cases/function/func_mo_log_date.result
  test/distributed/cases/function/func_mo_log_date.sql
  test/distributed/resources/external_table_file/mix/2023/02/06/ex_table_2_18.csv
Labels: kind/feature, size/M

#7863 fix mo reboot report unique key conflict
  pkg/common/moerr/error.go
Labels: kind/bug, size/XS

#7729 prolong task service connection timeout
  pkg/taskservice/task_service_holder.go
Labels: kind/enhancement, size/XS

#7869 improve the merge-order performance
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/order_test.go
  pkg/sql/colexec/mergeorder/types.go
Labels: kind/enhancement, size/M

#7902 Add alter view
  test/distributed/cases/view/alter_view.result
  test/distributed/cases/view/alter_view.sql
Labels: size/M

#7903 fix bug 7893
  pkg/sql/compile/ddl.go
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
Labels: kind/bug, size/S

#7907 fix task return when error task run failed
  pkg/taskservice/task_runner.go
Labels: kind/bug, size/XS

#7894 fix compact2 ut
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/tables_test.go
Labels: kind/enhancement, size/S

#7895 keep data transfer in load local even err occurs
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/plan/build_load.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#7908 remove bvt tag
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: size/S, kind/test-ci

#7916 external filter
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#7915 remove bvt tag
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
Labels: size/S, kind/test-ci

#7914 Fix bug: get tables is incorrect by non-sys account or after truncate table
  pkg/vm/engine/disttae/cache/catalog.go
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
Labels: kind/bug, size/S

#7921 add debuginfo
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_manager.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/enhancement, size/S

#7920 minor refacor in frontend
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
Labels: size/S, kind/refactor

#7927 Forced release of pipeline's resources
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/compile.go
  pkg/vm/pipeline/pipeline.go
Labels: kind/bug, kind/enhancement, size/S

#7925 disttae: refactor partition locking
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/S

#7928 Remove bvt tag
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: size/S

#7933 add selectivity in Stats and adjust join order
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/utils.go
  proto/plan.proto
Labels: kind/enhancement, size/S

#7940 ring: fix unstable tests
  pkg/util/ring/ring_test.go
Labels: kind/bug, size/XS

#7899 fix load big file from s3 oom
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#7926 check the sequence of morpc package and checkSum
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/tests/txn/cluster_basic_test.go
  proto/pipeline.proto
  test/distributed/cases/function/func_aggr_avg.test
  test/distributed/cases/function/func_aggr_count.test
Labels: kind/bug, size/M

#7936 foreign key cases
  test/distributed/cases/ddl/unique_secondary_index.result
  test/distributed/cases/ddl/unique_secondary_index.sql
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: size/L

#7930 External filepath filter bugfix
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#7918 fix bug: FK is comp-PK reported error
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/fk_base.sql
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: kind/bug, size/S

#7950 Fix inference bug for decimal scale
  pkg/sql/colexec/agg/new.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/mock.go
  test/distributed/cases/benchmark/tpch/03_QUERIES/q1.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q10.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q15.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q3.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q5.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q7.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/q7.sql
  test/distributed/cases/benchmark/tpch/03_QUERIES/q9.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/test_tpch_query_cache.result
  test/distributed/cases/benchmark/tpch/03_QUERIES/test_tpch_query_cache.sql
Labels: kind/bug, size/L

#7945 frondend: opt multi-address listening
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/frontend/server.go
Labels: kind/enhancement, size/M

#7911 add max concurrency for cron tasks
  pkg/pb/task/task.pb.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_cron_test.go
  pkg/util/metric/cron_task.go
  proto/task.proto
Labels: kind/bug, kind/enhancement, size/S

#7947 fix releasing the mempool twice
  pkg/frontend/routine.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/bug, size/S

#7953 fix bug: show indexes error in non-sys account
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/expr_eval.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#7955 fix comment escape char
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/util/util.go
  test/distributed/cases/comment/comment.result
  test/distributed/cases/dml/show/show.result
Labels: size/L

#7938 minor refactor in plan
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_util.go
Labels: size/M, kind/refactor

#7959 Fix the bug of prefetch
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/XS

#7958 Fix bug: foreign key msg is missing in show create table
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: kind/bug, size/L

#7952 [Feature] Add accountName col in mo_mysql_compatbility_mode table
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/alter.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/feature, size/XXL

#7969 fix data race, disable entry.close()
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
Labels: kind/bug, size/S

#7964 add cn TaskRunner ReservedTasks
  pkg/cnservice/types.go
Labels: kind/enhancement, size/XS

#7922 fix load local
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/plan/build_load.go
Labels: kind/bug, size/S

#7970 Move index def
  pkg/frontend/session.go
  pkg/pb/plan/plan.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_partition_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/types.go
  pkg/vm/engine/types.go
  pkg/vm/engine/types_test.go
  proto/plan.proto
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: kind/bug, size/XL

#7963 CI: Add an pr issue bot
  .github/workflows/docu_check.yaml
Labels: size/S, kind/test-ci

#7967 modify error msg of empty query result
  pkg/sql/plan/result_scan.go
  test/distributed/cases/benchmark/tpch/03_QUERIES/test_tpch_query_cache.result
Labels: size/S

#7931 morpc: valid messages before actually sending
  pkg/common/morpc/backend.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/server.go
  pkg/common/morpc/types.go
  pkg/logservice/client_test.go
  pkg/logservice/service_test.go
  pkg/vm/engine/tae/logtail/service/service_test.go
Labels: kind/bug, size/S

#7944 add missing mem count and change time to nanosec for analyze info
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/process/analyze.go
Labels: kind/enhancement, size/S

#7982 fix #7901 and change the dispatch remote function to a more suitable way
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/cnserviceDriver.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/types.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  proto/pipeline.proto
Labels: kind/bug, kind/enhancement, size/L

#7932 fileservice: add random offset and size read tests for ReadCloserForRead; add credentials cache
  pkg/fileservice/file_service_test.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/S

#8000 Update segmentation logic according to PR #7931
  pkg/vm/engine/tae/logtail/service/response.go
  pkg/vm/engine/tae/logtail/service/service_test.go
Labels: kind/enhancement, size/S, kind/refactor

#7924 add mo_ctl Inspect to check information in tae
  go.mod
  go.sum
  pkg/pb/ctl/ctl.pb.go
  pkg/sql/plan/function/builtin/ctl/cmd_inspectdn.go
  pkg/sql/plan/function/builtin/ctl/types.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/inspect.go
  proto/ctl.proto
Labels: kind/enhancement, kind/feature, size/M

#8024 fileservice: try to detect bucket region if not provided
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/enhancement, size/S

#7971 correct statement_info.database col value, while exec multi stmt in one req
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/log/query_version.result
  test/distributed/cases/log/query_version.sql
Labels: kind/bug, size/S

#7973 morpc: make header not counted in the maxMessageSize
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/codec.go
  pkg/logservice/client_test.go
Labels: kind/enhancement, size/S

#7978 temporary recovery logic for update/delete in begin txn
  pkg/vm/engine/disttae/partition_reader.go
Labels: kind/bug, size/XS

#8022 add bvt tag for issue7748
  test/distributed/cases/function/func_aggr_avg.test
  test/distributed/cases/function/func_aggr_count.test
Labels: size/XS

#7999 Change pull_request to pull_request_target docu_check.yaml
  .github/workflows/docu_check.yaml
Labels: size/S, kind/test-ci

#8003 refactor index Field
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/partition.go
  pkg/sql/util/index_util.go
  pkg/sql/util/index_util_test.go
  proto/plan.proto
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
Labels: kind/enhancement, size/M

#8026 fix: bvt unstable output with those failed stmt
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/S

#8001 fix bug: trace lost query end info if query is killed
  pkg/util/export/batch_processor.go
Labels: kind/bug, size/S

#8004 enhance mo-dump
  cmd/mo-dump/main.go
  cmd/mo-dump/main_test.go
Labels: kind/bug, kind/enhancement, size/M

#8007 refactor stats api and add some comment
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/function/builtin/ctl/table_stat_test.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/moengine/engine_test.go
  pkg/vm/engine/tae/moengine/relation.go
  pkg/vm/engine/types.go
  proto/plan.proto
Labels: kind/enhancement, size/L

#8020 fix bug about sql_source_type
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#8005 [Feature] Change select version() result when alter mo_mysql_compatbility_mode config
  pkg/container/types/json.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/sql/plan/function/builtin/binary/json_extract.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/feature, size/M

#8035 change err info
  pkg/vm/engine/disttae/partition_reader.go
Labels: size/XS

#8033 roll back broadcast join
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: kind/bug, size/M

#8031 CI: fix the bug of pr_coverage
  .github/workflows/coverage_pr.yml
Labels: size/S, kind/test-ci

#7957 simplify lockservice waiter logic
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
Labels: size/M, kind/refactor

#8039 Fix coverage bug
  .github/workflows/coverage_pr.yml
  .github/workflows/docu_check.yaml
Labels: size/XS, kind/test-ci

#8048 Coverage struct redesign
  .github/workflows/coverage_pr.yml
Labels: size/S, kind/test-ci

#8049 revert commits of right outer join
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/join_test.go
  pkg/sql/colexec/right/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/query_builder.go
  pkg/vm/overload.go
  pkg/vm/types.go
  test/distributed/cases/join/rightjoin.result
  test/distributed/cases/join/rightjoin.sql
Labels: kind/bug, size/XL

#8047 adjust stats and join order
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/util/composite_clusterby_util.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/enhancement, size/M

#8053 support lock/unlock table syntax in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/lock.go
Labels: kind/feature, size/XXL

#8046 Add cost time and fix bool print in mo-dump
  cmd/mo-dump/main.go
Labels: kind/bug, size/XS

#8041 rewrite remoteRun code and clean some confused code
  pkg/pb/pipeline/pipeline.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scopeRemoteRun_test.go
Labels: size/L, kind/refactor

#8057 string_format
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: size/M

#7746 support multi-paths in json_extract
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/utils.go
  pkg/container/types/json.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/function/builtin/binary/datediff_test.go
  pkg/sql/plan/function/builtin/binary/json_extract.go
  pkg/sql/plan/function/builtin/binary/json_extract_test.go
  pkg/sql/plan/function/builtin/binary/timediff_test.go
  pkg/sql/plan/function/builtin/multi/json_extract.go
  pkg/sql/plan/function/builtin/multi/json_extract_test.go
  pkg/sql/plan/function/builtins.go
  pkg/vectorize/json_extract/json_extract.go
  pkg/vectorize/json_extract/json_extract_test.go
  test/distributed/cases/function/func_json_extract.result
  test/distributed/cases/function/func_json_extract.test
Labels: kind/enhancement, kind/feature, size/L, kind/refactor

#8063 fix account level config error
  pkg/frontend/authenticate.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#8044 change ast tree for on duplicate key clause
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/insert.go
  pkg/sql/plan/build_insert.go
Labels: kind/feature, size/XXL, kind/refactor

#8069 fileservice: add FileService.StatFile
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/M

#8070 fix getsqlType func bug
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#8068 update Merge CMD
  pkg/vm/engine/tae/tables/txnentries/command_test.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
Labels: size/S

#8073 cn: fix rpc config not work for cn
  cmd/mo-service/main.go
  pkg/cnservice/cnclient/client.go
  pkg/cnservice/server.go
Labels: kind/bug, size/S

#8030 morpc: make write message synchronously as default
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/client.go
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/future.go
  pkg/common/morpc/future_test.go
  pkg/common/morpc/server.go
  pkg/common/morpc/server_test.go
  pkg/logservice/message.go
  pkg/vm/engine/tae/logtail/service/response.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/service_test.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/utils.go
  pkg/vm/engine/tae/logtail/service/utils_test.go
Labels: kind/enhancement, size/L

#8061 adjust stats
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#8075 Disable the problematic code which affects join order
  pkg/sql/plan/join_order.go
Labels: kind/bug, size/S

#8076 Resolve huang and fix some memory issues
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/types.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/build_test.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/process/types.go
Labels: kind/bug, size/L

#8055 Fix bug: relkind of some special tables is incorrect
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/sql/colexec/auto_incr.go
  pkg/sql/colexec/auto_incr_test.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  pkg/util/sysview/sysview.go
  pkg/vm/engine/disttae/database.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/table.go
  pkg/vm/engine/disttae/tools.go
  test/distributed/cases/dml/delete/delete_index.result
  test/distributed/cases/dml/delete/delete_index.test
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
  test/distributed/cases/function/account_info_func.result
  test/distributed/cases/function/account_info_func.sql
Labels: kind/bug, size/M

#8085 fileservice: optimize FileWithChecksum.readBlock
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/pool.go
  pkg/fileservice/pool_test.go
Labels: kind/enhancement, size/M

#8083 clean code
  pkg/frontend/cmd_executor.go
  pkg/frontend/load.go
  pkg/frontend/load_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/query_result.go
  pkg/frontend/session.go
  pkg/frontend/status_stmt.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/load_data/import_data.result
  test/distributed/cases/load_data/import_data.sql
  test/distributed/cases/table/temporary_table/various_test.result
  test/distributed/cases/table/temporary_table/various_test.sql
Labels: kind/enhancement, size/XXL

#8088 use method of filestat to get file size
  pkg/catalog/catalog.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/table_function/meta_scan.go
Labels: size/M

#8092 update gc catalog
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
Labels: kind/feature, size/M

#8078 show_test
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/S

#7981 Lock based mpool/freelist. Work around #7867
  pkg/cnservice/memory_engine.go
  pkg/common/morpc/codec_test.go
  pkg/common/mpool/freelist.go
  pkg/common/mpool/mpool.go
  pkg/common/mpool/mpool_test.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/testutil/util_function.go
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/process/process.go
Labels: kind/bug, size/L, kind/refactor

#8099 fileservice: add parallel pool benchmark
  pkg/fileservice/pool.go
  pkg/fileservice/pool_test.go
Labels: kind/enhancement, size/S

#8094 refactor parser for case sensitivity
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/dialect/mysql/scanner_test.go
  pkg/sql/parsers/tree/cstr.go
  pkg/sql/parsers/tree/cstr_test.go
  pkg/sql/parsers/tree/select.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
Labels: size/XXL
