Repository matrixorigin/matrixone, pull requests merged in 2023-08, with the labels that each got.

#10916 [refactor] clean up port configs.
  cmd/mo-service/config.go
  cmd/mo-service/main.go
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-with-proxy/cn1.toml
  etc/launch-with-proxy/cn2.toml
  etc/launch-with-proxy/dn.toml
  pkg/cnservice/cnclient/client.go
  pkg/cnservice/server.go
  pkg/cnservice/server_ctl.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/server_query.go
  pkg/cnservice/service_ports.go
  pkg/cnservice/service_ports_test.go
  pkg/cnservice/types.go
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/dnservice/service_ports.go
  pkg/dnservice/service_ports_test.go
  pkg/dnservice/store.go
  pkg/dnservice/store_ctl.go
  pkg/dnservice/store_heartbeat.go
  pkg/logservice/config.go
  pkg/logservice/config_test.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_test.go
  pkg/logservice/testclient.go
  pkg/tests/service/logservice.go
  pkg/tests/service/network.go
  pkg/tests/service/service.go
  pkg/util/address/address.go
Labels: size/L, kind/refactor

#10942 fix 10835
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#10936 improve performance in pessimistic mode
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/client.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/S

#10944 [bug] remove the default value for logservice ports.
  pkg/logservice/config.go
Labels: kind/bug, size/XS

#10940 fileservice: add StatementProfileNewSpan, SetStatementProfilerFrom
  pkg/fileservice/profile_statement.go
  pkg/frontend/computation_wrapper.go
  pkg/util/trace/impl/motrace/mo_trace.go
Labels: size/S

#10939 add log for 10656
  pkg/sql/compile/scope.go
Labels: kind/enhancement, size/S

#10937 small update to some id utils
  pkg/objectio/id.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: size/M, kind/refactor

#10943 refactor stats
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: kind/enhancement, size/M

#10941 fileservice: add callbacks for disk cache written and evict
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_callbacks.go
  pkg/fileservice/disk_cache_test.go
Labels: size/M

#10881 allow the last operator can be both connector and dispatch
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#10951 fix GetConstSetFunction bug which cause wrong join result.
  pkg/container/vector/functionTools.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/types.go
  pkg/sql/colexec/rightanti/join.go
  test/distributed/cases/dtype/binary.result
Labels: kind/bug, size/M

#10952 lruobjcache: improve performance of LRU.Get
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/fileservice/objcache/lruobjcache/lru_test.go
Labels: size/S

#10949 improve check pk changed in range
  pkg/sql/colexec/lockop/lock_op.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/S

#10979 fileservice: add IOEntry.fromCache to reduce unnecessary cache update
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/mem_cache.go
Labels: kind/enhancement, size/S

#10980 Revert "lruobjcache: improve performance of LRU.Get (#10952)"
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/fileservice/objcache/lruobjcache/lru_test.go
Labels: size/S

#10950 fix send recursive bat order
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/mergecte/mergecte.go
  pkg/sql/colexec/mergerecursive/mergerecursive.go
Labels: size/S

#10983 improve performance for check pk dup
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
Labels: kind/enhancement, size/M

#10989 bond logservice's 42345:12345 while docker-compose do startup
  etc/launch-tae-compose/compose.yaml
Labels: kind/enhancement, size/XS

#10988 add default panic handler for log append task
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
Labels: kind/bug, size/XS

#10991 missing set queue default size
  pkg/common/morpc/cfg.go
Labels: kind/bug, size/XS

#10994 add a batch splitter
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/batch_test.go
  pkg/vm/engine/tae/containers/types.go
Labels: kind/feature, size/S

#10995 fix checks pk changed with the wrong timestamp
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/bug, size/XS

#10999 fix window partition order
  pkg/sql/colexec/window/window.go
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/S

#10917 Auto increment
  test/distributed/cases/auto_increment/auto_increment.result
  test/distributed/cases/auto_increment/auto_increment.sql
Labels: kind/feature, size/XL

#10956 using sensor during prefetch
  pkg/objectio/extent.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/common/utils/sensor.go
  pkg/vm/engine/tae/common/utils/types.go
Labels: kind/feature, size/M, kind/refactor

#11001 optimize hashmap memory allocation
  pkg/sql/colexec/hashbuild/build.go
Labels: kind/enhancement, size/S

#10938 Remove tag 10848
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: size/XS, kind/test-ci

#11007 improve performance for checking PK dup in some cases
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_update.go
Labels: kind/enhancement, size/M

#10982 Alter table reference foreign key
  pkg/common/moerr/error.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  proto/plan.proto
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.sql
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.result
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
Labels: kind/bug, kind/feature, size/XL

#11005 addup anal.Output for right join
  pkg/sql/colexec/right/join.go
Labels: kind/bug, size/XS

#11021 improve perf
  pkg/cnservice/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
Labels: kind/enhancement, size/M

#11022 support shuffle join
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopmark/join_test.go
  pkg/sql/colexec/loopsemi/join_test.go
  pkg/sql/colexec/loopsingle/join_test.go
  pkg/sql/colexec/mark/join_test.go
  pkg/sql/colexec/product/product_test.go
  pkg/sql/colexec/right/join_test.go
  pkg/sql/colexec/rightanti/join_test.go
  pkg/sql/colexec/rightsemi/join_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  proto/pipeline.proto
Labels: kind/feature, size/M

#11011 fix bug: select partition table for update not working
  pkg/sql/plan/build_update.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#11023 Add metric mo_log_message_count and check the count value in CI
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e-standalone.yml
  optools/check_log_count.sh
  pkg/config/configuration.go
  pkg/util/metric/m_mo.go
  pkg/util/metric/m_register.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/mometric/metric_exporter.go
  pkg/util/trace/impl/motrace/report_log.go
Labels: kind/feature, size/M, kind/test-ci

#11033 fix panic in waiters iter
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
Labels: kind/bug, size/M

#11042 update ut
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/testutils/helpers.go
Labels: size/S

#11031 fix the issue which mignt lost error
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S

#11014 Conf refactor
  .github/workflows/ci.yml
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e-standalone.yml
  .github/workflows/release.yml
  .github/workflows/robot.yml
  cmd/mo-service/config.go
  etc/bootstrap-example/README.md
  etc/bootstrap-example/log-node-1.toml
  etc/bootstrap-example/log-node-2.toml
  etc/bootstrap-example/log-node-3.toml
  etc/bootstrap-example/log-node-4.toml
  etc/bootstrap-example2/README.md
  etc/bootstrap-example2/dn-node-1.toml
  etc/bootstrap-example2/dn-node-2.toml
  etc/bootstrap-example2/log-node-1.toml
  etc/bootstrap-example2/log-node-2.toml
  etc/bootstrap-example2/log-node-3.toml
  etc/bootstrap-example2/log-node-4.toml
  etc/cn-minimal-test.toml
  etc/cn-non-dist-memory.toml
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-dist-tae.toml
  etc/cn-standalone-test.toml
  etc/dn-minimal-s3-test.toml
  etc/dn-minimal-test.toml
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-CN-tae-DN/launch.toml
  etc/launch-tae-CN-tae-DN/log.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-tae-multi-CN-tae-DN/launch.toml
  etc/launch-tae-multi-CN-tae-DN/log.toml
  etc/launch/cn.toml
  etc/launch/cn1.toml
  etc/launch/dn.toml
  etc/launch/dn1.toml
  etc/launch/launch.toml
  etc/launch/log.toml
  etc/launch/log1.toml
  etc/launch/log2.toml
  etc/launch/log3.toml
  etc/log-minimal-test.toml
  pkg/cnservice/types.go
  pkg/config/configuration.go
  pkg/tests/service/cnservice.go
Labels: size/L, kind/refactor, kind/test-ci

#11041 [bug] load data: fix the timeout bug when load 1T data.
  pkg/common/morpc/cfg.go
  pkg/common/morpc/cfg_test.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
Labels: kind/bug, size/S

#10998 CI: change milestone and delete unuse action
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#11000 fileservice: benchmark codes clean-ups
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: size/M

#11034 fix replace panic when table has no keys
  pkg/sql/compile/scope.go
  pkg/sql/plan/build_replace.go
  test/distributed/cases/dml/replace/replace.result
  test/distributed/cases/dml/replace/replace.test
Labels: kind/bug, size/S

#11044 use real error instead of deadlock error
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/service.go
  pkg/lockservice/txn.go
Labels: kind/bug, size/S

#11012 handle on duplicate key issue
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
Labels: size/S

#11060 Revert "handle on duplicate key issue"
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
Labels: size/S

#11058 fix csv serialization
  cmd/mo-dump/main.go
  cmd/mo-dump/main_test.go
Labels: kind/bug, size/M

#11057 [feature] proxy: replay prepared stmt on connection migration.
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/server_conn_test.go
Labels: kind/feature, size/M

#11062 [Bug]: multi cn bvt test ：cn panic
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#11053 fix concurrency pipeline in recursive cte
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/mergerecursive/mergerecursive.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: kind/bug, size/S

#11063 optimize hash build by reducing memory reallocation
  pkg/container/batch/batch.go
  pkg/sql/colexec/hashbuild/build.go
Labels: kind/enhancement, size/S

#11071 optimize varlena function by reducing copy cost
  pkg/container/vector/vector.go
Labels: kind/enhancement, size/S

#11072 add skip label for bvt test case
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: kind/bug, size/XS

#11074 fix merge empty blocks and log duplicate batch
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/bug, size/S

#11077 Fix buffer leak if do aggr stmt
  pkg/common/util/uuid.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/export/table/table.go
  pkg/util/export/table/type.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
Labels: kind/bug, size/M

#11067 [feature] cn: add new config for init work state.
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/types.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  pkg/pb/metadata/metadata.go
  pkg/pb/metadata/metadata_test.go
  proto/logservice.proto
Labels: kind/feature, size/S

#11070 update for db ut
  pkg/vm/engine/tae/db/base_test.go
  pkg/vm/engine/tae/db/test/catalog_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/hidden_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/test/scheduler_test.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/db/test/txn_test.go
  pkg/vm/engine/tae/db/test/util_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: size/XXL, kind/test-ci

#11078 add txn gate
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
Labels: kind/feature, size/M

#11047 modify some case in different mode(optimistic/pessimistic)
  test/distributed/cases/optimistic/insert.result
  test/distributed/cases/optimistic/insert.test
  test/distributed/cases/pessimistic_transaction/insert.result
  test/distributed/cases/pessimistic_transaction/insert.test
Labels: size/L

#11003 logtailreplay: optimize checkpoints consumption
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/logtailreplay/partition_test.go
Labels: size/M

#11083 add compatibility ut
  pkg/vm/engine/tae/db/test/compatibility/all_test.go
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
  pkg/vm/engine/tae/db/test/compatibility/utils.go
  pkg/vm/engine/tae/db/testutil/engine.go
Labels: size/M, kind/test-ci

#11049 New partition system view
  pkg/bootstrap/bootstrap.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/pb/plan/plan.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/util.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_hash_test.go
  pkg/sql/plan/partition_list.go
  pkg/sql/util/util.go
  pkg/util/sysview/sysview.go
  proto/plan.proto
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/ddl/hash_key_partition.result
  test/distributed/cases/ddl/partition.result
  test/distributed/cases/ddl/partition_metadata.result
  test/distributed/cases/ddl/partition_metadata.sql
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/privilege/operate_catalog.result
  test/distributed/cases/tenant/privilege/operate_catalog.sql
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/bug, size/XL

#11075 [refactor] proxy: change some policies of selecting CN servers.
  pkg/clusterservice/selector.go
  pkg/clusterservice/selector_test.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/M, kind/refactor

#11087 adjust the position of `cluster by` option in the output of `show create table`
  pkg/sql/plan/build_show.go
  test/distributed/cases/dml/show/show3.result
  test/distributed/cases/dml/show/show3.sql
Labels: kind/bug, size/S

#11089 Modify the default rpc buffer size for mysql protocol server
  pkg/frontend/server.go
  pkg/frontend/types.go
Labels: kind/bug, size/XS

#11076 optimize hash build by preallocating hashmap
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/types.go
  pkg/container/hashtable/string_hash_map.go
  pkg/sql/colexec/hashbuild/build.go
Labels: kind/enhancement, size/S

#10620 Add statementId and sessionId to rawlog table
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/server_task.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_test.go
  pkg/frontend/util.go
  pkg/sql/plan/alter_util.go
  pkg/sql/plan/build_ddl.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/schema.go
  pkg/util/trace/impl/motrace/trace.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/dml/show/database_statistics.result
Labels: kind/bug, kind/enhancement, size/L

#11086 fix limit max active txn config not work
  pkg/cnservice/server.go
Labels: kind/bug, size/XS

#11052 fix a bug will cause empty agg result for 'processlist' and 'current_account'
  pkg/sql/colexec/table_function/current_account.go
  pkg/sql/colexec/table_function/processlist.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/colexec/table_function/types.go
Labels: kind/bug, size/M

#11094 subtask 10781 fix
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#11097 update for compatibility ut
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
Labels: size/S, kind/test-ci

#11090 fileservice: LRU related clean-ups
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/lrucache/lru.go
  pkg/fileservice/lrucache/lru_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/rc_bytes.go
  pkg/fileservice/rc_bytes_test.go
  pkg/fileservice/rc_pool.go
  pkg/fileservice/rc_pool_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/writer_test.go
  pkg/perfcounter/counter_set.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/model/index.go
Labels: kind/enhancement, size/L

#11069 support foreign key in more cases like MySQL
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/foreign_key/fk_base.result
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
Labels: kind/enhancement, size/S

#11106 update compatibility unit test
  pkg/vm/engine/tae/db/test/compatibility/all_test.go
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
  pkg/vm/engine/tae/db/test/compatibility/utils.go
Labels: size/M, kind/test-ci

#11109 Fix upgrader: do not panic for unknown type, instead skip it for now
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_test.go
Labels: kind/bug, size/S

#11119 fileservice: add per file read lock to reduce duplicated IO
  pkg/fileservice/io_entry.go
  pkg/fileservice/io_entry_reader.go
  pkg/fileservice/io_lock.go
  pkg/fileservice/io_lock_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/M

#11128 Revert "Revert "subtask 10781 fix" (#11102)"
  pkg/sql/compile/compile.go
Labels: kind/enhancement, size/S

#11080 handle add column with adding unique index
  pkg/sql/plan/build_ddl.go
Labels: kind/bug, size/S

#11127 add compatibility cases
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/utils.go
  pkg/vm/engine/tae/db/testutil/engine.go
Labels: size/M

#11115 optimize copy cost by expand different size
  pkg/container/vector/vector.go
Labels: kind/enhancement, size/S

#11133 dn vector wrapper supports const vector
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
Labels: kind/enhancement, size/M

#11129 add user txn flag
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
Labels: kind/enhancement, size/S

#11032 Implement IN filter on table scan
  pkg/container/types/decimal.go
  pkg/container/types/rowid.go
  pkg/container/types/txnts.go
  pkg/container/types/types.go
  pkg/container/types/uuid.go
  pkg/container/types/uuid_test.go
  pkg/container/vector/search.go
  pkg/container/vector/tools.go
  pkg/container/vector/utils.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/init.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compute.go
  pkg/vm/engine/tae/tables/functions.go
  proto/plan.proto
Labels: kind/feature, size/XL

#11137 fix a pipeline clean bug will cause hung
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/colexec/types.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/pipeline/types.go
Labels: kind/bug, size/S

#11132 Fix 10992 1
  pkg/container/batch/tools.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, size/M

#11084 support alter account in multi cn
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/handler.go
  pkg/queryservice/query_service.go
  pkg/queryservice/query_service_test.go
  pkg/queryservice/session_manager.go
  pkg/queryservice/session_manager_test.go
  proto/query.proto
Labels: kind/bug, size/M

#11138 fileservice: add CacheData, CacheDataAllocator; use Bytes as default cache data type
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/lrucache/lru.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/rc_bytes.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: size/M

#11103 reduce reset rc snapshot
  pkg/bootstrap/bootstrap.go
  pkg/cnservice/server_ctl.go
  pkg/frontend/test/txn_mock.go
  pkg/incrservice/service.go
  pkg/incrservice/store_mem.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/function/ctl/ctl.go
  pkg/txn/client/client.go
  pkg/txn/client/client_feature_test.go
  pkg/txn/client/client_test.go
  pkg/txn/client/leak_checker_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/enhancement, size/XL

#11100 Add zonemap sum
  pkg/container/types/decimal.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/plan/metadata_scan.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
  proto/plan.proto
Labels: kind/feature, size/S

#11099 fix a bug about null value handling in the insert process
  pkg/sql/plan/function/list_builtIn.go
Labels: kind/bug, size/M

#11104 Add approx_count
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: size/XXL

#11139 add upgrade ci test
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e_upgrade.yml
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: size/L, kind/test-ci

#11150 Revert "Add approx_count"
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: size/XXL

#11141 optimize shuffle join
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/S

#11148 fix lockservice ut failed
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_keeper_test.go
Labels: kind/bug, size/S, kind/test-ci

#11149 optimize prefetch
  pkg/vm/engine/tae/blockio/pipeline.go
Labels: kind/enhancement, size/S

#11147 const vector to support Window
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/containers/vector_test.go
Labels: kind/enhancement, size/S

#11135 Stats out traffic bytes
  pkg/frontend/export.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/protocol.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
Labels: kind/feature, size/M

#11145 remove unused expression code, optimize expression codes
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/mergetop/top.go
Labels: kind/enhancement, size/M

#11095 [refactor] proxy: change the delimiter in the username field.
  pkg/proxy/client_conn_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: size/S, kind/refactor

#11155 update configuration
  etc/launch-with-proxy/cn1.toml
  etc/launch-with-proxy/cn2.toml
  etc/launch-with-proxy/dn.toml
Labels: size/XS, kind/test-ci

#11120 add syntax of stream
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/stream.go
Labels: size/XXL

#11164 add commit slow log
  pkg/txn/service/service_cn_handler.go
Labels: kind/bug, size/XS

#11165 CI: modify the healthcheck for compose mo cluster
  .github/workflows/e2e-compose.yml
  optools/compose_bvt/entrypoint.sh
Labels: size/S, kind/test-ci

#11166 optimize shuffle join
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/M

#11093 bugfix: stmt entity need exported:true after StatementInfoUpdate
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#11159 add user transaction tag for connect from client
  pkg/frontend/txn.go
Labels: kind/feature, size/XS

#11028 [Feature] : Builtin SQRT Function
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/momath/math.go
  test/distributed/cases/function/func_math_exp.result
  test/distributed/cases/function/func_math_exp.test
  test/distributed/cases/function/func_math_log.result
  test/distributed/cases/function/func_math_log.test
Labels: kind/feature, size/S

#11170 fix unexpected errors in log
  pkg/frontend/session.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S

#11055 count expired task only once
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
Labels: kind/bug, size/S

#11173 add system variable version
  pkg/frontend/variables.go
Labels: kind/enhancement, size/XS

#11107 Adding full trace information to sql execution
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/plan/build.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
Labels: kind/enhancement, size/S

#11175 fix incrservice auto_increment overflow error msg
  pkg/incrservice/column_cache.go
Labels: kind/bug, size/S

#11073 Select for update cases
  test/distributed/cases/pessimistic_transaction/select_for_update.result
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
Labels: kind/feature, size/XL

#11179 print account id and db id of not found table
  pkg/vm/engine/disttae/txn_database.go
Labels: kind/enhancement, size/XS

#11176 update allocator for goetty in frontend
  go.mod
  go.sum
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/server.go
  pkg/frontend/types.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
Labels: kind/bug, size/M

#11153 Remove tag
  test/distributed/cases/optimistic/insert.test
Labels: size/XS

#11185 fix a bug that cause wrong shuffle method
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/XS

#11188 [feature] cn: implement kill conns when drop account in multi cns.
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/server_query.go
  pkg/cnservice/server_task.go
  pkg/config/configuration.go
  pkg/frontend/authenticate.go
  pkg/frontend/routine_manager.go
  pkg/pb/query/query.pb.go
  pkg/proxy/bootstrap.go
  pkg/proxy/bootstrap_test.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/config.go
  pkg/proxy/conn_manager.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/plugin_test.go
  pkg/proxy/router.go
  pkg/proxy/router_test.go
  pkg/proxy/server.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/sql_worker.go
  pkg/proxy/sql_worker_test.go
  pkg/queryservice/handler.go
  pkg/queryservice/query_service.go
  pkg/queryservice/query_service_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  proto/query.proto
Labels: size/XL, kind/refactor

#11189 remove batchfill in agg
  pkg/sql/colexec/agg/new.go
Labels: size/S

#11191 support more plan node to go shuffle in one query
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/S

#11177 optimize shuffle group on multicn
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/group/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: kind/enhancement, size/S

#11146 Fix task runner bug
  pkg/hakeeper/task/task_scheduler.go
  pkg/taskservice/task_runner.go
Labels: kind/bug, size/S

#10985 add alter account restricted cases
  test/distributed/cases/zz_accesscontrol/account_restricted.result
  test/distributed/cases/zz_accesscontrol/account_restricted.sql
Labels: kind/feature, size/M

#11193 optimize batch memory reuse
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/restrict/restrict.go
Labels: kind/enhancement, size/S

#11182 update metadata cache stats
  pkg/objectio/cache.go
  pkg/objectio/reader.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/runtime_filter.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/catalog/block.go
Labels: kind/enhancement, size/S

#11192 optimize shuffle join for right anti/semi/outer join
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/XS

#11156 Add approx_count
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: size/XXL

#11068 Feat group concat
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/group_concat.go
  pkg/sql/colexec/agg/new.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/having_binder.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  proto/pipeline.proto
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/function/function_group_concat.result
Labels: kind/feature, size/XL

#11196 set prefetch queue to unblocking
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/pipeline_test.go
  pkg/vm/engine/tae/logstore/sm/safeq.go
  pkg/vm/engine/tae/logstore/sm/sm_test.go
  pkg/vm/engine/tae/logstore/sm/types.go
Labels: kind/bug, kind/enhancement, size/M

#11200 add attr name when delete by pk and rowid
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS

#11208 optimize memory reuse
  pkg/vm/process/process.go
Labels: kind/enhancement, size/XS

#11199 fileservice: add CachePolicy
  pkg/fileservice/cache_policy.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/mem_cache.go
  pkg/objectio/funcs.go
Labels: kind/enhancement, size/S

#11209 Refactor object meta & load checkpoint
  pkg/objectio/cache.go
  pkg/objectio/funcs.go
  pkg/objectio/location.go
  pkg/objectio/meta.go
  pkg/objectio/metav1.go
  pkg/objectio/metav2.go
  pkg/objectio/object.go
  pkg/objectio/reader.go
  pkg/objectio/types.go
  pkg/objectio/versions.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/runtime_filter.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/prefetch.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/interval.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/option.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/compatibility/cases.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/util_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/model/aot.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/flushdeletes.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
Labels: kind/feature, size/XL

#11204 Refactor on duplicate key operator
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: size/M, kind/refactor

#11178 support set and insert index value for enum type
  pkg/container/types/enum.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/tools.go
  test/distributed/cases/dtype/enum_1.result
  test/distributed/cases/dtype/enum_1.test
Labels: kind/feature, size/M

#11183 Fix hashmap resize implementation
  pkg/common/hashmap/strhashmap.go
  pkg/container/hashtable/bucket.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
  pkg/sql/colexec/hashbuild/build.go
Labels: kind/bug, size/M

#11220 solve alter table missing null attributes
  pkg/sql/plan/build_alter_change_column.go
Labels: kind/bug, size/S

#11230 Revert "support set and insert index value for enum type"
  pkg/container/types/enum.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/tools.go
  test/distributed/cases/dtype/enum_1.result
  test/distributed/cases/dtype/enum_1.test
Labels: size/M

#11233 Revert "Revert "support set and insert index value for enum type" (#1…
  pkg/container/types/enum.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/tools.go
  test/distributed/cases/dtype/enum_1.result
  test/distributed/cases/dtype/enum_1.test
Labels: size/M

#11232 fix compability problem
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/M

#11234 Determine hashtable load factor by size
  pkg/container/hashtable/common.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: kind/enhancement, size/S

#11228 optimize group by preAllocate memory
  pkg/common/hashmap/inthashmap.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: kind/enhancement, size/M

#11198 Add system table upgrade
  pkg/cnservice/upgrader/newAddTable.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/authenticate.go
  pkg/frontend/internal_executor.go
  pkg/util/export/table/table.go
  pkg/util/internalExecutor/internal_executor.go
Labels: kind/bug, size/M

#11227 rewrite filter and fix show column_number
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/util/util.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/M

#10957 Remove precommit write
  pkg/dnservice/store_rpc_handler.go
  pkg/frontend/test/txn_mock.go
  pkg/pb/api/api.pb.go
  pkg/pb/txn/txn.pb.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/rpc/handle.go
  proto/api.proto
  proto/txn.proto
Labels: kind/enhancement, size/S

#11240 Change objectio's cache policy
  pkg/objectio/cache.go
  pkg/objectio/funcs.go
  pkg/objectio/metav2.go
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: kind/enhancement, size/M

#11251 Use 256MB blocks instead of 1GB in hash table
  pkg/container/hashtable/common.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/string_hash_map.go
Labels: kind/enhancement, size/S

#11256 add result summary for merge run
  .github/workflows/merge-trigger.yaml
Labels: size/S

#11243 better location output in metadata scan
  pkg/sql/colexec/table_function/metadata_scan.go
Labels: size/XS

#11262 Quickly fix the panic bug of prefetch
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/XS
