Repository matrixorigin/matrixone, pull requests merged in 2023-11, with the labels that each got.

#12438 CI: modify ci to avoid pwn
  .github/workflows/ci.yml
  .github/workflows/utils.yaml
Labels: kind/test-ci

#12315 the refactor of collecting accounts' storage usage info
  pkg/frontend/show_account.go
  pkg/frontend/show_account_test.go
  pkg/frontend/util_test.go
  pkg/objectio/metav2.go
  pkg/pb/ctl/ctl.pb.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint.go
  pkg/sql/plan/function/ctl/cmd_backup.go
  pkg/sql/plan/function/ctl/cmd_checkpoint.go
  pkg/sql/plan/function/ctl/cmd_flush.go
  pkg/sql/plan/function/ctl/cmd_inspectdn.go
  pkg/sql/plan/function/ctl/cmd_ping.go
  pkg/sql/plan/function/ctl/cmd_ping_test.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/ctl.go
  pkg/sql/plan/function/ctl/dist.go
  pkg/sql/plan/function/ctl/types.go
  pkg/tnservice/cfg.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/test/util_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/handle.go
  proto/ctl.proto
Labels: size/L, kind/enhancement

#12453 Handle view define issue
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/bind_context.go
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/database/system_variables.result
Labels: kind/bug, size/S

#12465 cherry pick object-list feature
  pkg/container/types/rowid.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/engine_mock.go
  pkg/objectio/block.go
  pkg/objectio/name.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/compile/dml.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/blockio/write_index.go
  pkg/vm/engine/types.go
  proto/plan.proto
Labels: kind/feature, size/XL

#12463 ViewDefinitionUpgradeBug
  pkg/util/sysview/sysview.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show.test
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/S

#12493 CI: change healthcheck and release
  etc/launch-tae-compose/compose.yaml
Labels: size/XS, kind/test-ci

#12428 [BugFix]: Vector To String Scale issue
  pkg/container/types/array.go
  pkg/container/types/array_test.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/moarray/array.go
  pkg/vectorize/moarray/array_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/M

#12480 Pick file service changes
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/file_cache.go
  pkg/fileservice/s3_fs.go
  pkg/perfcounter/counter_set.go
Labels: size/M

#12485 Add read checkpoint log
  pkg/vm/engine/tae/logtail/utils.go
Labels: size/S, kind/enhancement

#12486 Gc deletes when replay nablk
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/tables/ablk.go
Labels: kind/bug, size/S

#12494 Revert "imporve: use in expr to check PK dup (#12447)"
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
Labels: size/S

#12456 [enhancement] proxy: reduce some log messages.
  pkg/common/moerr/error.go
  pkg/proxy/rebalancer.go
  pkg/proxy/tunnel.go
Labels: size/S, kind/enhancement

#12457 CI: Remove eks mergerun in 1.0 dev
  .github/workflows/ci.yml
  .github/workflows/merge-trigger-tke.yml
  .github/workflows/utils.yaml
Labels: size/XL, kind/test-ci

#12455 [enhancement] proxy: reduce some log messages.
  pkg/common/moerr/error.go
  pkg/proxy/rebalancer.go
  pkg/proxy/tunnel.go
Labels: size/S, kind/enhancement

#12473 fix cron task checkNewAccount logic
  pkg/util/metric/mometric/cron_task.go
Labels: kind/bug, size/S

#12481 fix account status suspend_time not null
  pkg/frontend/authenticate.go
Labels: kind/bug, size/S

#12478 fix plan cache
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#12484 add param for control select into outfile
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS, kind/enhancement

#12499 fileservice: get upstream credentials in provider function
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#12507 resubmit optimize rule: remove effectless left joins
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/join/leftjoin.result
  test/distributed/cases/join/leftjoin.test
  test/distributed/cases/optimizer/pushdown.result
Labels: size/M, kind/enhancement

#12467 fix: support present ordinary/unique key
  pkg/sql/plan/build_show.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/ddl/alter_table_add_drop_constraint.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/ddl/secondary_index_alter.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/M

#12475 fix: support present foreign key
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/desc_table_with_foreign_key.result
  test/distributed/cases/ddl/desc_table_with_foreign_key.sql
  test/distributed/cases/foreign_key/foreign_key.result
Labels: kind/bug, size/S

#12510 CI: change regex and add tke regresison yaml for 1.0 dev
  .github/ISSUE_TEMPLATE/schema.json
  .github/workflows/ci.yml
  .github/workflows/utils.yaml
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci

#12521 fix a misuse of `defer time.Since`
  pkg/frontend/show_account.go
Labels: kind/bug, size/XS

#12498 feat: support convert_tz function (1.0-dev)
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
Labels: size/M

#12501 cherry-pick fix plan cache, suspend_time, select into control (1.0-dev)
  pkg/config/configuration.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
Labels: size/S

#12509 fix show columns (1.0-dev)
  pkg/sql/plan/build_show.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/ddl/alter_table_add_drop_constraint.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/desc_table_with_foreign_key.result
  test/distributed/cases/ddl/desc_table_with_foreign_key.sql
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/ddl/secondary_index_alter.result
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/clustertable2.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: size/M

#12523 add log for metadata scan
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S

#12500 cherry pick checkNewAccount logic fix
  pkg/util/metric/mometric/cron_task.go
Labels: kind/bug, size/S

#12443 [enhancement] hakeeper: Do not perform repeated restore operation.
  pkg/logservice/config.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_bootstrap_test.go
Labels: size/S, kind/enhancement

#12525 fix commit error mapping
  pkg/txn/client/operator.go
Labels: kind/bug, size/S

#12528 reduce golang objects allocation during merge sort
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/mergesort/func.go
Labels: size/M, kind/enhancement

#12524 change to load specified ckp data batch when `show accounts` to avoid possible oom.
  pkg/frontend/show_account.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#12511 cherry pick add more txn metrics
  pkg/cnservice/cnclient/client.go
  pkg/common/morpc/cfg.go
  pkg/common/morpc/client.go
  pkg/common/mpool/mpool.go
  pkg/defines/type.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/txn/client/operator.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_rpc.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/logtail.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/XL, kind/enhancement

#12519 CI: modify regex for main
  .github/workflows/ci.yml
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e-standalone.yml
  .github/workflows/e2e_upgrade.yml
  .github/workflows/utils.yaml
Labels: size/S, kind/test-ci

#12531 Fix resource cleanup issue after recover
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/vm/vm.go
Labels: kind/bug, size/S

#12526 cherry pick fix commit error mapping
  pkg/txn/client/operator.go
Labels: kind/bug, size/S

#12508 add more metrics
  pkg/cnservice/cnclient/client.go
  pkg/common/morpc/cfg.go
  pkg/common/morpc/client.go
  pkg/common/mpool/mpool.go
  pkg/defines/type.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/txn/client/operator.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_rpc.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/logtail.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/XL, kind/enhancement

#12496 Skip file upload if record already existed
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/merge.go
Labels: kind/bug, size/M

#12545 restore pipeline max connections
  pkg/cnservice/cnclient/client.go
Labels: kind/bug, size/XS

#12546 restore pipeline max connections
  pkg/cnservice/cnclient/client.go
Labels: kind/bug, size/XS

#12492 fix a bug that internal query can not get stats correctly
  pkg/frontend/compiler_context.go
  pkg/sql/compile/sql_executor_context.go
Labels: kind/bug, size/S

#12537 [BugFix]: Turnoff Dup Check for SK
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/S

#12542 Fix resource cleanup issue after recover
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/vm/vm.go
Labels: kind/bug, size/S

#12540 modify bvt case
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: kind/bug, size/XS

#12461 [metrics]: adding more counters for ranges loading object meta operation.
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement

#12529 improve: use IN expr to check PK dup
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/utils.go
Labels: size/S, kind/enhancement

#12543 Remove unused code for recover
  pkg/sql/compile/scope.go
Labels: kind/bug, size/XS

#12522 refactor task metric grafana dashboard
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/read.go
Labels: size/M, kind/refactor

#12554 CI: change builder to 1.20.7
  optools/images/Dockerfile
Labels: size/XS, kind/test-ci

#12464 sync `metrics to ranges loading object meta` to 1.0-dev
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#12527 fix convert_tz funtion
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
Labels: kind/bug, size/M, kind/refactor

#12550 time_window case
  test/distributed/cases/window/time_window.result
  test/distributed/cases/window/time_window.sql
  test/distributed/resources/external_table_file/time_window.csv
Labels: size/XL

#12454 fix using fs without shared
  pkg/sql/compile/compile.go
Labels: size/XS

#12520 add shuffleRange in stats cache
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_algo.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: size/M, kind/refactor

#12567 fix using fs without shared(1.0-dev)
  pkg/sql/compile/compile.go
Labels: size/XS

#12572 [refactor] logtail: some refactor logtail consumer and fix a bug
  pkg/txn/client/client.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
Labels: kind/bug, size/L, kind/refactor

#12574 CI: add git,tzdata to image and modify ci
  .github/workflows/merge-trigger-tke.yaml
  cmd/mo-service/main.go
  optools/images/Dockerfile
Labels: size/S, kind/test-ci

#12579 removeTag11774
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: size/S, kind/test-ci

#12558 fix convert_tz funtion (1.0-dev)
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
Labels: kind/bug, size/M

#12566 fix privilege check for index of system table
  pkg/frontend/authenticate.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/drop.go
Labels: size/S, kind/enhancement

#12559 Skip file upload if record already existed (#12496)
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/merge.go
Labels: kind/bug, size/M

#12490 merge more blocks automatically
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/common/stats_test.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: kind/feature, size/M

#12553 add unique key for system table
  pkg/frontend/authenticate.go
  test/distributed/cases/ddl/secondary_index_create.result
  test/distributed/cases/ddl/secondary_index_create.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/zz_accesscontrol/inner_object.result
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/feature, size/M

#12586 [Bug]: After a long run, the tpch get wrong result
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#12536 remove redundant join condition
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: size/S

#12584 [Bug]: After a long run, the tpch get wrong result
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#12589 [bug] logservice: fix a UT
  pkg/logservice/store_test.go
Labels: kind/bug, size/S

#12585 [bug] proxy: fix UT
  pkg/clusterservice/cluster.go
  pkg/proxy/router_test.go
Labels: kind/bug, size/XS

#12599 Revert "[Bug]: After a long run, the tpch get wrong result"
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/S

#12598 Revert "[Bug]: After a long run, the tpch get wrong result"
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/S

#12569 cherry-pick : update error to 1.0dev
  pkg/frontend/mysql_protocol.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/handler.go
Labels: kind/bug, size/M

#12577 [enhancement] hakeeper: Do not perform repeated restore operation.
  pkg/logservice/config.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_bootstrap_test.go
Labels: size/S, kind/enhancement

#12600 CI: change clone method
  .github/workflows/merge-trigger-tke.yaml
Labels: size/S, kind/test-ci

#12602 CI: sync ci with main
  .github/workflows/merge-trigger-tke.yml
  cmd/mo-service/main.go
  optools/images/Dockerfile
Labels: size/S, kind/test-ci

#12576 [refactor] logtail: some refactor logtail consumer and fix a bug
  pkg/txn/client/client.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
Labels: kind/bug, size/L, kind/refactor

#12582 fileservice: trigger eviction on startup; more logs; use blocks * block
  pkg/fileservice/disk_cache.go
Labels: kind/bug, size/S

#12605 Revert "fileservice: trigger eviction on startup; more logs; use blocks * block"
  pkg/fileservice/disk_cache.go
Labels: size/S

#12607 resubmit "[Bug]: After a long run, the tpch get wrong result"
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#12610 Fix the error handling of channel when recovering
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/XS

#12606 allow multiple rollbacks of a transaction
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: kind/bug, size/XS

#12581 fileservice: trigger eviction on startup; more logs
  pkg/fileservice/disk_cache.go
Labels: kind/bug, size/S

#12612 resubmit "[Bug]: After a long run, the tpch get wrong result"
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#12590 fix privilege check for index of system table (1.0-dev)
  pkg/frontend/authenticate.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/drop.go
Labels: size/S

#12479 [Feature]: Kmeans + Normalize_L2 SQL functions | Vector Index Phase 1
  go.mod
  go.sum
  pkg/common/assertx/float64.go
  pkg/common/assertx/float64_test.go
  pkg/container/types/array.go
  pkg/container/types/array_test.go
  pkg/container/vector/vector.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_cast.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer_bench_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/distance_func.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/distance_func_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/initializer.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/initializer_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/types.go
  pkg/sql/plan/function/functionAgg/cluster_centers.go
  pkg/sql/plan/function/functionAgg/group_concat.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/testutil/util_function.go
  pkg/vectorize/moarray/array.go
  pkg/vectorize/moarray/external.go
  pkg/vectorize/moarray/external_test.go
  pkg/vectorize/moarray/gonums_utils.go
  pkg/vectorize/moarray/gonums_utils_test.go
  pkg/vectorize/moarray/internal.go
  pkg/vectorize/moarray/internal_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
Labels: kind/feature, size/XXL

#12594 add unique key for system table (1.0-dev)
  pkg/frontend/authenticate.go
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/zz_accesscontrol/inner_object.result
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: size/M

#12621 fix Incorrect logging
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#12611 Fix the error handling of channel when recovering
  pkg/sql/compile/scope.go
Labels: kind/bug, size/XS

#12608 fix shuffle_algo nil pointer
  pkg/sql/plan/shuffle_algo.go
Labels: size/S

#12580 fix: support non-second datetime format
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  test/distributed/cases/function/func_date.result
  test/distributed/cases/function/func_date.sql
  test/distributed/cases/function/func_date_format.result
  test/distributed/cases/function/func_date_format.test
  test/distributed/cases/function/func_date_format_1.result
  test/distributed/cases/function/func_date_format_1.sql
  test/distributed/cases/function/func_datetime_date.result
  test/distributed/cases/function/func_datetime_date.test
  test/distributed/cases/function/func_datetime_date_add.result
  test/distributed/cases/function/func_datetime_date_add.test
  test/distributed/cases/function/func_datetime_dayofyear.result
  test/distributed/cases/function/func_datetime_dayofyear.test
  test/distributed/cases/function/func_datetime_extract.result
  test/distributed/cases/function/func_datetime_extract.test
  test/distributed/cases/function/func_datetime_weekday.result
  test/distributed/cases/function/func_datetime_weekday.test
  test/distributed/cases/function/func_datetime_year.result
  test/distributed/cases/function/func_datetime_year.test
Labels: kind/bug, size/M

#12620 remove useless log print in stats
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: size/XS, kind/enhancement

#12597 fix error result when timezone in hh:mm format
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
Labels: kind/bug, size/S

#12632 fileservice: add toOSSCredentialProvider
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#12628 Revert "merge more blocks automatically (#12490)"
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/common/stats_test.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: size/M

#12624 fix Incorrect logging (1.0-dev)
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS

#12637 add metric for reader
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/pipeline.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
  pkg/vm/pipeline/pipeline.go
Labels: size/M, kind/enhancement

#12623 [Bug]: shuffle need to handle null
  pkg/sql/colexec/shuffle/shuffle.go
Labels: kind/bug, size/M

#12587 object list phase 2
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/feature, size/M

#12641 do not record rowid transfer history for tables without primary key
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
Labels: size/S, kind/enhancement

#12615 [fix] the issue of view changing the original data format of char
  pkg/sql/plan/query_builder.go
  test/distributed/cases/view/view-from-subquery.result
  test/distributed/cases/view/view-from-subquery.sql
Labels: kind/bug, size/S

#12647 hotfix metadata load
  pkg/vm/engine/tae/catalog/segment.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
Labels: size/S

#12638 Split batch for table function:generate_series
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/generate_series_test.go
  pkg/sql/colexec/table_function/table_function_test.go
  pkg/sql/colexec/table_function/types.go
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
Labels: kind/bug, size/M

#12640 fileservice: add default aliyun credential provider
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#12651 add null count info in stats cache
  pkg/sql/plan/shuffle_algo.go
  pkg/sql/plan/shuffle_test.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
Labels: size/S, kind/refactor

#12557 [Improvement]: Adding AlgoType, AlgoTableType & AlgoParams to "mo_indexes" | Vector Index Phase 2
  pkg/bootstrap/bootstrap.go
  pkg/catalog/secondary_index_utils.go
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_column.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/authenticate.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/index_metadata.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/sql_executor_context_test.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/index_algo_params.go
  pkg/sql/plan/mock.go
  pkg/vm/engine/types.go
  proto/plan.proto
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/secondary_index_alter.result
  test/distributed/cases/ddl/secondary_index_create.result
  test/distributed/cases/ddl/secondary_index_create.sql
  test/distributed/cases/ddl/secondary_index_delete.result
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/dml/show/IndexMetadata.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: size/XXL, kind/enhancement

#12649 fix Incorrect spelling words
  pkg/common/moerr/error.go
  pkg/common/moerr/mysql_error_define.go
  pkg/common/morpc/codec.go
  pkg/container/types/datetime.go
  pkg/container/types/datetime_test.go
  pkg/container/types/time.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_alter_add_primarykey.go
  pkg/sql/plan/function/functionAgg/cluster_centers.go
  pkg/taskservice/types.go
  pkg/tests/service/service_test.go
  proto/gen.sh
  test/distributed/cases/auto_increment/auto_increment_columns.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_rename_column.sql
  test/distributed/cases/dtype/TimeToInt.result
  test/distributed/cases/dtype/datetime.result
  test/distributed/cases/dtype/text_1.result
  test/distributed/cases/expression/temporal_interval.result
  test/distributed/cases/function/func_cast.result
  test/distributed/cases/function/func_date_format.result
  test/distributed/cases/function/func_date_format_1.result
  test/distributed/cases/function/func_datetime_date_add.result
  test/distributed/cases/function/func_string_concat_ws.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/prepare/prepare_all.result
  test/distributed/cases/zz_accesscontrol/create_role.sql
  test/distributed/cases/zz_accesscontrol/create_user.sql
Labels: kind/bug, size/M

#12664 fileservice: add SkipFullFilePreloads policy
  pkg/backup/tae.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/policy.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path_test.go
  pkg/objectio/cache.go
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: size/M

#12661 pick file service changes
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/cache.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/M

#12668 record rowid transfer history for a short time for the table without primary key
  pkg/vm/engine/tae/model/pages.go
  pkg/vm/engine/tae/model/transfer_test.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
Labels: size/S, kind/enhancement

#12654 Add logging of empty plans and recove when an empty plan is encountered
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  proto/pipeline.proto
Labels: kind/bug, size/S

#12665 remove bvt tag
  test/distributed/cases/ddl/secondary_index_create.sql
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/bug, size/XS

#12667 support var_pop func
  pkg/sql/plan/function/function_id.go
  test/distributed/cases/function/func_aggr_var_pop.result
  test/distributed/cases/function/func_aggr_var_pop.test
Labels: kind/feature, size/M

#12630 fix: support non-second datetime format (1.0-dev)
  pkg/container/types/date.go
  pkg/container/types/datetime.go
  test/distributed/cases/function/func_date.result
  test/distributed/cases/function/func_date.sql
  test/distributed/cases/function/func_date_format.result
  test/distributed/cases/function/func_date_format.test
  test/distributed/cases/function/func_date_format_1.result
  test/distributed/cases/function/func_date_format_1.sql
  test/distributed/cases/function/func_datetime_date.result
  test/distributed/cases/function/func_datetime_date.test
  test/distributed/cases/function/func_datetime_date_add.result
  test/distributed/cases/function/func_datetime_date_add.test
  test/distributed/cases/function/func_datetime_dayofyear.result
  test/distributed/cases/function/func_datetime_dayofyear.test
  test/distributed/cases/function/func_datetime_extract.result
  test/distributed/cases/function/func_datetime_extract.test
  test/distributed/cases/function/func_datetime_weekday.result
  test/distributed/cases/function/func_datetime_weekday.test
  test/distributed/cases/function/func_datetime_year.result
  test/distributed/cases/function/func_datetime_year.test
Labels: size/M

#12672 Update reader SkipFullFilePreloads policy
  pkg/objectio/cache.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: size/S, kind/enhancement

#12634 fix error result when timezone in hh:mm format (1.0-dev)
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
Labels: size/S

#12670 fileservice: add SkipFullFilePreloads policy (#12664)
  pkg/backup/tae.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services_test.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/policy.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path_test.go
  pkg/objectio/cache.go
  pkg/objectio/funcs.go
  pkg/objectio/reader.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: size/M, kind/enhancement

#12674 adding metrics for TN mpool and transfer page
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/mem.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/common/utils/types.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/model/pages.go
  pkg/vm/engine/tae/model/transfer.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/M, kind/enhancement

#12677 add mo-ctl ignore ckp
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: size/S, kind/enhancement

#12679 [data race]: fix data race when collect metrics
  pkg/vm/engine/tae/containers/pool.go
  pkg/vm/engine/tae/db/open.go
Labels: size/S, kind/enhancement

#12675 sync `adding metrics for TN mpool and transfer page`
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/mem.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/common/utils/types.go
  pkg/vm/engine/tae/containers/pool.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/model/pages.go
  pkg/vm/engine/tae/model/transfer.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/M, kind/enhancement

#12676 Update reader SkipFullFilePreloads policy
  pkg/objectio/cache.go
  pkg/vm/engine/tae/blockio/reader.go
Labels: size/S

#12642 addCase
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/S

#12653 Split batch to 8192 rows for Product operator
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/product/types.go
  test/distributed/cases/expression/cte.result
Labels: kind/bug, size/S

#12684 fix mpool leak during replay
  pkg/vm/engine/tae/db/checkpoint/replay.go
Labels: kind/bug, size/XS

#12688 fix a very weak mpool leak
  pkg/vm/engine/tae/tables/base.go
Labels: kind/bug, size/XS

#12689 fix wrong unique index prefix
  pkg/catalog/types.go
  pkg/sql/plan/mock.go
  pkg/sql/util/index_util.go
Labels: kind/bug, size/S

#12687 fix leak in delete node
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/delete.go
Labels: kind/bug, size/XS

#12683 cherry-pick-fix-data-race-for-1.0-dev
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/feature, size/M

#12694 fileservice: fix aliyun sdk error handling
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#12695 fileservice: fix aliyun sdk error handling
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#12671 some minor refactor for stats
  pkg/frontend/compiler_context.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/refactor

#12693 add show accounts case
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
Labels: size/XS, kind/test-ci

#12690 cherry pick: fix wrong unique table name
  pkg/catalog/types.go
  pkg/sql/util/index_util.go
Labels: kind/bug, size/S

#12680 fix Incorrect spelling words (1.0-dev)
  pkg/common/moerr/error.go
  pkg/common/moerr/mysql_error_define.go
  pkg/common/morpc/codec.go
  pkg/container/types/datetime.go
  pkg/container/types/datetime_test.go
  pkg/container/types/time.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_alter_add_primarykey.go
  pkg/taskservice/types.go
  pkg/tests/service/service_test.go
  proto/gen.sh
  test/distributed/cases/auto_increment/auto_increment_columns.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_rename_column.sql
  test/distributed/cases/dtype/TimeToInt.result
  test/distributed/cases/dtype/datetime.result
  test/distributed/cases/dtype/text_1.result
  test/distributed/cases/expression/temporal_interval.result
  test/distributed/cases/function/func_cast.result
  test/distributed/cases/function/func_date_format.result
  test/distributed/cases/function/func_date_format_1.result
  test/distributed/cases/function/func_datetime_date_add.result
  test/distributed/cases/function/func_string_concat_ws.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/prepare/prepare_all.result
  test/distributed/cases/zz_accesscontrol/create_role.sql
  test/distributed/cases/zz_accesscontrol/create_user.sql
Labels: size/M

#12591 [BugFix]: Fixing Precision issue for VECF64
  pkg/common/assertx/float64.go
  pkg/common/assertx/float64_test.go
  pkg/container/types/array.go
  pkg/container/types/array_test.go
  pkg/frontend/resultset.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/vectorize/moarray/external_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array_index.result
Labels: kind/bug, size/M

#12698 fileservice: add S3FS.restoreFromDiskCache
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/error.go
  pkg/fileservice/path.go
  pkg/fileservice/policy.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_restore.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M

#12700 enable shuffle join to block probe until build ready
  pkg/sql/plan/runtime_filter.go
Labels: size/XS

#12699 fileservice: add S3FS.restoreFromDiskCache
  pkg/fileservice/config.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/error.go
  pkg/fileservice/path.go
  pkg/fileservice/policy.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_restore.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M

#12691 adding object stats describer interface
  pkg/objectio/object.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/blockio/writer.go
Labels: kind/feature, size/S, kind/enhancement

#12697 Add logging of empty plans and recover when an empty plan is encountered
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scopeRemoteRunTypes_test.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  proto/pipeline.proto
Labels: kind/bug, size/S

#12704 fix panic caused by #12700
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#12712 remove invalid lock table bind
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/types.go
  pkg/pb/txn/txn.pb.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_cn_handler_test.go
  proto/txn.proto
Labels: kind/bug, size/M

#12713 remove invalid lock table bind
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/types.go
  pkg/pb/txn/txn.pb.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/service/service_cn_handler.go
  pkg/txn/service/service_cn_handler_test.go
  proto/txn.proto
Labels: kind/bug, size/M

#12714 add show accounts bvt case
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
Labels: size/XS, kind/test-ci

#12718 Redesign object stats
  pkg/objectio/object.go
  pkg/objectio/object_stats.go
  pkg/objectio/writer.go
Labels: kind/feature, size/M, kind/enhancement

#12719 fix a small mpool leak during saving checkpoint
  pkg/vm/engine/tae/db/checkpoint/runner.go
Labels: kind/bug, size/XS

#12705 add log for get Subscription Meta
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_ddl.go
Labels: kind/bug, size/S

#12709 fix data race and log print
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
Labels: kind/bug, size/S

#12722 remove the account fro mthe stmt_info cluster by
  pkg/util/trace/impl/motrace/schema.go
Labels: size/XS, kind/enhancement

#12703 adding more metrics for mpool
  pkg/common/mpool/mpool.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/mem.go
  pkg/util/metric/v2/metrics.go
  pkg/vm/engine/tae/common/utils/types.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/model/transfer.go
Labels: kind/feature, size/M, kind/enhancement
