Repository matrixorigin/matrixone, pull requests merged in 2023-09, with the labels that each got.

#11573 fix some enum type bug in pessimistic mode
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/func_compare.go
  pkg/sql/plan/function/operatorSet.go
  pkg/sql/util/eval_expr_util.go
  pkg/sql/util/index_util.go
  pkg/testutil/util_new.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/common/print.go
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum.sql
Labels: kind/bug, size/M

#11586 add fk cases and remove issue tag
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/atomicity.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
  test/distributed/cases/recursive_cte/recursive_cte1.result
  test/distributed/cases/recursive_cte/recursive_cte1.sql
Labels: kind/feature, size/M

#11592 fix in memory collect deletes
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/hidden_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/iface/data/block.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: kind/bug, size/M

#11595 pick stability fixed commit from main to 1.0rc
  pkg/sql/compile/scope.go
  pkg/txn/client/client.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/pipeline/types.go
Labels: kind/bug, size/S

#11594 pick fix missing deletes after restarting (#11541) for 1.0
  pkg/vm/engine/tae/catalog/block.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnimpl/block.go
Labels: size/M

#11602 add window case
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/L

#11589 Fix Gorm migrate issue
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/sql/plan/visit_plan.go
  test/distributed/cases/prepare/prepare_all.result
  test/distributed/cases/prepare/prepare_all.sql
Labels: kind/bug, size/S

#11593 adjust join order for tpch q10
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/XS

#11603 fix group by null
  pkg/sql/plan/group_binder.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/XS

#11610 CI: fix sysbench bug
  .github/workflows/merge-trigger.yaml
Labels: size/XS

#11608 modify some case and result
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/M

#11606 [Enhancement]: optimize decimal arith by processing batch
  pkg/container/types/decimal.go
  pkg/sql/plan/function/arithmetic.go
  pkg/sql/plan/function/baseTemplate.go
Labels: kind/enhancement, size/M

#11609 Fix gorm migrate2
  pkg/cnservice/upgrader/newAddTable.go
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/ddl/index_metadata.result
  test/distributed/cases/ddl/index_metadata.sql
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/mo_cloud/mo_cloud.result
Labels: kind/feature, size/M

#11617 [Enhancement]: optimize decimal arith by processing batch
  pkg/container/types/decimal.go
  pkg/sql/plan/function/arithmetic.go
  pkg/sql/plan/function/func_cast.go
Labels: kind/enhancement, size/M

#11591 [Subtask]: set channel buffer size of shuffle join and shuffle group to proper value
  pkg/sql/compile/scope.go
Labels: size/XS

#11616 support prepare for limit and offset
  pkg/sql/plan/limit_binder.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/enhancement, size/S

#11627 remove an useless log and add test
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scope_test.go
Labels: size/S

#11626 using bloom filter for composite primary key equal filter
  pkg/objectio/stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
Labels: kind/enhancement, size/S

#11621 Add system module for observing various information of mo
  go.mod
  go.sum
  pkg/common/system/system.go
  pkg/common/system/system_test.go
  pkg/common/system/types.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/system/system.result
  test/distributed/cases/system/system.sql
Labels: kind/feature, size/M

#11635 CI: change runner for some actions in `1.0.0-rc1` branch
  .github/workflows/merge-trigger.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
Labels: size/S, kind/test-ci

#11639 Revert "Add system module for observing various information of mo"
  go.mod
  go.sum
  pkg/common/system/system.go
  pkg/common/system/system_test.go
  pkg/common/system/types.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/system/system.result
  test/distributed/cases/system/system.sql
Labels: size/M

#11637 optimize bat shrink
  pkg/container/batch/batch.go
Labels: kind/enhancement, size/XS

#11588 fix data race during bootstrap
  pkg/bootstrap/bootstrap.go
  pkg/cnservice/server.go
Labels: kind/bug, size/M

#11642 fix collect deletes in range
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
Labels: kind/bug, size/S

#11644 fix a uuid map bug will cause hung if query ends early
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
Labels: kind/bug, size/S

#11632 support unique key for on duplicate key statement
  pkg/sql/colexec/agg/anyvalue.go
  pkg/sql/colexec/agg/new.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
  test/distributed/cases/dml/insert/on_duplicate_key.result
  test/distributed/cases/dml/insert/on_duplicate_key.sql
Labels: kind/enhancement, size/M

#11638 Remove tag
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
Labels: size/XS

#11625 Adjust Stmt duration as sum value and format aggr statemnt format
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
Labels: kind/enhancement, size/S

#11633 Add LOAD INTO VALUES
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
  test/distributed/cases/load_data/load_data_csv_values.result
  test/distributed/cases/load_data/load_data_csv_values.sql
Labels: kind/feature, size/XXL

#11649 Add shared lock mode support in lockservice
  pkg/lockservice/btree_storage.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
Labels: kind/feature, size/XXL, kind/refactor

#11657 lock_op add shared mode support
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/types.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/feature, size/S

#11615 add checksum for saving tae files
  CODEOWNERS
  pkg/backup/backup.go
  pkg/backup/backup_test.go
  pkg/backup/fs.go
  pkg/backup/fs_test.go
  pkg/backup/tae.go
  pkg/backup/types.go
  pkg/backup/types_test.go
  pkg/frontend/backup.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/feature, size/L

#11643 alter cte cases
  test/distributed/cases/recursive_cte/recursive_cte1.result
  test/distributed/cases/recursive_cte/recursive_cte1.sql
Labels: size/S

#11607 Add s3vis span
  pkg/cnservice/server_query.go
  pkg/fileservice/file_service.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/pb/ctl/ctl.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/query_service.go
  pkg/queryservice/query_service_test.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/cmd_tracespan_test.go
  pkg/sql/plan/function/ctl/types.go
  pkg/util/trace/config.go
  pkg/util/trace/config_test.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/noop_trace.go
  pkg/util/trace/trace.go
  pkg/util/trace/type.go
  proto/ctl.proto
  proto/query.proto
Labels: kind/enhancement, size/L

#11667 modify case
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/S

#11675 fix a remote run bug may return error for succeed query.
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#11673 split large batch in inner join
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
Labels: size/M

#11679 Revert "split large batch in inner join (#11673)"
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
Labels: kind/bug, size/M

#11631 change runtime filter threshold of in predicate to 10000 from 1024
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/variables.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/enhancement, size/S

#11645 CI: add darwin arm64 bvt test to mergerun
  .github/workflows/merge-trigger.yaml
Labels: size/S, kind/test-ci

#11676 fix ut - time sensitive case
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
Labels: kind/bug, size/S

#11682 CI: debug path error
  .github/workflows/merge-trigger.yaml
Labels: size/XS, kind/test-ci

#11646 CI: add darwin arm64 bvt test to 1.0.0-rc1
  .github/workflows/merge-trigger.yaml
Labels: size/S, kind/test-ci

#11671 fix 11630 and add bvt case
  pkg/container/types/decimal.go
  pkg/container/types/decimal_test.go
  pkg/sql/plan/function/arithmetic.go
  pkg/sql/plan/function/baseTemplate.go
  test/distributed/cases/dtype/decimal.result
  test/distributed/cases/dtype/decimal.test
Labels: size/L

#11640 fileservice: set s3 http client max conns per host to 1000
  pkg/fileservice/s3_fs.go
Labels: kind/enhancement, size/XS

#11688 Fix frontend log fromat
  pkg/frontend/cmd_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/util.go
  pkg/util/export/table/table_test.go
Labels: kind/enhancement, size/M

#11691 CI: collect trace before clean env
  .github/workflows/merge-trigger.yaml
Labels: size/S, kind/test-ci

#11686 remove pipeline's wrong log
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/receiver_operator.go
Labels: kind/bug, size/S

#11699 CI: get pprof after test
  .github/workflows/merge-trigger.yaml
Labels: size/XS, kind/test-ci

#11660 fileservice: add ObjectStorage, AwsSDKv2
  pkg/backup/fs.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/config.go
  pkg/fileservice/get.go
  pkg/fileservice/get_test.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/object_storage.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/retry.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/utils.go
Labels: size/XL

#11668 fix desc column precision for time type
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_util.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/clustertable2.result
Labels: kind/bug, size/M

#11684 add lock table without txn
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/colexec/lockop/lock_op_no_txn_test.go
  pkg/sql/colexec/lockop/lock_op_test.go
Labels: kind/enhancement, size/M

#11698 Block probe side unitl build side finished for shuffle join
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/types.go
  pkg/sql/plan/runtime_filter.go
  proto/pipeline.proto
Labels: kind/enhancement, size/M

#11441 Add bit_cast function for binary types
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/metadata_scan.go
  pkg/vm/engine/disttae/txn_table.go
  proto/plan.proto
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan.sql
Labels: kind/feature, size/XXL

#11717 fix AddColumnCnt (#11486)
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/hidden_test.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
Labels: size/M

#11720 Cherrypick a37de24 2b4022a
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/proxy/client_conn.go
  pkg/proxy/handshake.go
  pkg/proxy/label_info.go
  pkg/proxy/label_info_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_alter_table_test.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
  test/distributed/cases/recursive_cte/recursive_cte1.result
  test/distributed/cases/recursive_cte/recursive_cte1.sql
  test/distributed/cases/subquery/subquery-with-in.result
  test/distributed/cases/subquery/subquery-with-in.sql
  test/distributed/cases/view/view-subquery-with-in.result
  test/distributed/cases/view/view-subquery-with-in.sql
Labels: size/XL

#11730 Fix a boundary check bug for binary search
  pkg/container/vector/search.go
Labels: kind/bug, size/S

#11763 revert some prs which cause hung problem
  pkg/lockservice/btree_storage.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/colexec/lockop/lock_op_no_txn_test.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/XXL

#11744 alter cases and add issue tag
  test/distributed/cases/pessimistic_transaction/select_for_update.result
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: size/S

#11636 fix bug: get latest schema when retry to run SQL
  pkg/sql/plan/build_dml_util.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/table_guard.go
  pkg/vm/engine/disttae/cache/table_guard_test.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: kind/bug, size/M

#11680 fix bugs and improvement for mo_ctl supported traces
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/cmd_tracespan_test.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_bench_test.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/trace.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, kind/enhancement, size/M

#11759 move lock node to front for DML statement
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/M

#11697 support create or replace view stmt in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/view.go
Labels: kind/feature, size/XXL

#11728 remove bvt tag
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/database/system_variables.sql
Labels: size/XS, kind/test-ci

#11765 fix bug: can not lock partition table for DDL statement
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#11693 optimize fillStrKey function
  pkg/common/hashmap/inthashmap.go
Labels: kind/enhancement, size/S

#11729 optimize merge operator by do not use reflect.select
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/colexec/receiver_operator_expand.go
Labels: kind/enhancement, size/XL

#11714 [Subtask]: set channel buffer size of shuffle join to proper value
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/enhancement, size/S

#11743 support alter sequence in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
Labels: kind/feature, size/XXL

#11755 [Subtask]: reduce shuffle memory allocation
  pkg/sql/colexec/shuffle/shuffle.go
Labels: kind/enhancement, size/S

#11748 add `mo_sessions` table function and view
  pkg/cnservice/upgrader/newAddTable.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/authenticate.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/txn.go
  pkg/frontend/util.go
  pkg/pb/status/status.pb.go
  pkg/sql/colexec/table_function/processlist.go
  pkg/sql/plan/query_builder.go
  proto/status.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/M

#11758 fix concurrent map writes in multiCN bvt test
  pkg/frontend/authenticate.go
Labels: kind/bug, size/S

#11689 Gc partition state
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/feature, size/M

#11739 optimize memory allocation for group operator
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
Labels: kind/enhancement, size/XS

#11741 fix a rightsemi bug and optimize memory allocation for rightsemi and rightanti
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/types.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/types.go
Labels: kind/enhancement, size/S

#11778 fix create account not in one transaction
  pkg/frontend/authenticate.go
  pkg/frontend/stmt_kind.go
Labels: kind/bug, size/S

#11773 fix deadlock check busy
  pkg/lockservice/service_remote.go
Labels: kind/bug, size/XS

#11760 cluster table support insert on duplicate key statement
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_util.go
  test/distributed/cases/table/cluster_table/cluster_table.result
  test/distributed/cases/table/cluster_table/cluster_table.sql
Labels: kind/bug, size/M

#11762 Support query plan partition
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/partition_prune.go
  pkg/sql/plan/query_builder.go
  proto/plan.proto
Labels: kind/feature, size/L

#11787 CI: change waittime for mo-tester to reduce the time of bvt
  .github/workflows/merge-trigger.yaml
Labels: size/S, kind/test-ci

#11799 update merge run in 1.0-dev branch
  .github/workflows/merge-trigger.yaml
Labels: size/M, kind/test-ci

#11800 update merge run in 1.0.0-rc1 branch
  .github/workflows/merge-trigger.yaml
Labels: size/M, kind/test-ci

#11745 reserve WAL entry
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/option.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/compatibility/registry.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
Labels: kind/enhancement, size/M

#11784 add shared lock support in lockservice
  pkg/lockservice/btree_storage.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
  pkg/lockservice/waiter_queue.go
  pkg/lockservice/waiter_queue_test.go
  pkg/lockservice/waiter_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/colexec/lockop/lock_op_no_txn_test.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/feature, size/XXL

#11769 [feature] proxy: proxy could identify if the connection is from internal or external network
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/pb/proxy/proxy.go
  pkg/pb/proxy/proxy_test.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/config.go
  pkg/proxy/handler.go
  pkg/proxy/router.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/feature, size/M

#11808 fix a bug introduced in partition plan
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#11654 fix ut for connector_test.go
  pkg/stream/connector/connector_test.go
Labels: kind/bug, size/S

#11810 add iter for get all locks info in current cn
  pkg/lockservice/lock.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
Labels: kind/feature, size/M

#11777 removeTag
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
  test/distributed/cases/pessimistic_transaction/ww_conflict.result
  test/distributed/cases/pessimistic_transaction/ww_conflict.sql
Labels: size/M

#11770 support create or replace view stmt
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
  test/distributed/cases/view/replace_view.result
  test/distributed/cases/view/replace_view.test
Labels: kind/feature, size/S

#11829 [Subtask]: optimize shuffle strategy
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/S

#11798 [Bug Fix] Error while inserting vecf32 with spaces.
  pkg/container/types/array.go
  pkg/container/types/array_test.go
Labels: kind/bug, size/S

#11820 Decimal error message update
  pkg/container/types/decimal.go
  test/distributed/cases/ddl/mysql_ddl_3.result
  test/distributed/cases/dml/select/union_and_union_all.result
  test/distributed/cases/dtype/decimal.result
  test/distributed/cases/dtype/text_1.result
  test/distributed/cases/function/func_datetime_unixtime.result
Labels: size/S

#11825 Add session buffer
  pkg/common/buffer/buffer.go
  pkg/common/buffer/buffer_test.go
  pkg/common/buffer/chunk.go
  pkg/common/buffer/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/vm/process/types.go
Labels: kind/feature, size/M

#11837 Revert "Add session buffer (#11825)"
  pkg/common/buffer/buffer.go
  pkg/common/buffer/buffer_test.go
  pkg/common/buffer/chunk.go
  pkg/common/buffer/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/vm/process/types.go
Labels: kind/bug, size/M

#11812 add view system.sql_statement_hotspot to show top 10 querys which run longest in last 10 minutes
  pkg/cnservice/upgrader/newAddTable.go
  pkg/util/export/table/table.go
  pkg/util/export/table/table_test.go
  pkg/util/trace/impl/motrace/schema.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/log/query_sql_statement_hotspot.result
  test/distributed/cases/log/query_sql_statement_hotspot.sql
Labels: kind/feature, size/M

#11833 [bug] script: Install protoc-gen-gogofaster automatically.
  proto/gen.sh
Labels: kind/bug, size/S

#11842 fix drop database or table not revoke priv
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/M

#11826 support alter sequence stmt
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/sequence.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
  test/distributed/cases/sequence/alter_sequence.result
  test/distributed/cases/sequence/alter_sequence.sql
Labels: kind/feature, size/XXL

#11843 keep vector order for left/semi/anti join
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/semi/join.go
Labels: kind/enhancement, size/S

#11840 add `mo_locks` view and table function
  pkg/cnservice/upgrader/newAddTable.go
  pkg/frontend/authenticate.go
  pkg/sql/colexec/table_function/system_view.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/system_view.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/M

#11844 remove bvt tag
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/function/func_string_concat_ws.result
  test/distributed/cases/function/func_string_concat_ws.test
  test/distributed/cases/function/left_function.result
  test/distributed/cases/function/left_function.sql
Labels: size/S

#11792 add table functions `mo_configurations`
  pkg/cnservice/options.go
  pkg/cnservice/server.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/service_ports_test.go
  pkg/cnservice/types.go
  pkg/cnservice/upgrader/newAddTable.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/hakeeper/rsm.go
  pkg/logservice/config.go
  pkg/logservice/option.go
  pkg/logservice/service.go
  pkg/logservice/service_commands.go
  pkg/objectio/utils.go
  pkg/objectio/writer_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/proxy/config.go
  pkg/proxy/server.go
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/table_function/system_view.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/function/ctl/cmd_ping_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/system_view.go
  pkg/testutil/util_new.go
  pkg/tnservice/cfg.go
  pkg/tnservice/cfg_test.go
  pkg/tnservice/store.go
  pkg/tnservice/store_heartbeat.go
  pkg/util/dump_config.go
  pkg/util/dump_config_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  proto/logservice.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/XL

#11694 consider row size when controlling merge memory consumption
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/containers/blkview.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
Labels: kind/bug, kind/enhancement, size/M

#11789 free batches when the last statement finished
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#11845 Add session buffer
  pkg/common/buffer/buffer.go
  pkg/common/buffer/buffer_test.go
  pkg/common/buffer/chunk.go
  pkg/common/buffer/types.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/vm/process/types.go
Labels: kind/feature, size/M

#11841 [Subtask]: optimize shuffle strategy
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/S

#11854 add bvt test for alter sequences
  test/distributed/cases/sequence/alter_sequence_1.result
  test/distributed/cases/sequence/alter_sequence_1.sql
Labels: kind/enhancement, size/S

#11822 fix s-1 11437
  pkg/cnservice/upgrader/newAddTable.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_add_primarykey.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_alter_table_test.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/visit_plan.go
  pkg/util/sysview/sysview.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
  test/distributed/cases/ddl/index_metadata.result
  test/distributed/cases/ddl/index_metadata.sql
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/optimistic/atomicity.result
  test/distributed/cases/optimistic/atomicity.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
  test/distributed/cases/prepare/prepare_all.result
  test/distributed/cases/prepare/prepare_all.sql
Labels: kind/bug, size/L

#11846 update session.process.UnixTime while do new query to refresh now() function result.
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/function/func_datetime_now.result
  test/distributed/cases/function/func_datetime_now.test
Labels: kind/bug, size/S

#11852 add multi cn lock view
  pkg/cnservice/server_query.go
  pkg/cnservice/upgrader/newAddTable.go
  pkg/frontend/authenticate.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/query_service.go
  pkg/sql/colexec/table_function/processlist.go
  pkg/sql/colexec/table_function/system_view.go
  pkg/sql/plan/system_view.go
  proto/query.proto
Labels: kind/feature, size/L

#11880 fileservice: refine aliyun sdk credentials
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs_credentials.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/L

#11879 [Subtask]: support range shuffle for string type
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
  pkg/sql/plan/stats.go
Labels: kind/enhancement, size/M

#11849 Key hash partition prune
  pkg/sql/plan/partition_prune.go
  test/distributed/cases/ddl/partition_prune.result
  test/distributed/cases/ddl/partition_prune.sql
Labels: kind/feature, size/XL

#11732 [Feature] kafka connector manangement.
  pkg/bootstrap/bootstrap.go
  pkg/catalog/types.go
  pkg/cnservice/server_heartbeat.go
  pkg/cnservice/server_task.go
  pkg/cnservice/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/common/moerr/error.go
  pkg/config/configuration.go
  pkg/frontend/authenticate.go
  pkg/frontend/connector.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/task.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_test.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.go
  pkg/pb/task/task.pb.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/connector.go
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/task.go
  pkg/stream/connector/connector.go
  pkg/stream/connector/connector_test.go
  pkg/stream/connector/converter.go
  pkg/stream/connector/converter_test.go
  pkg/stream/connector/decoder.go
  pkg/stream/connector/decoder_avro.go
  pkg/stream/connector/decoder_json.go
  pkg/stream/connector/decoder_json_test.go
  pkg/stream/connector/error.go
  pkg/stream/connector/options.go
  pkg/stream/connector/options_test.go
  pkg/taskservice/daemon_task.go
  pkg/taskservice/daemon_task_test.go
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/mysql_task_storage_test.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/task_runner_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_cron_test.go
  pkg/taskservice/task_service_holder.go
  pkg/taskservice/task_service_test.go
  pkg/taskservice/task_storage_test.go
  pkg/taskservice/types.go
  pkg/tests/service/task_test.go
  pkg/util/export/merge.go
  pkg/util/export/merge_test.go
  proto/plan.proto
  proto/task.proto
  test/distributed/cases/dml/show/database_statistics.result
Labels: kind/feature, size/XXL

#11884 fileservice: reduce allocations in FileWithChecksum.ReadAt and WriteAt
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/file_with_checksum_test.go
Labels: kind/enhancement, size/S

#11882 update HandleMetadataDelete
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/bug, size/S

#11871 Improve alter table
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_add_drop_constraint.result
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
Labels: kind/bug, size/L

#11885 fix comment failure
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/tree/show.go
  test/distributed/cases/ddl/mysql_ddl_1.result
  test/distributed/cases/dml/select/select.result
Labels: kind/bug, size/S

#11888 [Bug]: query from statemnent_info return panic by index out of range [0] with length 0:
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/XS

#11868 Gather data for runtime filter when building hash table
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/compile/scope.go
  proto/pipeline.proto
Labels: kind/feature, size/M

#11898 [Subtask]: support range shuffle for string type
  pkg/sql/plan/shuffle.go
Labels: kind/enhancement, size/XS

#11895 fix DoPrecommitDedupByNode
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/XS

#11903 record conn type in statement_info.stats
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
Labels: kind/feature, size/M

#11901 fileservice: replace S3Config with ObjectStorageArguments
  pkg/fileservice/config.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3.go
Labels: size/M

#11904 add start dynamic cn services support in launch
  cmd/mo-service/config.go
  cmd/mo-service/dynamic.go
  cmd/mo-service/launch.go
  cmd/mo-service/main.go
  etc/launch-dynamic-cn/cn.toml.base
  etc/launch-dynamic-cn/launch.toml
  etc/launch-dynamic-cn/log.toml
  etc/launch-dynamic-cn/tn.toml
Labels: size/M, kind/test-ci

#11907 alter wrong cases
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: size/XS, kind/test-ci

#11889 cherry-pick : Improve alter table
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_add_drop_constraint.result
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
Labels: kind/enhancement, size/L

#11909 fix future will hung if notified twice before Get
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/future.go
Labels: kind/bug, size/S

#11913 modify lock wait tag for some wrong cases
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: size/XS, kind/test-ci

#11783 [Refactor] : Preliminary primary key/unique key constraint checking using fuzzy filter
  go.mod
  go.sum
  pkg/common/bitmap/bitmap.go
  pkg/container/types/tuple.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/filter_test.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/overload.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum.sql
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
Labels: kind/enhancement, size/XL

#11922 remote delete mo_pubs
  pkg/frontend/authenticate.go
Labels: size/XS

#11912 add fetch overview of all txns in current cn support
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/test/types_mock.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/feature, size/M

#11914 Update xorfilter version
  go.mod
  go.sum
  pkg/objectio/versions.go
Labels: kind/bug, size/S

#11924 add bug fatal log in incrservice
  pkg/incrservice/store_sql.go
Labels: kind/bug, size/S

#11751 remove print
  pkg/common/morpc/client.go
Labels: kind/bug, size/S

#11920 add read timeout for lockservice remote lock
  CODEOWNERS
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/future.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service_remote_test.go
Labels: kind/bug, size/M

#11927 return error if received a invalid request
  pkg/lockservice/rpc.go
Labels: kind/bug, size/XS

#11929 fix drop account
  pkg/frontend/authenticate.go
Labels: size/XS

#11926 [bug] distcache: limit the item count for the dist cache.
  pkg/fileservice/cache.go
  pkg/gossip/delegate.go
  pkg/gossip/dist_key_cache.go
  pkg/gossip/node.go
Labels: kind/bug, size/S

#11934 CI: exclude optimized case in merge run
  .github/workflows/merge-trigger.yaml
Labels: size/XS, kind/test-ci

#11940 Revert "[Refactor] : Preliminary primary key/unique key constraint ch…
  go.mod
  go.sum
  pkg/common/bitmap/bitmap.go
  pkg/container/types/tuple.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/filter_test.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/overload.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum.sql
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
Labels: size/XL

#11674 remove issue tag
  test/distributed/cases/dml/insert/insert_duplicate.result
  test/distributed/cases/dml/insert/insert_duplicate.sql
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/atomicity.sql
Labels: kind/bug, size/M

#11930 fix some mpool record number leak bug.
  pkg/common/mpool/mpool.go
  pkg/common/mpool/mpool_test.go
  pkg/frontend/computation_wrapper.go
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/vm/process/process.go
Labels: kind/bug, size/M

#11942 fileservice: fix aliyun sdk sts credentials
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M

#11939 [bug] fix data race in unit test.
  pkg/taskservice/daemon_task.go
Labels: kind/bug, size/S

#11941 Support list partition
  pkg/common/moerr/error.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_key.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/partition_list_test.go
  pkg/sql/plan/partition_range.go
  pkg/sql/plan/partition_test.go
  pkg/sql/plan/partition_util.go
  test/distributed/cases/ddl/partition.result
Labels: kind/feature, size/L

#11933 add `internal` attribute into `mo_configurations` view
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  cmd/mo-service/main.go
  pkg/cnservice/options.go
  pkg/cnservice/types.go
  pkg/config/configuration.go
  pkg/fileservice/cache.go
  pkg/logservice/config.go
  pkg/logservice/option.go
  pkg/logutil/internal.go
  pkg/proxy/config.go
  pkg/tnservice/cfg.go
  pkg/tnservice/service_ports_test.go
  pkg/tnservice/store.go
  pkg/util/dump_config.go
  pkg/util/dump_config_test.go
Labels: kind/feature, size/M

#11950 CI: change bvt sockes timeout to 300000 in merge run
  .github/workflows/merge-trigger.yaml
Labels: size/XS, kind/test-ci

#11875 Feat sha256
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/function_sha2.result
  test/distributed/cases/function/function_sha2.sql
Labels: kind/feature, size/M
