Repository matrixorigin/matrixone, pull requests merged in 2023-07, with the labels that each got.

#10345 fix a potential bug handing filtering
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/S

#10346 Update workflow
  .github/workflows/chatgpt_review.yaml
  .github/workflows/ci.yml
  .github/workflows/command_rerun.yml
  .github/workflows/contributors.yml
  .github/workflows/coverage_pr.yml
  .github/workflows/docu_check.yaml
  .github/workflows/e2e-standalone.yml
  .github/workflows/e2e_upgrade.yml
  .github/workflows/e2e_with_race.yml
  .github/workflows/image-build.yml
  .github/workflows/issue_to_project.yml
  .github/workflows/labeler.yml
  .github/workflows/lint_docs.yml
  .github/workflows/merge-trigger.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
Labels: size/XL, kind/test-ci

#10347 refactor workflow structure
  .github/workflows/ci.yml
  .github/workflows/robot.yml
Labels: size/S

#10344 add codec change log
  pkg/objectio/CHANGELOG.md
Labels: kind/documentation, size/XS

#10349 CI: modify the setting of mergify
  .github/mergify.yml
Labels: size/S, kind/test-ci

#10348 use small-sized vector pool to improve the vector resue rate
  pkg/vm/engine/tae/common/mpool.go
  pkg/vm/engine/tae/containers/batch.go
  pkg/vm/engine/tae/containers/factory.go
  pkg/vm/engine/tae/containers/types.go
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/testutils/mocks/types.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/localseg.go
Labels: kind/enhancement, size/S

#10352 fix possible mpool leak when network fails
  pkg/vm/engine/tae/logtail/service/server.go
Labels: kind/bug, size/XS

#10350 improve tp performance in high concurrency and big data scenarios
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/enhancement, size/M

#10343 optimize build varlena function and remove useless code
  pkg/container/types/bytes.go
  pkg/container/vector/vector.go
Labels: kind/enhancement, size/XS

#10207 Resubmit opt compact
  pkg/vm/engine/tae/tables/base.go
Labels: kind/enhancement, size/S

#10357 update vector pool stats
  pkg/vm/engine/tae/containers/pool.go
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
Labels: kind/enhancement, size/S

#10342 fix rc not work
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/txn.go
  pkg/lockservice/waiter.go
  pkg/sql/compile/compile.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
Labels: kind/bug, size/M

#10360 fix set global err in general tenant
  pkg/frontend/authenticate.go
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: kind/bug, size/S

#10366 fix bug: when retry in lock error. the prepare batch was cleaned
  pkg/frontend/computation_wrapper.go
  pkg/frontend/types.go
Labels: kind/bug, size/XS

#10339 check task expired from heartbeat
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/util/metric/cron_task.go
  pkg/util/test/cron_task_test.go
Labels: kind/bug, size/M, kind/refactor

#10341 improve performance of string compare
  pkg/container/vector/tools.go
  pkg/sql/plan/function/baseTemplate.go
  pkg/sql/plan/function/func_compare.go
Labels: size/S

#10385 Add issue number for window function
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/S

#10387 remove unused code in external
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
Labels: size/M, kind/refactor

#10390 Revert "Resubmit opt compact (#10207)"
  pkg/vm/engine/tae/tables/base.go
Labels: size/S

#10369 not check data changed in retry
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/enhancement, size/M

#10393 fix open/suspend field when create account
  pkg/frontend/authenticate.go
Labels: kind/bug, size/S

#10398 fix bug: panic when truncate table in rc&pessimistic
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/bug, size/XS

#10375 CI: clear the start status of mo when run for head repo
  .github/workflows/e2e-standalone.yml
Labels: size/XS, kind/test-ci

#10399 continue fix (#10074)
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/S

#10367 fix drop primary crash
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
Labels: kind/bug, size/S

#10401 skip empty cached batches for blocking lock
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/bug, size/XS

#10405 fileservice: add by-path read/write locks to disk cache
  pkg/fileservice/disk_cache.go
Labels: kind/enhancement, size/M

#10407 fileservice: refactor ProfileHandler
  cmd/mo-service/debug.go
  pkg/fileservice/profile.go
  pkg/fileservice/profile_test.go
Labels: kind/enhancement, size/S

#10403 fix bug: pk idx is incorrect in select for update
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S

#10408 add pk when write delete in s3
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/deepcopy.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/feature, size/S

#10414 fix the metadata scan panic issue after ddl
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#10413 [bug] the version is not correct when build binary in CI.
  .github/workflows/release.yml
Labels: kind/bug, size/XS

#10412 fix format function
  pkg/vectorize/format/format.go
  test/distributed/cases/function/func_string_format.result
  test/distributed/cases/function/func_string_format.test
Labels: kind/bug, size/M

#10417 fix conflict miscalculation due to range lock
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/service_test.go
Labels: kind/bug, size/M

#10400 fix stmt agg stats with raw data
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
Labels: kind/bug, size/M

#10374 morpc: fix dead lock in ut
  pkg/common/morpc/backend.go
Labels: kind/bug, size/S

#10428 change runner to ubuntu-20.04 to make glibc version to 2.31
  .github/workflows/release.yml
Labels: size/XS, kind/test-ci

#10433 fix buildin function purge_log just handle first table
  pkg/sql/plan/function/func_builtin.go
  test/distributed/cases/function/func_purge_log.result
  test/distributed/cases/function/func_purge_log.sql
Labels: kind/bug, size/S

#10423 fix bug: valueScanBatch was cleaned when retry
  pkg/sql/compile/compile.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#10436 debug: pull repo from corresponding branch
  .github/workflows/release.yml
Labels: size/S, kind/test-ci

#10426 add cfg to set max prepare stmt count
  cmd/mo-service/main.go
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  etc/launch-with-proxy/dn.toml
  etc/launch/dn1.toml
  pkg/cnservice/types.go
  pkg/dnservice/cfg.go
  pkg/dnservice/cfg_test.go
  pkg/dnservice/factory.go
  pkg/dnservice/store.go
  pkg/dnservice/store_test.go
  pkg/frontend/session.go
  pkg/tests/service/dnservice.go
Labels: kind/bug, kind/feature, size/S

#10445 fix insert partition table offset error
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/S

#10449 fix docker-compose config
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
Labels: kind/bug, size/S

#10432 create systeminit task in bootstrap pkg
  pkg/bootstrap/bootstrap.go
  pkg/hakeeper/checker.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_wrap.go
  pkg/sql/plan/base_binder.go
  pkg/tests/service/logservice.go
  pkg/tests/service/service.go
Labels: size/M, kind/refactor

#10456 fileservice: refactor CacheConfig
  pkg/fileservice/cache.go
  pkg/fileservice/example_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/util/export/etl/csv_test.go
Labels: kind/enhancement, size/M

#10458 prolong task timeout limit
  pkg/hakeeper/task/task_scheduler.go
Labels: kind/enhancement, size/XS

#10469 fix logtail lagging gc
  pkg/vm/engine/tae/db/open.go
Labels: kind/bug, size/XS

#10464 fix alter stmt crash bug
  pkg/sql/plan/build_ddl.go
Labels: kind/enhancement, size/XS

#10415 Fix index issue#10353
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_index_util.go
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: kind/bug, size/M

#10448 support alter account restricted in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
Labels: kind/feature, size/XXL

#10461 add morpc stream receive trace
  pkg/common/moprobe/probe.go
  pkg/common/morpc/backend.go
Labels: kind/enhancement, size/S

#10483 [User Bug]:insert导入dmt_001数据集报错
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#10482 add system variable foreign_key_checks
  pkg/frontend/variables.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#10430 fileservice: fix 3rd-party credentials provider
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/S

#10493 fix a mpool leak after stream closed
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/session.go
Labels: size/S

#10497 fix TestSession
  pkg/vm/engine/tae/logtail/service/session.go
Labels: size/XS, kind/test-ci

#10480 Just set pessimistic to run pessimistic. Config is still by default, optimistic.
  etc/launch-tae-multi-CN-tae-DN/cn1.toml
  etc/launch-tae-multi-CN-tae-DN/cn2.toml
  etc/launch-tae-multi-CN-tae-DN/dn.toml
  pkg/cnservice/types.go
  pkg/dnservice/cfg.go
Labels: kind/enhancement, size/S

#10475 skip dup check for update non pk col
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_update.go
Labels: kind/bug, kind/feature, size/S

#10494 init system variable table by config
  pkg/frontend/authenticate.go
Labels: kind/feature, size/S

#10486 [bug] proxy: current way of detecting txn status is not robust
  pkg/frontend/cmd_executor.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/resultset_stmt.go
  pkg/frontend/session.go
  pkg/frontend/status_stmt.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/mysql_conn_buf_test.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/bug, size/L

#10504 add cancel call after receiving RPCMessage
  pkg/common/morpc/backend.go
Labels: kind/bug, size/XS

#10495 logtailreplay: add shared state to PartitionState
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/enhancement, size/S

#10462 Replace go trace with moprobe.
  pkg/common/moprobe/probe.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/enhancement, size/S

#10508 update DoIfDebugEnabled
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/db/db_test.go
  pkg/vm/engine/tae/logtail/tools.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/enhancement, size/S

#10490 Fix and change the Stmt Aggr logic
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
Labels: kind/bug, kind/enhancement, size/M

#10442 bugfix empty stats in agg stmt entity
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
  test/distributed/cases/log/query_stats.result
  test/distributed/cases/log/query_stats.sql
Labels: kind/bug, kind/enhancement, size/M

#10512 Support dump trace and a new indivial work-goroutine to check timeout threshold.
  pkg/util/profile/profile.go
  pkg/util/trace/config.go
  pkg/util/trace/config_test.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
Labels: kind/enhancement, size/L

#10518 Index syntax supports sorting
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_index_util.go
Labels: kind/bug, size/S

#10517 fix a bug that can stop the stmt recording
  pkg/util/trace/impl/motrace/buffer_pipe.go
Labels: kind/bug, size/S

#10521 Append index sort key bvt case
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
Labels: kind/bug, size/S

#10523 Fix the problem of incorrect coverage statistics
  .github/workflows/robot.yml
Labels: size/XS, kind/test-ci

#10519 support alter account restricted in plan
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
Labels: kind/feature, size/S

#10492 fileservice: refactor profile handler
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/profile.go
  pkg/fileservice/profile_test.go
  pkg/fileservice/s3_fs.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/enhancement, size/M

#10524 [feature] hakeeper: support snapshot for HAKeeper.
  pkg/hakeeper/rsm.go
  pkg/logservice/config.go
  pkg/logservice/truncation.go
  pkg/logservice/truncation_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/feature, size/M

#10522 Add FaultInjection in mo_ctl for DN
  pkg/pb/ctl/ctl.pb.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint.go
  pkg/sql/plan/function/ctl/types.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle.go
  proto/ctl.proto
  test/distributed/cases/dml/insert/insert.result
  test/distributed/cases/dml/insert/insert.test
Labels: size/M, kind/test-ci

#10539 fix wrong system variables tuple number
  pkg/frontend/authenticate.go
Labels: kind/bug, size/S

#10536 fix busy loop when closing client
  pkg/common/morpc/server.go
Labels: kind/bug, size/XS

#10537 add logstore append pool
  pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
Labels: kind/enhancement, size/S

#10543 Modify defaultLogtailCollectInterval to 2ms
  pkg/dnservice/cfg.go
Labels: kind/enhancement, size/XS

#10540 dump goutine info when sql run timeout
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/enhancement, size/S

#10534 fix bug: delete same row multi times
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  test/distributed/cases/foreign_key/foreign_key_multilayer.result
  test/distributed/cases/foreign_key/foreign_key_multilayer.sql
Labels: kind/bug, size/M

#10544 refactor: extract the appendLockNode function
  pkg/sql/plan/build_dml_util.go
Labels: size/M, kind/refactor

#10468 add no-parallel join run for shuffle and single cpu scenario
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/types.go
  pkg/container/batch/batch.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/types.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
Labels: kind/bug, kind/enhancement, kind/feature, size/M

#10516 support function `repeat` and add test case.
  pkg/sql/plan/function/baseTemplate.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/func_builtin_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_string_repeat.result
  test/distributed/cases/function/func_string_repeat.sql
Labels: kind/feature, size/M

#10560 fix span NeedProfile and add doc.
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/trace.go
  pkg/util/trace/type.go
Labels: kind/bug, kind/enhancement, size/S

#10558 Revert "refactor: extract the appendLockNode function (#10544)"
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/M

#10564 fileservice: handle role arn in aliyun and qcloud credentials providers
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/enhancement, size/S

#10566 fix bug: lost project node in select for update
  pkg/sql/compile/compile.go
  test/distributed/cases/dml/update/update.result
  test/distributed/cases/dml/update/update.test
Labels: kind/bug, size/S

#10546 fix hash_value function bug will cause result unstable in one machine.
  pkg/sql/plan/function/func_builtin.go
Labels: kind/bug, size/S

#10570 fileservice: s3 credential provider clean-ups
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/enhancement, size/M

#10569 Remove the extra configuration items of dnservice
  pkg/dnservice/cfg.go
  pkg/dnservice/factory.go
  pkg/frontend/txn.go
  pkg/frontend/util.go
  pkg/sql/compile/scope.go
  pkg/tests/service/dnservice.go
  pkg/txn/storage/tae/storage.go
Labels: size/S, kind/refactor

#10582 Improve stats calculate cost while collect statement info
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/enhancement, size/M

#10584 fix the AnalyzeInfo wrong issue which is due to no reset
  pkg/sql/compile/compile.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#10547 support oridinary mysql sql stmt with parser / phase 1
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
Labels: kind/enhancement, size/XXL

#10588 update logstore config
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
Labels: kind/enhancement, size/XS

#10592 compact logtail txn table to reduce memory usage
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/scanner.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
Labels: kind/enhancement, size/M

#10591 Fix bug: need catch constant fold error
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/S

#10563 add object name column for metadata scan
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/plan/metadata_scan.go
  pkg/vm/engine/disttae/txn_table.go
  proto/plan.proto
Labels: kind/bug, kind/enhancement, size/S

#10575 add a new field "CatalogVersion" in mo_tables
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/objectio/CHANGELOG.md
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtailPushModel.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/sysblock.go
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/feature, size/L

#10595 verificate set global system variables between different accounts
  test/distributed/cases/database/config.result
  test/distributed/cases/database/config.sql
Labels: size/S, kind/test-ci

#10594 fix query nil check while do MarshalPlan
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#10580 Add error handling to doIncrementalCheckpoint in ForceCKP
  pkg/vm/engine/tae/db/checkpoint/testutils.go
Labels: kind/bug, size/XS

#10609 partition expression support mod operator
  pkg/sql/plan/partition_binder.go
  pkg/sql/plan/partition_hash_test.go
  pkg/sql/plan/partition_list_test.go
  pkg/sql/plan/partition_range_test.go
Labels: kind/bug, size/S

#10601 [feature] logservice: add API to update CN work state in HAKeeper.
  pkg/clusterservice/cluster.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/logservice/logservice_test.go
  pkg/pb/metadata/metadata.pb.go
  proto/logservice.proto
  proto/metadata.proto
Labels: kind/feature, size/XL

#10561 [feature] proxy: add connection attributes to username parameter.
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_protocol.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/doc.go
  pkg/proxy/handshake.go
  pkg/proxy/label_info.go
  pkg/proxy/label_info_test.go
  pkg/proxy/router.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
  pkg/util/test/cron_task_test.go
Labels: kind/feature, size/M

#10572 add privileges check for alter config
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/database/config.result
  test/distributed/cases/database/config.sql
Labels: kind/feature, size/S

#10599 Comment hint
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: kind/enhancement, size/S

#10603 fix dup key and others errors in rc retry
  pkg/sql/compile/compile.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#10614 fix bug: execute with date type panic
  pkg/sql/util/eval_expr_util.go
Labels: kind/bug, size/XS

#10600 fix append2, autocompactablk2
  pkg/vm/engine/tae/db/db_test.go
Labels: kind/bug, size/S

#10590 fix the typo for cloud_nonuser_sql
  pkg/frontend/cmd_executor.go
  pkg/frontend/constant/constant.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result.go
  pkg/frontend/types.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/S

#10607 Improve perf ON trace Span Free and Span handle Hung checker
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_bench_test.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/test/mo_trace_hung_test.go
Labels: kind/bug, kind/enhancement, size/L

#10284 more comments for Relation.PrimaryKeysMayBeModified and other clean-ups
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/types.go
Labels: size/S

#10628 add bvt test for priv check
  test/distributed/cases/database/config_1.result
  test/distributed/cases/database/config_1.sql
Labels: size/S, kind/test-ci

#10581 add filter for system view schemata
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: kind/bug, size/S

#10627 fix memory leak in logstore
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
Labels: kind/bug, size/S

#10608 Lock table in load stmt
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_load.go
Labels: kind/enhancement, size/M

#10638 remove bvt tag
  test/distributed/cases/database/system_variables.sql
Labels: size/XS, kind/test-ci

#10644 fix waiter reference count incorrectly
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_test.go
Labels: kind/bug, size/S

#10636 Support customized initial value by using AUTO_INCREMENT=n
  pkg/incrservice/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
  test/distributed/cases/auto_increment/auto_increment_columns.result
  test/distributed/cases/auto_increment/auto_increment_columns.sql
Labels: kind/feature, size/S

#10625 fileservice: add rrsa credential to aliyun
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/enhancement, size/S

#10622 Improve insert check pk dup
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/colexec/preinsertunique/preinsertunique.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/partition_util.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/process/types.go
Labels: kind/bug, kind/enhancement, size/L

#10641 [feature] logservice: add API to delete CN store from HAKeeper.
  pkg/hakeeper/rsm.go
  pkg/hakeeper/rsm_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.pb.go
  proto/logservice.proto
Labels: kind/feature, size/M

#10652 [bug] logservice: fix compatibility issue when upgrade.
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/metadata/metadata.pb.go
  proto/logservice.proto
  proto/metadata.proto
Labels: kind/bug, size/S

#10653 skip lock if all pk filtered
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/types.go
Labels: kind/bug, size/L

#10668 remove log pkg usage
  cmd/mo-service/main.go
  pkg/common/morpc/examples/pingpong/main.go
  pkg/common/morpc/examples/stream/main.go
  pkg/testutil/testengine/testdata.go
Labels: kind/bug, kind/enhancement, size/S

#10611 abort txn if has s3 operations in RC mode
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#10665 fix bug: not deal with null for execute stmt
  pkg/sql/colexec/evalExpression.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#10670 fix bug: send bool result incorrect
  pkg/frontend/mysql_protocol.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/S

#10673 fix 10499 and quick return if any null used in pk filter expr
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, kind/enhancement, size/M

#10645 CI: Change MergeRun to parallel
  .github/workflows/merge-trigger.yaml
Labels: size/M, kind/test-ci

#10675 Auto set transaction related configs.
  etc/launch-tae-CN-tae-DN/cn.toml
  etc/launch-tae-CN-tae-DN/dn.toml
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/dn.toml
  etc/launch-with-proxy/dn.toml
  etc/launch/cn1.toml
  etc/launch/dn1.toml
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/sql/colexec/s3util.go
Labels: kind/enhancement, size/S

#10646 Alter grammer
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/plan/build_ddl.go
Labels: kind/enhancement, size/XXL

#10679 change config in mo checkin regression
  .github/workflows/e2e-compose.yml
  .github/workflows/e2e-standalone.yml
  .github/workflows/merge-trigger.yaml
  optools/compose_bvt/compose_bvt.sh
  optools/mo_checkin_regression/mo_checkin_regression.yaml
Labels: size/S, kind/test-ci

#10309 Enable runtime filters on multi CN
  pkg/frontend/test/engine_mock.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/runtime_filter.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/protogen.sh
  pkg/vm/engine/disttae/runtime_filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
  proto/pipeline.proto
Labels: kind/feature, size/L

#10686 Fix statement out-of-bounds within workspace
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/XS

#10688 fix a cn client race may cause panic
  pkg/cnservice/cnclient/client.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#9682 [Feature]: Data Overlap Checker for MemCache
  pkg/fileservice/cache.go
  pkg/fileservice/checks/interval/interval_tree.go
  pkg/fileservice/checks/interval/interval_tree_test.go
  pkg/fileservice/checks/interval/overlap.go
  pkg/fileservice/checks/interval/overlap_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/objcache/clockobjcache/clock.go
  pkg/fileservice/objcache/lruobjcache/lru.go
  pkg/fileservice/objcache/lruobjcache/lru_test.go
  pkg/objectio/cache.go
  pkg/vm/engine/tae/model/index.go
Labels: kind/feature, kind/api-change, size/XL

#10694 feat: proxy should migrate connections to selected CN if possible
  pkg/proxy/rebalancer.go
  pkg/proxy/rebalancer_test.go
Labels: kind/feature, size/M

#10672 change error msg
  pkg/sql/compile/operator.go
Labels: kind/bug, size/XS

#10697 not notice when pr closed
  .github/workflows/merge-trigger.yaml
Labels: size/XS

#10647 fileservice: disable aliyun and qcloud credentials
  pkg/fileservice/s3_fs_credentials.go
Labels: kind/bug, size/S

#10635 fileservice: clean-up config files; add default disk cache path
  cmd/mo-service/config.go
  etc/bootstrap-example2/dn-node-1.toml
  etc/bootstrap-example2/dn-node-2.toml
  etc/cn-minimal-test.toml
  etc/cn-non-dist-memory.toml
  etc/cn-standalone-dist-tae-test.toml
  etc/cn-standalone-dist-tae.toml
  etc/cn-standalone-test.toml
  etc/dn-minimal-s3-test.toml
  etc/dn-minimal-test.toml
  etc/launch/cn1.toml
  etc/launch/dn1.toml
  etc/launch/log1.toml
  etc/launch/log2.toml
  etc/launch/log3.toml
  etc/log-minimal-test.toml
Labels: kind/enhancement, size/M

#10705 fix bug: check pk dup with uuid panic
  pkg/sql/plan/build_insert.go
Labels: kind/bug, size/XS

#10714 improve performance if locked with no conflict
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/sql/colexec/lockop/lock_op.go
Labels: kind/enhancement, size/M

#10700 mo-service: fix file service creation
  cmd/mo-service/config.go
Labels: kind/bug, size/XS

#10717 fileservice: add span profiler
  go.mod
  go.sum
  pkg/fileservice/profile.go
  pkg/fileservice/profile_info.go
  pkg/fileservice/profile_span.go
  pkg/fileservice/profile_span_test.go
  pkg/fileservice/profile_statement.go
Labels: kind/enhancement, size/M

#10678 promote ut coverage for front
  pkg/frontend/authenticate_test.go
Labels: kind/enhancement, size/L

#10479 Prefetch deletes for block merge reader partition reader
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/enhancement, size/M

#10719 fix check data changed
  pkg/sql/colexec/lockop/lock_op.go
  pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
Labels: kind/bug, size/XS
