Repository matrixorigin/matrixone, pull requests merged in 2024-04, with the labels that each got.

#15273 Revert "[refactor] : continue reuse memory for parser"
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/branch.go
  pkg/sql/parsers/tree/compound.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/declare.go
  pkg/sql/parsers/tree/delete.go
  pkg/sql/parsers/tree/do.go
  pkg/sql/parsers/tree/execute.go
  pkg/sql/parsers/tree/function.go
  pkg/sql/parsers/tree/grant.go
  pkg/sql/parsers/tree/iteration.go
  pkg/sql/parsers/tree/kill.go
  pkg/sql/parsers/tree/lock.go
  pkg/sql/parsers/tree/mo_dump.go
  pkg/sql/parsers/tree/procedure.go
  pkg/sql/parsers/tree/replace.go
  pkg/sql/parsers/tree/reset.go
  pkg/sql/parsers/tree/revoke.go
  pkg/sql/parsers/tree/select.go
  pkg/sql/parsers/tree/select_lock.go
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/table_function.go
  pkg/sql/parsers/tree/values.go
  pkg/sql/parsers/tree/view.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/query_builder.go
Labels: size/XXL

#15262 change threshold for small scan
  pkg/vm/engine/disttae/tools.go
Labels: size/XS, kind/enhancement

#15219 fix panic
  pkg/common/morpc/codec.go
Labels: kind/bug, size/S

#15270 fix explain
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
Labels: kind/bug, size/M

#15258 Solve cross tenant system view query error
  pkg/cnservice/upgrader/new_add_table.go
  pkg/util/sysview/sysview.go
Labels: kind/bug, size/S

#15184 make table.Pkey not nil
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/colexec/preinsert/preinsert_test.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/util.go
  pkg/sql/plan/agg_pushdown_pullup.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/build_alter_add_primarykey.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/runtime_filter.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/M, kind/refactor

#15243 [refactor] remove tableDef in some operator
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertunique/preinsertunique.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/deepcopy.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/M, kind/refactor

#15213 support Keep result set column name as user specified in SQL
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/plsql_interpreter.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/session.go
  pkg/frontend/show_account_test.go
  pkg/frontend/show_subsriptions.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  pkg/proxy/event.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/example/eg_mysql.go
  pkg/sql/parsers/sqlparse.go
  pkg/sql/parsers/sqlparse_test.go
  pkg/sql/parsers/tree/cstr.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_expr_test.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/explain/column_prune_test.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/explain/marshal_query_test.go
  pkg/sql/plan/explain/tpch_explain_test.go
  pkg/sql/plan/partition_hash_test.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/partition_range.go
  pkg/sql/plan/partition_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/recursive_test.go
  pkg/sql/plan/tpch_test.go
  test/distributed/cases/database/select_origin.result
  test/distributed/cases/database/select_origin.sql
Labels: kind/feature, size/XXL

#15263 CI: add `musl build` and related release job
  .github/workflows/release.yml
  Makefile
Labels: size/M, kind/test-ci

#15232 support create table like stmt
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
  test/distributed/cases/database/create_table_like.result
  test/distributed/cases/database/create_table_like.sql
Labels: kind/feature, size/XXL

#15281 CI: fix 1.1 dev ci
  .github/workflows/release.yml
Labels: kind/test-ci

#15257 [enhancement] sql: add client host and proxy host in session status.
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/pb/proxy/proxy.go
  pkg/pb/proxy/proxy.pb.go
  pkg/pb/proxy/proxy_test.go
  pkg/pb/status/status.pb.go
  pkg/proxy/client_conn.go
  pkg/proxy/label_info.go
  pkg/proxy/router.go
  pkg/proxy/server_conn_test.go
  pkg/sql/colexec/table_function/processlist.go
  proto/proxy.proto
  proto/status.proto
  test/distributed/cases/dml/show/database_statistics.result
Labels: size/M, kind/enhancement

#15280 [Enhancement] add conn and req count metric
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/frontend.go
  pkg/util/metric/v2/metrics.go
Labels: size/S, kind/enhancement

#15266 Revert "logtailreplay: various changes (#15099)"
  cmd/mo-service/debug.go
  cmd/mo-service/main.go
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/profile.go
  pkg/fileservice/profile_info.go
  pkg/fileservice/profile_span.go
  pkg/fileservice/profile_span_test.go
  pkg/fileservice/profile_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtailPullModel.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/pipeline/pipeline.go
Labels: kind/bug, size/L

#15278 fix stats for limit node
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/pushdown.result
Labels: size/S, kind/enhancement

#15285 [BugFix]: Replace MaxArrayLimit to 65535 from 65536
  pkg/container/types/array.go
  test/distributed/cases/array/array.result
Labels: kind/bug, size/XS

#15289 Revert "unlimited the RPC msg body size (#15250)"
  pkg/tnservice/factory.go
Labels: kind/bug, size/XS

#15287 fix not init using toml file for some variables
  pkg/frontend/session.go
Labels: kind/bug, size/S

#15271 fix explain
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
Labels: kind/bug, size/M

#15225 record cu when plan errs happend
  pkg/frontend/mysql_cmd_executor.go
Labels: size/S, kind/enhancement

#15300 fix bug: ut（compile_test.go) failed
  pkg/testutil/testengine/testdata.go
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: kind/bug, size/S

#15253 rm tag 15984
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/test_escaped_by01.csv
Labels: kind/bug, size/S

#15304 CI: upgrade docker compose to v2
  .github/workflows/e2e-compose.yaml
Labels: kind/test-ci

#15064 CI: modify build version
  Makefile
Labels: size/XS, kind/test-ci

#15277 add one column for mo_snapshots
  pkg/cnservice/upgrader/new_add_column.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/sql/plan/mock.go
  pkg/util/export/table/table.go
Labels: size/S, kind/enhancement

#15302 clean batch when hanging in join
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
Labels: size/S

#15260 [Fix] remove trimspace in user authenticate
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
Labels: kind/bug, size/S

#15294 fix delete chain ppstring
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/task.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/M, kind/enhancement

#15264 Solve cross tenant system view query error
  pkg/cnservice/upgrader/new_add_table.go
  pkg/util/sysview/sysview.go
Labels: kind/bug, size/S

#15317 remove issue tag
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: size/S

#15319 [Feature] add function sysdate
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_datetime_now.result
  test/distributed/cases/function/func_datetime_now.test
Labels: kind/feature, size/S

#15303 fix json_extract
  pkg/container/bytejson/bytejson.go
  test/distributed/cases/ddl/json_type.result
  test/distributed/cases/ddl/json_type.sql
Labels: kind/bug, size/S

#15290 fix a bug that some filters don't push to block filter for 1.1-dev
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#15306 CI: upgrade docker compose to v2 for 1.1-dev
  .github/workflows/e2e-compose.yaml
Labels: kind/test-ci

#15214 [Feature] CREATE ACCOUNT support prepared statement
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/utils.go
  proto/plan.proto
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_account.sql
Labels: kind/feature, size/XXL

#15320 fileservice: remove unused codes
  cmd/mo-service/debug.go
  cmd/mo-service/main.go
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/profile.go
  pkg/fileservice/profile_info.go
  pkg/fileservice/profile_span.go
  pkg/fileservice/profile_span_test.go
  pkg/fileservice/profile_test.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: size/XL, kind/enhancement

#15305 fix json_extract(#1.1-dev)
  pkg/container/bytejson/bytejson.go
Labels: kind/bug, size/XS

#15318 add case for create table like
  test/distributed/cases/ddl/create_table_like.result
  test/distributed/cases/ddl/create_table_like.sql
Labels: kind/feature, size/M

#15311 fix keep remote lock
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/backend.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/tnservice/store.go
  pkg/txn/service/service_cn_handler_test.go
Labels: size/M

#15297 fix keep remote lock
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/backend.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/lockservice/types.go
  pkg/tnservice/store.go
  pkg/txn/service/service_cn_handler_test.go
Labels: size/M

#15329 fix a bug which disables runtime filter
  pkg/sql/plan/runtime_filter.go
Labels: kind/bug, size/S

#15321 add alter table for enum type.
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
Labels: kind/bug, size/M

#15315 [Tech Request]: optimize in filter with large vector step 2
  pkg/container/vector/search.go
Labels: size/S, kind/enhancement

#15335 Handle load data from s3 url panic
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/plan/build_load.go
Labels: kind/bug, size/S

#15308 flush deletes by block
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: size/M, kind/enhancement

#15336 two phase transfer in flushing
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/M, kind/enhancement

#15284 [Enhancement] add conn and req count metric
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/frontend.go
  pkg/util/metric/v2/metrics.go
Labels: size/S, kind/enhancement

#15330 cherry-pick sys variables
  pkg/config/configuration.go
  pkg/frontend/session.go
Labels: kind/bug, size/S

#15259 [Fix] remove trimspace in user authenticate
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
Labels: kind/bug, size/S

#15323 add alter table for enum type(1.1-dev)
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
Labels: size/M

#15283 bugfix: copy the map while SetLabelSelector
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
Labels: kind/bug, size/S

#15256 [enhancement] sql: add client host and proxy host in session status.
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/pb/proxy/proxy.go
  pkg/pb/proxy/proxy.pb.go
  pkg/pb/proxy/proxy_test.go
  pkg/pb/status/status.pb.go
  pkg/proxy/client_conn.go
  pkg/proxy/label_info.go
  pkg/proxy/router.go
  pkg/proxy/server_conn_test.go
  pkg/sql/colexec/table_function/processlist.go
  proto/proxy.proto
  proto/status.proto
  test/distributed/cases/dml/show/database_statistics.result
Labels: size/M, kind/enhancement

#15255 fix metric/sql_statement_total and disable tcp pkg count.
  pkg/config/configuration.go
  pkg/frontend/cmd_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/trace.go
Labels: kind/bug, size/S

#15341 resubmit "[Tech Request]: optimize in filter with large vector step 2 "
  pkg/container/vector/search.go
Labels: size/S, kind/enhancement

#15342 undo change of rightjoin.sendlast()(#14136)
  pkg/sql/colexec/right/join.go
Labels: size/M

#15351 fix sync lock table between cn and dn
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
Labels: size/S

#15350 fix sync lock table between cn and dn
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
Labels: size/S

#15353 CI: migrate ci and remove some unuse file for 1.1-dev
  .github/actions/ecr/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/e2e-compose.yaml
  .github/workflows/e2e-standalone.yaml
  .github/workflows/e2e-upgrade.yaml
  .github/workflows/entrypoint.yaml
  .github/workflows/image-build.yml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
  .github/workflows/utils.yaml
Labels: kind/test-ci

#15354 CI: migrate ci and remove unuse file
  .github/actions/ecr/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/e2e-compose.yaml
  .github/workflows/e2e-standalone.yaml
  .github/workflows/e2e-upgrade.yaml
  .github/workflows/entrypoint.yaml
  .github/workflows/image-build.yml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
  .github/workflows/utils.yaml
Labels: kind/test-ci

#15352 [buf] ut: fix a ut case.
  pkg/queryservice/query_service_test.go
Labels: kind/bug, size/S

#15348 avoid rpc waiting too long after connection disconnected
  pkg/common/morpc/backend.go
Labels: kind/bug, size/S

#15343 fix insert stats overcount
  pkg/sql/colexec/insert/insert.go
Labels: kind/bug, size/XS

#15313 [Tech Request]: optimize in filter with large vector
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/M, kind/enhancement

#15363 [Fix] table name be overwrited when show table status
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
Labels: kind/bug, size/XS

#15366 Insert ignore
  test/distributed/cases/dml/insert/insert_ignore.result
  test/distributed/cases/dml/insert/insert_ignore.sql
Labels: kind/feature, size/M

#15333 cherry pick Supports REFERENTIAL_CONSTRAINTS system view
  pkg/cnservice/upgrader/new_add_table.go
  pkg/util/sysview/sysview.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/tenant.result
Labels: kind/bug, size/S

#15361 chore: record exec plan and cu stats while query failed in mo 1.1
  pkg/frontend/cmd_executor.go
  pkg/frontend/mysql_cmd_executor.go
Labels: size/S, kind/enhancement

#15362 [Fix] table name overwritten when show table status
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result.go
Labels: kind/bug, size/XS

#15326 fix usage of PrefixCompare
  pkg/vm/engine/tae/index/zm.go
Labels: kind/bug, size/S

#15383 non-sys tenant should not support cluster level backup(#1.1-dev)
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
Labels: kind/bug, size/S

#15387 support push from_unixtime to block filters
  pkg/sql/plan/function/list_builtIn.go
Labels: size/XS, kind/enhancement

#15406 cherry-pick index related commits to 1.1-dev
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/feature, size/S

#15411 fix handle lock table bind changed err
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/service_test.go
Labels: size/S

#15394 [#15374] fix panic,since persisted appendable block is not sorted!
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
Labels: size/M

#15397 support unknown flag
  pkg/common/morpc/codec.go
  pkg/common/morpc/codec_test.go
  pkg/common/morpc/server.go
Labels: size/S, kind/enhancement

#15418 Fix segment falut bug for hyperloglog
  pkg/vm/engine/tae/blockio/write_index.go
Labels: kind/bug, size/XS

#15409 always try to push block filter for 1.1
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#15328 [fix] the process for enum type in external
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/S

#15384 let go schedule cpu in large ap query
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/mergegroup/group.go
Labels: size/S, kind/enhancement

#15382 non-sys tenant should not support cluster level backup
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
Labels: kind/bug, size/S

#15379 Add interface for list snapshot
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/snapshot.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
Labels: kind/feature, size/M

#15424 Adjust mo_indexes Upgrade Order
  pkg/cnservice/upgrader/upgrader.go
Labels: kind/bug, size/S

#15334 [Feature] Load parquet files, basic
  go.mod
  go.sum
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/parquet.go
  pkg/sql/colexec/external/parquet_test.go
  pkg/sql/colexec/external/types.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/utils.go
  test/distributed/cases/load_data/load_data_parquet.result
  test/distributed/cases/load_data/load_data_parquet.sql
  test/distributed/resources/load_data/simple.parq
Labels: kind/feature, size/L

#15404 a quick fix that avoids the failure of mo_table_size when the index table name is empty
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S

#15428 Handle system view Processlist Not Available issue
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/frontend/internal_executor.go
  pkg/stream/connector/connector_test.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/metric/mometric/metric_collector_test.go
  pkg/util/sysview/sysview.go
  pkg/util/trace/impl/motrace/example/main.go
  pkg/util/trace/impl/motrace/schema_test.go
Labels: kind/bug, size/S

#15412 fix handle lock table bind changed err
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/service_test.go
Labels: size/S

#15410 [Feature] implement UNHEX() function
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_unhex.result
  test/distributed/cases/function/func_unhex.sql
Labels: kind/feature, size/M

#15408 fix date_add with param input
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/expression/temporal_interval.result
  test/distributed/cases/expression/temporal_interval.sql
Labels: kind/bug, size/S

#15391 add case for information_schema.referenctial_constraints
  test/distributed/cases/metadata/information_schema.result
  test/distributed/cases/metadata/information_schema.sql
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: kind/bug, size/S

#15437 fix validate lock service
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: size/M

#15378 handle partition boundary violations
  pkg/sql/colexec/lockop/lock_op.go
  test/distributed/cases/ddl/partition4.result
  test/distributed/cases/ddl/partition4.sql
Labels: kind/bug, size/S

#15439 [Tech Request]: time and datetime type can not fold correctly (#14698)
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#15360 [BugFix]: Simplify Vector Index KNN Query Plan for improved performance
  pkg/catalog/types.go
  pkg/frontend/variables.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_vector_index_util.go
  pkg/sql/plan/make.go
  pkg/sql/plan/make_test.go
  pkg/vectorize/moarray/external.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
  test/distributed/cases/array/array_index_knn.result
  test/distributed/cases/array/array_index_knn.sql
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: kind/bug, size/XL

#15390 fix explain execute
  pkg/frontend/mysql_cmd_executor.go
Labels: size/S

#15435 [cherry-pick-1.1-dev] fix load data stmt affect rows count calculation incorrectly
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#15413 two-phase transfer for merge
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: size/M, kind/enhancement

#15425 cherry-pick bug fixes to 1.1-dev
  pkg/container/types/bytes.go
  pkg/container/vector/search.go
  pkg/container/vector/utils_test.go
  pkg/sql/plan/function/func_prefix.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/index/zm.go
Labels: kind/bug, kind/feature, size/M

#15419 [BugFix]: Fix Vector Scalar Type Conversion issue
  pkg/sql/plan/function/type_check.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/vector/vector_type.result
  test/distributed/cases/vector/vector_type.sql
Labels: kind/bug, size/S

#15429 support push from_unixtime to block filters
  pkg/sql/plan/function/list_builtIn.go
Labels: size/XS, kind/enhancement

#15392 add case for information_schema.referenctial_constraints(1.1-dev)
  test/distributed/cases/metadata/information_schema.result
  test/distributed/cases/metadata/information_schema.sql
Labels: kind/bug, size/S

#15314 [perf] enhance the handling for non-compliant JSON data
  pkg/sql/colexec/external/external.go
Labels: size/XS, kind/enhancement

#15400 fileservice: refine io lock
  pkg/fileservice/cache.go
  pkg/fileservice/io_lock.go
  pkg/fileservice/io_lock_test.go
  pkg/fileservice/io_vector.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/M, kind/enhancement

#15444 fix db not found when `mo_table_size`
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S

#15446 fix blocksel
  pkg/sql/plan/stats.go
Labels: kind/bug, size/XS

#15449 Dealing with tenant upgrade failure issues
  pkg/cnservice/server_task.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/util/export/table/table.go
  pkg/util/test/cron_task_test.go
Labels: kind/bug, size/M

#15430 add set keep user target list case
  test/distributed/cases/set/set_keep_user_target.result
  test/distributed/cases/set/set_keep_user_target.sql
Labels: kind/feature, size/S

#15440 unlimited the msg size to logservice
  pkg/tnservice/factory.go
Labels: size/XS, kind/enhancement

#15415 add case for json_extract
  test/distributed/cases/function/func_json_extract.result
  test/distributed/cases/function/func_json_extract.test
Labels: kind/bug, size/S

#15327 [fix] : remove pre check logic for create unique index for existed table
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/types.go
  pkg/sql/compile/util.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter_add_unique_index.result
  test/distributed/cases/ddl/alter_add_unique_index.sql
  test/distributed/cases/optimistic/unique_secondary_index.result
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
Labels: kind/bug, size/M

#15427 [opt] : disable dup check for create secondary-index for existed table
  pkg/sql/plan/build_dml_util.go
Labels: size/XS, kind/enhancement

#15454 cherry pick "optimize plan for update with secondary index column (#14856)" to 1.1
  pkg/sql/plan/build_dml_util.go
Labels: size/S, kind/enhancement

#15380 refactor Compile. remove unused field
  pkg/frontend/cmd_executor.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/session.go
  pkg/frontend/status_stmt.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/output/output_test.go
  pkg/sql/colexec/output/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
Labels: size/S, kind/refactor

#15451 fileservice: refine io lock
  pkg/fileservice/io_lock.go
Labels: size/S, kind/enhancement

#15357 skip index table when dedup
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S, kind/enhancement

#15456 [Feature]: Replace Decode( "...", "hex") with UNHEX("...")
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/function/func_encode_decode.result
  test/distributed/cases/function/func_encode_decode.sql
Labels: kind/feature, size/S

#15462 fix stats with limit
  pkg/sql/plan/stats.go
Labels: kind/bug, size/XS

#15274 [BugFix]: Insert Performance Fix
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/S

#15468 fix bvt/purge_log
  test/distributed/cases/function/func_purge_log.result
  test/distributed/cases/function/func_purge_log.sql
  test/distributed/cases/table/system_table_cases.sql
Labels: kind/bug, size/S

#15464 fix data race when creating table
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/bug, size/S, kind/enhancement

#15450 fix date_add with param input (#1.1-dev)
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/expression/temporal_interval.result
  test/distributed/cases/expression/temporal_interval.sql
Labels: kind/bug, size/S

#15476 [Feature] support db modification in publication
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/alter.go
  test/distributed/cases/tenant/pub_sub2.result
  test/distributed/cases/tenant/pub_sub2.sql
Labels: kind/feature, size/XXL

#15474 add case
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
Labels: kind/bug, size/S

#15471 modify defaultMaxLockRowCount to reduce deadlocks
  pkg/lockservice/cfg.go
Labels: size/XS

#15467 fix select variable fail occasionally
  test/distributed/cases/set/set_keep_user_target.result
  test/distributed/cases/set/set_keep_user_target.sql
Labels: kind/bug, size/XS

#15470 pick 'chore: stable bvt case result abort statement query_type' in 1.1
  test/distributed/cases/statement_query_type/regression.result
  test/distributed/cases/statement_query_type/regression.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
  test/distributed/cases/statement_query_type/statement_query_type_1.result
  test/distributed/cases/statement_query_type/statement_query_type_1.sql
  test/distributed/cases/statement_query_type/statement_query_type_2.result
  test/distributed/cases/statement_query_type/statement_query_type_2.sql
  test/distributed/cases/statement_query_type/statement_query_type_3.result
  test/distributed/cases/statement_query_type/statement_query_type_3.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_2.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_2.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_3.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_3.sql
Labels: kind/bug, size/XXL

#15475 feat: refine python-udf local launch
  pkg/udf/pythonservice/cfg.go
  pkg/udf/pythonservice/service.go
Labels: size/S, kind/enhancement

#15197 Refactor GC codes phase 2
  pkg/vm/engine/tae/blockio/types.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/db/gc/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/feature, size/L, kind/refactor, kind/enhancement

#15478 detect CN status before remove the lock on an orphan txn
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/backend.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
Labels: kind/bug, size/M

#15472 modify defaultMaxLockRowCount to reduce deadlocks
  pkg/lockservice/cfg.go
Labels: size/XS

#15438 fix validate lock service
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: size/M

#15473 Refine code for supporting snapshot read feature
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/plan/function/func_mo.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
Labels: size/S

#15484 fix bvt/purge_log (#1.1-dev)
  test/distributed/cases/function/func_purge_log.result
  test/distributed/cases/function/func_purge_log.sql
Labels: kind/bug, size/S

#15486 fix panic too large fixed slice
  pkg/lockservice/cfg.go
Labels: size/XS

#15487 fix panic too large fixed slice
  pkg/lockservice/cfg.go
Labels: size/XS

#15483 let go schedule cpu in large ap query (#15384) to 1.1
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/mergegroup/group.go
Labels: kind/bug, size/S

#15340 Support snapshot-read-1
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn_test.go
  pkg/frontend/util_test.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/feature, size/L

#15493 Modify case about auth
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: size/S

#15461 [Feature] CREATE, ALTER, DROP account support prepared statement
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
  pkg/frontend/util.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/agg/protogen.sh
  pkg/sql/colexec/multi_col/group_concat/protogen.sh
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/drop.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/function/functionAgg/protogen.sh
  pkg/sql/plan/utils.go
  pkg/vm/engine/memoryengine/protogen.sh
  pkg/vm/engine/protogen.sh
  pkg/vm/engine/tae/db/protogen.sh
  proto/gen.sh
  proto/plan.proto
  test/distributed/cases/zz_accesscontrol/alter_account_prepare.result
  test/distributed/cases/zz_accesscontrol/alter_account_prepare.sql
  test/distributed/cases/zz_accesscontrol/create_account.result
  test/distributed/cases/zz_accesscontrol/create_account.sql
  test/distributed/cases/zz_accesscontrol/drop_account.result
  test/distributed/cases/zz_accesscontrol/drop_account.sql
Labels: kind/feature, size/XXL

#15500 [Fix] Use EncodeSlice instead of EncodeSliceWithCap
  pkg/sql/plan/function/functionAgg/bitmap_or.go
Labels: kind/bug, size/XS

#15503 [bug] tae: fix hang issue and reserve some table IDs.
  pkg/catalog/types.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/db/test/storage_usage_test.go
Labels: kind/bug, size/S

#15490 add new etc file
  etc/launch-dynamic-with-proxy/cn.toml.base
  etc/launch-dynamic-with-proxy/launch.toml
  etc/launch-dynamic-with-proxy/log.toml
  etc/launch-dynamic-with-proxy/proxy.toml
  etc/launch-dynamic-with-proxy/tn.toml
Labels: size/M, kind/test-ci

#15480 [Feature]: Replace `Decode("", "base64")` with `FROM_BASE64`
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
  test/distributed/cases/function/func_encode_decode.result
  test/distributed/cases/function/func_encode_decode.sql
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: kind/feature, size/L

#15506 [enhancement] add some logs
  pkg/common/morpc/backend.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: size/XS, kind/enhancement

#15106 [Tech Request]: refactor runtime filter using message
  pkg/container/batch/types.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/runtime_filter.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/types.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/utils.go
  pkg/vm/process/message.go
  pkg/vm/process/runtimeFilterMsg.go
  proto/pipeline.proto
  test/distributed/cases/optimizer/top.result
Labels: size/L, kind/refactor

#15502 split lock-time-consumption stats
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: size/S, kind/refactor

#15515 Revert "detect CN status before remove the lock on an orphan txn"
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/backend.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
Labels: size/M

#15517 [fix] insert ignore values affected return 0 rows
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
Labels: kind/bug, size/S

#15520 [fix] : fix data race for compileFuzzyFilter.func1
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/S

#15499 when scan blocks less than 200, should force scan on one cn
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#15523 force scan on one CN for right/right semi/right anti join if don't go shuffle
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: kind/bug, size/S
