Repository matrixorigin/matrixone, pull requests merged in 2024-11, with the labels that each got.

#19668 skip invalid global checkpoint request
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
Labels: size/M, kind/enhancement

#19734 set sink mysql timeout to 10min
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/util.go
Labels: size/S, kind/enhancement

#19736 Fix missing workspace data in restore process
  pkg/sql/compile/sql_executor.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
Labels: kind/bug, size/M

#19692 uses CI release/2.0-dev for 2.0-dev
  .github/workflows/entrypoint.yaml
  .github/workflows/image-build.yml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
Labels: kind/test-ci, Review effort [1-5]: 2

#19738 Fix missing workspace data in restore process - main
  pkg/sql/compile/sql_executor.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
Labels: kind/bug, size/M

#19681 refactor: improve checkTableDefChange
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/types.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/visit_plan_rule.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/txn_table.go
  proto/plan.proto
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/M, kind/refactor

#19724 recover panic
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
Labels: size/S, kind/enhancement

#19741 Fix TestGlobalCheckpoint5 timeout
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci

#19745 fix mpool leak
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/tables/utils.go
Labels: kind/bug, size/XS

#19677 sync to 2.0: reduce the comparison during the reader primary key iterator scan
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/logtailreplay/types.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
Labels: size/M

#19737 add some debug info for reader and paritition state
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/reader_test.go
Labels: size/M, kind/refactor

#19686 optimize folding in EvalExpression(2.0-dev)
  pkg/container/vector/vector.go
  pkg/sql/colexec/debugTools.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpressionOpt.go
  pkg/sql/colexec/evalExpressionReset.go
  pkg/sql/plan/function/function.go
Labels: size/M

#19748 abort all active txn on invalid service and make new txn can work
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/pb/lock/lock.go
  pkg/pb/lock/lock.pb.go
  pkg/pb/txn/txn.pb.go
  pkg/tests/issues/issue_test.go
  pkg/tnservice/store.go
  pkg/tnservice/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  proto/lock.proto
  proto/txn.proto
Labels: kind/bug, size/L

#19704 [enhancement] proxy: reduce the interval time of refresh cn nodes
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/proxy/config.go
Labels: size/S, kind/enhancement

#19708 Operator analyze counter set reuse2.0-dev
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/vm/process/operator_analyzer.go
Labels: size/S, kind/enhancement

#19749 abort all active txn on invalid service and make new txn can work to 2.0
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/lockservice/txn_test.go
  pkg/lockservice/types.go
  pkg/pb/lock/lock.go
  pkg/pb/lock/lock.pb.go
  pkg/pb/txn/txn.pb.go
  pkg/tests/issues/issue_test.go
  pkg/tnservice/store.go
  pkg/tnservice/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  proto/lock.proto
  proto/txn.proto
Labels: kind/bug, size/L, kind/test-ci

#19742 Fix test global checkpoint5 2.0
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
Labels: size/M, kind/test-ci

#19721 support user unlock
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: kind/feature, size/XXL

#19719 cp #19686 to main
  pkg/container/vector/vector.go
  pkg/sql/colexec/debugTools.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpressionOpt.go
  pkg/sql/colexec/evalExpressionReset.go
  pkg/sql/plan/function/function.go
Labels: size/M

#19747 reduce available mem after revice
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
Labels: kind/bug, size/S

#19763 fix TestChangesHandle3
  pkg/vm/engine/tae/containers/mock.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/XS

#19730 fileservice: use global http transport and net dialer
  pkg/fileservice/http_client.go
  pkg/fileservice/http_client_test.go
Labels: size/M, kind/enhancement

#19714 fifocache: avoid allocation in key hashing
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
Labels: size/S, kind/enhancement

#19773 fix lockservice dead lock with txn
  pkg/lockservice/rpc.go
Labels: kind/bug, size/S

#19770 some code clean for expand ranges
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/S, kind/refactor

#19720 [opt] : use context cancel with cause when needed
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterunServer_test.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/task_runner_test.go
  pkg/vm/pipeline/types.go
  pkg/vm/process/process2.go
  pkg/vm/process/process2_test.go
  pkg/vm/process/types.go
Labels: size/M, kind/enhancement

#19761 fix password complexity authentication policies
  pkg/frontend/password_management.go
  pkg/frontend/variables.go
  test/distributed/cases/zz_accesscontrol/password_management/password_management_alter_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_create_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.sql
Labels: kind/bug, size/S

#19772 fix lockservice with txn dead lock
  pkg/lockservice/rpc.go
Labels: kind/bug, size/S

#19776 reuse txnop
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/test/Makefile
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
Labels: kind/feature, size/M, kind/enhancement

#19775 fix dedup
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/functions.go
Labels: kind/bug, size/M

#19735 support password management policy
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_1/clusetr_upgrade_list.go
  pkg/bootstrap/versions/v2_0_1/log.go
  pkg/bootstrap/versions/v2_0_1/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_1/upgrade.go
  pkg/bootstrap/versions/v2_0_1/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  pkg/frontend/pitr_test.go
  pkg/frontend/predefined.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/system_initialize.go
  pkg/frontend/variables.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
  test/distributed/cases/zz_accesscontrol/password_management/password_expired.result
  test/distributed/cases/zz_accesscontrol/password_management/password_expired.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_alter_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_alter_user.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_create_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_create_user.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.result
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.result
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.sql
Labels: kind/feature, size/XXL

#19751 handle index table missing table_kind identifier
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/ddl/table_kind.sql
Labels: kind/bug, size/L

#19780 [bug] return retry error if snapshot ts is smaller than ts of catalog
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_test.go
Labels: kind/bug, size/S

#19774 fix dedup
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/functions.go
Labels: kind/bug, size/M

#19788 delay expand ranges for system table
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/M, kind/refactor

#19760 Fix bindexpr panic and remove some bvt tags
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/func_cast.go
  test/distributed/cases/dtype/bool.test
  test/distributed/cases/dtype/char.result
  test/distributed/cases/dtype/char.test
  test/distributed/cases/dtype/date.result
  test/distributed/cases/dtype/date.test
  test/distributed/cases/dtype/datetime.result
  test/distributed/cases/dtype/datetime.test
  test/distributed/cases/dtype/timestamp.result
  test/distributed/cases/dtype/timestamp.test
  test/distributed/cases/dtype/varchar.result
  test/distributed/cases/dtype/varchar.test
  test/distributed/cases/function/func_cast.result
  test/distributed/cases/function/func_cast.test
Labels: size/XL

#19790 Backup adapts to main
  pkg/backup/backup_test.go
  pkg/backup/tae.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: kind/bug, size/M

#19785 Password management policy to 2.0-dev
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_1/clusetr_upgrade_list.go
  pkg/bootstrap/versions/v2_0_1/log.go
  pkg/bootstrap/versions/v2_0_1/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_1/upgrade.go
  pkg/bootstrap/versions/v2_0_1/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  pkg/frontend/pitr_test.go
  pkg/frontend/predefined.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/system_initialize.go
  pkg/frontend/variables.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
  test/distributed/cases/zz_accesscontrol/password_management/password_expired.result
  test/distributed/cases/zz_accesscontrol/password_management/password_expired.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_alter_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_alter_user.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_create_user.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_create_user.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.result
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.result
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.sql
Labels: kind/feature, size/XXL

#19794 Fix TestAppendAndGC
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#19778 fix group concat without data
  pkg/sql/colexec/window/window.go
  test/distributed/cases/function/function_group_concat.result
  test/distributed/cases/function/function_group_concat.sql
Labels: kind/bug, size/S

#19777 fix group concat without data
  pkg/sql/colexec/window/window.go
  test/distributed/cases/function/function_group_concat.result
  test/distributed/cases/function/function_group_concat.sql
Labels: size/S

#19791 set sink mysql timeout to 10min
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/util.go
Labels: size/S, kind/enhancement

#19779 [bug] return retry error if snapshot ts is smaller than ts of catalog
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_test.go
Labels: kind/bug, size/S

#19795 Fix TestAppendAndGC for 2.0
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#19796 handle index table missing table_kind identifier
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/ddl/table_kind.sql
Labels: kind/bug, size/L

#19797 Improve cdc send sql performance
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc.go
Labels: size/L, kind/enhancement

#19809 fix: fetch result from correct resultset 2.0-dev
  pkg/util/metric/mometric/cron_task.go
Labels: kind/bug, size/XS

#19817 fix txn status invalid to 2.0
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: kind/bug, size/S

#19836 fix ut
  pkg/cdc/sinker_test.go
Labels: kind/bug, size/S

#19830 check user after open check switch
  pkg/bootstrap/versions/v2_0_1/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
Labels: kind/bug, size/M

#19831 fix transfer deletes
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/S

#19839 [bug] logtail client: change the channel to buffered one
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: kind/bug, size/S

#19810 fix: fetch result from correct resultset
  pkg/util/metric/mometric/cron_task.go
Labels: kind/bug, size/XS

#19816 fix txn status invalid
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: kind/bug, size/S

#19701 refactor: reduce memory alloc in makeBatchRows
  pkg/sql/colexec/external/external.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/integer_numbers_4.csv
Labels: size/M, kind/refactor

#19824 Fix TestAppendAndGC2
  pkg/backup/backup_test.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#19793 refactor: reduce memory alloc in makeBatchRows
  pkg/sql/colexec/external/external.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/integer_numbers_4.csv
Labels: size/M, kind/refactor

#19746 refactor: remove openSysTable
  pkg/catalog/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/engine_util/datasource.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#19798 Refactor merge memory control
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
Labels: size/M, kind/refactor

#19842 [pick 19841] fix #19802 and do code clean for remote run.
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/hashbuild/build_test.go
  pkg/sql/colexec/shufflebuild/build_test.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/types.go
  pkg/vm/process/process_spoolr.go
  pkg/vm/types.go
Labels: kind/bug, size/M

#19812 Add set time_zone in BVT func_cast.test
  test/distributed/cases/function/func_cast.result
  test/distributed/cases/function/func_cast.test
Labels: size/XS

#19829 objectio: make metadata cache capacity dynamic adjustable
  pkg/cnservice/server_query.go
  pkg/cnservice/server_query_test.go
  pkg/objectio/cache.go
  pkg/pb/query/query.pb.go
  proto/query.proto
Labels: size/S, kind/enhancement

#19866 CI: reduce disk cache for 2.0-dev
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-compose/config/tn.toml
  optools/images/Dockerfile
Labels: size/S, kind/test-ci

#19850 Fix file not found for GC
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S

#19827 fix transfer deletes
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/S

#19821 refactor: convert byte to string using unsafe, reduce memory alloc
  pkg/sql/util/csvparser/csv_parser.go
Labels: kind/refactor, size/XS

#19818 fix nil panic
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#19849 use customized driver
  go.mod
  go.sum
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/cdc/util.go
Labels: size/M, kind/enhancement

#19837 check user after open check switch to main
  pkg/bootstrap/versions/v2_0_1/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
Labels: kind/bug, size/M

#19843 [Cherry-pick] Improve cdc send sql performance
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc.go
Labels: size/L, kind/enhancement

#19855 allow now function pushdown to block filters
  pkg/sql/plan/function/list_builtIn.go
Labels: size/XS, kind/enhancement

#19825 Fix TestAppendAndGC2
  pkg/backup/backup_test.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#19819 fix nil panic
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/XS

#19804 udpate txnop resuse
  pkg/frontend/mysql_buffer.go
  pkg/frontend/txn.go
Labels: kind/bug, size/S, kind/enhancement

#19815 delay expand ranges for agg optimization
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
Labels: size/M, kind/refactor

#19854 allow now function pushdown to block filters
  pkg/sql/plan/function/list_builtIn.go
Labels: size/XS, kind/enhancement

#19833 add debug tool for remote run
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterunClient_test.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/util/debug/goroutine/util.go
  pkg/util/debug/goroutine/util_test.go
  proto/pipeline.proto
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: size/M, kind/enhancement

#19841 fix a bug cause remote run cannot stop immediately.
  pkg/sql/colexec/connector/types.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/hashbuild/build_test.go
  pkg/sql/colexec/shufflebuild/build_test.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/types.go
  pkg/vm/process/process_spoolr.go
  pkg/vm/types.go
Labels: kind/bug, size/M

#19853 fix Incorrect time unit for password lock check(#2.0-dev)
  pkg/frontend/session.go
Labels: kind/bug, size/XS

#19868 fix the `batchApplyTombstone` got unsorted rowOffsets.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S

#19805 fifocache: add context params to methods
  cmd/mo-service/debug_test.go
  pkg/backup/backup_test.go
  pkg/cnservice/server_query.go
  pkg/datasync/consumer_test.go
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/caching_file_service.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services.go
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/fscache/data_cache.go
  pkg/fileservice/fuzz_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/qcloud_sdk.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/writer_test.go
  pkg/perfcounter/counter_set.go
  pkg/queryservice/query_service_test.go
  pkg/sql/colexec/multi_update/util_for_test.go
  pkg/testutil/util_new.go
  pkg/txn/trace/service_load_test.go
  pkg/util/export/etl/tae_test.go
  pkg/vm/engine/tae/db/merge/mod_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/rpc/tool_test.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail_test.go
Labels: size/L, kind/enhancement

#19871 FullText Index: Phrase search result do the exact match with the search string that keep the same words order as search string
  pkg/fulltext/fulltext.go
  pkg/fulltext/fulltext_test.go
  pkg/fulltext/types.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/bug, size/M

#19845 [fix] : Instead of sending the value scan's batch all at once, split it up to reuse memory.
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertsecondaryindex/types.go
  pkg/sql/colexec/value_scan/types.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/colexec/value_scan/value_scan_test.go
Labels: kind/bug, size/M

#19828 objectio: make metadata cache capacity dynamic adjustable
  pkg/cnservice/server_query.go
  pkg/cnservice/server_query_test.go
  pkg/objectio/cache.go
  pkg/pb/query/query.pb.go
  proto/query.proto
Labels: size/S, kind/enhancement

#19874 make ut for multi_update faster (#19861)
  pkg/sql/colexec/multi_update/delete_test.go
  pkg/sql/colexec/multi_update/insert_test.go
  pkg/sql/colexec/multi_update/update_test.go
  pkg/sql/colexec/multi_update/util_for_test.go
Labels: size/S, kind/test-ci

#19879 [bug] proxy: fix UT
  pkg/proxy/tunnel_test.go
Labels: kind/bug, size/S

#19880 [bug] proxy: fix UT
  pkg/proxy/tunnel_test.go
Labels: kind/bug, size/S

#19877 metric: redefine duration buckets
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
Labels: size/S, kind/enhancement

#19878 metric: redefine duration buckets
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
Labels: size/S, kind/enhancement

#19852 fix Incorrect time unit for password lock check
  pkg/frontend/session.go
Labels: kind/bug, size/XS

#19870 to 2.0: fix the batchApplyTombstone got unsorted rowOffsets
  pkg/vm/engine/disttae/local_disttae_datasource.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S

#19846 [cherry-pick-19845] : Instead of sending the value scan's batch all at once, split it up to reuse memory
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertsecondaryindex/types.go
  pkg/sql/colexec/value_scan/types.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/colexec/value_scan/value_scan_test.go
Labels: kind/bug, size/M

#19857 reduce the upper limit of hard disk cache
  etc/launch-tae-compose/config/cn-0.toml
  etc/launch-tae-compose/config/cn-1.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-tae-compose/config/tn.toml
  optools/images/Dockerfile
Labels: size/S, kind/test-ci

#19882 support ip whitelist feat
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  test/distributed/cases/zz_accesscontrol/connection_management/ip_whitelist.result
  test/distributed/cases/zz_accesscontrol/connection_management/ip_whitelist.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.sql
Labels: kind/feature, size/M

#19899 fix nested recursive cte
  pkg/sql/colexec/mergecte/mergecte.go
  pkg/sql/colexec/mergecte/types.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/tools.go
  test/distributed/cases/recursive_cte/recursive_cte.result
  test/distributed/cases/recursive_cte/recursive_cte.sql
Labels: size/M

#19896 Fix loopjoin panic
  pkg/sql/colexec/loopjoin/join.go
  test/distributed/cases/join/join.result
  test/distributed/cases/join/join.test
Labels: size/XS

#19881 optimize performance for filling hashkeys on string vectors
  pkg/common/hashmap/strhashmap.go
  test/distributed/cases/optimizer/group.result
  test/distributed/cases/optimizer/group.test
Labels: size/M, kind/enhancement

#19905 [Bug]: use load_file() function to load stage data, mo report 'ERROR 20101 (HY000): internal error: Invalid alloc size 7775731712
  pkg/common/mpool/mpool.go
  pkg/common/mpool/mpool_test.go
Labels: kind/bug, size/S

#19898 fix nested recursive cte
  pkg/sql/colexec/mergecte/mergecte.go
  pkg/sql/colexec/mergecte/types.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/tools.go
  test/distributed/cases/recursive_cte/recursive_cte.result
  test/distributed/cases/recursive_cte/recursive_cte.sql
Labels: size/M

#19906 [opt] disable dedup for restore stmt
  pkg/sql/plan/bind_insert.go
Labels: kind/bug, size/XS

#19891 Fix file not found for GC
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/logtail/storage_usage.go
Labels: kind/bug, size/S, kind/enhancement

#19886 malloc: do not unmap to avoid VMA fragmentation
  pkg/common/malloc/fixed_size_mmap_allocator.go
  pkg/common/malloc/fixed_size_mmap_allocator_test.go
  pkg/common/malloc/profile_allocator.go
Labels: size/S, kind/enhancement

#19838 [bug] logtail client: change the channel to buffered one
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: kind/bug, size/S

#19897 some code clean for delay expand ranges
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterun.go
  pkg/vm/engine/types.go
  proto/pipeline.proto
Labels: size/S, kind/refactor

#19766 fileservice, fifocache: add context params
  cmd/mo-service/debug_test.go
  pkg/backup/backup_test.go
  pkg/cnservice/server_query.go
  pkg/datasync/consumer_test.go
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/caching_file_service.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_bench_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/file_services.go
  pkg/fileservice/file_with_checksum.go
  pkg/fileservice/fscache/data_cache.go
  pkg/fileservice/fuzz_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/qcloud_sdk.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
  pkg/fileservice/sub_path.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/writer_test.go
  pkg/perfcounter/counter_set.go
  pkg/queryservice/query_service_test.go
  pkg/sql/colexec/multi_update/util_for_test.go
  pkg/testutil/util_new.go
  pkg/txn/trace/service_load_test.go
  pkg/util/export/etl/tae_test.go
  pkg/vm/engine/tae/db/merge/mod_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/rpc/tool_test.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail_test.go
Labels: size/L, kind/enhancement

#19902 bug fix fulltext phrase search
  pkg/common/datalink/docx/docx_test.go
  pkg/common/datalink/docx/testfiles/wiki.docx
  pkg/common/datalink/docx/types.go
  pkg/common/fulltext/fulltext.go
  pkg/common/fulltext/fulltext_test.go
  pkg/common/fulltext/types.go
Labels: kind/bug, size/M

#19892 add debug tool for remote run (#19833)
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterunClient_test.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/util/debug/goroutine/util.go
  pkg/util/debug/goroutine/util_test.go
  proto/pipeline.proto
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: size/M, kind/enhancement

#19865 feat: keep S3IOInput as 6-prec float value.
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
Labels: size/S, kind/enhancement

#19864 feat: keep S3IOInput as 6-prec float value.
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/statistic/stats_array_test.go
Labels: size/S, kind/enhancement

#19823 refactor: remove openSysTable 2.0
  pkg/catalog/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/engine_util/datasource.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#19887 Add metric for GC
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/logtail/storage_usage.go
Labels: size/S, kind/enhancement

#19885 malloc: do not unmap to avoid VMA fragmentation
  pkg/common/malloc/fixed_size_mmap_allocator.go
  pkg/common/malloc/fixed_size_mmap_allocator_test.go
  pkg/common/malloc/profile_allocator.go
Labels: size/S, kind/enhancement

#19918 cherry-pick optimize performance for filling hashkeys on string vectors (#19881)
  pkg/common/hashmap/strhashmap.go
  test/distributed/cases/optimizer/group.result
  test/distributed/cases/optimizer/group.test
Labels: size/M, kind/enhancement

#19908 do some lock if lock no rows after lock_op
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/pessimistic_transaction/isolation.result
  test/distributed/cases/pessimistic_transaction/isolation.sql
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
Labels: kind/bug, size/M

#19927 fix bug: sysbench delete pk will flush s3
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#19919 support ip whitelist feat (#2.0-dev)
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  test/distributed/cases/zz_accesscontrol/connection_management/ip_whitelist.result
  test/distributed/cases/zz_accesscontrol/connection_management/ip_whitelist.sql
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.result
  test/distributed/cases/zz_accesscontrol/password_management/password_management_system_variable.sql
Labels: kind/feature, size/M

#19938 cherry pick 'support pushdown cast expression to block filters for date time type'
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/pushdown.result
  test/distributed/cases/optimizer/pushdown.test
Labels: size/S, kind/enhancement

#19930 optimize workspace size
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement

#19934 ignore bvt case
  test/distributed/cases/log/show_table.sql
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: size/XS, kind/test-ci

#19935 ignore bvt case 2.0-dev
  test/distributed/cases/log/show_table.sql
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: size/XS, kind/test-ci

#19936 fix bug: sysbench delete pk will flush s3
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#19932 update log
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S, kind/enhancement

#19888 simplify merge code
  pkg/common/malloc/default.go
  pkg/common/malloc/default_test.go
  pkg/common/malloc/fixed_size_make_allocator.go
  pkg/common/malloc/fixed_size_make_allocator_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/M, kind/refactor

#19947 tag EXPLAIN bvt case
  test/distributed/cases/optimizer/runtimefilter.test
Labels: size/XS, kind/test-ci

#19954 [bug] clusterservice: ignore tn store which is expired
  pkg/clusterservice/cluster.go
  pkg/clusterservice/cluster_test.go
Labels: kind/bug, size/S

#19931 update log
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S, kind/enhancement

#19950 support password_history and password_reuse_interval take effect separately(#2.0-dev)
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.result
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.sql
Labels: kind/feature, size/M

#19944 [plan] postpone composition of secondary index columns
  pkg/sql/plan/bind_insert.go
Labels: size/S, kind/enhancement

#19916 enable transfer in metric and cu table on 2.0-dev
  pkg/util/metric/mometric/metric.go
  test/distributed/cases/log/show_table.result
  test/distributed/cases/mo_cloud/mo_cloud.result
Labels: kind/bug, size/XS

#19949 support password_history and password_reuse_interval take effect separately
  pkg/frontend/password_management.go
  pkg/frontend/password_management_test.go
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.result
  test/distributed/cases/zz_accesscontrol/password_management/password_reuse.sql
Labels: kind/feature, size/M

#19929 optimize workspace size
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement

#19958 update usage
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
Labels: size/M, kind/enhancement

#19926 cherry-pick: support observe cache usage and hit status (#19914)
  go.mod
  pkg/cnservice/server_query.go
  pkg/cnservice/server_query_test.go
  pkg/defines/const.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/mem_cache.go
  pkg/objectio/cache.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/fileservice.go
  pkg/util/metric/v2/metrics.go
  proto/query.proto
Labels: kind/feature, size/M

#19959 set estimateMemUsagePerRow to 30
  pkg/vm/engine/tae/db/merge/utils.go
Labels: kind/bug, size/XS

#19946 add system variable profiling_history_size(#2.0-dev)
  pkg/frontend/variables.go
  test/distributed/cases/system_variable/system_variables.result
  test/distributed/cases/system_variable/system_variables.sql
Labels: kind/feature, size/S

#19917 enable transfer in metric and cu table
  pkg/util/metric/mometric/metric.go
  test/distributed/cases/log/show_table.result
  test/distributed/cases/mo_cloud/mo_cloud.result
Labels: kind/bug, size/XS

#19968 cherry-pick: couple of updates
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/test/Makefile
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
Labels: kind/bug, size/L, kind/enhancement

#19945 add system variable profiling_history_size
  pkg/frontend/variables.go
  test/distributed/cases/system_variable/system_variables.result
  test/distributed/cases/system_variable/system_variables.sql
Labels: kind/feature, size/S

#19901 update logtail entry type
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  proto/api.proto
Labels: size/M, kind/api-change

#19895 update logtail entry type
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  proto/api.proto
Labels: size/M, kind/api-change

#19956 [bug] fix ut, which raises "address already in use" error
  pkg/logservice/store_hakeeper_check_test.go
Labels: kind/bug, size/S

#19933 remove usages of unsafe.Slice
  pkg/common/bloomfilter/util.go
  pkg/common/buffer/buffer.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/malloc/profiler.go
  pkg/common/reuse/mpool_based.go
  pkg/common/util/unsafe.go
  pkg/common/util/unsafe_test.go
  pkg/container/nulls/nulls.go
  pkg/container/types/encoding.go
  pkg/container/vector/vector.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/shard.go
  pkg/frontend/password_management.go
  pkg/frontend/util.go
  pkg/sql/plan/function/func_builtin.go
  pkg/testutil/util_new.go
Labels: size/M, kind/enhancement

#19957 [bug] fix ut, which raises "address already in use" error
  pkg/logservice/store_hakeeper_check_test.go
Labels: kind/bug, size/S

#19971 fix panic in fillStrhashmap
  pkg/common/hashmap/strhashmap.go
Labels: kind/bug, size/S

#19978 fix create view with hint(#2.0-dev)
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_util.go
  test/distributed/cases/statement_query_type/statement_query_type_2.result
  test/distributed/cases/statement_query_type/statement_query_type_3.result
  test/distributed/cases/view/view.result
  test/distributed/cases/view/view.test
Labels: kind/bug, size/S

#19972 fix bug: panic on create fulltext idx
  pkg/sql/colexec/multi_update/insert_test.go
  pkg/sql/colexec/multi_update/s3writer_util.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/bug, size/S

#19975 fix bug: panic on create fulltext idx
  pkg/sql/colexec/multi_update/insert_test.go
  pkg/sql/colexec/multi_update/s3writer_util.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/bug, size/S

#19942 skip inKind pk tombstone filter if exists a huge number of in values.
  pkg/frontend/test/engine_mock.go
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/disttae/txn_table_sharding_test.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
  pkg/vm/engine/engine_util/pk_filter_mem_test.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#19986 Fix TestBackupData2 for 2.0
  pkg/backup/backup_test.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/logtail/storage_usage.go
Labels: size/S, kind/test-ci

#19987 optimize index only scan in some cases
  pkg/sql/plan/apply_indices.go
  test/distributed/cases/optimizer/explain_index.result
Labels: size/M, kind/enhancement
