Repository matrixorigin/matrixone, pull requests merged in 2024-02, with the labels that each got.

#14494 fix visitObjectEntry
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/XS

#14488 Check the schema before stat the file in load
  pkg/sql/plan/build_load.go
  test/distributed/cases/load_data/load_data.result
Labels: kind/bug, size/S

#14495 [fix] the process for enclosed by '' in mo_dump
  pkg/frontend/export.go
Labels: kind/bug, size/XS

#14491 append code for alter
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS

#14497 Add more precise workspace size control
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/S

#14498 don't assume input vector to be sorted in prefix_*
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/operator_between.go
Labels: kind/bug, size/M

#14482 handle metadata update operations in explicit transactions
  pkg/container/vector/vector.go
  pkg/frontend/show_subscriptions_test.go
  pkg/sql/compile/alter.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/pessimistic_transaction/create_table.result
  test/distributed/cases/pessimistic_transaction/create_table.sql
Labels: kind/bug, size/M

#14499 cherry-pick index related commits to 1.1-dev
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/operator_between.go
Labels: kind/feature, size/M

#14464 fileservice: return proper error in AliyunSDK.Stat
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/XS

#14502 backup: optimize CopyFile
  pkg/backup/tae.go
Labels: size/S, kind/enhancement

#13873 bump kafka client version
  go.mod
Labels: kind/bug, size/XS, kind/enhancement

#14493 remove create/delete blk in table tail
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
Labels: size/S

#14511 fix a panic caused by prefix_in on memtable
  pkg/sql/plan/function/func_prefix.go
Labels: kind/bug, size/XS

#14487 [Feature]: Master Secondary Index
  pkg/catalog/secondary_index_utils.go
  pkg/catalog/types.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
Labels: kind/feature, size/XXL

#14522 Revert "clean up func getPkValueExpr"
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_insert.go
Labels: size/M

#14526 fix bug for cn panic
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XS

#14461 [Enhancement]: S3 read ordering
  pkg/frontend/test/engine_mock.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/table_scan/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#14528 optimize ForeachBlkInObjStatsList
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/S, kind/enhancement

#14504 fileservice: fix error when creating directory in parallel
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/XS

#14537 support parallel config for backup
  pkg/backup/backup.go
  pkg/backup/backup_test.go
  pkg/backup/types.go
  pkg/backup/utils.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/backup.go
Labels: size/XXL, kind/enhancement

#14538 fix a pre-insert packer bug.
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertsecondaryindex/types.go
  pkg/sql/colexec/preinsertunique/preinsertunique.go
  pkg/sql/colexec/preinsertunique/types.go
  pkg/sql/util/index_util.go
  pkg/sql/util/index_util_test.go
Labels: kind/bug, size/M

#14410 Add GC's config for 1.0
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/tae/db/gc/delete.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/types.go
Labels: size/S, kind/enhancement

#14540 Backup adapt object (#14376)
  pkg/backup/tae.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/feature, size/L, kind/enhancement

#14539 support parallel config for backup (#1.1-dev)
  pkg/backup/backup.go
  pkg/backup/backup_test.go
  pkg/backup/types.go
  pkg/backup/utils.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/backup.go
Labels: size/XXL, kind/enhancement

#14527 fix bug
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XS

#14542 Fix the bug of backup checkpoint metadata (#14448)
  pkg/backup/tae.go
Labels: kind/bug, size/S

#14519 cherry-pick index related commits to 1.1-dev
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/operator_between.go
Labels: kind/bug, size/M

#14543 Add backup parallel
  pkg/backup/backup.go
  pkg/backup/backup_test.go
  pkg/backup/tae.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/vm/engine/tae/logtail/backup.go
Labels: size/M, kind/enhancement

#14547 [opt] allow filters with parameter/variable to use index
  pkg/sql/plan/apply_indices.go
Labels: kind/feature, size/S

#14549 Fix non sys tenant mo_pubs upgrade
  pkg/cnservice/upgrader/upgrader.go
  pkg/frontend/internal_executor.go
Labels: kind/bug, size/M

#14550 fix wrong result caused by prefix_eq
  pkg/sql/plan/function/func_prefix.go
Labels: kind/bug, size/XS

#14531 semi join can skip probe if runtime filter push in_pred to probe side
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/types.go
Labels: size/S, kind/enhancement

#14551 [opt] allow filters with variable to use index
  pkg/sql/plan/apply_indices.go
Labels: kind/feature, size/XS

#14555 fix a bug of semi join when semi join can skip probe
  pkg/sql/colexec/semi/join.go
Labels: size/S

#14554 [Subtask]: Runtime filter MUST be pushed down to ranges
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#14545 Move writeoffset update from Ranges to Relation (#14434)
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#14546 Add more precise workspace size control (#14497)
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/S

#14556 [opt] ensure runtime filter is deduced after applying index
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/bug, size/XS

#14524 [#14523] fix bug for distribute delete
  go.mod
  go.sum
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XXL

#14561 [Tech Request]: don't display too long vector in explain
  pkg/sql/plan/explain/explain_expr.go
Labels: kind/bug, size/XS

#14564 [Bug]: [regression 2.7] internal error: send notify msg to dispatch operator timeout during tpch 1T queries and TPCH cost increaseed more than 25%
  pkg/sql/plan/stats.go
Labels: kind/bug, size/XS

#14439 fix data race (cherry-pick #14429)
  pkg/vm/engine/tae/catalog/object.go
Labels: kind/bug, size/XS

#14580 optimize wait wal latency in the commit critical path
  pkg/vm/engine/tae/db/test/txn_test.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/M, kind/enhancement

#14570 add explain execute
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: kind/feature, size/XXL, kind/enhancement

#14581 increase the default val of the tn rpc worker
  pkg/common/morpc/cfg.go
Labels: size/XS, kind/enhancement

#14483 add cn selector for task scheduler
  pkg/hakeeper/task/cn_ordered_map.go
  pkg/hakeeper/task/cn_selector.go
  pkg/hakeeper/task/cn_selector_test.go
  pkg/hakeeper/task/parse.go
  pkg/hakeeper/task/parse_test.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
Labels: size/M, kind/enhancement

#14360 GC Adapt Object
  pkg/vm/engine/tae/db/gc/entry.go
  pkg/vm/engine/tae/db/gc/table.go
Labels: kind/feature, size/S

#14590 [Tech Request]: missing debug info for some operators
  pkg/sql/compile/debugTools.go
Labels: kind/bug, size/XS

#14591 remove some time consumer during commit flush tail transaction
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
Labels: size/S, kind/enhancement

#14582 sync to 1.1: increase the default val of the tn rpc worker
  pkg/common/morpc/cfg.go
Labels: size/XS, kind/enhancement

#14567 fix scanner(1.1-dev)
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: kind/bug, size/XS

#14510 fileservice: add ObjectStorageArguments.NoBucketValidation
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/get.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs_test.go
Labels: size/M, kind/enhancement

#14596 [Bug]: Incorrect explain in bvt with race enabled to 1.1-dev
  test/distributed/cases/join/leftjoin.result
  test/distributed/cases/join/leftjoin.test
Labels: kind/bug, size/XS

#14594 support isnull and isnotnull in block filter
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement

#14595 support isnull and isnotnull in block filter to 1.1-dev
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#13974 [feature] ctl: add new cmd for mo_ctl() to unsubscribe table.
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/server_query.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/query_service.go
  pkg/sql/plan/function/ctl/cmd_rpc_version_test.go
  pkg/sql/plan/function/ctl/cmd_unsubscribe_table.go
  pkg/sql/plan/function/ctl/types.go
  pkg/util/status/hakeeper.go
  pkg/util/status/hakeeper_test.go
  pkg/util/status/lock.go
  pkg/util/status/logtail_client.go
  pkg/util/status/logtail_server.go
  pkg/util/status/logtail_server_test.go
  pkg/util/status/server.go
  pkg/util/status/status.go
  pkg/util/status/txn_client.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/types.go
  proto/query.proto
Labels: kind/feature, size/L

#14598 resolve CN write s3 object with wrong sort index
  pkg/sql/colexec/s3util.go
  pkg/sql/plan/build_constraint_util.go
Labels: kind/bug, size/S

#14615 [bug] status: fix concurrent map access
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: kind/bug, size/XS

#14605 [refactor] : Extract the code related to pkfilter
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
Labels: size/XL, kind/refactor

#14571 [#14523] fix distribute delete bug-2
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/vm/engine/disttae/txn.go
Labels: size/S

#14583 Fix variance/abs/sum(decimal64)
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/functionAgg/sum.go
  pkg/sql/plan/function/functionAgg/var_pop.go
  pkg/sql/plan/function/list_builtIn.go
Labels: size/S

#14627 Revert "[#14523] fix distribute delete bug-2 (#14571)"
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/vm/engine/disttae/txn.go
Labels: size/S

#14514 dump profile when found a memory spike
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: size/S, kind/enhancement

#14622 Cleanup some error message
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
Labels: kind/refactor, size/XS

#14602 fix bug: get incorrect result for "in" expr in some case
  pkg/container/vector/vector.go
  pkg/sql/plan/partition_util.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/M

#14568 [Subtask]: Improve Operator Communication in Pipeline
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/table_scan/types.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/sql/compile/types.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/message.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/process/message.go
  pkg/vm/process/process.go
  pkg/vm/process/topValueMsg.go
  pkg/vm/process/types.go
  pkg/vm/types.go
  proto/plan.proto
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
Labels: kind/feature, size/L

#14606 fix writeoffset data race
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14585 add load data case
  test/distributed/cases/load_data/load_data_set_escaped.result
  test/distributed/cases/load_data/load_data_set_escaped.sql
  test/distributed/resources/load_data/load.csv
Labels: kind/bug, size/S

#14584 Fix splitpart
  pkg/sql/plan/function/func_binary.go
  test/distributed/cases/function/func_string_split_part.result
  test/distributed/cases/function/function_split_part.result
Labels: size/M

#14637 Fix writeoffset race
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14629 fix a bug that runtime filter could cause wrong result
  pkg/sql/colexec/evalExpression.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/runtimefilter.result
  test/distributed/cases/optimizer/runtimefilter.test
Labels: kind/bug, size/M

#14640 Fix TestAppendAndGC
  pkg/vm/engine/tae/db/gc/entry.go
Labels: kind/bug, size/S

#14630 an interface for copy-on-write of table def
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/types_mock.go
  pkg/sql/compile/alter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
Labels: size/S, kind/enhancement

#14626 sync to 1.1: an interface for copy-on-write of table def
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/types_mock.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#14636 check nil vector before flushing blk & print w-w detail in pessimistic mode
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/flushdeletes.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/S, kind/enhancement

#14644 logtailreplay: tune btree degree to lower allocations
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: size/XS, kind/enhancement

#14650 optimize in filter card limit for runtime filters
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/runtime_filter.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/M, kind/enhancement

#14632 fix dump enum type error
  pkg/container/types/types.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/mysql_ddl_3.result
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum_2.result
  test/distributed/cases/dtype/enum_2.test
Labels: kind/bug, size/S

#14638 fix scanner for '#'
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: size/XS, kind/enhancement

#14654 [bug] stats: performace is bad as the condition is wrong.
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#14651 [#14523]fix distribute delete bug
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/vm/engine/disttae/txn.go
Labels: size/S

#14658 a tiny trace framework for TN commit routine
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: size/M, kind/enhancement

#14662 fix data race
  pkg/vm/engine/tae/catalog/table.go
Labels: kind/bug, size/XS

#14631 fix bug: get incorrect result for "in" expr in some case (#14602)
  pkg/container/vector/vector.go
  pkg/sql/plan/partition_util.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/M

#14544 Fix bug for delete
  pkg/container/batch/batch.go
  pkg/container/batch/batch_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/restrict/restrict.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/logtail/backup.go
Labels: size/S

#14671 [bug] fix wrong data type in stats info.
  pkg/pb/statsinfo/shuffle.go
  pkg/pb/statsinfo/statsinfo.pb.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/disttae/stats.go
  proto/statsinfo.proto
Labels: kind/bug, size/M

#14599 [Feature] support create table ... as select ...
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/stmt_kind.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/binding.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  proto/plan.proto
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/feature, size/XXL

#14558 chore: update go 1.21 denpency
  go.mod
  go.sum
  pkg/container/types/array_str.go
Labels: size/S, kind/test-ci

#14635 addCreateTableCase
  test/distributed/cases/ddl/table_partition.result
  test/distributed/cases/ddl/table_partition.test
Labels: kind/bug, size/M

#14634 fix bug: get incorrect result for "in" expr in some case (#14602)
  pkg/container/vector/vector.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/M

#14677 optimize shuffle method in some cases
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#14655 fix dump enum type error (#1.1-dev)
  pkg/container/types/types.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/mysql_ddl_3.result
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum_2.result
  test/distributed/cases/dtype/enum_2.test
Labels: kind/bug, size/S

#14683 clean all usage of the `StartTxnWithLatestTS`
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/S, kind/enhancement

#14659 fix scanner for '#' (#1.1-dev)
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: size/XS, kind/enhancement

#14663 sync to 1.1: adding detailed phased trace in the TN commit routine helps us catch the time killer when TN commits.
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/tae/db/test/txn_test.go
  pkg/vm/engine/tae/iface/txnif/consts.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: size/M, kind/enhancement

#14676 [Tech Request]: add new join type Index_Join
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/feature, size/L

#14653 1.1: check nil vector before flushing blk & print w-w detail in pessimistic mode
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushblk.go
  pkg/vm/engine/tae/tables/jobs/flushdeletes.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S

#14688 reduce the overhead from precommitwrite
  pkg/vm/engine/tae/common/map.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_test.go
Labels: size/M, kind/enhancement

#14694 ignore TestHandle_MVCCVisibility
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: kind/bug, size/S

#14684 sync to 1.1: clean all usage of the StartTxnWithLastestTs
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/S, kind/enhancement

#14563 [OPT]: Implementing Vector KNN Rule in Optimizer
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/limit_binder.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
Labels: size/L

#14690 1.1: add flush range lag
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/collector.go
Labels: size/S, kind/enhancement

#14681 fix pkfilter bug and clean some code
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  test/distributed/cases/pessimistic_transaction/insert.result
  test/distributed/cases/pessimistic_transaction/insert.test
Labels: kind/bug, size/M

#14679 [fix] select outfile json type include " which enclosed by ''
  pkg/frontend/export.go
Labels: kind/bug, size/S

#14699 fix a bug of indexjoin that it does not output columns correctly
  pkg/sql/colexec/indexjoin/join.go
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/bug, size/S

#14698 [Tech Request]: time and datetime type can not fold correctly
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#14693 Metric dup sys record
  pkg/frontend/internal_executor.go
  test/distributed/cases/log/column_metric.result
  test/distributed/cases/log/column_metric.sql
Labels: kind/bug, size/S

#14715 Revert index join
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/bug, size/L

#14728 Revert the replace `StartTxnWithLatestTS` with `StartTxn`
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/task.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/S

#14733 revert revert index join
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: size/L, kind/enhancement
