Repository matrixorigin/matrixone, pull requests merged in 2024-06, with the labels that each got.

#16555 sync to 1.2: filter optimization of the loadDeletes
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: size/M, kind/enhancement

#16561 [enhancement] logtail: change the default timeout of sending resp.
  pkg/vm/engine/tae/options/cfg.go
Labels: size/XS, Enhancement, Review effort [1-5]: 1

#16559 [enhancement] proxy: filter CNs that are not in working state.
  pkg/proxy/conn_migration.go
  pkg/proxy/rebalancer.go
  pkg/proxy/tunnel.go
Labels: size/S, Enhancement, Review effort [1-5]: 2, Other

#16554 metric: fix fileservice board
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16545 add issue 16178 cases
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2

#16553 metric: fix fileservice board
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16563 fix bvt test
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16516 fix snapshot name ambiguous
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  test/distributed/cases/snapshot/snapshot.result
  test/distributed/cases/snapshot/snapshot.sql
Labels: kind/bug, size/XXL, Review effort [1-5]: 2, Bug fix

#16464 fix drop publication if exists statement (#1.2-dev)
  pkg/frontend/authenticate.go
  test/distributed/cases/tenant/pub_sub2.result
  test/distributed/cases/tenant/pub_sub2.sql
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16481 add case for restore system table(1.2-dev)
  test/distributed/cases/snapshot/nonsys_restore_system_table_to_nonsys_account.result
  test/distributed/cases/snapshot/nonsys_restore_system_table_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_newnonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_nonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.sql
Labels: kind/feature, size/XXL, Tests, Review effort [1-5]: 5

#16571 clean code
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/connector.go
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/output.go
  pkg/frontend/output_test.go
  pkg/frontend/protocol.go
  pkg/frontend/protocol_test.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/resp_client.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_test.go
  pkg/frontend/self_handle.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/show_subsriptions.go
  pkg/frontend/status_stmt.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
Labels: kind/bug, size/XXL, kind/enhancement, Enhancement, Bug fix, Review effort [1-5]: 5

#16214 filter optimization of the `loadDeletes`.
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4, Bug fix

#16539 GC needs to consume all the mo_snapshot tables
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/gc/delete.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, kind/feature, size/M, Enhancement, Review effort [1-5]: 4, Bug fix

#16575 append log for upgrade and sqlExecutoer
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/v1_2_1/upgrade.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#16558 [enhancement] proxy: filter CNs that are not in working state.
  pkg/proxy/conn_migration.go
  pkg/proxy/rebalancer.go
  pkg/proxy/tunnel.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2, Other

#16517 fix lock service ut
  pkg/lockservice/service_test.go
Labels: size/S, Tests, Review effort [1-5]: 2

#16568 rewrite 'insert ... on duplicate key update' to 'replace into' in some case
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_replace.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#16470 Add cost of GC Check
  pkg/fileservice/file_service.go
  pkg/fileservice/file_services.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/sub_path.go
  pkg/vm/engine/tae/db/gc/check.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#16576 append log for upgrade and sqlExecutoer1.2 dev
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/v1_2_1/upgrade.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#16578 optimize explain info for tp/ap query
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/result_row_stmt.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#16582 Bvt if disable trace in 1.2
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/table/system_table_cases.sql
  test/distributed/cases/table/system_table_cases_2.result
  test/distributed/cases/table/system_table_cases_2.sql
  test/distributed/cases/zz_statement_query_type/result_count.sql
Labels: size/L, kind/test-ci, Tests, Review effort [1-5]: 2

#16581 Bvt disable trace
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/table/system_table_cases.sql
  test/distributed/cases/table/system_table_cases_2.result
  test/distributed/cases/table/system_table_cases_2.sql
  test/distributed/cases/zz_statement_query_type/result_count.sql
Labels: size/L, kind/test-ci, Review effort [1-5]: 3, Tests

#16586 pick #16523 to 1.2-dev
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/group/types.go
Labels: size/M, kind/refactor, Tests, Enhancement, Review effort [1-5]: 4

#16546 remove log print from automaxprocs
  cmd/mo-service/main.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/engine.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#16590 add bvt tag(#1.2-dev)
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
Labels: size/XS, kind/test-ci

#16588 fix a remote run bug, rpc stream should be closed after pipeline cleanup.
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16585 rmTag15901
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/snapshot/snapshotRead.sql
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Bug fix

#16579 cherry-pick fix bvt test
  test/distributed/cases/benchmark/tpch/04_CLEANUP/00_COUNT.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/00_COUNT.sql
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: size/M, kind/test-ci, Tests, Review effort [1-5]: 2

#16361 remove some MustStrCol&MustBytesCol
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/partition/partition.go
  pkg/sort/sort.go
  pkg/sort/sort_test.go
  pkg/sql/colexec/aggexec/aggResult.go
  pkg/sql/colexec/aggexec/approx_count.go
  pkg/sql/colexec/aggexec/cluster_centers.go
  pkg/sql/colexec/aggexec/exec_test.go
  pkg/sql/colexec/mergedelete/mergedelete.go
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/colexec/table_function/system_view_test.go
  pkg/sql/colexec/window/window.go
  pkg/sql/util/composite_primary_key_util_test.go
  pkg/sql/util/index_util.go
  pkg/testutil/util_compare.go
  pkg/vm/engine/disttae/cache/catalog_test.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/memoryengine/shard_hash.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/mergesort/aobj_merger.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
Labels: size/M, kind/enhancement

#16580 fix snapshot name ambiguous (#1.2-dev)
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  test/distributed/cases/snapshot/snapshot.result
  test/distributed/cases/snapshot/snapshot.sql
Labels: kind/bug, size/XXL

#16589 add bvt tag
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
Labels: size/XS, kind/test-ci

#16591 GC needs to consume all the mo_snapshot tables for 1.2
  pkg/fileservice/file_service.go
  pkg/fileservice/file_services.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/sub_path.go
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/gc/check.go
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/gc/delete.go
  pkg/vm/engine/tae/db/gc/table.go
  pkg/vm/engine/tae/db/gc/types.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/L, Enhancement, Review effort [1-5]: 4, Bug fix

#16594 [fix] : fix moc3399
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16600 fix a bug that cause load performance regression issue
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#16602 add case for restore pub_sub
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: kind/feature, size/XL, Tests, Review effort [1-5]: 5

#16592 rmTag15901(1.2-dev)
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/snapshot/snapshotRead.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests

#16366 [BugFix]: Use L2DistanceSq instead of L2Distance during IndexScan
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/vectorize/moarray/external.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Enhancement, Bug fix

#16606 add sharding metrics
  pkg/shardservice/runtime.go
  pkg/shardservice/service.go
  pkg/shardservice/service_read.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_sharding.go
  pkg/util/metric/v2/sharding.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#16608 fix data race
  pkg/common/morpc/server.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Bug fix

#16621 fix convert string to timestamp
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#15879 Refactor reshape
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/mergesort/types_test.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/L, kind/enhancement

#16611 [cherry-pick-16594] : fix moc3399
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16488 support restore publication db (#1.2-dev)
  pkg/frontend/authenticate.go
  pkg/frontend/snapshot.go
  pkg/frontend/types.go
  test/distributed/cases/snapshot/snapshot_restore_publication.result
  test/distributed/cases/snapshot/snapshot_restore_publication.sql
Labels: kind/feature, size/L, Tests, Enhancement, Review effort [1-5]: 4

#16604 bump go to 1.22.3, fix make compose and optimize ut script
  .dockerignore
  .gitignore
  Makefile
  etc/launch-tae-compose/compose.yaml
  go.mod
  optools/bvt_ut/Dockerfile
  optools/compose_bvt/Dockerfile.tester
  optools/compose_bvt/compose_bvt.sh
  optools/compose_bvt/entrypoint.sh
  optools/images/Dockerfile
  optools/utilities.sh
Labels: size/S, kind/test-ci, Review effort [1-5]: 3, Tests, Enhancement

#16632 Fix condition to ignore delete booking if no transfer needed on 1.2-dev
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#16622 remove isMerge from build operator
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/build_test.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/colexec/shufflebuild/build.go
  pkg/sql/colexec/shufflebuild/types.go
Labels: size/S, kind/refactor, Enhancement, Review effort [1-5]: 2

#16623 [Cherry-pick] fix convert string to timestamp
  pkg/frontend/snapshot.go
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16619 fileservice: add newHTTPClient to unify all http client in all S3 SDKs
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/http_client.go
  pkg/fileservice/minio_sdk.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#16637 fileservice: refactor read write duration metrics
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/fileservice.go
  pkg/util/metric/v2/metrics.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 2

#16603 add case for restore pub_sub(1.2-dev)
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: kind/feature, size/XL, Tests, Review effort [1-5]: 4

#16522 [opt] : build fuzzy filter on smaller child and clean up code
  pkg/common/bloomfilter/util.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4

#16641 fix read on tombstone replica
  pkg/shardservice/service.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16648 Optimize logs 1.2 dev
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/v1_2_0/upgrade.go
  pkg/sql/compile/sql_executor.go
Labels: kind/feature, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#16644 bump go to 1.22.3, fix make compose and optimize ut script for 1.2-dev
  .dockerignore
  .gitignore
  Makefile
  etc/launch-tae-compose/compose.yaml
  go.mod
  optools/bvt_ut/Dockerfile
  optools/compose_bvt/Dockerfile.tester
  optools/compose_bvt/compose_bvt.sh
  optools/compose_bvt/entrypoint.sh
  optools/images/Dockerfile
  optools/utilities.sh
Labels: size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#16467 modify the variable filter for k8s dashboard
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
Labels: kind/test-ci, Tests, Enhancement, Review effort [1-5]: 2

#16635 add debug info for panic
  pkg/frontend/back_exec.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/session_test.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/util.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16626 fix restore pub db
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/snapshot_restore_publication.result
  test/distributed/cases/snapshot/snapshot_restore_publication.sql
Labels: kind/bug, size/M

#16647 Optimize logs
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/v1_2_0/upgrade.go
  pkg/sql/compile/sql_executor.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2, Bug fix

#16643 update bloom filter for the future tombstone changes
  pkg/container/types/rowid.go
  pkg/objectio/id.go
  pkg/objectio/reader.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/hybrid_filter.go
  pkg/vm/engine/tae/index/indexwrapper/immutindex.go
  pkg/vm/engine/tae/index/prefix_filter.go
  pkg/vm/engine/tae/index/types.go
Labels: kind/feature, size/L, Tests, Enhancement, Review effort [1-5]: 4

#16669 Support merge policy parameter 1.2 dev
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/function/mo_ctl/mo_ctl_merge.result
  test/distributed/cases/function/mo_ctl/mo_ctl_merge.test
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16605 fix bvt test
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.sql
Labels: kind/bug, size/S

#16677 remove duplicates in object list for flushing
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement, Bug fix

#16675 handle null in convertRowsIntoBatch
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16666 fix stats for prefix_eq function
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#16692 Fix enumtype system variable check
  pkg/frontend/types.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16633 Fix condition to ignore delete booking if no transfer needed
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#16693 [opt] merge filters on composite primary keys in plan (1.2-dev)
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/function/func_get_admin.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/make.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/feature, size/M, Review effort [1-5]: 3, Enhancement, Bug fix

#16676 [Cherry-pick] handle null in convertRowsIntoBatch
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16691 Fix enumtype system variable check
  pkg/frontend/types.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16642 support query replica count of special cn
  pkg/cnservice/server_query.go
  pkg/pb/query/query.pb.go
  pkg/shardservice/service.go
  pkg/shardservice/types.go
  proto/query.proto
Labels: kind/feature, size/S, Enhancement, Review effort [1-5]: 2

#16702 fileservice: add caching dns resolver
  go.mod
  go.sum
  pkg/fileservice/http_client.go
Labels: size/S, kind/enhancement

#16681 Fix-16620
  pkg/sql/compile/compile.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#16668 fix restore pub db (#1.2-dev)
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/snapshot_restore_publication.result
  test/distributed/cases/snapshot/snapshot_restore_publication.sql
Labels: kind/bug, size/M

#16700 rmTag16601_16597
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16687 sync to 1.2: block reader supports between filter
  pkg/container/vector/search.go
  pkg/vm/engine/disttae/util.go
  test/distributed/cases/disttae_filters/reader_filters/block_reader/between_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/between_filter.sql
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.sql
  test/distributed/cases/disttae_filters/reader_filters/partition_reader/partition_state_primary_key_index_filter.result
  test/distributed/cases/disttae_filters/reader_filters/partition_reader/partition_state_primary_key_index_filter.sql
Labels: size/M, kind/enhancement

#16705 optimize limit operator in pipeline for tp query
  pkg/sql/compile/compile.go
Labels: size/XS, kind/enhancement

#16719 Add issue 16613 cases
  test/distributed/cases/save_query_result/save_query_result.result
  test/distributed/cases/save_query_result/save_query_result.sql
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16711 add case for function hex() and unhex()
  test/distributed/cases/function/func_hex_unhex.result
  test/distributed/cases/function/func_hex_unhex.sql
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
Labels: size/L, Review effort [1-5]: 3, Tests

#16717 optimize group operator in pipeline for tp query
  pkg/sql/compile/compile.go
Labels: size/S, kind/enhancement

#16634 add debug info for panic
  pkg/frontend/back_exec.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/session_test.go
  pkg/frontend/show_account_test.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/util.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16684 update bloom filter for the new prefix bf
  pkg/objectio/meta.go
  pkg/objectio/reader.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/index/types.go
Labels: kind/feature, size/M, Tests, Review effort [1-5]: 4, Feature

#16313 memorycache: code clean-ups
  pkg/fileservice/memorycache/cache.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/data_alloc_free.go
  pkg/fileservice/memorycache/data_test.go
  pkg/fileservice/memorycache/rc_bytes.go
  pkg/fileservice/memorycache/rc_bytes_test.go
  pkg/fileservice/memorycache/types.go
Labels: size/M, kind/enhancement

#16718 cherry-pick http client and dns changes to 1.2-dev
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/http_client.go
  pkg/fileservice/minio_sdk.go
Labels: size/M, kind/enhancement

#16706 optimize offset operator in pipeline for tp query
  pkg/sql/compile/compile.go
Labels: size/S, kind/enhancement

#16733 add issue 16139 cases
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16703 rmTag16601_16597(1.2-dev)
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: kind/bug, size/M, Tests, Review effort [1-5]: 4, Bug fix

#16567 handle Restore Duplicate Entry
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/sql/plan/function/func_mo.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M, Enhancement, Review effort [1-5]: 4, Bug fix

#16695 add global system variable and session variable account isolation cases
  test/distributed/cases/database/system_variables_new.result
  test/distributed/cases/database/system_variables_new.sql
Labels: kind/feature, size/L, Tests, Review effort [1-5]: 4

#16735 Handle Cancel Restore Statement Fail
  pkg/frontend/authenticate.go
  pkg/frontend/snapshot.go
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16737 fix a bug that cause ap performance regression on multi cn
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/XS

#16742 optimize order operator in pipeline for tp query
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/order_test.go
  pkg/sql/colexec/mergeorder/types.go
  pkg/sql/compile/compile.go
Labels: size/S, kind/enhancement

#16746 dashboard: refactor runtime dashboard
  pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
Labels: size/M, kind/enhancement

#16736 Handle Cancel Restore Statement Fail
  pkg/frontend/authenticate.go
  pkg/frontend/snapshot.go
  pkg/frontend/util.go
Labels: kind/bug, size/S

#16721 add issue 16613 cases
  test/distributed/cases/save_query_result/save_query_result.result
  test/distributed/cases/save_query_result/save_query_result.sql
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16728 skip stats for create view
  pkg/frontend/util.go
  pkg/sql/plan/alter_partition_util.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/partition_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#16729 skip stats for create view to 1.2-dev
  pkg/frontend/util.go
  pkg/sql/plan/alter_partition_util.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_dcl.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/partition_test.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#16674 block reader supports between filter.
  pkg/container/vector/search.go
  pkg/vm/engine/disttae/util.go
  test/distributed/cases/disttae_filters/reader_filters/block_reader/between_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/between_filter.sql
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.sql
  test/distributed/cases/disttae_filters/reader_filters/partition_reader/partition_state_primary_key_index_filter.result
  test/distributed/cases/disttae_filters/reader_filters/partition_reader/partition_state_primary_key_index_filter.sql
Labels: size/M, kind/enhancement

#16697 change LIMIT,OFFSET's data type from int64 to uint64
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/limit/limit_test.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/offset/offset_test.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/top/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/limit_binder.go
  pkg/sql/plan/make.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/memoryengine/compiler_context.go
  test/distributed/cases/dml/select/limit.result
  test/distributed/cases/dml/select/limit.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16698 change LIMIT,OFFSET's data type from int64 to uint64
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/limit/limit_test.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/offset/offset_test.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/top/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/limit_binder.go
  pkg/sql/plan/make.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/vm/engine/memoryengine/compiler_context.go
  test/distributed/cases/dml/select/limit.result
  test/distributed/cases/dml/select/limit.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#16759 fix shard service panic
  pkg/cnservice/server.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#16757 make add txn error trace async
  pkg/txn/trace/service.go
  pkg/txn/trace/service_txn_event.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Bug fix

#16754 Revert "resubmit pipeline client max connections is too large (#16209)"
  pkg/cnservice/cnclient/client.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: size/XS, Review effort [1-5]: 2, Bug fix

#16758 make add txn error trace async
  pkg/txn/trace/service.go
  pkg/txn/trace/service_txn_event.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Enhancement, Bug fix

#16734 add issue 16139 cases
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#16760 [bug] launch: fix timeout mechanism when TN service startup
  cmd/mo-service/launch.go
  go.mod
  pkg/logservice/hakeeper_client.go
Labels: kind/bug, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#16762 add a code owner for vector
  CODEOWNERS
Labels: kind/refactor, size/XS

#16756 refactor the block reader filter to support more expressions
  pkg/container/vector/search.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.sql
Labels: size/XL, kind/enhancement

#16763 add a code owner for 1.2
  CODEOWNERS
Labels: kind/refactor, size/XS

#16755 sync to 1.2: refactor the block reader filter to support more expressions.
  pkg/container/vector/search.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.result
  test/distributed/cases/disttae_filters/reader_filters/block_reader/block_reader_filter.sql
Labels: size/XL, kind/enhancement

#16761 [bug] launch: fix timeout mechanism when TN service startup
  cmd/mo-service/launch.go
  pkg/logservice/hakeeper_client.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16749 fileservice: fix fd leak in LocalFS.read
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/M

#16689 [1.2-dev] fix: respsect filterFn in pluginRouter
  pkg/proxy/plugin.go
  pkg/proxy/plugin_test.go
Labels: size/S, Tests, Review effort [1-5]: 2, Bug fix

#16243 update readme(1.2.0)
  README.md
  README_CN.md
Labels: kind/documentation

#16723 Remove list checkpoint meta file
  pkg/vm/engine/tae/blockio/types.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/snapshot.go
  pkg/vm/engine/tae/db/gc/check.go
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/gc/table.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4, Bug fix

#16748 fileservice: fix fd leak in LocalFS.read
  pkg/fileservice/local_fs.go
Labels: kind/bug, size/M

#16766 [BugFix]: Remove unnecessary projections in master index
  pkg/sql/plan/apply_indices_master.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#16743 handle Restore Duplicate Entry-1.2-dev
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/util_test.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/sql/plan/function/func_mo.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M

#16712 add SERVER_MORE_RESULTS_EXISTS judgment
  pkg/frontend/result_row_stmt.go
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16770 fileservice: tune metrics dashboard
  pkg/fileservice/s3_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/fileservice.go
Labels: size/S, kind/enhancement

#16744 [opt] retain IN expression in prepared stmt
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan_rule.go
Labels: kind/feature, size/S, Enhancement, Review effort [1-5]: 4

#15984 Refactor view scope execute
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
Labels: size/M, kind/enhancement

#16773 optimize join pipeline for tp query
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
Labels: kind/bug, size/M

#16782 add optimizer hints
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
Labels: size/S, kind/enhancement

#16778 [BugFix]: Add ColName to MasterIndexScan for Filter PushDown
  pkg/frontend/variables.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/plan/apply_indices_master.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/bug, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#16777 Cherry-pick-for-snapshot-read-bug
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, Review effort [1-5]: 3, Bug fix

#16771 dashboard: fix runtime dashboard
  pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
Labels: size/XS, kind/enhancement

#16786 remove 1PC commands
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/test/catalog_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/tables/updates/append.go
  pkg/vm/engine/tae/tables/updates/delete.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/feature, size/M, Tests, Enhancement, Review effort [1-5]: 4

#16783 add cases
  test/distributed/cases/database/system_variables_new.result
  test/distributed/cases/database/system_variables_new.sql
Labels: kind/feature, size/S, Tests, Review effort [1-5]: 2

#16731 do not apply delete when flush
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/mergesort/aobj_merger.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/func_test.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#16800 [opt] retain IN expression in prepared stmt (cp to 1.2-dev)
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan_rule.go
Labels: kind/feature, size/S, Enhancement, Review effort [1-5]: 4

#16774 fix panic
  cmd/mo-service/main.go
  pkg/frontend/resp_client.go
  pkg/frontend/server.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/metric/mometric/metric.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#16797 [opt] retain IN expression in prepared stmt
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/utils.go
Labels: kind/feature, size/XS, Enhancement, Review effort [1-5]: 2

#16805 workaround for get col type panic when construct block reader filter.
  pkg/vm/engine/disttae/util.go
Labels: size/S, kind/enhancement

#16804 sync to 1.2: workaround for get col type panic when construct block reader filter.
  pkg/vm/engine/disttae/util.go
Labels: kind/bug, size/S

#16791 add case for issue3302.
  test/distributed/cases/system/system.result
  test/distributed/cases/system/system.sql
Labels: kind/bug, size/XS, Tests, Review effort [1-5]: 1

#16793 do not rewrite on duplicate key stmt to replace for prepare
  pkg/sql/plan/build_insert.go
Labels: size/XS, kind/enhancement, Enhancement, Review effort [1-5]: 2, Bug fix

#16627 Refactor system variable lower_case_table_names
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/variables.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/cstr.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/parsers/tree/select.go
  pkg/sql/plan/build_show_util_test.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/dml/show/show_create_table.result
  test/distributed/cases/dtype/TimeToInt.result
  test/distributed/cases/dtype/TimeToInt.sql
  test/distributed/cases/dtype/datetime.result
  test/distributed/cases/dtype/datetime.test
  test/distributed/cases/dtype/timestamp.result
  test/distributed/cases/dtype/timestamp.test
  test/distributed/cases/function/func_datetime_unixtime.result
  test/distributed/cases/function/func_datetime_unixtime.test
  test/distributed/cases/function/func_datetime_utc_timestamp.result
  test/distributed/cases/function/func_datetime_utc_timestamp.test
  test/distributed/cases/function/func_if.result
  test/distributed/cases/function/func_if.test
  test/distributed/cases/function/func_math_abs.test
  test/distributed/cases/prepare/prepare_all.result
  test/distributed/cases/prepare/prepare_all.sql
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
  test/distributed/cases/system_variable/system_variables.result
  test/distributed/cases/system_variable/system_variables.sql
  test/distributed/cases/system_variable/system_variables_cross_acc.result
  test/distributed/cases/system_variable/system_variables_cross_acc.sql
  test/distributed/cases/system_variable/system_variables_new.result
  test/distributed/cases/system_variable/system_variables_new.sql
  test/distributed/cases/system_variable/system_variables_same_acc.result
  test/distributed/cases/system_variable/system_variables_same_acc.sql
Labels: kind/feature, size/XXL, kind/refactor, Tests, Enhancement, Review effort [1-5]: 4

#16792 add case for issue3302(1.2-dev).
  test/distributed/cases/system/system.result
  test/distributed/cases/system/system.sql
Labels: kind/bug, size/XS, Tests, Review effort [1-5]: 1

#16796 optimize pipeline for tp delete query
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/scope.go
Labels: size/S, kind/enhancement

#16776 fix panic
  cmd/mo-service/main.go
  pkg/frontend/resp_client.go
  pkg/frontend/server.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/metric/mometric/metric.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#16787 Refactor view scope execute-1.2-dev
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
Labels: size/M, kind/enhancement

#16789 Do not apply delete when aobject merge on 1.2 dev
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/mergesort/aobj_merger.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/func_test.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/mergesort/types_test.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/L, kind/enhancement

#16788 rewrite 'insert ... on duplicate key update' to 'replace into' in some case
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_replace.go
  pkg/sql/plan/deepcopy.go
  proto/plan.proto
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#16781 add SERVER_MORE_RESULTS_EXISTS judgment
  pkg/frontend/result_row_stmt.go
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#16720 change multi clone snapshot op in one op
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/vm/process/types.go
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.sql
  test/distributed/cases/snapshot/snapshot_restore_view.sql
Labels: kind/bug, size/S

#16809 [CherryPick]: Unhex/ Hex Feature Parity with MySQL
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/function/func_hex.result
  test/distributed/cases/function/func_hex_unhex.result
  test/distributed/cases/function/func_hex_unhex.sql
  test/distributed/cases/function/func_unhex.result
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
Labels: kind/bug, size/L, Tests, Review effort [1-5]: 4, Bug fix

#16810 fix a bug that caused by mergeorder operator
  pkg/sql/colexec/mergeorder/order.go
Labels: kind/bug, size/XS

#16696 fix a bug about send notify message to remote node.
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#16768 change some UnsafeGetStringAt to GetStringAt
  pkg/sql/colexec/external/parquet_test.go
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/operator.go
Labels: size/S, kind/refactor, Enhancement, Review effort [1-5]: 2

#16814 rm tag 16710(1.2-dev)
  test/distributed/cases/function/func_hex_unhex.result
  test/distributed/cases/function/func_hex_unhex.sql
Labels: kind/bug, size/S
