Repository matrixorigin/matrixone, pull requests merged in 2024-10, with the labels that each got.

#19118 move vectors from go heap to offheap
  pkg/sql/colexec/aggexec/aggResult.go
Labels: size/XS, kind/enhancement

#19063 add mo-ctl to get table shards info
  pkg/cnservice/server_task.go
  pkg/common/stopper/stopper_test.go
  pkg/embed/cluster.go
  pkg/embed/cluster_test.go
  pkg/embed/config.go
  pkg/embed/operator.go
  pkg/embed/template.go
  pkg/embed/types.go
  pkg/frontend/test/mock_shard/types.go
  pkg/shardservice/runtime.go
  pkg/shardservice/service.go
  pkg/shardservice/storage_mo.go
  pkg/shardservice/types.go
  pkg/sql/plan/function/ctl/cmd_get_table_shards.go
  pkg/sql/plan/function/ctl/types.go
  pkg/tests/shard/partition_based_test.go
  pkg/tests/shard/shard_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/process/process_codec.go
Labels: size/L, kind/enhancement

#19114 cherry-pick: fix dashboard
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
  pkg/util/metric/v2/frontend.go
Labels: kind/bug, size/S

#19121 refactoring build_dml_util.go
  pkg/sql/plan/build_dml_util.go
Labels: kind/feature, size/XL, Enhancement, Review effort [1-5]: 4

#19079 CI: optimize ut analysis utils
  .dockerignore
  .gitignore
  optools/run_ut.sh
Labels: size/S, kind/test-ci, Tests, Enhancement, Review effort [1-5]: 2

#19132 refactor read related code for physical address column
  pkg/catalog/types.go
  pkg/objectio/const.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/transfer_util.go
  pkg/vm/engine/engine_util/container_util.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/engine_util/reader_util.go
  pkg/vm/engine/engine_util/sinker.go
  pkg/vm/engine/engine_util/tombstone_data_test.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/utils_test.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/sinker_test.go
Labels: size/M, kind/enhancement

#19077 merge checkpoint add pitr
  pkg/vm/engine/tae/db/gc/v2/checkpoint.go
  pkg/vm/engine/tae/db/gc/v2/types.go
Labels: kind/bug, size/S

#18969 remove overlap policy
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/common/stats_test.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/merge/config_test.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: kind/bug, size/L

#19047 fix TestReLockInRollingRestartCN
  pkg/lockservice/service_test.go
Labels: size/S

#19135 optimize degree of parallelism for shuffle plan
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
Labels: size/S, kind/enhancement

#19131 reduce memory allocation for unique vector in hash build operator
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  pkg/sql/colexec/hashmap_util/hashmap_util_test.go
  pkg/sql/colexec/shufflebuild/build.go
Labels: size/S, kind/enhancement

#19137 set upper limit of degree of parallelism for shuffle plan
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
Labels: kind/bug, size/XS

#19031 [fix] : avoid the case that increservice may fill duplicated number in multi-CN
  pkg/frontend/test/incrservice_mock.go
  pkg/frontend/test/mock_incr/types.go
  pkg/incrservice/allocator.go
  pkg/incrservice/allocator_test.go
  pkg/incrservice/column_cache.go
  pkg/incrservice/service.go
  pkg/incrservice/store_mem.go
  pkg/incrservice/store_sql.go
  pkg/incrservice/table_cache.go
  pkg/incrservice/types.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/tests/issues/issue_test.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/dml/insert/insert_auto_pk.result
  test/distributed/cases/dml/insert/insert_auto_pk.sql
Labels: kind/bug, size/XL

#19142 fix time(now())
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_datetime_now.result
  test/distributed/cases/function/func_datetime_now.test
Labels: kind/bug, size/S

#19144 reduce memory allocation in AppendBlockInfo
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XS, kind/enhancement

#19032 load parallel control
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope_test.go
  pkg/sql/plan/build_load.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
Labels: kind/bug, size/M

#19152 fix panic: keep item.Free at the end of the loop.
  pkg/util/trace/impl/motrace/buffer_content.go
  pkg/util/trace/impl/motrace/buffer_content_test.go
  pkg/util/trace/impl/motrace/common_test.go
Labels: kind/bug, size/S

#19158 fix pitr valid time not effect
  pkg/frontend/pitr.go
Labels: kind/bug, size/XS

#19149 move vectors in spool from go heap to offheap
  pkg/container/pSpool/copy.go
Labels: size/XS, kind/enhancement

#19151 update collect ckp files
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/XS

#19160 Revert "fix shufflerange miss strvalue (#19083)"
  pkg/pb/statsinfo/shuffle.go
Labels: size/XS

#19081 [feature] add logservice health check method in HAKeeperClient interface
  pkg/datasync/txn_client_test.go
  pkg/frontend/logservice_test.go
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_test.go
  pkg/logservice/store.go
  pkg/logservice/store_test.go
  pkg/pb/logservice/logservice.pb.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/proxy/label_info_test.go
  pkg/sql/colexec/table_function/system_view_test.go
  pkg/tnservice/store_test.go
  pkg/util/status/hakeeper_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  proto/logservice.proto
Labels: kind/feature, size/M

#18433 add reusable bitmap for memory reuse
  pkg/common/bitmap/bitmap.go
  pkg/common/bitmap/bitmap_test.go
  pkg/container/nulls/nulls.go
  pkg/fileservice/pool.go
  pkg/objectio/bitmap.go
  pkg/objectio/bitmap_test.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/engine_util/datasource.go
  pkg/vm/engine/engine_util/tombstone_data.go
  pkg/vm/engine/engine_util/tombstone_data_test.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/types.go
Labels: size/L, kind/enhancement

#19159 [bug] datasync: fix ut
  pkg/datasync/syncer_test.go
Labels: kind/bug, size/S

#19150 fix data inconsistent
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/cdc/util.go
  pkg/cdc/util_test.go
Labels: kind/bug, size/L

#19162 fix zm compare method in processing zm-based merge
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
Labels: kind/bug, size/M

#19107 Fix joinorder
  pkg/sql/plan/associative_law.go
  pkg/sql/plan/opt_misc.go
  test/distributed/cases/optimizer/joinorder.result
  test/distributed/cases/optimizer/joinorder.test
Labels: size/M

#19167 [enhancement] logservice: add retry if ut failed as port is inuse
  pkg/logservice/client_test.go
  pkg/logservice/service.go
  pkg/logservice/service_commands_test.go
  pkg/logservice/service_test.go
  pkg/logservice/test_utils.go
Labels: size/M, kind/enhancement

#19168 fix ut TestCollector with correct time-check logic
  pkg/util/metric/mometric/metric_collector_test.go
Labels: kind/bug, size/XS, kind/test-ci

#19182 add metric && simplify sinker
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/cdc/types_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/frontend.go
  pkg/util/metric/v2/metrics.go
Labels: kind/bug, size/L

#19178 add error condition for pitr restore
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
Labels: kind/bug, size/M

#19169 reuse eligible in semi and anti join
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/types.go
Labels: size/S, kind/enhancement

#19170 move vectors from go heap to offheap
  pkg/container/vector/functionTools.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/product/product.go
Labels: size/S, kind/enhancement

#19189 malloc: optimize profiler to avoid memory leak
  pkg/common/malloc/profiler.go
Labels: size/M, kind/enhancement

#19145 mo-service: track active connections
  cmd/mo-service/debug_connections.go
  cmd/mo-service/debug_connections_test.go
  go.mod
  go.sum
Labels: size/M, kind/enhancement

#19191 [enhancement] logservice: add retry if port is inuse for store instance
  pkg/logservice/service_commands_test.go
  pkg/logservice/store.go
  pkg/logservice/store_hakeeper_check_test.go
  pkg/logservice/store_metadata_test.go
  pkg/logservice/store_test.go
Labels: size/M, kind/enhancement

#19172 reuse object in GenerateFunctionFixedTypeParameter in agg
  pkg/container/vector/functionTool_test.go
  pkg/container/vector/functionTools.go
  pkg/sql/colexec/aggexec/argument.go
Labels: size/M, kind/enhancement

#19199 fix show subs
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
Labels: kind/bug, size/S

#19175 fix: fixed tn hakeeper client config
  pkg/tnservice/factory.go
Labels: kind/bug, size/XS

#19147 remove Ro attribute from batch.
  pkg/cdc/reader_test.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types_test.go
  pkg/cdc/util_test.go
  pkg/container/batch/batch.go
  pkg/container/batch/types.go
  pkg/container/pSpool/copy.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/util.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/filter/filter_test.go
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key_test.go
  pkg/sql/colexec/top/top.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/util/composite_primary_key_util_test.go
  pkg/testutil/testengine/testdata.go
  pkg/txn/storage/memorystorage/catalog_handler.go
  pkg/txn/storage/memorystorage/mem_handler.go
  pkg/txn/storage/memorystorage/storage_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/engine_util/container_util.go
  pkg/vm/engine/memoryengine/operations_test.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/M, kind/refactor

#19165 [#19157]Fix panic
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/M

#19198 prolong mo_retention bvt wait time
  test/distributed/cases/ddl/create_retention_table.result
  test/distributed/cases/ddl/create_retention_table.sql
Labels: kind/bug, size/S

#19200 cherry-pick : fix leak info & load hung
  pkg/cnservice/server.go
  pkg/frontend/authenticate.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/cdc_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session_test.go
  pkg/frontend/status_stmt.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/pb/txn/txn.pb.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/table_scan/table_scan_test.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
  proto/txn.proto
Labels: kind/bug, size/M, kind/enhancement

#19197 fix a bug that cause sysbench performance regression
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#19148 [bug] proxy: release resource in the new server connection after transfer
  pkg/proxy/tunnel.go
Labels: kind/bug, size/S

#19196 optimize show pitr and error info
  pkg/frontend/pitr.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
Labels: size/S, kind/enhancement

#19153 not execute grant or revoke in background session
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/status_stmt.go
Labels: size/M, kind/enhancement

#19155 fileservice: optimize memory allocations in Bytes
  pkg/fileservice/bytes.go
  pkg/fileservice/bytes_test.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/remote_cache_test.go
Labels: size/S, kind/enhancement

#19177 refactor: binary execute
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
Labels: size/S, kind/refactor

#19208 PreAlloc buffer for blockinfo slice when doRanges
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/util_test.go
  pkg/objectio/block_info.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/function/func_mo.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/disttae/txn_table_sharding_test.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/types.go
Labels: size/S, kind/enhancement

#19224 fix ut TestBalanceWithSingleTable
  pkg/shardservice/service_test.go
Labels: size/XS, kind/test-ci

#19201 malloc: optimize profiler to avoid memory leak
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/profiler_test.go
Labels: size/M, kind/enhancement

#19240 fix bug: SortAndCompact get incorrect value (#19056)
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/plan/function/list_operator.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/L

#19234 fix goroutineid 0
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
Labels: kind/bug, size/XS, kind/enhancement

#19235 Fix the problem of filling pitr's tombstone into the object list
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S

#19238 reuse FunctionFixedTypeParameter in filter operator
  pkg/sql/colexec/filter/filter.go
  pkg/sql/colexec/filter/types.go
Labels: size/S, kind/enhancement

#19242 optimize restore account
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
Labels: size/M, kind/enhancement

#19239 Fix backup tae list dup
  pkg/backup/backup_test.go
  pkg/backup/tae.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#19241 adjust hashmap size factor
  pkg/container/hashtable/common.go
Labels: size/XS, kind/enhancement

#19216 [feature] datasync: add gc meta files to WAL
  pkg/datasync/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/gc/v2/checkpoint.go
  pkg/vm/engine/tae/db/gc/v2/table.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/M, kind/enhancement

#19203 refactor: single scope use origin groutine
  pkg/sql/compile/compile.go
Labels: size/S, kind/refactor

#19231 malloc: fix profiler
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/profiler_test.go
Labels: kind/bug, size/S

#19236 fix check create pitr for the same object
  pkg/frontend/authenticate_test.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  test/distributed/cases/pitr/pitr_basic.result
  test/distributed/cases/pitr/pitr_basic.sql
Labels: kind/bug, size/M

#19220 change tableId's type to string
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/cdc/watermark_updater.go
  pkg/cdc/watermark_updater_test.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
  pkg/frontend/predefined.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
Labels: kind/bug, size/M

#19174 service isolation
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/backup.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/connector.go
  pkg/frontend/export.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/logservice.go
  pkg/frontend/logservice_test.go
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_buffer_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/pitr_test.go
  pkg/frontend/protocol_test.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/show_account.go
  pkg/frontend/status_stmt.go
  pkg/frontend/task.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/event_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/rebalancer_test.go
  pkg/proxy/router_test.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/metric/mometric/metric.go
  pkg/util/test/cron_task_test.go
Labels: kind/bug, size/XL, kind/enhancement

#19270 fix proxy new connection failed
  pkg/frontend/server.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/event_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/rebalancer_test.go
  pkg/proxy/router_test.go
  pkg/proxy/server.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
Labels: kind/bug, size/S

#19253 Add debug info for 19202-19171-19018
  pkg/tests/shard/partition_based_test.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
Labels: size/S

#19243 fix forced ickp empty start ts
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: kind/bug, size/S

#19258 fix 19255
  test/distributed/cases/ddl/create_table_with_retention.result
  test/distributed/cases/ddl/create_table_with_retention.sql
Labels: kind/bug, size/S

#19266 fix TestGlobalCheckpoint5
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#19223 Fix network count
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql
  test/distributed/cases/zz_statement_query_type/query_tcp.result
  test/distributed/cases/zz_statement_query_type/query_tcp.sql
Labels: kind/bug, size/M

#19271 fix a bug that cause sysbench random ranges performance regression
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#19276 Add Outer Apply
  pkg/sql/colexec/apply/apply.go
  pkg/sql/colexec/apply/types.go
  pkg/sql/compile/compile.go
  test/distributed/cases/join/apply.result
  test/distributed/cases/join/apply.test
Labels: size/S

#19254 adjust shuffle dop to get suitable hashmap size
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
Labels: size/S, kind/enhancement

#19279 fix bvt joinorder oom
  test/distributed/cases/optimizer/joinorder.result
  test/distributed/cases/optimizer/joinorder.test
Labels: size/XS

#19222 workaround for view no fake pk panic when pull logtail.
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/logtail_consumer.go
  test/distributed/cases/function/builtin.result
  test/distributed/cases/function/builtin.sql
Labels: kind/bug, size/S

#19209 fix ut
  pkg/frontend/mysql_buffer_test.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
Labels: kind/bug, size/M, kind/enhancement

#19260 release reader && sinker
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc.go
Labels: kind/bug, size/M

#19283 [#19277] Fix bug
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S

#19217 some refactor on overlap policy
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/M, kind/refactor

#19252 Change the upgrade versionfrom 1.3.0 to 2.0.0
  pkg/bootstrap/service_test.go
  pkg/bootstrap/service_upgrade.go
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_0/data_key.go
  pkg/bootstrap/versions/v2_0_0/data_key_test.go
  pkg/bootstrap/versions/v2_0_0/log.go
  pkg/bootstrap/versions/v2_0_0/pubsub.go
  pkg/bootstrap/versions/v2_0_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_0/upgrade.go
  pkg/bootstrap/versions/v2_0_0/upgrade_test.go
Labels: kind/feature, size/M

#19262 fix making selectlist in tpch
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/function/function.go
Labels: size/XS

#19273 malloc: make profiler counters monotonic
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/profiler_test.go
Labels: kind/bug, size/M

#19244 fix apply tombstone
  pkg/vm/engine/tae/blockio/read.go
Labels: size/XS

#19292 fix bvt: remove 'group by statement', caused by merged-record statement column
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql
Labels: size/S, kind/test-ci, kind/enhancement

#19291 isolate embed multi cluster by file based cluster id
  pkg/embed/cluster.go
  pkg/embed/cluster_test.go
Labels: size/S, kind/test-ci

#19250 close rpc future with real error
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
  pkg/common/morpc/server_test.go
Labels: size/S, kind/enhancement

#19290 fix cdc task pause not work
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/cdc/watermark_updater.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/M

#19296 remove redundant mo_table_size, rows bvt case
  test/distributed/cases/function/builtin.result
  test/distributed/cases/function/builtin.sql
Labels: kind/bug, size/S

#19246 Optimize Unnest
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/sql/colexec/table_function/unnest.go
Labels: size/S

#18991 fix convertRowsIntoBatch useless make and then copy
  pkg/frontend/util.go
  pkg/frontend/util_test.go
Labels: size/M, kind/enhancement

#19264 move RecordRunningCompile and removeRunningCompile to compile.Run()
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/compileService_test.go
  pkg/sql/compile/remoterunServer.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/vm/process/process2.go
Labels: kind/bug, size/M

#19249 fix ut
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
Labels: kind/bug, size/XXL, kind/enhancement

#19286 add log for the syncing files
  pkg/datasync/consumer.go
  pkg/datasync/consumer_test.go
  pkg/datasync/entry.go
  pkg/datasync/entry_test.go
  pkg/datasync/log_client_test.go
  pkg/datasync/producer.go
  pkg/datasync/syncer.go
  pkg/logservice/client_test.go
  pkg/logservice/rsm.go
  pkg/logservice/rsm_test.go
  pkg/logservice/store_test.go
Labels: size/M, kind/enhancement

#19309 optimize memcache policy for readers
  pkg/pb/shard/shard.pb.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/test/reader_test.go
  proto/shard.proto
Labels: size/S, kind/enhancement

#19281 imp: check_log_count.sh with log info
  optools/check_log_count.sh
Labels: size/S, kind/test-ci, kind/enhancement

#19304 remove "dispatch remote receiver has been closed" error.
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/dispatch/sendfunc.go
Labels: size/S

#19299 fix pitr modified time and add restore privilege for cluster level pitr
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/M

#19263 [fix] : add type check for func generate_series
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/generate_series_test.go
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
Labels: kind/bug, size/S

#19322 fix get replica panic on disabled shardservice
  pkg/shardservice/service.go
  pkg/shardservice/service_test.go
Labels: kind/bug, size/XS

#19315 reduce small objects for new vector
  pkg/container/nulls/nulls.go
  pkg/container/vector/reuse.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/vm/engine/tae/containers/utils.go
Labels: size/M, kind/enhancement

#19308 separate queue for flush and merge
  pkg/sql/compile/ddl.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tasks/types.go
Labels: kind/bug, size/S

#19318 not update last insert id when insert fail
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/function/func_unary.go
  test/distributed/cases/auto_increment/auto_increment_columns.result
  test/distributed/cases/auto_increment/auto_increment_columns.sql
Labels: kind/bug, size/S

#19316 optimize sendlast for right joins
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
Labels: size/S, kind/enhancement

#19333 reduce the memory allocation when batch prefetch block data.
  pkg/vm/engine/disttae/local_disttae_datasource.go
Labels: size/S, kind/enhancement

#19164 do not update stats within a short time limit
  pkg/frontend/compiler_context.go
  pkg/pb/statsinfo/statsinfo.pb.go
  proto/statsinfo.proto
Labels: size/XS, kind/enhancement

#19349 fix sinker panic
  pkg/cdc/reader.go
  pkg/frontend/cdc.go
Labels: kind/bug, size/S

#19356 [#19326] Fix bug
  pkg/vm/engine/disttae/db.go
Labels: size/S

#19358 reduce reader heap allocation
  pkg/container/batch/batch.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/containers/vectors.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/M, kind/enhancement

#19321 remove getTableDef in openSysTable
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
Labels: size/S, kind/enhancement

#19344 fix some little bugs in shuffle
  pkg/pb/statsinfo/shuffle.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#19352 [bug] release resources in UT
  pkg/proxy/client_conn_test.go
  pkg/proxy/event_test.go
  pkg/proxy/router_test.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
Labels: kind/bug, size/S

#19364 add rollback and retry log
  pkg/sql/compile/compile2.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement

#19331 prefetch data in changes handle
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
Labels: size/M, kind/enhancement

#19311 update replay table info for GC
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/M

#19334 restore pub after restore table
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
Labels: kind/bug, size/M

#19351 Support more remote run.
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
Labels: kind/feature, size/M

#19371 malloc: refactor Profiler
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/profiler_test.go
Labels: size/M, kind/enhancement

#19381 fix: binary execute bug
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#18870 Fulltext index
  go.mod
  go.sum
  pkg/catalog/secondary_index_utils.go
  pkg/catalog/tuplesGen.go
  pkg/catalog/types.go
  pkg/common/fulltext/fulltext.go
  pkg/common/fulltext/fulltext_test.go
  pkg/common/fulltext/types.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/frontend/variables.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/postdml/postdml.go
  pkg/sql/colexec/postdml/postdml_test.go
  pkg/sql/colexec/postdml/types.go
  pkg/sql/colexec/table_function/fulltext.go
  pkg/sql/colexec/table_function/fulltext_tokenize.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/expr.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_fulltext.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_index_util.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/fulltext.go
  pkg/sql/plan/function/func_fulltext.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/vm/process/process2.go
  pkg/vm/process/types.go
  pkg/vm/types.go
  proto/gen.sh
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/feature, size/XXL, Tests, Enhancement, Review effort [1-5]: 4, Bug fix, Feature, Configuration changes, Dependencies

#19386 optimize reader heap allocation
  pkg/objectio/types.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/pk_filter.go
  pkg/vm/engine/tae/blockio/funcs.go
  pkg/vm/engine/tae/blockio/read.go
Labels: size/M, kind/enhancement

#19375 tp query can run in single goroutine when there's no merge operator
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
Labels: size/S, kind/enhancement

#19342 IOAccessTime and IOMergerTime statistics overlap
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/compile/analyze_module.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S

#19389 sync to main: fix Intersection2Vector panic
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
Labels: kind/bug, size/M

#19392 [#19202,#19171, #19018]Add debug info
  pkg/tests/shard/partition_based_test.go
  pkg/tests/testutils/test_utils.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/S

#19385 update changes handler, check GCTS
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/M

#19370 Fix panic cause miss stmt info and log in 1.2
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
Labels: kind/bug, size/XS

#19393 skip restore database which is referenced by other db
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/cluster/snapshot_restore_skip_master_db.result
  test/distributed/cases/snapshot/cluster/snapshot_restore_skip_master_db.sql
Labels: kind/bug, size/M

#19413 extend timeout period for lockservice ut
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
Labels: size/S

#19382 optimize restore account with cluster level pitr
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
Labels: size/XL, kind/enhancement

#19362 output data in a txn
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
  pkg/frontend/predefined.go
  test/distributed/cases/database/system_table.result
  test/distributed/cases/database/system_table.sql
Labels: kind/feature, size/M

#19397 fix recognize stale read
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
Labels: kind/bug, size/S

#19312 scancsvfile memory reuse
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/plan/build_load.go
  pkg/sql/util/csvparser/csv_parser.go
  pkg/sql/util/csvparser/csv_parser_test.go
Labels: size/M, kind/enhancement

#19406 Optimize Hash On Primary Key
  pkg/sql/plan/opt_misc.go
Labels: size/S

#19396 optimize reader
  pkg/objectio/const.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/engine_util/reader.go
Labels: size/M, kind/refactor, kind/enhancement

#19400 make txn do not wait in incrservice while the logtail is paused
  pkg/incrservice/store_sql.go
  pkg/pb/txn/txn_option.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/util/executor/options.go
Labels: kind/bug, size/S

#19410 update the scopes `txnOffset` when reuse compile.
  pkg/sql/compile/compile.go
Labels: size/S

#19417 make txn do not wait in incrservice while the logtail is paused to 1.2
  pkg/incrservice/store_sql.go
  pkg/pb/txn/txn_option.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
  pkg/util/executor/options.go
Labels: kind/bug, size/S

#19369 Fix panic cause miss stmt info and log
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
Labels: kind/bug, size/XS

#19274 malloc: make profiler counters monotonic
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/profiler_test.go
Labels: kind/bug, size/M

#19425 Update tableinfo
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S

#19430 fix restore error info
  pkg/frontend/pitr.go
Labels: kind/bug, size/XS

#19431 fix apply panic
  pkg/sql/colexec/apply/apply.go
  pkg/sql/colexec/apply/types.go
Labels: size/XS

#19320 [refactor] : remove useless code
  pkg/frontend/authenticate.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/compiler_context_test.go
  pkg/frontend/self_handle.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/sql/compile/sql_executor_context.go
Labels: size/M, kind/refactor

#19363 fix: fixed query-service panic on GetReplicaCount
  pkg/cnservice/server_query.go
  pkg/cnservice/server_query_test.go
Labels: kind/bug, size/S

#19432 feat: support truncate big line log message
  pkg/config/configuration.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/trace.go
Labels: size/S, kind/enhancement

#19404 update transfer delete in TN
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/M

#19429 remove some log in task service
  pkg/taskservice/task_service_cron.go
Labels: size/XS, kind/enhancement

#18255 delay ranges call for dml queries
  pkg/sql/compile/compile.go
Labels: size/S, kind/refactor

#19424 add case for restoring pub-sub.
  test/distributed/cases/snapshot/restore_pub_sub.result
  test/distributed/cases/snapshot/restore_pub_sub.sql
Labels: kind/bug, size/M
