Repository matrixorigin/matrixone, pull requests merged in 2024-03, with the labels that each got.

#14750 revert index join again
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: size/L

#14719 fix constant folding of literal vector with 1 item
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#14752 add flush and txn sql into txn trace framework
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/internal_executor.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
  pkg/txn/trace/entry_filter_table.go
  pkg/txn/trace/metedata.go
  pkg/txn/trace/service.go
  pkg/txn/trace/types.go
  pkg/txn/trace/vector.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/L

#14761 [bug] stats: fix connection timed out and r-w confict
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#14762 [bug] revert: performace is bad as the condition is wrong
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/XS

#14757 update readme
  README.md
  README_CN.md
Labels: kind/documentation, size/XS

#14569 chore: stable bvt case result abort statement query_type
  test/distributed/cases/statement_query_type/regression.result
  test/distributed/cases/statement_query_type/regression.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
  test/distributed/cases/statement_query_type/statement_query_type_1.result
  test/distributed/cases/statement_query_type/statement_query_type_1.sql
  test/distributed/cases/statement_query_type/statement_query_type_2.result
  test/distributed/cases/statement_query_type/statement_query_type_2.sql
  test/distributed/cases/statement_query_type/statement_query_type_3.result
  test/distributed/cases/statement_query_type/statement_query_type_3.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_2.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_2.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_3.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_3.sql
Labels: size/XXL, kind/test-ci

#14656 [Bug]: Fix Group By issue in Cluster Index creation.
  pkg/sql/compile/ddl_index_algo.go
Labels: kind/bug, size/XS

#14759 1.1: fix wrong Next call on memory deletes collecting
  pkg/vm/engine/tae/tables/base.go
Labels: kind/bug, size/XS

#14758 fix wrong Next call on memory deletes collecting
  pkg/vm/engine/tae/tables/base.go
Labels: kind/bug, size/XS

#14725 add annotion case
  test/distributed/cases/comment/annotion.result
  test/distributed/cases/comment/annotion.sql
Labels: kind/bug, size/S

#14685 Remove writes from table
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/M, kind/refactor

#14768 Fix TestAppendAndGC for 1.1
  pkg/vm/engine/tae/db/gc/entry.go
Labels: kind/bug, size/S

#14736 addCaseFor2533
  test/distributed/cases/dtype/bigint.result
  test/distributed/cases/keyword/NoReservedKeyword.result
  test/distributed/cases/keyword/NoReservedKeyword.sql
  test/distributed/cases/keyword/ReservedKeyword.result
  test/distributed/cases/keyword/ReservedKeyword.sql
  test/distributed/cases/pessimistic_transaction/insert.result
  test/distributed/cases/pessimistic_transaction/insert.test
  test/distributed/cases/subquery/subquery-with-in.result
  test/distributed/cases/subquery/subquery-with-in.sql
Labels: kind/bug, size/L

#14741 sync to 1.1: restore the switched account id when mo_table_size and mo_table_rows.
  pkg/sql/plan/function/func_mo.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/engine.go
Labels: kind/bug, size/M

#14720 Fix Cron task issue
  pkg/cnservice/upgrader/upgrade_sql.go
  pkg/cnservice/upgrader/upgrader.go
  pkg/cnservice/upgrader/upgrader_util.go
  pkg/util/export/table/table.go
Labels: kind/bug, size/S

#14710 [enhancement] stats: add session cache for stats info.
  pkg/frontend/compiler_context.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/pb/statsinfo/statsinfo.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/compiler_context.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#14772 fix bug : halloween
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S

#14770 [bug] stats: fix bug that stats may be updated to nil.
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/XS

#14713 change plan for insert without unique key column
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  test/distributed/cases/optimizer/insert.result
  test/distributed/cases/optimizer/insert.test
Labels: size/M, kind/enhancement

#14753 resubmit index join again
  pkg/container/batch/batch.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/vm/process/process.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: size/L, kind/enhancement

#14572 Support cn s3 rollback
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/feature, size/M

#14735 fix: fixed panic when python server cannot be connected (#14145)
  pkg/udf/pythonservice/client.go
Labels: kind/bug, size/XS

#14743 [Fix] : fix pkfilter is not work with compound pk in IN expr
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
Labels: kind/bug, size/M

#14777 Fix memory leak caused by fuzzyfilter
  pkg/sql/colexec/fuzzyfilter/types.go
Labels: kind/bug, size/XS

#14731 [bug] logtail server: make a timeout value configurable.
  pkg/tests/service/dnservice.go
  pkg/tests/service/options.go
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/tnservice/service_ports_test.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/tae/logtail/service/session.go
  pkg/vm/engine/tae/logtail/service/session_test.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/cfg_test.go
Labels: size/M

#14724 add cn selector for task scheduler
  pkg/hakeeper/task/cn_ordered_map.go
  pkg/hakeeper/task/cn_ordered_map_test.go
  pkg/hakeeper/task/cn_pool.go
  pkg/hakeeper/task/cn_pool_test.go
  pkg/hakeeper/task/cn_selector.go
  pkg/hakeeper/task/cn_selector_test.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/pb/task/task.pb.go
  proto/task.proto
Labels: size/L, kind/enhancement

#14739 [BugFix]: `SELECT distinct vec, vec from t` throws panic.
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/mergegroup/group.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/S

#14707 for dynamic parameter, substitute param ref and const fold cast expression to improve performance
  pkg/sql/compile/compile.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement

#14776 delay ranges call for insert/delete/update statement
  pkg/sql/compile/compile.go
Labels: size/XS, kind/enhancement

#14740 restore the switched account id when `mo_table_size` and `mo_table_rows`.
  pkg/sql/plan/function/func_mo.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/engine.go
Labels: kind/bug, size/M

#14766 implement fast range for better block filter performance - phase 1
  pkg/objectio/block_info.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/XL, kind/enhancement

#14660 add fk forward reference
  pkg/bootstrap/service.go
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/util_test.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/mock.go
  proto/plan.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.sql
  test/distributed/cases/foreign_key/fk_self_refer2.result
  test/distributed/cases/foreign_key/fk_self_refer2.sql
  test/distributed/cases/foreign_key/fk_self_refer3.result
  test/distributed/cases/foreign_key/fk_self_refer3.sql
  test/distributed/cases/foreign_key/fk_self_refer5.result
  test/distributed/cases/foreign_key/fk_self_refer5.sql
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
  test/distributed/cases/foreign_key/foreign_key_multilayer.result
  test/distributed/cases/foreign_key/foreign_key_multilayer.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/bug, size/XL

#14621 [improvement] moerr: modify the misunderstanding error message.
  pkg/common/moerr/error.go
Labels: size/XS, kind/enhancement

#14773 fix: fixed dashboard filter in pool env
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
Labels: kind/bug, size/S

#14793 Revert "implement fast range for better block filter performance - ph…
  pkg/objectio/block_info.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/index/zm.go
Labels: kind/bug, size/XL

#14791 Added back to the release of compile and its referenced objects
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#14811 Revert "add fk forward reference (#14660)"
  pkg/bootstrap/service.go
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/util_test.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/mock.go
  proto/plan.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.sql
  test/distributed/cases/foreign_key/fk_self_refer2.result
  test/distributed/cases/foreign_key/fk_self_refer2.sql
  test/distributed/cases/foreign_key/fk_self_refer3.result
  test/distributed/cases/foreign_key/fk_self_refer3.sql
  test/distributed/cases/foreign_key/fk_self_refer5.result
  test/distributed/cases/foreign_key/fk_self_refer5.sql
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
  test/distributed/cases/foreign_key/foreign_key_multilayer.result
  test/distributed/cases/foreign_key/foreign_key_multilayer.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: size/XL, kind/test-ci

#14797 sync to 1.1: fix the logic err in PrefixIn when vector unsorted
  pkg/sql/plan/function/func_prefix.go
Labels: kind/bug, size/XS

#14751 feat: add fromProxy to status session
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/pb/status/status.pb.go
  proto/status.proto
Labels: kind/feature, size/S

#14800 [bug] BR: fix bug when restore data
  pkg/logservice/service_bootstrap.go
Labels: kind/bug, size/S

#14808 fileservice: add ObjectStorageArguments.NoBucketValidation (#14510)
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v1.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/get.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs_test.go
Labels: size/M, kind/enhancement

#14744 Fix Avg.Merge()
  pkg/sql/plan/function/functionAgg/avg.go
Labels: size/XS

#14782 fix 14780
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/options/options.go
Labels: kind/bug, size/XS

#14809 modify mo_task primary key type to bigint in 1.1
  pkg/bootstrap/bootstrap.go
  pkg/sql/plan/function/ctl/cmd_task.go
Labels: kind/bug, size/S

#14801 add txn based trace
  go.mod
  pkg/cnservice/server.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session_test.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/util_test.go
  pkg/incrservice/service.go
  pkg/incrservice/store_mem.go
  pkg/pb/txn/txn.pb.go
  pkg/pb/txn/txn_option.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/function/ctl/cmd_txn_trace.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/leak_checker_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_events.go
  pkg/txn/client/operator_events_test.go
  pkg/txn/client/operator_test.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/txn/trace/filter_data.go
  pkg/txn/trace/filter_txn.go
  pkg/txn/trace/metedata.go
  pkg/txn/trace/service.go
  pkg/txn/trace/service_data_event.go
  pkg/txn/trace/service_txn_event.go
  pkg/txn/trace/types.go
  pkg/util/executor/options.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
  proto/txn.proto
  test/distributed/cases/tenant/tenant.result
Labels: kind/feature, size/XL

#14819 remove some stats to improve tp performance in 1.1-dev
  pkg/objectio/cache.go
  pkg/vm/engine/tae/blockio/pipeline.go
Labels: size/S, kind/enhancement

#14760 add support to query task user
  pkg/sql/plan/function/ctl/cmd_task.go
Labels: size/S, kind/enhancement

#13801 Estimate the tcp packet num response
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/protocol.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/M, kind/enhancement

#14738 [Feature]: Master Index Optimizer Rule
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_master.go
  pkg/sql/plan/apply_indices_vector.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
Labels: kind/feature, size/L

#14704 [opt] use secondary index when join on indexed columns
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/init.go
  pkg/sql/plan/join_order.go
  pkg/sql/plan/limit_binder.go
  pkg/sql/plan/make.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/pushdown.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/visit_plan.go
  proto/plan.proto
Labels: kind/feature, size/XL

#14810 remove some stats to improve tp performance
  pkg/objectio/cache.go
  pkg/vm/engine/tae/blockio/pipeline.go
Labels: size/S, kind/performance, perf/tp, kind/enhancement

#14382 Background query run in selected CN
  cmd/mo-service/main.go
  etc/launch/log.toml
  pkg/clusterservice/selector.go
  pkg/common/runtime/types.go
  pkg/config/configuration.go
  pkg/util/cn_address_func.go
  pkg/util/cn_address_func_test.go
  pkg/util/export/etl/db/db_holder.go
Labels: kind/feature, size/S

#14816 [fix] : fix #14521
  pkg/sql/plan/build_insert.go
Labels: kind/bug, size/S

#14709 fix data race in ApplyCommit
  pkg/vm/engine/tae/catalog/table.go
Labels: kind/bug, size/XS

#14805 format with quotation marks
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S

#14814 [fix] missing free for compile.Compile
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S

#14822 fix data race in ApplyCommit , cherry-pick 14709
  pkg/vm/engine/tae/catalog/table.go
Labels: kind/bug, size/XS

#14603 add some indexes for tables in mo_task
  pkg/bootstrap/service.go
  pkg/bootstrap/versions/v1_2_0/upgrade.go
  test/distributed/cases/tenant/tenant.test
Labels: size/S, kind/enhancement

#14769 Support 'double' type variable
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/database/system_variables.sql
Labels: size/S, kind/enhancement

#14818 cherry pick fix 14780 (#14782) to 1.1-dev
  pkg/vm/engine/tae/db/scheduler.go
  pkg/vm/engine/tae/options/options.go
Labels: kind/bug, size/S

#14795 update cron task before run another time
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/mysql_task_storage_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_holder.go
  pkg/taskservice/types.go
Labels: size/L, kind/enhancement

#14830 Remove writes from table
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#14826 small Improve TS API
  pkg/container/types/txnts.go
Labels: size/S, kind/enhancement

#14645 disttae: call packer.FreeMem in pool reset function
  pkg/vm/engine/disttae/engine.go
Labels: kind/bug, size/XS

#14807 CI: enable txn trace for checkin regression
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#14835 fix a bug that runtime filter is not pushed for 1.1
  pkg/sql/plan/runtime_filter.go
Labels: kind/bug, size/XS

#14798 Enable pkfilter for unqiue index
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
Labels: size/L, kind/enhancement

#14838 CI: splite prepare data and test for sysbench
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#14841 Improve point select performance
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/S, kind/enhancement

#14796 fix the logic err in `PrefixIn` when vector unsorted
  pkg/sql/plan/function/func_prefix.go
Labels: kind/bug, size/XS

#14831 fix a bug that table scan do not go index sometimes
  pkg/sql/plan/apply_indices.go
Labels: kind/bug, size/S

#14722 Fix offset in dumpBatchLocked. #14587
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14845 [Bug]: Index JOIN returns left child rows when right child is empty
  pkg/sql/compile/scope.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/bug, size/S

#14813 Check length when casting other types to str
  pkg/sql/plan/function/func_cast.go
  pkg/sql/plan/function/type_check.go
Labels: size/M

#14851 [enhancement] proxy: transfer connection more proactivly
  pkg/proxy/config.go
  pkg/proxy/config_test.go
  pkg/proxy/conn_manager.go
  pkg/proxy/conn_manager_test.go
  pkg/proxy/event.go
  pkg/proxy/handler.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/rebalancer.go
  pkg/proxy/router_test.go
  pkg/proxy/scaling.go
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/proxy/util.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
  pkg/util/metric/v2/proxy.go
Labels: size/M, kind/enhancement

#14834 [BugFix]: Master Index `LIMIT` support
  pkg/sql/plan/apply_indices_master.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
Labels: kind/bug, size/S

#14858 [enhancement] proxy: transfer connection more proactivly
  pkg/proxy/config.go
  pkg/proxy/config_test.go
  pkg/proxy/conn_manager.go
  pkg/proxy/conn_manager_test.go
  pkg/proxy/event.go
  pkg/proxy/handler.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/rebalancer.go
  pkg/proxy/router_test.go
  pkg/proxy/scaling.go
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/proxy/util.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
  pkg/util/metric/v2/proxy.go
Labels: size/M, kind/enhancement

#14833 support stale read in parser
  pkg/frontend/authenticate_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/dialect/mysql/scanner.go
  pkg/sql/parsers/tree/table_name.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/query_builder.go
Labels: kind/feature, size/XXL

#14844 fix trace
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/trace/metedata.go
  pkg/txn/trace/service_txn_event.go
  pkg/txn/trace/types.go
Labels: kind/feature, size/S

#14842 add character set
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
  test/distributed/cases/load_data/load_data_set_null.result
  test/distributed/cases/load_data/load_data_set_null.sql
Labels: kind/bug, size/XXL

#14850 Optimize timestamp operations
  pkg/container/types/txnts.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/txnentries/compactblk.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnbase/impl.go
Labels: size/S, kind/enhancement

#14867 revert delay ranges call
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#14865 [Bug]: The plan of prepared statement changes every run
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/XS

#14815 add fk forward reference
  pkg/bootstrap/service.go
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/frontend/query_result_test.go
  pkg/frontend/util_test.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/util.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/mock.go
  proto/plan.proto
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks2.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks3.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks4.sql
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.result
  test/distributed/cases/foreign_key/fk_foreign_key_checks5.sql
  test/distributed/cases/foreign_key/fk_self_refer2.result
  test/distributed/cases/foreign_key/fk_self_refer2.sql
  test/distributed/cases/foreign_key/fk_self_refer3.result
  test/distributed/cases/foreign_key/fk_self_refer3.sql
  test/distributed/cases/foreign_key/fk_self_refer5.result
  test/distributed/cases/foreign_key/fk_self_refer5.sql
  test/distributed/cases/foreign_key/foreign_key.result
  test/distributed/cases/foreign_key/foreign_key.sql
  test/distributed/cases/foreign_key/foreign_key_multilayer.result
  test/distributed/cases/foreign_key/foreign_key_multilayer.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/bug, size/XL

#14864 return allocate error in auto increment service
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
  pkg/incrservice/service_test.go
  pkg/incrservice/table_cache.go
Labels: kind/bug, size/S

#14734 Support: Check PrimaryKeys persisted on S3 whether changed between(snapshotTS, lockedTS] when txn runs on RC-Pessimistic mode.
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
Labels: size/M

#14862 fix split command, cherry-pick 14855
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#14853 [bug] fix ut case
  pkg/util/address/address_test.go
Labels: kind/bug, size/XS

#14861 Fix: get tblName/colName by relpos and colpos instead of col.Name
  pkg/sql/plan/binding.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: kind/bug, size/S

#14875 patch for pr 14734
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/S

#14832 [BugFix]: Master Index `IN` support
  pkg/sql/plan/apply_indices_master.go
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/secondary_index_master.sql
  test/distributed/cases/optimizer/index.result
Labels: kind/bug, size/M

#14854 [bug] fix ut case
  pkg/util/address/address_test.go
Labels: kind/bug, size/XS

#14873 update kinds of abnormal txn behavior
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/cnservice/server.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/util_test.go
  pkg/pb/txn/txn.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/client.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/entire_engine_test.go
  proto/txn.proto
Labels: size/M, kind/enhancement

#14742 fix split_part and revert #14584
  pkg/sql/plan/function/func_binary.go
  test/distributed/cases/function/func_string_split_part.result
  test/distributed/cases/function/function_split_part.result
Labels: size/M

#14855 fix OnReplayTxn
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#14859 fix delete not assign to new slice
  pkg/hakeeper/task/cn_pool.go
Labels: kind/bug, size/XS

#14869 fix the storage usage obj double delete
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: kind/bug, size/M

#14609 [enhancement] proxy: migrate prepare stmts when connection is transferred from one cn to another one.
  pkg/cnservice/server_query.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/pb/query/query.pb.go
  pkg/pb/task/task.pb.go
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/conn_migration.go
  pkg/proxy/conn_migration_test.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler.go
  pkg/proxy/handler_test.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/server_conn_test.go
  pkg/proxy/tunnel.go
  pkg/proxy/util_test.go
  pkg/queryservice/client/query_client.go
  proto/query.proto
Labels: kind/feature, size/XL, kind/enhancement

#14847 [1.1-dev] add GetPipelineInfo API to query-service
  pkg/cnservice/server.go
  pkg/cnservice/server_query.go
  pkg/cnservice/types.go
  pkg/pb/query/query.pb.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/pipeline.go
  proto/query.proto
Labels: size/S, kind/enhancement

#14884 optimize sql statement with limit 0
  pkg/sql/colexec/limit/limit.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement

#14848 [1.1-dev] feat: add fromProxy to status session
  pkg/frontend/mysql_protocol.go
  pkg/frontend/session.go
  pkg/pb/status/status.pb.go
  proto/status.proto
Labels: size/S, kind/enhancement

#14771 support snapshot opt
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/snapshot.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/mock.go
  pkg/sql/util/util.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/snapshot/snapshot.result
  test/distributed/cases/snapshot/snapshot.sql
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: kind/feature, size/XXL

#14874 cherry-pick to 1.1dev: add character set
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/update.go
  test/distributed/cases/load_data/load_data_set_null.result
  test/distributed/cases/load_data/load_data_set_null.sql
Labels: size/XXL

#14870 sync to 1.1: fix the storage usage obj double delete
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#14892 add alter table case for pub-sub db
  test/distributed/cases/ddl/alter_publish_subscribe_table.result
  test/distributed/cases/ddl/alter_publish_subscribe_table.sql
Labels: kind/feature, size/M

#14898 [bug] proxy: fix lost connection issue in tpcc test.
  pkg/proxy/conn_manager.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/tunnel.go
  pkg/proxy/util.go
Labels: kind/bug, size/M

#14889 cherry pick "optimize sql statement with limit 0 (#14884)" to 1.1-dev
  pkg/sql/colexec/limit/limit.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement

#14891 cherry-pick to 1.1dev: add rollback last statement
  pkg/frontend/cmd_executor.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/protocol.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/optimistic/atomicity_1.result
  test/distributed/cases/optimistic/autocommit.result
  test/distributed/cases/optimistic/autocommit_1.result
  test/distributed/cases/optimistic/autocommit_isolation.result
  test/distributed/cases/optimistic/autocommit_isolation_1.result
  test/distributed/cases/optimistic/conflict_transation.result
  test/distributed/cases/optimistic/drop_table_truncate.result
  test/distributed/cases/optimistic/isolation.result
  test/distributed/cases/optimistic/isolation_1.result
  test/distributed/cases/optimistic/isolation_2.result
  test/distributed/cases/optimistic/rollback_stmt.result
  test/distributed/cases/optimistic/rollback_stmt.sql
  test/distributed/cases/optimistic/rollback_stmt2.result
  test/distributed/cases/optimistic/rollback_stmt2.sql
  test/distributed/cases/optimistic/rollback_stmt3.result
  test/distributed/cases/optimistic/rollback_stmt3.sql
  test/distributed/cases/optimistic/rollback_stmt4.result
  test/distributed/cases/optimistic/rollback_stmt4.sql
  test/distributed/cases/optimistic/special.result
  test/distributed/cases/optimistic/special.sql
  test/distributed/cases/optimistic/transaction_enhance.result
  test/distributed/cases/optimistic/unique_secondary_index.result
  test/distributed/cases/pessimistic_transaction/atomicity.result
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.sql
  test/distributed/cases/pessimistic_transaction/autocommit_isolation_1.result
  test/distributed/cases/pessimistic_transaction/autocommit_isolation_1.sql
  test/distributed/cases/pessimistic_transaction/conflict_transaction.result
  test/distributed/cases/pessimistic_transaction/drop_table_truncate.result
  test/distributed/cases/pessimistic_transaction/insert.result
  test/distributed/cases/pessimistic_transaction/isolation.result
  test/distributed/cases/pessimistic_transaction/isolation_1.result
  test/distributed/cases/pessimistic_transaction/isolation_2.result
  test/distributed/cases/pessimistic_transaction/isolation_2.sql
  test/distributed/cases/pessimistic_transaction/rollback_stmt.result
  test/distributed/cases/pessimistic_transaction/rollback_stmt.sql
  test/distributed/cases/pessimistic_transaction/rollback_stmt2.result
  test/distributed/cases/pessimistic_transaction/rollback_stmt2.sql
  test/distributed/cases/pessimistic_transaction/rollback_stmt3.result
  test/distributed/cases/pessimistic_transaction/rollback_stmt3.sql
  test/distributed/cases/pessimistic_transaction/select_for_update.result
  test/distributed/cases/pessimistic_transaction/special.result
  test/distributed/cases/pessimistic_transaction/special.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/unique_secondary_index.result
  test/distributed/cases/pessimistic_transaction/ww_conflict.result
  test/distributed/cases/sequence/create_sequence.result
Labels: kind/bug, size/XL

#14896 [bug] proxy: fix lost connection issue in tpcc test.
  pkg/proxy/conn_manager.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/tunnel.go
  pkg/proxy/util.go
Labels: kind/bug, size/M

#14899 fix bug: can not show databases after drop database
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.sql
Labels: kind/bug, size/S

#14857 Add task schedule in 1.1
  pkg/hakeeper/task/cn_ordered_map.go
  pkg/hakeeper/task/cn_ordered_map_test.go
  pkg/hakeeper/task/cn_pool.go
  pkg/hakeeper/task/cn_pool_test.go
  pkg/hakeeper/task/cn_selector.go
  pkg/hakeeper/task/cn_selector_test.go
  pkg/hakeeper/task/parse.go
  pkg/hakeeper/task/parse_test.go
  pkg/hakeeper/task/task_scheduler.go
  pkg/hakeeper/task/task_scheduler_test.go
  pkg/pb/task/task.pb.go
  pkg/taskservice/mem_task_storage.go
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/mysql_task_storage_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_holder.go
  pkg/taskservice/types.go
  proto/task.proto
Labels: kind/feature, size/XL

#14871 CU calculation & metric improvement
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/config/configuration.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_sql.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/mometric/metric_collector.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/cu.go
  pkg/util/trace/impl/motrace/cu_bench_test.go
  pkg/util/trace/impl/motrace/cu_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/trace.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/log/query_cu.result
  test/distributed/cases/log/query_cu.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: kind/feature, size/XL

#14927 disable cu metric for Regression Test
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/XS

#14904 fix bug: can not show databases after drop database (#14899)
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.sql
Labels: kind/bug, size/S

#14922 cherry pick dup
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S

#14907 Split Sels in Inner/Left/Rignt Join
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
Labels: size/M

#14933 [BugFix]: Master Index LIMIT panic
  pkg/sql/plan/apply_indices_master.go
Labels: kind/bug, size/S

#14881 Background query run in selected CN in 1.1
  cmd/mo-service/main.go
  etc/launch/log.toml
  pkg/clusterservice/selector.go
  pkg/common/runtime/types.go
  pkg/config/configuration.go
  pkg/util/cn_address_func.go
  pkg/util/cn_address_func_test.go
  pkg/util/export/etl/db/db_holder.go
Labels: kind/feature, size/S

#14887 cherry-pick to 1.1-dev: add foreign key self refer
  .gitignore
  pkg/common/moerr/error.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/utils.go
  proto/plan.proto
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_change_column.sql
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.sql
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.result
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.sql
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_modify_column.sql
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/alter_table_rename_column.sql
  test/distributed/cases/ddl/desc_table_with_foreign_key.result
  test/distributed/cases/ddl/desc_table_with_foreign_key.sql
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/dtype/binary.test
  test/distributed/cases/foreign_key/fk_self_refer.result
  test/distributed/cases/foreign_key/fk_self_refer.sql
  test/distributed/cases/foreign_key/fk_self_refer2.result
  test/distributed/cases/foreign_key/fk_self_refer2.sql
  test/distributed/cases/foreign_key/fk_self_refer3.result
  test/distributed/cases/foreign_key/fk_self_refer3.sql
  test/distributed/cases/foreign_key/fk_self_refer4.result
  test/distributed/cases/foreign_key/fk_self_refer4.sql
  test/distributed/cases/foreign_key/fk_self_refer5.result
  test/distributed/cases/foreign_key/fk_self_refer5.sql
Labels: kind/bug, size/XXL

#14923 adjust the db, table visibility in `show accounts`
  pkg/frontend/show_account.go
Labels: kind/bug, size/S

#14924 sync to 1.1: adjust the db, table visibility in show accounts
  pkg/frontend/show_account.go
  test/distributed/cases/tenant/tenant.result
Labels: kind/bug, size/S

#14928 add case for serial_extract
  test/distributed/cases/function/func_encode_decode.result
  test/distributed/cases/function/func_encode_decode.sql
Labels: kind/feature, size/S

#14893 filter by prefix_between/prefix_in in Reader
  pkg/container/types/bytes.go
  pkg/container/vector/search.go
  pkg/container/vector/utils_test.go
  pkg/sql/plan/function/func_prefix.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/index/zm.go
Labels: kind/feature, size/M

#14929 Add load case
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/test_character.csv
  test/distributed/resources/load_data/test_character01.csv
Labels: kind/feature, size/M

#14944 fix wrong name of file in fileservice
  pkg/catalog/catalog.go
Labels: kind/bug, size/XS

#14934 support insert into time/datetime/timestamp type with hint
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/expr.go
  pkg/sql/util/util.go
  test/distributed/cases/dtype/timestamp.result
  test/distributed/cases/dtype/timestamp.test
Labels: kind/feature, size/XXL

#14941 Reduce the memory overhead of fuzzy filter during primary dup check
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: size/XS, kind/enhancement

#14945 Record negative cpu / cu value
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_trace.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/trace.go
  pkg/util/trace/impl/motrace/report_statement.go
Labels: kind/bug, size/S

#14906 lock service rolling restart
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/defines/const.go
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/pb/lock/lock.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
  proto/lock.proto
Labels: size/XL

#14921 fix insert into enum type with select clause (#1.1-dev)
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/util/eval_expr_util.go
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum_1.result
  test/distributed/cases/dtype/enum_1.test
Labels: kind/bug, size/S

#14947 change RPC timeout to avoid stream closed
  pkg/cnservice/cnclient/client.go
Labels: kind/bug, size/XS

#14951 fix delete nil routine
  pkg/frontend/routine_manager.go
Labels: kind/bug, size/S

#14948 CU calculation & metric improvement in 1.1
  pkg/catalog/types.go
  pkg/cnservice/upgrader/new_add_table.go
  pkg/config/configuration.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/query_builder.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_sql.go
  pkg/util/metric/mometric/metric.go
  pkg/util/metric/mometric/metric_collector.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_trace.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/trace.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/cu.go
  pkg/util/trace/impl/motrace/cu_bench_test.go
  pkg/util/trace/impl/motrace/cu_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/trace.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/log/query_cu.result
  test/distributed/cases/log/query_cu.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/tenant/tenant.result
Labels: kind/feature, size/XL

#14952 support insert into time/datetime/timestamp type with hint (#1.1-dev)
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/expr.go
  pkg/sql/util/util.go
  test/distributed/cases/dtype/timestamp.result
  test/distributed/cases/dtype/timestamp.test
Labels: kind/bug, size/XXL

#14942 cherry-pick to 1.1dev: update kinds of abnormal txn behavior
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/cnservice/server.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/util_test.go
  pkg/pb/txn/txn.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/client.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/leak_checker_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/entire_engine_test.go
  proto/txn.proto
Labels: size/M, kind/enhancement

#14920 Optimize timestamp operations
  pkg/backup/tae.go
  pkg/container/types/txnts.go
  pkg/container/vector/vector.go
  pkg/sql/compile/compile.go
  pkg/txn/storage/memorystorage/memorytable/tuple.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/primary_key_utils.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/txn_test.go
  pkg/vm/engine/tae/db/test/util_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/logtailer.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/blk.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnbase/mvccslice.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/M, kind/enhancement

#14954 sync to 1.1: counting index table sizes and the original table size together when mo_table_size
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/M

#14963 Revert "lock service rolling restart"
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/defines/const.go
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/test_helper.go
  pkg/pb/lock/lock.pb.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
  proto/lock.proto
Labels: size/XL

#14925 [Improvement] : For auto incr unique key, remove deduplication detection if there will be no conflict.
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  test/distributed/cases/optimizer/insert.result
  test/distributed/cases/optimizer/insert.test
Labels: size/M, kind/enhancement

#14966 cherrypick to 1.1-dev: add statement latency metric
  pkg/cnservice/upgrader/new_add_table.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_sql.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/tenant/tenant.result
Labels: kind/feature, size/S

#14799 filters optimization in `ranges`
  pkg/objectio/block_info.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/index/zm.go
Labels: size/XL, kind/enhancement

#14957 fix bug: get deleted db when autocommit=0
  pkg/catalog/catalog.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/pessimistic_transaction/autocommit_isolation.result
Labels: kind/bug, size/S

#14868 return allocate error in auto increment service to 1.1
  pkg/incrservice/column_cache.go
  pkg/incrservice/column_cache_test.go
  pkg/incrservice/service_test.go
  pkg/incrservice/table_cache.go
Labels: kind/bug, size/S

#14978 Revert "filters optimization in `ranges` (#14799)"
  pkg/objectio/block_info.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/index/zm.go
Labels: kind/bug, size/XL

#14971 optimize like expr
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/function/init.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
  test/distributed/cases/optimizer/like.result
  test/distributed/cases/optimizer/like.test
  test/distributed/cases/optimizer/runtimefilter.result
  test/distributed/cases/optimizer/runtimefilter.test
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
Labels: size/M, kind/enhancement

#14910 [refactor] : continue use reuse package to reuse some parser-nodes
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/analyze.go
  pkg/sql/parsers/tree/backup.go
  pkg/sql/parsers/tree/connector.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/deallocate.go
  pkg/sql/parsers/tree/drop.go
  pkg/sql/parsers/tree/explain.go
  pkg/sql/parsers/tree/extension.go
  pkg/sql/parsers/tree/function.go
  pkg/sql/parsers/tree/prepare.go
  pkg/sql/parsers/tree/procedure.go
  pkg/sql/parsers/tree/replace.go
  pkg/sql/parsers/tree/sequence.go
  pkg/sql/parsers/tree/snapshot.go
  pkg/sql/parsers/tree/source.go
  pkg/sql/parsers/tree/stages.go
  pkg/sql/parsers/tree/truncate.go
  pkg/sql/parsers/tree/use.go
  pkg/sql/parsers/tree/view.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/query_builder.go
Labels: size/XXL, kind/enhancement

#14912 Feature/bitmap
  pkg/sql/colexec/agg/agg.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/bitmap_or.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_agg.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_bitmap.result
  test/distributed/cases/function/func_bitmap.sql
Labels: kind/feature, size/XXL

#14980 [Improvement] : For auto incr unique key, remove deduplication detection if there will be no conflict
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
Labels: size/M, kind/enhancement

#14990 [BugFix]: Upgrade Not getting applied to System Tenant
  pkg/cnservice/upgrader/new_add_column.go
  pkg/cnservice/upgrader/upgrader.go
Labels: kind/bug, size/S
