Repository matrixorigin/matrixone, pull requests merged in 2024-01, with the labels that each got.

#13934 CI: change account for sysbench
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13935 CI: change account for sysbench for 1.1-dev
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#13940 modify the result of function year
  test/distributed/cases/function/func_datetime_utc_timestamp.result
Labels: kind/bug, size/XS

#13947 cherry-pick 'modify the result of function year()' to 1.0-dev.
  test/distributed/cases/function/func_datetime_utc_timestamp.result
Labels: kind/bug

#13945 cherry-pick 'modify the result of function year()' to 1.1-dev.
  test/distributed/cases/function/func_datetime_utc_timestamp.result
Labels: kind/bug, size/XS

#13663 Check PK duplication on cn side when small txn commits
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/frontend/test/txn_mock.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/bug, size/L, kind/enhancement

#13952 remove segdel batch and block meta without deltaloc in ckp
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/feature, size/M

#13957 CI: change auto add milestone to 1.2.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/robot.yml
Labels: kind/test-ci

#13962 [bug] disttae: fix a UT in route package.
  pkg/vm/engine/disttae/route/route_test.go
Labels: kind/bug, size/XS

#13964 fix 12617
  pkg/sql/colexec/external/external.go
Labels: kind/bug, size/XS

#13859 Ranges returns []byte instead of [][]byte
  pkg/catalog/types.go
  pkg/catalog/types_test.go
  pkg/frontend/test/engine_mock.go
  pkg/frontend/util_test.go
  pkg/objectio/block_info.go
  pkg/objectio/block_info_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/runtime_filter.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/plan/function/func_mo.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/types.go
  proto/pipeline.proto
Labels: size/L, kind/refactor

#13896 [postfix] proxy: fix the prepare wait condition from execute to close
  pkg/proxy/client_conn.go
  pkg/proxy/event.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/bug, size/S

#13941 Remove an incorrectly timed dropout update that invalidates a live probe
  pkg/lockservice/lock_table_allocator.go
Labels: kind/bug, size/XS

#13966 [cherry-pick] #13965 optimized the uuid-process map to avoid memory leak.
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/S

#13937 docs: refine python udf docs
  pkg/udf/pythonservice/demo/README.md
  pkg/udf/pythonservice/demo/README_CN.md
Labels: kind/documentation, size/XS

#13981 [cherry-pick] #13941 Remove an incorrectly timed dropout update that invalidates a live probe
  pkg/lockservice/lock_table_allocator.go
Labels: kind/bug, size/XS

#13980 [cherry-pick] #13941 Remove an incorrectly timed dropout update that invalidates a live probe
  pkg/lockservice/lock_table_allocator.go
Labels: kind/bug, size/XS

#13972 support fast fail if lock conflict
  pkg/bootstrap/bootstrap.go
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/incrservice/store_sql.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/compile/sql_executor.go
  pkg/tests/txn/cluster_basic_test.go
  pkg/util/executor/mem_executor.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/feature, size/M

#13969 Add Load data case from jsonline
  test/distributed/cases/load_data/load_data_jsonline.result
  test/distributed/cases/load_data/load_data_jsonline.test
  test/distributed/resources/load_data/jsonline_array01.jl
Labels: kind/bug, size/S

#13979 fileservice: do not set default role arn from os env
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#13938 fix-maxvalue-panic
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
Labels: kind/bug, size/XXL

#13965 optimized the map from uuid to process to avoid memory leak.
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: size/S, kind/enhancement

#13989 update lazy-load to avoid unnecessary blocking
  pkg/vm/engine/disttae/logtailreplay/partition.go
Labels: size/XS, kind/enhancement

#13975 fileservice: do not set default role arn from os env
  pkg/fileservice/aliyun_sdk.go
Labels: kind/bug, size/S

#14001 fix cmd_field_list
  pkg/frontend/util.go
Labels: kind/bug, size/S

#13967 enable pkfilter for auto increment type pk if none valus is null
  pkg/sql/plan/build_insert.go
Labels: size/S, kind/enhancement

#13994 CI: sync ci to 1.0-dev
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/e2e-upgrade.yaml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
  .github/workflows/utils.yaml
Labels: kind/test-ci

#14014 fix non reserverd keyword last
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/util/keywords.result
  test/distributed/cases/util/keywords.sql
Labels: size/XXL

#14017 fix cmd_field_list (#1.0-dev)
  pkg/frontend/util.go
Labels: kind/bug, size/S

#14010 fix cmd_field_list (#1.1-dev)
  pkg/frontend/util.go
Labels: kind/bug, size/S

#13985 add query results cases
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
  test/distributed/cases/query_result/query_result_cloud.result
  test/distributed/cases/query_result/query_result_cloud.sql
Labels: kind/bug, size/XL

#14013 fix non reserved keyword ownership
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: size/XXL

#14018 update handle object insert
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/bug, size/S

#14003 [bug] disttae: fix a UT in route package.
  pkg/vm/engine/disttae/route/route_test.go
Labels: kind/bug, size/XS

#13895 [postfix] proxy: fix the prepare wait condition from execute to close
  pkg/proxy/client_conn.go
  pkg/proxy/event.go
  pkg/proxy/mysql_conn_buf.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/bug, size/S

#14016 fix non reserved keyword import, stream
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  test/distributed/cases/util/keywords.result
  test/distributed/cases/util/keywords.sql
Labels: size/XXL

#14012 Compare ranges.Size() with len(newranges) instead of ranges.Len()
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#14004 Fix bug: marshal query error
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/explain/marshal_query_test.go
Labels: kind/bug, size/M

#13932 [Feature]: Vector Index | Phase 4 (kmeans issue, delete from table, lists=0)
  pkg/catalog/secondary_index_utils.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer.go
  pkg/sql/plan/function/functionAgg/cluster_centers.go
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
Labels: kind/feature, size/M

#13988 fix bug: prepare statement should throw error when too many parameters
  pkg/common/moerr/error.go
  pkg/sql/plan/build_dcl.go
Labels: kind/bug, size/S

#14022 cherry-pick update handle object insert (#14018)
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/bug, size/S

#14025 Add a loop to guarantee gc
  pkg/common/mpool/alloc_tracing.go
Labels: kind/bug, size/S

#14039 fix panic if allocating lock table from dn failed to 1.1
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
Labels: kind/bug, size/S

#14019 fileservice: refine disk cache with fifo cache
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/queue.go
  pkg/fileservice/fifocache/queue_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/L, kind/enhancement

#14029 sync_to_1.1: defer on time.since not work
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/XS

#14036 Fix bug: marshal query error (#14004)
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/explain/marshal_query_test.go
Labels: kind/bug, size/M

#14040 fix panic if allocating lock table from dn failed
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
Labels: kind/bug, size/S

#14023 remove segdel batch and block meta without deltaloc in ckp, cherry-pick #13952
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: size/M, kind/enhancement

#13973 CI: upgrade go version to 1.21.5
  .github/actions/setup_env/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/e2e-upgrade.yaml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
  .github/workflows/utils.yaml
  .golangci.yml
  Makefile
  optools/bvt_ut/Dockerfile
  optools/bvt_ut/entrypoint.sh
  optools/compose_bvt/Dockerfile.tester
  optools/images/Dockerfile
Labels: size/M, kind/test-ci

#13953 [opt] apply indices for BETWEEN expressions
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/associative_law.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_layout.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/operator_between.go
  pkg/sql/plan/function/type_check.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/index/zm.go
  test/distributed/cases/operator/between_and_operator.result
  test/distributed/cases/optimizer/pushdown.result
Labels: kind/feature, size/XL, kind/enhancement

#14049 objectio: use fifocache
  pkg/objectio/cache.go
Labels: size/S, kind/enhancement

#14030 add more metrics for accept connection duration
  pkg/frontend/mysql_protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/util/metric/v2/frontend.go
Labels: size/S, kind/enhancement

#14035 [cherry-pick] #14034 fix lots of unhandled errors.
  pkg/container/batch/batch_test.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/objectio/utils.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/table_function/current_account.go
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/generate_series_test.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/function/function_test.go
  pkg/sql/util/eval_expr_util.go
  pkg/testutil/types.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/util/export/etl/tae.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/containers/vector.go
Labels: kind/bug, size/XL

#14045 add more metrics for accept connection duration
  pkg/frontend/mysql_protocol.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/util/metric/v2/frontend.go
Labels: size/S, kind/enhancement

#14047 support cmd_set_option
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/protocol.go
Labels: size/M, kind/enhancement

#14053 [cherry-pick] #14052 removed a context done error at the remote run stage.
  pkg/sql/colexec/server.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/S

#14051 Cherry-pick #13268(1.1dev)
  pkg/frontend/compiler_context.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_load.go
  pkg/sql/plan/build_replace.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/stats.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
Labels: size/M, kind/enhancement

#14042 cherry-pick #13690 (1.0dev)
  pkg/container/types/rowid.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/agg/agg.go
  pkg/sql/colexec/agg/distagg.go
  pkg/sql/colexec/agg/types.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/types.go
  pkg/sql/colexec/multi_col/group_concat/group_concat.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/types.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/any_value.go
  pkg/sql/plan/function/functionAgg/approx_count.go
  pkg/sql/plan/function/functionAgg/avg.go
  pkg/sql/plan/function/functionAgg/bit_and.go
  pkg/sql/plan/function/functionAgg/bit_or.go
  pkg/sql/plan/function/functionAgg/bit_xor.go
  pkg/sql/plan/function/functionAgg/count.go
  pkg/sql/plan/function/functionAgg/dense_rank.go
  pkg/sql/plan/function/functionAgg/group_concat.go
  pkg/sql/plan/function/functionAgg/max.go
  pkg/sql/plan/function/functionAgg/median.go
  pkg/sql/plan/function/functionAgg/min.go
  pkg/sql/plan/function/functionAgg/rank.go
  pkg/sql/plan/function/functionAgg/row_number.go
  pkg/sql/plan/function/functionAgg/stddev_pop.go
  pkg/sql/plan/function/functionAgg/sum.go
  pkg/sql/plan/function/functionAgg/var_pop.go
  proto/pipeline.proto
Labels: size/L

#14058 support cmd_set_option (#1.1-dev)
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/protocol.go
Labels: size/M, kind/enhancement

#14060 fix a bug that shuffle on expression cause wrong result
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#13857 change gen uuid method to v7
  cmd/mo-service/main.go
  go.mod
  go.sum
  pkg/backup/backup.go
  pkg/cnservice/memory_engine.go
  pkg/common/morpc/backend.go
  pkg/container/types/rowid.go
  pkg/container/types/uuid.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/session.go
  pkg/objectio/id.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRunTypes_test.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/udf.go
  pkg/sql/plan/query_builder.go
  pkg/sql/util/index_util.go
  pkg/stream/adapter/kafka/adapter.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/logservice.go
  pkg/tests/service/service.go
  pkg/txn/client/generator.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/uuidutil_test.go
  pkg/vm/engine/tae/common/seqnum.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: size/S, kind/enhancement

#14043 [Feature]: Vector Index | Phase 4 (kmeans normalize for better member distribution)
  pkg/catalog/secondary_index_utils.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/function/functionAgg/agg_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer_bench_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/types.go
  pkg/sql/plan/function/functionAgg/cluster_centers.go
  pkg/vectorize/moarray/internal.go
  test/distributed/cases/array/array_index.result
  test/distributed/cases/array/array_index.sql
Labels: kind/feature, size/M

#14037 fix bug: prepare statement should throw error when too many parameter…
  pkg/common/moerr/error.go
  pkg/sql/plan/build_dcl.go
Labels: kind/bug, size/S

#14055 [fix] : fix moc2224 and add bvt test
  pkg/container/types/tuple.go
  pkg/sql/compile/fuzzyCheck.go
  test/distributed/cases/dml/insert/insert_duplicate.result
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: kind/bug, size/M

#14059 fix a bug that shuffle on expression cause wrong result
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#14052 remove a context done error at the remote run stage.
  pkg/sql/colexec/server.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/S

#14061 refactor cron tasks
  pkg/taskservice/cron_state.go
  pkg/taskservice/cron_state_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_cron_test.go
Labels: size/L, kind/refactor

#14090 fix bug for file not fuond
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Labels: size/S

#14089 update lazy-load to avoid unnecessary blocking -> 1.1-dev
  pkg/vm/engine/disttae/logtailreplay/partition.go
Labels: kind/bug, size/XS

#14084 fix bug-file-not-found
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Labels: size/S

#14093 Revert "fix bug for file not fuond"
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Labels: size/S

#14075 [enhancement] proxy: change default config value and sql stmt of use.
  pkg/proxy/client_conn.go
  pkg/proxy/config.go
Labels: size/XS, kind/enhancement

#13963 support alter table add partition
  pkg/common/moerr/error.go
  pkg/pb/api/api.go
  pkg/pb/api/api.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/format.go
  pkg/sql/plan/alter_partition_util.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/partition.go
  pkg/sql/plan/partition_hash.go
  pkg/sql/plan/partition_hash_test.go
  pkg/sql/plan/partition_key.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/partition_range.go
  pkg/sql/plan/partition_util.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  proto/api.proto
  proto/plan.proto
  test/distributed/cases/ddl/alter_table_add_partition.result
  test/distributed/cases/ddl/alter_table_add_partition.sql
Labels: kind/feature, size/XL

#14094 fifocache: shard values map
  pkg/fileservice/disk_cache.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/shard.go
  pkg/objectio/cache.go
Labels: size/M, kind/enhancement

#14048 [Feature]: `SubVector` and `ArithemeticOp b/w scalar and vector`
  pkg/sql/plan/function/arithmetic.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/sql/plan/function/functionAgg/algos/kmeans/elkans/clusterer.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/type_check.go
  pkg/vectorize/moarray/external.go
  pkg/vectorize/moarray/external_test.go
  pkg/vectorize/moarray/gonums_utils.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/feature, size/L

#14054 [opt] apply indices for BETWEEN expressions (#13953)
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_layout.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/operator_between.go
  pkg/sql/plan/function/type_check.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/index/zm.go
  test/distributed/cases/operator/between_and_operator.result
  test/distributed/cases/optimizer/pushdown.result
Labels: kind/feature, size/XL

#14103 Refactor cron tasks on 1.1
  pkg/taskservice/cron_state.go
  pkg/taskservice/cron_state_test.go
  pkg/taskservice/task_service.go
  pkg/taskservice/task_service_cron.go
  pkg/taskservice/task_service_cron_test.go
Labels: size/L, kind/refactor

#14097 update default global version interval
  pkg/vm/engine/tae/options/types.go
Labels: kind/bug, size/XS

#14105 fix-cpu-stats
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S, kind/enhancement

#14112 fix bug: should throw err when prepare multi stmt
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#14118 fix various bugs related to index
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/M

#14102 improve stopper performance
  pkg/common/stopper/stopper.go
  pkg/common/stopper/stopper_test.go
Labels: size/M, kind/enhancement

#14109 fix-maxvalue-panic (#13938)
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
Labels: kind/bug, size/XXL

#14115 fix various bugs related to index
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/M

#14056 [fix] : fix moc2224 and add bvt test
  pkg/container/types/tuple.go
  pkg/sql/compile/fuzzyCheck.go
  test/distributed/cases/dml/insert/insert_duplicate.result
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: kind/bug, size/M

#14143 fix bug relate to "invalid file path"
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Labels: size/S

#13889 [Tech Request]: fix stats for values scan
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#14124 fix bug: should throw err when prepare multi stmt (#14112)
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#14121 fileservice: fix DiskCache.DeletePaths
  pkg/fileservice/disk_cache.go
  pkg/fileservice/fifocache/fifo.go
Labels: kind/bug, size/XS

#14142 fix bug relate to invalid file path
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
Labels: size/S

#13999 fix build show columns
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/ddl/mysql_ddl_2.sql
Labels: kind/bug, size/M

#14132 [Bug]: Incorrect explain in bvt with race enabled
  test/distributed/cases/join/leftjoin.result
  test/distributed/cases/join/leftjoin.test
Labels: kind/bug, size/XS

#14153 fix invalid dead lock error
  pkg/txn/client/operator.go
Labels: size/XS

#14126 fix udf python service
  pkg/udf/pythonservice/service.go
  pkg/udf/pythonservice/service_test.go
Labels: kind/bug, size/M

#14162 Revert #14054 and #14118
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/function/func_builtin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_layout.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/operator_between.go
  pkg/sql/plan/function/type_check.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/index/zm.go
  test/distributed/cases/operator/between_and_operator.result
  test/distributed/cases/optimizer/pushdown.result
Labels: kind/feature, size/XL

#14164 cherry pick [Bug]: [date 1.11]tke regression: cn restart, panic error to 1.1-dev
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
Labels: size/S, kind/enhancement

#14098 addNoReservedKeywordCase
  test/distributed/cases/keyword/NoReservedKeyword.result
  test/distributed/cases/keyword/NoReservedKeyword.sql
Labels: kind/bug, size/M

#14134 add page limiter for mo-ctl.object
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/ablk.go
Labels: size/M, kind/enhancement

#14119 [Tech Request]: optimize hash join build batches step 1
  pkg/container/batch/batch.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopmark/join_test.go
  pkg/sql/colexec/loopsemi/join_test.go
  pkg/sql/colexec/loopsingle/join_test.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mark/join_test.go
  pkg/sql/colexec/product/product_test.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/join_test.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/join_test.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/join_test.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/compile/operator.go
Labels: size/L, kind/enhancement

#14133 optimize hash build by not allocate sels for semi/anti
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/right/join_test.go
  pkg/sql/colexec/rightanti/join_test.go
  pkg/sql/colexec/rightsemi/join_test.go
  pkg/sql/colexec/semi/join_test.go
  pkg/sql/colexec/single/join_test.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: size/S, kind/enhancement

#14175 increaset bvt (e2e BVT Test on Linux/x64(LAUNCH)) timeout
  .github/workflows/e2e-standalone.yaml
Labels: kind/bug, size/XS

#13876 only aggr the statement when count is bigger than 1
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_version.result
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/statement_query_type/statement_query_type.result
  test/distributed/cases/statement_query_type/statement_query_type.sql
Labels: kind/bug, size/M, kind/enhancement

#14067 Fix the mesa in workspace
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#14163 [Bug]: [date 1.11]tke regression: cn restart, panic error
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
Labels: kind/bug, size/S

#14176 disable auto create backend automatically in background by default
  pkg/common/morpc/client.go
  pkg/common/morpc/client_test.go
Labels: kind/bug, size/S

#14145 fix: fixed panic when python server cannot be connected
  pkg/udf/pythonservice/client.go
Labels: kind/bug, size/XS

#14177 disable auto create backend automatically in background by default to 1.1
  pkg/common/morpc/client.go
  pkg/common/morpc/client_test.go
Labels: kind/bug, size/S

#13977 refactor merge tool functions
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/mergesort.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/command_test.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeblocks.go
  pkg/vm/engine/tae/tables/txnentries/mergeblockscmd.go
Labels: size/L, kind/enhancement

#14161 add case
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
Labels: kind/bug, size/S

#14116 fileservice: fix aliyun credentials
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/object_storage_arguments.go
Labels: kind/bug, size/M

#14158 fifocache: use xxhash
  pkg/fileservice/disk_cache.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/shard.go
  pkg/objectio/cache.go
Labels: size/S, kind/enhancement

#13923 fix mo_ctl
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate2.go
  pkg/frontend/authenticate2_test.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/M

#14136 Split batch in join
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopanti/types.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsemi/types.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightanti/types.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/rightsemi/types.go
Labels: size/L

#14034 fix lots of unhandled errors.
  pkg/container/batch/batch_test.go
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/objectio/utils.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/table_function/current_account.go
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/generate_series_test.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/function/function_test.go
  pkg/sql/util/eval_expr_util.go
  pkg/testutil/types.go
  pkg/testutil/util_make.go
  pkg/testutil/util_new.go
  pkg/util/export/etl/tae.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/containers/vector.go
Labels: kind/bug, size/XL

#14091 fix-cpu-stats
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S, kind/enhancement

#14201 fix lock table map
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/lock_table_proxy_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
Labels: kind/bug, size/M

#14199 do not break when fetch cron tasks error
  pkg/taskservice/cron_state.go
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/S

#14181 fix object command failed
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/index/zm_test.go
Labels: kind/bug, size/S

#14193 The interface for load metadata adds Release
  pkg/objectio/funcs.go
Labels: size/S, kind/enhancement

#14209 DiskGC may be disturbed when loading stale object stats
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#14214 fix flushblk error handling
  pkg/vm/engine/tae/tables/jobs/flushblk.go
Labels: kind/bug, size/XS

#14202 fix lock table map to 1.1
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/lock_table_keeper_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
Labels: kind/bug, size/M

#14215 fix flush block error handling 1.1
  pkg/vm/engine/tae/tables/jobs/flushblk.go
Labels: kind/bug, size/XS

#14218 pick gc fix to 1.1
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/gc/diskcleaner.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#14189 Add core dump function
  pkg/pb/query/query.pb.go
  pkg/queryservice/coredump.go
  pkg/queryservice/query_service.go
  pkg/sql/plan/function/ctl/cmd_core_dump.go
  pkg/sql/plan/function/ctl/types.go
  pkg/util/core_dump.go
  proto/query.proto
Labels: kind/feature, size/M

#14200 do not break when fetch cron tasks error
  pkg/taskservice/cron_state.go
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/S

#14184 fileservice: s3 fs backports
  go.mod
  go.sum
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/object_storage_arguments.go
Labels: kind/bug, size/M

#14222 cherry pick #14221, load less CKP entries when replay
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/M

#14171 TableScan should merge little batch to reduce operator call
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/table_scan/types.go
Labels: size/S, kind/enhancement

#14188 Pick print more ckp details to 1.1
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: size/M, kind/enhancement

#14220 fix mpool leak in txn.WriteBatch
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14221 load less CKP entries when replay
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/M

#14233 use mo_ctl task method to run task
  pkg/cnservice/server_query.go
  pkg/pb/query/query.pb.go
  pkg/sql/plan/function/ctl/cmd_task.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/types.go
  proto/query.proto
Labels: size/M, kind/enhancement

#14196 fix race
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S

#14217 fix mpool leak in LockMoDatabase
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#14213 Make cluster test framework work
  pkg/cnservice/server.go
  pkg/cnservice/server_cache.go
  pkg/cnservice/server_heartbeat.go
  pkg/logservice/service.go
  pkg/tests/service/cnservice.go
  pkg/tests/service/dnservice.go
  pkg/tests/service/logservice.go
  pkg/tests/service/network.go
  pkg/tests/service/options.go
  pkg/tests/service/options_test.go
  pkg/tests/service/service.go
  pkg/tests/service/service_test.go
Labels: size/S, kind/test-ci

#14207 fix: desc table key error
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/ddl/alter_table_add_drop_constraint.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/mysql_ddl_2.result
  test/distributed/cases/ddl/mysql_ddl_2.sql
Labels: kind/bug, size/M

#14232 add getPkExpr unit test
  pkg/sql/plan/make.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/M, kind/test-ci

#14210 [opt] avoid reading original table if index contains all needed columns
  pkg/frontend/authenticate.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/runtime_filter.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/marshal_model.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  proto/plan.proto
Labels: kind/feature, size/M

#14223 Start tasks by mo_ctl
  pkg/cnservice/server_query.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/query_service.go
  pkg/sql/plan/function/ctl/cmd_task.go
  pkg/taskservice/task_ctl.go
  pkg/taskservice/task_ctl_test.go
  pkg/taskservice/task_runner.go
  pkg/taskservice/types.go
  proto/query.proto
Labels: size/M, kind/enhancement

#14237 adding RWMutex to avoid concurrent map write
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14243 fix bind changed not handled to 1.1
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/pb/lock/lock.go
Labels: kind/bug, size/S

#14246 update trigger times before write to async task
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/XS

#14238 sync to 1.1: adding RWMutex to avoid concurrent map write
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#14229 update table tail column names, cherry-pick #14227
  pkg/catalog/types.go
  pkg/sql/plan/build_util.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/utils.go
Labels: kind/bug, size/S

#14244 fix bind changed not handled
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
  pkg/pb/lock/lock.go
Labels: kind/bug, size/S

#14249 fix mpool leak in LockMoDatabase (#14217)
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/S

#14253 sync to 1.1: augment the hakeeperDefaultTimeout in ut to avoid TestHAKeeperCanBootstrapAndRepairShards failed
  pkg/logservice/store_hakeeper_check.go
  pkg/logservice/store_hakeeper_check_test.go
Labels: kind/bug, size/S

#14227 update table tail column names
  pkg/catalog/types.go
  pkg/sql/plan/build_util.go
  pkg/vm/engine/tae/catalog/model.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/txn_handle.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/utils.go
Labels: kind/bug, size/S

#14250 fix mpool leak in txn.WriteBatch (#14220)
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S
