Repository matrixorigin/matrixone, pull requests merged in 2024-05, with the labels that each got.

#15804 fix gc catalog
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/replay.go
Labels: kind/bug, size/S

#15818 consider original size to merge
  pkg/pb/api/api.pb.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/task.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/common/stats.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/rpc/inspect.go
  proto/api.proto
  test/distributed/cases/function/mo_ctl/mo_ctl_merge.result
Labels: size/M, kind/enhancement

#15826 rm handle metadata delete
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/bug, size/S

#15817 add Information System View Tenant Isolation cases
  test/distributed/cases/zz_accesscontrol/inner_object.result
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/feature, size/M

#15685 move pebble skiplist to mo and make it easy to use
  .licenserc.yml
  pkg/common/arenaskl/LICENSE
  pkg/common/arenaskl/README.md
  pkg/common/arenaskl/arena.go
  pkg/common/arenaskl/arena_test.go
  pkg/common/arenaskl/iterator.go
  pkg/common/arenaskl/node.go
  pkg/common/arenaskl/skl.go
  pkg/common/arenaskl/skl_test.go
  pkg/common/fastrand/fastrand.go
  pkg/common/fastrand/fastrand_test.go
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
Labels: kind/feature, size/XXL

#15824 DiskCleaner replay add Init snapshot table info op
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/M

#15828 Add backup parallel&retry
  pkg/backup/backup.go
  pkg/backup/backup_test.go
  pkg/backup/fs.go
  pkg/backup/tae.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/logtail/backup.go
Labels: size/M, kind/enhancement

#15786 [fix] error caused by parallel slicing in load data
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/compile.go
  pkg/sql/util/csvparser/csv_parser.go
Labels: kind/bug, size/M

#14774 optimize select count(*)
  pkg/sql/compile/compile.go
  pkg/sql/plan/base_binder.go
Labels: size/S

#15857 dump core if no txn found during prepare commit
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/S

#15846 Add write sync error info
  pkg/objectio/writer.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, kind/enhancement

#15860 change force checkpoint timeout time from 1min to 1.5min
  pkg/vm/engine/tae/db/db.go
Labels: kind/bug, size/XS

#15836 handle errors during merge properly
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/mergesort/aobj_merger.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: kind/bug, size/M

#15539 Expand column in the mo_account table
  pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/version.go
  pkg/frontend/authenticate.go
  pkg/frontend/system_initialize.go
  pkg/sql/plan/function/func_get_admin.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/database/system_variables.result
  test/distributed/cases/dml/insert/insert_ignore.result
  test/distributed/cases/dml/insert/insert_ignore.sql
  test/distributed/cases/dml/show/database_statistics.result
Labels: kind/feature, size/M

#15851 [enhancement] proxy: use the global unique logger in all sessions
  pkg/proxy/router.go
  pkg/proxy/router_test.go
  pkg/proxy/server_conn.go
Labels: size/S, kind/enhancement

#15859 update default incr cache size to 10000
  pkg/incrservice/cfg.go
Labels: size/XS, kind/enhancement

#15871 fix policy name parse
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#15832 fix adding transfer pages in empty merge tasks
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: kind/bug, size/S

#15791 support database operator In transactions
  pkg/frontend/stmt_kind.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  test/distributed/cases/optimistic/atomicity_1.result
  test/distributed/cases/optimistic/autocommit_1.result
  test/distributed/cases/optimistic/isolation_2.result
  test/distributed/cases/optimistic/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/database_operator.result
  test/distributed/cases/pessimistic_transaction/database_operator.sql
  test/distributed/cases/pessimistic_transaction/isolation_2.result
  test/distributed/cases/pessimistic_transaction/isolation_2.sql
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/statement_query_type/statement_query_type_1.result
Labels: kind/feature, size/L

#15874 [fix] error caused by parallel load
  pkg/sql/colexec/external/external.go
  pkg/sql/util/csvparser/csv_parser.go
Labels: kind/bug, do-not-merge/wip, size/XS

#15735 Format mo catalog system view
  pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/util/util.go
  pkg/util/sysview/sysview.go
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/pessimistic_transaction/catalog.result
  test/distributed/cases/pessimistic_transaction/catalog.sql
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/M

#15863 malloc: fix mimalloc and use v2.1.4 version
  pkg/common/malloc/malloc.go
  pkg/common/malloc/mimalloc/LICENSE
  pkg/common/malloc/mimalloc/alloc-aligned.c
  pkg/common/malloc/mimalloc/alloc.c
  pkg/common/malloc/mimalloc/arena.c
  pkg/common/malloc/mimalloc/bitmap.c
  pkg/common/malloc/mimalloc/bitmap.h
  pkg/common/malloc/mimalloc/free.c
  pkg/common/malloc/mimalloc/heap.c
  pkg/common/malloc/mimalloc/init.c
  pkg/common/malloc/mimalloc/mimalloc.h
  pkg/common/malloc/mimalloc/mimalloc/internal.h
  pkg/common/malloc/mimalloc/mimalloc/prim.h
  pkg/common/malloc/mimalloc/mimalloc/types.h
  pkg/common/malloc/mimalloc/options.c
  pkg/common/malloc/mimalloc/os.c
  pkg/common/malloc/mimalloc/page-queue.c
  pkg/common/malloc/mimalloc/page.c
  pkg/common/malloc/mimalloc/prim/unix/prim.c
  pkg/common/malloc/mimalloc/segment.c
  pkg/common/malloc/mimalloc/stats.c
Labels: size/XXL, kind/enhancement

#15873 support incremental backup in parser
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/backup.go
Labels: kind/feature, size/XXL

#15882 sort out the code to make it less prone to data race
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/updates/chain_test.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
  pkg/vm/engine/tae/txn/txnimpl/antidepend.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/object.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/sysobject.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
Labels: size/M, kind/refactor

#15889 fix dead lock
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: size/XS

#15899 fix wrong usage of vector.PreExtend
  pkg/container/vector/functionTool_test.go
  pkg/container/vector/functionTools.go
  pkg/sql/colexec/aggexec/aggResult.go
  pkg/sql/colexec/external/external.go
Labels: size/S, kind/enhancement

#15890 fix data race
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/tables/updates/delchain.go
Labels: size/S

#15853 [enhancement] util: use new method to check if the port is available
  pkg/util/address/address.go
Labels: size/S, kind/enhancement

#15898 add md5 and sha cases
  test/distributed/cases/function/func_md5.result
  test/distributed/cases/function/func_md5.sql
  test/distributed/cases/function/func_sha1.result
  test/distributed/cases/function/func_sha1.sql
Labels: kind/feature, size/M

#15886 [BugFix]: Normalize_L2 Optimization
  pkg/vectorize/moarray/external.go
  test/distributed/cases/array/array_index.result
Labels: kind/bug, size/S

#15900 fix the UT `TestAll`
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/db.go
Labels: kind/bug, size/S

#15881 fix ut failed about race
  pkg/frontend/authenticate.go
  pkg/frontend/back_exec.go
  pkg/frontend/connector.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/routine_test.go
  pkg/frontend/server.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/show_account.go
  pkg/frontend/show_subsriptions.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/proxy/client_conn.go
Labels: kind/bug, size/XXL

#15903 malloc: re-apply reverted go managed allocator
  pkg/common/malloc/bench_test.go
  pkg/common/malloc/handle.go
  pkg/common/malloc/malloc.go
  pkg/common/malloc/malloc_test.go
  pkg/common/malloc/mimalloc/alloc-aligned.c
  pkg/common/malloc/mimalloc/alloc-override.c
  pkg/common/malloc/mimalloc/alloc-posix.c
  pkg/common/malloc/mimalloc/alloc.c
  pkg/common/malloc/mimalloc/arena.c
  pkg/common/malloc/mimalloc/bitmap.c
  pkg/common/malloc/mimalloc/bitmap.h
  pkg/common/malloc/mimalloc/free.c
  pkg/common/malloc/mimalloc/heap.c
  pkg/common/malloc/mimalloc/init.c
  pkg/common/malloc/mimalloc/libc.c
  pkg/common/malloc/mimalloc/mimalloc-new-delete.h
  pkg/common/malloc/mimalloc/mimalloc-override.h
  pkg/common/malloc/mimalloc/mimalloc.h
  pkg/common/malloc/mimalloc/mimalloc/atomic.h
  pkg/common/malloc/mimalloc/mimalloc/internal.h
  pkg/common/malloc/mimalloc/mimalloc/prim.h
  pkg/common/malloc/mimalloc/mimalloc/track.h
  pkg/common/malloc/mimalloc/mimalloc/types.h
  pkg/common/malloc/mimalloc/options.c
  pkg/common/malloc/mimalloc/os.c
  pkg/common/malloc/mimalloc/page-queue.c
  pkg/common/malloc/mimalloc/page.c
  pkg/common/malloc/mimalloc/prim/emscripten/prim.c
  pkg/common/malloc/mimalloc/prim/osx/alloc-override-zone.c
  pkg/common/malloc/mimalloc/prim/osx/prim.c
  pkg/common/malloc/mimalloc/prim/prim.c
  pkg/common/malloc/mimalloc/prim/readme.md
  pkg/common/malloc/mimalloc/prim/unix/prim.c
  pkg/common/malloc/mimalloc/prim/wasi/prim.c
  pkg/common/malloc/mimalloc/prim/windows/etw-mimalloc.wprp
  pkg/common/malloc/mimalloc/prim/windows/etw.h
  pkg/common/malloc/mimalloc/prim/windows/etw.man
  pkg/common/malloc/mimalloc/prim/windows/prim.c
  pkg/common/malloc/mimalloc/prim/windows/readme.md
  pkg/common/malloc/mimalloc/random.c
  pkg/common/malloc/mimalloc/segment-map.c
  pkg/common/malloc/mimalloc/segment.c
  pkg/common/malloc/mimalloc/static.c
  pkg/common/malloc/mimalloc/stats.c
  pkg/fileservice/memorycache/data_alloc_free.go
  pkg/fileservice/memorycache/data_alloc_free_tracing.go
  pkg/fileservice/memorycache/refcnt.go
  pkg/fileservice/memorycache/refcnt_tracing.go
  pkg/fileservice/memorycache/types.go
Labels: size/XXL, kind/enhancement

#15896 Fix BLKCNMetaInsertIDX panic
  pkg/vm/engine/tae/logtail/backup.go
Labels: kind/bug, size/XS

#15905 increase flush priority for dropped tables
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/options/options.go
Labels: size/S, kind/enhancement

#15880 [enhancement] change timeout from 30s to 5m in SyncLatestCommitTS
  pkg/txn/client/client.go
Labels: size/XS, kind/enhancement

#15894 add log
  pkg/hakeeper/task/task_scheduler.go
Labels: size/XS, kind/enhancement

#15915 add base64 and md5 functions cases
  test/distributed/cases/function/func_encode_decode.result
  test/distributed/cases/function/func_encode_decode.sql
  test/distributed/cases/function/func_md5.result
  test/distributed/cases/function/func_md5.sql
  test/distributed/cases/function/func_sha1.result
  test/distributed/cases/function/func_sha1.sql
Labels: kind/feature, size/S

#15919 [bug] proxy: too many logs in proxy
  pkg/proxy/client_conn.go
  pkg/proxy/conn_manager.go
  pkg/proxy/handshake.go
  pkg/proxy/router.go
  pkg/proxy/server_conn.go
  pkg/proxy/server_conn_test.go
Labels: kind/bug, size/S

#15910 [Performance]: tune ap cache policy
  pkg/vm/engine/disttae/reader.go
Labels: kind/bug, size/XS

#15777 fix set global var not effect
  go.mod
  go.sum
  pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/show_subscriptions_test.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  pkg/sql/compile/ddl_index_algo.go
  test/distributed/cases/database/select_origin.result
  test/distributed/cases/database/select_origin.sql
  test/distributed/cases/database/set_keep_user_target.result
  test/distributed/cases/database/set_keep_user_target.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/publication_subscription/pub_sub_improvment.sql
Labels: kind/bug, size/XL

#15892 [bug] remove the timeout parameter to avoid the wrong check result.
  pkg/util/address/address.go
Labels: kind/bug, size/XS

#15823 improvement reuse, change from using string to type to get pool
  pkg/common/reuse/factory.go
  pkg/common/reuse/pool_test.go
  pkg/common/reuse/types.go
Labels: size/S, kind/enhancement

#15866 disttae: cache result of GetTableById in PartitionState
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
Labels: size/S, kind/enhancement

#15924 [BugFix]: FROM_BASE64 return NULL if throws error
  pkg/sql/plan/function/func_unary.go
  test/distributed/cases/function/func_encode_decode.result
  test/distributed/cases/function/func_encode_decode.sql
Labels: kind/bug, size/S

#15940 Revert "fix set global var not effect (#15777)"
  go.mod
  go.sum
  pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/query_result_test.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/show_subscriptions_test.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
  pkg/sql/compile/ddl_index_algo.go
  test/distributed/cases/database/select_origin.result
  test/distributed/cases/database/select_origin.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/publication_subscription/pub_sub_improvment.sql
  test/distributed/cases/set/set_keep_user_target.result
  test/distributed/cases/set/set_keep_user_target.sql
Labels: size/XL

#15716 accept multiple arguments for AND/OR implementation
  pkg/sql/plan/function/list_operator.go
  pkg/sql/plan/function/logicalOperator.go
Labels: size/M, kind/enhancement

#15906 use decimal256 in CalculateCU
  pkg/container/types/decimal.go
  pkg/util/trace/impl/motrace/cu.go
Labels: size/S

#15729 Format mo catalog system view1.1 dev
  pkg/cnservice/upgrader/new_add_table.go
  pkg/frontend/authenticate.go
  pkg/sql/util/util.go
  test/distributed/cases/pessimistic_transaction/catalog.result
  test/distributed/cases/pessimistic_transaction/catalog.sql
Labels: kind/bug, size/M

#15902 [impr] : add `strict` field to control whether do the valid check
  pkg/sql/colexec/external/external.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/update.go
Labels: kind/bug, size/XXL, kind/enhancement

#15937 [#15936]fix bug for snapshot read
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
Labels: size/S

#15942 Record exec_plan consider txn wait-active cost
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/util_test.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/trace/impl/motrace/report_log_test.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
  pkg/util/trace/impl/motrace/trace.go
  pkg/vm/engine/entire_engine_test.go
Labels: kind/feature, size/M

#15931 modify some case and remove bvt tag
  test/distributed/cases/publication_subscription/pub_sub.result
  test/distributed/cases/publication_subscription/pub_sub.sql
  test/distributed/cases/publication_subscription/pub_sub_improvment.result
  test/distributed/cases/publication_subscription/pub_sub_improvment.sql
Labels: kind/bug, size/M

#15948 Fix block does not consume bug
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
Labels: kind/bug, size/XS

#15927 force index join on one cn
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#15908 clean txn
  .gitignore
  pkg/cnservice/server_query.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate2.go
  pkg/frontend/authenticate2_test.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_self_handle.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/backup.go
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/connector.go
  pkg/frontend/export.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/output.go
  pkg/frontend/output_test.go
  pkg/frontend/plsql_interpreter.go
  pkg/frontend/protocol.go
  pkg/frontend/query_result.go
  pkg/frontend/query_result_test.go
  pkg/frontend/resp_client.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/routine_test.go
  pkg/frontend/self_handle.go
  pkg/frontend/session.go
  pkg/frontend/session_test.go
  pkg/frontend/show_account.go
  pkg/frontend/show_subscriptions_test.go
  pkg/frontend/show_subsriptions.go
  pkg/frontend/snapshot.go
  pkg/frontend/status_stmt.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/task.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  pkg/proxy/server_conn_test.go
  pkg/sql/compile/compile.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/parsers/tree/update.go
Labels: kind/feature, size/XXL, kind/enhancement

#15945 fix some bugs in mo-debug tool
  cmd/mo-debug/goroutine.go
  pkg/util/debug/goroutine/types.go
Labels: kind/bug, size/S

#15944 fix hung by dump locks
  pkg/lockservice/service_observability.go
Labels: kind/bug, size/S

#15934 add make musl and upgrade kafka package version
  .github/mergify.yml
  Makefile
  go.mod
  go.sum
  pkg/util/metric/m_hardware.go
  pkg/util/metric/m_process.go
  pkg/util/metric/m_utills.go
Labels: size/M, kind/test-ci

#15938 clean catalog codes
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: size/XL, kind/enhancement

#15914 fix Bvt case in issue 14836
  test/distributed/cases/log/query_version.result
  test/distributed/cases/log/query_version.sql
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
  test/distributed/cases/zz_statement_query_type/query_version.result
  test/distributed/cases/zz_statement_query_type/query_version.sql
  test/distributed/cases/zz_statement_query_type/sql_source_type.result
  test/distributed/cases/zz_statement_query_type/sql_source_type.sql
Labels: kind/bug, size/S

#15913 Print tn config when opening and replace numCPU with procs
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/S, kind/enhancement

#15957 [subtask] : let preinsert can get outcnt from stats
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/preinsert/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: size/S, kind/enhancement

#15930 fix HasCommittedPersistedData
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
Labels: kind/bug, size/S

#15966 fix Bvt case in issue 14836 in 1.2
  test/distributed/cases/log/query_version.result
  test/distributed/cases/log/query_version.sql
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/sql_source_type/sql_source_type.result
  test/distributed/cases/sql_source_type/sql_source_type.sql
  test/distributed/cases/zz_statement_query_type/query_version.result
  test/distributed/cases/zz_statement_query_type/query_version.sql
  test/distributed/cases/zz_statement_query_type/sql_source_type.result
  test/distributed/cases/zz_statement_query_type/sql_source_type.sql
Labels: kind/bug, size/S

#15925 Predefine system table as global var
  pkg/bootstrap/service.go
  pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/predefined.go
  pkg/util/sysview/predefined.go
  pkg/util/sysview/sysview.go
Labels: size/XXL, kind/enhancement

#15941 fix bug: incorrect row count for value scan node
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: kind/bug, size/XS

#15970 cp catalog and options change to 1.2
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/base_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
Labels: size/XL, kind/enhancement

#15955 Support mo_logger disable ErrorCollection
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/types_mock.go
  pkg/util/errutil/context.go
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/trace.go
Labels: kind/feature, size/S

#15978 Support mo_logger disable ErrorCollection in 1.2
  pkg/config/configuration.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/test/types_mock.go
  pkg/util/errutil/context.go
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/trace.go
Labels: kind/feature, size/S

#15893 remove bvt tag of snapshot read
  test/distributed/cases/snapshot/snapshot_read.sql
  test/distributed/cases/snapshot/snapshot_read_1.sql
  test/distributed/cases/snapshot/snapshot_read_2.sql
  test/distributed/cases/snapshot/snapshot_read_3.sql
Labels: size/XS, kind/test-ci

#15981 fix index table merge too much on 1.2
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/vm/engine/tae/db/merge/executor.go
Labels: kind/bug, size/S

#15980 fix index table merge too much
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/vm/engine/tae/db/merge/executor.go
Labels: kind/bug, size/S

#15986 force index join on one cn
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/opt_misc.go
  test/distributed/cases/optimizer/pushdown.result
Labels: kind/bug, size/S

#15987 Predefine system table as global var (#15925)
  pkg/bootstrap/service.go
  pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v1_2_0/tenant_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/predefined.go
  pkg/util/sysview/predefined.go
  pkg/util/sysview/sysview.go
Labels: size/XXL, kind/enhancement

#15992 Fix the bug of losing deltaLoc when doing checkpoint
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/XS

#15999 fix drop database failure
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/bug, size/S

#15989 fix bug: incorrect row count for value scan node (#15941)
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: kind/bug, size/XS

#15995 improve incr service pre allocate
  pkg/incrservice/service.go
  pkg/incrservice/table_cache.go
  pkg/incrservice/types.go
  pkg/sql/colexec/preinsert/preinsert.go
Labels: size/S, kind/enhancement

#15983 move some logic from compile to run
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/limit/limit_test.go
  pkg/sql/colexec/limit/types.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergelimit/types.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergeoffset/types.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/offset/offset_test.go
  pkg/sql/colexec/offset/types.go
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/top/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRun_test.go
  pkg/sql/compile/types.go
  pkg/sql/plan/build_load.go
  proto/pipeline.proto
Labels: size/L, kind/refactor

#15993 Fix the bug of losing deltaLoc when doing checkpoint for 1.2
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/XS

#15990 force index join on one cn
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/opt_misc.go
  test/distributed/cases/optimizer/pushdown.result
Labels: kind/bug, size/S

#16000 fix drop database failure
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: kind/bug, size/S

#15965 fix HasCommittedPersistedData, cherry-pick #15930
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/updates/delchain.go
  pkg/vm/engine/tae/txn/txnbase/mvccchain.go
Labels: kind/bug, size/S

#15985 add quote to dbname when drop account
  pkg/frontend/authenticate.go
  test/distributed/cases/zz_accesscontrol/drop_account.result
  test/distributed/cases/zz_accesscontrol/drop_account.sql
Labels: size/S, kind/enhancement

#16004 [cherry-pick-15957] : let preinsert can get outcnt from stats
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/preinsert/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: size/S, kind/enhancement

#16014 fix hung
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session.go
Labels: kind/bug, size/S

#16011 Restore bootstrap to establish index code for mo-task
  pkg/bootstrap/service.go
  pkg/frontend/predefined.go
Labels: size/S, kind/enhancement

#16012 Restore bootstrap to establish index code for mo-task
  pkg/bootstrap/service.go
  pkg/frontend/predefined.go
Labels: size/S, kind/enhancement

#16016 fix argument type of prefix_in
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#16015 fix hung
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session.go
Labels: kind/bug, size/S

#16017 add error log in taskservice
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/task_service.go
Labels: size/S, kind/enhancement

#16018 add error log in taskservice
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/task_service.go
Labels: size/S, kind/enhancement

#16003 [bug] fix ut TestAddressManager
  pkg/proxy/handler.go
  pkg/util/address/address.go
  pkg/util/address/address_test.go
Labels: kind/bug, size/S

#16020 improve incr service to 1.2
  pkg/incrservice/service.go
  pkg/incrservice/table_cache.go
  pkg/incrservice/types.go
  pkg/sql/colexec/preinsert/preinsert.go
Labels: size/S, kind/enhancement

#16025 add dump profile
  cmd/mo-service/main.go
  pkg/cnservice/server.go
Labels: kind/feature, size/S, kind/enhancement

#16024 add quote to dbname when drop account (#1.2-dev)
  pkg/frontend/authenticate.go
  test/distributed/cases/zz_accesscontrol/drop_account.result
  test/distributed/cases/zz_accesscontrol/drop_account.sql
Labels: kind/bug, size/S

#16030 sync to 1.2: fix `ForceCheckpoint` retry logic.
  pkg/vm/engine/tae/db/db.go
Labels: kind/bug, size/XS

#15994 Fix bug for snapshot-read
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/M

#16029 fix `ForceCheckpoint` retry logic.
  pkg/vm/engine/tae/db/db.go
Labels: kind/bug, size/XS

#16023 [cherry-pick] fix argument type of prefix_in
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#15949 add snapshot read case
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/snapshot/snapshotRead.sql
Labels: kind/feature, size/XL

#16026 add dump profile
  cmd/mo-service/main.go
  pkg/cnservice/server.go
Labels: kind/feature, size/S, kind/enhancement

#15870 remove bvt tag of snapshot restore
  test/distributed/cases/snapshot/snapshot.sql
  test/distributed/cases/snapshot/snapshot_restore_account_level.result
  test/distributed/cases/snapshot/snapshot_restore_account_level.sql
  test/distributed/cases/snapshot/snapshot_restore_database_level.sql
  test/distributed/cases/snapshot/snapshot_restore_table_level.sql
Labels: size/S, kind/test-ci

#15713 [Bug]: pipeline client max connections is too large
  pkg/cnservice/cnclient/client.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/XS

#16040 fix parse oom
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#16041 fix parse oom
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
Labels: kind/bug, size/S

#16036 retry for first lock table bind change
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: size/M

#16045 Revert "[Bug]: pipeline client max connections is too large (#15713)"
  pkg/cnservice/cnclient/client.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes.go
Labels: kind/bug, size/XS

#16033 Fix bug for snapshot-read(1.2-dev)
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/snapshot/snapshot.sql
  test/distributed/cases/snapshot/snapshot_read.sql
  test/distributed/cases/snapshot/snapshot_read_1.sql
  test/distributed/cases/snapshot/snapshot_read_2.sql
  test/distributed/cases/snapshot/snapshot_read_3.sql
  test/distributed/cases/snapshot/snapshot_restore_account_level.sql
  test/distributed/cases/snapshot/snapshot_restore_database_level.sql
  test/distributed/cases/snapshot/snapshot_restore_table_level.sql
Labels: kind/bug, size/M

#16050 add leak config to mergerun cn
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci

#16052 add leak config to mergerun cn for 1.2-dev
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci

#16056 fix test delete3, cherry-pick #16054
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#16002 [bug] fix ut TestAddressManager
  pkg/proxy/handler.go
  pkg/util/address/address.go
  pkg/util/address/address_test.go
Labels: kind/bug, size/S

#16054 fix test delete3
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#16071 fix wrong txn status
  pkg/frontend/result_row_stmt.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/S

#15961 Fix flush deletes
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/updates/delchain.go
Labels: kind/bug, size/S

#16060 Fix flush deletes, cherry-pick #15961
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/updates/delchain.go
Labels: kind/bug, size/S

#16064 add snapshot read test for tpch
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.result
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.sql
Labels: size/XXL, kind/test-ci

#16065 add case for snapshot br
  test/distributed/cases/snapshot/nonsys_restore_to_nonsys_account.result
  test/distributed/cases/snapshot/nonsys_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_to_newnonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.result
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_to_sys_account.sql
Labels: kind/feature, size/XXL

#16019 change use workflow branch
  .github/workflows/entrypoint.yaml
  .github/workflows/image-build.yml
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
  .github/workflows/release.yml
  .github/workflows/robot.yml
Labels: kind/test-ci

#15827 [feat] Load parquet files, indexed string
  pkg/sql/colexec/external/parquet.go
  pkg/sql/colexec/external/parquet_test.go
  test/distributed/cases/load_data/load_data_parquet.result
  test/distributed/cases/load_data/load_data_parquet.sql
  test/distributed/resources/load_data/indexed_str.parq
Labels: kind/feature, size/L

#16069 fix wrong txn status
  pkg/frontend/result_row_stmt.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/txn.go
Labels: kind/bug, size/S

#16044 Support not deleting the checkpoint referenced by the snapshot
  pkg/vm/engine/tae/db/checkpoint/snapshot.go
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/M

#16032 retry for first lock table bind change
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: size/M

#16072 fix snapshot read with addtion data
  pkg/sql/compile/operator.go
  test/distributed/cases/snapshot/snapshot_read_incremental_data.result
  test/distributed/cases/snapshot/snapshot_read_incremental_data.sql
Labels: kind/bug, size/M

#16087 fileservice: add error messages to IsRetryableError
  pkg/fileservice/error.go
Labels: size/S, kind/enhancement

#16068 fix bvt query_tae_table in 1.2
  test/distributed/cases/log/query_stmt.result
  test/distributed/cases/log/query_stmt.sql
  test/distributed/cases/log/query_tae_table.result
  test/distributed/cases/log/query_tae_table.sql
  test/distributed/cases/zz_statement_query_type/query_stmt.result
  test/distributed/cases/zz_statement_query_type/query_stmt.sql
Labels: kind/bug, size/M, kind/test-ci

#16084 clean some unused parameter in hash build
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRun_test.go
Labels: kind/bug, size/S

#16094 add log of profile
  cmd/mo-service/main.go
Labels: size/XS, kind/enhancement

#16077 sync to 1.2: adding in filter for the partition state rows scan
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/disttae_filters/ranges_filters/ranges_filters.result
  test/distributed/cases/disttae_filters/ranges_filters/ranges_filters.sql
  test/distributed/cases/disttae_filters/reader_filters/partition_state_primary_key_index_filter.result
  test/distributed/cases/disttae_filters/reader_filters/partition_state_primary_key_index_filter.sql
Labels: size/M, kind/enhancement

#16089 fix spare mem in container
  go.mod
  go.sum
  pkg/vm/engine/tae/db/merge/executor.go
Labels: kind/bug, size/S

#16073 [Feature] support view on snapshot
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/snapshot.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/tree/insert.go
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/vm/engine/memoryengine/compiler_context.go
  proto/plan.proto
  test/distributed/cases/snapshot/snapshot_restore_view.result
  test/distributed/cases/snapshot/snapshot_restore_view.sql
Labels: kind/feature, size/XL

#15877 refactor mo logging for rawlog and statement_info
  pkg/bootstrap/versions/v1_2_0/cluster_upgrade_list.go
  pkg/frontend/authenticate.go
  pkg/frontend/back_exec.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/export.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/output.go
  pkg/frontend/plsql_interpreter.go
  pkg/frontend/protocol.go
  pkg/frontend/query_result.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/status_stmt.go
  pkg/frontend/txn.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/logutil/dragonboat.go
  pkg/logutil/fields.go
  pkg/logutil/internal.go
  pkg/logutil/internal_test.go
  pkg/logutil/report_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRun.go
  pkg/sql/compile/scopeRemoteRunTypes.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/context.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/report_log.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  pkg/util/trace/impl/motrace/schema.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  proto/pipeline.proto
  test/distributed/cases/dml/show/database_statistics.result
Labels: kind/feature, size/L

#16109 add trigger condition for mergerun
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#16110 add trigger condition for mergerun for 1.2 dev
  .github/workflows/merge-trigger-standalone.yaml
  .github/workflows/merge-trigger-tke.yaml
Labels: kind/test-ci

#16103 remove unused bucket logic in hash table
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/inthashmap_test.go
  pkg/common/hashmap/iterator.go
  pkg/common/hashmap/joinmap.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/common/hashmap/types.go
  pkg/container/hashtable/bucket.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersect/types.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/intersectall/types.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/minus/types.go
  pkg/sql/colexec/sample/sample.go
  pkg/sql/colexec/sample/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scopeRemoteRun.go
  proto/pipeline.proto
Labels: size/L, kind/enhancement

#16066 refactor messageBoard to support listening on context.Done
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/compile/scope.go
  pkg/vm/process/message.go
  pkg/vm/process/runtimeFilterMsg.go
Labels: kind/bug, size/S

#16105 improve cn merge and reuse sort code
  pkg/sort/sort.go
  pkg/sql/colexec/merge_util.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/tae/mergesort/aobj_merger.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/mergesort_test.go
  pkg/vm/engine/tae/mergesort/types.go
Labels: size/M, kind/enhancement

#16113 adding `prefix_eq` filter for the partition state rows scan
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
Labels: size/M, kind/enhancement

#16095 add log of profile
  cmd/mo-service/main.go
Labels: size/XS, kind/enhancement

#16115 sync to 1.2: adding prefix_eq filter for the partition state rows scan
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
Labels: size/M, kind/enhancement

#16081 add metadata check
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/check_metadata.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/feature, size/M

#16082 [feat] Load parquet files, indexed string (#1.2-dev)
  pkg/sql/colexec/external/parquet.go
  pkg/sql/colexec/external/parquet_test.go
  test/distributed/cases/load_data/load_data_parquet.result
  test/distributed/cases/load_data/load_data_parquet.sql
  test/distributed/resources/load_data/indexed_str.parq
Labels: kind/bug, size/L

#16092 fix spare mem in container (main)
  go.mod
  go.sum
  pkg/vm/engine/tae/db/merge/executor.go
Labels: kind/bug, size/S

#16133 fileservice: ignore not found error in FileService.Delete
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: size/S, kind/enhancement

#16134 fileservice: ignore not found error in FileService.Delete
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
Labels: size/S, kind/enhancement

#16140 fix del map error after merge
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/hidden_test.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: kind/bug, size/M

#16142 fix snapshot read with addtion data(#1.2-dev)
  pkg/sql/compile/operator.go
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.result
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/01_DROP.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/02_Snapshot.sql
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.result
  test/distributed/cases/benchmark/tpch/04_CLEANUP/03_Snapshot_tpch.sql
  test/distributed/cases/snapshot/snapshot_read_incremental_data.result
  test/distributed/cases/snapshot/snapshot_read_incremental_data.sql
Labels: kind/bug, size/XXL

#16148 [bug] proxy: when sequence id is rotated, there may be a wrong ok packet
  pkg/proxy/tunnel.go
Labels: kind/bug, size/S
