Repository matrixorigin/matrixone, pull requests merged in 2024-08, with the labels that each got.

#17774 Handle data race when get table def
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#17802 Session disable agg stmt
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  test/distributed/cases/result_count/result_count.result
  test/distributed/cases/result_count/result_count.sql
  test/distributed/cases/statement_query_type/statement_query_type_1.result
  test/distributed/cases/statement_query_type/statement_query_type_1.sql
  test/distributed/cases/zz_statement_query_type/result_count.result
  test/distributed/cases/zz_statement_query_type/result_count.sql
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.result
  test/distributed/cases/zz_statement_query_type/statement_query_type_1.sql
Labels: kind/bug, size/M

#17799 fileservice: add active reader metrics to object storage
  pkg/fileservice/object_storage_metrics.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
Labels: size/S, kind/enhancement

#17779 More constant fold for expression executor
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_regular_substr.result
Labels: size/M, kind/enhancement

#17836 cp to 1.2-dev 'adjust reuse leak check (#17669)'
  pkg/common/reuse/sync_pool_based.go
Labels: size/S, kind/enhancement

#17812 Fix databaseIsValid
  pkg/sql/plan/utils.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/S

#17795 Mo inspect checkpoint command
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/tool.go
Labels: kind/feature, size/L, Enhancement, Review effort [1-5]: 4, Feature

#17734 Reduce transfer page memory usage on 1.2 dev
  pkg/objectio/name.go
  pkg/objectio/writer.go
  pkg/pb/api/api.go
  pkg/pb/api/api.pb.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/blockio/types.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  proto/api.proto
Labels: size/M

#17837 [Cherry-pick] fix databaseIsValid
  pkg/sql/plan/utils.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/S

#17840 [pick to 1.2] support idempotence for batch Clean method and process PutBatch method
  pkg/container/batch/batch.go
  pkg/vm/process/process.go
Labels: kind/bug, size/S

#17826 Fix show double type definition when scale = 0
  pkg/sql/plan/build_show_util.go
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S

#17794 add sql length metric
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/frontend.go
  pkg/util/metric/v2/metrics.go
Labels: kind/bug, size/S, kind/enhancement

#17827 [Cherry-pick] Fix show double type definition when scale = 0
  pkg/sql/plan/build_show_util.go
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S

#17791 delete committing txn state log
  pkg/lockservice/lock_table_allocator.go
Labels: size/XS

#17838 support idempotence for batch's Clean method
  pkg/container/batch/batch.go
  pkg/vm/process/process2.go
Labels: size/S, kind/enhancement

#17809 [bug] stats: fix nil pointer in partition table that is newly created.
  pkg/vm/engine/disttae/stats.go
Labels: size/XS

#17829 fix merge scope in shuffle join probe side
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/S, kind/refactor

#17776 Refactor dml node compilation for analyze
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertunique/preinsertunique.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/unionall/types.go
  pkg/sql/colexec/unionall/union.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/vm/types.go
  proto/pipeline.proto
Labels: kind/feature, size/M

#17755 Make sels int64
  pkg/container/vector/search.go
  pkg/container/vector/utils_test.go
  pkg/container/vector/vector.go
  pkg/embed/cluster_test.go
  pkg/objectio/utils.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/types.go
  pkg/sql/plan/function/func_unary.go
  pkg/vm/engine/disttae/pk_filter.go.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/containers/vector.go
  pkg/vm/engine/tae/tables/base.go
Labels: size/M, kind/refactor, Tests, Enhancement, Review effort [1-5]: 4

#17859 change default dop of merge scope to 1
  pkg/sql/compile/compile.go
Labels: kind/refactor, size/XS

#17824 fix table not found in tranfer deletes in CN
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/pessimistic_transaction/ww_conflict.result
  test/distributed/cases/pessimistic_transaction/ww_conflict.sql
Labels: kind/bug, size/M

#17847 fix: result_scan, meta_scan prepare with parameter
  pkg/frontend/computation_wrapper.go
  pkg/frontend/query_result.go
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/result_scan.go
  pkg/sql/plan/visit_plan.go
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result.sql
Labels: kind/bug, size/S

#17858 Remove unused bucket join
  pkg/sql/compile/compile.go
Labels: size/S, kind/refactor

#17871 Revert "More constant fold for expression executor (#17779)"
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_regular_substr.result
Labels: kind/bug, size/M

#17831 Json_extract on simple path.
  pkg/common/mpool/mpool.go
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_test.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/path_test.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/container/vector/functionTools.go
  pkg/container/vector/vector.go
  pkg/sql/plan/function/func_builtin_json.go
Labels: size/M, kind/enhancement

#17873 fix transfer failed
  pkg/catalog/types.go
  pkg/container/types/tuple.go
  pkg/objectio/fs.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/testutil/util.go
Labels: kind/bug, size/S

#17864 Fix: read sys var table out of lock
  pkg/frontend/variables.go
Labels: size/XS, kind/enhancement

#17868 fileservice: make memory and disk cache capacity dynamic adjustable
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/fscache/capacity.go
  pkg/fileservice/fscache/capacity_test.go
  pkg/fileservice/fscache/data.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/memorycache/cache.go
  pkg/fileservice/memorycache/cache_test.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/lrucache/lru.go
  pkg/fileservice/memorycache/lrucache/lru_test.go
  pkg/fileservice/memorycache/lrucache/shard.go
  pkg/fileservice/memorycache/lrucache/types.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
Labels: size/M, kind/enhancement

#17849 Refactor SubOperator Call
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/limit/limit.go
  pkg/sql/colexec/mergedelete/mergedelete.go
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/sample/sample.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/types.go
  pkg/vm/types.go
Labels: kind/feature, size/M

#17819 chore: span profile support BackOff strategy
  etc/launch-dynamic-cn/log.toml
  etc/launch-dynamic-with-proxy/log.toml
  etc/launch-multi-cn/log.toml
  etc/launch-tae-compose/config/log.toml
  etc/launch-with-proxy/log.toml
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/frontend/routine.go
  pkg/util/trace/config.go
  pkg/util/trace/impl/motrace/config.go
  pkg/util/trace/impl/motrace/mo_trace.go
  pkg/util/trace/impl/motrace/mo_trace_test.go
  pkg/util/trace/impl/motrace/ptrace.go
  pkg/util/trace/impl/motrace/trace.go
Labels: kind/bug, kind/feature, size/L

#17790 Fix MetadataScan info
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#17876 [BugFix]: Vector index BVT fix
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: kind/bug, size/XS

#17869 fix show pitr
  pkg/sql/plan/build_show.go
  test/distributed/cases/pitr/pitr_basic.result
Labels: kind/bug, size/M

#17818 Fix execCtx leak
  pkg/frontend/back_exec.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/S

#17667 remove some comment and useless code
  pkg/frontend/mysql_protocol.go
Labels: size/S, kind/refactor

#17828 fix print blkCnt and RowCnts durint merge
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: size/S, kind/enhancement

#17880 add some tools for UT of operators
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/projection/projection_test.go
  pkg/testutil/types.go
  pkg/testutil/util_make.go
  pkg/vm/types.go
Labels: size/M, kind/test-ci

#17860 fix restore cluster table (#1.2-dev)
  pkg/frontend/snapshot.go
Labels: kind/bug, size/S

#17877 Add merge operator as child of some operators
  pkg/sql/colexec/fill/fill.go
  pkg/sql/colexec/fill/types.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/mergegroup/types.go
  pkg/sql/colexec/mergelimit/limit.go
  pkg/sql/colexec/mergelimit/limit_test.go
  pkg/sql/colexec/mergelimit/types.go
  pkg/sql/colexec/mergeoffset/offset.go
  pkg/sql/colexec/mergeoffset/offset_test.go
  pkg/sql/colexec/mergeoffset/types.go
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/mergetop/top_test.go
  pkg/sql/colexec/mergetop/types.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/colexec/partition/partition.go
  pkg/sql/colexec/partition/types.go
  pkg/sql/colexec/timewin/timewin.go
  pkg/sql/colexec/timewin/types.go
  pkg/sql/colexec/window/types.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/XL, kind/refactor

#17886 Add proxy configurations for 1.2-dev
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci, Tests, Enhancement, Review effort [1-5]: 2

#17863 refactor mo_logger Collector to improve performance.
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/util.go
  pkg/util/export/batch_processor.go
  pkg/util/export/batch_processor_test.go
  pkg/util/export/etl/common_test.go
  pkg/util/export/etl/content.go
  pkg/util/export/etl/content_test.go
  pkg/util/export/etl/csv.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/sql.go
  pkg/util/export/etl/sql_test.go
  pkg/util/export/etl/tae_test.go
  pkg/util/export/merge.go
  pkg/util/export/table/aggr.go
  pkg/util/export/table/type.go
  pkg/util/export/table/type_test.go
  pkg/util/export/writer_factory.go
  pkg/util/metric/mometric/metric_collector.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_trace.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/trace.go
  pkg/util/ring/ring.go
  pkg/util/ring/ring_test.go
  pkg/util/trace/impl/motrace/Aggr.go
  pkg/util/trace/impl/motrace/Aggr_test.go
  pkg/util/trace/impl/motrace/buffer_content.go
  pkg/util/trace/impl/motrace/buffer_pipe.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/syncer.go
  pkg/util/trace/impl/motrace/trace.go
Labels: size/XL, kind/refactor, kind/enhancement

#17884 [bug] proxy: free memory out of heap
  pkg/frontend/mysql_buffer.go
  pkg/frontend/server.go
  pkg/proxy/client_conn.go
  pkg/proxy/server_conn.go
Labels: kind/bug, size/S

#17888 Fix column case problem in insert stmt
  pkg/sql/plan/build_insert.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/S

#17894 bugfix: panic if ContentBuffer is empty.
  pkg/util/trace/impl/motrace/buffer_content.go
  pkg/util/trace/impl/motrace/buffer_content_test.go
Labels: kind/bug, size/S

#17890 Add snapshot schema check
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S

#17850 fix MOCloud 3830
  pkg/txn/rpc/server.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#17848 remove false positive branch in PrimaryKeysMayBeModified
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XS, kind/enhancement

#17898 update tombstones
  pkg/container/types/rowid.go
  pkg/objectio/extent.go
  pkg/objectio/location.go
  pkg/objectio/name.go
  pkg/vm/engine/disttae/datasource_test.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#17902 support `reset` method for evaluate expression without opt.
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpressionReset.go
  pkg/sql/compile/compileService.go
  pkg/vm/process/types.go
Labels: kind/enhancement

#17901 Revert remove false positive branch in PrimaryKeysMayBeModified
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS

#17908 move constant folding for function expression from New() to Eval()
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpressionReset.go
  pkg/sql/colexec/evalExpression_test.go
Labels: kind/enhancement

#17912 add ut for expression's reset
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
Labels: kind/bug, kind/test-ci

#17761 Add ProjectList in some operators
  pkg/sql/colexec/aggexec/types.go
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/evalProjection.go
  pkg/sql/colexec/evalProjection_test.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/fill/fill.go
  pkg/sql/colexec/fill/types.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopanti/types.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/types.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopleft/types.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopmark/types.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsemi/types.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/loopsingle/types.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/mark/types.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/types.go
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/product/types.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/productl2/types.go
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/projection/projection_test.go
  pkg/sql/colexec/projection/types.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/semi/types.go
  pkg/sql/colexec/single/join.go
  pkg/sql/colexec/single/types.go
  pkg/sql/colexec/source/source.go
  pkg/sql/colexec/source/types.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/table_scan/types.go
  pkg/sql/colexec/value_scan/types.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
Labels: size/L, Tests, Enhancement, Review effort [1-5]: 4

#17843 fix order by json type
  pkg/container/bytejson/types.go
  pkg/sort/sort.go
  test/distributed/cases/function/func_json_extract_order.result
  test/distributed/cases/function/func_json_extract_order.sql
Labels: kind/bug, size/L

#17910 [Tech Request]: reduce unnecessary channel in broadcast joins
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/vm/process/types.go
Labels: size/S, kind/refactor

#17904 Fix bug: get params index error when retry prepare insert stmt
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/pessimistic_transaction/prepare.result
  test/distributed/cases/pessimistic_transaction/prepare.sql
Labels: kind/bug, size/S

#17874 Add proxy configurations
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci, Tests, Enhancement, Review effort [1-5]: 2

#17844 fix order by json type(#1.2-dev)
  pkg/container/bytejson/types.go
  pkg/sort/sort.go
  test/distributed/cases/function/func_json_extract_order.result
  test/distributed/cases/function/func_json_extract_order.sql
Labels: kind/bug, size/L

#17933 CI: fix proxy nodeselector error
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/bug

#17789 delete committing txn state log
  pkg/lockservice/lock_table_allocator.go
Labels: size/XS

#17918 Fix oom for reader
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/types.go
Labels: size/M

#17932 [fix] : fix missing free for compile.Scope
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#17940 refactor value scan
  pkg/sql/colexec/value_scan/types.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/colexec/value_scan/value_scan_test.go
Labels: refactor-pipeline

#17942 fix a bug that cause build scopes lost in broadcast join
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
Labels: kind/bug, size/S

#17930 Fix ut TestNewMOCollector - segmentation fault
  pkg/util/export/batch_processor_test.go
  pkg/util/export/merge_test.go
  pkg/util/export/table/table_test.go
  pkg/util/export/table/type_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
Labels: kind/bug, size/S

#17929 refactor: preinsertunique
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex.go
  pkg/sql/colexec/preinsertsecondaryindex/preinsertsecondaryindex_test.go
  pkg/sql/colexec/preinsertsecondaryindex/types.go
  pkg/sql/colexec/preinsertunique/preinsertunique.go
  pkg/sql/colexec/preinsertunique/preinsertunique_test.go
  pkg/sql/colexec/preinsertunique/types.go
  pkg/sql/util/index_util.go
Labels: kind/refactor, refactor-pipeline

#17916 remove global var
  pkg/cnservice/server.go
  pkg/embed/cluster_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/refactor

#14897 Fix: update calls to `runtime.fastrand` to use `cheaprand` for compatibility with Go 1.22
  pkg/vm/engine/tae/containers/pool.go
  pkg/vm/engine/tae/containers/runtime.go
  pkg/vm/engine/tae/containers/runtime_1.22.go
Labels: size/S

#17945 remove unused statement in bvt
  test/distributed/cases/snapshot/snapshot_restore_system_table.result
  test/distributed/cases/snapshot/snapshot_restore_system_table.sql
Labels: kind/bug, size/S

#17968 fix indexjoin
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/indexjoin/types.go
Labels: refactor-pipeline

#17976 Revert Projection operator back to bb4f5ea
  pkg/sql/colexec/projection/projection.go
  pkg/sql/colexec/projection/projection_test.go
  pkg/sql/colexec/projection/types.go
  pkg/sql/compile/compile.go
Labels: size/M

#17892 apply pk filter for mo_tables and mo_database
  pkg/vm/engine/disttae/pk_filter_base.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/M, kind/enhancement

#17867 CN merge objects in batch
  pkg/cnservice/server.go
  pkg/cnservice/server_task.go
  pkg/frontend/test/engine_mock.go
  pkg/objectio/block_info.go
  pkg/objectio/block_info_test.go
  pkg/pb/api/api.pb.go
  pkg/pb/shard/shard.pb.go
  pkg/shardservice/types.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/s3util.go
  pkg/sql/plan/function/ctl/cmd_merge.go
  pkg/sql/plan/function/ctl/object_filter.go
  pkg/sql/plan/function/ctl/object_filter_test.go
  pkg/txn/storage/tae/read.go
  pkg/txn/storage/tae/write.go
  pkg/vm/engine/disttae/datasource_test.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logstore/sm/sm.go
  pkg/vm/engine/tae/logstore/sm/types.go
  pkg/vm/engine/tae/mergesort/heap.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/types.go
  proto/api.proto
  proto/shard.proto
Labels: kind/feature, size/L

#17773 [fix] : fix restore related issues
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
Labels: kind/bug, size/S

#17927 refactor Innerjoin
  pkg/sql/colexec/evalProjection.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/join/types.go
Labels: Review effort [1-5]: 3, Enhancement, refactor-pipeline

#17846 Add max_allow_packet check
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_buffer_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/server.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
Labels: kind/feature, size/L, kind/refactor

#17928 support show pitr with range value and unit
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/pitr/pitr_basic.result
  test/distributed/cases/pitr/pitr_basic.sql
Labels: kind/feature, size/M

#17975 Fix data race
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S

#17962 Fix: skip view when collect rows and size in cmd `show table status`
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/dml/show/show4.result
  test/distributed/cases/dml/show/show4.sql
Labels: kind/bug, size/S

#17981 fix txn opt
  pkg/frontend/back_exec.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/txn.go
Labels: kind/bug, size/S

#17949 support multi test cluster run concurrently
  pkg/embed/cluster.go
  pkg/embed/cluster_test.go
  pkg/embed/operator.go
  pkg/embed/template.go
  pkg/embed/testing.go
  pkg/embed/types.go
  pkg/hakeeper/checkers/dnservice/check.go
  pkg/hakeeper/checkers/dnservice/check_test.go
  pkg/hakeeper/checkers/dnservice/parse.go
  pkg/hakeeper/checkers/dnservice/parse_test.go
  pkg/logservice/config.go
  pkg/logservice/service.go
Labels: size/M, kind/test-ci

#17950 fix parallel run scope never do context rebuild.
  pkg/sql/compile/compile2.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/pipeline/types.go
  pkg/vm/process/process2.go
  pkg/vm/process/types.go
Labels: kind/bug, size/M

#18027 [Cherry-pick] collect table statistics for Ordinary and Materialized
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/dml/show/show4.result
  test/distributed/cases/dml/show/show4.sql
Labels: kind/bug, size/S

#17911 [proxy] enhancement: don't change txn status if it is error packet
  pkg/proxy/tunnel.go
  pkg/proxy/tunnel_test.go
  pkg/proxy/util.go
Labels: kind/bug, size/S, kind/enhancement

#18026 collect table statistics for Ordinary and Materialized
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS, kind/enhancement

#17987 Refactor on duplicate key for mem reuse
  pkg/sql/colexec/onduplicatekey/on_duplicate_key.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key_test.go
  pkg/sql/colexec/onduplicatekey/types.go
  pkg/sql/compile/operator.go
Labels: refactor-pipeline

#17966 fix hashbuild operator
  CODEOWNERS
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
Labels: refactor-pipeline

#17985 fix shuffle operator
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/shuffle_test.go
  pkg/sql/colexec/shuffle/types.go
Labels: refactor-pipeline

#17941 refactor index_build operator
  CODEOWNERS
  pkg/sql/colexec/indexbuild/build.go
  pkg/sql/colexec/indexbuild/types.go
Labels: refactor-pipeline

#18024 Adjust some pub sub behaviors
  pkg/common/pubsub/types.go
  pkg/common/pubsub/utils.go
  pkg/common/pubsub/utils_test.go
  pkg/frontend/publication_subscription.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/pub_sub.go
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/publication_subscription/pub_sub_improvment.result
  test/distributed/cases/publication_subscription/publish_subscribe.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
  test/distributed/cases/snapshot/snapshot_restore_publication.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/tenant/pub_sub3.result
Labels: size/M, kind/enhancement

#18033 Fix bug: prepare for update with limit clause get error
  pkg/sql/plan/query_builder.go
  test/distributed/cases/pessimistic_transaction/select_for_update.result
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
Labels: kind/bug, size/S

#17969 return the err if some failure happened when build reader filter
  pkg/container/vector/vector.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/pk_filter.go.go
  pkg/vm/engine/disttae/pk_filter_base.go
  pkg/vm/engine/disttae/pk_filter_mem.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/test/testutil/util.go
Labels: size/M, kind/enhancement

#17947 [bug] fix memory leak
  pkg/frontend/mysql_buffer.go
  pkg/proxy/server_conn.go
Labels: kind/bug, size/S

#18028 Optimize commit readonly txn
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn_test.go
  pkg/txn/client/client.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement

#17900 [bug] logtail: pause the client if error occurrs
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: kind/bug, size/XS

#18030 refactor snapshot and support show create database with sp hint
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/connector.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session_test.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/sql_executor_context_test.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/show.go
  pkg/sql/parsers/tree/table_name.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_master.go
  pkg/sql/plan/apply_indices_vector.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_delete.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_show_util.go
  pkg/sql/plan/build_show_util_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/memoryengine/compiler_context.go
Labels: size/XXL, kind/enhancement

#18038 Optimize create txn
  pkg/cnservice/server.go
  pkg/txn/client/client.go
  pkg/txn/client/generator.go
  pkg/txn/client/generator_test.go
Labels: size/S, kind/enhancement

#17943 add spool
  CODEOWNERS
  pkg/common/spool/cursor.go
  pkg/common/spool/node.go
  pkg/common/spool/spool.go
  pkg/common/spool/spool_test.go
Labels: size/L, kind/enhancement

#17978 Cache a mysql parser in session.
  pkg/frontend/back_exec.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/types.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/scanner.go
Labels: size/M, kind/enhancement

#18040 remove pipeline in shuffle join probe side
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
Labels: size/S, kind/refactor

#18032 Fix bug: prepare for update with limit clause get error
  pkg/sql/plan/query_builder.go
  test/distributed/cases/pessimistic_transaction/select_for_update.result
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
Labels: kind/bug, size/S

#17982 fix txn opt
  pkg/frontend/back_exec.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/txn.go
Labels: kind/bug, size/S

#18037 fix WatchDirty UT
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
Labels: kind/bug, size/S

#18029 fix missing objectEntry after rollbacking
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/object_list.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#17763 Add output exec analyze-1.2-dev
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/feature, size/S

#18056 reuse: make ReusableObject pointer type
  pkg/common/reuse/checker.go
  pkg/common/reuse/factory.go
  pkg/common/reuse/mpool_based.go
  pkg/common/reuse/pool_test.go
  pkg/common/reuse/sync_pool_based.go
  pkg/common/reuse/types.go
Labels: size/M, kind/enhancement

#17832 fix bug: can not constant fold some expr
  pkg/sql/colexec/restrict/restrict.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/rule/constant_fold.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: kind/bug, size/S

#18050 simply scopes in shuffle join
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/remoterun.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/shuffle.go
  pkg/vm/process/process2.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/M, kind/refactor

#18057 use sync.Mutex to replace channel for CompileService.
  pkg/sql/compile/compileService.go
Labels: kind/bug, size/S

#17984 refactor operator of time window
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/timewin/timewin.go
  pkg/sql/colexec/timewin/timewin_test.go
  pkg/sql/colexec/timewin/types.go
Labels: refactor-pipeline

#18049 add pub sub case
  test/distributed/cases/publication_subscription/pub_sub_improve2.result
  test/distributed/cases/publication_subscription/pub_sub_improve2.sql
  test/distributed/cases/publication_subscription/pub_sub_improvement.result
  test/distributed/cases/publication_subscription/pub_sub_improvement.sql
  test/distributed/cases/publication_subscription/pub_sub_improvement2.result
  test/distributed/cases/publication_subscription/pub_sub_improvement2.sql
Labels: kind/feature, size/XXL

#18069 remove unused logic in scope
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/scope.go
Labels: size/S, kind/refactor

#17891 remove MysqlResultSet.Name2Index
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  pkg/frontend/internal_executor.go
  pkg/frontend/internal_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/resultset.go
  pkg/frontend/show_account.go
  pkg/stream/connector/connector_test.go
  pkg/stream/connector/converter.go
  pkg/util/internalExecutor/internal_executor.go
  pkg/util/metric/mometric/cron_task.go
Labels: size/M, kind/refactor

#18046 Refactor LeftJoin
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/left/types.go
Labels: refactor-pipeline

#18043 malloc: reduce memory usages of stacktrace
  pkg/common/malloc/checked_allocator.go
  pkg/common/malloc/closure_deallocator.go
  pkg/common/malloc/config.go
  pkg/common/malloc/stacktrace.go
  pkg/common/malloc/stacktrace_test.go
Labels: size/M, kind/enhancement

#18066 Refactor LoopAnti
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopanti/types.go
Labels: refactor-pipeline

#18073 refactor pipelines in shuffle group
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: size/M, kind/refactor

#18036 Refactor insert for mem reused
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/s3util.go
Labels: refactor-pipeline

#17983 fix shufflebuild
  pkg/sql/colexec/shufflebuild/build.go
  pkg/sql/colexec/shufflebuild/types.go
Labels: refactor-pipeline

#18031 Refactor AntiJoin
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/anti/types.go
  pkg/sql/colexec/join/join.go
Labels: refactor-pipeline

#17970 refactor: external
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/parquet.go
  pkg/sql/colexec/external/types.go
Labels: kind/refactor, refactor-pipeline

#18052 colexec/top: refactor
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/top/types.go
Labels: refactor-pipeline

#18093 fix ut `Test_Append`
  pkg/vm/engine/test/testutil/disttae_engine.go
Labels: kind/bug, size/XS

#18044 malloc: reduce memory usages of stacktrace
  pkg/common/malloc/checked_allocator.go
  pkg/common/malloc/closure_deallocator.go
  pkg/common/malloc/config.go
  pkg/common/malloc/stacktrace.go
  pkg/common/malloc/stacktrace_test.go
Labels: size/M, kind/enhancement

#18086 Refactor order for mem reused
  pkg/sql/colexec/order/order.go
  pkg/sql/colexec/order/order_test.go
  pkg/sql/colexec/order/types.go
Labels: refactor-pipeline

#18089 Refactor mergeorder for mem reused
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergeorder/order_test.go
  pkg/sql/colexec/mergeorder/types.go
Labels: refactor-pipeline

#18059 [bug] logtail: pause the client if error occurrs
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: kind/bug, size/XS

#18025 refactor preinsert
  pkg/frontend/test/incrservice_mock.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/colexec/preinsert/preinsert_test.go
  pkg/sql/colexec/preinsert/types.go
Labels: kind/refactor, refactor-pipeline

#18092 ctx deadline should not retry lock
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/XS

#18091 ctx deadline should not retry lock
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/XS

#18061 [enhancement] processlist: show sessions on draining cns
  pkg/sql/colexec/table_function/processlist.go
Labels: kind/bug, size/XS

#17856 Fix some warnings. #17854
  pkg/container/types/array_test.go
  pkg/sql/plan/build_dml_util.go
Labels: kind/refactor, size/XS

#18087 add pub sub case
  test/distributed/cases/publication_subscription/pub_sub2.result
  test/distributed/cases/publication_subscription/pub_sub2.sql
  test/distributed/cases/publication_subscription/pub_sub_improvement2.result
  test/distributed/cases/publication_subscription/pub_sub_improvement2.sql
Labels: kind/feature, size/L

#18098 Refactor offset for mem reused
  pkg/sql/colexec/offset/offset.go
  pkg/sql/colexec/offset/offset_test.go
  pkg/sql/colexec/offset/types.go
Labels: refactor-pipeline

#18085 [Tech Request]: operators never receive data directly from channel
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/sql/colexec/fuzzyfilter/filter_test.go
  pkg/sql/colexec/fuzzyfilter/types.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersect/intersect_test.go
  pkg/sql/colexec/intersect/types.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/intersectall/intersectall_test.go
  pkg/sql/colexec/intersectall/types.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/colexec/merge/merge.go
  pkg/sql/colexec/merge/types.go
  pkg/sql/colexec/mergecte/mergecte.go
  pkg/sql/colexec/mergecte/types.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/colexec/mergerecursive/mergerecursive.go
  pkg/sql/colexec/mergerecursive/types.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/minus/minus_test.go
  pkg/sql/colexec/minus/types.go
  pkg/sql/colexec/partition/partition.go
  pkg/sql/colexec/receiver_operator.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  proto/pipeline.proto
Labels: size/L, kind/refactor

#18090 Refactor LoopLeft
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopleft/join_test.go
  pkg/sql/colexec/loopleft/types.go
Labels: refactor-pipeline

#18079 Refactor LoopJoin
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopjoin/types.go
Labels: refactor-pipeline

#18078 Fix bug: double free batch
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/indexjoin/join.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
  pkg/sql/colexec/loopanti/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/loopjoin/types.go
  pkg/sql/colexec/loopleft/join.go
  pkg/sql/colexec/loopmark/join.go
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/right/types.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
Labels: kind/bug, size/S

#18100 call table_scan.Reader.Close() during table_scan.Free
  pkg/sql/colexec/table_scan/types.go
Labels: kind/bug, size/XS

#18110 Fix Join UT
  pkg/sql/colexec/anti/join_test.go
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  pkg/sql/colexec/loopanti/join_test.go
  pkg/sql/colexec/loopjoin/join_test.go
  pkg/sql/colexec/loopleft/join_test.go
Labels: refactor-pipeline

#18099 [tech] pprof: dump malloc profile
  cmd/mo-service/debug.go
  pkg/common/malloc/default.go
Labels: size/S, kind/enhancement

#18109 [Cherry-pick] Fix: get system variable autocommit in backSession
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/stmt_kind.go
  pkg/frontend/types.go
  pkg/frontend/variables.go
Labels: kind/bug, size/S

#18102 Refactor LoopSingle
  pkg/sql/colexec/loopsingle/join.go
  pkg/sql/colexec/loopsingle/types.go
Labels: refactor-pipeline

#18101 Refactor LoopSemi
  pkg/sql/colexec/loopsemi/join.go
  pkg/sql/colexec/loopsemi/types.go
Labels: refactor-pipeline

#18071 Refactor mergedelete for mem reused
  pkg/sql/colexec/mergedelete/mergedelete.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/mergedelete/types.go
Labels: refactor-pipeline

#18070 Refactor mergeblock for mem reused
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergeblock/types.go
Labels: refactor-pipeline

#18068 refactor deletion for mem reused
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/deletion/types.go
Labels: refactor-pipeline

#18108 [cherry-pick-17773] : fix restore related issues
  pkg/frontend/snapshot.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/types.go
Labels: kind/bug, size/M

#18120 refactor product and product_L2
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/product/types.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/productl2/types.go
Labels: refactor-pipeline

#18064 reuse col def packet constructed during prepare stmt
  pkg/frontend/computation_wrapper.go
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/resp_client.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/proxy/server_conn_test.go
Labels: kind/feature, size/M
