Repository matrixorigin/matrixone, pull requests merged in 2024-12, with the labels that each got.

#20469 Fix TestSnapshotGC
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#20420 Fix cuio calculated result as float64 val
  pkg/sql/plan/function/func_builtin.go
  pkg/util/trace/impl/motrace/cu.go
  pkg/util/trace/impl/motrace/cu_bench_test.go
  test/distributed/cases/log/query_cu.result
  test/distributed/cases/log/query_cu.sql
Labels: kind/bug, size/S

#20439 Update incremental dedup
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/index/indexwrapper/mutindex.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/obj.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/types.go
  pkg/vm/engine/tae/txn/txnimpl/base_table.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/cases/stage/external_stage.result
  test/distributed/cases/stage/external_stage.sql
  test/distributed/cases/stage/external_stage_columns.result
  test/distributed/cases/stage/external_stage_columns.sql
  test/distributed/cases/stage/stage_based_stage.result
  test/distributed/cases/stage/stage_based_stage.sql
  test/distributed/cases/stage/stage_based_stage_columns.result
  test/distributed/cases/stage/stage_based_stage_columns.sql
Labels: size/M, kind/enhancement

#20446 quick return if has no tombstone in WorkspaceS3FlushedDeletes
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/tae/blockio/utils.go
Labels: size/S, kind/enhancement

#20385 quit cdc Start func when pause
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
  pkg/taskservice/daemon_task.go
Labels: size/S, kind/enhancement

#20487 optimize index plan to support sysbench random ranges benchmark
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/runtime_filter.go
  test/distributed/cases/optimizer/explain_index.result
  test/distributed/cases/optimizer/explain_index.sql
  test/distributed/cases/optimizer/like.result
Labels: size/M, kind/enhancement

#20489 [Cherry-pick] quit cdc Start func when pause
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
  pkg/taskservice/daemon_task.go
Labels: size/S, kind/enhancement

#20495 remove panic in parsing txn entries
  pkg/catalog/tuplesParse.go
  pkg/catalog/tuplesParse_test.go
  pkg/vm/engine/tae/common/linklist_test.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_test.go
Labels: size/M, kind/enhancement

#20481 chore: cu price allows 0
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/util/trace/impl/motrace/buffer_pipe_test.go
Labels: kind/bug, size/M

#20494 add backSes Exec lower_case_table_names(#2.0-dev)
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.sql
Labels: kind/bug, size/M

#20496 remove panic in parsing txn entries - main
  pkg/catalog/tuplesParse.go
  pkg/catalog/tuplesParse_test.go
  pkg/vm/engine/tae/common/linklist_test.go
  pkg/vm/engine/tae/common/print.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_test.go
Labels: size/M, kind/enhancement

#20502 reduce memory consumption in bvt shuffle test
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: kind/bug, size/S

#20506 fix bug: update secondary key panic
  pkg/sql/plan/bind_update.go
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: kind/bug, size/S

#20485 fix backSes Exec lower_case_table_names
  pkg/frontend/authenticate_test.go
  pkg/frontend/back_exec.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case_table_names.sql
Labels: kind/bug, size/M

#20480 refactor merge
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/config.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/mod_test.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyGroup.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/mergesort/task.go
Labels: size/L, kind/enhancement

#20451 Analyzer adds FileService Cache read and hit statistics
  pkg/pb/plan/plan.pb.go
  pkg/perfcounter/counter_set.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/mergeblock/mergeblock.go
  pkg/sql/colexec/multi_update/delete.go
  pkg/sql/colexec/multi_update/insert.go
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/colexec/output/output.go
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/compile/analyze_module.go
  pkg/sql/models/logic_plan.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/function/func_mo_explain_phy_test.go
  pkg/vm/process/operator_analyzer.go
  pkg/vm/process/operator_analyzer_test.go
  proto/plan.proto
Labels: kind/bug, size/L

#20503 to 2.0 "reduce memory consumption in bvt shuffle test"
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: kind/bug, size/S

#20505 fix bug: update secondary key panic
  pkg/sql/plan/bind_update.go
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: kind/bug, size/S

#20508 fix data race in ut
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: size/M, kind/test-ci

#20513 fix wait done reporting error
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
Labels: kind/bug, size/S

#20435 use mo_table_rows/size in `show table status`
  pkg/frontend/back_exec.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/plan/function/func_mo.go
  test/distributed/cases/publication_subscription/pub_sub.result
  test/distributed/cases/publication_subscription/pub_sub_improvement.result
  test/distributed/cases/tenant/pub_sub2.result
  test/distributed/cases/tenant/pub_sub3.result
Labels: size/M, kind/enhancement

#20519 [Cherry-pick] fix data race in ut
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: size/M, kind/test-ci

#20515 fix double close atomic batch
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/types.go
Labels: kind/bug, size/S

#20518 fix wait done reporting error on 2.0-dev
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
Labels: kind/bug, size/S

#20499 [improvement] logtail: do not abort txns when reconnect.
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/server.go
  pkg/tests/issues/issue_test.go
  pkg/txn/client/client.go
  pkg/txn/client/timestamp_waiter.go
  pkg/txn/client/timestamp_waiter_test.go
  pkg/txn/client/types.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/sender_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/L, kind/enhancement

#20524 fix lower_case_table_names in view definition
  pkg/sql/plan/query_builder.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/M

#20455 vm: add Process.GetSpillFileService
  cmd/mo-service/main.go
  pkg/defines/const.go
  pkg/fileservice/sub_path.go
  pkg/fileservice/sub_path_test.go
  pkg/vm/process/process.go
  pkg/vm/process/process2_test.go
Labels: size/M, kind/enhancement

#20490 [Cherry-pick] update table id when cdc task resume/restart
  pkg/cdc/watermark_updater.go
  pkg/cdc/watermark_updater_test.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: size/M, kind/enhancement

#20530 optimization of the reader Equal filter.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
  pkg/vm/engine/engine_util/reader.go
Labels: size/S, kind/enhancement

#20532 fix busy loop in morpc if send queue is full to 2.0
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: size/S, kind/enhancement

#20531 fix busy loop in morpc if send queue is full
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: size/S, kind/enhancement

#20538 [Cherry-pick] fix lower in view && fix double close atomic batch
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/types.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/M

#20511 fileservice: retry writes for small objects
  pkg/fileservice/aliyun_sdk.go
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/object_storage.go
  pkg/fileservice/qcloud_sdk.go
Labels: size/M, kind/enhancement

#20525 Add tenxcloud bvt test,base:2.0-dev
  test/distributed/cases/dataXtest/dataXtest01.result
  test/distributed/cases/dataXtest/dataXtest01.sql
  test/distributed/cases/tenxcloud_xx/tenxcloudtest.result
  test/distributed/cases/tenxcloud_xx/tenxcloudtest.sql
Labels: size/S, kind/test-ci, Review effort [1-5]: 1

#20521 fileservice: close idle connections periodically
  pkg/fileservice/http_client.go
Labels: size/S, kind/enhancement

#20550 fix bug: insert/update sk get incorrect value
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/bind_update.go
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: kind/bug, size/S

#20552 fix bug: insert/update sk get incorrect value
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/bind_update.go
  test/distributed/cases/dml/insert/not_null_check.result
  test/distributed/cases/dml/insert/not_null_check.sql
Labels: kind/bug, size/S

#20537 txnmgr refactor for tn migration
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/tasks/job.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/util.go
Labels: size/M, kind/refactor, kind/enhancement

#20545 add case for sensitive restore(2.0-dev)
  test/distributed/cases/snapshot/snapshot_restore_lower_case.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case.sql
Labels: kind/bug, size/M

#20555 fix binary execute record sql
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_test.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
Labels: kind/bug, size/M

#20548 [bug] fix the bug when get info from cgroup v1
  go.mod
  go.sum
Labels: kind/bug, size/XS

#20553 fix binary execute record sql
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_test.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
Labels: kind/bug, size/M

#20473 cgo: let the go toolchain build the c library
  Makefile
  cgo/lib.go
  pkg/common/bitmap/cbitmap.go
Labels: size/S, kind/enhancement

#20547 [bug] fix the bug when get info from cgroup v1
  go.mod
  go.sum
Labels: kind/bug, size/XS

#20569 cgo: fix CFLAGS to support older c compiler
  cgo/lib.go
Labels: size/XS, kind/enhancement

#20571 refactor for the future tn migration 2
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnbase/types.go
Labels: size/L, kind/refactor

#20579 fix txn deadlock during drop account
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/publication_subscription.go
Labels: kind/bug, size/S

#20580 fix txn deadlock during drop account
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/publication_subscription.go
Labels: kind/bug, size/S

#20546 add case for sensitive restore
  test/distributed/cases/snapshot/snapshot_restore_lower_case.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case.sql
Labels: kind/bug, size/M

#20581 fix checking database id in creating table
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/XS

#20587 to 2.0 "make index scan always tp"
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#20585 make index scan always tp
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#20573 remove unnecessary logics after delay expand ranges
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/types.go
Labels: size/M, kind/refactor

#20586 [Cherry-pick] use mo_table_rows/size in `show table status`
  pkg/frontend/back_exec.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/plan/function/func_mo.go
  test/distributed/cases/publication_subscription/pub_sub.result
  test/distributed/cases/publication_subscription/pub_sub4.result
  test/distributed/cases/publication_subscription/pub_sub4.sql
  test/distributed/cases/publication_subscription/pub_sub_improvement.result
  test/distributed/cases/tenant/pub_sub2.result
  test/distributed/cases/tenant/pub_sub3.result
Labels: size/M, kind/enhancement

#20601 fix show table status of an empty db
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/publication_subscription/pub_sub4.result
  test/distributed/cases/publication_subscription/pub_sub4.sql
Labels: kind/bug, size/S

#20602 Revert "remove unnecessary logics after delay expand ranges (#20573)"
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/types.go
Labels: kind/bug, size/M

#20588 fileservice: in minio and qcloud sdk, do not load credentials from env vars if provided in arguments
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/minio_sdk_test.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_arguments_test.go
  pkg/fileservice/qcloud_sdk.go
  pkg/fileservice/utils.go
  pkg/fileservice/utils_test.go
Labels: size/M, kind/enhancement

#20590 support json_set/json_insert/json_replace
  pkg/container/bytejson/bytejosn_modifier_test.go
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_modifier.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/sql/plan/function/func_builtin_json.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_json_insert.result
  test/distributed/cases/function/func_json_insert.sql
  test/distributed/cases/function/func_json_replace.result
  test/distributed/cases/function/func_json_replace.sql
  test/distributed/cases/function/func_json_set.result
  test/distributed/cases/function/func_json_set.sql
Labels: kind/feature, size/XL

#20599 fix eating err
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/txn.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
Labels: size/S, kind/enhancement

#20598 fix eating err
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/txn.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
Labels: size/M, kind/enhancement

#20615 recover run panic
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
Labels: kind/bug, size/S, kind/enhancement

#20621 to 2.0 "make in predicate null rejecting"
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#20607 add debug log
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: kind/bug, size/S

#20606 clean temporary files when `disttae.test` UTs are complete.
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/mo_table_stats_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/test/testutil/tae_engine.go
  pkg/vm/engine/test/testutil/types.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/M

#20635 fix show index
  pkg/sql/plan/build_show.go
  test/distributed/cases/array/array_index.result
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/drop_if_exists.result
  test/distributed/cases/ddl/secondary_index_alter.result
  test/distributed/cases/ddl/secondary_index_create.result
  test/distributed/cases/ddl/secondary_index_delete.result
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/dml/show/IndexMetadata.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show6.result
  test/distributed/cases/dml/show/show6.sql
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/optimistic/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/alter_table.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result_cloud.result
  test/distributed/cases/system_variable/system_variables.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/L, kind/enhancement

#20618 make in predicate null rejecting
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS

#20628 [bug] logtail: fix data race, a new worker send all requests
  pkg/common/moerr/cause.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/tae/logtail/service/client.go
  pkg/vm/engine/tae/logtail/service/server_test.go
Labels: kind/bug, size/M

#20600 refactor for the tn migration 3
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/gc/gc_test.go
  pkg/vm/engine/tae/gc/job.go
  pkg/vm/engine/tae/gc/manager.go
  pkg/vm/engine/tae/gc/option.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tasks/cancelablejob.go
  pkg/vm/engine/tae/tasks/job.go
  pkg/vm/engine/tae/txn/txnbase/helper.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/test/testutil/util.go
Labels: size/XL, kind/refactor

#20605 to 2.0: clean temporary files when `disttae.test` UTs are complete.
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/mo_table_stats_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/test/testutil/tae_engine.go
  pkg/vm/engine/test/testutil/types.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/M

#20626 fix use panic
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/ddl/use.result
  test/distributed/cases/ddl/use.sql
Labels: kind/bug, size/S

#20629 to 2.0: switch the size getter of the show accounts to mo_table_size.
  pkg/frontend/show_account.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/test/mo_table_stats_test.go
Labels: kind/bug, size/L, kind/enhancement

#20565 [bug] logtail: fix data race, a new worker send all requests
  pkg/common/moerr/cause.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/tae/logtail/service/client.go
  pkg/vm/engine/tae/logtail/service/server_test.go
Labels: kind/bug, size/M

#20582 fix checking database id in creating table - main
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/XS

#20509 Refactor fault injection
  pkg/cnservice/server_query.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/objectio/injects.go
  pkg/pb/api/api.pb.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/remoterunClient_test.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint_test.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/reader.go
  pkg/sql/plan/function/ctl/types.go
  pkg/sql/plan/function/fault/fault.go
  pkg/sql/plan/function/fault/fault_test.go
  pkg/sql/plan/function/fault/types.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/utils.go
  pkg/tests/issues/issue_test.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
  pkg/util/fault/handler.go
  pkg/vm/engine/cmd_util/operations.go
  pkg/vm/engine/cmd_util/operations.pb.go
  pkg/vm/engine/cmd_util/operations.proto
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/test/disttae_engine_test.go
  proto/api.proto
  proto/query.proto
Labels: size/XL, kind/refactor

#20608 apply reader PK filter on workspace entries.
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/engine_util/datasource.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
  pkg/vm/engine/engine_util/pk_filter_mem_test.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/engine_util/tombstone_data.go
  pkg/vm/engine/engine_util/tombstone_data_test.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#20559 refactor: improve external
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/external_test.go
  pkg/sql/colexec/external/parquet.go
  pkg/sql/colexec/external/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/plan/types.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/M, kind/refactor

#20627 add debug log
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: kind/bug, size/S

#20641 fix data race in shuffle pool stats
  pkg/sql/colexec/shuffleV2/shufflepool.go
Labels: kind/bug, size/S

#20643 fix init mo_table_stats cron task meta.
  pkg/cnservice/distributed_tae.go
  pkg/frontend/server.go
  pkg/predefine/predefine.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/test/testutil/disttae_engine.go
Labels: kind/bug, size/M

#20625 fix use panic
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/util/fault/fault_test.go
  test/distributed/cases/ddl/use.result
  test/distributed/cases/ddl/use.sql
Labels: kind/bug, size/S

#20648 prefetch table meta for slow ranges
  pkg/frontend/test/engine_mock.go
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#20658 use force_update policy in `show table status`
  pkg/frontend/mysql_cmd_executor.go
Labels: size/XS, kind/enhancement

#20595 Optimize Analyze module code
  pkg/sql/compile/analyze_module.go
  pkg/sql/models/phy_plan.go
  pkg/sql/models/phy_plan_test.go
  pkg/sql/models/show_phyplan_test.go
  pkg/vm/process/operator_analyzer.go
Labels: size/S, kind/enhancement

#20636 fix show index
  pkg/sql/plan/build_show.go
  test/distributed/cases/array/array_index.result
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter_table.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/alter_table_rename_column.result
  test/distributed/cases/ddl/drop_if_exists.result
  test/distributed/cases/ddl/secondary_index_alter.result
  test/distributed/cases/ddl/secondary_index_create.result
  test/distributed/cases/ddl/secondary_index_delete.result
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/ddl/secondary_index_master.result
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/dml/show/IndexMetadata.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/dml/show/show6.result
  test/distributed/cases/dml/show/show6.sql
  test/distributed/cases/dtype/binary.result
  test/distributed/cases/optimistic/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/alter_table.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/query_result/query_result.result
  test/distributed/cases/query_result/query_result_cloud.result
  test/distributed/cases/system_variable/system_variables.result
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/L, kind/enhancement

#20661 fix incorrect error info
  pkg/container/bytejson/bytejosn_modifier_test.go
  pkg/container/bytejson/utils.go
Labels: kind/bug, size/S

#20671 Optimize workspace dump
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/M, kind/enhancement

#20674 fix hung due to deadlock to 2.0
  pkg/txn/client/client.go
Labels: kind/bug, size/S

#20676 delete unsubscribed account in mo_subs
  pkg/bootstrap/versions/v2_0_1/pubsub.go
  pkg/bootstrap/versions/v2_0_1/pubsub_test.go
Labels: kind/bug, size/S

#20668 fix restore view with lower case table names equals to 0(#2.0-dev)
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/snapshot_restore_lower_case_2.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case_2.sql
Labels: kind/bug, size/L

#20673 fix hung due to deadlock
  pkg/txn/client/client.go
Labels: kind/bug, size/S

#20551 do not merge tombstone when compact
  pkg/vm/engine/tae/db/merge/cnScheduler.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: kind/bug, size/M

#20667 fix restore view with lower case table names equals to 0
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/snapshot_restore_lower_case_2.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case_2.sql
Labels: kind/bug, size/L

#20685 [Cherry-pick] fix delete unsubscribed account in mo_subs
  pkg/bootstrap/versions/v2_0_1/pubsub.go
  pkg/bootstrap/versions/v2_0_1/pubsub_test.go
Labels: kind/bug, size/S

#20686 small code refactor
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
Labels: size/S, kind/refactor

#20689 malloc: tune tests to run faster
  pkg/common/malloc/allocator_test.go
  pkg/common/malloc/metrics_allocator.go
Labels: size/XS, kind/enhancement

#20660 prefetch table meta for slow ranges
  pkg/frontend/test/engine_mock.go
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#20679 fix ut in fault injection
  pkg/sql/plan/function/fault/fault_test.go
  pkg/util/fault/fault_test.go
Labels: kind/bug, size/S

#20619 [improvement] stats: add some logs and UT
  pkg/cnservice/server_query.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/mo_table_stats_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/test/testutil/logtailserver.go
  pkg/vm/engine/test/testutil/tae_engine.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/L, kind/enhancement

#20684 [Cherry-pick]fix show table status
  pkg/frontend/mysql_cmd_executor.go
  test/distributed/cases/dml/show/show4.sql
  test/distributed/cases/publication_subscription/pub_sub.sql
  test/distributed/cases/publication_subscription/pub_sub4.sql
  test/distributed/cases/publication_subscription/pub_sub_improvement.sql
  test/distributed/cases/tenant/pub_sub2.sql
  test/distributed/cases/tenant/pub_sub3.sql
Labels: kind/bug, size/S

#20695 [Tech Request]: optimize filters on composite columns
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/expr_opt.go
  test/distributed/cases/optimizer/blockfilter.result
  test/distributed/cases/optimizer/blockfilter.test
Labels: size/M, kind/enhancement

#20691 add logs in fault enable and disable
  pkg/util/fault/fault.go
Labels: size/S, kind/enhancement

#20678 optimize workspace dump memory usage
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement

#20611 Lock mo_databases for DDL/DML
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_test.go
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.result
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
Labels: kind/bug, size/M

#20564 fileservice: in minio and qcloud sdk, do not load credentials from env vars if provided in arguments
  pkg/fileservice/minio_sdk.go
  pkg/fileservice/minio_sdk_test.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_arguments_test.go
  pkg/fileservice/qcloud_sdk.go
  pkg/fileservice/utils.go
  pkg/fileservice/utils_test.go
Labels: kind/bug, size/M

#20703 cp to 2.0 "[Tech Request]: optimize filters on composite columns (#20695)"
  pkg/sql/plan/explain/explain_expr.go
  pkg/sql/plan/expr_opt.go
  test/distributed/cases/optimizer/blockfilter.result
  test/distributed/cases/optimizer/blockfilter.test
Labels: size/M, kind/enhancement

#20699 making partition state index read only with no copy.
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
Labels: size/S

#20520 fileservice: close idle connections periodically
  pkg/fileservice/http_client.go
Labels: size/S, kind/enhancement

#20710 fix a bug for case when expression
  pkg/sql/plan/function/func_compare.go
  test/distributed/cases/expression/case_when.result
  test/distributed/cases/expression/case_when.sql
Labels: size/S

#20434 Add security case:base main
  test/distributed/cases/security/password.result
  test/distributed/cases/security/password.sql
Labels: size/L, kind/test-ci, Review effort [1-5]: 3

#20592 support json_set/json_insert/json_replace(#2.0-dev)
  pkg/container/bytejson/bytejosn_modifier_test.go
  pkg/container/bytejson/bytejson.go
  pkg/container/bytejson/bytejson_modifier.go
  pkg/container/bytejson/path.go
  pkg/container/bytejson/types.go
  pkg/container/bytejson/utils.go
  pkg/sql/plan/function/func_builtin_json.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_json_insert.result
  test/distributed/cases/function/func_json_insert.sql
  test/distributed/cases/function/func_json_replace.result
  test/distributed/cases/function/func_json_replace.sql
  test/distributed/cases/function/func_json_set.result
  test/distributed/cases/function/func_json_set.sql
Labels: kind/feature, size/XL

#20593 fix filter of window func
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/opt_misc_test.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/window/window.result
  test/distributed/cases/window/window.sql
Labels: size/M

#20711 fix a bug for case when expression
  pkg/sql/plan/function/func_compare.go
  test/distributed/cases/expression/case_when.result
  test/distributed/cases/expression/case_when.sql
Labels: kind/bug, size/S

#20707 fileservice: more disk cache events logging
  pkg/fileservice/cache.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/string.go
Labels: size/M, kind/enhancement

#20717 optimize stats for runtime filters when table not flushed
  pkg/sql/plan/runtime_filter.go
Labels: size/XS, kind/enhancement

#20719 cp to 2.0 "optimize stats for runtime filters when table not flushed"
  pkg/sql/plan/runtime_filter.go
Labels: size/XS, kind/enhancement

#20617 Lock mo_databases for DDL/DML(2.0-dev)
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_test.go
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.result
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
Labels: kind/bug, size/M

#20729 Add debug log for 2.0.1
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: size/S, kind/refactor

#20706 fileservice: more disk cache events logging
  pkg/fileservice/cache.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/string.go
Labels: size/M, kind/enhancement

#20714 to 2.0: fix show accounts double counting size.
  pkg/sql/plan/function/ctl/cmd_mo_table_stats.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/test/mo_table_stats_test.go
Labels: kind/bug, size/M

#20716 fix bad write format error - 2.0
  pkg/catalog/tuplesParse.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/test/testutil/types.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/S

#20732 [improvement] logtail: do not abort txns when reconnect.
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/common/morpc/server.go
  pkg/tests/issues/issue_test.go
  pkg/txn/client/client.go
  pkg/txn/client/timestamp_waiter.go
  pkg/txn/client/timestamp_waiter_test.go
  pkg/txn/client/types.go
  pkg/txn/rpc/sender.go
  pkg/txn/rpc/sender_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/L, kind/enhancement

#20709 rm tag 20544(2.0-dev)
  test/distributed/cases/snapshot/snapshot_restore_lower_case.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case.sql
Labels: kind/bug, size/S

#20715 fix bad write format error - main
  pkg/catalog/tuplesParse.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/test/testutil/types.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/S

#20720 Blob supports maximum storage64 m data 2.0 dev
  pkg/container/types/bytes.go
  pkg/sql/plan/function/func_unary.go
Labels: kind/feature, size/S

#20743 fix functionid
  pkg/sql/plan/build_update.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/build_util_test.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_id_test.go
Labels: kind/bug, size/XL, kind/enhancement

#20713 Blob supports a maximum storage capacity of 64M data
  pkg/container/types/bytes.go
  pkg/sql/plan/function/func_unary.go
Labels: size/S, kind/enhancement

#20738 prevent cn oom
  pkg/vm/engine/tae/db/merge/cnScheduler_test.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policy_test.go
Labels: kind/bug, size/S

#20730 Improve debug info
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: size/M

#20704 [improvement] logservice: add some logs
  pkg/logservice/service_bootstrap.go
  pkg/logservice/service_bootstrap_test.go
Labels: size/S, kind/enhancement

#20745 fix tests
  pkg/common/morpc/backend_test.go
Labels: size/XS, kind/test-ci

#20620 [improvement] stats: add some logs and UT
  pkg/cnservice/server_query.go
  pkg/frontend/show_account.go
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/mo_table_stats_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/test/testutil/logtailserver.go
  pkg/vm/engine/test/testutil/tae_engine.go
  pkg/vm/engine/test/testutil/util.go
  pkg/vm/engine/test/workspace_test.go
  pkg/vm/engine/types.go
Labels: size/XL, kind/enhancement

#20748 fix stats when merge filters on composite key
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/opt_misc.go
Labels: kind/bug, size/XS

#20749 fix stats when merge filters on composite key
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/opt_misc.go
Labels: kind/bug, size/XS

#20750 to 2.0: apply reader pk filter on workspace entry.
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/engine_util/datasource.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
  pkg/vm/engine/engine_util/pk_filter_mem_test.go
  pkg/vm/engine/engine_util/reader.go
  pkg/vm/engine/engine_util/tombstone_data.go
  pkg/vm/engine/engine_util/tombstone_data_test.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement

#20754 Refactor tn migration 4
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/M, kind/refactor

#20746 fix tests
  pkg/common/morpc/backend_test.go
Labels: size/XS, kind/test-ci

#20683 reduce some UTs' latency.
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/colexec/s3util_test.go
  pkg/tests/issues/issue_test.go
  pkg/vm/engine/engine_util/sinker_test.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
Labels: size/M, kind/enhancement

#20757 fix task concurrency control
  pkg/taskservice/task_runner.go
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/S

#20755 [improvement] logtail: some refactor and add UTs
  pkg/util/address/address.go
  pkg/util/address/address_test.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/logtail/service/server.go
Labels: size/L, kind/enhancement

#20722 optimize operator of fill
  pkg/sql/colexec/fill/fill.go
  pkg/sql/colexec/fill/fill_test.go
  pkg/sql/colexec/fill/types.go
  pkg/sql/colexec/mock_util.go
Labels: size/M

#20523 Refactor fault injection
  pkg/cnservice/server_query.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/objectio/injects.go
  pkg/pb/api/api.pb.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/remoterunClient_test.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint.go
  pkg/sql/plan/function/ctl/cmd_addfaultpoint_test.go
  pkg/sql/plan/function/ctl/cmd_tracespan.go
  pkg/sql/plan/function/ctl/reader.go
  pkg/sql/plan/function/ctl/types.go
  pkg/sql/plan/function/fault/fault.go
  pkg/sql/plan/function/fault/fault_test.go
  pkg/sql/plan/function/fault/types.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/utils.go
  pkg/tests/issues/issue_test.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
  pkg/util/fault/handler.go
  pkg/vm/engine/cmd_util/operations.go
  pkg/vm/engine/cmd_util/operations.pb.go
  pkg/vm/engine/cmd_util/operations.proto
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/test/disttae_engine_test.go
  proto/api.proto
  proto/query.proto
Labels: size/XL, kind/refactor

#20533 to 2.0: optimization of the reader Equal filter.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/engine_util/pk_filter_mem.go
  pkg/vm/engine/engine_util/reader.go
Labels: size/S, kind/enhancement

#20697 the GroupOperator support queries where there are a large number of groups.
  pkg/common/hashmap/iterator.go
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/aggInformation.go
  pkg/sql/colexec/aggexec/aggMethod.go
  pkg/sql/colexec/aggexec/aggResult.go
  pkg/sql/colexec/aggexec/approx_count.go
  pkg/sql/colexec/aggexec/argument.go
  pkg/sql/colexec/aggexec/cluster_centers.go
  pkg/sql/colexec/aggexec/concat.go
  pkg/sql/colexec/aggexec/count.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/aggexec/exec_test.go
  pkg/sql/colexec/aggexec/fromBytesRetBytes.go
  pkg/sql/colexec/aggexec/fromBytesRetFixed.go
  pkg/sql/colexec/aggexec/fromFixedRetBytes.go
  pkg/sql/colexec/aggexec/fromFixedRetFixed.go
  pkg/sql/colexec/aggexec/median.go
  pkg/sql/colexec/aggexec/multi.go
  pkg/sql/colexec/aggexec/register.go
  pkg/sql/colexec/aggexec/result.go
  pkg/sql/colexec/aggexec/result_test.go
  pkg/sql/colexec/aggexec/serialize.go
  pkg/sql/colexec/aggexec/serialize.pb.go
  pkg/sql/colexec/aggexec/serialize.proto
  pkg/sql/colexec/aggexec/serialize_test.go
  pkg/sql/colexec/aggexec/tool.go
  pkg/sql/colexec/aggexec/types.go
  pkg/sql/colexec/aggexec/window.go
  pkg/sql/colexec/group/exec.go
  pkg/sql/colexec/group/exec_test.go
  pkg/sql/colexec/group/execctx.go
  pkg/sql/colexec/group/group.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/group/reset.go
  pkg/sql/colexec/group/types.go
  pkg/sql/colexec/mergegroup/exec.go
  pkg/sql/colexec/mergegroup/exec_test.go
  pkg/sql/colexec/mergegroup/group.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/mergegroup/reset.go
  pkg/sql/colexec/mergegroup/types.go
  pkg/sql/colexec/timewin/timewin.go
  pkg/sql/colexec/timewin/timewin_test.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
Labels: kind/bug, size/XXL, do-not-merge/wip, kind/enhancement

#20708 rm tag 20544(main)
  test/distributed/cases/snapshot/snapshot_restore_lower_case.result
  test/distributed/cases/snapshot/snapshot_restore_lower_case.sql
Labels: kind/bug, size/S

#20763 improve lock meta table for DML
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/lock_meta.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/types.go
Labels: size/M, kind/refactor

#20752 fix data race
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/executor_test.go
Labels: kind/bug, size/S

#20764 refactor tn migration 5
  pkg/vm/engine/engine_util/sinker.go
  pkg/vm/engine/engine_util/sinker_test.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/deleter.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/gc/v3/executor.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/mock_cleaner.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/tasks/cancelablejob.go
Labels: size/XL, kind/refactor

#20770 fix tables under mo_catalog stats not update.
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: kind/bug, size/S

#20741 Print index name when doing explain or explain analyze
  pkg/frontend/mysql_cmd_executor.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/types.go
  proto/plan.proto
  test/distributed/cases/fulltext/fulltext1.result
  test/distributed/cases/optimizer/explain_index.result
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/like.result
Labels: kind/feature, size/M

#20774 improve lock meta table for DML (#20763)
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/lock_meta.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/types.go
Labels: size/M, kind/refactor
