Repository matrixorigin/matrixone, pull requests merged in 2024-07, with the labels that each got.

#17235 fileservice: optimize io merging
  pkg/fileservice/cache.go
  pkg/fileservice/io_merger.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/M, kind/enhancement

#17179 Fix show columns compatibility issues
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_like.result
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/show/show5.result
  test/distributed/cases/dml/show/show5.sql
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/pessimistic_transaction/catalog.result
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/bug, size/M

#17186 [fix] remove unnecessary values from the second parameter of prefix_in (cp #17111 to 1.2)
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/list_builtIn.go
Labels: kind/bug, size/S

#17219 Add CoreDump when CachedData is nil
  pkg/objectio/cache.go
  pkg/objectio/funcs.go
Labels: kind/bug, size/S

#17222 memorycache: do not allow nil Data
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/data_test.go
Labels: size/S, kind/enhancement

#17224 fix always return illegal state error on special connection
  pkg/common/morpc/backend.go
Labels: kind/bug, size/S

#17238 fix unlock fatal when tn restart
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/txn/client/operator_test.go
Labels: size/M

#17228 [bug] proxy: fix the connection id when send request to cn server.
  pkg/proxy/client_conn.go
Labels: kind/bug, size/S

#17089 fix rpc metrics
  pkg/common/morpc/client.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_rpc.go
Labels: kind/bug, size/S

#17237 fix unlock fatal when tn restart
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/log.go
  pkg/lockservice/service_remote_test.go
  pkg/lockservice/service_test.go
  pkg/lockservice/types.go
  pkg/txn/client/operator_test.go
Labels: size/M

#17233 Some PRs from 1.2 cp to main
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/objectio/writer.go
  pkg/pb/api/api.go
  pkg/pb/api/api.pb.go
  pkg/sql/plan/function/ctl/cmd_disk_cleaner.go
  pkg/sql/plan/function/ctl/types.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/gc/types.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  proto/api.proto
Labels: kind/bug, size/M, kind/enhancement

#17249 The global checkpoint only collects the node of the last deltaLoc
  pkg/vm/engine/tae/db/gc/check.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#17113 pick remote-run fix from 1.2 to main.
  pkg/cnservice/server.go
  pkg/common/morpc/mock_morpc/types_mock.go
  pkg/common/morpc/server.go
  pkg/common/morpc/types.go
  pkg/pb/pipeline/pipeline.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/colexec/dispatch/sendfunc.go
  pkg/sql/colexec/dispatch/types.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/sql/colexec/types2.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scopeRemoteRunTypes_test.go
  pkg/txn/rpc/server_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_pipeline.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/pipeline.go
  pkg/vm/engine/tae/logtail/service/session_test.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
  proto/pipeline.proto
Labels: kind/bug, size/XL

#17255 add debug info for remap error
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: kind/bug, size/M

#17250 fileservice: use wrapped standard retryer in AWS sdk
  pkg/fileservice/aws_sdk_v2.go
Labels: kind/bug, size/S

#17260 cherry-pick stats related fix into 1.2-dev
  pkg/sql/compile/compile.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_util.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/partition_list.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/like.result
Labels: kind/bug, size/S

#17265 fix a bug that hashmap allocated more than once in broadcast join
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#17253 malloc: remove deallocate counter from MetricsAllocator
  pkg/common/malloc/default.go
  pkg/common/malloc/metrics_allocator.go
  pkg/common/malloc/metrics_allocator_test.go
  pkg/fileservice/malloc.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/mem.go
Labels: size/S, kind/enhancement

#17240 update delete by deltaloc
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Enhancement

#17268 cp 17265 into 1.2-dev
  pkg/sql/compile/compile.go
Labels: kind/bug, size/S

#17264 support last_day and makedate
  pkg/container/types/date.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/feature, size/M

#17271 Fix-snapshot-read-bug[txn is stale: timestamp is too small]
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: size/S

#17274 fix restore account with cluster snapshot
  pkg/frontend/snapshot.go
Labels: kind/bug, size/S

#17275 reduce mem allocate in ForeachWindowVarlen
  pkg/vm/engine/tae/containers/utils.go
Labels: size/XS, kind/enhancement

#17276 Enable merging based on delta location
  Makefile
  pkg/vm/engine/disttae/logtailreplay/object_filter.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/M, kind/enhancement

#17277 support last_day and makedate (#1.2-dev)
  pkg/container/types/date.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/feature, size/M

#17256 add debug info for remap error
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: kind/bug, size/M

#17257 cherry-pick: remove compilectx
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/compileService_test.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/fuzzyCheck.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/compile/types.go
Labels: size/L, kind/enhancement

#17172 fix show create External table-1.2-dev
  pkg/sql/plan/build_show_util.go
  test/distributed/cases/dml/show/show_create_table.result
  test/distributed/cases/dml/show/show_create_table.sql
  test/distributed/resources/external_table_file/extable.csv
Labels: kind/bug, size/S

#17199 Fix show columns compatibility issues1.2 dev
  pkg/sql/plan/build_show.go
  pkg/sql/plan/mock.go
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_change_column.result
  test/distributed/cases/ddl/alter_table_check_foreign_key.result
  test/distributed/cases/ddl/alter_table_check_foreignkey_reference.result
  test/distributed/cases/ddl/alter_table_modify_column.result
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_like.result
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/show/show5.result
  test/distributed/cases/dml/show/show5.sql
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/pessimistic_transaction/catalog.result
  test/distributed/cases/tenant/pub_sub.result
  test/distributed/cases/zz_accesscontrol/inner_object.result
Labels: kind/bug, size/M

#17283 fix bvt test
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/XS

#17284 fix bvt test(#1.2-dev)
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/XS

#17296 fix a bug that cause wrong parallelism for tpch
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#17297 cherry-pick to 1.2-dev 'fix a bug that cause wrong parallelism for tpch'
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#17305 add bvt test for restore system table
  test/distributed/cases/snapshot/snapshot_restore_system_table.result
  test/distributed/cases/snapshot/snapshot_restore_system_table.sql
Labels: size/M, kind/test-ci

#17272 cherry-pick runtime metrics changes
  pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
Labels: size/M, kind/enhancement

#17266 [cherry-pick] support Compile service
  pkg/frontend/computation_wrapper.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/compileService_test.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/service/service.go
Labels: kind/bug, kind/feature, size/M

#17247 fix: delete from mo_catalog.mo_increment_columns only when account ex…
  pkg/incrservice/store_sql.go
  pkg/incrservice/store_sql_test.go
  pkg/util/executor/test/sql_executor_mock.go
Labels: kind/bug, size/M

#17291 enable deltaLoc merge by default
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/rpc/inspect.go
Labels: size/S, kind/enhancement

#17310 fix a bug that cause tpch performance regression
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#17278 fix dual
  pkg/common/moerr/error.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/dml/select/dual.result
  test/distributed/cases/dml/select/dual.sql
Labels: kind/bug, size/S

#17273 Fix set global var do not work cross cns
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result_test.go
  pkg/frontend/variables.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/S

#17313 Fix-bugs[Dup/WW/Data-corruption]
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S

#17312 Cherry-pick-fix-bugs[Dup/WW/Data-corruption]
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/S

#17282 When DDL statement has been executed within a transaction, force the use of a single CN
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile_test.go
  pkg/sql/compile/scope_test.go
  pkg/txn/client/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.result
  test/distributed/cases/ddl/alter_table_add_drop_primary_key.sql
Labels: kind/bug, size/M

#17279 fix dual
  pkg/common/moerr/error.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/dml/select/dual.result
  test/distributed/cases/dml/select/dual.sql
Labels: kind/bug, size/S

#17311 add case for cluster level snapshot restore pub-sub table
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
Labels: kind/feature, size/XL

#17315 cherry-pick to 1.2-dev 'fix a bug that cause tpch performance regression '
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/S

#17322 fix bugs for between function in prepare mode
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S

#17321 retry lock when cn down
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/S

#17320 retry lock when cn down
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/S

#17323 [Cherry-pick] Fix set global var do not work cross cns
  pkg/frontend/authenticate_test.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/query_result_test.go
  pkg/frontend/variables.go
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: kind/bug, size/S

#17242 modify code owner of join and shuffle
  CODEOWNERS
Labels: kind/documentation, size/S

#17306 Cherry pick- fix-snapshot-read-bug[txn is stale: timestamp is too small] (#17271)
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: size/S

#17245 fileservice: intern strings in slow event logger
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/event_logger.go
  pkg/fileservice/event_logger_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/string.go
Labels: size/M, kind/enhancement

#17319 fix data race when get deltaloc on 1.2-dev
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#17328 Merge delta loc 1.2 dev
  Makefile
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/logtailreplay/object_filter.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: size/M, kind/enhancement

#17285 fix enum type op in one transaction (#1.2-dev)
  pkg/container/types/enum.go
  pkg/container/types/enum_test.go
  pkg/frontend/export.go
  pkg/frontend/output.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/objectio/utils.go
  pkg/sql/colexec/aggexec/argument.go
  pkg/sql/colexec/aggexec/fromBytesRetFixed.go
  pkg/sql/colexec/aggexec/fromFixedRetBytes.go
  pkg/sql/colexec/aggexec/fromFixedRetFixed.go
  pkg/sql/colexec/aggexec/multi.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/top/top.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/function/agg/any_value.go
  pkg/sql/plan/function/agg/max.go
  pkg/sql/plan/function/agg/min.go
  pkg/sql/plan/function/func_cast.go
  pkg/sql/plan/function/func_mo.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/testutil/util_new.go
Labels: kind/bug, size/M

#17334 add bvt tag and fix bvt
  test/distributed/cases/snapshot/sys_restore_system_table_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_newnonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_nonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.sql
  test/distributed/cases/tenant/pub_sub2.result
  test/distributed/cases/tenant/pub_sub2.sql
Labels: kind/bug, size/S

#17317 fix data race when get deltaLoc
  pkg/vm/engine/tae/db/dbutils/mem.go
  pkg/vm/engine/tae/db/scannerop.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#17216 memorycache: evict before allocate
  pkg/fileservice/malloc.go
  pkg/fileservice/memorycache/cache.go
  pkg/fileservice/memorycache/cache_test.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/hashmap.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/hashmap_test.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/types.go
  pkg/fileservice/memorycache/lrucache/lru.go
  pkg/fileservice/memorycache/lrucache/lru_test.go
  pkg/fileservice/memorycache/lrucache/shard.go
  pkg/fileservice/memorycache/lrucache/types.go
Labels: size/M, kind/enhancement

#17324 improve dn flush and merge log prints
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushdeletes.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4

#17326 cluser level snapshot restore case
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_newnonsys_account.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_newnonsys_account.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_nonsys_account.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_sys_account.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_sys_account.sql
Labels: kind/feature, size/XXL

#17307 Refactor some logic for prepare
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session_test.go
  pkg/frontend/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/scope.go
  pkg/vm/pipeline/types.go
Labels: size/M, kind/refactor

#17336 fix makedate and lastday func
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/M

#17338 Fix unsafe.string causing some stored values to be changed
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/types.go
  pkg/frontend/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#17110 [enhancement] stats: reduce the parallel goroutines to update stats
  pkg/vm/engine/disttae/stats.go
Labels: size/S, kind/enhancement

#17344 Fix Location's Extend is 0 when call UpdateTableStats
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#17349 [pick to 1.2] fix a bug that process's cancel not match to its context
  pkg/sql/compile/remoterunServer.go
  pkg/vm/process/process.go
Labels: kind/bug, size/S

#17348 fix a bug that process's cancel not match to its context
  pkg/sql/compile/remoterunServer.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#17346 Fix Location's Extend is 0 when call UpdateTableStats for 1.2
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#17343 fix makedate and lastday func(#1.2-dev)
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/M

#17267 fileservice: use wrapped standard retryer in AWS sdk (#17250)
  pkg/fileservice/aws_sdk_v2.go
Labels: size/S, kind/enhancement

#17246 update delete by deltaloc
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Bug fix

#17351 log some filter exprs
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#17352 fix Compile clear() method bug.
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#17330 fileservice: limit the number of concurrent object storage operations to 100
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/http_client.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_semaphore.go
  pkg/fileservice/s3_fs.go
Labels: size/M, kind/enhancement

#17353 [pick to main] fix Compile clear() bug.
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#17363 [bug] stats: fix hang issue
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#17362 Revert "fix Compile clear() method bug and [pick to 1.2] fix a bug that process's cancel not match to its context "
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterunServer.go
  pkg/vm/process/process.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#17364 [bug] stats: fix hang issue
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#17356 add filter expr log and optimize expr print
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/rpc/utils.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#17361 [fix] : still check dup even if the value is generated by incrservice
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS

#17217 Add jq and try_jq function.
  go.mod
  go.sum
  pkg/container/nulls/nulls.go
  pkg/container/vector/functionTools.go
  pkg/sql/plan/function/baseTemplate.go
  pkg/sql/plan/function/func_builtin_jq.go
  pkg/sql/plan/function/function.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_jq.result
  test/distributed/cases/function/func_jq.sql
Labels: kind/feature, size/XL, Tests, Enhancement, Review effort [1-5]: 4

#17368 Revert "fix a bug that process's cancel not match to its context (#17…
  pkg/sql/compile/remoterunServer.go
  pkg/vm/process/process.go
  pkg/vm/process/types.go
Labels: kind/bug, size/S

#17372 fix cannot restart lockservice
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/service_test.go
Labels: size/S

#17332 Add PrepareParams into ProcessInfo
  pkg/container/vector/tools.go
  pkg/container/vector/vector.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/plan/shuffle.go
  pkg/vm/process/process_codec.go
  proto/pipeline.proto
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/M, Enhancement, Bug fix

#17374 fix restore to new account with cluster sp
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/cluster/resore_account_using_cluster_sp_to_new.result
  test/distributed/cases/snapshot/cluster/resore_account_using_cluster_sp_to_new.sql
  test/distributed/cases/snapshot/cluster/restore_database_using_cluster_sp_to_new.result
  test/distributed/cases/snapshot/cluster/restore_database_using_cluster_sp_to_new.sql
  test/distributed/cases/snapshot/cluster/restore_table_using_cluster_sp_to_new.result
  test/distributed/cases/snapshot/cluster/restore_table_using_cluster_sp_to_new.sql
Labels: kind/bug, size/XXL

#17371 fix cannot restart lockservice
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/service_test.go
Labels: size/S

#17369 support reload auto increment cache to 1.2
  pkg/cnservice/server.go
  pkg/cnservice/server_query.go
  pkg/cnservice/types.go
  pkg/incrservice/service.go
  pkg/incrservice/types.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/plan/function/ctl/cmd_reload_increment.go
  pkg/sql/plan/function/ctl/types.go
  proto/query.proto
Labels: kind/feature, size/M

#17373 only create buffer when err is nil
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: kind/bug, size/S

#17360 fileservice: allow loading file infos asynchronously in disk cache
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/S, kind/enhancement

#17377 Support reload auto increment cache
  pkg/cnservice/server.go
  pkg/cnservice/server_query.go
  pkg/cnservice/types.go
  pkg/incrservice/service.go
  pkg/incrservice/service_test.go
  pkg/incrservice/store_mem.go
  pkg/incrservice/types.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/plan/function/ctl/cmd_reload_increment.go
  pkg/sql/plan/function/ctl/types.go
  proto/query.proto
Labels: kind/feature, size/M

#17383 Expansion 1.2.2 Upgrade Package
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v1_2_2/log.go
  pkg/bootstrap/versions/v1_2_2/upgrade.go
Labels: kind/feature, size/M

#17387 release unused memory in shuffleRange
  pkg/pb/statsinfo/shuffle.go
  pkg/sql/plan/shuffle_test.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#17357 forward sharding read txn table rows
  pkg/cnservice/server.go
  pkg/cnservice/server_query.go
  pkg/common/morpc/buffer_pool.go
  pkg/common/morpc/method_based.go
  pkg/common/morpc/method_based_test.go
  pkg/common/morpc/reuse.go
  pkg/common/morpc/types.go
  pkg/fileservice/remote_cache_test.go
  pkg/proxy/conn_migration_test.go
  pkg/queryservice/coredump.go
  pkg/queryservice/query_service.go
  pkg/queryservice/query_service_test.go
  pkg/queryservice/rpc_version.go
  pkg/shardservice/service_read.go
  pkg/shardservice/service_remote.go
  pkg/shardservice/shard_server.go
  pkg/shardservice/storage_mem.go
  pkg/shardservice/storage_mo.go
  pkg/shardservice/types.go
  pkg/sql/colexec/table_function/system_view_test.go
  pkg/sql/plan/function/ctl/cmd_tracespan_test.go
  pkg/tnservice/store.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
Labels: kind/feature, size/M

#17375 only create buffer when err is nil
  pkg/vm/engine/tae/mergesort/reshaper.go
Labels: kind/bug, size/XS

#17386 cp to 1.2-dev "release unused memory in shuffleRange"
  pkg/pb/statsinfo/shuffle.go
  pkg/sql/plan/shuffle_test.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/S

#17390 add clean commit state log
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/log.go
Labels: size/S

#17385 don't calculate stats for limit 0 query
  pkg/sql/plan/build.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement

#17391 add clean commit state log
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/log.go
Labels: size/S

#17400 cp to 1.2-dev "don't calculate stats for limit 0 query"
  pkg/sql/plan/build.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/stats.go
Labels: size/S

#17384 Extend1.2.2 upgrade package main
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v1_2_2/log.go
  pkg/bootstrap/versions/v1_2_2/upgrade.go
Labels: kind/feature, size/M

#17401 [enhancement] proxy: remove error logs caused by hearteabt of LB.
  pkg/proxy/client_conn.go
  pkg/proxy/error.go
Labels: size/S, kind/enhancement

#17230 fix: scope.instruction as tree
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/pipeline.go
  pkg/vm/pipeline/types.go
  pkg/vm/types.go
  pkg/vm/vm.go
Labels: size/XL, kind/refactor

#17395 fix bug: compile.originSQL is empty in some case
  pkg/frontend/computation_wrapper.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S

#17418 [enhancement] stats: add factor to update worker number.
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
Labels: size/S, kind/enhancement

#17399 [enhancement] proxy: remove error logs caused by hearteabt of LB.
  pkg/proxy/client_conn.go
  pkg/proxy/error.go
Labels: size/S, kind/enhancement

#17405 Forward sharding read txn table size
  pkg/cnservice/server.go
  pkg/shardservice/types.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/disttae/txn_table_sharding_handle.go
Labels: kind/feature, size/M

#17422 [enhancement] stats: do not update the same key at the same time.
  pkg/vm/engine/disttae/stats.go
Labels: size/S, kind/enhancement

#17398 fileservice: set finalizer on read closer to avoid potential leaks
  pkg/fileservice/s3_fs.go
Labels: size/XS, kind/enhancement

#17432 fix change morpc backend state to 1.2
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: kind/bug, size/S

#17393 adjust some stats and shuffle strategy
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
Labels: size/S, kind/enhancement

#17434 metric: fix typo and register fsWriteCounter
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/metrics.go
Labels: kind/bug, size/XS

#17423 [fix] don't push LIMIT clause to index table if main table has filters
  pkg/sql/plan/apply_indices.go
Labels: kind/bug, size/S

#17429 cherry-pick some fileservice changes from main branch
  pkg/fileservice/aws_sdk_v2.go
  pkg/fileservice/cache.go
  pkg/fileservice/event_logger.go
  pkg/fileservice/event_logger_test.go
  pkg/fileservice/http_client.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/io_merger.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_semaphore.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/string.go
Labels: size/M, kind/enhancement

#17406 [Fix] Alter table add column with lower_case_table_names = 0
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/parsers/dialect/mysql/mysql_lexer.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/object_name.go
  pkg/sql/plan/build_show.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
Labels: kind/bug, size/XXL

#17436 using process memory usage for background task memory throttle 1.2
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
Labels: size/S, Review effort [1-5]: 3, Enhancement

#17433 metric: fix typo and register fsWriteCounter
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/metrics.go
Labels: kind/bug, size/XS

#17431 fix change morpc backend state
  pkg/common/morpc/backend.go
  pkg/common/morpc/backend_test.go
Labels: kind/bug, size/S

#17397 fileservice: set finalizer on read closer to avoid potential leaks
  pkg/fileservice/s3_fs.go
Labels: size/XS, kind/enhancement

#17437 1.2 optimize flush and merge prints
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushdeletes.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4

#17355 malloc: add allocated and inuse objects metrics to MetricsAllocator
  pkg/common/malloc/default.go
  pkg/common/malloc/metrics_allocator.go
  pkg/common/malloc/metrics_allocator_test.go
  pkg/fileservice/malloc.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/mem.go
Labels: size/S, kind/enhancement

#17447 fix possible flush panic
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: kind/bug, size/XS

#17446 [fix] don't push LIMIT clause to index table if main table has filters
  pkg/sql/plan/apply_indices.go
Labels: kind/bug, size/S

#17438 fix: setAnalyzeInfo, opInfo forgot set OpType
  pkg/vm/vm.go
Labels: kind/refactor, size/XS

#17450 fix ut Test_saveQueryResultMeta panic
  pkg/frontend/compiler_context.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#17456 Fix TestSnapshotMeta data race&failed
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, kind/test-ci

#17442 cluster level snapshot restore view case
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_newnonsys_account.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_newnonsys_account.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_newnonsys.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_newnonsys.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_nonsys.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_nonsys.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_sys.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_sys.sql
Labels: kind/feature, size/XXL

#17461 remove an info-level log.
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#17427 [enhancement] stats: do not update the same key at the same time.
  pkg/vm/engine/disttae/stats.go
Labels: kind/bug, size/S

#17440 The global checkpoint only collects the node of the last deltaLoc
  pkg/vm/engine/tae/db/gc/check.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/tables/updates/mvcc.go
Labels: kind/bug, size/S

#17457 Add bvt
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: size/S, kind/test-ci

#17460 Fix TestSnapshotMeta data race&failed for 1.2
  pkg/vm/engine/tae/db/gc/checkpoint.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, kind/test-ci

#17462 [pick to main] remove an info-level log.
  pkg/sql/compile/compile.go
Labels: kind/bug, size/XS

#17454 sort objects in ascending order
  pkg/vm/engine/tae/db/merge/mod.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/scannerop.go
Labels: kind/bug, size/S

#17415 Fix ww/dup/data not found when unsub constantly
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/partition_reader.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/M

#17359 fileservice: load disk cache file infos in parallel and asynchronously
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
Labels: size/S, kind/enhancement

#17417 using process memory usage for background task memory throttle
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/merge/policyBasic.go
  pkg/vm/engine/tae/db/scannerop.go
Labels: size/M, Review effort [1-5]: 3, Enhancement

#17466 [BugFix]: Reduce mp.Grow2 in SEMI Join and TableScan Operator
  pkg/container/vector/vector.go
  pkg/sql/colexec/semi/join.go
  pkg/vm/engine/tae/blockio/read.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#17403 fix makedate and last_day func
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/M

#17452 fix restore cluster table
  pkg/frontend/snapshot.go
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster/restore_cluster_table.sql
Labels: kind/bug, size/XL

#17428 Refactor prepare to reuse Compile
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#17444 cluster level snapshot restore system table case
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_nonsys.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_nonsys.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_sys_account.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_sys_account.sql
Labels: kind/feature, size/XXL

#17469 fileservice: fix TestFuzzingDiskS3
  pkg/fileservice/fuzz_test.go
Labels: size/XS, kind/enhancement

#17472 Fix GC MaxConsumed For Backup
  pkg/backup/tae.go
  pkg/vm/engine/tae/blockio/types.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
Labels: kind/bug, size/M

#17479 Fix merge mem contro 1.2
  pkg/vm/engine/tae/db/merge/policyBasic.go
Labels: kind/bug, size/XS

#17480 Revert "Refactor prepare to reuse Compile (#17428)"
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/sql/colexec/connector/connector.go
  pkg/sql/colexec/dispatch/dispatch.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compileService.go
  pkg/sql/compile/reuse.go
  pkg/sql/compile/scope.go
Labels: kind/bug, size/S

#17473 fix makedate and last_day func (#1.2-dev)
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  test/distributed/cases/function/func_last_day.result
  test/distributed/cases/function/func_last_day.sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: kind/bug, size/M

#17458 Add bvt
  test/distributed/cases/system_variable/lower_case_table_names.result
  test/distributed/cases/system_variable/lower_case_table_names.sql
Labels: size/S, kind/test-ci
