Repository matrixorigin/matrixone, pull requests merged in 2024-09, with the labels that each got.

#18450 Fix snapshot refers
  pkg/vm/engine/tae/db/gc/table.go
Labels: kind/bug, size/S

#18427 refactor: csvparser.readBlock
  pkg/sql/util/csvparser/csv_parser.go
Labels: size/S, kind/refactor

#18469 add some disttae testing utils
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/tae_engine.go
  pkg/vm/engine/test/testutil/util.go
Labels: size/M, kind/refactor, kind/test-ci

#18417 fileservice, cnservice: dynamic cache size
  pkg/cnservice/server_query.go
  pkg/cnservice/server_query_test.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/disk_object_storage.go
  pkg/fileservice/disk_object_storage_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/object_storage_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: size/L, kind/enhancement

#18464 fileservice: release semaphore after reader close in objectStorageSemaphore.Read
  pkg/fileservice/object_storage_semaphore.go
Labels: kind/bug, size/S

#18456 add changes handle
  pkg/frontend/test/engine_mock.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/types.go
Labels: kind/feature, size/XL

#18451 fix suspend not effect
  pkg/cnservice/server_query.go
  pkg/frontend/authenticate.go
  pkg/frontend/routine_manager.go
  pkg/queryservice/query_service.go
Labels: kind/bug, size/S

#18459 fix rename table(#1.2-dev)
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/ddl/alter_table_AddDrop_column.result
  test/distributed/cases/ddl/alter_table_rename_new_synax.result
  test/distributed/cases/ddl/alter_table_rename_new_synax.sql
Labels: kind/bug, size/S

#18488 fix delete routine log
  pkg/frontend/routine_manager.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#18480 Fix Ceiling(1.2-dev)
  pkg/sql/plan/base_binder.go
  test/distributed/cases/function/func_math_ceil.result
  test/distributed/cases/function/func_math_ceil.test
Labels: size/S

#18477 fix ut TestManyRangeLockInManyGoroutines data race
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
Labels: size/S

#18479 Fix Ceiling
  pkg/sql/plan/base_binder.go
  test/distributed/cases/function/func_math_ceil.result
  test/distributed/cases/function/func_math_ceil.test
Labels: size/S

#18500 fix drop account error
  pkg/frontend/authenticate.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18463 fileservice: release semaphore after reader close in objectStorageSemaphore.Read
  pkg/fileservice/object_storage_semaphore.go
Labels: kind/bug, size/S

#18485 to 1.2: adding object count metric for accounts
  pkg/bootstrap/versions/v1_2_3/tenant_upgrade_list.go
  pkg/bootstrap/versions/v1_2_3/upgrade.go
  pkg/frontend/compiler_context.go
  pkg/frontend/show_account.go
  pkg/frontend/show_account_test.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_server.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/db/test/storage_usage_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
Labels: size/L

#18489 malloc: use unique.Handle in GetStacktrace
  pkg/common/malloc/leaks_tracker.go
  pkg/common/malloc/leaks_tracking_allocator.go
  pkg/common/malloc/stacktrace.go
  pkg/common/malloc/stacktrace_test.go
  pkg/common/mpool/alloc.go
  pkg/common/mpool/alloc_tracing.go
  pkg/common/mpool/mpool.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18421 Fengttt conn
  pkg/embed/benchmark_test.go
  pkg/frontend/variables.go
Labels: size/S, kind/test-ci

#18394 fileservice: do disk cache eviction after loading and before writing files
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
Labels: kind/bug, size/M

#18468 print debug message when waiting message timeout
  pkg/sql/colexec/anti/join.go
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/loopjoin/join.go
  pkg/sql/colexec/mark/join.go
  pkg/sql/colexec/product/product.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/right/join.go
  pkg/sql/colexec/rightanti/join.go
  pkg/sql/colexec/rightsemi/join.go
  pkg/sql/colexec/semi/join.go
  pkg/sql/colexec/single/join.go
  pkg/sql/compile/compile2.go
  pkg/vm/message/joinMapMsg.go
  pkg/vm/message/message.go
  pkg/vm/message/message_test.go
  pkg/vm/message/runtimeFilterMsg.go
  pkg/vm/message/topValueMsg.go
Labels: kind/bug, size/M

#18506 refactor tombstone read related code
  pkg/objectio/object_stats.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/catalog/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: size/M, kind/refactor, Enhancement, Review effort [1-5]: 4

#18462 refactoring dispatch scopes
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/plan/stats.go
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: size/M, kind/refactor

#18496 fix the condition for runtime filters
  pkg/sql/plan/agg_pushdown_pullup.go
  pkg/sql/plan/runtime_filter.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18503 remove restriction for top value optimization
  pkg/sql/plan/message.go
  test/distributed/cases/optimizer/pushdown.result
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18504 remove restriction for top value optimization to 1.2-dev
  pkg/sql/plan/message.go
  test/distributed/cases/optimizer/pushdown.result
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 1

#18491 fix suspend not effect in main
  pkg/cnservice/server_query.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
  pkg/queryservice/query_service.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Enhancement, Bug fix

#18498 fix too early return in processLoadLocal
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/util.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18514 release hashmap memory when input batch rowcnt is 0
  pkg/sql/colexec/hashbuild/types.go
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  pkg/sql/colexec/shufflebuild/build.go
  pkg/sql/colexec/shufflebuild/types.go
  pkg/vm/message/joinMapMsg.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18522 fileservice: also acquire semaphore in List and Write
  pkg/fileservice/object_storage_semaphore.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18510 refactor the run method of pipelines
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
Labels: size/S, kind/refactor, Review effort [1-5]: 3, Enhancement

#18525 code refactoring of some pipelines
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Tests, Enhancement

#18517 remove unused code
  pkg/objectio/const.go
  pkg/objectio/types.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/catalog/base.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/dbmvccnode.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/tablemvccnode.go
  pkg/vm/engine/tae/common/bitmap.go
  pkg/vm/engine/tae/common/id.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/iface/handle/object.go
  pkg/vm/engine/tae/iface/handle/relation.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/adaptors.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/txn/txnbase/handle.go
  pkg/vm/engine/tae/txn/txnimpl/object.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/reader_test.go
Labels: size/M, kind/refactor, Enhancement, Review effort [1-5]: 2

#18536 Fix data race
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/pnode.go
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18490 fix bug: make sure vector will be free in some case
  pkg/sql/colexec/lockop/lock_op.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/lockop/types.go
  pkg/sql/colexec/mergeorder/order.go
  pkg/sql/plan/build_insert.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#18532 Io access time consumptionissue 1.2 dev
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18528 fix TestGetInitPort
  pkg/embed/cluster_test.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#18509 fix disttae mpool leak
  pkg/container/batch/batch.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18540 fileservice: log rc operations to help debugging
  pkg/fileservice/memorycache/checks/interval/interval_tree.go
  pkg/fileservice/memorycache/checks/interval/overlap.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/hashmap.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/hashmap_test.go
  pkg/fileservice/memorycache/lrucache/internal/hashmap/types.go
  pkg/fileservice/memorycache/refcnt.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement, Bug fix

#18546 Isolate IOAccessTime When Compile.runOnce
  pkg/sql/compile/compile.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#18549 refactor pipelines of broadcast join to reduce pipeline break
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
  pkg/sql/compile/types.go
  pkg/sql/plan/shuffle.go
  proto/pipeline.proto
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Tests, Enhancement

#18560 remove transfer delete log
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/refactor, size/XS, Enhancement, Review effort [1-5]: 2

#18515 add test case for create partition based shard table
  pkg/bootstrap/service.go
  pkg/bootstrap/versions/v1_3_0/cluster_upgrade_list.go
  pkg/cnservice/server.go
  pkg/embed/cluster.go
  pkg/frontend/authenticate.go
  pkg/frontend/test/mock_shard/types.go
  pkg/shardservice/env.go
  pkg/shardservice/runtime.go
  pkg/shardservice/scheduler_allocate.go
  pkg/shardservice/scheduler_down.go
  pkg/shardservice/service.go
  pkg/shardservice/types.go
  pkg/sql/compile/ddl.go
  pkg/tests/shard/partition_based_test.go
  pkg/tests/shard/shard_storage_test.go
  pkg/tests/shard/shard_test.go
  pkg/tests/testutils/test_utils.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/metadata/information_schema.result
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.result
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/tenant/drop_account.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
Labels: size/L, kind/test-ci, Review effort [1-5]: 3, Tests, Enhancement

#18478 fix ut TestManyRangeLockInManyGoroutines data race
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/waiter.go
  pkg/lockservice/waiter_events.go
Labels: size/S

#18557 save transfer page memory usage
  pkg/vm/engine/tae/model/pages.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18554 fix a bug that sometimes hashmap is not released
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  pkg/sql/colexec/table_scan/types.go
  pkg/sql/compile/scope.go
  pkg/vm/message/joinMapMsg.go
  pkg/vm/message/message.go
  pkg/vm/message/runtimeFilterMsg.go
  pkg/vm/message/topValueMsg.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#18556 fix: buildload LoadWriteS3
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_load.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18460 refactor: value_scan
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/connector/connector_test.go
  pkg/sql/colexec/dispatch/dispatch_test.go
  pkg/sql/colexec/group/group_test.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/mergegroup/group_test.go
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/output/output_test.go
  pkg/sql/colexec/top/top_test.go
  pkg/sql/colexec/value_scan/types.go
  pkg/sql/colexec/value_scan/value_scan.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterunClient.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/vm/pipeline/pipeline.go
  proto/pipeline.proto
Labels: size/M, kind/refactor

#18526 support group by with rollup in parser
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/select.go
  pkg/sql/plan/query_builder.go
Labels: kind/feature, size/XXL, Review effort [1-5]: 3, Tests, Enhancement

#18545 Fix some data race in frontend
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/protocol.go
  pkg/frontend/routine_manager_test.go
  pkg/frontend/server.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18541 fix TransferDeleteIntent for S3 tombstone
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#18529 Upgrade panic bug 1.2 dev
  pkg/bootstrap/service_upgrade.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18552 update CODEOWNERS
  CODEOWNERS
Labels: size/XS, kind/enhancement, Enhancement, Review effort [1-5]: 1

#18580 fix checkpoint entry use after clean
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18589 fileservice: fix object storage semaphore
  pkg/fileservice/io.go
  pkg/fileservice/object_storage_semaphore.go
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/S, Enhancement, Review effort [1-5]: 2, Bug fix

#18569 fileservice: re-implement memory cache with fifocache
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/fscache/data.go
  pkg/fileservice/fscache/data_cache.go
  pkg/fileservice/fuzz_test.go
  pkg/fileservice/interval/interval_tree.go
  pkg/fileservice/interval/interval_tree_test.go
  pkg/fileservice/interval/overlap.go
  pkg/fileservice/interval/overlap_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/malloc.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/memorycache/cache.go
  pkg/fileservice/memorycache/cache_test.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/data_test.go
  pkg/fileservice/memorycache/lrucache/list.go
  pkg/fileservice/memorycache/lrucache/lru.go
  pkg/fileservice/memorycache/lrucache/lru_test.go
  pkg/fileservice/memorycache/lrucache/pool.go
  pkg/fileservice/memorycache/lrucache/shard.go
  pkg/fileservice/memorycache/lrucache/types.go
  pkg/fileservice/memorycache/refcnt.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
Labels: size/L, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18379 reduce *Conn.Read syscall
  pkg/frontend/mysql_buffer.go
  pkg/frontend/mysql_buffer_test.go
  pkg/frontend/routine_manager_test.go
Labels: size/M, kind/enhancement

#18588 Aggr statements with same error msg to keep error msg in 1.2-dev
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  test/distributed/cases/statement_query_type/aggr_error_stmt.result
  test/distributed/cases/statement_query_type/aggr_error_stmt.sql
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18581 delay ranges call for dml queries [part 1]
  pkg/sql/compile/scope.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement, Bug fix

#18570 optimize shuffle plans
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18537 Aggr statements with same error msg and keep the error msg info
  pkg/util/trace/impl/motrace/report_statement.go
  pkg/util/trace/impl/motrace/report_statement_test.go
  test/distributed/cases/statement_query_type/aggr_error_stmt.result
  test/distributed/cases/statement_query_type/aggr_error_stmt.sql
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.result
  test/distributed/cases/zz_statement_query_type/aggr_error_stmt.sql
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18574 optimize insert pipelines to reduce pipeline berak
  pkg/sql/compile/compile.go
  pkg/sql/compile/util.go
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Enhancement, Code Refactoring

#18607 skip restart cn test case
  pkg/embed/cluster_test.go
  pkg/tests/shard/replica_test.go
Labels: size/XS, kind/test-ci, Tests, Review effort [1-5]: 1

#18609 update github.com/parquet-go/parquet-go
  go.mod
  go.sum
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18542 reduce insert memory usage
  pkg/container/vector/vector.go
  pkg/container/vector/vector_test.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/merge_util.go
  pkg/sql/colexec/s3util.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/L, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18573 adapt old config observablity::metricUpdateStorageUsageInterval
  pkg/config/configuration.go
  pkg/config/configuration_test.go
  pkg/frontend/test/mock_shard/types.go
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18613 [bug] proxy: session does not transfer after COM_STMT_CLOSE.
  pkg/proxy/tunnel.go
  pkg/proxy/util.go
  pkg/proxy/util_test.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Bug fix

#18550 Upgrade panic bug main
  pkg/bootstrap/service_test.go
  pkg/bootstrap/service_upgrade.go
  pkg/bootstrap/versions/version.go
Labels: kind/bug, size/M, Review effort [1-5]: 2, Bug fix

#18610 retry lock without lock table
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: size/M, Review effort [1-5]: 3, Tests, Enhancement

#18612 optimize pipelines for external scan to reduce pipeline breaks
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope_test.go
Labels: size/S, kind/refactor, Review effort [1-5]: 3, Enhancement

#18582 fix panic in ut
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18586 remove unnecessary log print
  pkg/sql/plan/stats.go
Labels: size/XS, kind/enhancement, Enhancement, Review effort [1-5]: 1

#18622 fix leak info & load hung
  pkg/cnservice/server.go
  pkg/frontend/authenticate.go
  pkg/frontend/back_result_row_stmt.go
  pkg/frontend/back_status_stmt.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol_test.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/session_test.go
  pkg/frontend/status_stmt.go
  pkg/frontend/test/txn_mock.go
  pkg/frontend/txn.go
  pkg/frontend/txn_test.go
  pkg/frontend/types.go
  pkg/frontend/util.go
  pkg/frontend/util_test.go
  pkg/pb/txn/txn.pb.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/operator.go
  pkg/txn/client/testutil.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/util/metric/v2/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/entire_engine_test.go
  proto/txn.proto
Labels: kind/bug, size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement, Bug fix

#18587 fix: 修改load strict参数默认行为
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/plan/build_load.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18579 mpool: remove memHdr.allocateStacktraceID
  pkg/common/mpool/alloc.go
  pkg/common/mpool/mpool.go
  pkg/sql/colexec/mergetop/top_test.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18592 fileservice: optimize io merger
  pkg/fileservice/file_service_test.go
  pkg/fileservice/fuzz_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18564 refactor some code for the future code reuse for disttae and tae
  pkg/container/vector/vector.go
  pkg/frontend/test/engine_mock.go
  pkg/objectio/types.go
  pkg/sql/colexec/index_metadata_test.go
  pkg/sql/colexec/table_scan/table_scan.go
  pkg/sql/colexec/table_scan/table_scan_test.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/filter.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/pk_filter.go.go
  pkg/vm/engine/disttae/pk_filter_mem.go
  pkg/vm/engine/disttae/pk_filter_mem_test.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/engine_util/expr_filter.go
  pkg/vm/engine/engine_util/expr_util.go
  pkg/vm/engine/engine_util/expr_util_test.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/pk_filter.go
  pkg/vm/engine/engine_util/pk_filter_base.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/types.go
Labels: size/XXL, kind/refactor, Tests, Enhancement, Review effort [1-5]: 4, Code Refactoring

#18584 fileservice: re-implement memory cache with fifocache
  pkg/fileservice/bytes.go
  pkg/fileservice/cache.go
  pkg/fileservice/caching_file_service_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/example_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/file_service.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/fscache/data.go
  pkg/fileservice/fscache/data_cache.go
  pkg/fileservice/interval/interval_tree.go
  pkg/fileservice/interval/interval_tree_test.go
  pkg/fileservice/interval/overlap.go
  pkg/fileservice/interval/overlap_test.go
  pkg/fileservice/io_entry.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/malloc.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/memorycache/cache.go
  pkg/fileservice/memorycache/cache_test.go
  pkg/fileservice/memorycache/data.go
  pkg/fileservice/memorycache/data_test.go
  pkg/fileservice/memorycache/lrucache/list.go
  pkg/fileservice/memorycache/lrucache/lru.go
  pkg/fileservice/memorycache/lrucache/lru_test.go
  pkg/fileservice/memorycache/lrucache/pool.go
  pkg/fileservice/memorycache/lrucache/shard.go
  pkg/fileservice/memorycache/lrucache/types.go
  pkg/fileservice/memorycache/refcnt.go
  pkg/fileservice/remote_cache.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
Labels: size/XL, kind/enhancement, Tests, Enhancement

#18543 fileservice: object storage semaphore refinements
  pkg/fileservice/io.go
  pkg/fileservice/object_storage_semaphore.go
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18626 Refactor block prefetch
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/prefetch.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/reader.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/object.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4, Bug fix

#18508 Incr blob size limit and clean up.
  pkg/container/types/array.go
  pkg/container/types/bytes.go
  pkg/container/types/packer.go
  pkg/container/types/tuple.go
  pkg/sql/colexec/lockop/fetch.go
  pkg/sql/colexec/lockop/fetch_test.go
  pkg/sql/plan/function/func_builtin.go
  test/distributed/cases/function/func_string_repeat.result
  test/distributed/cases/function/func_string_repeat.sql
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement, Bug fix

#18628 add more sharding metrics
  pkg/shardservice/filters.go
  pkg/shardservice/scheduler_allocate.go
  pkg/shardservice/scheduler_balance.go
  pkg/shardservice/scheduler_down.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_sharding.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/sharding.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18627 Optimize select count
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/tae/blockio/utils.go
Labels: kind/bug, size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement, Bug fix

#18576 Adding a create db test.
  pkg/embed/cluster_test.go
Labels: size/S, kind/test-ci, Tests, Review effort [1-5]: 2

#18527 adding flag to block info and object info
  pkg/objectio/block.go
  pkg/objectio/block_info.go
  pkg/objectio/block_info_test.go
  pkg/objectio/object_stats.go
  pkg/objectio/object_stats_test.go
  pkg/objectio/writer.go
  pkg/objectio/writer_test.go
  pkg/sql/colexec/mergeblock/mergeblock_test.go
  pkg/sql/colexec/s3util.go
  pkg/sql/compile/compile.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/datasource_test.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/types.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/db/gc/v2/table.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/M, Tests, Enhancement, Review effort [1-5]: 4

#18633 some code refactor
  pkg/catalog/catalog.go
  pkg/objectio/cache.go
  pkg/objectio/stats.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/engine_util/expr_filter.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/filter_util.go
  pkg/vm/engine/engine_util/pk_filter.go
  pkg/vm/engine/tae/blockio/pipeline.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/index/filter.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: size/M, kind/refactor, kind/enhancement, Review effort [1-5]: 3, Enhancement, bug_fix

#18363 adding object count metric for accounts.
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v1_2_3/tenant_upgrade_list.go
  pkg/frontend/compiler_context.go
  pkg/frontend/show_account.go
  pkg/frontend/show_account_test.go
  pkg/tests/upgrade/upgrade_init_test.go
  pkg/tests/upgrade/upgrade_test.go
  pkg/tests/upgrade/upgrade_v1_2_3_test.go
  pkg/util/metric/m_register.go
  pkg/util/metric/m_server.go
  pkg/util/metric/mometric/cron_task.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/tae/db/operations.go
  pkg/vm/engine/tae/db/operations.pb.go
  pkg/vm/engine/tae/db/operations.proto
  pkg/vm/engine/tae/db/test/storage_usage_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/mo_cloud/mo_cloud.sql
  test/distributed/cases/tenant/drop_account.result
  test/distributed/cases/tenant/drop_account.sql
Labels: size/L, kind/enhancement

#18616 [Subtask]: reduce shuffle memory allocation step 1
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/shuffle_test.go
  pkg/sql/colexec/shuffle/shufflepool.go
  pkg/sql/colexec/shuffle/types.go
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Enhancement

#18611 retry lock without lock table
  pkg/frontend/test/txn_mock.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
  pkg/sql/colexec/lockop/lock_op.go
  pkg/txn/client/operator.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
  pkg/vm/engine/entire_engine_test.go
Labels: size/M, Review effort [1-5]: 3, Tests, Enhancement

#18572 support rename multi table
  pkg/frontend/authenticate.go
  pkg/frontend/stmt_kind.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/alter.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  proto/plan.proto
  test/distributed/cases/ddl/rename_to_table.result
  test/distributed/cases/ddl/rename_to_table.sql
Labels: kind/feature, size/XXL, attention/doc-influence, Tests, Enhancement, Review effort [1-5]: 4

#18565 Dealing with duplicate S3 resource statistics issues
  pkg/sql/compile/compile.go
  pkg/sql/compile/types.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18639 Fix test dedup snapshot3
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/txn/txnbase/txnctx.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18644 [Bug]: performance regression of loading compressed file
  pkg/sql/plan/external.go
  pkg/sql/plan/stats.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18617 [refactor] : reuse memory for insert/delete partition table
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Enhancement

#18646 hashtable: add memory limit checks
  pkg/common/hashmap/inthashmap.go
  pkg/common/hashmap/strhashmap.go
  pkg/common/malloc/config.go
  pkg/common/malloc/inuse_tracking_allocator.go
  pkg/common/malloc/inuse_tracking_allocator_test.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/malloc.go
  pkg/container/hashtable/malloc_test.go
  pkg/container/hashtable/string_hash_map.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18516 refactor: preinsert
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/constraint_util.go
  pkg/sql/colexec/preinsert/preinsert.go
  pkg/sql/colexec/preinsert/types.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/function/init.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/M, kind/refactor, Enhancement, Review effort [1-5]: 4

#18659 dispatch operator must be in a pipeline with single parallel
  pkg/sql/colexec/shuffle/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/scope_test.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Bug fix

#18660 remove persisted tombstones merge during flush
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18657 fix ut
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18635 fix types.Rowid|types.Blockid compare related
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/container/types/rowid.go
  pkg/container/types/txnts.go
  pkg/container/types/types.go
  pkg/container/types/types_test.go
  pkg/container/vector/vector.go
  pkg/objectio/block.go
  pkg/objectio/block_info.go
  pkg/objectio/block_info_test.go
  pkg/objectio/id_test.go
  pkg/objectio/object_stats.go
  pkg/sort/sort.go
  pkg/sort/sort_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/function/ctl/object_filter_test.go
  pkg/sql/plan/function/func_compare.go
  pkg/sql/plan/function/operator_between.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/datasource_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/types.go
  pkg/vm/engine/disttae/reader.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/blockio/utils.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/compute/compare_test.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/table_scan.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
Labels: kind/bug, size/L, kind/enhancement, Tests, Enhancement, Review effort [1-5]: 4, Bug fix

#18658 bug fix: Top Operator should not change input batch
  pkg/sql/colexec/top/top.go
  pkg/sql/colexec/top/types.go
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18665 Refactor join node compilation analyze
  pkg/sql/compile/compile.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Enhancement, Bug fix

#18675 [bug] logtail: clear the tables in global stats when logtail re-connect
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18670 fix select version
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/self_handle.go
  pkg/frontend/session.go
  test/distributed/cases/database/config.result
  test/distributed/cases/database/config.sql
  test/distributed/cases/zz_accesscontrol/account_restricted.result
  test/distributed/cases/zz_accesscontrol/account_restricted.sql
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Enhancement, Bug fix

#18674 [bug] logtail: clear the tables in global stats when logtail re-connect
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18682 fix a bug that cause load performance regression when there is sink_scan node in plan
  pkg/sql/compile/compile.go
  pkg/sql/compile/util.go
Labels: kind/bug, size/S, Review effort [1-5]: 4, Bug fix

#18677 update CollectDeletesLocked
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/model/transferdels.go
  pkg/vm/engine/tae/tables/updates/delchain.go
Labels: kind/bug, size/S, Bug fix, Review effort [1-5]: 1

#18662 fix replay incomplete data to catalog cache
  pkg/catalog/types.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Tests, Bug fix

#18640 fix non reserved keyword period
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
Labels: size/XXL, Review effort [1-5]: 1, bug_fix

#18690 mo-service: fix default cache configs
  cmd/mo-service/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Enhancement, Bug fix

#18693 using pointers as function arguments to avoid relying on golang compiler optimizations
  pkg/objectio/block_info.go
  pkg/vm/engine/disttae/logtailreplay/blocks_iter.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/engine_util/exec_util.go
  pkg/vm/engine/engine_util/expr_filter.go
Labels: size/S, kind/refactor, kind/enhancement, Review effort [1-5]: 3, Enhancement, Code Refactoring

#18700 add restart txn interface for reuse txn operator
  pkg/frontend/test/txn_mock.go
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/leak_checker.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
  pkg/txn/client/types.go
  pkg/txn/storage/memorystorage/storage_txn_client.go
Labels: size/M, kind/enhancement, Tests, Enhancement, Review effort [1-5]: 4

#18699 avoid metadata cache access heap allocation
  pkg/objectio/cache.go
  pkg/objectio/constructors.go
  pkg/objectio/funcs.go
  pkg/objectio/meta_entry.go
  pkg/objectio/types.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/tombstones.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18703 malloc: optimize profiler
  pkg/common/malloc/checked_allocator.go
  pkg/common/malloc/config.go
  pkg/common/malloc/inuse_tracking_allocator.go
  pkg/common/malloc/leaks_tracking_allocator.go
  pkg/common/malloc/managed_allocator.go
  pkg/common/malloc/managed_allocator_test.go
  pkg/common/malloc/metrics_allocator.go
  pkg/common/malloc/profile_allocator.go
  pkg/common/malloc/profiler.go
  pkg/common/malloc/random_allocator.go
  pkg/common/malloc/read_only_allocator.go
  pkg/common/malloc/sharded_allocator.go
  pkg/common/malloc/size_bounded_allocator.go
  pkg/frontend/types.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4

#18691 add summary for txnBlock(1.2-dev only)
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/logtail.go
  pkg/util/metric/v2/metrics.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/options/types.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18711 bug fix: unique key/secondary key get incorrect value
  pkg/sql/plan/build_dml_util.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18705 fix GetOrCreateTxnWithMeta not get txn error
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18708 set userID & roleID for executor
  pkg/cnservice/server_task.go
  test/distributed/cases/ddl/create_table_with_retention.result
  test/distributed/cases/ddl/create_table_with_retention.sql
Labels: kind/bug, size/M, Review effort [1-5]: 2, Bug fix

#18668 Datalink support stage URL and add save_file() function
  pkg/container/types/datalink.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/function/func_unary.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/function/stage_test.go
  pkg/sql/plan/function/stage_util.go
  pkg/sql/util/eval_expr_util.go
  test/distributed/cases/function/func_load_file_datalink.result
  test/distributed/cases/function/func_load_file_datalink.sql
Labels: kind/feature, size/L, Tests, Enhancement, Review effort [1-5]: 4

#18713 optimize create vector index
  pkg/sql/colexec/product/product.go
  pkg/vm/message/message.go
Labels: kind/bug, size/S, Review effort [1-5]: 3, Enhancement, Bug fix

#18698 add new ExpressionExecutor for plan.Expr_List
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpression_test.go
  pkg/sql/colexec/reuse.go
Labels: size/M, kind/refactor, Review effort [1-5]: 3, Tests, Enhancement

#18706 Update TransferDeletes for S3 deletes
  pkg/vm/engine/tae/catalog/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/txn/txnimpl/base_table.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, size/M, Tests, Enhancement, Review effort [1-5]: 4, Bug fix

#18676 Explain the pipeline information of SQL physical plan
  pkg/frontend/authenticate.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/result_row_stmt.go
  pkg/frontend/test/types_mock.go
  pkg/frontend/types.go
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/debugTools.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/explain.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/plan/build.go
  pkg/sql/plan/stats.go
  test/distributed/cases/analyze/explain_phyplan.result
  test/distributed/cases/analyze/explain_phyplan.sql
Labels: kind/feature, size/XXL, Tests, Enhancement, Review effort [1-5]: 4

#18717 bug fix: unique key/secondary key get incorrect value (#18711)
  pkg/sql/plan/build_dml_util.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18721 optimize create vector index step 2
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18672 set srv.pu before creating hakeeper client
  pkg/cnservice/server.go
Labels: kind/bug, size/M, Review effort [1-5]: 2, Bug fix

#18679 Support Explain Cross Apply
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/apply/apply.go
  pkg/sql/colexec/apply/apply_test.go
  pkg/sql/colexec/apply/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/tree/select.go
  pkg/sql/plan/current_account.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/marshal_query.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/processlist.go
  pkg/sql/plan/pushdown.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stage.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/system_view.go
  pkg/sql/plan/unnest.go
  pkg/vm/types.go
  proto/plan.proto
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
Labels: size/XXL, Tests, Enhancement, Review effort [1-5]: 4

#18737 add issue18710 cases
  test/distributed/cases/dml/insert/insert_duplicate.result
  test/distributed/cases/dml/insert/insert_duplicate.sql
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18731 Method for reading query results during upgrade modification
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/version.go
  pkg/bootstrap/versions/version_upgrade.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18757 [bug] proxy: fix panic when kill connection
  pkg/proxy/client_conn.go
  pkg/proxy/client_conn_test.go
  pkg/proxy/event.go
  pkg/proxy/event_test.go
  pkg/proxy/handler_test.go
  pkg/proxy/tunnel.go
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18716 skip tombstone object by obj create ts.
  pkg/compare/compare.go
  pkg/container/types/encoding.go
  pkg/container/types/encoding_test.go
  pkg/container/types/txnts.go
  pkg/sort/sort.go
  pkg/vm/engine/disttae/datasource.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/compute/compare.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/index/zm.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18760 support order by limit optimization for non-sorted columns
  pkg/sql/plan/message.go
Labels: size/XS, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18753 support order by limit optimization for non-sorted columns
  pkg/sql/plan/message.go
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
Labels: size/S, kind/enhancement, Tests, Enhancement, Review effort [1-5]: 2

#18738 fix a bug that double int hashmap memory allocation
  pkg/container/hashtable/int64_hash_map.go
  pkg/sql/colexec/hashmap_util/hashmap_util_test.go
Labels: kind/bug, size/S, Review effort [1-5]: 2, Bug fix

#18751 make it less prone to go index for cluster by tables
  pkg/sql/plan/apply_indices.go
  test/distributed/cases/optimizer/index.result
  test/distributed/cases/optimizer/index.test
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18758 update delete flushThreshold
  pkg/sql/colexec/deletion/types.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#18748 remove mistake objIt.Next
  pkg/vm/engine/tae/catalog/table.go
Labels: kind/bug, size/XS, Bug fix, Review effort [1-5]: 1

#18766 optimize create vector index step 3
  pkg/sql/compile/ddl_index_algo.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18615 add lockmerge to prevent intensive transfer
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: kind/bug, size/M, kind/enhancement, Enhancement, Review effort [1-5]: 4

#18772 remove a unit test which cause ci hang
  pkg/vm/message/message_test.go
Labels: kind/bug, size/S, Bug fix, Review effort [1-5]: 1

#18689 mo-service: fix default cache configs
  cmd/mo-service/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/disk_object_storage.go
  pkg/fileservice/disk_object_storage_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/object_storage_test.go
  pkg/fileservice/remote_cache_test.go
  pkg/fileservice/s3_fs.go
  pkg/fileservice/s3_fs_test.go
Labels: kind/bug, size/M, Review effort [1-5]: 3, Bug fix

#18771 add support rollback running txn
  pkg/incrservice/column_cache.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: size/M, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18746 fix a bug that cause hashmap data wrong
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Bug fix

#18733 Update upgrade code main
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/upgrade_tenant_task_test.go
  pkg/bootstrap/versions/version_upgrade.go
  pkg/bootstrap/versions/version_upgrade_test.go
  pkg/util/executor/mem_executor.go
Labels: kind/bug, size/M, Bug fix

#18776 fix a bug in delete pipeline which may cause panic and hang
  pkg/sql/compile/compile.go
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18770 fix json_extract_string, json_extract_float64 with multi path param
  pkg/sql/plan/function/func_builtin_json.go
  test/distributed/cases/function/func_json_extract.result
  test/distributed/cases/function/func_json_extract.test
Labels: kind/bug, size/S, Tests, Review effort [1-5]: 2, Bug fix

#18779 cp to 1.2-dev 'fix a bug that cause hashmap data wrong'
  pkg/sql/colexec/hashbuild/build.go
  pkg/sql/colexec/hashbuild/types.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S, Review effort [1-5]: 3, Tests, Bug fix

#18768 [tech] pprof: dump malloc profile
  cmd/mo-service/debug.go
  pkg/common/malloc/default.go
Labels: size/S, kind/enhancement, Enhancement, Review effort [1-5]: 2

#18780 add summary for txnBlock
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/options/types.go
Labels: size/S, kind/enhancement, Review effort [1-5]: 3, Enhancement

#18786 remove the 1024bytes limit for group_concat result.
  pkg/sql/colexec/aggexec/concat.go
Labels: kind/bug, size/XS, Review effort [1-5]: 2, Bug fix

#18775 add support rollback running txn to 1.2
  pkg/incrservice/column_cache.go
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 3, Tests, Enhancement

#18784 Add wal ckp
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/entry/types.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/wal/checkpoint.go
  pkg/vm/engine/tae/wal/types.go
Labels: kind/feature, size/M, Tests, Enhancement, Review effort [1-5]: 4
