Repository matrixorigin/matrixone, pull requests merged in 2025-01, with the labels that each got.

#21039 Fix collect ckps in range
  pkg/vm/engine/tae/db/checkpoint/store.go
  test/distributed/cases/function/func_datetime_utc_timestamp.result
Labels: kind/bug, size/S

#21037 cleanup checkpoint related code
  pkg/backup/backup_test.go
  pkg/vm/engine/tae/common/retry.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/checkpoint/flusher_test.go
  pkg/vm/engine/tae/db/checkpoint/gckp_exec.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/store.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/test/mo_table_stats_test.go
  pkg/vm/engine/test/partition_state_test.go
  test/distributed/cases/dml/checkpoint/checkpoint.result
  test/distributed/cases/dml/checkpoint/checkpoint.test
Labels: size/M, kind/refactor

#20959 [bug] datasync: fix ut TestCompleteData
  pkg/datasync/consumer_test.go
Labels: kind/bug, size/XS

#21003 feat: mo gc tool
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/tool.go
  pkg/vm/engine/tae/rpc/tool_test.go
Labels: kind/feature, size/M

#21040 refactor some code to avoid import cycle
  pkg/frontend/compiler_context.go
  pkg/frontend/query_result.go
  pkg/objectio/ioutil/reader.go
  pkg/objectio/ioutil/sinker.go
  pkg/objectio/ioutil/sinker_test.go
  pkg/objectio/ioutil/write_index.go
  pkg/objectio/ioutil/writer.go
  pkg/objectio/mergeutil/types.go
  pkg/objectio/mergeutil/util.go
  pkg/sql/colexec/external/external.go
  pkg/sql/colexec/external/types.go
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/colexec/multi_update/s3writer_util.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/sql/colexec/table_function/meta_scan.go
  pkg/util/export/etl/tae.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/transfer_util.go
  pkg/vm/engine/tae/blockio/prefetch.go
  pkg/vm/engine/tae/blockio/utils_test.go
  pkg/vm/engine/tae/blockio/writer_test.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/reader.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/snapshot.go
  pkg/vm/engine/tae/db/gc/v3/executor.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/mergesort/func.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/rpc/tool_test.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/test/sinker_test.go
Labels: size/L, kind/refactor

#21047 fix: ut Test_gcArg failed
  pkg/vm/engine/tae/rpc/tool_test.go
Labels: kind/bug, size/XS

#21023 support startTs and endTs in cdc task
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: kind/feature, size/M

#21054 ignore base test cases
  test/distributed/cases/function/func_datetime_utc_timestamp.result
  test/distributed/cases/function/func_datetime_utc_timestamp.test
Labels: size/S, kind/test-ci

#21004 feat: mo gc tool
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/tool.go
  pkg/vm/engine/tae/rpc/tool_test.go
Labels: kind/feature, size/M

#21041 stop cn merge
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/utils.go
Labels: kind/bug, size/S

#21036 add columns to mo_pubs/subs
  pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
  pkg/common/pubsub/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/predefined.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
  pkg/frontend/snapshot.go
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/publication_subscription/pub_sub3.result
  test/distributed/cases/publication_subscription/pub_sub3.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: size/M, kind/refactor

#21028 [bug] logservice: fix context timeout for heartbeat
  pkg/logservice/service_commands.go
Labels: kind/bug, size/XS

#21025 modify case syntax about create snapshot for account.
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster/restore_cluster_table.sql
  test/distributed/cases/snapshot/cluster/restore_fk_restore_master_table.result
  test/distributed/cases/snapshot/cluster/restore_fk_restore_master_table.sql
  test/distributed/cases/snapshot/cluster/restore_simple_read.result
  test/distributed/cases/snapshot/cluster/restore_simple_read.sql
  test/distributed/cases/snapshot/cluster/snapshot_restore_skip_master_db.result
  test/distributed/cases/snapshot/cluster/snapshot_restore_skip_master_db.sql
  test/distributed/cases/snapshot/restore_fk_table.result
  test/distributed/cases/snapshot/restore_fk_table.sql
  test/distributed/cases/snapshot/restore_pub_sub.result
  test/distributed/cases/snapshot/restore_pub_sub.sql
  test/distributed/cases/snapshot/restore_sub.result
  test/distributed/cases/snapshot/restore_sub.sql
  test/distributed/cases/snapshot/snapshot.result
  test/distributed/cases/snapshot/snapshot.sql
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/snapshot/snapshotRead.sql
  test/distributed/cases/snapshot/snapshot_database_level.result
  test/distributed/cases/snapshot/snapshot_database_level.sql
  test/distributed/cases/snapshot/snapshot_read.result
  test/distributed/cases/snapshot/snapshot_read.sql
  test/distributed/cases/snapshot/snapshot_read_1.result
  test/distributed/cases/snapshot/snapshot_read_1.sql
  test/distributed/cases/snapshot/snapshot_read_3.result
  test/distributed/cases/snapshot/snapshot_read_3.sql
  test/distributed/cases/snapshot/snapshot_read_incremental_data.result
  test/distributed/cases/snapshot/snapshot_read_incremental_data.sql
  test/distributed/cases/snapshot/snapshot_restore_account_level.result
  test/distributed/cases/snapshot/snapshot_restore_account_level.sql
  test/distributed/cases/snapshot/snapshot_restore_cluster_table.result
  test/distributed/cases/snapshot/snapshot_restore_cluster_table.sql
  test/distributed/cases/snapshot/snapshot_restore_database_level.result
  test/distributed/cases/snapshot/snapshot_restore_database_level.sql
  test/distributed/cases/snapshot/snapshot_restore_keyword.result
  test/distributed/cases/snapshot/snapshot_restore_keyword.sql
  test/distributed/cases/snapshot/snapshot_restore_publication.result
  test/distributed/cases/snapshot/snapshot_restore_publication.sql
  test/distributed/cases/snapshot/snapshot_restore_system_table.result
  test/distributed/cases/snapshot/snapshot_restore_system_table.sql
  test/distributed/cases/snapshot/snapshot_restore_table_level.result
  test/distributed/cases/snapshot/snapshot_restore_table_level.sql
  test/distributed/cases/snapshot/snapshot_restore_to_table_fk.result
  test/distributed/cases/snapshot/snapshot_restore_to_table_fk.sql
  test/distributed/cases/snapshot/snapshot_restore_to_table_fk_2.result
  test/distributed/cases/snapshot/snapshot_restore_to_table_fk_2.sql
  test/distributed/cases/snapshot/snapshot_restore_to_table_view.result
  test/distributed/cases/snapshot/snapshot_restore_to_table_view.sql
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_view_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_view_to_sys_account.sql
Labels: size/M, kind/enhancement

#21046 fix one err handling
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S

#21060 fix handle empty startTs/endTs
  pkg/cdc/types.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/S

#21026 fix dn crash 2.0
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: kind/bug, size/S

#20970 fix deadlock
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_2/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_2/upgrade.go
  pkg/bootstrap/versions/v2_0_2/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/predefined.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/build_show.go
  pkg/util/sysview/predefined.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/M

#21059 [Cherry-pick] add columns to mo_pubs/subs
  pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
  pkg/common/pubsub/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/predefined.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
  pkg/frontend/snapshot.go
  test/distributed/cases/foreign_key/fk_show_columns.result
  test/distributed/cases/publication_subscription/pub_sub3.result
  test/distributed/cases/publication_subscription/pub_sub3.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
Labels: size/M, kind/refactor

#21058 support show recovery_window
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/pitr.go
  pkg/sql/parsers/tree/stmt.go
Labels: kind/feature, size/XXL

#21022 fix dn crash
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: kind/bug, size/S

#21072 add fault domain
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/util/fault/fault.go
  pkg/util/fault/fault_test.go
Labels: size/M, kind/enhancement

#21067 cherrypick from 2.0dev: fix deadlock
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_2/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_2/upgrade.go
  pkg/bootstrap/versions/v2_0_2/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/predefined.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/build_show.go
  pkg/util/sysview/predefined.go
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/select/sp_table.sql
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/tenant/tenant.test
  test/distributed/cases/zz_accesscontrol/account_restricted.result
Labels: kind/bug, size/M

#21034 fix rollback database ddl
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#21076 fix isValidRemoteTxn
  pkg/lockservice/log.go
  pkg/lockservice/orphan_txn_test.go
  pkg/lockservice/service.go
Labels: size/S

#21082 Update policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policy_test.go
Labels: kind/bug, size/S

#21074 fix bug: prefix_xx get incorrect result
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/func_prefix_test.go
Labels: kind/bug, size/M

#21077 fix isValidRemoteTxn
  pkg/lockservice/log.go
  pkg/lockservice/orphan_txn_test.go
  pkg/lockservice/service.go
Labels: size/S

#21090 disable logs
  pkg/frontend/internal_executor.go
  pkg/frontend/mysql_protocol.go
  pkg/frontend/query_result.go
  pkg/frontend/routine.go
  pkg/frontend/routine_manager.go
  pkg/frontend/session.go
Labels: size/S, kind/enhancement

#21075 fix bug: prefix_xx get incorrect result
  pkg/sql/plan/function/func_prefix.go
  pkg/sql/plan/function/func_prefix_test.go
Labels: kind/bug, size/M

#21085 Fix bug: incorrect pk filter for string column
  pkg/container/vector/search.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/pk_filter.go
  test/distributed/cases/optimizer/blockfilter.result
  test/distributed/cases/optimizer/blockfilter.test
Labels: kind/bug, size/M

#21055 Fulltext bugs
  pkg/monlp/tokenizer/simple.go
  pkg/monlp/tokenizer/simple_test.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_fulltext.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show_util.go
  pkg/sql/plan/build_show_util_test.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
  test/distributed/cases/fulltext/fulltext1.result
  test/distributed/cases/fulltext/fulltext2.result
  test/distributed/cases/snapshot/sys_restore_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.result
Labels: kind/bug, size/M

#20966 fix need retry in engine
  pkg/objectio/injects.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.result
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
Labels: kind/bug, size/M

#21091 Fix skip entry in replay
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/wal/driver.go
Labels: kind/bug, size/M

#21096 Fix bug: incorrect pk filter for string column (#21085)
  pkg/container/vector/search.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/pk_filter.go
  test/distributed/cases/optimizer/blockfilter.result
  test/distributed/cases/optimizer/blockfilter.test
Labels: kind/bug, size/M

#21087 Fix skip entry in replay
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/wal/driver.go
Labels: kind/bug, size/M

#21102 Fix bug: incorrect pk filter for string column (#21085)
  pkg/container/vector/search.go
  pkg/vm/engine/engine_util/filter_test.go
  pkg/vm/engine/engine_util/pk_filter.go
  test/distributed/cases/optimizer/blockfilter.result
  test/distributed/cases/optimizer/blockfilter.test
Labels: kind/bug, size/M

#21098 [bug] proxy: migrate session skip error when db is dropped
  pkg/frontend/session.go
  pkg/frontend/session_test.go
Labels: kind/bug, size/S

#21095 check col existence of mo_pubs/subs
  pkg/frontend/authenticate_test.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
Labels: kind/bug, size/M

#20769 Small refactor for delaying calls to expand ranges
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/stats.go
  pkg/tests/dml/dml_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  pkg/vm/engine/readutil/relation_data.go
  pkg/vm/engine/readutil/relation_data_test.go
  pkg/vm/engine/types.go
  proto/pipeline.proto
Labels: size/L, kind/enhancement

#21108 fix replay
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
Labels: kind/bug, size/M

#21084 skip the TS check when `getChangedTableList`.
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/table.go
  pkg/vm/engine/tae/logtail/table_test.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: size/S

#21103 disable partition bvt
  test/distributed/cases/database/system_table.sql
  test/distributed/cases/ddl/alter_table.sql
  test/distributed/cases/ddl/alter_table_AddDrop_column.sql
  test/distributed/cases/ddl/alter_table_add_partition.sql
  test/distributed/cases/ddl/create_retention_table.sql
  test/distributed/cases/ddl/create_table_as_select.sql
  test/distributed/cases/ddl/create_table_like.sql
  test/distributed/cases/ddl/hash_key_partition.sql
  test/distributed/cases/ddl/json_type.sql
  test/distributed/cases/ddl/mysql_ddl_3.sql
  test/distributed/cases/ddl/partition.sql
  test/distributed/cases/ddl/partition2.sql
  test/distributed/cases/ddl/partition3.sql
  test/distributed/cases/ddl/partition4.sql
  test/distributed/cases/ddl/partition_metadata.sql
  test/distributed/cases/ddl/partition_prepare.sql
  test/distributed/cases/ddl/partition_prune.sql
  test/distributed/cases/dml/insert/insert_ignore.sql
  test/distributed/cases/dml/insert/on_duplicate_key.sql
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/dml/show/show3.sql
  test/distributed/cases/dtype/time_1.sql
  test/distributed/cases/foreign_key/fk_show_columns.sql
  test/distributed/cases/optimistic/atomicity_1.sql
  test/distributed/cases/pessimistic_transaction/select_for_update.sql
  test/distributed/cases/publication_subscription/pub_sub2.sql
  test/distributed/cases/publication_subscription/pub_sub_improve2.sql
  test/distributed/cases/snapshot/cluster/restore_cluster_table.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_newnonsys.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_nonsys.sql
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_view_to_sys.sql
  test/distributed/cases/snapshot/nonsys_create_snapshot_for_nonsys_db_table_level.sql
  test/distributed/cases/snapshot/nonsys_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/nonsys_restore_view_to_nonsys_account.sql
  test/distributed/cases/snapshot/restore_pub_to_new.sql
  test/distributed/cases/snapshot/snapshotRead.sql
  test/distributed/cases/snapshot/snapshot_database_level.sql
  test/distributed/cases/snapshot/snapshot_restore_to_table_partition.sql
  test/distributed/cases/snapshot/sys_create_snapshot_for_sys_db_table_level.sql
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_newnonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_to_sys_account.sql
  test/distributed/cases/snapshot/sys_restore_view_to_newnonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_view_to_nonsys_account.sql
  test/distributed/cases/snapshot/sys_restore_view_to_sys_account.sql
  test/distributed/cases/tenant/privilege/operate_catalog.sql
  test/distributed/cases/window/window.sql
  test/distributed/cases/zz_accesscontrol/grant_privs_role.sql
  test/distributed/cases/zz_accesscontrol/inner_object.sql
Labels: kind/feature, size/S

#21068 fix incomplete cache 2.0
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#21107 Fix replay
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
Labels: kind/bug, size/M

#21053 fix need retry in engine 2.0
  pkg/objectio/injects.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/sql_executor.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/test/disttae_engine_test.go
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.result
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
Labels: kind/bug, size/M

#21119 fix merge
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/logtail/mgr.go
Labels: kind/bug, size/S

#21109 create snapshot ignore account case
  test/distributed/cases/snapshot/nonsys_create_snapshot_without_account.result
  test/distributed/cases/snapshot/nonsys_create_snapshot_without_account.sql
Labels: kind/bug, size/XL

#21120 fix bug: recall NewExpressionExecutor in prepare
  pkg/sql/colexec/dedupjoin/join.go
  test/distributed/cases/dml/insert/on_duplicate_key.result
  test/distributed/cases/dml/insert/on_duplicate_key.sql
Labels: kind/bug, size/S

#21121 fix bug: recall NewExpressionExecutor in prepare
  pkg/sql/colexec/dedupjoin/join.go
  test/distributed/cases/dml/insert/on_duplicate_key.result
  test/distributed/cases/dml/insert/on_duplicate_key.sql
Labels: kind/bug, size/S

#21104 Refactor create pitr statement
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/pitr.go
Labels: size/XXL, kind/enhancement

#20681 [Tech Request]: add new object list relation data
  pkg/frontend/test/engine_mock.go
  pkg/frontend/test/txn_mock.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/memoryengine/table_reader.go
  pkg/vm/engine/readutil/datasource_test.go
  pkg/vm/engine/readutil/relation_data.go
  pkg/vm/engine/types.go
Labels: size/L, kind/refactor

#21126 [improvement] logtail: some refactor to reduce GC pressure
  pkg/vm/engine/disttae/logtail_consumer.go
Labels: size/S, kind/enhancement

#21133 [Cherry-pick] check col existence of mo_pubs/subs
  pkg/frontend/authenticate_test.go
  pkg/frontend/publication_subscription.go
  pkg/frontend/publication_subscription_test.go
Labels: kind/bug, size/M

#20718 3-Add dataX and tenxcloud bvt test,base:main
  test/distributed/cases/dataXtest/dataXtest01.result
  test/distributed/cases/dataXtest/dataXtest01.sql
  test/distributed/cases/tenxcloud_xx/json_test.result
  test/distributed/cases/tenxcloud_xx/json_test.sql
  test/distributed/cases/tenxcloud_xx/tenxcloudtest.result
  test/distributed/cases/tenxcloud_xx/tenxcloudtest.sql
Labels: size/XL, kind/test-ci

#21127 fix replay
  pkg/vm/engine/tae/catalog/object_list.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: kind/bug, size/M

#21128 fix replay
  pkg/vm/engine/tae/catalog/object_list.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: kind/bug, size/M

#21137 fix createdInTxn impl 2.0
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#21138 fix createdInTxn impl
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#21144 fix TestGlobalCheckpoint7 ut
  pkg/vm/engine/tae/db/checkpoint/executor.go
Labels: kind/bug, size/S

#21132 chore: add account filter-condition to speedup etlmerge check-exist
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/merge.go
  pkg/util/metric/v2/trace.go
Labels: size/S, kind/enhancement

#21117 [#21049] Fix-bug-cherry-pick
  pkg/vm/engine/disttae/txn.go
Labels: size/XS

#21130 refactor: Reduce the number of objects in Api.Proto
  pkg/container/types/tools.go
  pkg/container/vector/tools.go
  pkg/pb/api/api.go
  pkg/pb/api/api.pb.go
  pkg/sql/compile/ddl.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/rpc/handle_test.go
  proto/api.proto
Labels: size/S, kind/refactor

#21142 W zr patch 1
  pkg/container/types/rowid.go
  pkg/container/types/uuid.go
  pkg/vm/engine/tae/blockio/writer.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
Labels: kind/bug, size/S

#21151 use full db.table path in insert stmt
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
Labels: kind/bug, size/S

#21147 fix bvt
  test/distributed/cases/database/system_table.sql
Labels: size/XS, kind/test-ci

#21146 fix bvt
  test/distributed/cases/database/system_table.sql
Labels: size/XS, kind/test-ci

#21129 refactor: Reduce the number of objects in Projection.Call
  pkg/sql/colexec/projection/projection.go
Labels: kind/refactor, size/XS

#21152 [Cherry-pick] use full db.table path in insert stmt
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
Labels: kind/bug, size/S

#21158 optimize readers when there is false filter
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_sharding.go
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: kind/bug, size/S

#21155 chore: add account filter-condition to speedup etlmerge check-exist
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/merge.go
  pkg/util/metric/v2/trace.go
Labels: size/S, kind/enhancement

#21150 add shuffle method for objlist split
  pkg/sql/compile/scope.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/readutil/relation_data.go
Labels: size/M, kind/enhancement

#21066 [#21049] Fix bug
  pkg/vm/engine/disttae/txn.go
  test/distributed/cases/optimistic/insert.result
  test/distributed/cases/optimistic/insert.test
Labels: kind/bug, size/S

#21165 If the schema version has reached the final version, mark and return
  pkg/bootstrap/service_upgrade.go
Labels: kind/bug, size/XS

#21161 improve replay
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/tables/table_scan.go
Labels: size/M, kind/enhancement

#21168 to 2.0: fix partition state pinned by mo table stats and adding some metrics.
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: kind/bug, size/S

#21167 fix partition state pinned by mo table stats and adding some metrics.
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: kind/bug, size/S

#21166 improve catalog
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/tables/table_scan.go
Labels: size/M, kind/enhancement

#21164 fix Test_CheckpointChaos1
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#21170 Change the upgraded panic error to fatal
  pkg/bootstrap/custom_upgrade.go
  pkg/bootstrap/service_upgrade.go
  pkg/bootstrap/service_upgrade_tenant.go
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/version.go
  pkg/bootstrap/versions/version_upgrade.go
Labels: kind/bug, size/S

#21173 Change the upgraded panic error to fatal
  pkg/bootstrap/custom_upgrade.go
  pkg/bootstrap/service_upgrade.go
  pkg/bootstrap/service_upgrade_tenant.go
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/upgrade_strategy.go
  pkg/bootstrap/versions/upgrade_tenant_task.go
  pkg/bootstrap/versions/version.go
  pkg/bootstrap/versions/version_upgrade.go
Labels: kind/bug, size/S

#21134 fix: load float with stringQuote into int type column return…
  pkg/sql/colexec/external/external.go
  pkg/sql/util/csvparser/csv_parser.go
  pkg/sql/util/csvparser/csv_parser_test.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/test_int.csv
Labels: kind/bug, size/M

#21169 add dop field in stats
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
  pkg/sql/plan/stats.go
  proto/plan.proto
Labels: size/M, kind/refactor

#21172 Fix TestCkpLeak
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#21175 fix disorder in reconnecting logtail 2.0
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/tae/logtail/service/client.go
  test/distributed/cases/dml/checkpoint/connectlogtail.result
  test/distributed/cases/dml/checkpoint/connectlogtail.test
Labels: kind/bug, size/M

#21176 fix a bug that cause panic in shuffle
  pkg/sql/plan/shuffle.go
Labels: kind/bug, size/XS

#21124 fix disorder in reconnecting logtail
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/service/client.go
  pkg/vm/engine/tae/logtail/table_test.go
  test/distributed/cases/dml/checkpoint/connectlogtail.result
  test/distributed/cases/dml/checkpoint/connectlogtail.test
Labels: kind/bug, size/M

#21182 [improvement] stats: add some metrics and watcher.
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
Labels: size/M, kind/enhancement

#21185 restore upgrade tenant Code
  pkg/bootstrap/service_upgrade.go
Labels: kind/bug, size/XS

#21184 restore upgrade tenant Code
  pkg/bootstrap/service_upgrade.go
Labels: kind/bug, size/XS

#21178 fix a bug that cause panic in shuffle
  pkg/sql/compile/compile.go
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: kind/bug, size/S

#21180 adjust dop of shuffle plan for future refactoring
  pkg/sql/compile/compile.go
  pkg/sql/plan/stats.go
  test/distributed/cases/optimizer/shuffle.result
  test/distributed/cases/optimizer/shuffle.test
Labels: size/S, kind/refactor

#21177 update cte & view
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build_test.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/types.go
  test/distributed/cases/expression/cte2.result
  test/distributed/cases/expression/cte2.sql
Labels: kind/bug, size/XL, kind/enhancement

#21193 [improvement] proxy: add logs when connect/disconnect
  pkg/proxy/conn_manager.go
Labels: size/XS, kind/enhancement

#21183 support show recovery_window
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_1_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_1_0/log.go
  pkg/bootstrap/versions/v2_1_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_1_0/upgrade.go
  pkg/bootstrap/versions/v2_1_0/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/predefined.go
  pkg/frontend/query_result.go
  pkg/frontend/self_handle.go
  pkg/frontend/show_recovery_window.go
  pkg/frontend/show_recovery_window_test.go
  pkg/frontend/types.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/tree/stmt.go
  test/distributed/cases/pitr/pitr.result
  test/distributed/cases/pitr/pitr.sql
  test/distributed/cases/pitr/pitr_basic.result
  test/distributed/cases/pitr/pitr_basic.sql
  test/distributed/cases/pitr/pitr_inherit.result
  test/distributed/cases/pitr/pitr_inherit.sql
  test/distributed/cases/snapshot/show_recovery_window.result
  test/distributed/cases/snapshot/show_recovery_window.sql
Labels: kind/feature, size/XXL

#21202 prune incomplete sql before send
  pkg/cdc/sinker.go
Labels: kind/bug, size/XS

#21199 fix TestReplay8
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tasks/poolhandler.go
Labels: kind/bug, size/S

#21188 refactor wal implementation to make it testable
  pkg/datasync/entry_test.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/metamvccnode.go
  pkg/vm/engine/tae/common/intervals.go
  pkg/vm/engine/tae/common/intervals_test.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/replay.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/syncbase.go
  pkg/vm/engine/tae/logstore/driver/entry/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/append.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/faker.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replayer.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/samples/replay/main.go
  pkg/vm/engine/tae/logstore/store/checkpointinfo.go
  pkg/vm/engine/tae/logstore/store/load.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: kind/bug, size/XL, kind/refactor, kind/enhancement

#21194 ensure endTs greater than startTs
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/S

#21205 fix TestGCCheckpoint1
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#21191 [CherryPick]Fix bug for 21179
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/M

#21203 support shuffle pipeline refactoring for right joins
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
Labels: size/S, kind/refactor

#21190 [improvement] proxy: add logs when connect/disconnect
  pkg/proxy/conn_manager.go
Labels: size/XS, kind/enhancement

#21208 fix top container reset
  pkg/sql/colexec/top/types.go
  pkg/sql/colexec/top/types_test.go
Labels: kind/bug, size/S

#21206 fix unlock when version of bind changed
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
Labels: size/S

#21207 fix unlock when version of bind changed
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_remote_test.go
Labels: size/S

#21216 fix enum type parse stage(#2.0-dev)
  pkg/container/types/enum.go
Labels: kind/bug, size/XS

#21218 feat: optimize mo backup
  pkg/backup/backup_test.go
  pkg/backup/tae.go
  pkg/backup/types.go
Labels: size/M, kind/enhancement

#21214 fix enum type parse stage
  pkg/container/types/enum.go
Labels: kind/bug, size/XS

#21211 malloc: default to malloc
  pkg/common/malloc/default.go
Labels: size/XS, kind/enhancement

#21221 support GOBUILD_OPT pass to Makefile
  Makefile
Labels: kind/feature, size/XS

#21224 fix the err missing when `GetChangedTableList`.
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: kind/bug, size/M

#21200 fix TestReplay8 2.0
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tasks/poolhandler.go
Labels: kind/bug, size/S

#21219 remove fields
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: size/S, kind/enhancement

#21223 add datasync code owner
  CODEOWNERS
Labels: kind/documentation, size/XS

#21196 add partitionservice for create and delete partition table
  CODEOWNERS
  pkg/catalog/types.go
  pkg/cnservice/distributed_tae.go
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/common/runtime/types.go
  pkg/partitionservice/cfg.go
  pkg/partitionservice/service.go
  pkg/partitionservice/service_test.go
  pkg/partitionservice/storage.go
  pkg/partitionservice/storage_test.go
  pkg/partitionservice/types.go
  pkg/pb/partition/partition.go
  pkg/pb/partition/partition.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_ddl.go
  pkg/tests/partition/create_hash_test.go
  pkg/tests/partition/partition_test.go
  pkg/tests/testutils/test_utils.go
  proto/partition.proto
  proto/plan.proto
Labels: kind/feature, size/XL

#21189 [#21179]Fix bug
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/M

#21229 fix rollback not exec
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/types.go
  pkg/cdc/util.go
  pkg/frontend/cdc.go
Labels: kind/bug, size/M

#21232 fix data copy in replaying from checkpoint
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/schema.go
Labels: kind/bug, size/S

#21234 [bug] stats: fix hang issue when get stats
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/M

#21228 [bug] stats: fix hang issue when get stats
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/M

#21231 fix snapshot and create table as of timestamp
  pkg/frontend/snapshot.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
  test/distributed/cases/snapshot/nonsys_create_snapshot_for_nonsys_db_table_level.result
  test/distributed/cases/snapshot/snapshot_database_level.result
  test/distributed/cases/snapshot/sys_create_snapshot_for_sys_db_table_level.result
Labels: kind/bug, size/S

#21230 enable shuffle reuse for shuffle join pipeline refactoring
  pkg/sql/colexec/shuffleV2/shufflepool.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/shuffle.go
Labels: size/M, kind/refactor

#21233 fix data copy in replaying from checkpoint - main
  pkg/container/vector/vector.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/schema.go
Labels: kind/bug, size/S

#21239 malloc: tune glibc malloc
  pkg/common/malloc/c_allocator.go
  pkg/common/malloc/utils.go
Labels: size/S, kind/enhancement

#21141 Plugin framework
  go.mod
  go.sum
  pkg/frontend/variables.go
  pkg/sql/colexec/table_function/plugin.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/plan/function/func_builtin_w.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/plugin.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/func_wasm.result
  test/distributed/cases/function/func_wasm.sql
  test/distributed/cases/plugin/plugin.result
  test/distributed/cases/plugin/plugin.sql
  test/distributed/resources/plugin/cat.wasm
  test/distributed/resources/plugin/hello.wasm
  test/distributed/resources/plugin/multistream.json
  test/distributed/resources/plugin/result.json
Labels: kind/feature, size/L

#21032 Reset flush s3 threshold
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/multi_update/insert.go
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/colexec/multi_update/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/plan/build_ddl.go
  proto/pipeline.proto
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
Labels: kind/bug, size/S, kind/enhancement

#21240 add retry option in Send()
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
Labels: kind/bug, size/S

#21244 reduce the memory consumption by storing points in the partition state.
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/types.go
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: size/S, kind/enhancement

#21245 to 2.0: reduce the memory consumption by using pointer as btree item in the partition state
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter.go
  pkg/vm/engine/disttae/logtailreplay/types.go
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: size/S, kind/api-change

#21247 Fix Transient VPool leak
  pkg/vm/engine/tae/tables/utils.go
Labels: kind/bug, size/XS

#21249 fix a bug for shuffle dop
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/shuffle_test.go
Labels: size/S, kind/refactor

#21254 to 2.0: skip to subscribe to the deleted table when calculating the mo table stats.
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: size/S, kind/enhancement

#21088 snapshot restore dropped account case
  test/distributed/cases/fulltext/fulltext2.sql
  test/distributed/cases/pitr/pitr.result
  test/distributed/cases/pitr/pitr.sql
  test/distributed/cases/pitr/pitr1.result
  test/distributed/cases/pitr/pitr1.sql
  test/distributed/cases/snapshot/restore_dropped_account.result
  test/distributed/cases/snapshot/restore_dropped_account.sql
Labels: kind/feature, size/XL

#21250 malloc: fix macos build
  pkg/common/malloc/c_allocator.go
  pkg/common/malloc/c_allocator_darwin.go
  pkg/common/malloc/c_allocator_linux.go
  pkg/common/malloc/c_allocator_test.go
Labels: kind/bug, size/S

#21248 optimize log entry with v2
  pkg/datasync/consumer_test.go
  pkg/datasync/entry.go
  pkg/datasync/entry_test.go
  pkg/datasync/producer_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/appender.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/codec.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/commit.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/entry_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/faker.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/group_committer.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/logentry.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/read.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replayer.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/v1.go
Labels: size/XXL, kind/refactor, kind/enhancement

#21262 Revert "malloc: default to malloc (#21211)"
  pkg/common/malloc/default.go
Labels: size/XS

#21263 to 2.0: notify global stats when subscribed table.
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
Labels: size/S

#21255 refactor: make table_function as source class operator
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/current_account.go
  pkg/sql/plan/fulltext.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/meta_scan.go
  pkg/sql/plan/metadata_scan.go
  pkg/sql/plan/plugin.go
  pkg/sql/plan/processlist.go
  pkg/sql/plan/pushdown.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/stage.go
  pkg/sql/plan/system_view.go
  pkg/sql/plan/unnest.go
  test/distributed/cases/fulltext/fulltext.result
Labels: size/M, kind/refactor

#21269 clean fields
  pkg/sql/plan/bind_context.go
  pkg/sql/plan/build_sample.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/types.go
Labels: size/M, kind/enhancement

#21273 fix mo_table_stats task panic and release mpool.
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: kind/bug, size/S

#21257 create index check duplicate index with same parts
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/bug, size/S

#21275 bug fix: Invalid search string converted to empty pattern to panic
  pkg/common/fulltext/fulltext.go
  pkg/common/fulltext/fulltext_test.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: kind/bug, size/S

#21274 fix operator of partition
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/partition/partition.go
  pkg/sql/colexec/partition/partition_test.go
Labels: size/S

#21266 prune incomplete sql
  pkg/cdc/sinker.go
Labels: kind/bug, size/XS

#21253 refactor checkpoint
  pkg/objectio/ioutil/const.go
  pkg/objectio/ioutil/sinker_test.go
  pkg/vm/engine/ckputil/meta.go
  pkg/vm/engine/ckputil/types.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/ckp_data.go
Labels: size/L, kind/refactor

#21278 fix TestGlobalCheckpoint7
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#21280 fix txn client deadlock 2.0
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
Labels: kind/bug, size/S

#21279 fix dead lock
  pkg/txn/client/client.go
  pkg/txn/client/client_test.go
  pkg/txn/client/operator.go
Labels: kind/bug, size/S

#21281 support dump for vecf32 and vecf64
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/S

#21282 support dump for vecf32 and vecf64(#2.0-dev)
  pkg/frontend/export.go
  pkg/frontend/export_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/array/array.sql
Labels: kind/bug, size/S
