Repository matrixorigin/matrixone, pull requests merged in 2025-07, with the labels that each got.

#22077 to 2.2: remove some prints.
  pkg/objectio/ioutil/pipeline.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, Review effort 2/5

#22078 remove some prints.
  pkg/objectio/ioutil/pipeline.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, Review effort 2/5

#22080 removed the object expansion logic in the workspace.
  pkg/cdc/watermark_updater_test.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/tools.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/M, kind/enhancement, Review effort 4/5

#22085 add case for replace
  test/distributed/cases/dml/replace/replace.result
  test/distributed/cases/dml/replace/replace.test
Labels: size/S, Review effort 2/5

#22092 enable new DML plan for tables with vector columns
  pkg/sql/plan/dml_context.go
Labels: kind/feature, size/XS, Review effort 2/5

#22094 fix failed BVT cases.
  test/distributed/cases/publication_subscription/pub_sub_improvement.result
  test/distributed/cases/snapshot/restore_dropped_account.result
  test/distributed/cases/snapshot/restore_dropped_account.sql
  test/distributed/cases/snapshot/restore_pub_to_new.result
  test/distributed/cases/snapshot/restore_pub_to_new.sql
  test/distributed/cases/zz_accesscontrol/grant_privs_role.result
  test/distributed/cases/zz_accesscontrol/grant_privs_role.sql
Labels: kind/bug, size/M, Review effort 2/5

#22089 enhance expr format
  pkg/sql/plan/utils.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/readutil/expr_filter.go
  pkg/vm/engine/readutil/expr_util.go
  pkg/vm/engine/readutil/pk_filter_base.go
Labels: kind/bug, size/M, Review effort 3/5

#22093 cdc frequency fix + createSql build bug fix
  pkg/cdc/sinker.go
  pkg/frontend/cdc_options.go
Labels: kind/bug, size/S, Review effort 2/5

#22110 fix any value for json (main)
  pkg/sql/plan/function/agg/any_value.go
Labels: kind/bug, size/XS, Review effort 2/5

#22106 add case for replace
  test/distributed/cases/dml/replace/replace.result
  test/distributed/cases/dml/replace/replace.test
Labels: size/S, Review effort 2/5

#22102 cleanup log 1
  pkg/frontend/compiler_context.go
  pkg/frontend/test/engine_mock.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_test.go
  pkg/sql/compile/scope.go
  pkg/txn/trace/service.go
  pkg/util/export/batch_processor.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/types.go
Labels: size/M, kind/enhancement, Review effort 3/5

#22113 Cdc for 2.2
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/sql_builder.go
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/cdc/testutil.go
  pkg/cdc/types.go
  pkg/cdc/types_test.go
  pkg/cdc/util.go
  pkg/cdc/util_test.go
  pkg/cdc/watermark_updater.go
  pkg/cdc/watermark_updater_test.go
  pkg/frontend/cdc_exector.go
  pkg/frontend/cdc_options.go
  pkg/frontend/cdc_test.go
  pkg/frontend/cdc_util.go
  pkg/vm/engine/tae/tasks/job.go
Labels: kind/feature, size/XXL, Review effort 4/5

#22116 Open commit inject logging
  pkg/objectio/injects.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: kind/bug, size/M, Review effort 2/5

#22111 bugfixes cherrypick to 2.2-dev
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/colexec/filter/filter_test.go
  pkg/sql/colexec/filter/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/dml_context.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/explain/explain_query.go
  pkg/sql/plan/explain/explain_test.go
  pkg/sql/plan/query_builder.go
  proto/pipeline.proto
  test/distributed/cases/dml/select/values.result
  test/distributed/cases/dml/select/values.sql
Labels: kind/bug, kind/feature, size/M, kind/enhancement, Review effort 4/5

#22124 make partition support index write
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/multi_update_partition.go
  pkg/sql/colexec/multi_update/types.go
  pkg/tests/partition/create_hash_test.go
  pkg/tests/partition/partition_index_test.go
Labels: kind/feature, size/M, Review effort 4/5

#22068 GC can handle different table share same object
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/executor.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/gc/v3/window_test.go
Labels: kind/feature, size/L

#22133 fix prints.
  pkg/vm/engine/disttae/txn_table.go
Labels: size/XS, Review effort 2/5

#22140 workaround txn commit failed but tn handled
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: size/S, Review effort 2/5

#22146 fix gc mpool leak
  pkg/vm/engine/tae/db/gc/v3/merge.go
Labels: kind/bug, size/XS, Review effort 2/5

#22143 fix force gckp
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/test/replay_test.go
Labels: kind/bug, size/S, Review effort 2/5

#22139 workaround txn commit failed but tn handled
  pkg/txn/client/operator.go
  pkg/txn/client/operator_test.go
Labels: size/S, Review effort 2/5

#22132 fix create pitr if exists
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_test.go
Labels: size/S, Review effort 3/5, Possible security concern

#22134 to 2.2: fix prints
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/test/snapshot_read_test.go
Labels: size/M, Review effort 2/5

#22145 fix force gckp for main
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/test/replay_test.go
Labels: kind/bug, size/S, Review effort 2/5

#22136 make internal sql executor support prepared statement
  pkg/sql/compile/sql_executor.go
  pkg/tests/testutils/test_utils.go
  pkg/tests/txnexecutor/txn_executor_test.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
Labels: kind/feature, size/M, Review effort 4/5, Possible security concern

#22157 Revert 22092 changes in 2.2-dev due to oom
  pkg/sql/plan/dml_context.go
Labels: kind/bug, size/XS, Review effort 2/5

#22152 enhance const fold pushdown
  pkg/sql/colexec/filter/filter_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/pushdown.result
  test/distributed/cases/optimizer/pushdown.test
Labels: kind/feature, size/L, Review effort 4/5

#22160 cleanup compact related code
  pkg/vm/engine/tae/tables/txnentries/command_test.go
  pkg/vm/engine/tae/tables/txnentries/compactblkcmd.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/types.go
Labels: size/M, kind/refactor, Review effort 2/5

#22158 partitioned tables support index queries
  pkg/partitionservice/service.go
  pkg/partitionservice/service_test.go
  pkg/sql/compile/scope.go
  pkg/tests/partition/partition_index_test.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_combined.go
  pkg/vm/engine/disttae/txn_table_combined_array.go
  pkg/vm/engine/disttae/txn_table_combined_partition.go
  pkg/vm/engine/disttae/txn_table_combined_test.go
  pkg/vm/engine/disttae/txn_table_delegate.go
  pkg/vm/engine/disttae/txn_table_delegate_test.go
  pkg/vm/engine/disttae/txn_table_partition.go
  pkg/vm/engine/disttae/txn_table_test.go
Labels: kind/feature, size/XXL, Review effort 4/5

#22164 bug fix:can not create database in some case
  pkg/frontend/authenticate.go
  test/distributed/cases/ddl/create_table_and_database.result
  test/distributed/cases/ddl/create_table_and_database.sql
Labels: kind/bug, size/S, Review effort 3/5, Possible security concern

#22162 fix the logic TS missing when cloning tables across accounts.
  pkg/frontend/clone.go
  pkg/sql/colexec/table_clone/table_clone.go
  pkg/vm/engine/disttae/table_meta_reader.go
  test/distributed/cases/snapshot/clone/database_clone.result
  test/distributed/cases/snapshot/clone/database_clone.sql
  test/distributed/cases/snapshot/clone/table_clone.result
  test/distributed/cases/snapshot/clone/table_clone.sql
Labels: kind/bug, size/M, Review effort 2/5

#22088 CI: use ustc ubuntu mirror
  optools/mo_checkin_regression/mo_checkin_regression_tke.yaml
Labels: kind/test-ci, Review effort 2/5

#22181 fix TestDedupSnapshot3
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci, Review effort 1/5

#22154 not lock insert select table
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  proto/plan.proto
  test/distributed/cases/pessimistic_transaction/ddl_atomicity.sql
  test/distributed/cases/pessimistic_transaction/drop_table.result
  test/distributed/cases/pessimistic_transaction/drop_table.sql
Labels: size/S, Review effort 3/5

#22184 Fix replay mpool leak
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
Labels: kind/bug, size/XS

#22182 fix rename column: delete table with old metadata
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.result
  test/distributed/cases/benchmark/tpch/02_LOAD/11_select_count_snapshot.sql
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
  test/distributed/cases/view/system_view.result
  test/distributed/cases/view/system_view.sql
Labels: kind/bug, size/S, Review effort 3/5

#22176 Fix Inconsistent SQL Query Results for the MO System Version.
  pkg/frontend/variables.go
  pkg/sql/plan/function/func_unary.go
Labels: kind/bug, size/S, Review effort 2/5

#22187 colexec/aggexec: add AggFuncExec.Size
  pkg/sql/colexec/aggexec/aggContext.go
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/aggMethod.go
  pkg/sql/colexec/aggexec/approx_count.go
  pkg/sql/colexec/aggexec/concat.go
  pkg/sql/colexec/aggexec/count.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/aggexec/fromBytesRetBytes.go
  pkg/sql/colexec/aggexec/fromBytesRetFixed.go
  pkg/sql/colexec/aggexec/fromFixedRetBytes.go
  pkg/sql/colexec/aggexec/fromFixedRetFixed.go
  pkg/sql/colexec/aggexec/median.go
  pkg/sql/colexec/aggexec/median_test.go
  pkg/sql/colexec/aggexec/result.go
  pkg/sql/colexec/aggexec/result_test.go
  pkg/sql/colexec/aggexec/tool.go
  pkg/sql/colexec/aggexec/types.go
  pkg/sql/colexec/aggexec/window.go
  pkg/sql/plan/function/agg/avg.go
  pkg/sql/plan/function/agg/avg_tw_cache.go
  pkg/sql/plan/function/agg/avg_tw_result.go
  pkg/sql/plan/function/agg/bitmap.go
  pkg/sql/plan/function/agg/size_test.go
  pkg/sql/plan/function/agg/sum.go
  pkg/sql/plan/function/agg/var_pop.go
Labels: size/L, kind/enhancement

#22192 fix add cdc task
  pkg/taskservice/mysql_task_storage.go
  pkg/taskservice/mysql_task_storage_test.go
  pkg/taskservice/task_service_holder_test.go
Labels: kind/bug, size/XS

#22194 Revert 22171 due to performance degradation
  pkg/fileservice/bytes.go
  pkg/fileservice/bytes_test.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fscache/data.go
  pkg/fileservice/io_vector.go
Labels: kind/bug, size/S

#22189 improvement: skip pk dedup in alter copy mode if pk is not changed
  pkg/defines/type.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_dml_util.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  proto/plan.proto
Labels: size/S, kind/enhancement

#22204 fix cdc with json
  pkg/cdc/sinker_test.go
  pkg/cdc/util.go
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
Labels: kind/bug, size/S

#22205 Fix cdc json 2.2
  pkg/cdc/sinker_test.go
  pkg/cdc/util.go
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
Labels: kind/bug, size/XS

#22206 colexec/external: log file system events in TestReadDirSymlink
  go.mod
  go.sum
  pkg/sql/colexec/external/external_test.go
Labels: size/S, kind/enhancement

#22188 Refactor show recovery window.
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v3_0_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v3_0_0/log.go
  pkg/bootstrap/versions/v3_0_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v3_0_0/upgrade.go
  pkg/bootstrap/versions/v3_0_0/upgrade_test.go
  pkg/frontend/authenticate.go
  pkg/frontend/pitr.go
  pkg/frontend/predefined.go
  pkg/frontend/show_recovery_window.go
  pkg/frontend/show_recovery_window_test.go
  pkg/frontend/snapshot.go
  pkg/sql/compile/ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/utils.go
  test/distributed/cases/snapshot/show_recovery_window.result
  test/distributed/cases/snapshot/show_recovery_window.sql
Labels: kind/bug, size/XXL

#22210 Remove try gc during replay
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
Labels: size/XS, kind/enhancement

#22212 for 2.2: cdc sync timing
  pkg/cdc/reader.go
Labels: kind/bug, size/XS

#22222 Add GCInMemoryTTL config for GC Catalog
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/testutils/config/options.go
Labels: size/S, kind/enhancement

#22221 support strcmp
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_id_test.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_string_strcmp.result
  test/distributed/cases/function/func_string_strcmp.test
Labels: kind/feature, size/M

#22179 [opt] implement RIGHT DEDUP join
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/group/execctx.go
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/rightdedupjoin/join.go
  pkg/sql/colexec/rightdedupjoin/join_test.go
  pkg/sql/colexec/rightdedupjoin/types.go
  pkg/sql/colexec/sample/sample.go
  pkg/sql/colexec/shufflebuild/build.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  pkg/vm/message/joinMapMsg.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
Labels: kind/feature, size/XL, kind/enhancement, Review effort 4/5

#22228 supports s3 write of index table data for partitioned tables
  pkg/sql/colexec/multi_update/delete.go
  pkg/sql/colexec/multi_update/insert.go
  pkg/sql/colexec/multi_update/insert_test.go
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/multi_update_partition.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/multi_update/types.go
  pkg/sql/compile/sql_executor.go
  pkg/tests/partition/s3_load_test.go
  pkg/tests/testutils/test_utils.go
Labels: kind/feature, size/L

#22225 change unsigned cast rule
  pkg/sql/plan/function/type_check.go
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dtype/bigint.result
  test/distributed/cases/function/func_aggr_bitwise.result
Labels: kind/bug, size/L

#22235 rm tag 8848
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.sql
Labels: kind/bug, size/S

#22232 fix partition affected rows not work
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/multi_update_partition.go
  pkg/sql/colexec/multi_update/types.go
  pkg/tests/partition/affected_rows_test.go
  pkg/tests/partition/s3_load_test.go
Labels: kind/bug, size/M

#22238 Add DefaultGlobalVersionInterval config
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
Labels: size/XS, kind/enhancement

#22234 adding more err msg for UT `TestIssue19551`
  pkg/tests/issues/issue_test.go
Labels: size/S, kind/enhancement

#22245 cleanup mo log 2
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/refactor

#22224 improvement: skip unique idx dedup in alter copy mode if those idxs remain unchanged
  pkg/defines/type.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_dml_util.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  proto/plan.proto
  test/distributed/cases/ddl/alter.result
  test/distributed/cases/ddl/alter.sql
  test/distributed/resources/load_data/dup_load.csv
Labels: size/M, kind/enhancement

#22253 fix shuffle RIGHT DEDUP join
  pkg/sql/compile/compile.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/shuffle.go
  test/distributed/cases/optimizer/insert.result
Labels: kind/bug, size/S

#22252 make sure the snapshot read TS greater than the TXN logic TS when create snapshot or clone.
  pkg/frontend/clone.go
  pkg/frontend/snapshot.go
Labels: kind/bug, size/S

#22257 add debug log
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/XS

#22223 CN can flush small objects by fault injection.
  pkg/objectio/injects.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/s3util.go
  pkg/sql/plan/function/fault/fault_test.go
  pkg/sql/plan/function/func_binary.go
  pkg/sql/plan/function/func_unary.go
  pkg/util/fault/handler.go
  test/distributed/cases/disttae/disttae_filters/ranges_filters/ranges_filters.result
  test/distributed/cases/disttae/disttae_filters/ranges_filters/ranges_filters.sql
  test/distributed/cases/disttae/disttae_filters/reader_filters/block_reader/between_filter.result
  test/distributed/cases/disttae/disttae_filters/reader_filters/block_reader/between_filter.sql
  test/distributed/cases/disttae/disttae_filters/reader_filters/block_reader/block_reader_filter.result
  test/distributed/cases/disttae/disttae_filters/reader_filters/block_reader/block_reader_filter.sql
  test/distributed/cases/optimizer/runtimefilter.result
  test/distributed/cases/optimizer/runtimefilter.test
  test/distributed/cases/optimizer/top.result
  test/distributed/cases/optimizer/top.test
  test/distributed/cases/save_query_result/save_query_result.sql
  test/distributed/cases/snapshot/cluster/restore_dropped_account_to_new.sql
  test/distributed/cases/snapshot/cluster/restore_dropped_account_with_account_sp.sql
  test/distributed/cases/snapshot/cluster/restore_dropped_account_with_cluster.sql
  test/distributed/cases/snapshot/cluster/restore_dropped_account_with_cluster_2.sql
  test/distributed/cases/snapshot/restore_dropped_account.sql
  test/distributed/cases/tenant/drop_account.sql
Labels: size/L, kind/enhancement

#22269 fix Test_CheckpointChaos3
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#22261 remove all table retention-related code.
  pkg/bootstrap/versions/v2_0_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v3_0_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v3_0_0/upgrade.go
  pkg/catalog/types.go
  pkg/cnservice/server_task.go
  pkg/common/moerr/cause.go
  pkg/common/moerr/cause_test.go
  pkg/frontend/authenticate.go
  pkg/frontend/predefined.go
  pkg/frontend/snapshot.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.go
  pkg/pb/task/task.pb.go
  pkg/predefine/predefine.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/util.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/function/ctl/cmd_task.go
  proto/plan.proto
  proto/task.proto
  test/distributed/cases/ddl/create_retention_table.result
  test/distributed/cases/ddl/create_retention_table.sql
  test/distributed/cases/disttae/mo_table_stats/mo_table_stats3.result
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/metadata/information_schema.result
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.result
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
  test/distributed/cases/zz_accesscontrol/create_account.result
Labels: size/XXL, kind/enhancement

#22268 add debug log
  pkg/frontend/cdc_dao.go
  pkg/vm/engine/tae/tables/appender.go
Labels: kind/bug, size/S

#22249 Support 'where tuple in tupleList'
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/base_binder.go
  pkg/sql/plan/function/func_compare.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/test/disttae_engine_test.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/feature, size/M

#22267 Generate_random_int64/float64 table functions.
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/genrandom.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/plan/generate_series.go
  pkg/sql/plan/query_builder.go
  test/distributed/cases/function/table_func_generate_series.result
  test/distributed/cases/function/table_func_generate_series.test
  test/distributed/cases/join/apply.result
Labels: kind/feature, size/L

#22273 fix string bigint(20) unsigned
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/types.go
Labels: size/S

#22277 fix union all select fulltext
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/utils.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: size/S

#22276 fix union all select fulltext
  pkg/sql/plan/function/list_builtIn.go
  pkg/sql/plan/utils.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: size/S

#22240 fileservice: add FileService.NewReader/NewWriter
  cmd/mo-service/debug_test.go
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/memory_fs.go
  pkg/fileservice/reader_writer_file_service.go
Labels: size/M, kind/enhancement

#22237 colexec/aggexec: implement marshal/unmarshal for distinctHash; export special agg ids
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/concat.go
  pkg/sql/colexec/aggexec/count.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/aggexec/median_test.go
  pkg/sql/colexec/aggexec/register.go
  pkg/sql/colexec/aggexec/serialize.go
  pkg/sql/colexec/aggexec/types.go
  pkg/sql/colexec/aggexec/window.go
Labels: size/M, kind/enhancement

#22281 Optimize s3writer
  pkg/container/batch/batch.go
  pkg/objectio/ioutil/sinker.go
  pkg/objectio/ioutil/sinker_test.go
  pkg/objectio/mergeutil/types.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/table_meta_reader.go
  pkg/vm/engine/disttae/transfer_util.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/readutil/datasource_test.go
  pkg/vm/engine/readutil/tombstone_data_test.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/utils_test.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/util.go
  pkg/vm/engine/tae/db/gc/v3/window_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/XL, kind/enhancement
