Repository matrixorigin/matrixone, pull requests merged in 2025-08, with the labels that each got.

#22293 fix right join dedup memory leak
  pkg/sql/colexec/rightdedupjoin/join.go
Labels: kind/bug, size/XS, Review effort 2/5

#22295 Pick 22284 22293 to 3.0-dev
  pkg/objectio/ioutil/sinker.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/rightdedupjoin/join.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/table_meta_reader.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/readutil/datasource_test.go
  pkg/vm/engine/readutil/tombstone_data_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/M, kind/enhancement, Review effort 4/5

#22215 Add Force GC
  pkg/cnservice/server_query.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/plan/function/ctl/cmd_disk_cleaner.go
  pkg/tnservice/factory.go
  pkg/tnservice/store.go
  pkg/txn/client/client.go
  pkg/txn/storage/tae/storage.go
  pkg/vm/engine/cmd_util/type.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/gc/v3/mock_cleaner.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/test/testutil/tae_engine.go
  proto/query.proto
  test/distributed/cases/dml/checkpoint/checkpoint.result
  test/distributed/cases/dml/checkpoint/checkpoint.test
Labels: kind/feature, size/M

#22282 fix shuffle join
  pkg/lockservice/cfg.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/shuffle.go
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/ddl/secondary_index_insert.sql
Labels: kind/bug, size/M

#22285 memory throttler for CN-flush-S3, workspace and merge.
  pkg/cnservice/server.go
  pkg/cnservice/types.go
  pkg/common/rscthrottler/resource_throttler.go
  pkg/common/rscthrottler/resource_throttler_test.go
  pkg/common/runtime/types.go
  pkg/config/configuration.go
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/multi_update_partition.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/multi_update/types.go
  pkg/sql/colexec/multi_update/util_for_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/merge/simulator.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/L, kind/enhancement

#22305 fix shuffle join (cp #22282)
  pkg/lockservice/cfg.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/compile/compile.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/shuffle.go
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/ddl/secondary_index_insert.sql
Labels: kind/bug, size/M, Review effort 3/5

#22309 add cases issue 18667
  test/distributed/cases/dml/select/select.result
  test/distributed/cases/dml/select/select.test
Labels: kind/bug, size/S, Review effort 2/5

#22314 Fix 22307 pick to 3.0
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnimpl/database.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: kind/bug, size/M, Review effort 3/5

#22315 fix empty unique index after altering 3.0
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/self_handle.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/prepare.go
  pkg/sql/plan/bind_insert.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  test/distributed/cases/ddl/create_index.result
  test/distributed/cases/ddl/create_index.sql
Labels: kind/bug, size/XXL, Review effort 3/5

#22292 add table id batch
  pkg/vm/engine/cmd_util/operations.go
  pkg/vm/engine/cmd_util/operations.pb.go
  pkg/vm/engine/cmd_util/operations.proto
  pkg/vm/engine/tae/db/checkpoint/cfg.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/meta.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/snapshot.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/options/cfg.go
  pkg/vm/engine/tae/rpc/handle_debug.go
Labels: kind/feature, size/XL, Review effort 4/5

#22303 fix 'db not selected' error in alter table
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/result_row_stmt.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/analyze_module_test.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build_alter_table.go
  pkg/util/trace/impl/motrace/statistic/stats_array.go
Labels: kind/bug, size/L, Review effort 3/5

#22323 fix show linear partition
  pkg/sql/plan/build_show_util.go
  pkg/tests/partition/create_hash_test.go
Labels: size/XS, Review effort 2/5

#22317 Fix the foreign key reference mismatch in clone statements.
  pkg/frontend/clone.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/snapshot.go
  pkg/sql/parsers/tree/clone.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_show_util.go
  pkg/sql/plan/build_show_util_test.go
  pkg/sql/plan/build_table_clone.go
  test/distributed/cases/snapshot/clone/clone_reference.result
  test/distributed/cases/snapshot/clone/clone_reference.sql
  test/distributed/cases/snapshot/clone/table_clone.result
  test/distributed/cases/snapshot/clone/table_clone.sql
Labels: kind/bug, size/L, Review effort 4/5

#22331 flushing objects in chunks 3.0
  pkg/vm/engine/tae/db/checkpoint/flusher.go
Labels: size/S, kind/enhancement, Review effort 3/5

#22329 some simple restrictions on clone privilege.
  pkg/frontend/clone.go
  pkg/frontend/pitr.go
  pkg/frontend/snapshot.go
  pkg/sql/parsers/tree/clone.go
  pkg/sql/plan/build_table_clone.go
  test/distributed/cases/snapshot/clone/clone_privilege.result
  test/distributed/cases/snapshot/clone/clone_privilege.sql
Labels: kind/feature, size/M, Review effort 2/5

#22300 Adding llm_chat function to starlark stored procedure.
  go.mod
  go.sum
  pkg/frontend/starlark_interpreter.go
  pkg/monlp/llm/llm.go
  pkg/monlp/llm/mockllm.go
  pkg/monlp/llm/mockllm_test.go
  pkg/monlp/llm/ollama.go
  pkg/monlp/llm/ollama_test.go
  test/distributed/cases/procedure/starlark_llm.result
  test/distributed/cases/procedure/starlark_llm.sql
Labels: kind/feature, size/L, Review effort 4/5

#22333 to 3.0: restrict MO_CTL execution of cn merge within explicit transactions
  pkg/sql/plan/function/ctl/ctl.go
  test/distributed/cases/function/mo_ctl/mo_ctl_merge.result
  test/distributed/cases/function/mo_ctl/mo_ctl_merge.test
Labels: kind/bug, size/S, Review effort 2/5

#22334 Add llm_chat and llm_embedding function.
  go.mod
  go.sum
  pkg/container/types/array.go
  pkg/container/types/array_str_test.go
  pkg/container/types/array_test.go
  pkg/monlp/llm/llm.go
  pkg/monlp/llm/mockllm.go
  pkg/monlp/llm/mockllm_test.go
  pkg/monlp/llm/ollama.go
  pkg/monlp/llm/ollama_test.go
  pkg/sql/colexec/table_function/parsejsonl.go
  pkg/sql/plan/function/func_builtin_llm.go
  pkg/sql/plan/function/function_id.go
  pkg/sql/plan/function/function_id_test.go
  pkg/sql/plan/function/list_builtIn.go
  test/distributed/cases/function/func_llm.result
  test/distributed/cases/function/func_llm.sql
Labels: kind/feature, size/M, Review effort 3/5, Possible security concern

#22355 container/hashtable: use longer than 16 bytes keys in tests
  pkg/common/malloc/inuse_tracking_allocator.go
  pkg/common/malloc/inuse_tracking_allocator_test.go
  pkg/container/hashtable/hash_test.go
  pkg/container/hashtable/int64_hash_map.go
  pkg/container/hashtable/malloc.go
  pkg/container/hashtable/string_hash_map.go
  pkg/container/hashtable/util_test.go
Labels: kind/bug, size/M, Review effort 3/5

#22354 Fix fuzzyfilter 3.0
  pkg/sql/colexec/fuzzyfilter/filter.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  test/distributed/cases/dml/replace/replace.result
  test/distributed/cases/dml/replace/replace.test
Labels: kind/bug, size/M, Review effort 2/5

#22344 to 3.0: Fix the appendable tombstone object clone logic.
  pkg/frontend/pitr.go
  pkg/objectio/ioutil/funcs.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/table_meta_reader.go
  test/distributed/cases/snapshot/clone/clone_appendable_obj.result
  test/distributed/cases/snapshot/clone/clone_appendable_obj.sql
Labels: kind/bug, size/M, Review effort 3/5

#22351 Left/Inner join produces better chunks
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
Labels: size/L, kind/enhancement, Review effort 4/5

#22356 pick Left/Inner join produces better chunks (#22351) to 3.0-dev
  pkg/sql/colexec/join/join.go
  pkg/sql/colexec/join/types.go
  pkg/sql/colexec/left/join.go
  pkg/sql/colexec/left/types.go
Labels: kind/bug, size/L, Review effort 4/5

#22370 fix context deadline not set
  pkg/frontend/cdc_exector.go
Labels: kind/bug, size/XS, Review effort 2/5

#22372 fix context deadline not set
  pkg/frontend/cdc_exector.go
Labels: kind/bug, size/XS, Review effort 2/5

#22375 fix cdc table scanner
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/frontend/cdc_exector.go
  pkg/objectio/injects.go
Labels: kind/bug, size/S, Review effort 2/5

#22377 fix cdc scanner
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/frontend/cdc_exector.go
  pkg/objectio/injects.go
Labels: kind/bug, size/S, Review effort 3/5

#22378 display stats for each operator in EXPLAIN PHYPLAN ANALYZE
  pkg/sql/compile/analyze_module.go
  pkg/sql/models/phy_plan.go
  pkg/vm/process/operator_analyzer.go
Labels: kind/feature, size/S, Review effort 2/5

#22384 change code owners
  CODEOWNERS
Labels: kind/documentation, size/S, Review effort 2/5

#22389 fix cdc sinker and handle new table
  pkg/cdc/sinker.go
  pkg/cdc/types.go
  pkg/cdc/util.go
  pkg/frontend/cdc_exector.go
  pkg/vm/engine/test/cdc_sinker_test.go
Labels: kind/bug, size/M, Review effort 2/5

#22341 add case for issue 15359 and 22301
  test/distributed/cases/function/func_string_strcmp.result
  test/distributed/cases/function/func_string_strcmp.test
  test/distributed/cases/snapshot/clone/clone.result
  test/distributed/cases/snapshot/clone/clone.sql
  test/distributed/cases/snapshot/clone/clone_db_table_to_new_db_table.result
  test/distributed/cases/snapshot/clone/clone_db_table_to_new_db_table.sql
  test/distributed/cases/snapshot/clone/clone_sys_db_table_to_new_db_table.result
  test/distributed/cases/snapshot/clone/clone_sys_db_table_to_new_db_table.sql
Labels: kind/bug, size/XXL, Review effort 3/5

#22364 add bvt and ut for inner/left join
  pkg/sql/colexec/join/join_test.go
  pkg/sql/colexec/left/join_test.go
  test/distributed/cases/join/join.result
  test/distributed/cases/join/join.test
  test/distributed/cases/join/leftjoin.result
  test/distributed/cases/join/leftjoin.test
Labels: size/L, kind/test-ci, Review effort 3/5

#22403 optimize top operator's batch processing 3.0
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/top/top.go
Labels: size/M, kind/refactor

#22399 fix clone bvt
  test/distributed/cases/snapshot/clone/clone.result
  test/distributed/cases/snapshot/clone/clone.sql
Labels: kind/bug, size/M

#22404 optimize top operator's batch processing
  pkg/sql/colexec/mergetop/top.go
  pkg/sql/colexec/top/top.go
Labels: size/M, kind/refactor

#22406 to 3.0: report the error when the subscription table fails.
  pkg/fulltext/fixedbytepool.go
  pkg/objectio/injects.go
  pkg/sql/colexec/anti/join.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/txn_table.go
  test/distributed/cases/snapshot/clone/table_clone.result
  test/distributed/cases/snapshot/clone/table_clone.sql
Labels: size/S

#22379 update ISCP workers
  pkg/iscp/consumer.go
  pkg/iscp/iteration.go
  pkg/iscp/mock_consumer.go
  pkg/iscp/types.go
  pkg/iscp/watermark_updater.go
  pkg/iscp/worker.go
  pkg/vm/engine/test/cdc_testutil.go
  pkg/vm/engine/test/change_handle_test.go
Labels: size/M, kind/enhancement, Review effort 2/5

#22411 Try snapshot read if the subscription does not exist.
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#22412 to 3.0: Try snapshot read if the subscription does not exist.
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#22402 fix TestProcessCallBack
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
Labels: kind/bug, size/S

#22427 fix data race
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
Labels: kind/bug, size/S

#22410 create/drop cdc internal
  pkg/cnservice/server.go
  pkg/cnservice/server_task.go
  pkg/embed/testing.go
  pkg/frontend/back_exec.go
  pkg/frontend/compiler_context.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/types.go
  pkg/frontend/util_test.go
  pkg/frontend/variables.go
  pkg/partitionprune/filter_test.go
  pkg/partitionprune/prune_test.go
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/colexec/lockop/lock_op_no_txn.go
  pkg/sql/colexec/lockop/lock_op_test.go
  pkg/sql/colexec/table_function/system_view_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_test.go
  pkg/sql/compile/remoterunServer.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/types.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/cdc.go
  pkg/sql/parsers/tree/stmt.go
  pkg/sql/parsers/tree/stmt_test.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/function/ctl/cmd_ping_test.go
  pkg/tests/ddl/ddl_test.go
  pkg/testutil/util_new.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/db_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/process/process.go
  pkg/vm/process/process2.go
  pkg/vm/process/process2_test.go
  pkg/vm/process/process_codec.go
  pkg/vm/process/types.go
  proto/plan.proto
Labels: size/XXL

#22434 Fixed the bug that caused GC Verify to panic when running during checkpoint but not completed.
  pkg/vm/engine/tae/db/gc/v3/check.go
  pkg/vm/engine/tae/db/gc/v3/window.go
Labels: size/S

#22417 stage remove enable/disable
  pkg/frontend/authenticate.go
  pkg/sql/plan/build_show.go
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_nonsys.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_system_table_to_sys_account.result
  test/distributed/cases/snapshot/nonsys_restore_system_table_to_nonsys_account.result
  test/distributed/cases/snapshot/restore_dropped_account.result
  test/distributed/cases/snapshot/snapshot_restore_system_table.result
  test/distributed/cases/snapshot/snapshot_restore_system_table.sql
  test/distributed/cases/snapshot/sys_restore_system_table_to_newnonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_nonsys_account.result
  test/distributed/cases/snapshot/sys_restore_system_table_to_sys_account.result
  test/distributed/cases/stage/external_stage.result
  test/distributed/cases/stage/external_stage_columns.result
  test/distributed/cases/stage/stage.result
  test/distributed/cases/stage/stage_based_stage.result
  test/distributed/cases/stage/stage_based_stage_columns.result
Labels: kind/bug, size/M

#22432 fore next after StaleReadErr
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
Labels: kind/bug, size/M

#22436 GC collects data from the mo_pitr table and needs to determine whether mo_catalog
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S

#22425 allow queries selecting distance to use vector index
  pkg/sql/plan/apply_indices_hnsw.go
  pkg/sql/plan/apply_indices_ivfflat.go
  pkg/sql/plan/apply_indices_vector.go
  test/distributed/cases/vector/vector_hnsw.result
  test/distributed/cases/vector/vector_hnsw.sql
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: kind/feature, size/M

#22423 clone with snapshot should match the snapshot level and owner.
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/snapshot.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/plan/build_table_clone.go
  proto/plan.proto
  test/distributed/cases/snapshot/clone/clone_privilege.result
  test/distributed/cases/snapshot/clone/clone_privilege.sql
  test/distributed/cases/snapshot/clone/snapshot_mismatch.result
  test/distributed/cases/snapshot/clone/snapshot_mismatch.sql
Labels: kind/bug, size/M

#22433 Force next after StaleReadErr
  pkg/cdc/reader.go
  pkg/cdc/reader_test.go
Labels: kind/bug, size/M

#22445 fix data race for taskservice
  pkg/cnservice/server.go
  pkg/cnservice/server_task.go
  pkg/config/configuration.go
  pkg/frontend/back_exec.go
  pkg/frontend/cdc_dao.go
  pkg/frontend/cdc_handle.go
  pkg/frontend/connector.go
  pkg/frontend/connector_test.go
  pkg/frontend/session.go
  pkg/frontend/show_account.go
  pkg/frontend/task.go
  pkg/frontend/task_test.go
Labels: size/M

#22447 secondary index table support replace into
  pkg/sql/plan/bind_replace.go
Labels: kind/bug, size/XS

#22385 to 3.0: apply cow to indexes if the primary key and indexed columns are not modified when ALTER TABLE
  pkg/defines/type.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/multi_update/insert.go
  pkg/sql/colexec/table_clone/table_clone.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_table_clone.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/engine/disttae/txn_database.go
  proto/plan.proto
  test/distributed/cases/snapshot/clone/clone_in_alter_table.result
  test/distributed/cases/snapshot/clone/clone_in_alter_table.sql
Labels: size/L, kind/enhancement, Review effort 4/5

#22380 apply cow to indexes if the primary key and indexed columns are not modified when ALTER TABLE.
  pkg/defines/type.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/multi_update/insert.go
  pkg/sql/colexec/table_clone/table_clone.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_change_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_rename_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_table_clone.go
  pkg/util/executor/options.go
  pkg/util/executor/types.go
  pkg/vm/engine/disttae/txn_database.go
  proto/plan.proto
  test/distributed/cases/snapshot/clone/clone_in_alter_table.result
  test/distributed/cases/snapshot/clone/clone_in_alter_table.sql
Labels: size/L, kind/enhancement, Review effort 4/5

#22264 RIGHT DEDUP join PRs cherry-pick to 2.2-dev
  pkg/common/hashmap/strhashmap.go
  pkg/common/hashmap/strhashmap_test.go
  pkg/container/batch/batch.go
  pkg/lockservice/cfg.go
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/aggexec/distinct.go
  pkg/sql/colexec/group/execctx.go
  pkg/sql/colexec/hashmap_util/hashmap_util.go
  pkg/sql/colexec/intersect/intersect.go
  pkg/sql/colexec/intersectall/intersectall.go
  pkg/sql/colexec/minus/minus.go
  pkg/sql/colexec/rightdedupjoin/join.go
  pkg/sql/colexec/rightdedupjoin/join_test.go
  pkg/sql/colexec/rightdedupjoin/types.go
  pkg/sql/colexec/sample/sample.go
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shufflebuild/build.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/debugTools.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/dml_context.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/shuffle.go
  pkg/sql/plan/stats.go
  pkg/vm/message/joinMapMsg.go
  pkg/vm/types.go
  proto/pipeline.proto
  proto/plan.proto
  test/distributed/cases/ddl/secondary_index_insert.result
  test/distributed/cases/ddl/secondary_index_insert.sql
  test/distributed/cases/optimizer/insert.result
Labels: kind/feature, size/XL

#22453 fix oltp performance degradation
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S

#22454 fix oltp query performance degradation to 3.0-dev
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_test.go
  pkg/vm/engine/disttae/types.go
Labels: kind/bug, size/S
