Repository matrixorigin/matrixone, pull requests merged in 2025-03, with the labels that each got.

#21467 Fix various merge issues
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyGroup.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/mergesort/task.go
Labels: size/M

#21444 refactor: AnalyzeExecPlan reduce CPU usage in Prepare mode
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/types.go
Labels: size/S, kind/refactor

#21466 Support new time hint
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/create.go
  pkg/sql/parsers/tree/table_name.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
  test/distributed/cases/snapshot/create_table_as_select_as_of_timestamp.result
  test/distributed/cases/snapshot/create_table_as_select_as_of_timestamp.sql
Labels: kind/feature, size/XXL

#20948 fileservice: add HDFS
  etc/launch-hdfs/cn.toml
  etc/launch-hdfs/launch.toml
  etc/launch-hdfs/log.toml
  etc/launch-hdfs/tn.toml
  go.mod
  go.sum
  pkg/fileservice/error.go
  pkg/fileservice/hdfs.go
  pkg/fileservice/hdfs_test.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_arguments_test.go
  pkg/fileservice/object_storage_test.go
  pkg/fileservice/s3_fs.go
Labels: size/L, kind/enhancement

#21464 minor improve for loop join
  pkg/sql/colexec/loopjoin/join.go
  test/distributed/cases/join/join.result
  test/distributed/cases/join/join.test
Labels: kind/bug, size/S, kind/enhancement

#21472 mitigate zm merge
  pkg/vm/engine/tae/db/merge/policyOverlap.go
Labels: size/XS, kind/enhancement

#21451 Add recovery window
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_3/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_3/log.go
  pkg/bootstrap/versions/v2_0_3/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_3/upgrade.go
  pkg/bootstrap/versions/v2_0_3/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/predefined.go
  pkg/frontend/query_result.go
  pkg/frontend/self_handle.go
  pkg/frontend/show_recovery_window.go
  pkg/frontend/show_recovery_window_test.go
  pkg/frontend/types.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/pitr.go
  pkg/sql/parsers/tree/stmt.go
  test/distributed/cases/pitr/pitr.result
  test/distributed/cases/pitr/pitr.sql
  test/distributed/cases/pitr/pitr_basic.result
  test/distributed/cases/pitr/pitr_basic.sql
  test/distributed/cases/pitr/pitr_inherit.result
  test/distributed/cases/pitr/pitr_inherit.sql
  test/distributed/cases/snapshot/show_recovety_window.result
  test/distributed/cases/snapshot/show_recovety_window.sql
Labels: kind/feature, size/XXL

#21476 Fix 21469
  .gitignore
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
Labels: size/S, kind/test-ci

#21459 refactor checkpoint
  pkg/backup/tae.go
  pkg/datasync/consumer.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/tae/db/checkpoint/cfg.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/checkpoint/store.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/mock_cleaner.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/storage_usage_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_data.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/logtail/table_test.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/tool.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
Labels: size/XXL, kind/refactor

#21471 fix: load parser error when line terminate with \r\n
  pkg/sql/util/csvparser/csv_parser.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
  test/distributed/resources/load_data/test_parse_newline.csv
Labels: kind/bug, size/M

#21493 Split batchs for shuffleV2
  pkg/container/batch/compact_batchs.go
  pkg/container/batch/compact_batchs_test.go
  pkg/sql/colexec/shuffleV2/shuffle.go
  pkg/sql/colexec/shuffleV2/shufflepool.go
  pkg/sql/colexec/shuffleV2/types.go
Labels: size/M, kind/refactor, kind/enhancement

#21494 make ParamExprEvaluator can resuse the memory
  pkg/sql/colexec/evalExpression.go
  pkg/sql/colexec/evalExpressionReset.go
Labels: size/S, kind/enhancement

#21497 Revert "Add recovery window (#21451)"
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_3/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_3/tenant_upgarde_list.go
  pkg/bootstrap/versions/v2_0_3/upgarde_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/pitr.go
  pkg/frontend/pitr_test.go
  pkg/frontend/predefined.go
  pkg/frontend/query_result.go
  pkg/frontend/self_handle.go
  pkg/frontend/show_recovery_window.go
  pkg/frontend/show_recovery_window_test.go
  pkg/frontend/types.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/keywords.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/pitr.go
  pkg/sql/parsers/tree/stmt.go
  test/distributed/cases/pitr/pitr.result
  test/distributed/cases/pitr/pitr.sql
  test/distributed/cases/pitr/pitr_basic.result
  test/distributed/cases/pitr/pitr_basic.sql
  test/distributed/cases/pitr/pitr_inherit.result
  test/distributed/cases/pitr/pitr_inherit.sql
  test/distributed/cases/snapshot/show_recovety_window.result
  test/distributed/cases/snapshot/show_recovety_window.sql
Labels: kind/bug, size/XXL

#21496 fileservice: various HDFS fixes
  pkg/fileservice/get.go
  pkg/fileservice/hdfs.go
  pkg/fileservice/hdfs_test.go
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/s3_fs.go
Labels: size/S, kind/enhancement

#21504 Fast fix for exceeding the object size limit.
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/M

#21500 refactor checkpoint
  pkg/vm/engine/ckputil/types.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
Labels: size/L, kind/refactor

#21468 change auto merge required reviewer for non-main branch
  .github/mergify.yml
Labels: kind/test-ci

#21491 refactor: improve authenticateCanExecuteStatementAndPlan for execute …
  pkg/frontend/computation_wrapper.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/S, kind/refactor

#21442 increase memory estimation
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
Labels: size/S, kind/enhancement

#21510 different exception when getting non-exist wasm file
  test/distributed/cases/function/func_wasm.result
  test/distributed/cases/function/func_wasm.sql
Labels: kind/bug, size/XS

#21514 add new upgrade entry
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_1_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_1_0/log.go
  pkg/bootstrap/versions/v2_1_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_1_0/upgrade.go
  pkg/bootstrap/versions/v2_1_0/upgrade_test.go
Labels: kind/bug, size/L

#21507 split batches for shuffle operator
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/shuffle_test.go
  pkg/sql/colexec/shuffle/shufflepool.go
  pkg/sql/colexec/shuffle/types.go
  pkg/sql/colexec/shuffleV2/shuffle_test.go
  pkg/sql/colexec/shuffleV2/shufflepool.go
Labels: size/M, kind/refactor, kind/enhancement

#21518 fix bug: can not get stats cache in txn Executor
  pkg/sql/compile/sql_executor_context.go
Labels: kind/bug, size/XS

#21516 fix: bvt in prepare.test
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/XS

#21479 update replay
  pkg/objectio/injects.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
Labels: size/M, kind/enhancement

#21517 change upgrade entry
  pkg/bootstrap/versions/v2_0_3/upgrade.go
  pkg/bootstrap/versions/v2_0_3/upgrade_test.go
Labels: kind/bug, size/M

#21521 fix replay
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
Labels: kind/bug, size/S

#21509 [#21508]Fix bug
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
Labels: size/M

#21528 sync verfied 2.0 merge changes to 2.1
  pkg/objectio/ioutil/writer.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/table_test.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyGroup.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/mergesort/types_test.go
Labels: kind/bug, size/L, kind/enhancement

#21536 modify mergify config to adapt 2.1-dev
  .github/mergify.yml
Labels: kind/test-ci

#21541 improve the performance of cleaning up the deleted table stats from the stats table.
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/mo_table_stats_test.go
Labels: size/S, kind/enhancement

#21542 to 2.1: improve the performance of cleaning up the deleted table stats from the stats table.
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/mo_table_stats_test.go
Labels: size/S, kind/enhancement

#21533 sync verfied 2.0 merge changes to 2.1
  pkg/objectio/ioutil/writer.go
  pkg/objectio/writer.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/table_test.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyGroup.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/mergesort/merger.go
  pkg/vm/engine/tae/mergesort/reshaper.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/mergesort/types.go
  pkg/vm/engine/tae/mergesort/types_test.go
Labels: kind/bug, size/L, kind/enhancement

#21545 fix: ignore some test in prepare.test
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/S, kind/test-ci

#21548 fix read ckp meta
  pkg/vm/engine/tae/logtail/ckp_reader.go
Labels: kind/bug, size/XS

#21550 malloc: fix VSS leaks
  pkg/common/malloc/fixed_size_mmap_allocator.go
Labels: kind/bug, size/S

#21543 malloc: fix VSS leaks
  pkg/common/malloc/fixed_size_mmap_allocator.go
Labels: kind/bug, size/S

#21554 fix: ignore some test in prepare.test
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/S, kind/test-ci

#21539 Fixed GC merge checkpoint memory leak
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
Labels: kind/bug, size/S

#21547 fix ckp meta
  pkg/vm/engine/ckputil/meta.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
Labels: kind/bug, size/S

#21559 Small refactor ckp
  pkg/objectio/ioutil/codec.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/meta.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: size/M, kind/refactor

#21561 Fix potential memory leak
  pkg/backup/tae.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/M, Review effort 3/5

#21562 fix adding incorrect delete entris to partition state index 2.1
  pkg/objectio/name.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
Labels: kind/bug, size/S, Review effort 2/5

#21563 fix potential memory leak
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/logtail/utils.go
Labels: kind/bug, size/S, Review effort 2/5

#21568 fix the prepare.test BVT case.
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/S, Review effort 2/5

#21569 to 2.1: fix the prepare.test BVT case.
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: size/S, kind/test-ci, Review effort 2/5

#21571 fix timeout - main
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
Labels: kind/bug, size/S, Review effort 2/5

#21570 fix timeout
  pkg/vm/engine/tae/logstore/driver/logservicedriver/clientpool.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
Labels: kind/bug, size/S, Review effort 2/5

#21529 spherical kmeans for sparse vector and bug fix
  pkg/frontend/variables.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/table_function/ivf_create.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/vectorindex/hnsw/build_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer.go
  pkg/vectorindex/metric/distance_func.go
  pkg/vectorindex/metric/distance_func_test.go
  pkg/vectorindex/types.go
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
Labels: kind/bug, size/L, kind/enhancement

#21558 fix adding incorrect delete entris to partition state index
  pkg/objectio/name.go
  pkg/vm/engine/disttae/logtailreplay/partition.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
Labels: kind/bug, size/S

#21549 fix: AnalyzeExecPlan bug which cause sysbench10w update panic
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/analyze_module_test.go
  pkg/sql/compile/compile2.go
Labels: kind/bug, size/M

#21552 fix: AnalyzeExecPlan bug which cause sysbench10w update panic
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/analyze_module_test.go
  pkg/sql/compile/compile2.go
Labels: size/M

#21580 fix row count
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/XS, Review effort 2/5

#21581 Fix get snapshot "file not found" error
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, Review effort 3/5

#21441 Unify the snapshot read and latest read-1
  pkg/frontend/test/engine_mock.go
  pkg/pb/statsinfo/statsinfo.pb.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/types.go
  proto/statsinfo.proto
Labels: kind/feature, size/XL

#21582 optimize apply uncommitted tombstones
  pkg/vm/engine/disttae/local_disttae_datasource.go
Labels: size/XS, kind/enhancement, Review effort 1/5

#21584 [improvement] logservice: add some logs in truncation of logservice.
  pkg/logservice/truncation.go
Labels: size/S, kind/enhancement, Review effort 1/5

#21583 [improvement] logservice: add some logs in truncation of logservice.
  pkg/logservice/truncation.go
Labels: size/S, kind/enhancement, Review effort 1/5

#21579 fix change handle
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/XS, Review effort 2/5

#21590 add wasm support for merge mo-ctl 2.1
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/filterStats.wasm
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/wasm.go
  pkg/vm/engine/tae/rpc/wasm_test.go
Labels: size/M, kind/enhancement, Review effort 3/5

#21586 add wasm support for merge mo-ctl
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/filterStats.wasm
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/wasm.go
  pkg/vm/engine/tae/rpc/wasm_test.go
Labels: size/M, kind/enhancement, Review effort 3/5

#21575 remove tpcc debug log
  pkg/vm/engine/tae/rpc/handle.go
Labels: size/XS, kind/enhancement, Review effort 1/5

#21593 [opt] merge multiple filters on primary key
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S, Review effort 2/5

#21594 [opt] merge multiple filters on primary key
  pkg/sql/plan/utils.go
Labels: kind/bug, size/S, Review effort 2/5

#21597 Fix workspace delete - main
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S, Review effort 2/5

#21596 Fix workspace delete bug
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  test/distributed/cases/dml/delete/delete.result
  test/distributed/cases/dml/delete/delete.test
Labels: kind/bug, size/S, Review effort 2/5

#21540 Fix cdc mo to mo invalid connection
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/M

#21600 fix an invalid memory access
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS, Review effort 2/5

#21601 fix an invalid memory access
  pkg/sql/plan/utils.go
Labels: kind/bug, size/XS, Review effort 2/5

#21595 to 2.1: merge small insert/delete bat to full batch in workspace.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/readutil/filter_util.go
  pkg/vm/engine/tae/rpc/handle.go
  test/distributed/cases/dml/update/update_workspace.result
  test/distributed/cases/dml/update/update_workspace.sql
Labels: size/M, Review effort 3/5

#21604 fix wasm dir to avoid grep check
  pkg/vm/engine/tae/rpc/wasm_test.go
  test/distributed/resources/plugin/filterStats.wasm
Labels: size/XS, kind/test-ci, Review effort 1/5

#21605 fix wasm dir to avoid grep check 2.1
  pkg/vm/engine/tae/rpc/wasm_test.go
  test/distributed/resources/plugin/filterStats.wasm
Labels: size/XS, kind/test-ci, Review effort 1/5

#21607 update fatal print with more context
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/database.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
Labels: size/M, kind/refactor, Review effort 2/5

#21610 Fix collectObjects for updateTableInfo
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, Review effort 2/5

#21612 Fix collectObjects for updateTableInfo
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: size/S, Review effort 2/5

#21614 update checkpoint cluster column
  pkg/vm/engine/ckputil/sinker.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/ckputil/types.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
Labels: kind/bug, size/S, Review effort 2/5

#21544 fix data race
  pkg/vm/engine/tae/tables/aobj.go
Labels: kind/bug, size/S

#21576 vector array remove unncessary cast from []float32 to []float64.
  pkg/frontend/variables.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/productl2/types.go
  pkg/sql/colexec/table_function/ivf_create.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer_test.go
  pkg/vectorindex/ivfflat/kmeans/types.go
  pkg/vectorindex/ivfflat/search.go
  pkg/vectorindex/metric/distance_func.go
  pkg/vectorindex/metric/distance_func_bench_test.go
  pkg/vectorindex/metric/distance_func_test.go
  pkg/vectorindex/metric/types.go
  pkg/vectorindex/types.go
  pkg/vectorize/moarray/external.go
  pkg/vectorize/moarray/external_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/vector/vector_func.result
  test/distributed/cases/vector/vector_func.sql
  test/distributed/cases/vector/vector_type.result
Labels: size/XL, kind/enhancement, Review effort 4/5

#21613 update ckp cluster column
  pkg/vm/engine/ckputil/sinker.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/ckputil/types.go
  pkg/vm/engine/tae/logtail/backup.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
Labels: kind/bug, size/S, Review effort 2/5

#21618 escape char in string col
  pkg/cdc/util.go
Labels: kind/bug, size/XS, Review effort 2/5

#21625 Fix cdc issues main
  pkg/cdc/util.go
  pkg/cdc/util_test.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S, Review effort 2/5

#21624 Fix cdc with blob|binary|varbinary
  pkg/cdc/util.go
  pkg/cdc/util_test.go
  pkg/sql/compile/sql_executor.go
Labels: kind/bug, size/S, Review effort 2/5

#21587 merge small insert/delete bat to full batch in workspace.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/readutil/filter_util.go
  pkg/vm/engine/tae/rpc/handle.go
  test/distributed/cases/dml/update/update_workspace.result
  test/distributed/cases/dml/update/update_workspace.sql
Labels: size/M, Review effort 3/5

#21628 Fix the bug of enum.Formt missing value
  pkg/sql/parsers/tree/types.go
Labels: kind/bug, size/S, Review effort 1/5

#21629 Fix the bug of enum.Formt missing value
  pkg/sql/parsers/tree/types.go
Labels: kind/bug, size/S, Review effort 1/5

#21630 Fix cdc ddl error
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/view/view.result
Labels: kind/bug, size/XS, Review effort 1/5

#21631 Fix cdc ddl error
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/table/create_table.result
  test/distributed/cases/view/view.result
Labels: kind/bug, size/XS, Review effort 1/5
