Repository matrixorigin/matrixone, pull requests merged in 2025-05, with the labels that each got.

#21789 Revert "Add Fast GC (#21325)"
  pkg/objectio/ioutil/codec.go
  pkg/objectio/ioutil/const.go
  pkg/objectio/ioutil/types.go
  pkg/sql/plan/function/ctl/cmd_disk_cleaner.go
  pkg/txn/client/client.go
  pkg/vm/engine/cmd_util/type.go
  pkg/vm/engine/tae/db/gc/v3/base.go
  pkg/vm/engine/tae/db/gc/v3/base_test.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/executor.go
  pkg/vm/engine/tae/db/gc/v3/fast.go
  pkg/vm/engine/tae/db/gc/v3/filter_test.go
  pkg/vm/engine/tae/db/gc/v3/gc_test.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/mock_cleaner.go
  pkg/vm/engine/tae/db/gc/v3/mock_test.go
  pkg/vm/engine/tae/db/gc/v3/object.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  test/distributed/cases/dml/checkpoint/checkpoint.result
  test/distributed/cases/dml/checkpoint/checkpoint.test
Labels: kind/bug, size/XXL

#21772 fix block_max_row is defined and used inconsistently across multiple files
  pkg/catalog/types.go
  pkg/container/batch/compact_batchs.go
  pkg/container/batch/compact_batchs_test.go
  pkg/objectio/bitmap.go
  pkg/objectio/s3_input_est.go
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/shuffle/shufflepool.go
  pkg/sql/colexec/shuffleV2/shufflepool.go
  pkg/sql/colexec/types.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/pushdown.go
  pkg/sql/plan/stats.go
  pkg/sql/util/index_util.go
  pkg/util/export/etl/tae.go
  pkg/util/export/etl/tae_test.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/process/process.go
Labels: size/M, kind/refactor

#21793 reduce goetty log output
  pkg/common/morpc/client.go
  pkg/common/morpc/server.go
Labels: size/XS, kind/enhancement

#21779 improve lock holders
  pkg/common/runtime/runtime.go
  pkg/lockservice/lock.go
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/lock_table_local_test.go
  pkg/lockservice/lock_table_proxy_test.go
  pkg/lockservice/lock_test.go
  pkg/lockservice/log.go
  pkg/lockservice/storage_test.go
  pkg/lockservice/types.go
  pkg/lockservice/waiter_events.go
Labels: size/M, kind/enhancement, Review effort 2/5

#21773 [#21676]Bug fix : performance degradation since commit id 6fbbd
  pkg/frontend/test/engine_mock.go
  pkg/pb/statsinfo/statsinfo.pb.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/types.go
  proto/statsinfo.proto
Labels: size/XL

#21797 [ci] remove bvt tag 14475
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: size/XS, kind/test-ci

#21794 BUG FIX: Fulltext skip overlap from N-gram output
  pkg/fulltext/fulltext.go
  pkg/fulltext/fulltext_test.go
  pkg/fulltext/sql.go
  pkg/fulltext/sql_test.go
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
  test/distributed/cases/fulltext/fulltext2.result
  test/distributed/cases/fulltext/fulltext_bm25.result
Labels: kind/bug, size/M

#21315 Remove txn reader from logtail
  pkg/common/moerr/error.go
  pkg/container/types/txnts.go
  pkg/util/fault/fault.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/catalog/basemvccnode.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/handle.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/logtail/operator.go
  pkg/vm/engine/tae/model/tree.go
  pkg/vm/engine/tae/model/tree_test.go
  pkg/vm/engine/tae/txn/txnbase/mvccnode.go
  pkg/vm/engine/test/disttae_engine_test.go
  test/distributed/cases/function/func_aggr_bitwise.result
  test/distributed/cases/function/func_aggr_bitwise.test
  test/distributed/cases/function/func_aggr_median.result
  test/distributed/cases/function/func_aggr_median.test
Labels: kind/bug, size/L, kind/refactor, kind/enhancement

#21801 Fix `duplicate entry` in ` replace into` caused by the `FastApplyDeletesByRowIds`.
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/objectio/injects.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/readutil/datasource.go
  pkg/vm/engine/readutil/datasource_test.go
  pkg/vm/engine/readutil/tombstone_data.go
  pkg/vm/engine/readutil/tombstone_data_test.go
Labels: kind/bug, size/M

#21805 [Subtask]: 对象分配优化：fileservice.newEventLogger #21394
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/XS

#21808 Revert "[Subtask]: 对象分配优化：fileservice.newEventLogger #21394 (#21805)"
  pkg/fileservice/s3_fs.go
Labels: kind/bug, size/XS

#21802 [ci] remove bvt tags
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
  test/distributed/cases/dtype/TimeToInt.sql
  test/distributed/cases/dtype/datetime.result
  test/distributed/cases/dtype/datetime.test
  test/distributed/cases/expression/temporal_interval.sql
Labels: size/S, kind/test-ci

#21653 s3fifo add ghost fifo
  cmd/mo-service/config.go
  pkg/embed/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/fifocache/bench2_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/ghost.go
  pkg/fileservice/fifocache/queue.go
  pkg/fileservice/fifocache/shardmap.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
Labels: size/L, kind/enhancement, Review effort 2/5

#21817 Fix make clean
  cgo/Makefile
  cgo/lib.go
  cgo/test/test_add.c
Labels: kind/bug, size/S, Review effort 1/5

#21815 s3fifo add ghost fifo for 2.1-dev
  cmd/mo-service/config.go
  pkg/embed/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/fifocache/bench2_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/ghost.go
  pkg/fileservice/fifocache/queue.go
  pkg/fileservice/fifocache/shardmap.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
Labels: kind/bug, size/L

#21827 [Refactoring]: Add comment on functions like buildFulltextIndexTable
  pkg/sql/plan/build_ddl.go
Labels: size/S, kind/refactor

#21816 ivf code port to 2.1-dev
  pkg/frontend/variables.go
  pkg/sql/colexec/productl2/product_l2.go
  pkg/sql/colexec/productl2/types.go
  pkg/sql/colexec/table_function/ivf_create.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/plan/function/func_binary_test.go
  pkg/sql/plan/function/func_unary_test.go
  pkg/vectorindex/hnsw/build_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer_bench_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer_test.go
  pkg/vectorindex/ivfflat/kmeans/types.go
  pkg/vectorindex/ivfflat/search.go
  pkg/vectorindex/metric/distance_func.go
  pkg/vectorindex/metric/distance_func_bench_test.go
  pkg/vectorindex/metric/distance_func_test.go
  pkg/vectorindex/metric/types.go
  pkg/vectorindex/types.go
  pkg/vectorize/moarray/external.go
  pkg/vectorize/moarray/external_test.go
  test/distributed/cases/array/array.result
  test/distributed/cases/vector/vector_func.result
  test/distributed/cases/vector/vector_func.sql
  test/distributed/cases/vector/vector_index.result
  test/distributed/cases/vector/vector_index.sql
  test/distributed/cases/vector/vector_type.result
Labels: kind/bug, size/XXL

#21831 fix TestAppend2
  pkg/vm/engine/tae/catalog/table_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/testutils/config/options_test.go
Labels: kind/bug, size/M

#21833 fix concurrent map read and map write
  pkg/lockservice/lock_table_allocator.go
Labels: size/XS

#21820 Remove some fileds to simplify dirty tree
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/tables_test.go
  pkg/vm/engine/tae/iface/txnif/memo.go
  pkg/vm/engine/tae/logtail/collector.go
  pkg/vm/engine/tae/logtail/reader.go
  pkg/vm/engine/tae/model/tree.go
  pkg/vm/engine/tae/model/tree_test.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/tables/table_scan.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/M, kind/enhancement

#21832 fix concurrent map read and map write
  pkg/lockservice/lock_table_allocator.go
Labels: size/XS

#21829 Remove GC's panic(), use Warn log instead: GC-PANIC
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/M

#21844 BUG FIX: Fulltext skip overlap from N-gram output 2.1-dev (#21799)
  pkg/fulltext/fulltext.go
  pkg/fulltext/fulltext_test.go
  pkg/fulltext/sql.go
  pkg/fulltext/sql_test.go
  test/distributed/cases/ddl/table_kind.result
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
  test/distributed/cases/fulltext/fulltext2.result
  test/distributed/cases/fulltext/fulltext_bm25.result
Labels: kind/bug

#21843 Remove GC's panic(), use Warn log instead: GC-PANIC
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug

#21842 Add LoadColumnsData error log
  pkg/objectio/constructors.go
  pkg/objectio/ioutil/loadfuncs.go
Labels: kind/bug, size/S

#21846 fix the cdc duplicated entry issue caused by in-memory transfer tombstones.
  pkg/container/types/rowid.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/readutil/datasource.go
  pkg/vm/engine/readutil/datasource_test.go
Labels: size/M

#21822 disable enum column in pk/index
  pkg/sql/plan/build_ddl.go
  test/distributed/cases/dtype/enum.result
  test/distributed/cases/dtype/enum.sql
Labels: kind/bug, size/S

#21492 Hdfs
  pkg/datalink/datalink.go
  pkg/datalink/datalink_test.go
  pkg/stage/stage.go
  pkg/stage/stage_test.go
Labels: size/S, kind/enhancement

#21841 CI: upgrade go version to 1.24.3
  .golangci.yml
  Makefile
  go.mod
  optools/bvt_ut/Dockerfile
  optools/compose_bvt/Dockerfile.tester
  optools/images/Dockerfile
  optools/images/Dockerfile.tke
  optools/run_ut.sh
  pkg/cdc/util.go
  pkg/proxy/event.go
  pkg/sql/parsers/goyacc/goyacc.go
  pkg/vm/engine/test/testutil/util.go
Labels: kind/feature, size/M

#21861 fix TestLockWithBindIsStale, TestIterLocks
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_remote_test.go
Labels: size/S

#21860 fix TestLockWithBindIsStale, TestIterLocks
  pkg/lockservice/service_observability_test.go
  pkg/lockservice/service_remote_test.go
Labels: size/S

#21859 fix data race in moerr & merge scheduler
  pkg/common/moerr/error.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/scheduler.go
Labels: kind/bug, size/S

#21800 Feature: metadata_scan supports checking the metadata of index table now
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/colexec/table_function/metadata_scan_test.go
  test/distributed/cases/function/table_func_metadata_scan_idx.result
  test/distributed/cases/function/table_func_metadata_scan_idx.sql
Labels: kind/feature, size/M

#21854 Revert "s3fifo add ghost fifo (#21653)" main branch
  cmd/mo-service/config.go
  pkg/embed/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/fifocache/bench2_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/ghost.go
  pkg/fileservice/fifocache/queue.go
  pkg/fileservice/fifocache/shardmap.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
Labels: kind/bug, size/L

#21871 fix data race 2.2
  pkg/common/moerr/error.go
  pkg/vm/engine/tae/db/merge/executor.go
  pkg/vm/engine/tae/db/scheduler.go
Labels: kind/bug, size/S

#21865 for_debug
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S

#21873 fix Test_Replayer11
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
Labels: kind/bug, size/S

#21875 for_debug_21865_2.2
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#21868 Bug fix: fix the panic
  pkg/container/types/binary.go
  pkg/sql/plan/function/agg/bit_and.go
  pkg/sql/plan/function/agg/bit_and_test.go
  test/distributed/cases/function/func_aggr_bitwise.result
Labels: kind/bug, size/M

#21876 Pick revert s3fifo to 2.2-dev
  cmd/mo-service/config.go
  pkg/embed/config.go
  pkg/fileservice/cache.go
  pkg/fileservice/cache_test.go
  pkg/fileservice/disk_cache.go
  pkg/fileservice/disk_cache_test.go
  pkg/fileservice/fifocache/bench2_test.go
  pkg/fileservice/fifocache/bench_test.go
  pkg/fileservice/fifocache/data_cache.go
  pkg/fileservice/fifocache/data_cache_test.go
  pkg/fileservice/fifocache/fifo.go
  pkg/fileservice/fifocache/fifo_test.go
  pkg/fileservice/fifocache/ghost.go
  pkg/fileservice/fifocache/queue.go
  pkg/fileservice/fifocache/shardmap.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
  pkg/fileservice/mem_cache.go
  pkg/fileservice/mem_cache_test.go
  pkg/fileservice/memory_fs_test.go
  pkg/fileservice/s3_fs.go
  pkg/objectio/cache.go
Labels: kind/bug, size/L

#21828 some code cleanup
  pkg/frontend/session_test.go
  pkg/frontend/test/engine_mock.go
  pkg/objectio/ioutil/reader.go
  pkg/objectio/reader.go
  pkg/util/test/cron_task_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_delegate.go
  pkg/vm/engine/disttae/txn_table_partition.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/readutil/expr_filter.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/tae/containers/utils.go
  pkg/vm/engine/tae/containers/utils_test.go
  pkg/vm/engine/types.go
Labels: size/M

#21878 modify case(main)
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S, Review effort 1/5

#21872 For 2.2-dev : metadata_scan supports checking the metadata of index table
  pkg/sql/colexec/table_function/metadata_scan.go
  pkg/sql/colexec/table_function/metadata_scan_test.go
  test/distributed/cases/function/table_func_metadata_scan_idx.result
  test/distributed/cases/function/table_func_metadata_scan_idx.sql
Labels: kind/feature, size/M

#21881 add 2.2-dev to mergify
  .github/mergify.yml
Labels: size/XS, kind/test-ci, Review effort 1/5

#21877 fix join order for DML plan
  pkg/sql/plan/join_order.go
Labels: kind/bug, size/S

#21879 add case(2.2-dev)
  test/distributed/cases/ddl/create_table_as_select.result
  test/distributed/cases/ddl/create_table_as_select.sql
Labels: kind/bug, size/S, Review effort 1/5

#21890 fix join order for DML plan
  pkg/sql/plan/join_order.go
Labels: kind/bug, size/S

#21883 remove stale compatibility code
  pkg/objectio/CHANGELOG.md
  pkg/vm/engine/tae/catalog/command.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/tables/updates/cmd.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/appendcmd.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
Labels: size/M, kind/refactor

#21858 enable EXPLAIN to show analyze info for background SQLs
  pkg/pb/plan/plan.pb.go
  pkg/sql/colexec/table_function/fulltext.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/plan/explain/explain_query.go
  pkg/util/executor/types.go
  proto/plan.proto
Labels: kind/feature, size/S

#21811 fileservice: make DiskCacheCallbacks a context.Context to eliminate usages of context.WithValue
  pkg/fileservice/disk_cache_callbacks.go
  pkg/fileservice/disk_cache_test.go
Labels: size/S, kind/enhancement

#21895 fix bug: execute using @var which value is null
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
  test/distributed/cases/dtype/decimal.result
  test/distributed/cases/dtype/decimal.test
  test/distributed/cases/dtype/numeric.result
  test/distributed/cases/dtype/numeric.sql
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
  test/distributed/cases/prepare/prepare_all.result
Labels: kind/bug, size/M

#21889 introduce err2 as local variable to prevent race
  pkg/vectorindex/ivfflat/search.go
  pkg/vectorindex/ivfflat/search_test.go
Labels: kind/bug, size/S

#21898 force SINK_SCAN to run on single CN
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/XS

#21901 fix bug: execute using @var which value is null (#21895)
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/session.go
  pkg/frontend/variables.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
  test/distributed/cases/dtype/decimal.result
  test/distributed/cases/dtype/decimal.test
  test/distributed/cases/dtype/numeric.result
  test/distributed/cases/dtype/numeric.sql
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
  test/distributed/cases/prepare/prepare_all.result
Labels: kind/bug, size/M

#21902 persist merge settings 2.2
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_2_0/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_2_0/log.go
  pkg/bootstrap/versions/v2_2_0/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_2_0/upgrade.go
  pkg/bootstrap/versions/v2_2_0/upgrade_test.go
  pkg/catalog/types.go
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate2.go
  pkg/frontend/predefined.go
  pkg/pb/api/api.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/util.go
  pkg/sql/plan/function/func_mo.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/metrics.go
  pkg/util/metric/v2/task.go
  pkg/vm/engine/tae/catalog/tableForMerge.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/merge/settings.go
  pkg/vm/engine/tae/db/merge/statVacuum.go
  pkg/vm/engine/tae/db/merge/utils_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/mergesort/task.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/inspectMerge.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/table_scan.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
  test/distributed/cases/disttae/mo_table_stats/mo_table_stats3.result
  test/distributed/cases/dml/select/sp_table.result
  test/distributed/cases/dml/show/database_statistics.result
  test/distributed/cases/dml/show/show.result
  test/distributed/cases/metadata/information_schema.result
  test/distributed/cases/snapshot/cluster/restore_cluster_table.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_cluster.result
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/tenant.result
Labels: kind/feature, size/XL

#21906 colexec/external: ensure symlink is valid in TestReadDirSymlink
  pkg/sql/colexec/external/external_test.go
Labels: kind/bug, size/S

#21905 fix the duplicate entry in the CDC test.
  pkg/objectio/mergeutil/tyeps_test.go
  pkg/objectio/mergeutil/types.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/M

#21904 force SINK_SCAN to run on single CN
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/XS

#21896 Fix: not throw panic "not supported: median in distinct mode:"
  pkg/container/batch/batch_test.go
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/register.go
  pkg/sql/colexec/aggexec/serialize.go
  pkg/sql/colexec/aggexec/types.go
  pkg/sql/colexec/group/exec.go
  pkg/sql/colexec/group/exec_test.go
  pkg/sql/colexec/group/execctx.go
  pkg/sql/colexec/group/execctx_test.go
  pkg/sql/colexec/mergegroup/exec.go
  pkg/sql/colexec/mergegroup/exec_test.go
  pkg/sql/colexec/timewin/timewin.go
  pkg/sql/colexec/timewin/timewin_test.go
  pkg/sql/colexec/window/window.go
  pkg/sql/compile/remoterun_test.go
  test/distributed/cases/function/func_aggr_median.result
  test/distributed/cases/time_window/time_window.result
  test/distributed/cases/time_window/time_window.sql
Labels: kind/bug, size/M

#21919 fix 21911
  pkg/container/batch/batch.go
  pkg/objectio/block_info.go
  pkg/objectio/id.go
  pkg/objectio/object_stats.go
  pkg/objectio/utils.go
Labels: kind/bug, size/S

#21921 fix 21911
  pkg/container/batch/batch.go
  pkg/objectio/block_info.go
  pkg/objectio/id.go
  pkg/objectio/object_stats.go
  pkg/objectio/utils.go
Labels: kind/bug, size/S

#21925 Fix version bug of cpt file 2.2
  pkg/vm/engine/tae/db/gc/v3/merge.go
Labels: kind/bug, size/XS

#21926 Fix version bug of cpt file main
  pkg/vm/engine/tae/db/gc/v3/merge.go
Labels: kind/bug, size/XS

#21924 Fix version bug of cpt file
  pkg/vm/engine/tae/db/gc/v3/merge.go
Labels: kind/bug, size/XS

#21928 Fix bug: get error result in binary execute with nil
  pkg/container/vector/vector.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S

#21930 to 2.2: fix tombstone object missing after the CN transfer
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/transfer_util.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#21929 fix tombstone objects missing after the CN transfer
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/transfer_util.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/S

#21918 fix tombstone vacuum check
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/rpc/inspectMerge.go
Labels: kind/bug, size/M, kind/enhancement

#21936 Fix 5252 to 2.2-dev
  pkg/container/vector/vector.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S

#21935 CI: modify dockerfile
  optools/images/Dockerfile
  optools/images/README.md
Labels: size/S, kind/test-ci
