Repository matrixorigin/matrixone, pull requests merged in 2025-02, with the labels that each got.

#21348 wal replay related changes
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/commit.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/faker.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replayer.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/wal/checkpoint.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: size/L, kind/refactor, kind/enhancement

#21298 fileservice: return AWS region detection error in ObjectStorageArgume…
  pkg/fileservice/object_storage_arguments.go
  pkg/fileservice/object_storage_arguments_test.go
Labels: size/S, kind/enhancement

#21354 add ut and fix logs
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/S, kind/enhancement

#21345 if delete can't rewrite to truncate table, use bind_delete make new plan
  pkg/sql/plan/bind_delete.go
  pkg/sql/plan/build.go
  pkg/sql/plan/build_test.go
Labels: size/S

#21353 add ut and fix logs
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
Labels: size/S, kind/enhancement

#21351 fix check pitr
  pkg/cdc/types.go
  pkg/frontend/cdc.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/S

#21360 fix bug: panic when drop table
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/XS

#21362 [improvement] logservice: replayed lsn check for log truncation.
  pkg/common/moerr/cause.go
  pkg/logservice/truncation.go
  pkg/logservice/truncation_test.go
  pkg/pb/logservice/logservice.go
  pkg/pb/logservice/logservice.pb.go
  pkg/tnservice/store_heartbeat.go
  proto/logservice.proto
Labels: size/M, kind/enhancement

#21326 refactor checkpoint
  pkg/vm/engine/ckputil/data.go
  pkg/vm/engine/ckputil/meta.go
  pkg/vm/engine/ckputil/reader_test.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/ckputil/types.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/ckp_data.go
  pkg/vm/engine/tae/logtail/types.go
  pkg/vm/engine/test/partition_state_test.go
Labels: size/XL, kind/refactor

#21357 fix bug: panic when drop table
  pkg/sql/compile/ddl.go
Labels: kind/bug, size/XS

#21347 handle ON UPDATE expr in column definition
  pkg/sql/plan/bind_update.go
Labels: kind/feature, size/S

#21363 replay related refactor
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/batchstore_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/store.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/driver_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/info.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replayer.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/truncate.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logtail/mgr.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/txn/txnbase/heartbeat_store.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/txn.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: size/M, kind/refactor, kind/enhancement

#21366 fix: doLock panic
  pkg/sql/compile/lock_meta.go
Labels: kind/bug, size/XS

#21367 refactor: use relation reset interface for reusing relation
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/S, kind/enhancement

#20996 checking tcp connection status
  pkg/config/configuration.go
  pkg/frontend/server.go
  pkg/frontend/tcpconn/linux.go
  pkg/frontend/tcpconn/macos.go
Labels: size/M, kind/enhancement, Review effort [1-5]: 4

#21359 chore: fix mologger reconnect mo
  pkg/util/export/etl/content.go
  pkg/util/export/etl/content_test.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/etl/sql_test.go
  pkg/util/metric/v2/trace.go
Labels: kind/bug, size/M

#21373 some code refactor
  pkg/objectio/fs.go
  pkg/objectio/writer_test.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/checkpoint/testutils.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/deleter.go
  pkg/vm/engine/tae/db/merge/scheduler.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/index/indexwrapper/immutindex.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/tool.go
  pkg/vm/engine/tae/rpc/utils.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/jobs/flushobj.go
  pkg/vm/engine/tae/tables/jobs/mergeobjects.go
  pkg/vm/engine/tae/tables/pnode.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail_test.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/tables/utils.go
  pkg/vm/engine/tae/txn/txnimpl/base_table.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/wal/types.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/testutil/util.go
Labels: size/M, kind/refactor

#21365 refactor: general_series parallel
  pkg/sql/colexec/table_function/generate_series.go
  pkg/sql/colexec/table_function/table_function.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/sql/plan/stats.go
Labels: size/M, kind/enhancement

#21375 change threshold of realloc
  pkg/common/mpool/mpool.go
Labels: kind/bug, size/XS

#21376 change threshold of realloc
  pkg/common/mpool/mpool.go
Labels: kind/bug, size/XS

#21380 code cleanup
  pkg/datasync/entry_test.go
  pkg/vm/engine/tae/catalog/catalog.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/types.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/dbutils/error.go
  pkg/vm/engine/tae/db/merge/cnScheduler_test.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/scheduler_test.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/storage_usage_test.go
  pkg/vm/engine/tae/logtail/ckp_data.go
  pkg/vm/engine/tae/logtail/utils.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/tables/object_test.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
  pkg/vm/engine/tae/wal/driver.go
Labels: size/M, kind/refactor

#21381 refactor: insert/deletion op using relation reset interface
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
Labels: size/M, kind/enhancement

#21382 code cleanup 2
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/checkpoint/flusher_test.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: size/M, kind/refactor

#21386 add txn status check
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/S, kind/enhancement

#21374 chore: fix mologger reconnect mo in 2.0
  pkg/util/export/etl/content.go
  pkg/util/export/etl/content_test.go
  pkg/util/export/etl/db/db_holder.go
  pkg/util/export/etl/db/db_holder_test.go
  pkg/util/export/etl/sql_test.go
  pkg/util/metric/v2/trace.go
Labels: kind/bug, size/M

#21385 add txn status check 2.0
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/test/disttae_engine_test.go
Labels: size/S, kind/enhancement

#21371 fix oom
  pkg/vm/engine/tae/mergesort/merger.go
Labels: kind/bug, size/XS

#21398 fix bug : incorrect lock index
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS

#21332 malloc: refactor mmap allocator
  pkg/common/malloc/config.go
  pkg/common/malloc/fixed_size_mmap_allocator.go
  pkg/common/malloc/fixed_size_mmap_allocator_test.go
  pkg/common/malloc/mmap_darwin.go
  pkg/common/malloc/mmap_linux.go
Labels: size/M, kind/enhancement

#21379 refactor: compileTableScanDataSource relation reset
  pkg/sql/compile/compile.go
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/txn_table.go
Labels: size/S, kind/enhancement

#21400 refactor for read-write tn migration
  pkg/objectio/injects.go
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/checkpoint/flusher_test.go
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/cronjobs.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/storage_usage_test.go
  pkg/vm/engine/tae/logtail/storage_usage.go
  pkg/vm/engine/tae/txn/txnbase/command.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
Labels: size/L, kind/refactor

#21402 change threshold of realloc
  pkg/common/mpool/mpool.go
Labels: kind/bug, size/XS

#21406 Revert "malloc: refactor mmap allocator (#21332)"
  pkg/common/malloc/config.go
  pkg/common/malloc/fixed_size_mmap_allocator.go
  pkg/common/malloc/fixed_size_mmap_allocator_test.go
  pkg/common/malloc/mmap_darwin.go
  pkg/common/malloc/mmap_linux.go
Labels: size/M, kind/enhancement

#21408 for read-write tn migration 2
  pkg/vm/engine/tae/db/controller.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/faker.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/options.go
  pkg/vm/engine/tae/logstore/driver/logservicedriver/replay_test.go
  pkg/vm/engine/tae/logstore/store/replay.go
Labels: size/M, kind/refactor, kind/test-ci

#21370 fix oom
  pkg/vm/engine/tae/mergesort/merger.go
Labels: kind/bug, size/XS

#21413 read-write tn migration 3
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/logstore/driver/batchstoredriver/type.go
  pkg/vm/engine/tae/logstore/driver/type.go
  pkg/vm/engine/tae/logstore/entry/base.go
  pkg/vm/engine/tae/logstore/store/checkpoint.go
  pkg/vm/engine/tae/logstore/store/checkpointinfo.go
  pkg/vm/engine/tae/logstore/store/partialckp.go
  pkg/vm/engine/tae/logstore/store/replay.go
  pkg/vm/engine/tae/logstore/store/store.go
  pkg/vm/engine/tae/logstore/store/store_test.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logstore/store/walinfo.go
  pkg/vm/engine/tae/wal/driver.go
  pkg/vm/engine/tae/wal/types.go
Labels: size/XL, kind/refactor, kind/enhancement

#21420 tn migration 4
  pkg/datasync/entry.go
  pkg/datasync/entry_test.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/runner.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logstore/store/type.go
  pkg/vm/engine/tae/logstore/wal/checkpoint.go
  pkg/vm/engine/tae/logstore/wal/replay.go
  pkg/vm/engine/tae/logstore/wal/store.go
  pkg/vm/engine/tae/logstore/wal/store_test.go
  pkg/vm/engine/tae/logstore/wal/type.go
  pkg/vm/engine/tae/logstore/wal/walinfo.go
  pkg/vm/engine/tae/txn/txnimpl/cmdmgr.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/txn_test.go
  pkg/vm/engine/tae/wal/driver.go
Labels: size/M, kind/refactor

#21426 tn migration 5
  pkg/cnservice/types.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/testutils/config/options.go
Labels: size/S, kind/refactor

#21427 Reduce the frequent calls to the String() method of objectName
  pkg/objectio/cache.go
Labels: size/XS, kind/enhancement

#21434 update code owners
  CODEOWNERS
Labels: kind/documentation, size/S

#21396 vector: always check types in *NoTypeCheck functions if race tag is set
  pkg/container/vector/functionTool_test.go
  pkg/container/vector/type_check_no_race.go
  pkg/container/vector/type_check_race.go
  pkg/container/vector/utils.go
  pkg/container/vector/vector.go
  pkg/sql/colexec/multi_update/insert_test.go
  pkg/sql/colexec/table_function/fulltext_test.go
  pkg/sql/colexec/table_function/fulltext_tokenize_test.go
Labels: size/S, kind/enhancement

#21429 Reduce the frequent calls to the String() method of objectName
  pkg/objectio/cache.go
Labels: size/XS, kind/enhancement

#21433 tn migration 6
  pkg/common/moerr/error.go
  pkg/common/moerr/error_no_ctx.go
  pkg/vm/engine/tae/catalog/mock.go
  pkg/vm/engine/tae/db/replay.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/iface/txnif/types.go
  pkg/vm/engine/tae/logstore/wal/replay.go
  pkg/vm/engine/tae/logstore/wal/walinfo.go
  pkg/vm/engine/tae/txn/txnbase/heartbeat_store.go
  pkg/vm/engine/tae/txn/txnbase/store.go
  pkg/vm/engine/tae/txn/txnbase/txn.go
  pkg/vm/engine/tae/txn/txnbase/txnmgr.go
  pkg/vm/engine/tae/txn/txnimpl/replaystore.go
  pkg/vm/engine/tae/txn/txnimpl/store.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
  pkg/vm/engine/tae/txn/txnimpl/txndb.go
Labels: size/M, kind/refactor

#21428 When prepared statement notice a schema change, it should automagical…
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/types.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/feature, size/M

#21431 add flush in send prepare response && fix table_constraints
  pkg/bootstrap/versions/v2_0_2/cluster_upgrade_list.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/util/sysview/predefined.go
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/table/system_table_cases.sql
Labels: kind/bug, size/XXL

#21432 When prepared statement notice a schema change, it should automagical…
  pkg/frontend/compiler_context.go
  pkg/frontend/computation_wrapper.go
  pkg/frontend/types.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/feature, size/M

#21430 remove the partition state that is cached in the txn table.
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_delegate.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/readutil/relation_data.go
  pkg/vm/engine/readutil/relation_data_test.go
  pkg/vm/engine/test/reader_test.go
Labels: kind/bug, size/M

#21440 fix tpcc performance degradation
  pkg/config/configuration.go
  pkg/frontend/mysql_protocol_predefines.go
  pkg/frontend/server.go
  pkg/frontend/tcpconn/linux.go
  pkg/frontend/tcpconn/macos.go
Labels: kind/bug, size/M, Review effort 3/5

#21436 fix small object merge
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/db/merge/policyCompact.go
  pkg/vm/engine/tae/db/merge/policyGroup.go
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policyTombstone.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/merge/utils.go
  pkg/vm/engine/tae/mergesort/task.go
Labels: kind/bug, size/M

#21446 change upgrade version from 2.1.0 to 2.0.3
  pkg/bootstrap/upgrade.go
  pkg/bootstrap/versions/v2_0_3/cluster_upgrade_list.go
  pkg/bootstrap/versions/v2_0_3/log.go
  pkg/bootstrap/versions/v2_0_3/tenant_upgrade_list.go
  pkg/bootstrap/versions/v2_0_3/upgrade.go
  pkg/bootstrap/versions/v2_0_3/upgrade_test.go
Labels: size/S, kind/enhancement

#21425 Change rowid, blockid to use value.
  pkg/compare/compare_test.go
  pkg/container/types/rowid.go
  pkg/container/types/rowid_test.go
  pkg/container/types/types_test.go
  pkg/objectio/block_info_test.go
  pkg/objectio/ioutil/funcs.go
  pkg/objectio/ioutil/writer.go
  pkg/objectio/location.go
  pkg/objectio/utils.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/mock_util.go
  pkg/sql/colexec/multi_update/delete_test.go
  pkg/sql/colexec/multi_update/update_test.go
  pkg/sql/colexec/multi_update/util_for_test.go
  pkg/sql/colexec/onduplicatekey/on_duplicate_key_test.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/disttae/logtailreplay/partition_state_test.go
  pkg/vm/engine/disttae/logtailreplay/rows_iter_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/readutil/tombstone_data_test.go
  pkg/vm/engine/tae/catalog/catalog_test.go
  pkg/vm/engine/tae/catalog/object.go
  pkg/vm/engine/tae/catalog/table_test.go
  pkg/vm/engine/tae/compute/compare_test.go
  pkg/vm/engine/tae/db/checkpoint/runner_test.go
  pkg/vm/engine/tae/db/merge/policy_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/hidden_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/test/txn_test.go
  pkg/vm/engine/tae/index/filter_test.go
  pkg/vm/engine/tae/index/indexwrapper/mutindex.go
  pkg/vm/engine/tae/model/tree.go
  pkg/vm/engine/tae/model/tree_test.go
  pkg/vm/engine/tae/rpc/rpc_test.go
  pkg/vm/engine/tae/tables/base.go
  pkg/vm/engine/tae/tables/functions.go
  pkg/vm/engine/tae/tables/jobs/flushTableTail.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/object_test.go
  pkg/vm/engine/tae/tables/table_scan.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
  pkg/vm/engine/tae/tables/updates/command_test.go
  pkg/vm/engine/tae/tables/updates/mvcc_test.go
  pkg/vm/engine/tae/txn/txnimpl/anode.go
  pkg/vm/engine/tae/txn/txnimpl/command_test.go
  pkg/vm/engine/tae/txn/txnimpl/object.go
  pkg/vm/engine/tae/txn/txnimpl/relation.go
  pkg/vm/engine/tae/txn/txnimpl/table.go
  pkg/vm/engine/tae/txn/txnimpl/table_space.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/M

#21449 fix memory limitation
  pkg/vm/engine/tae/db/merge/policyOverlap.go
  pkg/vm/engine/tae/db/merge/policy_test.go
Labels: kind/bug, size/S

#21443 [Cherry-pick] add flush in send prepare response && fix table_constraints
  pkg/bootstrap/versions/v2_0_3/cluster_upgrade_list.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/mysql_protocol.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/util/sysview/predefined.go
  test/distributed/cases/mo_cloud/mo_cloud.result
  test/distributed/cases/table/system_table_cases.result
  test/distributed/cases/table/system_table_cases.sql
Labels: kind/bug, size/XXL

#21450 add Dockerfile for tke test env
  optools/images/Dockerfile.tke
Labels: kind/test-ci

#21455 cdc sink to mo rewrite sql
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
Labels: kind/bug, size/M

#21461 fix the merge schedule interval.
  pkg/vm/engine/tae/db/cronjobs.go
Labels: kind/bug, size/XS, kind/enhancement

#21454 bug fix arm64 build docker failed
  optools/images/Dockerfile
Labels: kind/bug, size/S

#21462 [opt] enable Top operator to run in multi-thread
  pkg/pb/pipeline/pipeline.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/compile2.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/scope.go
  pkg/sql/compile/types.go
  pkg/sql/plan/explain/explain_node.go
  pkg/sql/plan/message.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_delegate.go
  pkg/vm/message/message.go
  proto/pipeline.proto
  proto/plan.proto
Labels: size/S, kind/enhancement

#21465 minor improve for loop join
  pkg/sql/colexec/loopjoin/join.go
Labels: kind/bug, size/XS, kind/enhancement
