Repository matrixorigin/matrixone, pull requests merged in 2025-04, with the labels that each got.

#21634 fix bug: panic in replace statement
  pkg/sql/plan/bind_replace.go
  test/distributed/cases/replace_statement/replace_statement.result
  test/distributed/cases/replace_statement/replace_statement.sql
Labels: kind/bug, size/XS, Review effort 2/5

#21522 refactor cn s3 writer.
  pkg/objectio/utils.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/insert/insert_test.go
  pkg/sql/colexec/insert/types.go
  pkg/sql/colexec/mergeblock/types.go
  pkg/sql/colexec/multi_update/s3writer.go
  pkg/sql/colexec/multi_update/s3writer_util.go
  pkg/sql/colexec/multi_update/types.go
  pkg/sql/colexec/multi_update/util_for_test.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/sql/plan/utils.go
  pkg/vectorindex/hnsw/apple
  pkg/vectorindex/hnsw0.bin
  pkg/vectorindex/hnsw1.bin
  pkg/vm/engine/disttae/local_disttae_datasource_test.go
  pkg/vm/engine/disttae/merge.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/util.go
  pkg/vm/engine/disttae/util_test.go
  pkg/vm/engine/readutil/datasource_test.go
  pkg/vm/engine/readutil/tombstone_data_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/workspace_test.go
Labels: kind/bug, size/XL, kind/enhancement

#21615 Fix TestPitrMeta
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci, Review effort 1/5

#21633 fix bug: panic in replace statement
  pkg/sql/plan/bind_replace.go
  test/distributed/cases/replace_statement/replace_statement.result
  test/distributed/cases/replace_statement/replace_statement.sql
Labels: kind/bug, size/XS, Review effort 2/5

#21636 update CDC change handle
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: size/M, kind/enhancement, Review effort 3/5

#21642 better expr print for debug
  pkg/sql/plan/utils.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/tae/common/print.go
Labels: size/S, kind/refactor, Review effort 2/5

#21641 Add expr pretty print for debug
  pkg/sql/plan/utils.go
  pkg/vm/engine/ckputil/sinker_test.go
  pkg/vm/engine/tae/common/print.go
Labels: size/S, kind/refactor, Review effort 2/5

#21643 fix bug: prefix_in not sorted in prepare stmt
  pkg/sql/plan/function/func_prefix.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S, Review effort 2/5

#21644 fix bug: prefix_in not sorted in prepare stmt
  pkg/sql/plan/function/func_prefix.go
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/bug, size/S, Review effort 2/5

#21647 fix TestGlobalCheckpoint7
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S, Review effort 2/5

#21650 reduce goroutines used calculating stats
  pkg/vm/engine/disttae/stats.go
Labels: size/S, kind/enhancement

#21655 fix license
  go.mod
  go.sum
  pkg/common/arenaskl/LICENSE
  pkg/common/arenaskl/README.md
  pkg/common/arenaskl/arena.go
  pkg/common/arenaskl/arena_test.go
  pkg/common/arenaskl/iterator.go
  pkg/common/arenaskl/node.go
  pkg/common/arenaskl/skl.go
  pkg/common/arenaskl/skl_test.go
  pkg/common/fastrand/fastrand.go
  pkg/common/fastrand/fastrand_test.go
  pkg/sql/util/csvparser/csv_parser.go
  pkg/sql/util/csvparser/csv_parser_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_frontend.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_fs.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_logtail.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_mem.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_pipeline.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_proxy.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_rpc.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_runtime.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_sharding.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_task.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_test.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_trace.go
  pkg/util/metric/v2/dashboard/grafana_dashboard_txn.go
  pkg/vm/engine/tae/mergesort/heap.go
Labels: kind/bug, size/XXL, Review effort 1/5

#21661 fix bug: dot not upgrade BM25
  pkg/bootstrap/versions/v2_1_0/upgrade.go
  pkg/bootstrap/versions/v2_1_0/upgrade_test.go
Labels: kind/bug, size/S, Review effort 2/5

#21668 change the version of mo
  Makefile
  pkg/bootstrap/versions/v2_0_3/upgrade.go
Labels: size/XS, kind/enhancement, Review effort 1/5

#21665 update cdc sinker and changes handle
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/S

#21660 fix the object sort key index mismatch when CN flush objects.
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/multi_update/s3writer_util.go
  pkg/sql/colexec/s3util.go
Labels: kind/bug, size/M

#21675 fix checkpoint UT
  pkg/vm/engine/tae/db/checkpoint/gckp_exec.go
  pkg/vm/engine/tae/db/checkpoint/info.go
  pkg/vm/engine/tae/db/checkpoint/store.go
  pkg/vm/engine/tae/db/test/catalog_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/db/test/replay_test.go
  pkg/vm/engine/tae/db/testutil/engine.go
  pkg/vm/engine/tae/db/testutil/funcs.go
  pkg/vm/engine/tae/rpc/tool_test.go
Labels: kind/bug, size/M

#21681 to 2.1: filter out the deletes object when merging deletes in the workspace.
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/XS

#21639 merge small insert batch into full batch in the workspace.
  pkg/common/bitmap/bitmap.go
  pkg/common/bitmap/bitmap_test.go
  pkg/container/nulls/nulls.go
  pkg/objectio/bitmap.go
  pkg/objectio/bitmap_test.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/tae/blockio/read.go
Labels: size/S, kind/enhancement, Review effort 2/5

#21689 fix collect softdelete objects in TN in 2.1
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/table_test.go
Labels: kind/bug, size/S

#21688 fix collect softdelete objects in TN
  pkg/vm/engine/tae/catalog/table.go
  pkg/vm/engine/tae/catalog/table_test.go
Labels: kind/bug, size/S

#21693 fix abort mark active txn
  pkg/txn/client/client.go
Labels: size/S, Review effort 2/5

#21692 fix abort mark active txn
  pkg/txn/client/client.go
Labels: size/S, Review effort 2/5

#21694 fix CN OOM by S3Writer in big data test.
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/s3util.go
Labels: kind/bug, size/S

#21696 cherry pick fix abort mark active txn to 2.0.3 hotfix (#21693)
  pkg/txn/client/client.go
Labels: kind/bug, size/S

#21621 [Refactoring]: IVFFLAT better error handling
  pkg/sql/colexec/productl2/product_l2.go
  pkg/vectorindex/hnsw/apple
  pkg/vectorindex/hnsw0.bin
  pkg/vectorindex/hnsw1.bin
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer_bench_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/clusterer_test.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer.go
  pkg/vectorindex/ivfflat/kmeans/elkans/initializer_test.go
  pkg/vectorindex/ivfflat/kmeans/types.go
  pkg/vectorindex/ivfflat/search.go
  pkg/vectorindex/metric/distance_func.go
  pkg/vectorindex/metric/distance_func_bench_test.go
  pkg/vectorindex/metric/distance_func_test.go
  pkg/vectorindex/metric/types.go
  pkg/vectorize/moarray/external.go
Labels: size/L, kind/enhancement, Review effort 2/5

#21697 fix dynamic rpath error for darwin
  .gitignore
  Makefile
Labels: kind/bug, size/XS, Review effort 2/5

#21700 fix cdc panic
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
Labels: kind/bug, size/S

#21662 fileservice: delete temp files if write error
  pkg/fileservice/file_service_test.go
  pkg/fileservice/local_etl_fs.go
  pkg/fileservice/local_etl_fs_test.go
  pkg/fileservice/local_fs.go
  pkg/fileservice/local_fs_test.go
Labels: size/M, kind/enhancement, Review effort 1/5

#21705 fix mergeTxnWorkspaceLocked
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/XS

#21706 fix mergeTxnWorkspaceLocked
  pkg/vm/engine/disttae/txn.go
Labels: kind/bug, size/XS

#21703 add check local timeout txn
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
Labels: size/M, Review effort 2/5

#21712 fix bug: agg push down panic
  pkg/sql/plan/agg_pushdown_pullup.go
  test/distributed/cases/optimizer/pushdown.result
  test/distributed/cases/optimizer/pushdown.test
Labels: kind/bug, size/S

#21704 add check local timeout txn
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
Labels: size/M, Review effort 2/5

#21715 fix bug: agg push down panic
  pkg/sql/plan/agg_pushdown_pullup.go
  test/distributed/cases/optimizer/pushdown.result
  test/distributed/cases/optimizer/pushdown.test
Labels: kind/bug, size/S

#21707 BVT cases for the replace statements in the workspace.
  test/distributed/cases/dml/replace/replace_workspace.result
  test/distributed/cases/dml/replace/replace_workspace.sql
Labels: size/S, kind/test-ci

#21717 fix TestAppend2
  pkg/vm/engine/tae/catalog/table_test.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/testutils/config/options.go
  pkg/vm/engine/tae/testutils/config/options_test.go
Labels: kind/bug, size/M

#21720 fix ExportStats
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
Labels: kind/bug, size/S

#21709 fix bug: agg push down panic
  pkg/sql/plan/agg_pushdown_pullup.go
  test/distributed/cases/optimizer/pushdown.result
  test/distributed/cases/optimizer/pushdown.test
Labels: kind/bug, size/S

#21719 fix ExportStats
  pkg/vm/engine/tae/db/checkpoint/executor.go
  pkg/vm/engine/tae/db/checkpoint/ickp_exec.go
  pkg/vm/engine/tae/logtail/ckp_writer.go
Labels: kind/bug, size/S

#21723 Fix TestCkpLeak (#21572)
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci

#21724 add debug log
  pkg/objectio/injects.go
  pkg/vm/engine/tae/db/checkpoint/flusher.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/collector.go
Labels: kind/bug, size/S

#21727 fix the compaction of objects by deletion when merging the TXN workspace.
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/tae/blockio/read.go
  pkg/vm/engine/test/mo_table_stats_test.go
  test/distributed/cases/dml/delete/delete_workspace.result
  test/distributed/cases/dml/delete/delete_workspace.sql
Labels: kind/bug, size/M

#21635 Fix TestPitrMeta
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci, Review effort 1/5

#21731 fix merge alloc
  pkg/common/mpool/mpool.go
  pkg/vm/engine/tae/mergesort/merger.go
Labels: size/S

#21735 Fix data race in TestDoHeartbeatInvalidTask
  pkg/taskservice/task_runner_test.go
Labels: size/XS, Review effort 1/5

#21733 [opt] improve join order and enable runtime filter for fulltext UPDATE
  pkg/sql/plan/build_dml_util.go
Labels: size/S, kind/enhancement

#21741 Fix the block filter not work when `where sortKey = ''`.
  pkg/vm/engine/readutil/expr_util.go
Labels: size/S

#21745 add debug log
  pkg/vm/engine/tae/db/test/db_test.go
Labels: kind/bug, size/S

#21737 feat: alter user lock
  pkg/frontend/authenticate.go
  pkg/frontend/authenticate_test.go
  pkg/frontend/session.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.go
  pkg/sql/parsers/dialect/mysql/mysql_sql.y
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  test/distributed/cases/tenant/privilege/alter_user_password.result
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.result
  test/distributed/cases/zz_accesscontrol/password_management/password_retry.sql
Labels: kind/feature, size/XXL

#21746 Fix the file service not found error when CN flushes objects.
  pkg/objectio/ioutil/sinker.go
  pkg/sql/colexec/deletion/deletion_test.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/insert/insert.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/s3util.go
  pkg/sql/colexec/s3util_test.go
  pkg/sql/colexec/types.go
  pkg/sql/compile/scope.go
  pkg/vm/engine/disttae/transfer.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/M

#21627 Improve the performance of the apply deletes in the workspace writes.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/readutil/datasource.go
  pkg/vm/engine/readutil/relation_data_test.go
  pkg/vm/engine/readutil/tombstone_data.go
  pkg/vm/engine/readutil/tombstone_data_test.go
Labels: size/L, kind/enhancement, Review effort 3/5

#21747 [opt] improve join order and enable runtime filter for fulltext UPDATE
  pkg/sql/plan/build_dml_util.go
Labels: size/S, kind/enhancement

#21732 Fix merge alloc 2.1
  pkg/common/mpool/mpool.go
  pkg/vm/engine/tae/mergesort/merger.go
Labels: size/S

#21674 [opt] convert BETWEEN filter to PREFIX_BETWEEN on composite keys
  pkg/sql/plan/expr_opt.go
  pkg/sql/plan/stats.go
  pkg/sql/plan/utils.go
  test/distributed/cases/optimizer/blockfilter.result
Labels: size/S, kind/enhancement

#21753 fix the duplicated entry issue caused by merging deletion on the uncommitted objects.
  pkg/vm/engine/disttae/txn_table.go
Labels: kind/bug, size/XS

#21757 fix duplicate pk due to big delete
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
Labels: size/S

#21756 fix duplicate pk due to big delete
  pkg/sql/colexec/multi_update/multi_update.go
  pkg/sql/colexec/multi_update/s3writer.go
Labels: kind/bug, size/S

#21749 [#21676]revert commid 6fbbd
  pkg/frontend/test/engine_mock.go
  pkg/pb/statsinfo/statsinfo.pb.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtail_consumer.go
  pkg/vm/engine/disttae/logtail_consumer_test.go
  pkg/vm/engine/disttae/mo_table_stats.go
  pkg/vm/engine/disttae/stats.go
  pkg/vm/engine/disttae/stats_test.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/entire_engine.go
  pkg/vm/engine/entire_engine_test.go
  pkg/vm/engine/memoryengine/binded.go
  pkg/vm/engine/memoryengine/engine.go
  pkg/vm/engine/tae/logtail/service/server.go
  pkg/vm/engine/test/change_handle_test.go
  pkg/vm/engine/test/disttae_engine_test.go
  pkg/vm/engine/test/partition_state_test.go
  pkg/vm/engine/test/reader_test.go
  pkg/vm/engine/test/testutil/disttae_engine.go
  pkg/vm/engine/types.go
  proto/statsinfo.proto
Labels: size/XL

#21755 Fix cdc mo to mo invalid connection
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/types.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/M

#21752 chore: remove bvt test tag #14293
  test/distributed/cases/dml/show/database_statistics.sql
  test/distributed/cases/dml/show/show4.result
  test/distributed/cases/dml/show/show4.sql
  test/distributed/cases/system/system.sql
Labels: size/S, kind/test-ci, Review effort 1/5

#21751 fix txn mistakenly aborted duo to deadlock
  pkg/common/moerr/cause.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/pb/lock/lock.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: size/L

#21761 retry when remote lock i/o timeout
  pkg/lockservice/lock_table_remote.go
  pkg/lockservice/lock_table_remote_test.go
  pkg/lockservice/service_test.go
Labels: size/S

#21765 Fix mo_cdc_task does not exist
  pkg/frontend/cdc_dao.go
  test/distributed/cases/dml/show/cdc.result
  test/distributed/cases/dml/show/cdc.test
Labels: kind/bug, size/S

#21764 sync dynamic link fix to 2.1-dev
  .gitignore
  Makefile
  optools/images/Dockerfile
Labels: kind/bug, size/S

#21766 small updates for the workspace.
  pkg/vm/engine/disttae/local_disttae_datasource.go
  pkg/vm/engine/readutil/datasource.go
Labels: size/S, kind/enhancement

#21750 fix txn mistakenly aborted duo to deadlock
  pkg/common/moerr/cause.go
  pkg/lockservice/deadlock.go
  pkg/lockservice/deadlock_test.go
  pkg/lockservice/lock.go
  pkg/lockservice/log.go
  pkg/lockservice/rpc.go
  pkg/lockservice/rpc_test.go
  pkg/lockservice/service.go
  pkg/lockservice/service_observability.go
  pkg/lockservice/service_remote.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
  pkg/pb/lock/lock.go
  pkg/pb/lock/lock.pb.go
  proto/lock.proto
Labels: size/L

#21770 remove bvt tag
  test/distributed/cases/dtype/text_blob.result
  test/distributed/cases/dtype/text_blob.sql
Labels: size/XS, kind/test-ci

#21725 clean some code in the workspace.
  pkg/container/batch/batch.go
  pkg/container/types/rowid.go
  pkg/container/types/types.go
  pkg/sql/colexec/cn_segment_map.go
  pkg/sql/colexec/deletion/deletion.go
  pkg/sql/colexec/deletion/types.go
  pkg/sql/colexec/mergedelete/mergedelete_test.go
  pkg/sql/colexec/multi_update/s3writer_delegate.go
  pkg/sql/colexec/server.go
  pkg/sql/colexec/types.go
  pkg/vm/engine/disttae/txn.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_test.go
  pkg/vm/engine/disttae/types.go
  pkg/vm/engine/test/workspace_test.go
Labels: size/L, kind/enhancement

#21776 fix bug: panic in order by uuid column
  pkg/partition/partition.go
  test/distributed/cases/dtype/uuid.result
  test/distributed/cases/dtype/uuid.sql
Labels: kind/bug, size/S

#21775 fix bug: panic in order by uuid column
  pkg/partition/partition.go
  test/distributed/cases/dtype/uuid.result
  test/distributed/cases/dtype/uuid.sql
Labels: kind/bug, size/S

#21781 to 2.1: Fix the block filter not work when `where sortKey = ''`
  pkg/vm/engine/readutil/expr_util.go
Labels: kind/bug, size/S

#21780 improve txn leak checker
  pkg/txn/client/leak_checker.go
  pkg/txn/client/leak_checker_test.go
Labels: size/S, kind/enhancement, Review effort 2/5

#21777 Support changing the product name into OmniFabric
  pkg/config/configuration.go
  pkg/frontend/variables.go
Labels: size/S, Review effort 2/5

#21783 Remove the wrong sql
  test/distributed/cases/function/func_make_date.result
  test/distributed/cases/function/func_make_date.sql
Labels: size/XS, Review effort 1/5

#21787 Fix TestPitrMeta
  pkg/vm/engine/tae/db/test/db_test.go
Labels: size/XS, kind/test-ci
