Repository matrixorigin/matrixone, pull requests merged in 2025-06, with the labels that each got.

#21953 For 2.2: fix panic
  pkg/container/types/binary.go
  pkg/sql/plan/function/agg/bit_and.go
  pkg/sql/plan/function/agg/bit_and_test.go
  test/distributed/cases/function/func_aggr_bitwise.result
Labels: kind/bug, size/M, Review effort 2/5

#21954 fix 21952 for 2.2-dev
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S, Review effort 2/5

#21943 update median
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/median.go
  pkg/sql/colexec/aggexec/median_test.go
  pkg/sql/colexec/aggexec/tool.go
Labels: kind/bug, size/L, Review effort 3/5

#21947 fix error handling of merge settings 2.2
  pkg/sql/compile/ddl.go
  pkg/vm/engine/tae/mergesort/task.go
Labels: kind/bug, size/S, Review effort 1/5

#21957 fix 21952 for main
  pkg/sql/plan/function/func_mo.go
Labels: kind/bug, size/S, Review effort 2/5

#21946 fix error handling of merge settings
  pkg/sql/compile/ddl.go
  pkg/vm/engine/tae/mergesort/task.go
Labels: kind/bug, size/S, Review effort 1/5

#21958 fix bug: user can create user without permission
  pkg/frontend/authenticate2.go
  test/distributed/cases/tenant/privilege/create_user_default_role.result
  test/distributed/cases/tenant/privilege/create_user_default_role.sql
Labels: kind/bug, size/S, Review effort 2/5

#21959 update median
  pkg/sql/colexec/aggexec/aggFrame_test.go
  pkg/sql/colexec/aggexec/median.go
  pkg/sql/colexec/aggexec/median_test.go
  pkg/sql/colexec/aggexec/tool.go
Labels: kind/bug, size/L, Review effort 3/5

#21965 to 2.2: fix data race in buildTablePairFromCache
  pkg/vm/engine/disttae/mo_table_stats.go
Labels: kind/bug, size/S, Review effort 2/5

#21969 update cdc sinker
  pkg/cdc/sinker.go
Labels: size/S, kind/enhancement, Review effort 2/5

#21971 disable runtime filter on fulltext DML temporarily
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
Labels: kind/bug, size/S, Review effort 2/5

#21966 CI: modify dockerfile (#21935)
  optools/images/Dockerfile
  optools/images/README.md
Labels: size/S, kind/test-ci, Review effort 2/5

#21346 make create index support partition
  pkg/defines/type.go
  pkg/frontend/test/engine_mock.go
  pkg/logservice/hakeeper_client.go
  pkg/partitionservice/service.go
  pkg/partitionservice/service_test.go
  pkg/partitionservice/types.go
  pkg/pb/api/api.pb.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/alter_test.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/compile/ddl_index_algo.go
  pkg/sql/compile/ddl_test.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/sql_executor.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/features/table_feature.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/function/ctl/cmd_table_extra.go
  pkg/sql/plan/function/ctl/types.go
  pkg/tests/features/table_features_test.go
  pkg/tests/partition/create_index_test.go
  pkg/tests/partition/partition_test.go
  pkg/tests/testutils/test_utils.go
  pkg/vm/engine/disttae/cache/catalog.go
  pkg/vm/engine/disttae/cache/types.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/disttae/txn_table.go
  pkg/vm/engine/disttae/txn_table_delegate.go
  pkg/vm/engine/disttae/txn_table_partition.go
  pkg/vm/engine/memoryengine/table.go
  pkg/vm/engine/types.go
  proto/api.proto
  proto/plan.proto
  test/distributed/cases/prepare/prepare.result
  test/distributed/cases/prepare/prepare.test
Labels: kind/feature, size/XL

#21974 fix data race in `ReConnectionBackOff`.
  pkg/util/export/etl/db/db_holder.go
Labels: kind/bug, size/S, Review effort 1/5

#21990 Fix changes handle
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/S, Review effort 2/5

#21991 fix changes handle
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/S, Review effort 2/5

#21994 fix changes handle
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, Review effort 3/5

#21998 Pick delete hung fix to 2.1
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, Review effort 2/5

#21995 fix txn unlock fatal
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/service.go
  pkg/lockservice/service_test.go
Labels: size/M, Review effort 4/5

#21989 offline tool to handle checkpoint meta file
  pkg/objectio/fs.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/checkpoint/types.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/rpc/inspect_test.go
  pkg/vm/engine/tae/rpc/tool.go
Labels: kind/feature, size/L, Review effort 4/5

#21984 change some interface of CompilerContext
  pkg/frontend/compiler_context.go
  pkg/frontend/connector.go
  pkg/frontend/mysql_cmd_executor.go
  pkg/frontend/mysql_cmd_executor_test.go
  pkg/frontend/session_test.go
  pkg/sql/compile/sql_executor_context.go
  pkg/sql/plan/Makefile
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/apply_indices_master.go
  pkg/sql/plan/bind_delete.go
  pkg/sql/plan/bind_insert.go
  pkg/sql/plan/bind_replace.go
  pkg/sql/plan/bind_update.go
  pkg/sql/plan/build_alter_add_column.go
  pkg/sql/plan/build_alter_modify_column.go
  pkg/sql/plan/build_alter_table.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_ddl.go
  pkg/sql/plan/build_ddl_test.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/build_insert.go
  pkg/sql/plan/build_show.go
  pkg/sql/plan/build_show_util.go
  pkg/sql/plan/dml_context.go
  pkg/sql/plan/mock.go
  pkg/sql/plan/opt_misc.go
  pkg/sql/plan/query_builder.go
  pkg/sql/plan/query_builder_test.go
  pkg/sql/plan/types.go
  pkg/sql/plan/types_mock_test.go
  pkg/vm/engine/disttae/txn_database.go
  pkg/vm/engine/memoryengine/compiler_context.go
  test/distributed/cases/function/table_func_metadata_scan.result
  test/distributed/cases/function/table_func_metadata_scan_idx_tb.result
  test/distributed/cases/optimistic/transaction_enhance.result
  test/distributed/cases/pessimistic_transaction/transaction_enhance.result
  test/distributed/cases/publication_subscription/publish_subscribe.result
  test/distributed/cases/snapshot/cluster_level_snapshot_restore_pubsub.result
  test/distributed/cases/snapshot/snapshotRead.result
  test/distributed/cases/snapshot/sys_restore_pubsub_to_sys_account.result
  test/distributed/cases/tenant/pub_sub.result
Labels: size/L, kind/refactor, Review effort 4/5

#22003 fix data race
  pkg/sql/colexec/table_function/fulltext.go
  pkg/sql/colexec/table_function/types.go
  pkg/sql/compile/analyze_module.go
  pkg/sql/compile/analyze_module_test.go
  pkg/sql/compile/operator.go
  pkg/vm/process/operator_analyzer.go
Labels: kind/bug, size/S, Review effort 4/5

#22007 fix allocate id - main
  pkg/logservice/hakeeper_client.go
  pkg/logservice/hakeeper_client_test.go
Labels: kind/bug, size/M, Review effort 3/5

#22010 fix TestBuildMulti race
  pkg/vectorindex/hnsw/build_test.go
Labels: kind/bug, size/S, Review effort 2/5

#22014 checkpoint tool II
  pkg/vm/engine/ckputil/meta.go
  pkg/vm/engine/ckputil/reader_test.go
  pkg/vm/engine/tae/db/checkpoint/entry.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/ckp_reader.go
  pkg/vm/engine/tae/rpc/inspect_test.go
  pkg/vm/engine/tae/rpc/tool.go
Labels: kind/feature, size/M, Review effort 3/5

#21845 Update transfer page
  cmd/mo-service/config.go
  cmd/mo-service/config_test.go
  pkg/defines/const.go
  pkg/embed/config.go
  pkg/embed/config_test.go
  pkg/fileservice/app_fs.go
  pkg/fileservice/config.go
  pkg/fileservice/tmp_fs.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/db/db.go
  pkg/vm/engine/tae/db/dbutils/runtime.go
  pkg/vm/engine/tae/db/open.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/model/pages.go
  pkg/vm/engine/tae/model/transfer_test.go
  pkg/vm/engine/tae/options/options.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/tables/txnentries/flushTableTail.go
  pkg/vm/engine/tae/tables/txnentries/mergeobjects.go
Labels: kind/feature, size/L

#22013 add debug log
  pkg/taskservice/mysql_task_storage.go
Labels: kind/bug, size/XS, Review effort 1/5

#22021 Fix PopulateBinaryFuse8 error panic (#22019)
  pkg/vm/engine/tae/index/filter.go
Labels: kind/bug, size/S, Review effort 3/5

#22025 [fix] put non-PK runtime filter in Filter operator
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/apply_indices.go
  pkg/sql/plan/build_constraint_util.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/runtime_filter.go
  pkg/sql/plan/utils.go
  pkg/sql/plan/utils_test.go
  proto/plan.proto
Labels: kind/bug, size/S, Review effort 4/5

#21821 add debug tool
  pkg/objectio/injects.go
  pkg/objectio/name.go
  pkg/objectio/writer.go
  pkg/tnservice/cfg.go
  pkg/tnservice/factory.go
  pkg/vm/engine/tae/catalog/catalogreplay.go
  pkg/vm/engine/tae/catalog/schema.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/data/object.go
  pkg/vm/engine/tae/options/types.go
  pkg/vm/engine/tae/rpc/apply_table_data.go
  pkg/vm/engine/tae/rpc/dump_table.go
  pkg/vm/engine/tae/rpc/inspect.go
  pkg/vm/engine/tae/rpc/inspect_test.go
  pkg/vm/engine/tae/tables/aobj.go
  pkg/vm/engine/tae/tables/appender.go
  pkg/vm/engine/tae/tables/mnode.go
  pkg/vm/engine/tae/tables/obj.go
Labels: kind/feature, size/XL

#22029 fix merge log
  pkg/vm/engine/tae/db/merge/statOverlap.go
Labels: size/XS, kind/test-ci, Review effort 1/5

#22028 show create partition table
  pkg/partitionservice/service.go
  pkg/sql/plan/build_show_util.go
  pkg/tests/partition/create_hash_test.go
Labels: size/M, Review effort 3/5

#22030 fix lock hung and remove big log lock
  pkg/lockservice/lock_table_allocator.go
  pkg/lockservice/lock_table_allocator_test.go
  pkg/lockservice/lock_table_keeper.go
  pkg/lockservice/log.go
  pkg/sql/colexec/lockop/lock_op.go
Labels: size/S, Review effort 3/5

#22040 [taskservice] bug: add Created condition when filter tasks
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/XS, Review effort 2/5

#22039 [taskservice] bug: add Created condition when filter tasks
  pkg/taskservice/task_service_cron.go
Labels: kind/bug, size/XS, Review effort 2/5

#22032 cdc support truncate
  pkg/cdc/reader.go
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/cdc/table_scanner.go
  pkg/cdc/types.go
  pkg/cdc/types_test.go
  pkg/frontend/cdc_exector.go
  pkg/frontend/cdc_test.go
Labels: kind/bug, size/M, Review effort 4/5

#22018 remove some debug log for gc
  pkg/vm/engine/tae/db/checkpoint/replay.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: size/M, kind/enhancement, Review effort 3/5

#22043 reduce memory usage and IO in DML plan with vector index
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/M, Review effort 4/5

#22044 reduce memory usage and IO in DML plan with vector index
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/M, Review effort 4/5

#22046 ast string with quote identifier
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/format.go
  pkg/sql/parsers/tree/identifier.go
  pkg/sql/parsers/tree/table_name.go
Labels: size/S, Review effort 2/5

#22045 make runtime filter work on non-PK column
  pkg/pb/pipeline/pipeline.pb.go
  pkg/sql/colexec/filter/filter.go
  pkg/sql/colexec/filter/filter_test.go
  pkg/sql/colexec/filter/types.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/operator.go
  pkg/sql/compile/remoterun.go
  pkg/sql/compile/remoterun_test.go
  pkg/sql/compile/scope.go
  pkg/sql/plan/build_dml_util.go
  pkg/sql/plan/types_mock_test.go
  proto/pipeline.proto
Labels: size/M, kind/enhancement, Review effort 4/5

#22048 db and table filter on scanloop in cdc
  pkg/cdc/sql_builder.go
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/frontend/cdc_exector.go
  pkg/frontend/cdc_test.go
Labels: kind/feature, size/M, Review effort 3/5

#22051 enable CHAR_LENGTH to accept TEXT
  pkg/sql/plan/function/list_builtIn.go
Labels: kind/bug, size/S, Review effort 1/5

#22050 enable CHAR_LENGTH to accept TEXT
  pkg/sql/plan/function/list_builtIn.go
Labels: kind/bug, size/S, Review effort 1/5

#22057 fix shuffle join for recursive cte
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/shuffle_test.go
  test/distributed/cases/recursive_cte/recursive_cte.result
  test/distributed/cases/recursive_cte/recursive_cte.sql
Labels: size/S, Review effort 2/5

#22056 fix shuffle join for recursive cte
  pkg/sql/colexec/shuffle/shuffle.go
  pkg/sql/colexec/shuffle/shuffle_test.go
  test/distributed/cases/recursive_cte/recursive_cte.result
  test/distributed/cases/recursive_cte/recursive_cte.sql
Labels: size/S, Review effort 2/5

#22023 bug fix index cache return index destroyed error when NewAlgo in one thread and Remove by another thread
  pkg/vectorindex/cache/cache.go
  pkg/vectorindex/cache/cache_test.go
Labels: kind/bug, size/M, Review effort 4/5

#22065 disable pushdown limit for 2.2-dev
  pkg/sql/plan/apply_indices_fulltext.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext_bm25.result
  test/distributed/cases/fulltext/fulltext_bm25.sql
Labels: kind/bug, size/S

#22047 make alter table index support partition
  pkg/partitionservice/service_hash.go
  pkg/partitionservice/service_hash_test.go
  pkg/partitionservice/service_list.go
  pkg/partitionservice/service_list_test.go
  pkg/partitionservice/service_range.go
  pkg/partitionservice/service_range_test.go
  pkg/partitionservice/storage.go
  pkg/partitionservice/storage_test.go
  pkg/pb/plan/plan.pb.go
  pkg/sql/compile/alter.go
  pkg/sql/compile/compile.go
  pkg/sql/compile/ddl.go
  pkg/sql/parsers/dialect/mysql/mysql_sql_test.go
  pkg/sql/parsers/tree/format.go
  pkg/sql/plan/build_ddl.go
  pkg/tests/partition/alter_table_test.go
  pkg/tests/partition/create_hash_test.go
  pkg/vm/engine/disttae/txn_table_partition.go
  proto/plan.proto
Labels: kind/feature, size/L, Review effort 4/5

#22070 fix error checking in rpc handler
  pkg/vm/engine/tae/rpc/handle.go
Labels: kind/bug, size/S

#22073 fix transfer tombstone failed when drop pitr bvt.
  pkg/container/vector/search.go
  pkg/vm/engine/readutil/filter_test.go
  pkg/vm/engine/readutil/pk_filter.go
  pkg/vm/engine/readutil/pk_filter_mem.go
  pkg/vm/engine/readutil/pk_filter_mem_test.go
Labels: kind/bug, size/M
