Repository matrixorigin/matrixone, pull requests merged in 2025-09, with the labels that each got.

#22459 Add Force GC& GC Details& GC Verify&Fix bug
  pkg/cnservice/server_query.go
  pkg/pb/query/query.pb.go
  pkg/queryservice/client/query_client.go
  pkg/sql/plan/function/ctl/cmd_disk_cleaner.go
  pkg/tnservice/factory.go
  pkg/tnservice/store.go
  pkg/txn/client/client.go
  pkg/txn/storage/tae/storage.go
  pkg/txn/storage/tae/storage_debug.go
  pkg/vm/engine/cmd_util/type.go
  pkg/vm/engine/tae/db/gc/v3/check.go
  pkg/vm/engine/tae/db/gc/v3/checkpoint.go
  pkg/vm/engine/tae/db/gc/v3/cleaner_test.go
  pkg/vm/engine/tae/db/gc/v3/diskcleaner.go
  pkg/vm/engine/tae/db/gc/v3/exec_v1.go
  pkg/vm/engine/tae/db/gc/v3/merge.go
  pkg/vm/engine/tae/db/gc/v3/mock_cleaner.go
  pkg/vm/engine/tae/db/gc/v3/types.go
  pkg/vm/engine/tae/db/gc/v3/window.go
  pkg/vm/engine/tae/db/test/db_test.go
  pkg/vm/engine/tae/iface/rpchandle/handler.go
  pkg/vm/engine/tae/logtail/snapshot.go
  pkg/vm/engine/tae/rpc/handle.go
  pkg/vm/engine/tae/rpc/handle_debug.go
  pkg/vm/engine/test/testutil/tae_engine.go
  proto/query.proto
  test/distributed/cases/dml/show/show.test
  test/distributed/cases/save_query_result/save_query_result.sql
  test/distributed/cases/tenant/tenant.test
  test/distributed/cases/util/check.result
  test/distributed/cases/util/check.sql
Labels: kind/bug, kind/feature, size/L, kind/enhancement, Review effort 4/5

#22457 fix iscp
  pkg/iscp/data_retriever.go
  pkg/iscp/executor.go
  pkg/iscp/iteration.go
  pkg/iscp/mock_consumer.go
  pkg/iscp/types.go
  pkg/iscp/watermark_updater.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/L, Review effort 3/5

#22469 reduce insert batch to prevent create hnsw index from oom
  pkg/vectorindex/hnsw/build.go
Labels: kind/bug, size/XS, Review effort 1/5

#22468 reduce insert batch to prevent create hnsw index from oom
  pkg/vectorindex/hnsw/build.go
Labels: kind/bug, size/XS, Review effort 2/5

#22485 Fix iscp bvt crashed
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/XS, Review effort 2/5

#22487 Fix iscp data race
  pkg/vm/engine/tae/logtail/snapshot.go
Labels: kind/bug, size/S, Review effort 2/5

#22479 Collect L0 objects by zonemap start value
  pkg/vm/engine/tae/db/merge/statLayerZero.go
  pkg/vm/engine/tae/db/merge/statOverlap.go
Labels: size/S, kind/enhancement, Review effort 2/5

#22490 Fix partition changes handle
  pkg/cdc/reader.go
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/iscp/consumer_entry.go
  pkg/iscp/executor.go
  pkg/iscp/iteration.go
  pkg/iscp/mock_consumer.go
  pkg/iscp/watermark_updater.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/db_test.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/L, Review effort 4/5

#22491 Fix partition changes handle
  pkg/cdc/reader.go
  pkg/cdc/table_scanner.go
  pkg/cdc/table_scanner_test.go
  pkg/vm/engine/disttae/change_handle.go
  pkg/vm/engine/disttae/db.go
  pkg/vm/engine/disttae/engine.go
  pkg/vm/engine/disttae/logtailreplay/change_handle.go
  pkg/vm/engine/disttae/logtailreplay/partition_state.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/bug, size/L, Review effort 4/5

#22495 fix dup in data clone
  pkg/vm/engine/disttae/table_meta_reader.go
Labels: kind/bug, size/M, Review effort 3/5

#22477 Change the right join to inner join in fulltext and ivf deletion plan
  pkg/sql/plan/build_dml_util.go
  test/distributed/cases/fulltext/fulltext.result
  test/distributed/cases/fulltext/fulltext.sql
Labels: size/S, Review effort 2/5

#22509 avoid redundant parsing of vecf32/vecf64 literals
  pkg/pb/plan/plan.pb.go
  pkg/pb/task/task.pb.go
  pkg/sql/colexec/evalExpression.go
  pkg/sql/plan/deepcopy.go
  pkg/sql/plan/rule/constant_fold.go
  proto/plan.proto
Labels: size/S, kind/enhancement, Review effort 2/5

#22514 fix runtime filter message tag
  pkg/sql/plan/build_dml_util.go
Labels: kind/bug, size/XS, Review effort 1/5

#22526 iscp update table name
  pkg/iscp/iteration.go
  pkg/iscp/watermark_updater.go
  pkg/vm/engine/test/change_handle_test.go
Labels: kind/feature, size/M, Review effort 3/5

#22534 fix leak of waiter
  pkg/lockservice/lock_table_local.go
  pkg/lockservice/service_test.go
  pkg/lockservice/txn.go
Labels: size/S, Review effort 2/5

#22536 change result score from l2sq to l2
  pkg/vectorindex/hnsw/search.go
  pkg/vectorindex/ivfflat/search.go
Labels: kind/bug, size/S, Review effort 2/5

#22528 update create sql
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/sql/plan/build_show_util.go
Labels: kind/bug, size/M, Review effort 2/5

#22540 update create sql
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
  pkg/sql/plan/build_show_util.go
Labels: kind/bug, size/M, Review effort 3/5

#22542 2.2 dev convert l2sq score tp l2 score for hnsw and ivfflat index
  pkg/vectorindex/hnsw/search.go
  pkg/vectorindex/ivfflat/search.go
Labels: kind/bug, size/S, Review effort 2/5

#22552 to 3.0: should ignore the nonexistence err of the foreign table when dropping the database and table
  pkg/sql/compile/ddl.go
  test/distributed/cases/foreign_key/disable_foreign_key_check.result
  test/distributed/cases/foreign_key/disable_foreign_key_check.sql
Labels: kind/bug, size/M, Review effort 2/5, queued

#22572 fix cdc create sql
  pkg/cdc/sinker.go
  pkg/cdc/sinker_test.go
Labels: kind/bug, size/XS, Review effort 2/5, queued

#22570 Align the default field separators for the export table and load data.
  pkg/sql/colexec/external/types.go
  pkg/sql/parsers/tree/update.go
  pkg/sql/plan/bind_load.go
  test/distributed/cases/load_data/load_data.result
  test/distributed/cases/load_data/load_data.sql
Labels: kind/bug, size/S, Review effort 2/5, queued

#22577 Add vector cases
  test/distributed/cases/vector/vector_ivf.result
  test/distributed/cases/vector/vector_ivf.sql
  test/distributed/resources/vector/ca_specify_answer_dataset.csv
Labels: kind/bug, size/L, Review effort 2/5, queued
